### ISSUE TITLE
Query : Telegraf to Icinga2

### ISSUE THREAD

**Issue by rahulramani** [telegraf/telegraf#1]
Hi,

Is there any way i can collect the metrics using Telegraf and pass it to Icinga2 using Icinga2 API call.

Thanks
Rahul

**Comment by dotcypress** [comment]
Hi,

Sure you can, but what metrics you want to collect?

**Comment by rahulramani** [comment]
Let say i have an Aerospike server and all the metrics which telegraf agent can collect for Aerospike, i would like to monitor all those in Icinga. (high water mark, stop writes , etc..)

**Comment by dotcypress** [comment]
Seems like i don't understand what exactly you need :)
Just add simple middleware to collect metrics and save it.
```
var app = new Telegraf(process.env.BOT_TOKEN, {polling: true})

app.use(function * () {
  // save stats
})
```

PS I will add some documentation soon
