### ISSUE TITLE
Question/Best Practice: How would you handle this?

### ISSUE THREAD

**Issue by Zweer** [telegraf/telegraf#10]
Hi,

I'm kinda new to Telegram Bot and I'm trying to figure out which is the best library. I've found this one after few other experiences and right now it is the best one (thanks a lot for you effort!!).

But here comes my question: how would you solve my problem?

I'm doing a telegram interface for a web REST api.
**My idea is**: when someone types /start, the bot asks for the email address and then asks me (or better, the admin telegram profile) if that person can be enabled to use the bot. I answer to the enabling question and then a record is added to the mysql database to specify that the couple "email address - telegramId" is allowed.
**My current solution**: 
```javascript
// routes.js

app.command('start', startHandler);
app.hears(/<email regex>/, startEmailHandler);
app.action(/enable :userId :telegramId/, startEnableHandler); // the "regex" is express.js-style
```

```javascript
// start.js

function startHandler(ctx) {
  // this.session.started = true;
  // sendMessage("Hi, type your email address to be enabled");
}

function startEmailHandler(ctx) {
  // if (!this.session.started) return;
  // const email
  // delete this.session.started;
  // sendMessage(adminId, "Hey, ${email} wants to be enabled, is it ok?", keyboardWithYesAndNo);
}

function startEnableHandler(ctx) {
  // const userId
  // const telegramId
  // user.telegramId = telegramId;
  // sendMessage(telegramId, "You are enabled");
  // sendMessage(adminId, "Done");
}
```

This approach, in my opinion, fails for two reasons:
- I have to handle (and then exit because there's no session) all the messages with an email address in it, isn't it possible to register and then de-register the handler?
- I have to handle all the enable callback_query (security constraint) and, here is the bad part, my userId is a uuid.v4, so I exceed the 64byte limit of telegram callback query...

While the first problem isn't so bad, the second one is terrible: I have to use sessions or a shorter id/hash, with all the concurrency/security problems of both solutions.

With another library (that I DO NOT want to use because it fails in thousands of other use cases) I could register callback_query handlers "on the fly" inside the "startEmailHandler" so that I can use a "user" variable in it, and then de-register it, so that, even if I press the "YES" button more than once, my DB isn't queried...

Sorry for the long post, but I don't know if I am missing something, if there is another way to think in a more "telegram style" or another way to do what I need...

Thanks a lot!!!
Zwe

**Comment by dotcypress** [comment]
Hey Zwe!

Thank you for feedback. Much appreciated.

Approach with registration callback_query handlers "on the fly" isn't ok. For example, graceful restart is't possible with in-memory handlers.

Related to your problem: you might use db for storing 'authorization' task details.
```
app.action('enable', startEnableHandler)

function startEmailHandler(ctx) {
  // if (!this.session.started) return; // BTW: You can filter this on top level ;)
  // const email
  // delete this.session.started;
  // messageId = sendMessage(adminId, "Hey, ${email} wants to be enabled, is it ok?", keyboardWithYesAndNo);
  // db.save(messageId, { user, email, etc })
}

function startEnableHandler(ctx) {
  // data = db.get(ctx.message.id)  
  // const userId = data...
  // const telegramId = data...
  // user.telegramId = telegramId;
  // sendMessage(telegramId, "You are enabled");
  // sendMessage(adminId, "Done");
}

```

This library is inspired by (koa)(http://koajs.com/) and the main feature of Telegraf is middleware/cascading. Now you can build powerful bots from tiny blocks. Check out [Telegraf middlewares](https://github.com/telegraf) for examples.

I recommend you read samples from (telegraf-flow)(https://github.com/telegraf/telegraf-flow), it's  experimental middleware for complex chatbots. We use 'scene' abstraction for handling user conversation flow and structure of our bots stays simple.

**Comment by Zweer** [comment]
Hey,

thanks, the "messageId" idea is really good, haven't thought about it!!!
In this way it a much more clean!!!

Good idea the Flow lib, I'm gonna have a look!!!

Thanks a lot!
