### ISSUE TITLE
ctx.InlineQueryResultVenue is not a function and telegram.InlineQueryResultVenue is not a function

### ISSUE THREAD

**Issue by faneyy** [telegraf/telegraf#1005]
`telegram.InlineQueryResultVenue(fromId,sug.geometry.coordinates[1],sug.geometry.coordinates[0],sug.properties.name,sug.properties.district.name);
`
* Telegraf.js Version: : "^3.38.0",
* Node.js Version: v12.14.0.
* Operating System: Windows 10

## Expected Behavior

List the locations or venue results with inline query. with provided parameter such as inline query id, coordinates (long,lat), title, address.

## Current Behavior

throws an error saying that "InlineQueryResultVenue" is not a function

## Failure Information (for bugs)

Error: catch nullTypeError: telegram.InlineQueryResultVenue is not a function
    at C:\xampp\htdocs\telegram\index.js:70:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\xampp\htdocs\telegram\index.js:54:5
    at async Promise.all (index 0)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1: receive data with coordinates, title and addres
2. step 2: try to show results within InlineQueryResultVenue();
3. you get it...

### Failure Logs

Error: catch nullTypeError: telegram.InlineQueryResultVenue is not a function
    at C:\xampp\htdocs\telegram\index.js:70:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\xampp\htdocs\telegram\index.js:54:5
    at async Promise.all (index 0)

**Comment by Piterden** [comment]
`telegram.inlineQueryResultVenue()`

**Comment by faneyy** [comment]
> `telegram.inlineQueryResultVenue()`

`Error: telegram.inlineQueryResultVenue is not a function`

Error: catch nullTypeError: telegram.inlineQueryResultVenue is not a function
    at C:\xampp\htdocs\telegram\index.js:77:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\xampp\htdocs\telegram\index.js:61:5
    at async Promise.all (index 0)

**Comment by KnorpelSenf** [comment]
You're looking for [`answerInlineQuery`](https://core.telegram.org/bots/api#answerinlinequery) instead of `InlineQueryResultVenue`. The former is the function you need to call, the latter is the shape of the object you have to pass to it.
