### ISSUE TITLE
Doesn't switchToCurrentChatButton 

### ISSUE THREAD

**Issue by maslopop** [telegraf/telegraf#1006]
Hi, thanks first of all for this excellent library, I would like to fix some keys in my bot one of which to activate the queries ... but the code that calls the switchToCurrentChatButton does nothing but write the text in the chat of the bot, it does not prepare me the message for query

Certainly I'm wrong in something but I don't really see where.

```
  ctx.reply(it.logo, Extra.markup((markup) => {
    return markup.resize()
      .keyboard([
        markup.button(it.super, false),
        markup.switchToCurrentChatButton(it.cerca, 'cambiami', false),
      ]).resize()
  }))
```
Current behavior
![image](https://user-images.githubusercontent.com/5228900/80297308-41f07f80-8782-11ea-97c0-780052cb70fb.png)

Expected behavior 

![image](https://user-images.githubusercontent.com/5228900/80303021-ed62f980-87ad-11ea-8a7d-061ce90a8029.png)

Massimo

**Comment by YouTwitFace** [comment]
`switch_inline_query_current_chat` only works for inline keyboards.
