### ISSUE TITLE
Need help with 'node-schedule'

### ISSUE THREAD

**Issue by Kaesebrot84** [telegraf/telegraf#101]
Hi I am trying to make my bot send me a message at certain times. Therefor I want to use 'node-schedule'.

The jobs are created cron like:

```
// node-scheduler integration
const schedule = require('node-schedule');
// define cron job
var j = schedule.scheduleJob('* * * * *',function(){
  console.log('message logged every minute');
  
// send message here?

});
```
So I was wondering, how can I trigger my bot to send a message inside this 'job' without reacting to any particular action taken by a human chat member?

I could not find a suited method on the [Telegraf - API](http://telegraf.js.org/introduction.html)

Maybe there are any other, more convenient ways to achieve the task?

**Comment by dotcypress** [comment]
Hey!

For sure, you can do that.
Check following example:

```js
const { Telegram } = require('telegraf')
const schedule = require('node-schedule')

const tg = new Telegram(process.env.BOT_TOKEN)

schedule.scheduleJob('* * * * *',function(){
  tg.sendMessage(userId, message)
})
```
(Telegram help)[http://telegraf.js.org/telegram.html]

**Comment by Kaesebrot84** [comment]
Hey thanks for the quick reply!
I did this:

```
const  Telegram = require('telegraf')
const app = new Telegram('<TOKEN>')

// node-scheduler integration
const schedule = require('node-schedule');
// define cron job
var j = schedule.scheduleJob('* * * * *',function(){
  console.log('task');
  app.sendMessage('xxxxxxxxx','message');
});
```

But unfortunately I get:

> TypeError: app.sendMessage is not a function

Any idea?

**Comment by Kaesebrot84** [comment]
Got it the call should be:

`app.telegram.sendMessage('xxxxxxxxx','message');`

Thanks a lot!

**Comment by nikolayay** [comment]
Hi, is there any way i can get access to the ```ctx``` object? 
I am trying to do something like: 
```
schedule.scheduleJob('* * * * *', function() {
  ctx.reply(message)
})
```

Thanks!
