### ISSUE TITLE
telegraf/typings has no exported member ContextMessageUpdate

### ISSUE THREAD

**Issue by furmanServices** [telegraf/telegraf#1010]
## Context
Trying to export:
`export { ContextMessageUpdate } from '../../node_modules/telegraf/typings'`
Error:
Module '"../../node_modules/telegraf/typings"' has no exported member 'ContextMessageUpdate'.

The path is correct. Because I can get the interface on typings file with cmd + click combination. Vscode recognizes the path.
* Telegraf.js Version:
3.36.0
* Node.js Version:
13.8

Previously normally worked functionality, now it doesn't.

**Comment by castrorry** [comment]
Test:
export { ContextMessageUpdate } from 'telegraf';
this if is version 3.36

**Comment by gsbelarus** [comment]
Has this class been renamed to `TelegrafContext` in the latest `Telegraf` version?

**Comment by castrorry** [comment]
Yes, in version 3.38

**Comment by EugeneDraitsev** [comment]
So what I should use in 3.38 instead of
```tsx
import { ContextMessageUpdate } from 'telegraf'
```
`TelegrafContext` import doesn't work

```
import { TelegrafContext } from 'telegraf'

 Module '"../node_modules/telegraf/typings"' has no exported
 member 'TelegrafContext'. Did you mean to use 'import TelegrafContext from "../node_modules/tel
egraf/typings"' instead?
```

**Comment by wojpawlik** [comment]
```ts
import { ​Context } ​from​ ​'telegraf'
```

https://github.com/telegraf/telegraf/pull/960#discussion_r407163948
