### ISSUE TITLE
deleteMessage context don't work

### ISSUE THREAD

**Issue by hypernova7** [telegraf/telegraf#1012]
It literally does nothing

**Comment by daukadolt** [comment]
You mean ‘ctx.deleteMessage()’?

**Comment by hypernova7** [comment]
> You mean `ctx.deleteMessage()`?

Yes but it does not work :c

**Comment by daukadolt** [comment]
I still haven't gotten used to the source code, so I am not sure of how `hashtag()` function operates.

However, if it's context object that you are destructuring, then `deleteMessage()` function requires chat id to be passed as an argument.

**Comment by hypernova7** [comment]
The function does it automatically based on what I've read from the source code

**Comment by daukadolt** [comment]
Could you reference the file/line?

I'm using `ctx.deleteMessage()`, and it works just fine

**Comment by Piterden** [comment]
https://github.com/telegraf/telegraf/blob/develop/context.js#L569-L581

https://github.com/telegraf/telegraf/blob/develop/telegram.js#L339-L344

**Comment by hypernova7** [comment]
I have created a bot that when using a hashtag remove messages automatically after a specific time.  For example:

> Hello world #rm30s

This is a small example of my code.

```javascript
const addEvent = (event, field) => {
  bot.on(event, (ctx) => {
    const message = ctx[field]
    if (hashtagRegex.test(message)) {
      setTimeout(() => {
        ctx.deleteMessage()
      }, 30000);
    }
  })
}
addEvent('message', 'message')
addEvent('edited_message', 'editedMessage')
```

**Comment by daukadolt** [comment]
> I have created a bot that when using a hashtag remove messages automatically after a specific time. For example:
> 
> > Hello world #rm30s
> 
> This is a small example of my code.
> 
> ```js
> const addEvent = (event, field) => {
>   bot.on(event, (ctx) => {
>     const message = ctx[field]
>     if (hashtagRegex.test(message.text)) {
>       setTimeout(() => {
>         ctx.deleteMessage()
>       }, 30000);
>     }
>   })
> }
> addEvent('message', 'message')
> addEvent('edited_message', 'editedMessage')
> ```

Your code should work, a minor edit is needed:
`ctx.deleteMessage(ctx[field].message_id)`

**Comment by hypernova7** [comment]
The function does it automatically
See this

https://github.com/telegraf/telegraf/blob/5e171d0f8b397e9cf9659710512f74e56b2542fe/context.js#L569-L581

**Comment by Piterden** [comment]
> I have created a bot that when using a hashtag remove messages automatically after a specific time. For example:
> 
> > Hello world #rm30s
> 
> This is a small example of my code.
> 
> ```js
> const addEvent = (event, field) => {
>   bot.on(event, (ctx) => {
>     const message = ctx[field]
>     if (hashtagRegex.test(message.text)) {
>       setTimeout(() => {
>         ctx.deleteMessage()
>       }, 30000);
>     }
>   })
> }
> addEvent('message', 'message')
> addEvent('edited_message', 'editedMessage')
> ```

The `bot` is undefined in your code

**Comment by hypernova7** [comment]
@Piterden Nope

**Comment by hypernova7** [comment]
I think I'll close this, it still works with `bot.telegram.deleteMessage (chat_id, message_id)`
