### ISSUE TITLE
Suggestion: Default context type for Telegraf in Typescript

### ISSUE THREAD

**Issue by 1valdis** [telegraf/telegraf#1016]
**Is your feature request related to a problem? Please describe.**
To instantiate the bot in typescript, I have to import `TelegrafContext` along with `Telegraf`.
```typescript
import { Telegraf } from 'telegraf'
import { TelegrafContext } from 'telegraf/typings/context';

class Bot {
   // ...
   private bot: Telegraf<TelegrafContext>;
}
```

**Describe the solution you'd like**
It would be nice if I could simply:
```typescript
import { Telegraf } from 'telegraf'

class Bot {
   // ...
   private bot: Telegraf;
}
```

For this, I suggest adding adding default type to Telegraf type definition, like this:
```diff
 export declare class Telegraf<
-   TContext extends TelegrafContext
+   TContext extends TelegrafContext = TelegrafContext
 > extends Composer<TContext> {
```

**Comment by 1valdis** [comment]
@dotcypress I can submit a PR if needed. I don't know if it's necessary for one line change though.

**Comment by wabilin** [comment]
It seems that you can use:
```ts
import { Telegraf, Context } from "telegraf";
```

**Comment by wojpawlik** [comment]
Fixed: https://github.com/telegraf/telegraf/commit/a74a6e9f96a915bfb433d0c7b51a67e72ed61425#diff-85233a140a9b21f45e6b26640e727d4cR83
