### ISSUE TITLE
sendDocument thumb cannot be changed !

### ISSUE THREAD

**Issue by ajanjairam** [telegraf/telegraf#1019]
when i send a new document from my local computer using sendDocument and with thumb extra parameter, thumbnail is set up successfully.
But whenever i send documents using file_id, thumbnail is not setting up

my code:-

const Telegraf = require('telegraf');
const bot = new Telegraf('bot_token');
bot.on('document', ctx => {
    bot.telegram.sendDocument(ctx.chat.id,ctx.update.message.document.file_id, {
      thumb: {url: "url_of_thumbnail"},
      caption: "Hi"
    })
})
bot.launch();

**Comment by KnorpelSenf** [comment]
This is not a problem of `telegraf`. Telegram itself does not allow this when resending via `file_id`. Check out the official docs: https://core.telegram.org/bots/api#sending-files
