### ISSUE TITLE
How to send messages as notifications

### ISSUE THREAD

**Issue by paulbraam** [telegraf/telegraf#1022]
I'm working on a Telegram bot based on `cron`. I'm also using `MongoDB` to store user data.
There is an issue I'm struggling with for days.

```
const CronJob = require('cron').CronJob;

const job = new CronJob('*/5 * * * * *', async function() {
    const user = await db.User.findOne({chat_id: ctx.chat.id});
    await bot.telegram.sendMessage(user.chat_id, 'Hello World');
})

bot.command('launch', async (ctx) => {
  job.start()
})

bot.command('stop', async (ctx) => {
  job.stop();
})
```
Getting users from the database this way works fine for internal events when a user interacts with the bot, but it doesn't work for external events like notifications and `ctx` is missing in this case.

Please suggest how to retrieve `chat_id` from the database using `ctx` or maybe suggest another workaround without using `ctx`.

**Comment by Piterden** [comment]
For any bot the id of a private chat with any user is the same as that user id

**Comment by paulbraam** [comment]
@Piterden thanks, but I don't know how to use this id in the external event retrieving it from the database.

**Comment by KnorpelSenf** [comment]
You probably want to rely on session middleware. It allows you to store any kind of data in your database when a request comes in. You can use this to store your `chat_id`. Check out the session middleware docs: https://telegraf.js.org/#/?id=session
