### ISSUE TITLE
how use This Type of Notification when click on inline_keyboard

### ISSUE THREAD

**Issue by felipe-negri** [telegraf/telegraf#1026]
I saw this type of notification in the "You Like This" box but I couldn't find any way to use it, does anyone know how?

image link
[https://1drv.ms/u/s!AvmBjBDFCJP9i7wYun63kcZitrbNOw?e=lM3fin](url)

thanks for helping

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#answercallbackquery

**Comment by felipe-negri** [comment]
i try this but just show this the notification like this:
[https://1drv.ms/u/s!AvmBjBDFCJP9i7wZflt1_jMTTpAHVQ?e=HYfTE4](url)
a modal with a ok button :c
i use:
`await ctx.telegram.answerCbQuery(callbackId,'Vote-', true);`
and this: 
`await ctx.answerCbQuery('Vote +', true);`
but the result was the same :c

**Comment by felipe-negri** [comment]
In mobile os just like this 
[](https://1drv.ms/u/s!AvmBjBDFCJP9i7wcmGZI-E-vziINfA)

**Comment by felipe-negri** [comment]
Image

**Comment by felipe-negri** [comment]
its just use the param false xD
thanks for the help
