### ISSUE TITLE
Debounce InlineQuery

### ISSUE THREAD

**Issue by christianromeni** [telegraf/telegraf#1027]
**Is your feature request related to a problem? Please describe.**
I'm trying to get an inline query to run against an API that has quite strickt Rate Limiting Rules.. 2 calls per 10 seconds.... Now the problem is, once the user starts typing, a request is fired towards the API. Once the user stops writing his "search", the result from the server is an error code, instead of a json object.

**Describe the solution you'd like**
It would be nice to have a debounce option, to fire the event after a set time only, or present a loading result, and then load the results after the set time...?

**Describe alternatives you've considered**
I was thinking about debouncing it myself, but I dont know how... :/

**Comment by YouTwitFace** [comment]
If there is only one result and you don't need to show it until the users sends the message, you can use `chosenInlineQuery`.

**Comment by christianromeni** [comment]
There are a maximum of 25 results.. It's a search. In the example here, it's done with recepies.. So if I enter rice, it will show all recepies related to rice.
But for every letter entered:
R = request
Ri = request
Rice = request
Etc. 
That's already three requests in one second. 
I want the request to be executed after the first word or after a certain amount of time...

**Comment by YouTwitFace** [comment]
You can try using using debounce with a larger wait timeout.

**Comment by christianromeni** [comment]
Yep.. But where exactly do I debounce :(
That's my problem..

**Comment by KnorpelSenf** [comment]
Closed because of inactivity. Please reopen if you still need to solve this problem.
