### ISSUE TITLE
EditMessageCaption lacks some options

### ISSUE THREAD

**Issue by LuisMayo** [telegraf/telegraf#1028]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.13.1
* Operating System: Windows 10 1909 Education

## Expected Behavior

I should be able to set some variables to ctx.[editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption) which I'm currently unable to. More specifically, I'd want to set the `parse_mode` field

## Current Behavior

I'm only allowed to set an Inline keyboard, nothing more, at least, that's the only thing that TS will let me

**Comment by TiagoDanin** [comment]
You must put the variable in "extra parameters", example:

```js
telegram.editMessageCaption(chatId, messageId, inlineMessageId, caption, {
   parse_mode: 'Markdown'
})
```

![image](https://user-images.githubusercontent.com/5731176/80917697-2879a580-8d37-11ea-997c-4ac766f1f783.png)
[see the documentation](https://telegraf.js.org/#/?id=editmessagecaption)

**Comment by LuisMayo** [comment]
I was actually talking about the `editMessageCaption` in the context object instead on the Telegram one (Thanks for remembering me I can actually use the Telegram object!).

The typing in the method inside context doesn't allow you to specify anything but a keyboard.
``` typescript
  /**
   * Use this method to edit captions of messages sent by the bot or via the bot (for inline bots).
   * On success, if edited message is sent by the bot, the edited Message is returned, otherwise True is returned.
   * @param caption New caption of the message
   * @param markup Markup of inline keyboard
   */
  editMessageCaption(
    caption?: string,
    markup?: tt.InlineKeyboardMarkup
```
Thanks for your help.

**Comment by jfkz** [comment]
Is that planned in ts rewriting or i can fix it by myself?
