### ISSUE TITLE
Self Signed Cert

### ISSUE THREAD

**Issue by H03in** [telegraf/telegraf#103]
`how` to upload my public key for telegram
im using SSL
its my code but doesn't work :

```js
const Telegraf = require('telegraf')
const fs = require('fs')

const app = new Telegraf('(my bot token)')

// Start https webhook
app.startWebhook('/(my secret path)', null, 3000)

// Set telegram webhook
app.telegram.setWebhook('https://www.(myhost).com/(my secret path)', {
  content: 'public.pem'
})

app.catch((err) => {
  console.log('Ooops', err)
})

app.on('p', (ctx) =>
{
    ctx.reply('received!!')
})
```

i think there is some thing wrong with uploading public.pem

**Comment by dotcypress** [comment]
Hey.

Could you check webhook info?
`$ curl https://api.telegram.org/bot%BOT_TOKEN%/getWebhookInfo`

And i see tricky part in your example:
```js

app.on('p', (ctx) =>
{
    ctx.reply('received!!')
})

// Right usage
app.on('message', (ctx) =>
{
    ctx.reply('received!!')
})
```

**Comment by H03in** [comment]
tanx for your response

it was in getWebHook error :

`"last_error_message":"SSL error {337047686, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}"

**Comment by dotcypress** [comment]
@H03in as i see from error message, i trying to use invalid certificate file.

**Comment by vcheckzen** [comment]
I meet the same problem and I've solved it. If you use a none-self-signed certificate, the WebhookInfo should be as follows, the `has_custom_certificate` should be `false` or you may edit your code. Now check it.

https://api.telegram.org/bot[TOKEN]/getWebhookInfo

```json
{"ok":true,"result":{"url":"https://example.com","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}
```
