### ISSUE TITLE
App quietly quits when async call to Mongo is awaited in middleware

### ISSUE THREAD

**Issue by daukadolt** [telegraf/telegraf#1030]
I am trying to fetch user from MongoDB using Mongoose async call:

```
const getUserInfo = async (ctx, next) => {
    ctx.state.user = await User.findOne({ chat_id: chatId });
    next();
};

bot.use(getUserInfo);

bot.start((ctx) => {
    ctx.reply(`Welcome ${ctx.state.user}`);
});
```

Setup:

* Telegraf.js Version: ^3.38.0
* Node.js Version: v12.16.3
* Operating System: MacOS Catalina version 10.15.1 (19B88)

## Expected Behavior

"Welcome null" message since no users are present

## Current Behavior

Node app just quits quietly with no logs in the terminal

Changing the code to:
```
const getUserInfo = async (ctx, next) => {
    ctx.state.user = 'Test';
    next();
};
```
results in a perfectly working bot, which keeps replying "Welcome Test"

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the code at the top of the issue

### Failure Logs

No logs

**Comment by Piterden** [comment]
What does `ctx.state` mean?

**Comment by daukadolt** [comment]
> What does `ctx.state` mean?

I followed an example [here](https://telegraf.js.org/#/?id=state).

I believe that I've figured out the issue, and it is very dumb 🙈
