### ISSUE TITLE
telegram poll message vote in bot chat not exist

### ISSUE THREAD

**Issue by gartals** [telegraf/telegraf#1031]
Hi.
I'm new in telegraf bot programming .I am developing a vote bot but i have problem in it.
this is my code that send poll Message to chat:

`bot.command('poll', (ctx) =>

    ctx.replyWithPoll(
        'Your favorite math constant',
        ['x', 'e', 'π', 'φ', 'γ'],
        { allows_multiple_answers: true, is_anonymous: false }
    )
)`
 everything is OK in telegram desktop
but the poll in chat with bot doesn't have vote button but when I forward the poll to other group or chat the problem is solved just in chat page with bot I cant see vote button

**Comment by KnorpelSenf** [comment]
If it works in TDesktop, then your bot does not have an issue. Bots are independent of the used Telegram client.

I cannot reproduce your issue where a poll is displayed differently in different chats when you manually forward the message.
