### ISSUE TITLE
Leave scene without ctx

### ISSUE THREAD

**Issue by paulbraam** [telegraf/telegraf#1032]
Hi,
I'm using `cron` to send messages every day.
I don't know how to use `ctx.scene.leave()` without `ctx` once the script is completed since the `cron` event uses the `chat_id` only.

Could you please suggest how to leave the scene without `ctx`?

**Comment by castrorry** [comment]
Usually the scenes are stored in the context `ctx`, could you exemplify what solution you are using to work with scenes?

**Comment by paulbraam** [comment]
I was able to push ctx instead of chat_id out of the command sent by user into an array.
