### ISSUE TITLE
Dynamically creating inline keyboard buttons Markup Telegraf?

### ISSUE THREAD

**Issue by SergoZheludkov** [telegraf/telegraf#1033]
Hello, I am trying to send buttons to my telegram bot using the telegram bot api. For now, for creating the buttons, I have to hard code the values in the fields but lets say I want to create the inline keyboard buttons dynamically through an array and passing the array index and the array values as parameters. How should i go about it ? This is what I tried so far.

```
import Telegraf from 'telegraf';
const { Markup } = Telegraf;

const buttons = ['low', 'middle', 'high'];

const inlineKeyboard = Markup
  .inlineKeyboard(
    buttons.map((button) => {
      Markup.callbackButton(button, button);
    })
  )
    .resize()
    .extra();
```
Thanks

**Comment by Piterden** [comment]
I have dynamically created keyboard example (@chessy_bot inline) https://github.com/Piterden/chessbot/blob/master/src/keyboards/board/index.js#L24-L52

**Comment by SergoZheludkov** [comment]
Oh, yes! I did! Thanks!))

**Comment by pmcp** [comment]
Can you explain how you tackled it?

**Comment by tyylynette** [comment]
@SergoZheludkov I'm trying to do the same thing now, could you share how it handled it? Thanks!

**Comment by shnigi** [comment]
Here you go. The buttons have to be passed as an array. You can have 8 buttons in one row so if you want less you have to split your array / create chunks. Here is example with lodash chunks.

```
const sortedDota2Heroes = _.sortBy(dota2heroes, ['localized_name']);
const dota2heroesChunk = _.chunk(sortedDota2Heroes, 4);

const inlineMessageHeroes = Markup.inlineKeyboard(
    dota2heroesChunk.map((chunk) => chunk.map((hero) => Markup.button.callback(hero.localized_name, hero.localized_name))),
);

const dota2heroperformanceSelectHero = async (ctx, playerId) => {
    selectedPlayer = playerId;
    ctx.editMessageText(
        'Choose hero',
        inlineMessageHeroes,
    );
};
```

**Comment by humblemodulo** [comment]
@shnigi  How, exactly, do you handle `.action()` for dynamically created buttons?
