### ISSUE TITLE
New invoice not showing up in telegram

### ISSUE THREAD

**Issue by 0x77dev** [telegraf/telegraf#1034]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: v14.2.0 / v10 / v13.0.0
* Operating System: macOS / GNU-Linux

## Expected Behavior

Invoice sent in a telegram chat

## Current Behavior

Sending without not showing up in telegram.

## Failure Information (for bugs)

`Nothing here`

### Steps to Reproduce

```typescript
bot.command("donate", async (ctx) => {
    const invoice: NewInvoiceParameters = {
        title: "Помощь проекту",
        photo_url: "https://image.freepik.com/free-vector/abstract-holographic-effect-background_1048-7861.jpg",
        description: "Помощь в поддрежке хостинга, и на хлебушек разработчику",
        prices: [{ label: "Хостинг", amount: 10 }, { label: "Хлебушек разработчику", amount: 5 }],
        currency: "UAH",
        payload: "payload",
        start_parameter: "startparam",
        provider_token: "<BotFather_Payment_Token>"
    }

    return await ctx.replyWithInvoice(invoice);
})
```

### Failure Logs
`Nothing here`

**Comment by Piterden** [comment]
1. Could you show a place where it is working correctly?
2. What error do you see in logs?

**Comment by 0x77dev** [comment]
The problem was fixed by adding `total_amount, but this variable is not defined in types.
