### ISSUE TITLE
Failed When Using Scene

### ISSUE THREAD

**Issue by drow-ranger** [telegraf/telegraf#1035]
Hello, I have the code as below

```
const greeterScene = new Scene("greeter");
greeterScene.enter(async (ctx) => {
  ctx.session.quote = await axios.get("https://baconipsum.com/api/?type=meat-and-filler");

  ctx.session.keyboard = [Markup.callbackButton("▶️", `/nav next`)];
  ctx.reply(`${ctx.session.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML());
});
greeterScene.action(/^\/nav[ =](.+)$/, async (ctx) => {
  ctx.session.quote = await axios.get("https://baconipsum.com/api/?type=meat-and-filler");

  ctx.session.keyboard = [Markup.callbackButton("▶️", `/nav next`)];
  ctx.editMessageText(`${ctx.session.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML());
});
bot.command("greeter", (ctx) => ctx.scene.enter("greeter"));
```
*actually I have several keyboards like next, prev, etc. But I only show next keyboard.

I use scenes because I hope the bot can handle requests from many users. When I simulate:
1. first person start command, then bot action reply
2. first person click next, then bot action edit text
3. second person click next but the bot doesn't do anything (as I expected)
4. second person start command, then bot action reply
5. after the second person runs a new scene, making the bot can respond to any input from anyone.

* check simulation: https://imgur.com/a/g9D0Rkn

maybe the code that I applied was wrong, so when there are 2 scenes makes chat a collision. 
Is there a solution so that editing text still serves the scene owner? 
Thanks.

**Comment by Piterden** [comment]
Where is it happening? In a group or in a private chat with bot?

**Comment by drow-ranger** [comment]
> Where is it happening? In a group or in a private chat with bot?
> 
> Oh, I see, it is group. In groups all participants are seeing the same message from bot, so scenes is a bit useless there...

oh sorry mr Piterden, i forgot to tell, the case occurred in the group.

I have another bot using Scene too.
Bots work like this:
1. User command /post
2. Bot enter Scene and reply please send me a photo with caption.
3. User send a photo with caption.
4. Bot save the photo, then leave Scene and reply thanks.

With the above method, bot can run normally in a group. Bot can serve many requests according to the Scene.  When first person command /post and second person responds by sending a photo, Bot will not respond. Bot only respond to who owns the Scene.

But unlike this case, Bot does not work well when running editText function.

**Comment by castrorry** [comment]
If I understand correctly, you can store message_id of the message sent by the bot in the session: 
```javascript
// ...
let sended = await ctx.reply(`${ctx.session.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML());
ctx.scene.session.message_id = sended.message_id;
// ...
// if (ctx.scene.session.message_id === ctx.callback_query.message.message_id) {...}
```
Then you will be able to check if the message that the bot will edit, and refer to the message stored in the user's session.
There is also another option, you can require the bot to send the message in response to the `/ greeter` command sent by the user, and then retrieve that user's id in` ctx.message.reply_to_message.from.id`, and check if the bot message refers to the session owner.

**Comment by Piterden** [comment]
> If I understand correctly, you can store message_id of the message sent by the bot in the session:

There is one important thing! The root session object (`ctx.session`) is not the same that the session object for scenes (`ctx.scene.session`). To know this behavior more detailed you'd better to look at [context of scenes](https://github.com/telegraf/telegraf/blob/develop/scenes/context.js).

**Comment by castrorry** [comment]
> > If I understand correctly, you can store message_id of the message sent by the bot in the session:
> 
> There is one important thing! The root session object (`ctx.session`) is not the same that the session object for scenes (`ctx.scene.session`). To know this behavior more detailed you'd better to look at [context of scenes](https://github.com/telegraf/telegraf/blob/develop/scenes/context.js).

```javascript
// ...
let sended = await ctx.reply(`${ctx.session.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML());
ctx.scene.state = { message_id: sended.message_id }
// ...
// if (ctx.scene.session.message_id === ctx.callback_query.message.message_id) {...}
```
So... store in state of session.

**Comment by Piterden** [comment]
```js
// ...
let { message_id } = await ctx.reply(
  `${ctx.session.quote.data[0]}`,
  Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML(),
).catch(console.log);

ctx.scene.state = { message_id, ...ctx.scene.state }
```
Maybe like this? But it should be tested...

**Comment by castrorry** [comment]
> ```js
> // ...
> let { message_id } = await ctx.reply(
>   `${ctx.session.quote.data[0]}`,
>   Extra.markup(Markup.inlineKeyboard(ctx.session.keyboard)).HTML(),
> ).catch(console.log);
> 
> ctx.scene.state = { message_id, ...ctx.scene.state }
> ```
> 
> Maybe like this? But it should be tested...

Yes, but considering good practices, then using the `id` of the invoker of the command through` reply_to_message`, it shows to be better, because it allows to continue interacting even if the scene session expires, if it is called `/greeter` again

I tested this with typescript syntax, feel free to test and refactor!
```javascript
const greeterScene = new Scene("greeter");
greeterScene.enter(async (ctx) => {
  // Replace session to state
  ctx.scene.state = { ...ctx.scene.state, quote: await axios.get("https://baconipsum.com/api/?type=meat-and-filler") };
  ctx.scene.state = { ...ctx.scene.state, keyboard: [Markup.callbackButton("▶️", `/nav next`)] };

  ctx.reply(`${ctx.scene.state.quote.data[0]}`, Extra.inReplyTo(ctx.message.message_id).markup(Markup.inlineKeyboard(ctx.scene.state.keyboard)).HTML());
});
greeterScene.action(/^\/nav[ =](.+)$/, async (ctx) => {
  let { from: prev_user } = ctx.callbackQuery;
  let { from: current_user } = ctx.callbackQuery.message.reply_to_message;
  if (prev_user.id === current_user.id) {
    // Replace to state
    ctx.scene.state = { ...ctx.scene.state, quote: await axios.get("https://baconipsum.com/api/?type=meat-and-filler") };

    // keyboard property already exists
    // ctx.scene.state.keyboard = [Markup.callbackButton("▶️", `/nav next`)];
    ctx.editMessageText(`${ctx.scene.state.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.scene.state.keyboard)).HTML());
  } else {
    // Ignore or show alert
    // ctx.answerCbQuery('Please call /greeter', true);
  }
});
bot.command("greeter", (ctx) => ctx.scene.enter("greeter"));
```
However, as @Piterden said about group scenes, it may not bring the best experience of all, but it is up to you.

**Comment by castrorry** [comment]
Hope this helps!

**Comment by drow-ranger** [comment]
> ```js
> const greeterScene = new Scene("greeter");
> greeterScene.enter(async (ctx) => {
>   // Replace session to state
>   ctx.scene.state = { ...ctx.scene.state, quote: await axios.get("https://baconipsum.com/api/?type=meat-and-filler") };
>   ctx.scene.state = { ...ctx.scene.state, keyboard: [Markup.callbackButton("▶️", `/nav next`)] };
> 
>   ctx.reply(`${ctx.scene.state.quote.data[0]}`, Extra.inReplyTo(ctx.message.message_id).markup(Markup.inlineKeyboard(ctx.scene.state.keyboard)).HTML());
> });
> greeterScene.action(/^\/nav[ =](.+)$/, async (ctx) => {
>   let { from: prev_user } = ctx.callbackQuery;
>   let { from: current_user } = ctx.callbackQuery.message.reply_to_message;
>   if (prev_user.id === current_user.id) {
>     // Replace to state
>     ctx.scene.state = { ...ctx.scene.state, quote: await axios.get("https://baconipsum.com/api/?type=meat-and-filler") };
> 
>     // keyboard property already exists
>     // ctx.scene.state.keyboard = [Markup.callbackButton("▶️", `/nav next`)];
>     ctx.editMessageText(`${ctx.scene.state.quote.data[0]}`, Extra.markup(Markup.inlineKeyboard(ctx.scene.state.keyboard)).HTML());
>   } else {
>     // Ignore or show alert
>     // ctx.answerCbQuery('Please call /greeter', true);
>   }
> });
> bot.command("greeter", (ctx) => ctx.scene.enter("greeter"));
> ```

thanks for help Mr Castrorry.
I try without using "if condition" the bot still runs well. Let say like this:
1. first person command /greeter
2. bot `reply_to_message` to id 123xx
3. when first person use navigation button, bot keep response
4. when second person use navigation button, bot not response (as I expected)

- check simulation: https://imgur.com/a/eN7n9s1

Maybe bot doesn't run `greeterScene.action (/ ^ \ / nav [=] (. +) $ /,` when the second person tried to use navigation button of the first person chat. As you can see in the simulation that I did.
Thanks for suggestion using `reply_to_message`, but I'm still curious why my code isn't working properly 🤣

**Comment by deniskutovskiy** [comment]
Your code isn't work properly (in your opinion) because of 2 facts:
- every person typing "greater" enters to the scene
- every action, which was bound to scene, will be handled if interactor is inside the scene.

I think the easiest way is to store userId in action data, so inside handler bot will compare id of interactor with id stored in data and ignore all presses made by everyone else but scene owner.

**Comment by KnorpelSenf** [comment]
Inactive.
