### ISSUE TITLE
(SOLVED) No response using Zeit now serverless api

### ISSUE THREAD

**Issue by waptik** [telegraf/telegraf#1036]
Hi! I'm a noob trying out bot creation for the first time.
I'm using latest version of telegraf alongside `@now/node` for serverless api in typescript.
I set the webhook url manually but I don't receive any feedback from bot, no output in console as well.
I might be doing something wrong, so a little bit of guidance will be helpful

The source code is at https://github.com/waptik/telegram-bot-boilerplate-now-serverless-api

**Comment by waptik** [comment]
So I was playing around with the code and with this commit (https://github.com/waptik/telegram-bot-boilerplate-now-serverless-api/tree/04017b82f4a59c610855efb68833d44c9738012c), I now get some info inside the console but when I use the `/start` command, no reply is being received.

**Comment by Piterden** [comment]
Try polling first.

**Comment by waptik** [comment]
> Try polling first.

Thanks.
It works with pooling.
But why not with webhook?

**Comment by castrorry** [comment]
Test this:
```typescript
export default async function handle(req: NowRequest, res: NowResponse) {

	if (!req.body) {
		// ok(res, 'Nothing to see here...');
		return;
	};
	return bot.handleUpdate(req.body, res);
}
```

**Comment by waptik** [comment]
> Test this in end of api/index.ts:
> ```typescript
> export default async function (req: NowRequest, res: NowResponse) {
> 
> 	if (!req.body) {
> 		// ok(res, 'Nothing to see here...');
> 		return;
> 	};
> 	return bot.handleUpdate(req.body, res);
> }
> ```

If you look at this commit(https://github.com/waptik/telegram-bot-boilerplate-now-serverless-api/tree/843b1ff8caada2b77e2e43bb3b44d70a0fd5b32a) which I use with pooling, it works but the reply from bot takes time before arriving.
