### ISSUE TITLE
ExtraReplyMessage is incompatible with ExtraVoice

### ISSUE THREAD

**Issue by reflash** [telegraf/telegraf#1037]
## Context

I've faced some typing issues after an upgrade from 3.36 to 3.38.
In my code I use `reply` and `replyWithVoice` with the same keyboard which contains multiple menu buttons. But now i'm not able to use `replyWithVoice` with the same code, so I have to ignore types even though I'm not using `disable_web_page_preview`
```
Argument of type 'ExtraReplyMessage' is not assignable to parameter of type 'ExtraVoice'.
  Types of property 'disable_web_page_preview' are incompatible.
    Type 'boolean' is not assignable to type 'never'.
```
* Telegraf.js Version: 3.38
* Node.js Version: 12.14.1
* Operating System: OS X Catalina

## Expected Behavior

No typing issue

## Current Behavior
```
Argument of type 'ExtraReplyMessage' is not assignable to parameter of type 'ExtraVoice'.
  Types of property 'disable_web_page_preview' are incompatible.
    Type 'boolean' is not assignable to type 'never'.
```

## Failure Information (for bugs)

Information provided above

**Comment by KnorpelSenf** [comment]
Version 4.0 will generate the types from source, this will most likely fix your problem. We are not going to update the handwritten types. You can already try this by building `telegraf` from source, using the `develop` branch.
