### ISSUE TITLE
Port this framework to Deno Land.

### ISSUE THREAD

**Issue by genemators** [telegraf/telegraf#1039]
**As everybody knows, a new Javascript runtime is out which is called "Deno".**

**Just port this project to this runtime**

Link to Deno's Homepage:
`https://deno.land/`

**Comment by genemators** [comment]
Thanks for creator & contributors for all your work and efforts you're doin for us. I truly appreciate this framework and I'll be waiting for Deno Port

**Comment by Piterden** [comment]
Are you Ad-Cock?
