### ISSUE TITLE
can't send audio with http url

### ISSUE THREAD

**Issue by AsakuraFuuko** [telegraf/telegraf#104]
> Error: Protocol "http:" not supported. Expected "https:"

https://github.com/telegraf/telegraf/blob/develop/lib/network/client.js#L36
https://github.com/telegraf/telegraf/blob/develop/lib/network/client.js#L133

I think this problem may be the default agent is HTTPS?

**Comment by dotcypress** [comment]
Hey.

Fixed in `v3.6.9`.

Thank you for bugreport 👍
