### ISSUE TITLE
correct_option_id - обязательная часть в sendQuiz

### ISSUE THREAD

**Issue by sadykhzadeh** [telegraf/telegraf#1041]
![image](https://user-images.githubusercontent.com/51178055/82346160-2c7c1780-9a07-11ea-8ade-6b37496ef4b1.png)

В [документации Telegraf](https://telegraf.js.org/#/?id=sendquiz) не указан **обязательный** параметр correct_option_id, который, если верить документации [Telegram BOT API](https://core.telegram.org/bots/api#sendpoll), очень важен.

![image](https://user-images.githubusercontent.com/51178055/82346517-9dbbca80-9a07-11ea-8b16-2ba71db90594.png)

**Comment by KnorpelSenf** [comment]
The docs will be generated from source in the future. Won't fix.
