### ISSUE TITLE
Incompatibility with TS 3.9.3

### ISSUE THREAD

**Issue by gsbelarus** [telegraf/telegraf#1045]
Project won't work with latest TS 3.9.3 if `Extra` and `Markup` are imported from `telegraf`. When running a code the next error will appear:

```
    Object.defineProperty(o, "default", { enumerable: true, value: v });
           ^
   TypeError: Cannot redefine property: default
```
The same code will execute without any errors if TS 3.8.3 is used.

Tested with `Node v.14.3` on `Windows 10 Pro`.

**Comment by bakanyaka** [comment]
Have similar problem with telegraf and typescript. What actually causes this error is when I have imports like this:
`import Telegraf, { session } from 'telegraf';`
but when I split import to multiple lines like this:
```
import Telegraf from 'telegraf';
import { session } from 'telegraf';
```
it does not generate
` Object.defineProperty(o, "default", { enumerable: true, value: v });`
and it executes without errors.

**Comment by gsbelarus** [comment]
Thanks for the hint. Dividing import into two lines works for me also.

**Comment by h0tw4t3r** [comment]
Got this error too.
https://github.com/microsoft/TypeScript/issues/38679 may be relevant.
