### ISSUE TITLE
webhookReply will not work on AWS Lambda + API Gateway

### ISSUE THREAD

**Issue by optimistiks** [telegraf/telegraf#1047]
When using Lambda with API Gateway, Lambda function has to return a specific object - https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format. 

There is no Response object available, meaning there is nothing to pass as a second argument to `bot.handleUpdate`.

Maybe one way could be to somehow get access to the payload object from answerToWebhook https://github.com/telegraf/telegraf/blob/99c243b097c46dfab82deba38a42af8522ddbb68/core/network/client.js#L187 so we can use it in that Lambda response object.

**Comment by KnorpelSenf** [comment]
Please check out the recently introduced example bot for AWS lambdas, confer #1186. Hope this helps.
