### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by supermomme** [telegraf/telegraf#105]
Hello,
If I create a webhook over the telegram api like this:
https://api.telegram.org/botxxxxxxxxxxxxxxxxxxxx/setWebhook?url=https://(myherokuapp).herokuapp.com/telegram/(randomToken)

and some code like this:
```javascript
app.telegraf.startWebhook(app.get('bot-webhook'), null, 5000)
app.use(app.telegraf.webhookCallback(app.get('bot-webhook')))
```
I get this error:
```
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates method while webhook is active
     at buildPayload.then.then.then.then (/app/node_modules/telegraf/lib/network/client.js:102:17)
     at process._tickCallback (internal/process/next_tick.js:109:7)
   code: 409,
   response: undefined,
   description: 'Conflict: can\'t use getUpdates method while webhook is active',
   retryAfter: undefined,
   migrateToChatId: undefined }
```

I'll wait for response. 😄

**Comment by dotcypress** [comment]
Hello.

Do you call `startPolling`? If yes, you need to remove this that call.

**Comment by supermomme** [comment]
Yes I call `startPolling`. I try that later.

**Comment by supermomme** [comment]
Yes it works, but now I have a problem with express. But I think I can solve that. Thanks for help. 😄
