### ISSUE TITLE
How to ignore old messages sent when the bot was offline

### ISSUE THREAD

**Issue by Mohamed-Magid** [telegraf/telegraf#1050]
Hi,
Let's say I have a very simple bot
```javascript
const Telegraf = require("telegraf");
const bot = new Telegraf(process.env.TOKEN);
bot.on('text', ctx => {
if(ctx.message.text === 'Hi')
   ctx.reply('Hello');
}

bot.launch();
```
And someone spammed ```Hi``` in the group chat while the bot was offline, how can I make the bot ignore all the messages that was sent when it was offline? Knowing that there's no database to store when it came back alive.

**Comment by Loskir** [comment]
see resetbot.com, there you can also see what request to send if you want to do it automatically

**Comment by Mohamed-Magid** [comment]
> see [resetbot.com](https://resetbot.com)
> 
> Here's the request you can send instead
> 
> ```
> https://api.telegram.org/bot{{token}}/getUpdates?offset=-1
> ```

Thanks so much, I'll give it a shot.

**Comment by bubanami** [comment]
> see [resetbot.com](https://resetbot.com)
> 
> Here's the request you can send instead
> 
> ```
> https://api.telegram.org/bot{{token}}/getUpdates?offset=-1
> ```

it still gets the last message. How to ignore all of them completely?

**Comment by bennycode** [comment]
@bubanami you can drop past messages (while the bot was offline) by passing `dropPendingUpdates: true` to your launch options:

```ts
await this.bot.launch({
  dropPendingUpdates: true
});
```
