### ISSUE TITLE
ctx.message.reply_to_message is inconsistent 

### ISSUE THREAD

**Issue by romanpastu** [telegraf/telegraf#1058]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.14.1
* Operating System: W10

## Expected Behavior

When replying to an user, `ctx.message.reply_to_message.from.id` should return the users id to whom I have replied

## Current Behavior

`ctx.message.reply_to_message.from.id` is only returned with some users. I cant seem to find a consistency there, but there are times when `ctx.message.reply_to_message == undefined` even tho it shouldnt

##Example code
```
bot.command('tip', (ctx) => {
    let myId = ctx.update.message.from.id
    let repliedId = ""
    let exists = false;

    if (ctx.message.reply_to_message != undefined) { //this is undefined sometimes even when I reply to an user, and it shouldnt appear as undefined
        repliedId = ctx.message.reply_to_message.from.id; 
        exists = true;
    } else {
       ...
})
```

**Comment by romanpastu** [comment]
Found the issue. The inconsistency happens when its not a supergroup

**Comment by Loskir** [comment]
And if you have *Privacy mode* enabled, right?

**Comment by romanpastu** [comment]
No @Loskir , it doesnt seem to have any influence. I have tried enabling and disabling it for some users, and the behaviour was still unexpected.

**Comment by Loskir** [comment]
Privacy mode is enabled for bot in BotFather
https://core.telegram.org/bots#privacy-mode

With this mode enabled the bot won't sometimes be able to see reply_to_message, afaik

**Comment by romanpastu** [comment]
It might actually be that then. I will test it
