### ISSUE TITLE
payments support

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#106]
https://telegram.org/blog/payments

please add support for payments.
I can try to help if someone makes a fork.

**Comment by dotcypress** [comment]
Already implemented
https://github.com/telegraf/telegraf/blob/develop/examples/shop-bot.js

**Comment by bitdom8** [comment]
The link is broken

**Comment by dr-iroh** [comment]
@bitdom8 https://github.com/telegraf/telegraf/blob/v4/docs/examples/shop-bot.js

**Comment by bitdom8** [comment]
thanks @dr-iroh
