### ISSUE TITLE
ctx.getChatMember giving reply status member even neither bot nor user part of the group/channel.

### ISSUE THREAD

**Issue by imdkbj** [telegraf/telegraf#1061]
## Context

* Telegraf.js Version: Latest
* Node.js Version: Latest
* Operating System: CentOs7

## Expected Behavior

It should to show error or something like not member if user/bot not part of the chatid.

## Current Behavior

Getting reply member which is unexpected at all.

### Steps to Reproduce

```js
bot.hears(/^My Referral Link$/i, (ctx) => {
    ctx.getChatMember(ctx.chat.id, '-*****')
    .then(s => {
        console.log('logs', s)
    })
    .catch(e => {
        console.log('error', e)
    })
})
```

Getting same reply in all case either bot/user part of channel or not

```js
logs {
  user: {
    id: **,
    is_bot: false,
    first_name: 'dEEPAK',
    username: '*',
    language_code: 'en'
  },
  status: 'member'
}
```

**Comment by Piterden** [comment]
Probably you pass the same id there.

**Comment by imdkbj** [comment]
Here first argument is chatid which is suppose channel id
![image](https://user-images.githubusercontent.com/46839821/84041383-64043100-a9c1-11ea-9642-5fdacfa60c45.png)

Now, Look here, The first argument is userid
![image](https://user-images.githubusercontent.com/46839821/84041568-9ca40a80-a9c1-11ea-825d-b9e2311b247e.png)

**These seems a cause of the error and if so then lot's of things might not work with ctx shortcut argument.**

**Comment by imdkbj** [comment]
> Probably you pass the same id there.

Nope buddy!!

**Comment by imdkbj** [comment]
> Probably you pass the same id there.


This is working fine so this bug is related to wrong ref in ctx shortcut

```js
 bot.hears(/^My Referral Link$/i, ({message,reply,telegram }) => {
    telegram.getChatMember('-**',message.chat.id)
    .then(s => {
        console.log('logs', s)
    })
    .catch(e => {
        console.log('error', e)
    })
}) 
```

```js
logs {
  user: {
    id: *,
    is_bot: false,
    first_name: 'dEEPAK',
    username: '**',
    language_code: 'en'
  },
  status: 'administrator',
  can_be_edited: false,
  can_change_info: true,
  can_post_messages: true,
  can_edit_messages: true,
  can_delete_messages: true,
  can_invite_users: true,
  can_restrict_members: true,
  can_promote_members: true
```

**Comment by Piterden** [comment]
The second argument is user id, not chat!

**Comment by imdkbj** [comment]
> The second argument is user id, not chat!

Test1
```js
bot.hears(/^test$/i, (ctx) => {
    ctx.getChatMember( '-1001355229208',ctx.chat.id)
    .then(s => {
        console.log('logs', s)
    })
    .catch(e => {
        console.log('error', e)
    })
})
```

Response1

```js
error TelegramError: 400: Bad Request: wrong user_id specified
    at /home/skymaxdigitech/public_html/bot/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: wrong user_id specified'
  },
  description: 'Bad Request: wrong user_id specified',
  parameters: {},
  on: {
    method: 'getChatMember',
    payload: { chat_id: 47504****, user_id: '-1001355229208' }
  }
}
```

Test2
```js
bot.hears(/^test$/i, (ctx) => {
    ctx.getChatMember( ctx.chat.id,'-1001355229208')
    .then(s => {
        console.log('logs', s)
    })
    .catch(e => {
        console.log('error', e)
    })
})
```

Response2

```js
logs {
  user: {
    id: 47504****,
    is_bot: false,
    first_name: 'dEEPAK',
    username: '******',
    language_code: 'en'
  },
  status: 'member'
}
```

**Comment by Piterden** [comment]
You need to pass user_id as the second argument! Chat_id there will cause error!

**Comment by imdkbj** [comment]
> You need to pass user_id as the second argument! Chat_id there will cause error!

Have a look on test1 report dude.

**Comment by imdkbj** [comment]
Another case is :: exportChatInviteLink

![image](https://user-images.githubusercontent.com/46839821/84129655-dc213400-aa5f-11ea-9ef5-3ea6045ebdb9.png)

```js
-10014328***** 71746****
TelegramError: 400: Bad Request: can't invite members to a private chat
    at /home/skymaxdigitech/public_html/bot/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: "Bad Request: can't invite members to a private chat"
  },
  description: "Bad Request: can't invite members to a private chat",
  parameters: {},
  on: { method: 'exportChatInviteLink', payload: { chat_id: 71746****} }
}


```

**Comment by Piterden** [comment]
Are you okay?
- **`ctx.chat.id`** is the ID of a chat where it is happening.
- **`ctx.from.id`** is the ID of a user who is doing something.
Where your bot interact with user in the private chat, the **`chat_id`** and the **`user_id`** are equal!

**Comment by imdkbj** [comment]
I am fine buddy!! Thx for the concern. I understand what to tabled. 

Can  u pls share how to get by ctx ....
Check status of a member in channel for getChatMember  method.
Get exportChatInviteLink of a group.

**Comment by BNO79** [comment]
> Another case is :: exportChatInviteLink
> 
> ![image](https://user-images.githubusercontent.com/46839821/84129655-dc213400-aa5f-11ea-9ef5-3ea6045ebdb9.png)
> 
> ```js
> -10014328***** 71746****
> TelegramError: 400: Bad Request: can't invite members to a private chat
>     at /home/skymaxdigitech/public_html/bot/node_modules/telegraf/core/network/client.js:281:17
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   code: 400,
>   response: {
>     ok: false,
>     error_code: 400,
>     description: "Bad Request: can't invite members to a private chat"
>   },
>   description: "Bad Request: can't invite members to a private chat",
>   parameters: {},
>   on: { method: 'exportChatInviteLink', payload: { chat_id: 71746****} }
> }
> ```

I've the same error :(

..anybody know some work around to use the method "exportChatInviteLink" to send invite from private group troughth bot?

**Comment by KnorpelSenf** [comment]
I understand this as solved, please reopen if the error persists.
