### ISSUE TITLE
add a custom file name while sharing a file

### ISSUE THREAD

**Issue by sarangsmk** [telegraf/telegraf#1062]
I want to change the name of a file(add custom name) while sharing a file

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#document

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#inputmediadocument'
It seems you will need to rename file on your disk before sending.

**Comment by deniskutovskiy** [comment]
According to this
https://github.com/telegraf/telegraf/blob/7a0052f7500a25047c3b47810239c0cfb337b6db/typings/telegram-types.d.ts#L314
and this
https://github.com/telegraf/telegraf/blob/f1403a8f400086cee3b16ff3574efefef2a87888/src/telegram.ts#L260
lines, and finally according to official bot API docs (https://core.telegram.org/bots/api#senddocument) you **can not**. You also can find more information about sending files in documentation (here is the chapter: https://core.telegram.org/bots/api#sending-files).
To reach your goal you can download your file, change its name, than upload it back to your chat.

**Comment by KnorpelSenf** [comment]
@deniskutovskiy explained it all, that is correct.
