### ISSUE TITLE
When using Webhook ctx.reply() not sent!

### ISSUE THREAD

**Issue by C0d6rZ** [telegraf/telegraf#1067]
I was making a simple telegram bot. It was supposed to send random dog pics through using an api. The bot was working fine when i was using polling but the error started when i used webhook and deployed it on heroku.
 The problem seems to be under 'shoot' command when i call the api, the ctx.reply() stops working.
Please look into this problem.

Here is the code.
const Telegraf   = require('telegraf');
const axios      = require('axios');
const apiToken   = myBotToken;
const port       = process.env.PORT || 3000;
const url        = 'https://myAppId.herokuapp.com';
const bot        = new Telegraf(apiToken);

//setup webhook
bot.telegram.setWebhook(`${url}/bot${apiToken}`);
bot.startWebhook(`/bot${apiToken}`,null,port);

//bot commands 

bot.start((ctx) => {
    ctx.reply("I'm Mr. Doggo. I can send you cute random dog pics.");
})

bot.command('shoot',(ctx)=>{
    var contentUrl = "https://random.dog/woof.json";
    axios.get(contentUrl)
    .then((res)=>{
        console.log(res.data.url);
        finalUrl = res.data.url;
        return ctx.replyWithPhoto(finalUrl);
    });
//    ctx.reply('shooting...');
    
})

bot.command('about',(ctx)=>{
    ctx.reply("I was created by a human. I just send random dog pics. :D");
})

bot.help((ctx) =>{
    ctx.reply("The following commands can be used:\n  /shoot - sends random dog images\n  /fact - sends random dog fact.\n  /about - about me.")
})

**Comment by DeusNexus** [comment]
I'm sure the error resides in the axios part where it is waiting for a promise.
Maybe you can try to turn it into an async function?

bot.command('shoot',async (ctx)=> {
var contentUrl = "https://random.dog/woof.json";

const response = await axios.get(contentUrl).catch(e => { ctx.reply(e) })
if(response) {
  console.log(res.data.url);
  finalUrl = res.data.url;
  return ctx.replyWithPhoto(finalUrl);
} else {
  ctx.reply('No response from url')
}

// ctx.reply('shooting...');
})
