### ISSUE TITLE
How to trigger an action with command or other action?

### ISSUE THREAD

**Issue by DeusNexus** [telegraf/telegraf#1068]
I have a menu with buttons and every time a button is clicked I want to spawn a new menu with updated buttons. My menu is created on 'action', if I would click on any button it will trigger that corresponding function but I also want it to delete the old message id and re-run the menu action.

How can this be done?

**Comment by deniskutovskiy** [comment]
What purpose of deleting the message id? And what do you mean saying "re-run the menu action"?
Please, provide some code sample and refer to it in your question.

**Comment by KnorpelSenf** [comment]
Closing as too general. Please ask a concrete question so that we can help you.
