### ISSUE TITLE
How to get private channel members

### ISSUE THREAD

**Issue by seocobe** [telegraf/telegraf#1069]
Hello,

Is there a way to get the username or user_id of the subscribers of a private channel?
I need to be able to manage those users based on the subscription they made on my website.
So what I need to do:
1) somebody subscribes to the channel via my website. Then they need to add their telegram username to their profile page. They will also receive the private channel URL so they can subscribe to the channel.
2) based on that username I need to check the subscribed users of that private channel. If they are still a member they can stay else I want to block them.
3) I also need to be able to block subscribers that not subscribed via my website and received the url from somewhere else.

I don't find a way to do this.
Any help would be appreciated.

Br,
/m

**Comment by deniskutovskiy** [comment]
Your issue looks like technical task or design specifications. Try to start coding your project and write here exactly the problem you faced.

**Comment by KnorpelSenf** [comment]
This is not possible. Telegram bots cannot manage channel members in the way that you need.

It's funny that I stumble upon this issue. In fact, I just wrote https://github.com/KnorpelSenf/subscription-manager-bot a few weeks ago which pretty much solves exactly your problem. It is already running in production for different groups. The main difference is probably that you know the Telegram IDs in advance, while my bot has a feature to find them out first.

If you cannot use that bot directly, it should still be relatively straightforward to adapt it to your needs.
