### ISSUE TITLE
Editing message with Extra Markup issue 

### ISSUE THREAD

**Issue by natget21** [telegraf/telegraf#1070]
so i was building a bot here i request a contact of the user and then edit that text with location request but i am not able to edit the text if the text has a markup inline keyboard in it it works fine without the keyboard is there something i am missing or is it not supported

```
return ctx.telegram.sendMessage(ctx.update.message.from.id,"Press Send Contact to send your contact", Extra.markup(markup => {
        return markup.oneTime().resize()
            .keyboard([
                markup.contactRequestButton('Send contact', false),
            ])
    })).then((msgInfo) => { chatid = msgInfo.chat.id; msgid = msgInfo.message_id });
```

after this i want to edit the current message not send a new one 

```
bot.on('contact', (ctx) => {
    ctx.telegram.deleteMessage(ctx.chat.id, ctx.message.message_id)
    return ctx.telegram.editMessageText(chatid,msgid,null,'Please send your location', Extra.markup(markup => {
        return markup.oneTime().resize()
            .keyboard([
                markup.locationRequestButton('Send Current location', false),
            ])
    }));
})
```

but i get the following error 

```
response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: message can\'t be edited' },
  description: 'Bad Request: message can\'t be edited',
  parameters: {},
  on:
   { method: 'editMessageText',
     payload:
      { chat_id: 446073823,
        message_id: 3793,
        text: 'Please send us your location',
        reply_markup: [Object] } } }
```

**Comment by deniskutovskiy** [comment]
Why do you delete message before editing it? Or is this a separate message (your code refers to unassigned variables)?

**Comment by KnorpelSenf** [comment]
You're trying to send a button that requests the user's location as a button of an inline keyboard. This type of button cannot be sent under a message. Check out the official docs on inline buttons: https://core.telegram.org/bots/api#inlinekeyboardbutton

The upcoming 4.0 release with TypeScript types will give you a compilation error in this case, so that type of issue should not happen anymore in the future.
