### ISSUE TITLE
A way to send message to subscribers of a channel that my bot is also member of the channel

### ISSUE THREAD

**Issue by Eliyanan** [telegraf/telegraf#1075]
I wanted to send a message to members of a telegram channel and I couldn't find that in telegraf doc, is there a way that I can achieve this feature using telegraf?

**Comment by MRVMV** [comment]
There is no way to get all members in channel nor there is a way to send to all of them if not all of them started the bot once (telegram bot api limitations). I suggest doing that manually by telling followers to start bot and then store there ids in a db and finally broadcast to them whenever you want

**Comment by KnorpelSenf** [comment]
What @MRVMV says is true. A bot can never proactively contact a user in a 1:1 chat.

You could of course just send a message to the channel using `bot.sendMessage`.
