### ISSUE TITLE
[QUESTION] How can I go from one scene to another?

### ISSUE THREAD

**Issue by radostnomne** [telegraf/telegraf#1079]
## Context

* Telegraf.js Version: 3.38.0
* Node.js Version: v12.16.1
* Operating System: macos 10.15.5

## Expected Behavior

jump from one scene to another

## Current Behavior

while Im jumping from one scene to another Im getting `Maximum call stack size exceeded`

### Steps to Reproduce

```js
const firstScene = new Scene('first')
const secondScene = new Scene('second')

firstScene.enter(ctx => {
  ctx.reply('Type cmd');
})

firstScene.hears('cmd', ctx => {
  ctx.reply('cmd');
  ctx.scene.leave();
})

firstScene.leave(ctx => {
  ctx.scene.enter('second')
})

secondScene.enter(ctx => { // this fires many times
  ctx.reply('Second scene');
})
```

### Failure Logs
`Maximum call stack size exceeded`

How to fire secondScene.enter one time?

**Comment by sagadav** [comment]
try:
`firstScene.enter(ctx => {
  ctx.reply('Type cmd');
})

firstScene.hears('cmd', ctx => {
  ctx.reply('cmd');
  ctx.scene.enter('second')
  ctx.scene.leave();
})
secondScene.enter(ctx => { 
  ctx.reply('Second scene');
})
`

**Comment by deniskutovskiy** [comment]
Hi! Due to this line https://github.com/telegraf/telegraf/blob/a6a5210abdeeb33bd535664f3fa5640bb8583c98/src/scenes/context.js#L47, when you call `ctx.scene.enter` inside `leave`-callback you get `leave-enter-leave`-loop. So, to achieve the goal you should call `ctx.scene.enter('second')` immediately, without leaving first scene.

**Comment by deniskutovskiy** [comment]
By the way, to be correct your `secondScene.enter`-callback fires zero times, because the loop iteration ends up before calling https://github.com/telegraf/telegraf/blob/a6a5210abdeeb33bd535664f3fa5640bb8583c98/src/scenes/context.js#L60
