### ISSUE TITLE
Add support for enum processor plugin to be able to transform integers not just strings

### ISSUE THREAD

**Issue by perzizzle** [telegraf/telegraf#1081]
**Is your feature request related to a problem? Please describe.**
We are using the telegraf snmp input plugin to pull F5 networking data. The snmp data returned has the values 0-5 correlating to the state of the device. 1 is a healthy device and the other 4 integers are various forms of failure. I wanted to make it easy to calcualte the percentage down if I can transform the data to 0 and 1 (for all failures) I can then in psuedo code do:

select sum(status)/count(status)*100

**Describe the solution you'd like**
```
[[processors.enum]]
  [[processors.enum.mapping]]
    field = "ltmPoolMbrStatusAvailState"
    dest = "ltmPoolMbrStatusAvailState_code"

    ## Table of mappings
    [processors.enum.mapping.value_mappings]
      1 = 0
      0 = 1
      2 = 1
      3 = 1
      4 = 1
      5 = 1
```
**Describe alternatives you've considered**
I could use nested queries to do this math but its not very readable.

(select count(status) where status!=1)/(select count(status))*100

**Comment by KnorpelSenf** [comment]
I don't think this is the right place to open an issue. This repo contains a framework for writing chatbots for the Telegram messenger in TypeScript or JavaScript.

I assume you were looking for https://github.com/influxdata/telegraf.
