### ISSUE TITLE
Add typing for file_unique_id

### ISSUE THREAD

**Issue by LuisMayo** [telegraf/telegraf#1085]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: N/A
* Operating System: N/A

## Expected Behavior

When using intellisense and Typescript within my project, `file_unique_id` should be a valid field in several types like `PhotoSize` as stated in the [telegram API](https://core.telegram.org/bots/api#photosize)

## Current Behavior

Intellisense don't find that field and tsc complains about it

**Comment by wojpawlik** [comment]
Already fixed on `develop`, will be published in 4.0.
