### ISSUE TITLE
messages with attachments in wrong order

### ISSUE THREAD

**Issue by artyom-vasich** [telegraf/telegraf#1086]
Hello! I was trying to send an album and then a bunch of callback buttons and noticed, that they arrive before the album. It appears that the first message with attachment in a row arrives later than expected. For example

```js
bot.command("foo", async ctx => {
    await ctx.replyWithPhoto("file_id 1");
    await ctx.reply("photo 1");
    await ctx.replyWithPhoto("file_id 2");
    await ctx.reply("photo 2");
    await ctx.replyWithPhoto("file_id 3");
    await ctx.reply("photo 3");
});
```
always results in sequence "photo 1" -> [img1] -> [img2] -> "photo 2" -> [img3] -> "photo 3"

If I log returned message objects like this
```js
bot.command("foo", async ctx => {
    const m1 = await ctx.replyWithPhoto("file_id 1");
    const m2 = await ctx.replyWithPhoto("file_id 2");
    const m3 = await ctx.replyWithPhoto("file_id 3");
    console.log(m1);
    console.log(m2);
    console.log(m3);
});
```
I see regular expected messages m2 and m3, but m1 is like that instead
```js
{
    webhook: true,
    details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
```

Am I doing something wrong? 

telegraf 3.38, and I am using webhook callbacks with fastify if it matters

**EDIT:** it turned out that attachments have nothing to do with this: first two messages always sent in reverse order regardless of content
```js
    await ctx.reply("1");
    await ctx.reply("2");
    await ctx.reply("3");
    await ctx.reply("4");
```
2 -> 1 -> 3 -> 4

**Comment by wojpawlik** [comment]
I have no experience with Fastify, please show me the code you use to integrate Telegraf with it.

**Comment by artyom-vasich** [comment]
Like with attachments, mention of fastify was misleading :( Just tried following minimal code

```js
const { Telegraf } = require("telegraf");

const bot = new Telegraf(process.env.BOT_TOKEN);

bot.command("start", async ctx => {
    await ctx.reply("1");
    await ctx.reply("2");
    await ctx.reply("3");
    await ctx.reply("4");
});

bot.telegram.setWebhook(`${process.env.HOST}/${process.env.BOT_TOKEN}`);
bot.startWebhook(`/${process.env.BOT_TOKEN}`, null, process.env.PORT);
```
and result remains the same:
![image](https://user-images.githubusercontent.com/11535902/87689767-4761d280-c791-11ea-93c9-ca0aad09f511.png)

**Comment by wojpawlik** [comment]
```
Welcome to Node.js v14.0.0.
Type ".help" for more information.
> http.ServerResponse.prototype.end.length
3
```

So I believe this code is responsible:

https://github.com/telegraf/telegraf/blob/cff8967f9ba083b267825c872282344c24e88d24/src/core/network/client.ts#L215-L217

It looks correct to me, which means that either I missed something, or the problem lies within bot API or Node.js.

Workaround:

```ts
const bot = new Telegraf(process.env.BOT_TOKEN, { telegram: { webhookReply: false } });
// or
bot.webhookReply = false
```

**Comment by artyom-vasich** [comment]
Yeap, it works! Thank you! Closing.
