### ISSUE TITLE
New bot example

### ISSUE THREAD

**Issue by howHighUR** [telegraf/telegraf#1087]
I've created bot that allow you to measure your pepe. It written in typescript with telegraf and there are some interesting architecture approaches. I would be appreciated if you take a look. If you are interested to add it to examples then I can translate bot to English. Thanks!

https://github.com/C0deRang3rs/bibabot

Features:
 - Pepe measuring
 - Virtual currency (bibacoin) with shop
 - Rate system for memes
 - Group auto-rename
 - Config
 - etc

**Comment by KnorpelSenf** [comment]
I'm not sure I understand what the bot does. Do you have some documentation that explains the terminology (biba, pepe, etc) or its use?

Also, no matter how good a bot is, most of the examples are rather simple bots that illustrate how to use the library. I'm not sure if complex bots help anyone with this, but if there's a need for it, you could open a PR to add it to the list of community bots.
