### ISSUE TITLE
Missing validation for file attachments

### ISSUE THREAD

**Issue by prabhu** [telegraf/telegraf#1095]
## Context

Hello. I was reviewing this repo using [ShiftLeft](https://docs.shiftleft.io/ngsast/analyzing-applications/javascript). I noticed that that client.ts doesn't perform any sanitization or validation on the file being attached as form media.

https://github.com/telegraf/telegraf/blob/66b795a38ab7c0bb8bbc29b05ddcc1d955d26205/src/core/network/client.ts#L184

## Expected Behavior

Only allowed file extensions from allowed directories should be allowed as attachments by default.

## Current Behavior

Lack of sanitization and validation.

**Comment by KnorpelSenf** [comment]
Do you have a suggestion which paths or file extensions should be put on a blocklist/allowlist?

I see that it could be a risk to allow arbitrary files to be sent to Telegram, but I'm not sure that it's possible to improve the security much here.

**Comment by wojpawlik** [comment]
Any filter could be easily bypassed by passing `ReadableStream` directly: https://github.com/telegraf/telegraf/blob/1f7dee72c702bdf05791ccba2a8a8c3b3c6f9dfc/src/telegram-types.ts#L22-L24

**Comment by KnorpelSenf** [comment]
@prabhu you may want to look into confirming that your tool doesn't produce false positives before you use GitHub issues for advertising.

**Comment by prabhu** [comment]
@KnorpelSenf Apologies was quite busy with few things. I would have expected an allow list of file paths since beyond some media types and documents telegram may not support other file types.

Thanks for calling this issue as advertising.

**Comment by KnorpelSenf** [comment]
> beyond some media types and documents telegram may not support other file types

If this was true, I agree that an allow list would make sense, but in fact you can send arbitrary files. What you say may apply to sending files via URL, but the code you're referencing has nothing to do with that. Also, `telegraf` taking care of the errors that the server-sideTelegram validation logic throws.
