### ISSUE TITLE
Can not to enable channelMode

### ISSUE THREAD

**Issue by bbalkonsky** [telegraf/telegraf#1097]
## Context

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.18.2
* Operating System: Win 10

I'm trying to enable channelMode:
`import { Telegraf} from 'telegraf';`
`const bot = new Telegraf(TOKEN, {channelMode: true});`
but have next error:
`Argument type {channelMode: boolean} is not assignable to parameter type TelegrafOptions | undefined `

**Comment by wojpawlik** [comment]
Already fixed on `develop`, will be published in 4.0.
