### ISSUE TITLE
504 Gateway-Timeout

### ISSUE THREAD

**Issue by phfaster** [telegraf/telegraf#110]
Please handle the 504 Gateway-timeout error. Now it is processed as Unsupported message from Telegram. I often have it when sending a photo. I propose to reconnect, because I understood the server of Telegram too long stupid.

Server response:
`<title>504 Gateway Time-out</title>

<h1>504 Gateway Time-out</h1>
<hr>nginx/1.6.2`

**Comment by dotcypress** [comment]
Hey 👋

[You can add custom errror hadling](http://telegraf.js.org/introduction.html#error-handling)
