### ISSUE TITLE
 Bad Gateway

### ISSUE THREAD

**Issue by sergiyvoytovych** [telegraf/telegraf#1100]
## Context
I've created new bot and received errors like describe below
But with bot I've created moth ago everything works fine.
* Telegraf.js Version: "3.38.0"
* Node.js Version:10
* Operating System:Linux

## Expected Behavior

Normal work as previously

## Current Behavior

const bot = new Telegraf(BOT_TOKEN,{telegram: { webhookReply: true }})
.......
bot.startPolling()
Failed to fetch updates. Waiting: 1s 502: Bad Gateway
OR
bot.launch()
Launch failed
Error: 502: Bad Gateway

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create new bot
2. Run bot with 
3. you get it...

### Failure Logs

Failed to fetch updates. Waiting: 1s 502: Bad Gateway
Failed to fetch updates. Waiting: 1s 502: Bad Gateway
Failed to fetch updates. Waiting: 1s 502: Bad Gateway

Launch failed
Error: 502: Bad Gateway
    at buildConfig.then.then.then.then (/home/sergiy/PhpstormProjects/wetelo-g/node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by razenization** [comment]
Bump. Experiencing the same behaviour.

**Comment by wojpawlik** [comment]
This should be a temporary problem on Telegram's side, and as such it's not printed to console by default since #1224.
