### ISSUE TITLE
How to Stop Telegram Updates

### ISSUE THREAD

**Issue by universidadeglobal** [telegraf/telegraf#1101]
Hi,
I hope are fine and safe.

How can I stop Telegram updates using Telegraf ?
For some reason, Telegram is always sending old updates and bot.on is calling over and over again.

Regards,

Roger

**Comment by illvart** [comment]
What do you mean?

If you mean ignoring messages for old update you can just call `next()` if `ctx.message.date` blabla.

Example how I implementation check in [My Gists](https://gist.github.com/illvart/9152147c40bf05b90008475d6ec00db0).

**Comment by universidadeglobal** [comment]
Yes, ignore old updates.
I will take a look in your gists.
Thanks a lot for help

**Comment by illvart** [comment]
> Yes, ignore old updates.
> I will take a look in your gists.
> Thanks a lot for help

You're welcome! If my solution works then you can close this issue.

**Comment by universidadeglobal** [comment]
Solved
