### ISSUE TITLE
incorrect import TelegrafContext

### ISSUE THREAD

**Issue by fjodor-rybakov** [telegraf/telegraf#1102]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: 14.6.0
* Operating System: Win

## Expected Behavior

import `TelegrafContext` without error

## Current Behavior
I try: `import {TelegrafContext} from 'telegraf'`
Put exception: `Error:(2, 20) TS2614: Module '"../../node_modules/telegraf/typings"' has no exported member 'TelegrafContext'. Did you mean to use 'import TelegrafContext from "../../node_modules/telegraf/typings"' instead?`

## Failure Information (for bugs)

tsconfig:
`{
  "compilerOptions": {
    "target": "es2017",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "outDir": "./dist",
    "declaration": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "baseUrl": "./src"
  },
  "include": [
    "./src"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "build"
  ]
}
`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. define type `TelegrafContext` for variable
2. import `TelegrafContext` like `import {TelegrafContext} from 'telegraf'`
3. and get exception import

### Failure Logs

`Error:(2, 20) TS2614: Module '"../../node_modules/telegraf/typings"' has no exported member 'TelegrafContext'. Did you mean to use 'import TelegrafContext from "../../node_modules/telegraf/typings"' instead?`

**Comment by wilddip** [comment]
`import { Telegraf.Context } from 'telegraf'` ?)

**Comment by illvart** [comment]
Try this:

```js
import Context from 'telegraf/context';
```
Or

```js
import Telegraf from 'telegraf';
const {Context} = Telegraf;
```

**Comment by fjodor-rybakov** [comment]
> `import { Telegraf.Context } from 'telegraf'` this works for me



> Try this:
> 
> ```js
> import Context from 'telegraf/context';
> ```
> 
> Or
> 
> ```js
> import Telegraf from 'telegraf';
> const {Context} = Telegraf;
> ```

This does not work

**Comment by fjodor-rybakov** [comment]
If import like `import {TelegrafContext} from 'telegraf/typings/context';` i got exception:
```
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'telegraf/typings/context'
Require stack:
- C:\projects\telegram\dist\bot\bot.service.js
- C:\projects\telegram\dist\bot\bot.module.js
- C:\projects\telegram\dist\app.module.js
- C:\projects\telegram\dist\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\projects\telegram\dist\bot\bot.service.js:21:19)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\projects\\telegram\\dist\\bot\\bot.service.js',
    'C:\\projects\\telegram\\dist\\bot\\bot.module.js',
    'C:\\projects\\telegram\\dist\\app.module.js',
    'C:\\projects\\telegram\\dist\\main.js'
  ]
}
```

**Comment by fjodor-rybakov** [comment]
`import { Context } from 'telegraf';` solve my problem
