### ISSUE TITLE
Failed to process updates. Error: Updates must be an array

### ISSUE THREAD

**Issue by ikerya** [telegraf/telegraf#1104]
* Telegraf.js Version: 3.38.0
* Node.js Version: 13.10.1
* Operating System: Debian GNU/Linux 8.11 (jessie)

Just got the error. What to do with that? 

```
Failed to process updates. Error: Updates must be an array
     at Telegraf.handleUpdates (/var/www/project/node_modules/telegraf/telegraf.js:153:29)
     at /var/www/dictionary-bot/node_modules/telegraf/telegraf.js:190:16
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ikerya** [comment]
Any comments?

**Comment by imdkbj** [comment]
Can you share the array what u are suppling to restrict the updates.

**Comment by ikerya** [comment]
I do not restrict anything. This is the only thing i do with the bot's instance:

```
bot.launch({
    polling: { timeout: 3 }
});
```

**Comment by ikerya** [comment]
Any comments? Still happening...

**Comment by imdkbj** [comment]
Hey! I am unable to reproduce the issue. Can u share the complete code after removing sensitive info.

![image](https://user-images.githubusercontent.com/46839821/92246645-ae734c00-eee3-11ea-8f74-a6e28f869ddd.png)


The said error will occurred only if you pass **allowedUpdates**
https://github.com/telegraf/telegraf/blob/develop/src/telegraf.ts

![image](https://user-images.githubusercontent.com/46839821/92246417-56d4e080-eee3-11ea-941e-4e3b03474ff9.png)

**Comment by ikerya** [comment]
![image](https://user-images.githubusercontent.com/49207045/94704849-079a9800-0349-11eb-9695-f140662efdd9.png)

I think the case is not in allowedUpdates, because as it seems, the getUpdates function is called and gets updates of a non array type, then an error is thrown. and the most important thing — the polling stops.

**Comment by imdkbj** [comment]
Check console for err. Pls share the code to reproduce the error.

**Comment by KnorpelSenf** [comment]
@ikerya please install the current `develop` branch and check if this is still an issue. Otherwise, please consider closing this.

**Comment by KnorpelSenf** [comment]
Closing because outdated.
