### ISSUE TITLE
sendVideo throws error

### ISSUE THREAD

**Issue by shazgames** [telegraf/telegraf#1106]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.18.3
* Operating System: Windows 7

## Expected Behavior

Calling bot.telegram.sendVideo(channelId, readStream) where bot is Telegraf instance should return success result. 

## Current Behavior

Throws ``` Error: 400: Bad Request: wrong URL host``` error

**Comment by shazgames** [comment]
If I pass video url instad stream everything is ok, but when pass stream sendVideo throws error

Code I use:
```
const Test = async () => {
  const readStream = fs.createReadStream("./697059707618.mp4")

  await bot.telegram.sendVideo(TELEGRAM_CHANNEL, readStream)
}
```

**Comment by shazgames** [comment]
Direct calling telegram api method sendVideo return success

**Comment by smithd-roses** [comment]
Due to [API](https://telegraf.js.org/#/?id=working-with-files): 
`bot.telegram.sendVideo(TELEGRAM_CHANNEL, { source: readStream })`

**Comment by KnorpelSenf** [comment]
What @smithd-roses says is correct, closing.
