### ISSUE TITLE
pin message

### ISSUE THREAD

**Issue by vineelsai26** [telegraf/telegraf#1107]
trying to pin a message with this 
```
bot.command('pin', (ctx) => {
    bot.telegram.pinChatMessage(ctx.chat.id, bot.telegram.message.message_id)
})
```
but nothing Is happening

**Comment by imdkbj** [comment]
This is wrong way!! U can't pin message on bot.

U have to pin into a group/channel.

So if u sending a new message then
```js
ctx.telegram.sendMessage(channelid,'xyz').then(({message_id})=>ctx.telegram.pinChatMessage(channelid,message_id))
```
or if u know the msg id.
```js
ctx.telegram.pinChatMessage(channelid,message_id)
```

**Comment by vineelsai26** [comment]
Can I do anything to find the message id of a message just by replying to it

**Comment by imdkbj** [comment]
Yes! reply and log u will get the message object attached with the body.

**Comment by PyJSBiba** [comment]
abobas blyat

**Comment by PyJSBiba** [comment]
> 
> 
> This is wrong way!! U can't pin message on bot.
> 
> U have to pin into a group/channel.
> 
> So if u sending a new message then
> 
> ```js
> ctx.telegram.sendMessage(channelid,'xyz').then(({message_id})=>ctx.telegram.pinChatMessage(channelid,message_id))
> ```
> 
> or if u know the msg id.
> 
> ```js
> ctx.telegram.pinChatMessage(channelid,message_id)
> ```

CUKA EBBANNAYA PADLA
