### ISSUE TITLE
Markup.formatHTML() misses the entities offset when special characters are used

### ISSUE THREAD

**Issue by dagema1** [telegraf/telegraf#1109]
## Context

i have a message object which contains an emoji and when i use sendCopy() to forward the message the inlne links starting point gets changed.

### original text
![image](https://user-images.githubusercontent.com/13154918/90575496-3529e880-e1c4-11ea-981d-255115815749.png)

### received with sendCopy() 
![image](https://user-images.githubusercontent.com/13154918/90575618-76ba9380-e1c4-11ea-826a-5684e0d4aec0.png)

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.18.3
* Operating System: windows 10 Home (version 2004)

## Expected Behavior

the message should be exactly as the first one.

**Comment by KnorpelSenf** [comment]
Fixed by #1105
