### ISSUE TITLE
WizardScene not going to next step on webhook

### ISSUE THREAD

**Issue by imdkbj** [telegraf/telegraf#1117]
## Current Behaviour
I am using bot.handleupdate but wizard auto flushing and leaving after the step 0.

What is the current behaviour? This seems a bug.

### Steps to Reproduce
Setup bot on webhook to get the issue. Working fine on polling.

Sample files 

Run polling.js for polling which will not have any issue.

Setup webhook for bot and run the handleupdate(msg)  and see the difference.

Sample
[test.zip](https://github.com/telegraf/telegraf/files/5120330/test.zip)

On Polling...

![image](https://user-images.githubusercontent.com/46839821/91098224-bc70d380-e67e-11ea-8a2b-9e4e391db7f2.png)

On webhook

![image](https://user-images.githubusercontent.com/46839821/91098294-d9a5a200-e67e-11ea-9665-868ea909a4aa.png)

**Comment by imdkbj** [comment]
Adding bot.launch() solved the issue. well documentation says we may avoid that.

**Comment by imdkbj** [comment]
After few analyse again this is an open issue.

Case:
1. If not using bot.launch() - wizard will not work
2. if using bot.launch() - wizard will work but webhook will be deleted [telegraf reference](https://github.com/telegraf/telegraf/blob/07042febbc8c3a39261e59384b298774c3d17ba0/src/telegraf.ts#L190) and it will convert to polling.
3. Using bot.launch with webhook option - wizard will not work

Can someone help how to solve this issue.  I have to use handleupdate as scaling multiple bots.


![image](https://user-images.githubusercontent.com/46839821/92309008-6cb7d380-efbf-11ea-8a22-8960492ee585.png)

**Comment by KnorpelSenf** [comment]
Can you retry with the current codebase on `develop`? The relevant parts of the library were recently rewritten, so I'm interested if this still happens.

**Comment by wojpawlik** [comment]
Was this fixed by 4.0.3?
