### ISSUE TITLE
m.switchToChatButton is not a function.

### ISSUE THREAD

**Issue by Starless-Sky** [telegraf/telegraf#112]
Hi. When I added the following part to `telegraf/helpers/markup` it worked. I don't know why it's not there. Maybe I should have called it from somewhere else?

```
  switchToChatButton (text, value, hide = false) {
    return Markup.switchToChatButton(text, value, hide);
  }
```

Thanks.

**Comment by dotcypress** [comment]
Thank you @Starless-Sky !
Changes published in `3.7.2`
