### ISSUE TITLE
Fetch old bot messages/ message-ids

### ISSUE THREAD

**Issue by ZerGo0** [telegraf/telegraf#1120]
Hey,

I'm trying to get the message-id of the last message from the bot in a private chat. I couldn't find anything in the docs, but maybe I'm just blind?

I know that I can get it from the message obj when I send/reply to messages, I don't need that.

**Comment by KnorpelSenf** [comment]
You need to store the ID yourself, so you need some sort of persistence. This could either be a file on your server, a database or a cloud storage provider (e.g. Google Cloud Firestore has a free plan).

`telegraf` supports so-called sessions. You can think of a session as an object of any shape that can be stored for every chat. Making use of session middleware gets you up and running with this in minutes, no matter which storage solution you prefer (e.g. I published `telegraf-session-firestore` to support Cloud Firestore).

**Comment by KnorpelSenf** [comment]
Also, have a look the `example-bot` for a simple way of storing data in memory.
https://github.com/telegraf/telegraf/blob/develop/docs/examples/example-bot.js

Note that this data will of course be lost as soon as you stop your bot.
