### ISSUE TITLE
Send local .zip file with sendDocument

### ISSUE THREAD

**Issue by Umberghost** [telegraf/telegraf#1122]
How can i do so, is there anyway i can send a local stored file as a document through telegraf api? I've tried with sendDocument, even with a localhosted website and requesting through 127.0.0.1 and it says "UnhandledPromiseRejectionWarning: Error: 400: Bad Request: wrong file identifier/HTTP URL specified" is there any way i can send those .zip?

Thanks in advance.

**Comment by imdkbj** [comment]
Try this!!

```js
bot.command('doc', ({
    replyWithDocument
}) => {
    const fileOptions = {
        source: '../test.zip',
        filename: "testfile.zip",
    };
    return replyWithDocument(fileOptions);
})
```

**Comment by Umberghost** [comment]
It does indeed work, thank you very much for your help, i will mark it as solved <3
