### ISSUE TITLE
formatHTML works wrong with emoji

### ISSUE THREAD

**Issue by ExposedCat** [telegraf/telegraf#1124]
Wrong offset with string with emoji
![image](https://user-images.githubusercontent.com/44642024/91661068-771b2e80-eae2-11ea-8aca-3f5e9bf42f43.png)

**Comment by Zamir-cc** [comment]
This article is a good reference what you are struggling with: https://flaviocopes.com/javascript-unicode/

**Comment by KnorpelSenf** [comment]
Using the correct values for `offset` and `length` should work. Thank you, @Zamir-cc, for the resource!
