### ISSUE TITLE
Hears but check if source is from group or pm

### ISSUE THREAD

**Issue by CyberMew** [telegraf/telegraf#1125]
I have something like this `bot.hears("hi", (ctx) => ctx.reply("Hey there"));`, but it just replies back to whoever sent it, even if it was in a group chat. How can I check against this and only selectively reply if this was sent privately?

Also I was trying to call `bot.telegram.sendMessage("@someuserhandle", "your message");` but there is an error and did not send at all. What gives?

**Comment by imdkbj** [comment]
log ctx.update.messge for both and see the difference.

bot.telegram.sendMessage("@someuserhandle", "your message") - Error??

**Comment by CyberMew** [comment]
Thanks, manage to get the chat type from message.

bot.telegram.sendMessage("@someuserhandle", "your message") - Error??
^ Yes apparently so, because (1) the user need to message the bot once, (2) I think @ is for channel/group, not user, so will need to reference number instead.

Will close this for now.
