### ISSUE TITLE
Keyboard doesn't pop up on iOS

### ISSUE THREAD

**Issue by paalex** [telegraf/telegraf#1137]
## Context
Telegraf.js Version: 3.38.0
Node.js Version: v10.21.0
Operating System: iOS

## Expected Behavior
Sending a reply with keyboard would bring up the keyboard

## Current Behavior
Keyboard stays closed

## Failure Information (for bugs)
No failure

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
 ```
const mainMenu = Markup.keyboard([Markup.callbackButton(DO_SOMETHING)]).oneTime().extra()
const inlineButton = Markup.inlineKeyboard([Markup.callbackButton(DO_SOMETHING_ELSE)]).removeKeyboard().extra()


ctx.reply("Here's the keyboard", mainMenu);

ctx.reply("Here's the keyboard removed and inline keyboard added", inlineButton);

ctx.reply("Here's the first keyboard added again, but it doesn't pop up on iOS. It DOES pop up on Android and macOS though...", mainMenu);
```

**Comment by ashitikov** [comment]
I think this is telegram's iOS client issue. As a solution you can send  a message with keyboard type - ReplyKeyboardRemove (https://core.telegram.org/bots/api#replykeyboardmarkup). And after that send a message with your mainMenu again. This should work.

**Comment by KnorpelSenf** [comment]
Bots are independent of the Telegram client of the users. This is not an issue with `telegraf`, so @ashitikov might be right.
