### ISSUE TITLE
Clearing message queue before polling

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#114]
Hello there,

I am aware of telegraf is accepting middleware in processing messages, but it comes to me a question, on how to clear the message queue -- letting the bot only answers to recent queries(e.g. <= 5m), instead of accepting all and causing a flood once the message queue was sent to the bot on startup.

Hopefully somebody can shed some lights on this puzzle.

Regards,
Ivan

**Comment by dotcypress** [comment]
Hey.

As fast solution, you can filter new updates:

```js
const { mount } = require('telegraf')

const dropOldUpdates = mount('message', ({ message }, next) => {
  const now = new Date().getTime() / 1000
  if (message.date > (now - 60 * 60 * 15)) {
    return next()
  }
})

// Bot code

const bot = new Telegraf()
bot.use(dropOldUpdates)
bot.use(...)
bot.use(...)

```
