### ISSUE TITLE
Why won't my bot send me a message?

### ISSUE THREAD

**Issue by unraujoe** [telegraf/telegraf#1141]
I have a working bot, it is running on my computer locally. I want to send a message to a telegram room or to me By PM when a user presses the start command. It would be a secondary function for the start command(is it possible for a command to trigger two functions?)

`//this has two inline options- begin and end
bot.start((ctx)=>{
    ctx.telegram.sendMessage(ctx.chat.id, 'This will take about 5 minutes! Are you ready to begin?',
    {
        reply_markup: {
            inline_keyboard: [
                [{text: "YES", callback_data: "begin"}, {text: "NO", callback_data: "end"}]
            ]
        }
    })
})`

`//this is a second start command
bot.command('start', ctx => {
    bot.telegram.sendMessage (-123456789, 'hello', ctx.from.id, ctx.chat.id)
    return ctx.reply('Hey')
  })`

**Comment by Zamir-cc** [comment]
If the first message send you are doing well but for second one to send you have to call `next()` in first one:
```javascript
bot.start( async (ctx, next) => {
  await ctx.reply('This will take about 5 minutes! Are you ready to begin?', { 
    reply_markup: {
      inline_keyboard: [ [{text: "YES", callback_data: "begin"}, {text: "NO", callback_data: "end"}] ]
    }
  });
  next();
})

//this is a second start command bot.
```

**Comment by KnorpelSenf** [comment]
What @Zamir-cc says is correct and fixes the problem.

If you need further guidance, check out [this section of the docs](https://telegraf.js.org/#/?id=middleware) or read things on the internet about middleware. It is a concept that is used in many different places, so it should be easy to find good explanations about it, so you can apply it to your bot.
