### ISSUE TITLE
Going back to previous scene

### ISSUE THREAD

**Issue by Antik22** [telegraf/telegraf#1142]
Hey, I have such a user profile scene (from **BaseScene**) and I enter on it from different scenes. Is it possible to go back exactly to scene from which I entered on this scene. I tried to use '**leave()**' but it's just going out of all scenes.
Also I read about **WizardScene**, but as I understood it's not want I am looking for...

Now I came up with idea to make a subclass of **BaseScene** and store the last scene in **'ctx.scene.state'** on every '**leave**' event. What do you think about it? Is it a good solution or you can recommend something different?
Thanks for your help!

**Comment by wojpawlik** [comment]
See #915. It'd need to be redone -- the file was ported to TS.

**Comment by KnorpelSenf** [comment]
> Now I came up with idea to make a subclass of **BaseScene**

That is one option, even though it can be difficult to get all the types right here. `WizardScene extends BaseScene` may help you.

Otherwise, it would be much simpler to add middleware that detects when you changed the scene, and pushes this on a stack.

```ts
// Something like this
bot.use(async (ctx, next) => {
  const oldScene = ctx.scene.session.current
  await next()
  if(ctx.scene.session.current !== oldScene) {
    ctx.scene.session.history ??= []
    ctx.scene.session.history.push(oldScene)
  }
})

// This is now how you can go back
bot.command('back', (ctx) => {
  const back = ctx.scene.session.history.pop()
  if (back) ctx.scene.enter(back) // navigate back
  else ctx.scene.reenter() // already at oldest scene
})
```
Untested. Never executed it.

If you use TypeScript, check out the new example bots on how to extend the `ctx.scene.session` object by the `history` property.

Please reopen if you have further questions.

**Comment by wojpawlik** [comment]
This looks like a perfectly reasonable pull request (#915), are there any hidden difficulties in implementing it?

**Comment by KnorpelSenf** [comment]
> This looks like

Can you elaborate on what _This_ is? Do you mean the idea of being able to go back to the previous scene, or #915? Or do you want to make the above middleware built-in or something?

**Comment by wojpawlik** [comment]
I think the best implementation would be adding `BaseScene::return()`.

**Comment by KnorpelSenf** [comment]
Thanks for the clarification. I'm not sure if we want to use a keyword as function name, but I get now where you were going
