### ISSUE TITLE
Catch and log sending messages (reply)

### ISSUE THREAD

**Issue by chuve-tov** [telegraf/telegraf#1143]
I can't find a current way to catch messages which bot send via a "reply" shortcut. The reason is to save messages in my DB to have a persistent log of messages from both sides (bot & client)

Example:
```
const onboarding = new Scene('onboarding');
onboarding.leave((ctx: any) => {
  const username = ctx.message.from.first_name || ctx.message.from.username;
  ctx.reply(`Bye ${username}`);
});
```

So I need a way how to catch sending an event, but I don't know what the right way to do it?

Any suggestions?

**Comment by sagadav** [comment]
Why not log messages right at the time of sending?

**Comment by KnorpelSenf** [comment]
I don't really know why you'd need the sent message as *an event*. You can easily get the message you sent by writing
```js
const sentMessage = await ctx.reply('My message')
```
so you can handle it further from there. That's basically what @sagadav is saying.

If you need to have it as an event for some reason, you can of course dispatch that yourself …
