### ISSUE TITLE
Delete History Method

### ISSUE THREAD

**Issue by Romans96** [telegraf/telegraf#1148]
**Describe the solution you'd like**
The possibility to clear the entire chat (for the selected user) message. Via Telegram i can do "Clear History"

**Describe alternatives you've considered**
I see that the Telegram API implements that method:
https://core.telegram.org/method/messages.deleteHistory

But i cannot find it on Telegraf documentation anywhere

**Comment by kolay-v** [comment]
`deleteHistory` is mtproto method but telegraf is telegram bot api library. You should look at bot api docs https://core.telegram.org/bots/api
