### ISSUE TITLE
Sending alert instead of message

### ISSUE THREAD

**Issue by newtoniumx3** [telegraf/telegraf#1149]
Is there a way to send the "baloon" type alert message instead of sending a message to the channel?

When responding to a message this does what I want.
`ctx.answerCbQuery(`My message`);`

How could I trigger that from just the telegraf bot instance variable?
`instance.telegram....()`

If not what are my options to give the user some sort of feedback of the processing happening, without spamming the channel for everyone?

**Comment by KnorpelSenf** [comment]
Have a look at the parameters that `ctx.answerCbQuery` takes: https://telegraf.js.org/#/?id=answercbquery

Use `text` to set your message and play around with `showAlert` to adjust the appearance of it.
