### ISSUE TITLE
[Solved] setGameScore & getGameHighScores has error if game starts from bot

### ISSUE THREAD

**Issue by amlashi-sadra** [telegraf/telegraf#115]
If a user starts a game from bot, when i want call **getGameHighScores** i should pass `userId` & `chatId` & `messageId`, but the error is:
```
Error: 400: Bad Request: chat not found
```
same as **getGameHighScores** the **setGameScore** pass the error:
```
Error: 400: Bad Request: wrong inline message identifier specified
```
there is no problem if I use `inlineMessageId` instead of `chatId` & `messageId`, but there is no `inlineMessageId` when game starts from bot.
what should I do? where is the problem?

**Comment by dotcypress** [comment]
You can see example usage of  `getGameHighScores` and `setGameScore` [here](https://github.com/telegraf/microgames/blob/master/index.js#L74)

```js
telegram.getGameHighScores(user, imessage, chat, message)
telegram.setGameScore(user, scoreValue, imessage, chat, message)
```

**Comment by amlashi-sadra** [comment]
how can i send imessage when i don't have it?
when a user start chat from bot, there is no imessage, there is just **chatId** & **messageId**, there is no **inlineMessageId**.
inlineMessageId is accessible just in a group chat.
by the way, when i pass **messageId** and **chatId** it can't find the chat

**Comment by amlashi-sadra** [comment]
I found the answer:
if a user starts game from a group chat, you should pass just **inline_message_id**
but if a user starts game from a bot, you should  pass 3 items, **id**, **chat_id** and **user_id**
you should ask which **id**?
the answer is here, when a user starts the game, you cand get these 3 parameters from the **gameQuery**
```json
{
  **"id": "1122334455",**
  "from": {
    **"id": 1122334455,**
    "first_name": "xxxxx",
    "last_name": "xxxxx",
    "username": "xxxxx",
    "language_code": "en"
  },
  "message": {
    **"message_id": 123,**
    "chat": {
      **"id": 1122334455,**
      "first_name": "xxxxxx",
      "last_name": "xxxxxx",
      "username": "xxxxxxx",
      "type": "private"
    }
  },
  "chat_instance": "000000000000",
  "game_short_name": "xxxxxxxx"
}
```

**Comment by dotcypress** [comment]
You can pass `undefined` for missing data

**Comment by amlashi-sadra** [comment]
yes, that's work with `'undefined'` too!!! :|
