### ISSUE TITLE
How do I create a keyboard that won't send right away?

### ISSUE THREAD

**Issue by e2sence** [telegraf/telegraf#1151]
Please tell me how to make a numeric keypad
1 2 3 +
4 5 6 -
7 8 9 *
0 . / =
sending a message from which will be performed by clicking the "=" button

I think that this picture from https://core.telegram.org/bots shows what is needed, but I cannot find a solution
![b397dfcefc6da0dc70](https://user-images.githubusercontent.com/32023734/95254487-9ebf8e00-0828-11eb-8a7d-9406fae76783.jpeg)
Help!

**Comment by KnorpelSenf** [comment]
You cannot control this, that's how Telegram works. If a user clicks one of those buttons, a message will be sent.

You have two options:
1) Delete the message from the user immediately. You can maybe edit the last message of the bot and append the sent character, that way it will look like the user is appending digits to an input field. Note that there will be a lot of flickering, though.
2) Do not use this type of keyboard, instead, use an inline keyboard. It will look differently (buttons underneath a message), but that one won't always send a message when a button is pressed.

**Comment by e2sence** [comment]
I still do not understand why there is no normal numeric keyboard

**Comment by KnorpelSenf** [comment]
Ah sorry, I think I misread your question. You can of course change the symbols of the bottoms as you wish.

Check out https://core.telegram.org/bots/api/#replykeyboardmarkup for docs about how to define your own keyboard layout and maybe [this example bot](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js) to see how it's used. with telegraf

**Comment by e2sence** [comment]
> Check out https://core.telegram.org/bots/api/#replykeyboardmarkup for docs about how to define your own keyboard layout and maybe [this example bot](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js) to see how it's used with telegraf

 ))  Thanks for your participation
Unfortunately this particular option is not suitable, the message is sent after clicking the button

**Comment by KnorpelSenf** [comment]
Well you have to combine what I said firstly with what I said lastly. Create your own layout, then register the incoming messages and merge them into one user input.

Or use an online keyboard because that does not send messages all the time.

You should really check out the Telegram docs on bots, I'll not copy and paste them here ;)
