### ISSUE TITLE
how to recognize user mention in text message ?

### ISSUE THREAD

**Issue by ArtricPlayer** [telegraf/telegraf#1153]
i saw the **bot.mention** but i need the username of the user in this case i dont have it
so my question is:
how do i recognize if in text message there is mention of user/channel/group ?

thank you very much

**Comment by Zamir-cc** [comment]
Use a regex!
```
bot.hears(/@([a-z0-9]+(_?[a-z0-9]+)*)/ig, console.log)
```
Warning: not tested the above code.

**Comment by kraftwerk28** [comment]
You can use [message entities](https://core.telegram.org/bots/api#messageentity), since Telegram parses them automatically. Just like
```js
bot
  .on('text', async (ctx, next) => {
    const text = (ctx.message.entities || [])
      .filter(entity => entity.type === 'mention')
      .map(mention => ctx.message.text.slice(mention.offset, mention.length))
      .join(' ');
    if (text.length) {
      await ctx.reply(text);
    }
    next();
  });

```
