### ISSUE TITLE
How to demote admin that was promoted manually?

### ISSUE THREAD

**Issue by dave-dm** [telegraf/telegraf#1155]
I'm using this code
```
await ctx.promoteChatMember(userId, {
        can_change_info: false,
        can_post_messages: false,
        can_edit_messages: false,
        can_delete_messages: false,
        can_invite_users: false,
        can_restrict_members: false,
        can_pin_messages: false,
        can_promote_members: false
})
```

If the bot promoted this user, he can demote him, but if I (the owner) promote him, he can't demote, it says "CHAT_ADMIN_REQUIRED" but the bot has all everything checked "yes" in the admin privileges in the mac desktop client.

**Comment by KnorpelSenf** [comment]
Admins in Telegram follow a promotion hierarchy. You are only allowed to manage the admins you promoted. In other words, a newly promoted admin cannot simply demote all others, and the same is true for bots.

This has nothing to do with telegraf in particular, it's about the way Telegram is designed.

**Comment by dave-dm** [comment]
is there any workaround at all?

**Comment by KnorpelSenf** [comment]
If a bot promotes you and you then promote a third member, then the bot can demote the third member again.

If you promoted the bot, then no, there is no “workaround” around security. The bot cannot take right away from you or other independent admins. (Image what happened if this was possible.)
