### ISSUE TITLE
[Question] How to identify if user has shared his own contact or someone else's for authentication

### ISSUE THREAD

**Issue by Dr-Phone** [telegraf/telegraf#1157]
I ask user to share his contact using 'request_contact' directive and then listen to 'contact' update type. However, user has option to click on the inline keyboard and share his own contact (desired) or can share someone else's contact from his contact list.

How can I force user to always share his own contact? OR 
find out when he has shared someone else's?

example code:

const welcomeMessage = 'Please share the your phone number to continue.';

        await ctx.telegram.sendMessage(ctx.chat.id, welcomeMessage, {
            parse_mode: "Markdown",
            reply_markup: {
                one_time_keyboard: true,
                keyboard: [
                    [{
                        text: "Share Phone Number",
                        request_contact: true
                    },
                    {
                        text: "Cancel"
                    }],
                ],
                force_reply: true
            }
        });

        this.bot.on("contact", (ctx: Context) => {
            const contact = ctx.message.contact.phone_number;
            if (phone_numer is someone else 's)
            ctx.reply('please share your own number');
                else {
                if (registered(contact){
                    ctx.reply('You can use the service now...');
                }
                else {
                    ctx.reply('Please register at example.com');
                }
            }

        });

**Comment by smaznet** [comment]
You should check 

``` js
if(ctx.message.contact.user_id !== ctx.from.id){
// The user sent other user contact
}

```
