### ISSUE TITLE
Wrong typings in 3.38.0

### ISSUE THREAD

**Issue by howHighUR** [telegraf/telegraf#1165]
You have wrong typings in the latest release, js files have methods that are not declared in d.ts. For example, there is setChatStickerSet method in telegram.js and no declaration for it in telegram.d.ts

**Comment by muuuzmich** [comment]
Yup, issuing the same trouble

**Comment by seryogium** [comment]
Issuing the same trouble

**Comment by YaMaZZZim** [comment]
Same issue

**Comment by AlexQuidditch** [comment]
Also still have no typings for WizardScene

**Comment by prakx1** [comment]
I want to work on this issue , can you guide me?

**Comment by foodornt** [comment]
@AlexQuidditch unfortunate

**Comment by foodornt** [comment]
Actually I installed the develop branch and I got some wizardscene typings
still not correct

**Comment by AlexQuidditch** [comment]
@foodornt 

Do u have any idea how we can do our own typings?

**Comment by KnorpelSenf** [comment]
This is actively being worked in #1177. The previous types were handwritten and did not always correspond to the code. #1108 largely fixed this by pulling in `typegram` types. However, there are upcoming breaking changes that require a new major version. We want to make sure the examples work before releasing that, hence #1177. Everything is expected to work soon:registered: in 4.0 .

**Comment by KnorpelSenf** [comment]
@AlexQuidditch can you try out the types from #1194, validate that they are correct, and confirm that we can merge them?
