### ISSUE TITLE
[Question] replyWithVideo method with custom headers

### ISSUE THREAD

**Issue by Mohamed-Magid** [telegraf/telegraf#1169]
It's not really a question about Telegraf itself more than a question about telegram bot API. If the URL of the photo or the video I'm trying to send using the bot is only accessible using a custom header that should be sent with the request. Is there a way to **pass these headers to telegram API** to use it to fetch the file? I know that telegraf's methods like ```replyWithPhoto``` or ```replyWithVideo``` is only a simplifying for ```sendPhoto``` and ```sendVideo``` methods by adding the chat ID by default so it's not really a something Telegraf can do. I tried to use axios to make the request and pass the stream response to telegram API but it's really painful and sometimes it doesn't work. So, any ideas?

**Comment by sagadav** [comment]
You can get an image via axios and then pass it to the sendPhoto method as multipart/form-data
https://core.telegram.org/bots/api#sendphoto
