### ISSUE TITLE
Error [ERR_STREAM_WRITE_AFTER_END]: write after end, when use Webhook

### ISSUE THREAD

**Issue by AndriiHryhorovskyi** [telegraf/telegraf#1170]
## Context
Delayed sending a response throws an error if you use webhooks, but if you use long polling the message will be sent.

* Telegraf.js Version: 3.38.0
* Node.js Version: 14.15.0
* Operating System: Linux 5.8.16-2-MANJARO

## Expected Behavior

It must send a message

## Current Behavior

Throw the error

#### WebHook
```javascript
const express = require("express");
const ngrok = require("ngrok");
const { Telegraf } = require("telegraf");

const PORT = 3000;
const BOT_TOKEN = "";

const app = express();
const bot = new Telegraf(BOT_TOKEN);

bot.use(Telegraf.log());
bot.start(ctx => ctx.reply("start command"));
bot.on("text", ctx => {
  setTimeout(() => ctx.reply("message"), 0);
});
app.use(bot.webhookCallback(`/${BOT_TOKEN}`));
ngrok
  .connect(PORT)
  .then((serverUrl) => {
    bot.telegram.setWebhook(`${serverUrl}/${BOT_TOKEN}`);
    app.listen(PORT, () => console.log(`Server started on port ${PORT}`));
  })
  .catch((err) => console.error(err));

````
#### Long polling
````javascript
const express = require("express");
const ngrok = require("ngrok");
const { Telegraf } = require("telegraf");

const PORT = 3000;
const BOT_TOKEN = "";

const app = express();
const bot = new Telegraf(BOT_TOKEN);

bot.use(Telegraf.log());
bot.start((ctx) => ctx.reply("start command"));
bot.on("text", (ctx) => {
  setTimeout(() => ctx.reply("message"), 0);
});
app.listen(PORT, () => console.log(`Server started on port ${PORT}`));
bot.launch();

````
### Failure Logs
![image](https://user-images.githubusercontent.com/50585074/97809148-ec86b500-1c73-11eb-9fda-e5397f05eae4.png)

**Comment by wojpawlik** [comment]
https://github.com/telegraf/telegraf/blob/fc5882cd52505aa81b7d0f8620838b9a6b4dad40/src/core/network/client.ts#L332 needs to be changed to `!response.writableEnded`, however

1. it'd likely conflict with #1082,
2. it would probably mean dropping `webhookReply` support for Koa; not a big loss IMO, I wouldn't mind it gone entirely.
