### ISSUE TITLE
keep break lines in message content

### ISSUE THREAD

**Issue by skmohammadi** [telegraf/telegraf#1175]
Hi. It seems break lines at end of message are skipping.

```
wellcomeMsg = "Hello\n\n How are you today?\n\n";
reply(wellcomeMsg);
```

![Annotation 2020-11-08 103517](https://user-images.githubusercontent.com/12100097/98459229-1ed16e80-21ae-11eb-8e2c-9c8d69d9ddae.png)

how we can keep break lines at the end of message content?

* Telegraf.js Version: 3.38.0

**Comment by sagadav** [comment]
You can't break lines at the end of messages in a telegram

**Comment by skmohammadi** [comment]
> You can't break lines at the end of messages in a telegram

But some month before, there is not this problem in some frameworks such as Slimbot.js , ...

**Comment by imdkbj** [comment]
The some month ago is one year old message as well as that is Right to left typo and in English left to right typo.

If u will send same message now, should to get that old experience. Can't sure that is possible with English.
