### ISSUE TITLE
Failed to get updates on now.sh

### ISSUE THREAD

**Issue by henriquea** [telegraf/telegraf#118]
Hi there 👋,

I started to get these errors on now:

```
06/06 01:14 AM (744ms)
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates method while webhook is active
    at TelegramError (/home/nowuser/src/node_modules/telegraf/lib/network/error.js:3:5)
    at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  response: undefined,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',
  retryAfter: undefined,
  migrateToChatId: undefined }
```

How do I fix that?

Many Thanks!

**Comment by henriquea** [comment]
@dotcypress I'm using micro-bot on now.sh `"start": "micro-bot -d index.js"` the first deployment was successful. After a couple of minutes the bot was down and checking the error log I got the message above. If I try to deploy again with `now -e BOT_TOKEN=xxxx` I get the follow error:

```
> > micro-bot -d index.js
> μ-bot :: Starting @CryptoJediBot
> Failed to get updates. Waiting: 1s { Error: 409: Conflict: terminated by other long poll or webhook
>     at TelegramError (/home/nowuser/src/node_modules/telegraf/lib/network/error.js:3:5)
>     at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
>     at process._tickCallback (internal/process/next_tick.js:109:7)
>   code: 409,
>   response: undefined,
>   description: 'Conflict: terminated by other long poll or webhook',
>   retryAfter: undefined,
>   migrateToChatId: undefined }
> μ-bot: Failed to start bot: Error: 400: Bad Request: bad webhook: getaddrinfo: Name or service not known
```

The bot is pretty simple https://gist.github.com/henriquea/080d31bb9bef438f022fc0e101c1d34b

Thanks for your quick response Vitaly ✊

**Comment by dotcypress** [comment]
You need to change start script with following: `"start": "micro-bot -d ${NOW_URL} index.js"`,
and make some changes in your code: https://gist.github.com/dotcypress/a0ef5897c8ccd3a401589f90e258fa9c

FYI: https://zeit.co/docs/deployment-types/node#deployment-inactivity

**Comment by henriquea** [comment]
@dotcypress hands down! 🙇

Ah ok I should use the `Composer` from micro and starting the pooling at the end was messing everything up.

Cheers mate 🍻

**Comment by MikeMajara** [comment]
@henriquea could you extend your description. I'm encountering the same error.
