### ISSUE TITLE
How to connect telegraf to a Local Bot API Server

### ISSUE THREAD

**Issue by zyadomer999** [telegraf/telegraf#1180]
Hello

Can anyone please tell me how to change the server used by telegraf from "https://api.telegram.org/" to my server?

I have already the server successfully and it works properly but do not know how to connect it to telegraf.

I mean this server:
<img width="834" alt="Screen Shot 2020-11-13 at 7 33 31 AM" src="https://user-images.githubusercontent.com/66646536/99029104-a9d1b080-2582-11eb-8254-d0f35c6212ed.png">

**Comment by jumoog** [comment]
instead of 

```JS
new Telegraf(process.env.BOT_TOKEN));
```
do 

```JS
new Telegraf(process.env.BOT_TOKEN), { telegram: { apiRoot: 'http://localhost:8081' } });
```

**Comment by zyadomer999** [comment]
Thank you very much for your help
