### ISSUE TITLE
Bug with bot.hears after ctx.sendMessage twice in one session

### ISSUE THREAD

**Issue by Ksedline** [telegraf/telegraf#1182]
## Bug with bot.hears after ctx.sendMessage

* Telegraf.js Version: 3.38.0
* Node.js Version: 14.8.0
* Operating System: Mac OS Big Sur 11.0.1

## Expected Behavior

bot.hears would listen any text sent via ctx.sendMessage with reply_markup: [{ 'keyboard': ['Key'] }]

## Current Behavior

bot.hears would listen and answer any text sent via ctx.sendMessage with reply_markup: [{ 'keyboard': ['Key'] }] only at once

## Failure Information (for bugs)

After hours of debugging I found that Composer.compose in composer.js method actually find this text anytime in context or ctx, but do nothing with that after second user's answer.

Reloading the bot helps to get an answer by bot if it stucks after second time.

### Steps to Reproduce

1. Send message to a user with 
```
await ctx.telegram.sendMessage(userToSendId, '<b>Test</b>', { parse_mode: 'HTML', reply_markup: JSON.stringify({ 'keyboard': [['Accept']] })});
```
also subscribe bot for 'Accept':
```
bot.hears('Accept', async (ctx) => await ctx.reply('Accepted'));
```
2. If you will send keyboard second time - bot.hears don't registrate 'Accept' and don't reply 'Accepted' to user

### Failure Logs
No specific logs or Error :(

**Comment by KnorpelSenf** [comment]
I'm not sure if I understand this correctly … are you saying that `bot.hears` only works once, and then the bot needs to be restarted?

**Comment by Ksedline** [comment]
Yes. 
You can reproduce it when trying to send message with keyboard dirrectly from bot ctx.telegram.sendMessage

**Comment by KnorpelSenf** [comment]
I did not manage to do reproduce that, and I have several bots running in production that are not suffering from this.

Could you maybe share an [SSCCE](http://sscce.org/)?

**Comment by Ksedline** [comment]
Sure, I do it later in this issue

**Comment by Ksedline** [comment]
I talk with my co-developer and we can't reproduce that bug. Sorry for wasted time

**Comment by KnorpelSenf** [comment]
No problem, I'm glad it's solved :)

**Comment by Hisahito** [comment]
I have a similar problem with the bot.hears method: 
bot.hears('Hello', (ctx) => { 
    ctx.message("Alola and Welcome, its good to see you here!" + ctx.from.first_name)
   })

nothing happneds and bot doesnt react! he only respond with commands /start /help but cant hear and responds when i text it "Hello"
hope you guys can help me.

**Comment by rumta123** [comment]
bot.hears('Привет', (ctx) => {
ctx.reply(`Алола и добро пожаловать, рад вас здесь видеть! + ${ctx.from.first_name}`)
})

**Comment by alexiiispc** [comment]
Hello in my case when you execute the command `bot.command("valor",(ctx)=>{
  bot.hears(...)

HERE I WANT TO FINISH LISTENING
})`

**Comment by MKRhere** [comment]
@alexiiispc You shouldn't add listeners within other listeners. You should use a Wizard instead. You should also not necropost in an unrelated issue. Open a new issue or discussion if you need more help.
