### ISSUE TITLE
Unset the bot.command or bot.hears or bot.action triggers

### ISSUE THREAD

**Issue by d0vdr0xx** [telegraf/telegraf#1185]
Is there any way to unset or unbind the command/action/hears triggers to reload them from file? Well, basically, i have every command or trigger in a different file, so is there a way to reload the thing without need to restart whole bot

**Comment by wojpawlik** [comment]
As of 3.38, you can replace "attached" `Composer`'s `handler` with one taken from updated `Composer`. TypeScript will complain, because it's an implementation detail that can change anytime.

**Comment by d0vdr0xx** [comment]
Uhh, you mean like I need to create a new Composer and update it in Telegraf instance?

**Comment by wojpawlik** [comment]
```js
oldComposer.handler = newComposer.handler
```

**Comment by d0vdr0xx** [comment]
So every reload I have to create new Composer to update handlers?
