### ISSUE TITLE
how Can I ask user location?

### ISSUE THREAD

**Issue by stefanocudini** [telegraf/telegraf#1188]
Only way founded is read ctx.message.location...

but I want ask send location from user

how can implement it?

**Comment by stefanocudini** [comment]
my not good solution :-(

```javascript

bot.command('gps', ctx => {
	ctx.reply('send your position');
	
});

bot.on('message', ctx => {
	if(ctx.message.location) {
		var res = elevation(ctx.message.location)
		ctx.reply(res+'metri slm');
	}
})


```

**Comment by wojpawlik** [comment]
Search `request_location` in https://core.telegram.org/bots/api

**Comment by stefanocudini** [comment]
ooh tnks, but how can I implement it in telegrafjs?

**Comment by stefanocudini** [comment]
how can I send a button via telegrajs? :-/

**Comment by KnorpelSenf** [comment]
Have a look at the example bots, specifically [this line](https://github.com/telegraf/telegraf/blob/d2126819c47f8668fedb4f9e4fe17c69ac2ce723/docs/examples/keyboard-bot.js#L35) of the `keyboard-bot`.

**Comment by stefanocudini** [comment]
```const { Markup } = require('telegraf');
bot.command('location', ctx => {
  return ctx.reply(
    'Special buttons keyboard',
    Markup.keyboard([
      Markup.button.locationRequest('Send location')
    ]).resize()
  )
})
```

```
TypeError: Markup.button.locationRequest is not a function
      at bot.command.ctx (/home/z4k/www/weather_bot/index.js:91:21)
      at Promise.resolve.then (/home/z4k/www/weather_bot/node_modules/telegraf/composer.js:143:56)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by KnorpelSenf** [comment]
@stefanocudini you're not using the same version of example bot and library. When the code evolves, the example bots are adapted to that. You're using the example is from the `develop` branch, but the error looks like you're using the latest stable version of the library from the `master` branch (that's what npm ships).

Maybe it can help you to use an editor like VSCode that provides content assist for the methods and that allows you to peek the lib's code. This makes it much easier to find out how things work, it shouldn't be a necessity to ask everything here :)
