### ISSUE TITLE
Error when running inside of docker

### ISSUE THREAD

**Issue by lukasz-kaniowski** [telegraf/telegraf#119]
Hi, 
I'm getting this error when I run bot from inside of docker container
```
Failed to get updates. Waiting: 1s { Error: 404: Not Found
    at TelegramError (/usr/src/app/node_modules/telegraf/lib/network/error.js:3:5)
    at buildPayload.then.then.then.then (/usr/src/app/node_modules/telegraf/lib/network/client.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 404,
  response: undefined,
  description: 'Not Found',
  retryAfter: undefined,
  migrateToChatId: undefined }
```
I'm using `startPolling()` to initiate bot

**Comment by henriquea** [comment]
I'm getting the same error in now.sh as I reported here #118. I tried to clear the messages queue as suggested here #114 but no luck so far.

**Comment by dotcypress** [comment]
Could you provide steps to reproduce?

**Comment by lukasz-kaniowski** [comment]
I found the issue. It was actually misconfiguration on my side. I was using docker env file and put token with `""`, ie:
```
BOT_TOKEN="XXXXXXX:YYYYYYYYYYYYYYY"
```
After changing this to:
```
BOT_TOKEN=XXXXXXX:YYYYYYYYYYYYYYY
```
this problem goes away.

**Comment by henriquea** [comment]
@dotcypress I still having issues. I'll post on #118
