### ISSUE TITLE
Get username by reply to a message

### ISSUE THREAD

**Issue by Antihero64** [telegraf/telegraf#1190]
I try to build a small Tipbot, and at the moment it works with the command /tip @Username, 
now i try to implement a mechanism which allows to reply to a message simply with /tip, 
and the bot use the username from the message. 

But i can´t find anything in the documentation i can use for.

**Comment by KnorpelSenf** [comment]
You can access the user of that message with `ctx.message.reply_to_message.from`. The username can in turn be accessed with `ctx.message.reply_to_message.from.username`.

Note that both `reply_to_message` and `username` are optional fields, i.e. they may not be present.

You can find out about this by first looking at which information is present in the `ctx` object: https://telegraf.js.org/#/?id=context
There you can see that the received message object is accessible through context. The official Telegram Bot API docs then tell you what a message is and how to get to the username you're looking for: https://core.telegram.org/bots/api#message
