### ISSUE TITLE
How to open chat with callback button?

### ISSUE THREAD

**Issue by Romans96** [telegraf/telegraf#1193]
hellO! I've a callbackbutton that calls a functions that send some text in the user private chat.

I've seen a bot that did the same thing but pressing the button it open directly the user chat. SO how can i do that with clalback button (NOT with URL button)?

Because i need to pass something via the button press so i cannot use the url button. Thank you

**Comment by KnorpelSenf** [comment]
There are a number of different buttons you can send. It is probably the best thing to check out the official documentation on which buttons you can send: https://core.telegram.org/bots/api#inlinekeyboardbutton

All of these options can be used in `telegraf` via the inline keyboard buttons provided by `Markdown`. The example bot on keyboards might help you here: https://github.com/telegraf/telegraf/blob/master/docs/examples/keyboard-bot.js

**Comment by wojpawlik** [comment]
Try [deep linking](https://core.telegram.org/bots/#deep-linking).

**Comment by wojpawlik** [comment]
Pass `url` to your bot to `answerCallbackQuery`.
