### ISSUE TITLE
Error: 400: Bad Request: message is not modified

### ISSUE THREAD

**Issue by stupicode** [telegraf/telegraf#1198]
app crash on `editMessageCaption` if edit message and replace with same thing.

console Error:
Error: 400: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message

suggest telegraf most ignore change or hint and no crash or stop app.

* Telegraf.js Version: 3.38.0
* Node.js Version: 15.3.0
* Operating System: arch linux 5.9.10-arch1

**Comment by wojpawlik** [comment]
There's no precedent for hiding API errors in Telegraf, they are left up to library user to [handle](https://github.com/thedevs-network/the-guard-bot/blob/8b9babf987da1b48845be6ba809577abe50664a5/handlers/middlewares/monkeyPatch.js) / avoid.
