### ISSUE TITLE
TS: Property 'session' does not exist on type 'TelegrafContext'.

### ISSUE THREAD

**Issue by ynhhoJ** [telegraf/telegraf#1203]
**Is your feature request related to a problem? Please describe.**
Types of `session` are undefined for TS and they aren't viewed by `TelegrafContext`.

**Describe the solution you'd like**
Connect `session`'s types to main `TelegrafContext`.

Way what i use and get error:

```typescript
import { Telegraf, session } from 'telegraf';

const bot = new Telegraf(process.env.BOT_TOKEN);
bot.use(session());

bot.on('text', (ctx) => {
    // TS2339: Property 'session' does not exist on type 'TelegrafContext'.
    ctx.session.counter = ctx.session.counter || 0;
    ctx.session.counter++;

    return ctx.reply(`Message counter: ${ctx.session.counter}`);
  });
bot.launch();
```

**Comment by wojpawlik** [comment]
Specify type of `ctx.session`, see https://github.com/telegraf/telegraf/blob/d2db6df67d54ea5e14ee06382d7c4009c97c78be/docs/examples/example-bot.ts and #914.

Be careful, it's possible to specify a type that's incorrect. To improve that, I'd have to change `Composer` to chain immutably, and `Telegraf` wouldn't be able to inherit from it anymore.

**Comment by ynhhoJ** [comment]
Hm, yes, it's works. Thank you!
