### ISSUE TITLE
Move to `typedoc`

### ISSUE THREAD

**Issue by wojpawlik** [telegraf/telegraf#1205]
- [x] Set up a GitHub action to publish docs on GitHub Pages every release.
- [ ] Try to build docs anyway at every commit to spot breakage early.
- [x] Remove (now redundant) handwritten API reference.
- [x] Try to make `docs/README.md` shorter. Move information into JSDoc. Remove junk. Deduplicate.
- [ ] Avoid putting example code directly into readme, since it's not typechecked there and can easily get outdated.
  Prefer putting it in `docs/examples/` and linking to it.
  Or perhaps embed it with `<iframe>`, Github escapes it, but `marked` used by `typedoc` [doesn't](https://www.npmjs.com/package/marked#usage) 😈
- [x] Make sure `docs/README.md` contains everything from `readme.md`.
- [x] Remove `readme.md`, now inferior to `docs/README.md`.
- [x] Move `docs/README.md` back to root and update https://github.com/telegraf/telegraf/blob/1f7dee72c702bdf05791ccba2a8a8c3b3c6f9dfc/tsconfig.json#L19

**Comment by KnorpelSenf** [comment]
Playing around with a 0.20 beta version of `typedoc`, I found that we can specify a number of every points. Only type definitions of actually exposed modules will be included in the docs. Right now, the website is extremely cluttered. As a newcomer, this is overwhelming.

I agree that we should use typedoc, but it's only half of what we need. The other half are guides and tutorials on how to use it. An API reference is not helpful if you don't know the purpose of it.

**Comment by KnorpelSenf** [comment]
@wojpawlik where would we write a quickstart guide if we wanted to begin with that?

**Comment by wojpawlik** [comment]
In README I think, after cleaning it up.

**Comment by KnorpelSenf** [comment]
In other words, `typedoc` does not allow writing separate pages in addition to the generated ones? I did not manage to find something like that
