### ISSUE TITLE
Disable link preview

### ISSUE THREAD

**Issue by Bostrot** [telegraf/telegraf#121]
I can not find in the docs how to disable the annoying link preview. Anyone knows how to?

**Comment by dotcypress** [comment]
Try following:

```js
const { Extra} = require('telegraf')
bot.reply('Hello http://github.com', Extra.webPreview(false))
```

**Comment by bubakazouba** [comment]
Extra.webPreview(false) returns an Extra, so you can chain it.

``
let markup = Extra.webPreview(false).HTML().markup((m) => {
	return m.inlineKeyboard(m.callbackButton("text", `action`));
});
ctx.reply("msg", markup);
```
