### ISSUE TITLE
Callback_query namespace event emitter ?

### ISSUE THREAD

**Issue by Shoyad** [telegraf/telegraf#123]
How to handle callback_query how:

category.subcategory

Can Telegraf provide namespace event emitter ? 

For example:

bot.action("category")?

**Comment by dotcypress** [comment]
You can use regular expression: 
```js
bot.action(/category.+/, (ctx) => { ... })
```
or predicate function
```js
bot.action((text) => text.startsWith('category'), (ctx) => { ... })
```

**Comment by Shoyad** [comment]
Thanks

**Comment by dotcypress** [comment]
@Shoyad waiting for next message is really bad pattern(bot restart will kill all state), use [FSM](https://en.wikipedia.org/wiki/Finite-state_machine) instead.

With telegraf you can use [`telegraf-flow`](https://github.com/telegraf/telegraf-flow)

**Comment by Shoyad** [comment]
Thanks I used telegraf-flow.

But I can't solve some problem:
I have inlineButton and handle for it:

`bot.action(/time.+/, async ctx => {
   enter('sendMePosition'); // 1
});`

1) I want to ask from user his location and handle it. But enter doesn't call it: 

`
const sendMePositionScene = new Scene('sendMePosition');
sendMePositionScene.on('location', (ctx) => ctx.reply(/**/))
flow.register(sendMePositionScene)
`

Maybe you give some best solutions ?

**Comment by dotcypress** [comment]
@Shoyad could you provide minimal code to reproduce?

**Comment by Shoyad** [comment]
`bot.action(/date.+/, async ctx => {
  const [section, day] = ctx.match[0].split(".");
  ctx.session.day = day;

  ctx.editMessageText(
    "Выберите время проезда:",
    Extra.markup(m =>
      m.inlineKeyboard(
        [
          m.callbackButton("⏱ 06:00 - 09:00", "time.06:00-09:00"),
          m.callbackButton("⏱ 09:00 - 12:00", "time.09:00-12:00"),
          m.callbackButton("⏱ 12:00 - 15:00", "time.12:00-15:00"),
          m.callbackButton("⏱ 15:00 - 18:00", "time.15:00-18:00"),
          m.callbackButton("⏱ 18:00 - 21:00", "time.18:00-21:00"),
          m.callbackButton("⏱ 21:00 - 00:00", "time.21:00-00:00"),
          m.callbackButton("⏱ 00:00 - 03:00", "time.00:00-03:00"),
          m.callbackButton("⏱ 03:00 - 06:00", "time.03:00-06:00")
        ],
        { columns: 2 }
      )
    )
  );
});`
