### ISSUE TITLE
Audio file_name

### ISSUE THREAD

**Issue by gadzi** [telegraf/telegraf#1238]
Bot API 5.0 added the ability to specify [file_name](https://core.tlgr.org/bots/api#audio)  for audio file. 
is it not yet resolved? tried to send file_name   but doesn't work. 

when will it be added? or is it already working?

**Comment by KnorpelSenf** [comment]
Are you using TypeScript? Can you share your source? This is just a property in `sendMessage`, so it should technically already work with older versions of `telegraf`, but I haven't tried this.

Full Bot API 5.0 support will ship in the next major release. This is not published to npm yet. You can track the progress in #1202.

If you want to have it supported immediately, you can install `telegraf` from source. `npm` allows you to simply specify `"telegraf": "telegraf/telegraf"` as a dependency.

Alternatively, this is possible via
```bash
mkdir ~/git
cd ~/git
git clone https://github.com/telegraf/telegraf.git
cd telegraf
npm install
npm run build
sudo npm link
```
and then installing it in your project via
```bash
npm link telegraf
```

Let us know if that works.

**Comment by wojpawlik** [comment]
The simplest way to install from Github is `npm install telegraf/telegraf`
