### ISSUE TITLE
Get message_id 

### ISSUE THREAD

**Issue by Bostrot** [telegraf/telegraf#124]
How can I get the message_id of a message that my bot sent?
`var msg = ctx.reply(ctx.from.id, 'test message')`
and then?

In order to delete that message again with `ctx.deleteMessage()`.

**Comment by dotcypress** [comment]
@Bostrot you don't need to use `messageId` in `reply*` methods, they already know that id.
Same with `ctx.deleteMessage()` - this method will delete current message, but if you want to delete another one, use `ctx.telegram.deleteMessage(chatId, messageId)` instead.
Current `chatId`/`messageId` you can find in `ctx.chat.id`/`ctx.message.message_id`

**Comment by Bostrot** [comment]
Thank you! but I am feeling kinda stupid now.
`bot.command('start', ({ reply, deleteMessage }) => {
  reply('test message')
  setTimeout(deleteMessage(), 2000)
})`

this doesn't delete the message. it returns: 

> Error(`${method} is not available for ${this.updateType}`)
>       ^
> 
> Error: deleteMessage is not available for message

what's wrong with it?

**Comment by dotcypress** [comment]
@Bostrot because bot can't delete users message, and this method allowed only for `callback_query` updates.

**Comment by zippytyro** [comment]
@dotcypress Thanks a lot man!

**Comment by kllbd** [comment]
var msg = await ctx.reply(ctx.from.id, 'test message')
await ctx.deleteMessage(msg.message_id)
