### ISSUE TITLE
callbackButton start link

### ISSUE THREAD

**Issue by Bostrot** [telegraf/telegraf#125]
Is it currently possible to start a link directly from the `callbackButton` ? 
(now i have to send the link first as a reply.  -- the user has to tap two times)

**Comment by Shoyad** [comment]
Point of entry telegram start command. But you can across 
`bot.command('start') `

`
     return ctx.reply(`
       ` "Some message",`
     `   Extra.HTML().markup(m =>`
       `   m.inlineKeyboard([m.callbackButton("▶ Start", "startt")])`
       ` )`
  `    );`
 `   }`

**Comment by Bostrot** [comment]
@Shoyad thanks for the reply but that is not what I mean. I mean: if its is possible to start a website url directly over the callbackButton.

-> Example: You click on the Button and it opens the popup ('Open url https://google.com/'?)

**Comment by dotcypress** [comment]
@Bostrot you can use [`urlButton`](https://github.com/telegraf/telegraf/blob/develop/examples/echo-bot.js#L5)
