### ISSUE TITLE
Some examples are no longer valid

### ISSUE THREAD

**Issue by daihaminkay** [telegraf/telegraf#1264]
## Context

As I started working more with the library, I realised that much of the documentations is no longer valid / outdated. For instance, `inline-bot` example, where

```
bot.on('chosen_inline_result'...
```
does not trigger anything, and by looking in the codebase, I only see typings, but I guess the implementation has changed on either side. 
Same goes for `keyboard-bot` where it is suggested to simply include `Markup.keyboard` in the `reply` extras, but what actually needs to be done is to pass them as `{reply_markup: <keyboard_obj>}`. 
I guess there is more that I haven't come across yet.

* Telegraf.js Version: master branch, release 3.38
* Node.js Version: 10 and 12
* Operating System: Ubuntu 18, Mac OS

## Expected Behavior

Examples are valid and can be copy-pasted and ran.

## Current Behavior

Examples only hint towards the expected code, but require user to dive deep into the library to find the actual usage

**Comment by wojpawlik** [comment]
Yes. We're preparing for breaking release. Sadly, 3.38 incorrectly links to https://github.com/telegraf/telegraf/tree/develop/docs/examples instead of https://github.com/telegraf/telegraf/tree/master/docs/examples, I will fix this in 4.0.
