### ISSUE TITLE
app.on('venue', fn()) does not work

### ISSUE THREAD

**Issue by firguy** [telegraf/telegraf#127]
app.on('venue') does not work because the message coming from telegram has also a location property. Then the message is routed as a location message...

See [https://github.com/telegraf/telegraf/blob/develop/lib/core/context.js#L50](code) in context.

**Comment by firguy** [comment]
A solution for the moment is to use app.on('location', fn()) and test if the context.message has a venue property

**Comment by dotcypress** [comment]
@firguy Thank you for report. 
Will fix this issue today.

**Comment by dotcypress** [comment]
Fix landed in `v3.7.4`

**Comment by firguy** [comment]
Sorry, I saw your [https://github.com/telegraf/telegraf/commit/864961fac3584043cb1f1074cc6e98a1d58d0f7d](commit) and I think it makes a new bug (I didn't try).

In fact, when you use app.on('venue') and app.on('location'), the both routes should match and their executions depend on the declaration order.

**Comment by firguy** [comment]
https://github.com/telegraf/telegraf/pull/128
