### ISSUE TITLE
Avoid script crash when Telegraf catch an unhandled exception

### ISSUE THREAD

**Issue by sidelux** [telegraf/telegraf#1270]
Hi all,
when i get an unhandled exception in my bot, it exit automatically, there is a way to avoid it, catch error and continue normally?
Exception example:
![image](https://user-images.githubusercontent.com/18572941/103443394-359cba80-4c5f-11eb-81e8-1735f90a86a2.png)

Thanks a lot.

Environment: Debian 9 - Node 12.13.1 - Telegraf 3.38.0

**Comment by wojpawlik** [comment]
Yes. With `bot.catch`, you can set a custom error handler that does not rethrow. This may leave your process in invalid state, so it's safer to let it crash and run it as `systemd`/`pm2` service so it gets restarted.

TypeScript or eslint can detect `ReferenceError`s among other issues without running the code.
