### ISSUE TITLE
Is there any AWS lambda deployment example?

### ISSUE THREAD

**Issue by timothyleung713** [telegraf/telegraf#129]
I have tried to deploy the telegraf function by Claudia nodeJS, but it does not work. 

Is there any code example on how to deploy the telegraf function to AWS lambda?

**Comment by tl0** [comment]
I've managed to get it work.

Quick n dirty tutorial

```javascript
const Telegraf = require('telegraf');
const app = new Telegraf(process.env.BOT_TOKEN);

app.hears('hi', ctx => ctx.reply('Hey there!'));

/* AWS Lambda handler function */
exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body); // get data passed to us
  app.handleUpdate(tmp); // make Telegraf process that data
  return callback(null, { // return something for webhook, so it doesn't try to send same stuff again
    statusCode: 200,
    body: '',
  });
};
```

[exports.handler](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html) function is key element here.

I don't have experience with Claudia.js (maybe it'll work if you copy handler function?), but here is how i did it manually

1. Create Lambda function (ZIP node_modules and all neccessary files like index.js) and set BOT_TOKEN environment variable to secret token given by BotFather, adjust memory/timeout if needed
2. Create API Gateway -> Add method POST -> Lambda Function -> Deploy -> Copy invoke url
3. Set invoke URL as webhook

```
curl -F "url=https://<INVOKE_URL>" https://api.telegram.org/bot<BOT_TOKEN>/setWebhook
```

4. Test it

**Comment by timothyleung713** [comment]
Thank you for your reply. 
However, I have tried to follow your steps mentioned without using claudia.js. It still does not have any response from my bot.

**Comment by timothyleung713** [comment]
I figure it out the problem. You have to add a trigger of API gateway endpoint in the lambda function.

**Comment by J053Fabi0** [comment]
```
const Telegraf = require('telegraf');
require('dotenv').config();
const bot = new Telegraf(process.env.TOKEN);

require('dotenv').config();
const firebase = require('firebase');
 
const app = firebase.initializeApp({
  apiKey: process.env.APIKEY,
  authDomain: process.env.AUTHDOMAIN,
  databaseURL: process.env.DATABASEURL,
  projectId: process.env.PROJECTID,
  storageBucket: process.env.STORAGEBUCKET,
  messagingSenderId: process.env.MESSAGINGSENDERID,
  appId: process.env.APPID
});

bot.use((ctx, next) => {
  // console.log(ctx.update.message.sticker) // Stickers
  // console.log(ctx.update);
  const rootRef = firebase.database().ref();
  let ordersRef = rootRef.child("last");

  ordersRef.once('value', function (dataSnapshot) {
    let data = dataSnapshot.val();
    ctx.reply(data);
  })
  next(ctx)
})

exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body); // get data passed to us
  bot.handleUpdate(tmp); // make Telegraf process that data
  return callback(null, { // return something for webhook, so it doesn't try to send same stuff again
    statusCode: 200,
    body: '',
  });
};
```

I'm using that. It returns the value of the firebase database, but it does it a lot of times. What is wrong? Maybe the return value of the handler is not being sended to Telegram Servers so they keep sending the same message?
