### ISSUE TITLE
If my bot is written totally in typescript and file ending is also .ts I get a lot of errors in nodemodules of Telegraf

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [telegraf/telegraf#1290]
## Context

* Telegraf.js Version:
* Node.js Version:
* Operating System:

## Minimal Example Code Reproducing the Issue

```ts
// your code here. Please omit everything not related to the issue,
// to make it easier to pinpoint the cause.
// Please try running this code to make sure it actually reproduces the issue.
```

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
Please include any relevant log snippets or files here.
```

**Comment by NavruzbekNoraliev** [comment]
> node index.ts

/Users/<username>/telegram_bots/<projectname>/node_modules/telegraf/lib/core/helpers/compact.js:11
    return Object.fromEntries(compactEntries);
                  ^

TypeError: Object.fromEntries is not a function

**Comment by wojpawlik** [comment]
Upgrade to Node 14.x or 15.x

**Comment by wojpawlik** [comment]
Duplicate of #1293.

**Comment by wojpawlik** [comment]
Duplicate of #1293
