### ISSUE TITLE
Trigger of a callback button is not handled within the scene

### ISSUE THREAD

**Issue by mikilian** [telegraf/telegraf#1292]
## Context

* Telegraf.js Version: `4.0.0`
* Node.js Version: `15.3.0`
* Operating System: `Windows 10 20H2 (Build 19042.685)` 

## Minimal Example Code Reproducing the Issue

```ts
import { Markup, Scenes, session, Telegraf } from 'telegraf';

const bot = new Telegraf<Scenes.SceneContext>(process.env.BOT_TOKEN);
const scene = new Scenes.BaseScene<Scenes.SceneContext>('example');

scene.enter(async ctx => await ctx.replyWithMarkdown(
  'Example Keyboard',
  Markup.inlineKeyboard([
    Markup.button.callback('Click Me', 'something')
  ])
));

scene.action('something', async ctx => await ctx.answerCbQuery('yeah!'))

const stage = new Scenes.Stage<Scenes.SceneContext>([scene]);

bot.use(session());
bot.use(stage.middleware());
bot.command('example', async ctx => await ctx.scene.enter('example'));
bot.launch().then(() => bot.start());
```

1. Run the example code
2. Send `/example` to your bot
3. Press on the `Click Me` button

## Expected Behavior

If a keyboard with one or more callback buttons has been created in a scene, the trigger should also be handled by this scene.

## Current Behavior

> The bug appeared only with the upgrade to version 4.

As long as the trigger is handled via the scene, it will never be called. However, if you use the `action` method of the bot instance, it works.
If two scenes use the same trigger, the workaround would not work.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
  telegraf:main Connecting to Telegram +0ms
  telegraf:client HTTP call getMe {} +0ms
  telegraf:main Launching @******************** +104ms
  telegraf:client HTTP call deleteWebhook {} +103ms
  telegraf:polling Starting long polling +0ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 0, allowed_updates: [] } +24ms
  telegraf:main Bot started with long polling +24ms
  telegraf:main Processing update 524828574 +3s
  telegraf:scenes:context Leaving scene +0ms
  telegraf:scenes:context Entering scene example {} false +1ms
  telegraf:client HTTP call sendMessage {
  chat_id: *********,
  text: 'Example Keyboard',
  parse_mode: 'Markdown',
  reply_markup: { inline_keyboard: [ [Array] ] }
} +3s
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 524828575, allowed_updates: [] } +44ms
  telegraf:main Processing update 524828575 +932ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 524828576, allowed_updates: [] } +887ms
```

**Comment by wojpawlik** [comment]
You wish for inactive scenes to handle `actions`? Do I understand you correctly?

Also, drop the [`bot.start`](https://telegraf.js.org/classes/composer.html#start) call, just `bot.launch()`.

**Comment by mikilian** [comment]
I would like the behavior to proceed as before. You can try the code from me with the last version of telegraf 3. In the version, the `action` is handled by the **scene**.

PS: Thanks for the hint regarding dropping the `bot.start` call.

**Comment by Loskir** [comment]
~~Looks like this code should fail at
`bot.command('example', async ctx => await ctx.scene.enter('example'));`
because `ctx.scene` should only be available in the `stage`~~

upd: no, `ctx.scene` is available in `bot` too

**Comment by Loskir** [comment]
So @mikilian, does dropping the `bot.start` call help? If no, please remove it from the first message

**Comment by Loskir** [comment]
```js
const { Markup, Scenes, session, Telegraf } = require('telegraf');

const bot = new Telegraf(process.env.BOT_TOKEN);
const scene = new Scenes.BaseScene('example');

scene.enter(async ctx => await ctx.replyWithMarkdown(
  'Example Keyboard',
  Markup.inlineKeyboard([
    Markup.button.callback('Click Me', 'something')
  ])
));

scene.action('something', async ctx => await ctx.answerCbQuery('yeah!'))

const stage = new Scenes.Stage([scene]);

bot.use(session());
bot.use(stage.middleware());
bot.command('example', async ctx => await ctx.scene.enter('example'));
bot.launch();
```

works for me (rewrote it in js)

**Comment by mikilian** [comment]
Hello @Loskir!

When I thanked in January that you can omit the `bot.start()` call, I did so and it did not fix the problem.
However, if I take your example or the code in the start post and remove the function call, it works.

Very strange, but all right. I think with this the ticket can be closed and I thank you all very much for the answers!
