### ISSUE TITLE
Object.fromEntries is not a function

### ISSUE THREAD

**Issue by Vandomas** [telegraf/telegraf#1293]
/node_modules/telegraf/lib/core/helpers/compact.js:11
    return Object.fromEntries(compactEntries);
                  ^

TypeError: Object.fromEntries is not a function

in telegraf@3.38.0 all good

**Comment by wojpawlik** [comment]
Upgrade to Node 14.x or 15.x.

**Comment by Y1a2s3h4** [comment]
iam having this issue how can i solve this problem please help.

**Comment by Y1a2s3h4** [comment]
> Upgrade to Node 14.x or 15.x.

in my local system I'm running node 16 version please

**Comment by Y1a2s3h4** [comment]
> Upgrade to Node 14.x or 15.x.

in my local system I'm running node 16 version please

**Comment by jerrychong25** [comment]
> Upgrade to Node 14.x or 15.x.

Upgraded Node to 14.21.3 fixed my issue.

Thanks @wojpawlik !
