### ISSUE TITLE
WizardScene doesnt start first step on ctx.scene.enter

### ISSUE THREAD

**Issue by websharik** [telegraf/telegraf#1298]
## Context

* Telegraf.js Version: 4.0.1
* Node.js Version: v14.8.0
* Operating System: Win 10

## Minimal Example Code Reproducing the Issue

```js
import { Telegraf, Scenes, session } from 'telegraf'

const TEST_SCENE = new Scenes.WizardScene('TEST_SCENE',
    async (ctx) => {
        ctx.reply('Hello world')
        return ctx.wizard.next()
    },
    async (ctx) => {
        ctx.reply('End')
        return ctx.scene.leave()
    }
)

const stage = new Scenes.Stage([TEST_SCENE])
const bot = new Telegraf(token)
bot.use(session())
bot.use(stage.middleware())

bot.command('test',  (ctx) => {
    ctx.scene.enter('TEST_SCENE')
})

bot.launch()
```

## Expected Behavior

On command /start, bot enter to scene, start first step and say 'Hello world'

## Current Behavior

On command /start bot nothink say. On next message to bot, he say 'Hello world'

**Comment by aedeveloper** [comment]
I've made [this issue](https://github.com/telegraf/telegraf/issues/1297) just 10 minutes before you :)
