### ISSUE TITLE
tg-bot-api local server webhook domain start with https (http required)

### ISSUE THREAD

**Issue by ig-gh** [telegraf/telegraf#1299]
## Context

* Telegraf.js Version: 4.0.1

## Minimal Example Code Reproducing the Issue

```ts
bot.launch(
    {
        webhook: {
            domain: 'myhost_1',
            hookPath: '/',
            port: 3000
        },
        allowedUpdates: 999,
    
    }
)
```

## Expected Behavior

Prior TS migration, local tg-bot-api is accepting webhook via http:
``` ts
bot.telegram.setWebhook('http://myhost_1/', null, 999)
bot.startWebhook('/', null, 3000)
```
```
webhook http://myhost_1
port 3000
webhook_max_connections=999 
```
## Current Behavior
HTTP is overrided with HTTPS in webhhok url and webhook_max_connections doesn't exists(?)
```
webhook	https://myhost_1/
webhook_max_connections	100
```

**Comment by Autapomorph** [comment]
According to [setWebhook](https://github.com/telegraf/telegraf/blob/develop/src/telegram.ts#L105) method signature changed
You can manually call `bot.telegram.setWebhook(url, { max_connections: 999 })` after `bot.launch`
`http` (not `https`) server [should ](https://github.com/telegraf/telegraf/blob/a57dbcdd4e706681cdb390a086e1cf90a4cfee4d/src/telegraf.ts#L141)start if you don't provide `tlsOptions` to `bot.launch`

**Comment by epicayay** [comment]
> According to [setWebhook](https://github.com/telegraf/telegraf/blob/develop/src/telegram.ts#L105) method signature changed
> You can manually call `bot.telegram.setWebhook(url, { max_connections: 999 })` after `bot.launch`
> `http` (not `https`) server [should ](https://github.com/telegraf/telegraf/blob/a57dbcdd4e706681cdb390a086e1cf90a4cfee4d/src/telegraf.ts#L141)start if you don't provide `tlsOptions` to `bot.launch`

Thank you @Autapomorph 
After all the configuration is same as previous version of telegraf with minor changes:
```ts
bot.telegram.setWebhook('http://myhost_1', {max_connections:999})
bot.launch({
        webhook: {
            hookPath: '/',
            port: 3000
        }
 })
```

**Comment by tilonuz99** [comment]
`const { Telegraf } = require('telegraf');
const express = require('express');


var TOKEN = "********:AAEJDm1uMb9Oxdki_c11zlJKWRPbzV1feQ4";

const bot = new Telegraf(`${TOKEN}`, {
  telegram: {
    apiRoot: 'http://localhost:8080'
  }
});
bot.telegram.setWebhook(`/bot`, {max_connections:999})
bot.launch({
        webhook: {
            hookPath: '/',
            port: 8080
        }
 })

const app = express();

//app.use(express.json());
app.use(bot.webhookCallback(`/`))
app.get(`/bot${TOKEN}`, (req, res) => res.send('Hello World!'))

app.listen(8080, () => {
  console.log(`Express server is listening on 8080`);
});

bot.start((ctx) => ctx.reply('Welcome'));
bot.help((ctx) => ctx.reply('Send me a sticker'));
bot.on('sticker', (ctx) => ctx.reply('👍'));
bot.hears('hi', (ctx) => ctx.reply('Hey there'));`


Please help!

**Comment by hypernova7** [comment]
`setWebhook` method now requires only https.
I will close this issue due to inactivity, reopen it if needed
