### ISSUE TITLE
silly fetchPackageMetaData error for telegraf@latest Unexpected token '<' at 1:1

### ISSUE THREAD

**Issue by GautierL** [telegraf/telegraf#130]
When doing a installation using: $ npm install telegraf --save
I got this error: silly fetchPackageMetaData error for telegraf@latest Unexpected token '<' at 1:1

[2017-06-22T10_37_39_383Z-debug.log.txt](https://github.com/telegraf/telegraf/files/1094473/2017-06-22T10_37_39_383Z-debug.log.txt)

**Comment by dotcypress** [comment]
Hey.

Check out [this thread](https://stackoverflow.com/questions/16280382/cant-install-any-package-with-node-npm).
