### ISSUE TITLE
Can not send large files via buffer using telegram-bot-api local server

### ISSUE THREAD

**Issue by ghost** [telegraf/telegraf#1301]
Basically, the title.
It is not possible to send by buffer files >50mb using Telegraf and Local Bot API Server.

This is how I send them:
`await bot.telegram.sendDocument(chatId,
  {
    source: bigBuffer
  })`
  
This is the error I'm getting:
```
/Users/acupoftea/Desktop/testbot/node_modules/node-fetch/lib/index.js:272
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at http://localhost:8081/botXXXXX:YYYYY/sendDocument reason: Unexpected end of JSON input
    at /Users/acupoftea/Desktop/testbot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Telegram.callApi (/Users/acupoftea/Desktop/testbot/node_modules/telegraf/lib/core/network/client.js:250:22)
    at async file:///Users/acupoftea/Desktop/testbot/testfiles.js:13:1 {
  type: 'invalid-json'
}
```

Sending the same file (and other large ones) by local path, url or using stream works fine. Sending them by buffer using node-telegram-bot-api library also works fine.

**Comment by horak** [comment]
I probably won't be able to help you but what command+flags are you using to run your local server?

**Comment by ghost** [comment]
> I probably won't be able to help you but what command+flags are you using to run your local server?

Sorry for late response. I used all the standard flags –`api-id`, `api-hash` and `local`.

**Comment by arkhemlol** [comment]
I managed to upload larger files (tested with ~100MB mp3 file, `local` flag is on) by providing absolute path to `replyWithAudio`, like this:

```
ctx.replyWithAudio(
        { source: path }, // Absolute OS path to the file (string)
        {
          //options
        }
 );
```
It works fine at the moment, since I'm developing locally. Nor `Buffer`, nor `file:///` didn't work for me though.

**Comment by banghasan** [comment]
Is there a solution already?
