### ISSUE TITLE
created session value is missing on the "poll_answer" ctx

### ISSUE THREAD

**Issue by Quernest** [telegraf/telegraf#1302]
## Context

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.18.3
* Operating System: Win 10

## Minimal Example Code Reproducing the Issue

```js
  const { session } = require('telegraf');

  const bot = new Telegraf(process.env.BOT_TOKEN)

  bot.use(session());

  bot.command('quiz', (ctx) => {
    // ✅ create session object with counter
    ctx.session = { counter: 0 };
    ctx.telegram.sendQuiz(args);
    return ctx;
  });

  bot.on('poll_answer', (ctx) => {
    console.log(ctx.session); // ⛔️ undefined
    return ctx;
  });
```

## Expected Behavior

```js
ctx.session // { counter: 0 };
```

## Current Behavior

```js
ctx.session // undefined
```

**Comment by gabrielrufino** [comment]
Same problem for me :(

**Comment by Autapomorph** [comment]
See [session source code](https://github.com/telegraf/telegraf/blob/develop/src/session.ts#L40)
By default if uses `${fromId}:${chatId}`

`poll_anwser` sends [this](https://core.telegram.org/bots/api#pollanswer) object
That's why `ctx.session` is undefined

You can try to provide custom [getSessionKey](https://github.com/telegraf/telegraf/blob/develop/src/session.ts#L23) to `session` middleware

**Comment by Quernest** [comment]
> 
> 
> See [session source code](https://github.com/telegraf/telegraf/blob/develop/src/session.ts#L40)
> By default if uses `${fromId}:${chatId}`
> 
> `poll_anwser` sends [this](https://core.telegram.org/bots/api#pollanswer) object
> That's why `ctx.session` is undefined
> 
> You can try to provide custom [getSessionKey](https://github.com/telegraf/telegraf/blob/develop/src/session.ts#L23) to `session` middleware

Yes. Getting the correct id can help fix this problem, but not much can be taken from this ctx. Thanks!

```js
  bot.use(
    session({
      getSessionKey: ({ pollAnswer, from, chat }) => {
        // for public quizzes
        if (pollAnswer?.user.id) {
          const { id } = pollAnswer.user;
          return `${id}:${id}`;
        }

        // fallback
        // ⚠️ Be careful, these values ​​may not be available.
        return `${from.id}:${chat.id}`;
      },
    }),
  );
```
