### ISSUE TITLE
Not enough types for Context

### ISSUE THREAD

**Issue by NedloGlitch** [telegraf/telegraf#1306]
**Is your feature request related to a problem? Please describe.**
I like the new typings system, but I think it lacks types for dividing code - when I want to create a functions/methods as handlers, I can't just grab "GuardedContext" and use it.

Code Example
```ts
import { Telegraf } from 'telegraf';
import { Message } from 'telegraf/typings/telegram-types';
import { Context, TextContext, GuardedContext } from 'telegraf/typings/context';

const bot = new Telegraf(process.env.BOT_TOKEN as string);

let number = 0;

bot.on('text', async (ctx) => {
    if (number === 0) {
        await first_handler(ctx);
    } else if (number === 1) {
        await second_handler(ctx);
    } else if (number === 2) {
        await third_handler(ctx);
    }
});

async function first_handler(ctx: Context & { message: Message.TextMessage }) {
    const message = (ctx.message.text) // Message string   
    if (message === "hello"){
        ctx.reply("Hey!") 
    } else {
        ctx.reply("Please say hello to me!")
    }
    number += 1;
}

async function second_handler(ctx: GuardedContext<Context, { message: Message.TextMessage; }>) { // This is what could be used, but its not available for import
    const message = (ctx.message.text)  
    if (message === "hello") {
        ctx.reply("Hey again!");
    } else {
        ctx.reply("Please say hello to me!");
    }
    number += 1;
}

async function third_handler(ctx: TextContext) { // This is how it can look like if we add premade types
    const message = (ctx.message.text)
    if (message === "hello") {
        ctx.reply("I've already met you!");
    } else {
        ctx.reply("Please say hello to me!");
    }
    number = 0;
}
```

**Describe the solution you'd like**
Maybe it's better to create separate types (TextContext, AudioContext, VideoContext, etc.)

**Describe alternatives you've considered**
Or make GuardedContext available for import

**Additional context**
I'm new, so don't be mad at me.

**Comment by wojpawlik** [comment]
I'm glad you asked! We probably should expose `GuardedContext`, just, how should it be described (JSDoc) to avoid confusing newcommers? And is `GuardedContext` even a good name?

Related: https://github.com/telegraf/telegraf/discussions/1284#discussioncomment-272819

> Maybe it's better to create separate types (TextContext, AudioContext, VideoContext, etc.)

No. Less powerful and needs way more code.

**Comment by NedloGlitch** [comment]
So after some conversation with more experienced dev friend, we've some-what agreed that the professional name for this should be "SafeContext", but if targeting newcomers, the "GuaranteedContext" or "GrantedContext" will be easier to understand.  

As for me personally, I like "GrantedContext" because it's self-explanatory name - "The context that you get."
The description should have first paragraph easy enough to undestand from first read, like "(GuranteedContext) GrantedContext is Context with guaranteed additional info (Message, TextMessage, idk.)" 

I may get or say some things wrong, but this is my opinion as a newcomer.
(P.S. - My English might be a bit broken, not my first language)

**Comment by wojpawlik** [comment]
How about just `Narrow`, @NedloGlitch, @KnorpelSenf? Description: "Narrows down `Context['update']` and some derived properties".

**Comment by NedloGlitch** [comment]
I think it should include "Context" in name just to be easily associated. Maybe "NarrowedContext"? 
Like, when I read "NarrowedContext" I think "Oh, so it must be context with less stuff inside" or "More targeted context it is then"

Also "Narrows down Context['update'] and some derived properties" sound a bit confusing, but I don't know how to improve it right now.

**Comment by german-bortoli** [comment]
@NedloGlitch which version of Telegraf do you have ?

**Comment by NedloGlitch** [comment]
@german-bortoli I currently use Telegraf 4.0.1, used 3.38.0 before.

**Comment by wojpawlik** [comment]
I kinda like `GuardedContext` name, it parallels [`Composer.guard`](https://telegraf.js.org/classes/composer.html#guard-1), but I think `NarrowedContext` (or `NarrowContext`) is clearer.

**Comment by EdJoPaTo** [comment]
How about `SpecificContext`?

**Comment by darvesh** [comment]
`NarrowContext` is better here imo

**Comment by wojpawlik** [comment]
These are good:
- `NarrowedContext` is my favorite so far.
- `NarrowContext` is equally good, just it'd be the only type with a verb name.
- `SpecificContext` is not bad... it just lacks the type narrowing connotation.

These are bad:
- I don't know where `GrantedContext` came from.
- `GuaranteedContext`... I just dislike, for no reason.
- `GuardedContext` tells you nothing if you don't know `Composer.guard`.
- `SafeContext` suggests `Context` is unsafe (it's not).
