### ISSUE TITLE
DOcumentation

### ISSUE THREAD

**Issue by Porkechebure** [telegraf/telegraf#1308]
Put up a decent documentation. The one present now sucks.
I can't even find a proper way to reply to a message (not just sending the text, replying to a message by quoting user).

**Comment by wojpawlik** [comment]
What do you find lackluster? The [readme](https://github.com/telegraf/telegraf/blob/v4.0.1/README.md) or the [API reference](https://telegraf.js.org/modules.html), which is so new that readme doesn't link it yet?

**Comment by rageroot** [comment]
The new version of the site with the API is disgusting. Return the old one, it was more convenient and understandable.

**Comment by wojpawlik** [comment]
What is disgusting about it? Let me know so I can fix it!

New docs are generated straight from source, so they're guaranteed to be correct and need little maintenance.

**Comment by rageroot** [comment]
https://telegraf.js.org/index.html
can't you see it yourself? Just put next to the site that was back in December and what is now. Very uncomfortable. Now I needed to find some information, I opened a site, and there it is ... I am sitting in suffering, thinking how to live on with such a site.

**Comment by wojpawlik** [comment]
I'm only fixing issues. New docs address #211. If you cannot express your issue, I cannot address it. Alternatively, please review #1305.

**Comment by wojpawlik** [comment]
Two can play that game: old docs are obviously inferior. Equally unhelpful, doesn't suggest a way forward.

Compare with: old docs are inferior because:

- they require clientside JS to render,
- their API reference is known to be incomplete: #211,
- their API reference was incorrect and had to be fixed manually: #829, #805, #856.

New API reference will be rendered straight from the source on every release, which means it **cannot** be incomplete or incorrect.

So please, tell me what exactly you don't like about the new docs, and I'll be happy to do my best to address your concerns.

**Comment by ivanlewin** [comment]
Hi, I just wanted to say that I think this is a really good project and you @Porkechebure could be a lot nicer given that you're not even contributing to this repo in any way.

I have been using Telegraf for the last few months and it really made my life easier, however I really miss the old docs.
I see you're working on a new one, but is there any chance to have the old one available in the meantime? Even if it's just a really long screenshot I think it could be very useful in some cases.

**Comment by Code0x2** [comment]
> Hi, I just wanted to say that I think this is a really good project and you (@Porkechebure and @rageroot) could be a lot nicer given that you're not even contributing to making it better.
> 
> I have been using Telegraf for the last few months and it really made my life easier, however I really miss the old docs.
> I see you're working on a new one, but is there any chance to have the old one available in the meantime? Even if it's just a really long screenshot I think it could be very useful in some cases.

Agreed. Its a lot easier to navigate the old one and find stuff that you need quicker. Also new docs dont have the api reference for the telegraf.telegram methods

**Comment by wojpawlik** [comment]
Thank you for the kind words, stranger. For the old docs, see https://github.com/telegraf/telegraf/discussions/1304#discussioncomment-288779.

What exactly could be added to new docs to make them easier to navigate?

`typedoc` generates docs only for exported members. I cannot (https://github.com/telegraf/telegraf/pull/1257#issuecomment-755763674) and don't want to export `Telegram` right now, so IntelliSense must suffice for now.

**Comment by ivanlewin** [comment]
Thank you very much, my bad for not looking thoroughly. Maybe this new version is less intuitive? or maybe we were used to the previous one. I just upgraded to v4.0.1 tho, and so far so good. If I encounter a new issue I will share it here.

Keep it up!

**Comment by cddm13** [comment]
I agree with @Porkechebure the new Documentation site is hard to understand (the font especially) I find it very confusing to use (not sure why exactly tho) also I think it lacks concrete examples. Whoever I do think that there's a better way to ask for things, so please to the maintainers if you could go back to the previous style and also include more examples on the API reference would be awesome.

**Comment by wojpawlik** [comment]
See https://github.com/telegraf/telegraf/tree/develop/docs/examples

**Comment by AVert** [comment]
NEW version of docs 
not have correct and working search!!!
Search not working and not have table of contents
we cant use this awful new version of website please return back old one!!!
and finish search first
