### ISSUE TITLE
TypeScript type inference

### ISSUE THREAD

**Issue by simonuvarov** [telegraf/telegraf#1317]
## Context

* Telegraf.js Version: 4.0.1
* Node.js Version: 14.15.1
* Operating System: MacOS Big Sur

## Minimal Example Code Reproducing the Issue

The following code triggers the error:
```ts
const bot = new Telegraf(process.env.BOT_TOKEN);
bot.on('sticker', ctx => ctx.reply('👍'));
bot.launch();
```

## Error Message and Logs

```
src/index.ts:12:8 - error TS2345: Argument of type '"sticker"' is not assignable to parameter of type 'MaybeArray<T>'.
```

## Additional Information

The workaround for now is to explicitly set the type like:
```ts
const bot = new Telegraf(process.env.BOT_TOKEN);
bot.on<'sticker'>('sticker', ctx => ctx.reply('👍'));
bot.launch();
```

... or to set `strictFunctionTypes` to `false` in `tsconfig.json`

**Comment by wojpawlik** [comment]
Cannot reproduce.

**Comment by simonuvarov** [comment]
I tried upgrading different packages and it was typescript that caused this error. Bumping it from `4.0.3` to `4.1.5` resolved this issue. In any case, thanks for your time!

**Comment by FilippoVigani** [comment]
It's happening to me as well. Updating typescript doesn't help.
