### ISSUE TITLE
Cant add hyperlink

### ISSUE THREAD

**Issue by Code0x2** [telegraf/telegraf#1318]
I'm trying to do the following 

`bot.telegram.sendMessage(GROUPID, '[google](https://google.com)')`

It just sends the message as `[google](https://google.com)`, instead of a link like [google](https://google.com).

Trying to do `bot.telegram.sendMessage(GROUPID, '[google](https://google.com', Extra.markdownV2())`
returns error saying cannot read property markdownV2 of undefined.

**Comment by Autapomorph** [comment]
Extra is removed in v4:
```javascript
bot.telegram.sendMessage(GROUPID, '[google](https://google.com)', { parse_mode: 'MarkdownV2' })
```

**Comment by Code0x2** [comment]
> Extra is removed in v4:
> 
> ```js
> bot.telegram.sendMessage(GROUPID, '[google](https://google.com)', { parse_mode: 'MarkdownV2' })
> ```

Thanks, although having to prepend special characters with \ is a bit of a pain i found that html works better.

**Comment by Wafiismail27** [comment]
> > Extra is removed in v4:
> > ```js
> > bot.telegram.sendMessage(GROUPID, '[google](https://google.com)', { parse_mode: 'MarkdownV2' })
> > ```
> 
> Thanks, although having to prepend special characters with \ is a bit of a pain i found that html works better.

You can additionally use this: 

```
// https://core.telegram.org/bots/api#markdownv2-style

const SPECIAL_CHARS = [
  '\\',
  '_',
  '*',
  '[',
  ']',
  '(',
  ')',
  '~',
  '`',
  '>',
  '<',
  '&',
  '#',
  '+',
  '-',
  '=',
  '|',
  '{',
  '}',
  '.',
  '!'
]

const escapeMarkdown = (text) => {
  SPECIAL_CHARS.forEach(char => (text = text.replaceAll(char, `\\${char}`)))
  return text
}
```
