### ISSUE TITLE
How do I keep track of the last sent message?

### ISSUE THREAD

**Issue by doplumi** [telegraf/telegraf#132]
I feel like this should be trivial but I still can't quite get there:

```
bot.use((ctx, next) => {
  return next().then(() => {
    ctx.session.lastSentMessage = ???
  });
});
```

Overriding reply also seems like a dead end:

```
const reply = bot.context.reply;
bot.context.reply = (...args) => {
  ???
  reply(...args);
}
```

**Note** I'm not talking about the user message but the last message sent from the server.
It's useful so that I can keep track of ''where'' the user is at any time.

**Comment by doplumi** [comment]
Would be cool if `chat` already had this property included.

**Comment by dotcypress** [comment]
Yes, you can save any user related info to session storage.

Also, check out [`telegraf-flow`](https://github.com/telegraf/telegraf-flow) library.
