### ISSUE TITLE
`bot.command` doesn't capture commands in channels

### ISSUE THREAD

**Issue by bubakazouba** [telegraf/telegraf#1323]
## Context

I was able to reproduce on multiple systems:
* Telegraf.js Version: 3.21.2
* Node.js Version: v12.15.0
* Operating System: Mac

* Telegraf.js Version: 4.0.1
* Node.js Version: v12.15.0
* Operating System: Mac
* 
* Telegraf.js Version: 3.21.2
* Node.js Version: v8.10.0
* Operating System:  Ubuntu 18.04.1 LTS

## Minimal Example Code Reproducing the Issue

```js
bot.command("list", (ctx) => {
console.log("I ran"); // doesn't run
});
```

1- Create a channel
2- Add bot to channel as admin
3- send a command "/list"

## Expected Behavior

1- Bot runs the `list` command callback and logs `"I ran"`

## Current Behavior

1- No logs occur, but I was able to confirm with a middleware that runs before the command callback that the bot does receive the message.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

None

**Comment by Loskir** [comment]
Channel posts are not the same as all other messages. So `.command`, `.hears` and other handlers don't work for them

**Comment by bubakazouba** [comment]
I understand that the input format is different for channels.

I was hoping that telegraf can abstract this away for me and handle `.command` and `.hears` regardless of it came from a private, group or channel.

Is this something that you plan on supporting in the future?

If this is only a matter of bandwidth, I would be willing to contribute to the repo to help make this happen. I can submit a proposal today for this.

**Comment by Loskir** [comment]
You don't usually need to handle commands in channels...

But the easiest solution I can think of (a bit hacky tbh) is
```js
bot.on('channel_post', (ctx, next) => {
  ctx.update.message = ctx.update.channel_post
  return next()
})
```

**Comment by bubakazouba** [comment]
I remember trying something like this before by using a middleware that runs before anything else, but it was a bit problematic as `update` was a read only variable. I used `Object.assign` but it still didn't propagate to `bot.command`.

I'm a bit confused as to why you don't recognize handling commands in channels as a typical use case. Especially when the telegram client (at least the iOS one), shows you the list of commands the bot supports within a channel when you type `/`. From the perspective of users of my bot, this is a bug. See screenshot below.

![image](https://user-images.githubusercontent.com/7442301/107160058-c6df0b00-6948-11eb-98fb-2d4e91a329ce.png)

**Comment by bubakazouba** [comment]
Are there any plans for supporting this in the future? The only alternative I see for supporting channels in my bot is to create my own implementation of `bot.command`, `bot.action`, `bot.hears`.. which would render telegraf useless for my project (and any other bot that wishes to suppot channels).

Again I would like to offer a contribution to the telegraf repo to add this as a feature.

**Comment by bubakazouba** [comment]
Gentle ping

**Comment by wojpawlik** [comment]
How would you implement this?

3.38 had `channelMode`, which caused for example `Composer.mount('text')` to trigger on channel posts too, but it was removed in 4.0 because it was too difficult to type.

Related: #430, #898

**Comment by T1MOXA** [comment]
Ping

**Comment by bauti-defi** [comment]
ping

**Comment by wojpawlik** [comment]
I'd merge `composer.on("channel_post").command(...)` into v5 branch. I'll close this issue if nobody steps up before 5.0.0.

**Comment by wojpawlik** [comment]
If you need custom matching, use `Composer.dispatch`.

**Comment by MKRhere** [comment]
There's no interest in adding this to core. However, I'm going to leave this middleware here as an answer, in case anyone wants this behaviour (comments provided to help understand): [channelMode gist ↗️](https://gist.github.com/MKRhere/b48590095eb6f62fe4ee6e2684616018)

Feel free to copy and adapt as you wish.

### Usage:

```TS
import { channelMode } from "./channelMode";

const bot = new Telegraf(token);
bot.use(channelMode());

// these now work in channels

bot.hears("hello", handler);
bot.command("hello", ctx => ctx.reply("Hello!"));
```

Working screenshot:
![image](https://github.com/telegraf/telegraf/assets/19621208/022ffeeb-77bd-4eb3-a098-1f52d9edd3b0)

Closing this as resolved.
