### ISSUE TITLE
Seems, `formatHTML` helper has been deleted accidentally?

### ISSUE THREAD

**Issue by esindger** [telegraf/telegraf#1325]
File `src/core/helpers/formatting.ts` has been deleted and helper `formatHTML()` is not available any more. Why? Is there a reason?

https://github.com/telegraf/telegraf/commit/fb13ad397cf268ca2ac8c0429fe7627fa2f1903d

**Comment by wojpawlik** [comment]
It was deleted, deliberately. It was an internal function used only by `sendCopy`, obsoleted by official `copyMessage`.
