### ISSUE TITLE
How to get sequence of question's answer?

### ISSUE THREAD

**Issue by rsa408** [telegraf/telegraf#133]
How to get sequence of question's answer and send them to mongodb?

**Comment by dotcypress** [comment]
See example of questionary in [`telegraf-flow`](https://github.com/telegraf/telegraf-flow/blob/develop/examples/wizard-bot.js) library

**Comment by rsa408** [comment]
Thanks,
 I only need one more question please. where these text are kept? i tried to send them to console but I've was not success. 
thanks
