### ISSUE TITLE
Telegram return .dat instead .mp4 (download) on video sended via replyWithMediaGroup

### ISSUE THREAD

**Issue by websharik** [telegraf/telegraf#1330]
Bot send videos + photos to user. User trying share video from tg to instagram, but cant it becouse video is .dat format. (original video is mp4)

When i use replyWithVideo - all is right, video on saving is mp4.
When i use replyWithMediaGroup - video on saving is dat.
I tried manually send video + photos group in telegram client and video was be mp4.

## Context

* Telegraf.js Version: 4.0.2
* Node.js Version: 14.8.0
* Operating System: Win10

## Minimal Example Code Reproducing the Issue

```js
//Telegram return .mp4
await ctx.replyWithVideo({
    url: "site.com/video.mp4"
})

//Telegram return .dat
await ctx.replyWithMediaGroup([
    {
        type: 'video',
        media: {
            url: "site.com/video.mp4"
            //source: ... //too .dat
        }
    }
])
```

## Expected Behavior

On bot send video via replyWithMediaGroup video should be mp4 format.

## Current Behavior

On bot send video via replyWithMediaGroup video is dat format.

**Comment by Porkechebure** [comment]
The biggest question is why this dude deloping this thing is not ever documenting anything,
One is left to guess.
For example. I needed this and I needed to add a caption somewhere.
No explanation anywhere on how to do it.
Awesome job

**Comment by hypernova7** [comment]
Try

```javascript
ctx.replyWithDocument({
  source: 'video.mp4',
  filename: 'My Video.mp4'
})
```

```javascript
ctx.replyWithMediaGroup([
  {
    type: 'video',
    media: {
      source: 'video.mp4',
      filename: 'My Video.mp4'
    }
  }
])
```
