### ISSUE TITLE
Invoking ctx.scene.enter() on a WizardScene doesn't actually start the scene until the next update

### ISSUE THREAD

**Issue by annorax** [telegraf/telegraf#1333]
It does create the state within the session, and sets the current scene within the state, but doesn't set the cursor, and more importantly, never even enters the first step until the next update.

I tracked this down to the following code within SceneContextScene.enter():

```javascript
const handler =
      'enterMiddleware' in this.current &&
      typeof this.current.enterMiddleware === 'function'
        ? this.current.enterMiddleware()
        : this.current.middleware()
```

This predicate is <i>always</i> true: 
```javascript
'enterMiddleware' in this.current &&
      typeof this.current.enterMiddleware === 'function'
```

And therefore handler is always set to `this.current.enterMiddleware()`, which returns `this.current.enterHandler`, which is, in turn, a passthru composer that simply wastes the current request doing nothing.

I am currently working around this by setting:
```javascript
Scenes.WizardScene.prototype.enterMiddleware = Scenes.WizardScene.prototype.middleware;
```

Just before defining my `WizardScene`s.

**Comment by aedeveloper** [comment]
related [issue](https://github.com/telegraf/telegraf/issues/1297)
