### ISSUE TITLE
Make the damn documentation

### ISSUE THREAD

**Issue by Porkechebure** [telegraf/telegraf#1336]
I've already told once the documentation sucks and people followed along (not in the way I was thinking, but still).

Now I'm getting frustrated at scenes. God the docs and the library are awful. Get your ass up and work if you want to do a library.

https://github.com/telegraf/telegraf/issues/705 -> Some other people complaining.

```
basically doing
const { Telegraf, Composer, BaseScene} = require('telegraf')
const configScene = new BaseScene('configScene');
```

Same goes for something simple as

```
bot.command('confgen', async(ctx) => {
    const configScene = new BaseScene('configScene');
    configScene.enter((ctx) => {
        ctx.reply('Please paste the message')
        var response = ''
        bot.on('text', (ctx => response = ctx.message.text))
        console.log(response);
    })
    configScene.leave((ctx) => ctx.reply("bye"))
})
```

 it gives 

> (Node:27112) UnhandledPromiseRejectionWarning: TypeError: BaseScene is not a constructor
>     at c:\pers\tgaccountcreator\index.js:18:25
>     at c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:157:111
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async execute (c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:456:17)
>     at async c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:457:21
>     at async execute (c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:456:17)
>     at async c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:457:21
>     at async execute (c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:456:17)
>     at async c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:457:21
>     at async execute (c:\pers\tgaccountcreator\node_modules\telegraf\lib\composer.js:456:17)
> (Use `node --trace-warnings ...` to show where the warning was created)
> <node_internals>/internal/process/warning.js:43
> (node:27112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> <node_internals>/internal/process/warning.js:43
> (node:27112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> <node_internals>/internal/process/warning.js:43
> Process exited with code 1
> 

says basescene is not a constructor. Make some damn example up to date with telegraf 4. Why you even bother developing it if the issue section will be flooded by people asking for help and docs

OH AND BEFORE YOU SAY IT: https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes/scenes-bot.ts
Gives the same thing: Scenes is not a constructor

the only way I found for making it work is 

```
bot.command('confgen', (ctx) => {
    const configScene = new Scenes.BaseScene('configScene');
    configScene.enter((ctx) => {
        ctx.reply('Please paste the message')
        var response = ''
        bot.on('text', (ctx => response = ctx.message.text))
        console.log(response);
    })
    configScene.leave((ctx) => ctx.reply("bye"))
})
```

but it d'esn't "enter" the  enter method so nothing happens

**Comment by Morb0** [comment]
Example shows how to create scene:
https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes/scenes-bot.ts#L13

In example you can also see that it is not enough just to create a scene, it still needs to be registered in the `Stage` that later used as middleware.
https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes/scenes-bot.ts#L29

But in general, I agree that there is not enough documentation for the scenes.

**Comment by wojpawlik** [comment]
It's true that scenes could use more docs. PR welcome. JSDoc comments are preferred over adding to readme.

@Porkechebure, you seem to misunderstand open source. You don't pay me, therefore I don't owe you anything, therefore you have no right to complain. Make the change you wish to see and open a PR. Or don't use the library, you will not be missed.

**Comment by wojpawlik** [comment]
Updated https://github.com/telegraf/telegraf/issues/705#issuecomment-549056045

**Comment by Porkechebure** [comment]
> It's true that scenes could use more docs. PR welcome. JSDoc comments are preferred over adding to readme.
> 
> @Porkechebure, you seem to misunderstand open source. You don't pay me, therefore I don't owe you anything, therefore you have no right to complain. Make the change you wish to see and open a PR. Or don't use the library, you will not be missed.

How I am supposed to make the change by making docs on something you developed and knows how it work? Lol

>You don't pay me, therefore I don't owe you anything
Have fun getting the issue section filled by questions then. Bye

>Or don't use the library, you will not be missed.
Like someone misses you. They miss your documentation though

**Comment by wojpawlik** [comment]
I'm not familiar with `Scenes` either. They were developed mostly by @dotcypress, and typed by @KnorpelSenf.
