### ISSUE TITLE
parse_mode doesn't work with editMessageText

### ISSUE THREAD

**Issue by ramsuthar305** [telegraf/telegraf#1337]
* Telegraf.js Version: ^4.0.2
* Node.js Version: 12.16.1
* Operating System: Ubuntu 20.14

## parse_mode doesn't work with ctx.editMessageText
I am trying to mention user, but it doen't mention user. 

```js
const editedMessage=`[ Ramm Suthar ](tg://user?id=123456789) Hello, wassup?`
ctx.editMessageText(editedMessage,{parse_mode:"Markdown"})
```

## Expected Behavior
I want user to be mentioned, like this
`Ramm Suthar Hello, wassup`

## Current Behavior
Message appears like this but user isn't getting mentioned 
`[ Ramm Suthar ](tg://user?id=123456789) Hello, wassup?`

**Comment by shakibamoshiri** [comment]
Hi,
For me it works perfectly. Here is the code I use :
```JS
req.answerCbQuery();
req.editMessageText( nextCaption,  {
    parse_mode: 'HTML',
    ...nextMenu
});
```
Version 4 of telegraf && Ubuntu 18
