### ISSUE TITLE
How to catch message from group chat?

### ISSUE THREAD

**Issue by ArtemNikolaev** [telegraf/telegraf#134]
*.hear doesn't work in group chat
Also *.on('message') and *.on('text') works only in private bot chat, but can't work inside any group channel.
How to fix this problem?

**Comment by Bostrot** [comment]
@ArtemNikolaev In order that your bot can interact with groups, change group privacy settings in botfather and insert this into your code:
	
	
	// Provide with options
	const bot = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})

	// Or you can get username from Telegram server
	const bot = new Telegraf(process.env.BOT_TOKEN)

	bot.telegram.getMe().then((botInfo) => {
	  bot.options.username = botInfo.username
	})

see [http://telegraf.js.org](http://telegraf.js.org)
