### ISSUE TITLE
[v5] `void` type

### ISSUE THREAD

**Issue by wojpawlik** [telegraf/telegraf#1342]
`void` type is problematic. Only `undefined` is directly assignable to `void`. `unknown` is assignable indirectly however:

```ts
const foo: () => void = (): unknown => 42
const bar = foo() 
// bar is `unknown` disguised as `void`
```

Because `void` is disguised `unknown`, unions with `void` are disguised `unknown`.

**Describe the solution you'd like**

- [x] Change `MiddleareFn` to return `Promise<unknown>` instead of `Promise<unknown> | void` (#1156),
- [ ] Remove now redundant `Promise.resolve` from `Telegraf::handleUpdate`, `Composer.catch` and `Composer.tap`,
- [ ] Change `Telegraf::handleError`, `SessionStore::get` and `SessionStore::delete` to return `MaybePromise<undefined>` or `Promise<void>` instead of `MaybePromise<void>`,
- [ ] Consider [banning](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) `void` entirely and replacing it with `undefined` or `unknown`,
- [ ] Consider enabling [`@typescript-eslint/explicit-module-boundary-types`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) for some files to surface inferred `void` return types?

**Comment by EdJoPaTo** [comment]
[@typescript-eslint/no-confusing-void-expression](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-confusing-void-expression.md)

**Comment by wojpawlik** [comment]
I'd rather replace eslint with deno lint :)

`MaybePromise<void>`s prevent `Map` from being assignable to `SessionStore`. To fix that in v5, they need to be changed to `MaybePromise<bool / this>`, or (better) the interface needs to be split into sync and async variant.

**Comment by MKRhere** [comment]
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghiARhACgJwPYFsCWBnCAHgBUA+KAXimKgB8p1t8iyBuAWACgvRIoBBAHYhKUAN4BfOlACuggCYQAZjkER50wTIA22jt06KAxtrhpoSuUeA4MgqEoAUAcwBcURwEpK5eElSYuASEQiCknu4Abhg48vpcxqbmDlY2dlDOXu6IGBjaEHCC+olmFqm29gAWWVDRscUQJqUpgtYVUDg1jEFEOXkFgqTxnE7OnvpOleNcTjjTnEA) | [Chat](https://t.me/TelegrafJSChat/89436)

![black magic](https://user-images.githubusercontent.com/19621208/201204738-5fd50e60-e9e2-4563-9c6d-8917c5b60f28.png)

**Comment by wojpawlik** [comment]
I prefer prefer `Promise<unknown> | void` over `Promise<Any>` after all; code like this fails to typecheck:

```ts
const fn: () => (Promise<unknown> | void) = () => 42;
```

**Comment by MKRhere** [comment]
That would not improve the situation.

> `MaybePromise<void>` prevents `Map`

`Promise<unknown> | void` also prevents `Map`!

Now, we can give up and make it truly just `unknown` (`MaybePromise<unknown>` will flatten to `unknown` as well). But we want to signal that `Store::{get,set,delete}` may return Promise.

Of the 4 options, only my version typechecks with `Map` and also retains `Promise`. Any other option must also solve both these problems.

[[Playground]](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyBDRAjYAFKCAWwEsBnYAHgBUA+OAXjmrgB84Djyq6BuAKH4B6AFRwAwgFcoUYADt4AN2BQyJCHLgih-UJFhwSClQDMMAY1QBlYGTUarMaD3oBvfnE9wA5sBgAuOAAKOQwiYECyGCgjbwBKRnpMHHxCUgoaNjhJOQATYBMjYFzaDy8KAODQ8Mjo2IAaOEUMABtJCOYEhiSsXE50qkUIEhKyz3yWvw6QsI6omLl4xPRe1K4MoZHSgF9BUTgAAQB3CAArMAwjlpIAawByMjgwQkgKXKaVe01tXXBoeCMMFMFmsti+jmcAHUzhcrrcaG4xj4-IEZjU4PNYl0eil+txMuwcvlCnJirQBF4MSiqrNagtvI1mm0OtRsRw0vicjc5BAjnJ6OxNrkKV4JlNUdU5nVFmy8RkuTy+QKmsNhfxdsIxMcYZdrvdHhAYAALFRPF4QN4fVTqb46PT-QzGKBmSxwGx2G0Q2TQ86624AJgRcHclN8MDRUvpcUCyT6HIyLEJeQKRRKAiRFQjdIaTVa7UCrMCQpFnkzkuzi0ZeZZ0fZ6yoCt5-PTlLFQKzGOl8SLqpLcDbwA7mJlgTlDbk3Kb5PVgiQKDgAEE5IhGMHtlkiSnSe92HJJC0Wun9gciDcoCbZA8zRBXsUrV8tHa-gZAcDXe7wU5ZGgANIAJSDEMvDDCVaU7KNlljNYBgJbJkxJMk+wqUD0WHBlc2ZAs2SgsdKCXRBp1bYBJiBFDIyxSDVlw-Dpw1V9nRBN0wRtYM4HMCAckqPciFwKA4A1di5CiTtnECD9PS-KhxI0egmFJI4VjASg0MaaT+SCOJ00E4Somcf0MDE5iHEkn1YT1Sg1NkuB5MU5Su1Uoz1M0wRtPgXTZH9bBDI9YyoR1OEbkDSzVxszAlJUpifKcrSNB0ySAGZvM-ZxfwA4K5OABSwrs+kHKi2gNIEIA)

**Comment by wojpawlik** [comment]
I'm talking strictly about `MiddlewareFn`. I already figured session store, I'm just waiting for #1713 to be merged into v5.

**Comment by MKRhere** [comment]
Closing this issue as done in v5.
