### ISSUE TITLE
Support vercel and nextjs Req and Res formats

### ISSUE THREAD

**Issue by mr47** [telegraf/telegraf#1369]
**Is your feature request related to a problem? Please describe.**
Feature request, like there a lot of providers that uses custom AWS functions that wraps basic stuff.
`req` `res` etc.

**Describe the solution you'd like**
Redefining `generateCallback` will make sure that get full response so people can use telegraf, make it rewritable or as an option on configuration when you working on AWS lambda env.
```js
export default function (
    hookPath,
    updateHandler
) {
    return async (
        req,
        res,
        next = () => {
            res.status(403);
        }
) => {
        if (req.method !== 'POST' || req.url !== hookPath) {
            return next()
        }
        let update = req.body;

        try {
            await updateHandler(update, res)
        } catch (err) {
            res.status(500);
            throw err
        }
    }
}
```

For example: 
```js
const bot = new Telegraf(token, {
    telegram: { webhookReply: true, webhookReplyGenerator: (req, res) => req.body  }
})
```

```ts
  webhookCallback(path = '/') {
   const fn = this.telegram.webhookReply && this.telegram.webhookReplyGenerator  ? this.telegram.webhookReplyGenerator : generateCallback;
    return fn(
      path,
      (update: tt.Update, res: http.ServerResponse) =>
        this.handleUpdate(update, res)
    )
  }
```

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by wojpawlik** [comment]
You can already build your own webhook callback by calling `bot.handleUpdate` manually, see https://github.com/telegraf/telegraf/blob/develop/docs/examples/koa-webhook-bot.js.

**Comment by mr47** [comment]
@wojpawlik got it thanks, anyway I think mentioning that you can just use `handleUpdate` in docs can help in the future. Thanks!

**Comment by wojpawlik** [comment]
Yeah, [`handleUpdate`](https://github.com/telegraf/telegraf/blob/b7985d3611822f295d0116c82bfe1998485dd0d3/src/telegraf.ts#L207) (and a lot of other functions) could use some JSDoc, PR welcome!
