### ISSUE TITLE
How to pass the username to a JSON ?

### ISSUE THREAD

**Issue by timothyleung713** [telegraf/telegraf#137]
I want to pass the username from 1 aws lambda function to another. So I have to get the username and pass it to the Payload in params. How can I assign the username to the Payload as JSON?

app.on('text', (ctx) => {
  const username = ctx.message.from.username
  return ctx.reply(username)
})

var params = {
   FunctionName: 'TestingNewbot', // the lambda function we are going to invoke
   InvocationType: 'RequestResponse',
   LogType: 'Tail',
   Payload: JSON.stringify({"username": username})  // the parameter we are passing
 };

**Comment by bostrot** [comment]
@timothyleung713 it is a bit unclear what you mean (at least I don't understand it). You are passing the username already in the payload. (post a bit more code if you can).

**Comment by timothyleung713** [comment]
@bostrot  Sorry for that.  Here is the full code.

I want to pass the username of the user from bot.js to another aws lambda function(TestingNewbot.js) which insert the username to the aws Dynamodb. 

___________________________________________________________________________
bot.js
const Telegraf = require('telegraf');
const app = new Telegraf('mybottoken');
var AWS = require('aws-sdk');
AWS.config.region = 'us-east-1';
var lambda = new AWS.Lambda();


app.on('text', (ctx) => {
const username = ctx.message.from.username
return ctx.reply(username)
})

/* AWS Lambda handler function */
exports.handler = (event, context, callback) => {


  var params = {
  FunctionName: 'TestingNewbot', // the lambda function we are going to invoke
  InvocationType: 'RequestResponse',
  LogType: 'Tail',
  Payload: JSON.stringify({"username": username}) // the parameter we are passing
  };

  lambda.invoke(params, function(err, data) {
   if (err) {
    context.fail(err);
   } else {
   context.succeed(data.Payload);
  }
 })

 const tmp = JSON.parse(event.body); // get data passed to us
  app.handleUpdate(tmp); // make Telegraf process that data
  return callback(null, { // return something for webhook, so it doesn't try to send same stuff again
    statusCode: 200,
    body: '',
  });
};

____________________________________________________________________________________
TestingNewbot.js
const AWS = require('aws-sdk');
const docClient = new AWS.DynamoDB.DocumentClient({region: 'us-east-1'});

exports.handle = function(event,ctx, callback){
  

    var params = {
      Item: {
        UserId : event.username
      },

      TableName: 'TestingNewbot'
    };

    docClient.put(params, function(err,data){
        if(err){
          callback(err,null);
        }
        else{
          callback(null, data);
        }
    });
}
