### ISSUE TITLE
Nonsense hangs uploading videos with local-api-server 

### ISSUE THREAD

**Issue by glococo** [telegraf/telegraf#1371]
Hi,

I am migrating some Youtube channels to Telegram Channel using a bot, however I need to upload bigger videos which require a local-bot-server and somehow it get stuck in the loop every one or two videos.

Note that it work flawlessly in the public server with videos below the size limit.
I also watch realtime logs of telegram-api-server on statistics port and seems to be all normal.

```
for loop {
await bot.telegram.sendVideo( chat_id, { source: `videos/${v.id}.mp4` }, { caption: v.caption })
await bot.telegram.sendMessage( chat_id, v.description )
}
```

* Telegraf.js Version: 4.0.3
* Node.js Version: 15.8.0 and 12.18.2
* Operating System: Ubuntu 20.10

Any clue ?

**Comment by wojpawlik** [comment]
Possibly related to #1301

**Comment by glococo** [comment]
Thanks for your reply. Bug confirmed.

I tried local, stream and buffer without success.
I then uploaded all videos to my https server, and run with **pipe url** and seems to works well !
Thanks 

Update: I uploaded 80 videos with 2 hangs. First iteration hangs at loop 13, second after 48 more loops, and the third ended well.
