### ISSUE TITLE
inlinekeyboard callbackbutton Action character limit

### ISSUE THREAD

**Issue by aminjoharinia** [telegraf/telegraf#138]
Hey there

i should transfer some data with inline keyboard callbackbutton action

`ctx.reply(`'   scene  ${S.result[key].Name}    '`, Extra.HTML().markup((m) =>
                m.inlineKeyboard([
                    m.callbackButton(` |   run scene    |   `, `SceneON🎻${S.result[key].idx}🎻🎷${S.result[key].Name}🎷`)
                ])
            ))`

some times the variables are long and this error happens 

`(node:545692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 400: Bad Request: BUTTON_DATA_INVALID`

what should i do ? is there any ways to expand this limit?

**Comment by bostrot** [comment]
Well, I guess there is no way to expand this limit. Though, you could try to use [sessions](http://telegraf.js.org/introduction.html#session) with an object to transfer your data.
