### ISSUE TITLE
Too restrictive typescript type on bot.url function

### ISSUE THREAD

**Issue by Akeboshiwind** [telegraf/telegraf#1381]
## Context

My goal is to have a function that gets called when the user sends a message with a url with a *specific* domain in it.

So if the user sends any of the following then I want my function to run:
```
example.com
https://example.com
https://example.com/my-sub-page
```

I'm new to the library but it looks like `bot.url` does what I want it to (although it's not really documented). But because the first parameter is labed `MaybeArray<string>`, typescript throws an error when I supply regex instead of a string.

It looks like there's a duplicate issue here: #1111

* Telegraf.js Version: 4.0.3
* Node.js Version: v14.4.0
* Operating System: OSX

## Minimal Example Code Reproducing the Issue

```ts
import { Telegraf } from 'telegraf'

const token = process.env.BOT_TOKEN;

if (token === undefined) {
  throw new Error('BOT_TOKEN must be provided!')
}

const bot = new Telegraf(token);

// @ts-ignore: MaybeArray<string> can also be a regex under the hood
bot.url(/^.example.com.*$/, (ctx) => {
    ctx.reply(`With match: ${ctx.match}`);
});

bot.launch()
```

If you remove the comment with `@ts-ignore`, the compiler will error with:
```bash
$ npx tsc                                                                                                                                                       127 ↵
src/index.ts:11:9 - error TS2345: Argument of type 'RegExp' is not assignable to parameter of type 'string | string[]'.
  Type 'RegExp' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.

11 bot.url(/^.example.com.*$/, (ctx) => {
           ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by equt** [comment]
The [`hears`](https://telegraf.js.org/classes/composer.html#hears) method should fit your needs.

```typescript
bot.hears(/^.example.com.$/, ctx => ctx.reply(`Matched!`))
```

**Comment by Akeboshiwind** [comment]
That does work for me yes :D

What is the actual use case of the `url` function then? It seems quite restrictive to only have exact matches?

**Comment by equt** [comment]
This is the point I'm confused about.

By the name `url` I would expect it to be a more concrete version of `hears`, which supports regex and helps do the stuff like URL validation. But I went through the examples under [examples](https://github.com/telegraf/telegraf/tree/develop/docs/examples) and found nothing helpful about this method.

I agree with the point that `url` could be more general, glad to help if the members find it useful.
