### ISSUE TITLE
Expose `MatchedContext` in typings

### ISSUE THREAD

**Issue by auguwu** [telegraf/telegraf#1383]
## Context
`MatchedContext` is used in `Composer.on` and it can't be inferred, so I can't tell what `ctx` should be when using functions instead of implementing in the `.on` block

* Telegraf.js Version: 4.0.3
* Node.js Version: 15.0.1
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```ts
const bot = new Telegraf('...');

function onChatMemberJoined(ctx: ???) { // `MatchedContext` isn't exported so I can't type what it is?
    // noop
}

bot.on('new_chat_members', onChatMemberJoined);
```

**Comment by wojpawlik** [comment]
4.1.0 exposed `NarrowedContext`, used by `MatchedContext`, isn't it enough?

**Comment by stanislav-suslov** [comment]
P.S. You also can use type reference. Example for instance of `Telegraf<Context>`:
`Parameters<typeof Telegraf.prototype.command>['1']`

**Comment by 0xtmphey** [comment]
@wojpawlik `NarrowedContext` doesn't allow to define context type with for e.g. text message update. 
```typescript
const bot = new Telegraf('...')

function handleMessage(ctx: ???) {
    ctx.message.text // `text` property isn't available here because no ability to specify `MatchedContext<Context, 'text'>`
}

bot.on('text', handleMessage)
```

**Comment by wojpawlik** [comment]
`NarrowedContext<Context, Types.MountMap['text']>`.
