### ISSUE TITLE
Handle updates directly using `handleUpdate` method on AWS Lambda

### ISSUE THREAD

**Issue by equt** [telegraf/telegraf#1389]
**Is your feature request related to a problem? Please describe.**

Currently, the [AWS Lambda example](https://github.com/telegraf/telegraf/blob/develop/docs/examples/aws-lambda.js) introduces a third-party `lambda-request-handler` which basically mocks a server to handle the updates from the telegram server.

**Describe the solution you'd like**

But this could be easily done with the following code

```typescript
import { Update } from 'typegram'

const bot = new Telegraf(token, {
    telegram: { webhookReply: true },
})

// The events received from AWS API Gateway are just raw `Update`s from Telegram
export const handler = async (event: Update) => {
    bot.handleUpdate(event)
}
```

**Comment by wojpawlik** [comment]
It's needed for `webhookReply`. I wouldn't mind merging adding another, simpler AWS example, and linking it from README.

> ```ts
> // The events received from AWS API Gateway are just raw `Update`s from Telegram
> ```

[_Citation needed_]

**Comment by equt** [comment]
> Regardless of which option you choose, you will receive JSON-serialized Update objects as a result.

From the [Getting updates](https://core.telegram.org/bots/api#getting-updates) section. Request toward API Gateway would be directly forward to AWS Lambda if no extra steps were set.

---

Honestly, I'm not sure what the `webhookReply` does here, and in #1250 this option seems to be discouraged. There seems no difference after I turned it off.

**Comment by wojpawlik** [comment]
See #1082.

I mean, I doubt that AWS gives you parsed JSON, you'd have no way to access headers.

**Comment by maxymshg** [comment]
Hi there,
I recently tried to launch AWS integration example, but it not works. I'm not sure is it my failure or example is not working.
I registered API Gateway as a trigger for AWS lambda with provided example, but `/start` command doesn't give me response. 

Would be great to have step-by-step guide for such examples.

**Comment by equt** [comment]
Tested that the example also doesn't work for me. Maybe the dependencies break or the configurations setup different? Using both HTTP API and the REST API.
