### ISSUE TITLE
InlineQueryResultPhoto and InlineQueryResultCachedPhoto confusion.

### ISSUE THREAD

**Issue by lioialessandro** [telegraf/telegraf#139]
Hello I'm writing a inline bot but I've got a problem with the answerInlineQuery.
I want to have an InlineQueryResultPhoto so that I can use an external photo but Telegraf gives me an error. `can't find field "photo_file_id"`. In the Telegram bot documentation, this field is a parameter of InlineQueryResultCachedPhoto. 
How can I use InlineQueryResultPhoto, instead of InlineQueryResultCachedPhoto?

**Comment by bostrot** [comment]
Could you post a bit of your code, please?

**Comment by lioialessandro** [comment]
I've resolved my issue. Apparently I wasn't giving an appropriate jpeg.
To avoid this confusion, is it possible to have a class pass to `answerInlineQuery`?
Like this: 
```
answerInlineQuery(new InlineQueryResultPhoto({id: id, thumb_url: '', photo_url: ''})
```

**Comment by bostrot** [comment]
No, but as I said, use cache_time.

**Comment by lioialessandro** [comment]
That's what I am asking.
This is becoming more a pull request than an issue.
It would be great to have a class for every InlineQueryResult* that Telegram support for better support and maintanance

**Comment by sascha1337** [comment]
How 2 fix this issue now ?
