### ISSUE TITLE
Wizard not going to the next step when bot is added in a group

### ISSUE THREAD

**Issue by roshankshaw** [telegraf/telegraf#1397]
## Context

* Telegraf.js Version: 4.1.2
* Node.js Version: 15.10
* Operating System: Ubuntu

## Minimal Example Code Reproducing the Issue

const registerWizard = new Scenes.WizardScene(
'REGISTER_WIZARD_ID', 
(ctx) => {
ctx.reply('Enter passcode');
return ctx.wizard.next();
},
async (ctx) => {
console.log('Step 2');
if (ctx.message.text === "test"){
await registerUser(ctx.message.chat.id,ctx);
}
else{
ctx.reply('You are unauthorized');
}
return ctx.scene.leave();
},
);

const stage = new Scenes.Stage([registerWizard]);
bot.use(session()); 
bot.use(stage.middleware());
bot.command('register',Scenes.Stage.enter('REGISTER_WIZARD_ID'));

## How to trigger the issue?
To trigger the issue, a bot with the above code can be added to the group and the wizard scene can be triggered using /register

## Expected Behavior
On posting /register, the bot asks for the passcode and depending on the reply, it either registers or discards. Its really simple flow.

## Current Behavior
The step 1 of wizard  is executed with bot replying 'Enter passcode'
However, on replying with pascode, it doesn't go to step 2 and 'step 2' is not logged. The bot stops responding.
The issue is not with registerUser method as  'step 2' is not logged in console which implies bot hasn't moved to next step.

**Comment by nick4fake** [comment]
Are there any workarounds? I haven't found any solutions

**Comment by nick4fake** [comment]
Nevermind.

@roshankshaw try disabling bot privacy
