### ISSUE TITLE
Crash when POST data is not JSON

### ISSUE THREAD

**Issue by 22sk** [telegraf/telegraf#14]
When POSTing is invoked from a non-Telegram source, such as Postman, the request might not contain valid JSON, or a different data type like x-www-form-urlencoded. The whole app crashes when this happens.

**Comment by dotcypress** [comment]
Thank you for feedback.

I suppose that webhook url is non-public information and only Telegram servers can reach it.

But if you want to filter malicious traffic, you might build security layer on top of Telegraf.

Any errors [will cause app stop](https://github.com/telegraf/telegraf/blob/develop/docs/introduction.md#error-handling), it's good for polling, and not for webhook.

Will fix it soon.
