### ISSUE TITLE
Telegraf 4.0.3 problem with webhook

### ISSUE THREAD

**Issue by swampfast** [telegraf/telegraf#1402]
## Context
* Telegraf.js Version: **4.0.3**
* Node.js Version: 12.21.0
* Operating System: Debian

## Minimal Example Code Reproducing the Issue
```
const tls = {
  key:  fs.readFileSync(key),
  cert: fs.readFileSync(pem),
  ca: [ fs.readFileSync(pem) ]
}
bot = new Telegraf(apikey);
bot.on('text', async (ctx) => { ctx.reply('echo'); });
bot.deleteWebhook;
bot.telegram.setWebhook('https://'+server+':8443'+'/'+apikey, {source: pem})
bot.startWebhook('/'+apikey, null, 8881); // nginx proxy 8443 to localhost:8881
``` 

## How to trigger the issue?

- Send message to bot

## Expected Behavior

- Bot replying 'echo' message 

## Current Behavior

- Nothing happens

## Error Message and Logs (`export DEBUG='telegraf:*'`)
console:

>   telegraf:core Webhook listening on port: 8881 +0ms

nginx error.log:
  many error messages (~30 per minute)

>   2021/03/11 13:15:37 [info] 9663#9663: *163 SSL_do_handshake() failed (SSL: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:SSL alert number 48) while SSL handshaking, client: 91.108.6.118, server: 0.0.0.0:8443

## Additional info 
Absolutly same code work good  with Telegraf ver. **3.38.0**. Bot succesfully replying 'echo' message, nginx error.log don't have messages and console log:

>   telegraf:webhook Incoming request POST /XXXXXXXXXX +0ms
>   telegraf:core Processing update 570050144 +11s
>   telegraf:client Call via webhook sendMessage { chat_id: XXXXXXX, text: 'echo' } +11s

**Comment by ttys83** [comment]
Try like this:
`bot.telegram.setWebhook('https://'+server+':8443'+'/'+apikey, {certificate: { source: pem }})`

**Comment by MKRhere** [comment]
Closing as stale
