### ISSUE TITLE
Difference between .sendCopy() and sendMessage()

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#141]
Hello!

Thank you for taking the time to read this.

Would it be possible to figure out what the difference between sendCopy() and sendMessage() is? It seems to do the same thing.

Best Regards,
Joshua

**Comment by bostrot** [comment]
@joshuaquek `sendCopy` sends the copy of a message, wether it's a video, photo, voice etc..

`sendMessage` sends the given text. See http://telegraf.js.org/telegram.html#sendcopy

**Comment by joshuaquek** [comment]
Hi dotcypress,

Thank you!!

Best Regards,
Josh
