### ISSUE TITLE
Markup<T> not exported

### ISSUE THREAD

**Issue by RainGrid** [telegraf/telegraf#1414]
## Context

* Telegraf.js Version: 4.1.1
* Node.js Version: 13.12.0
* Operating System: win 10 x64

Cant type own functions with Markup<T> because Markup class is not exported

**Comment by wojpawlik** [comment]
I could easily expose it, but I think you're better of accepting https://github.com/KnorpelSenf/typegram/blob/6bb1b9848a0b3234bf6546157d21b211009099d2/proxied.d.ts#L158-L162

**Comment by RainGrid** [comment]
> 
> 
> I could easily expose it, but I think you're better of accepting https://github.com/KnorpelSenf/typegram/blob/6bb1b9848a0b3234bf6546157d21b211009099d2/proxied.d.ts#L158-L162

![изображение](https://user-images.githubusercontent.com/5560310/111869760-a58b2900-89a2-11eb-9d8b-49b466e50802.png)

Thank you for the help, maybe you can give me an advice how to solve this warning the best way?

**Comment by wojpawlik** [comment]
`{ reply_markup: ReplyKeyboardMarkup }`?

I could easily expose `Markup` class, but that would bloat suggestions: https://github.com/telegraf/telegraf/pull/1134#issuecomment-706606221
![obraz](https://user-images.githubusercontent.com/23058303/111870768-e5dcae00-8986-11eb-8b61-a12f00d6e448.png)

**Comment by RainGrid** [comment]
@wojpawlik ok, thank you
