### ISSUE TITLE
How to notify user about error?

### ISSUE THREAD

**Issue by Lisand7ru** [telegraf/telegraf#142]
Is it possible to send a message to a user if error occurs while he using a bot?

Context is not passed to Telegraf.handleError, so is there another way?

**Comment by bostrot** [comment]
Are you looking for something like this?

	bot.command('start', async (ctx) => {
		try {
			await ctx.reply('If this message can\'t be sent') // something that may return an error
		} catch (e) {
			ctx.reply('Your command returned an error!')
		}
	})

**Comment by Lisand7ru** [comment]
i've been looking for such thing

`	app.use(async (ctx, next) => {
		try {
			let n = await next()
		} catch (e) {
			if(e instanceof Error && e.name == 'VKApiError') {
				ctx.reply('vk api error')
				return Promise.resolve()
			}

			return Promise.reject(e)
		}
		
		return Promise.resolve()
	})`
