### ISSUE TITLE
poll don't update ❓ 

### ISSUE THREAD

**Issue by ygorpinto** [telegraf/telegraf#1422]
Hello, I sent some polls to several groups to generate a report with the answers.
However for some reason my bot did not hear the answers, there would be some way to end the poll and receive this data?

![okok](https://user-images.githubusercontent.com/73406162/113350755-43baaf80-9310-11eb-842f-fc9e77033da1.png)

When I send a poll to a test group I can receive the voting data, but in the groups that I really needed it does not update the voting data.
I thought about ending the poll and recovering that data. Would there be any way to do that?

**Comment by chiliec** [comment]
I have this problem, but not for all users. Not receive answers from certain people.

**Comment by ygorpinto** [comment]
i've solved that using webhooks
