### ISSUE TITLE
How to get users of channel with telegraf bot?

### ISSUE THREAD

**Issue by siamak** [telegraf/telegraf#1429]
## Context

* Telegraf.js Version:
* Node.js Version:
* Operating System:

## Minimal Example Code Reproducing the Issue

```ts
// your code here. Please omit everything not related to the issue,
// to make it easier to pinpoint the cause.
// Please try running this code to make sure it actually reproduces the issue.
```

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
Please include any relevant log snippets or files here.
```

**Comment by waptik** [comment]
`bot.telegram.getChatMember` or `ctx.getChatMember`

Next time, please search through issues or discussion.

**Comment by allandiego** [comment]
Telegram bot api dont have a option to get all users from a channel / group. You need save all the members by yourself from a middleware to a database or in memory

**Comment by F3Joule** [comment]
> Telegram api dont have a option to get all users from a channel / group. You need save all the members by yourself from a middleware to a database or in memory

What about this method?
https://core.telegram.org/method/channels.getParticipants

**Comment by Amirkamaliannot** [comment]
> 

wrong
