### ISSUE TITLE
Image with caption and inline keyboard.

### ISSUE THREAD

**Issue by Kryjite** [telegraf/telegraf#144]
Hi. How to send photo with caption and inline keyboard? (w/o caption works perfectly)
This code dont work:
`telegram.sendPhoto('CLIENT_ID', 'http://lorempixel.com/400/200/cats/', {caption: 'cute kitty'}, Extra.markup((markup) => {
    return markup.inlineKeyboard([{
      'text': 'test button',
      'callback_data': '1'
    }
    ])
  }))`

**Comment by bostrot** [comment]
Not tested it but try to send the caption not as an object.
`telegram.sendPhoto('CLIENT_ID', 'http://lorempixel.com/400/200/cats/', 'cute kitty', ...`

**Comment by Kryjite** [comment]
> Not tested it but try to send the extras as an object.
Does not work

> you don't need to write the whole object in reply markup either
It's cool, but it does not solve my problem.

**Comment by Kryjite** [comment]
My decision:
`  function sendPhoto (chatId, photo, caption, extra) {
    return app.telegram.callApi('sendPhoto', Object.assign({ chat_id: chatId, photo: photo }, {caption: caption}, extra))
  }

  sendPhoto('420656223', 'http://lorempixel.com/400/200/cats/', 'cute kitty', Extra.markup(m => m.inlineKeyboard([m.callbackButton('test button', '1')])))`

**Comment by bostrot** [comment]
@Kryjite it seems like Extra.markup adds the reply_markup parameter by itself, so it will work if you put the pure object in it: ` telegram.sendPhoto('CLIENT_ID', 'http://lorempixel.com/400/200/cats/', {"reply_markup":{"inline_keyboard":[[{"text":"test button","callback_data":"test","hide":false}]]}, caption: 'cute kitty'})`

**Comment by Kryjite** [comment]
@bostrot works too. Ty.
