### ISSUE TITLE
Add revoke_messages option for kicking users

### ISSUE THREAD

**Issue by Moldoteck** [telegraf/telegraf#1443]
On march 9, there were some changes for tg api: https://core.telegram.org/bots/api
One of these: **Added the parameter revoke_messages to the method kickChatMember, allowing to delete all messages from a group for the user who is being removed.**
Looking here: https://github.com/telegraf/telegraf/blob/9584cf6bd741e5cd4ebc87a79fe5184e392a9ae9/src/telegram-types.ts
I see this:
```
export type ExtraKickChatMember = MakeExtra<
  'kickChatMember',
  'user_id' | 'until_date'
>
```
Can you add revoke_messages option too?

**Comment by sergpsu** [comment]
seems it is still not implemented: messages are still in group after their author is kicked

**Comment by juanbercoff** [comment]
> seems it is still not implemented: messages are still in group after their author is kicked

This is working as expected. The option 'revoke_messages' removes the ability from the removed user to see previous messages, it does not removes the removed user messages from the group. 

If revoke_messages is false or undefined it will remove then user but they will still be able to see all previous messages in the group.
