### ISSUE TITLE
Bot is write message in silent mode when mention somebody in inline link

### ISSUE THREAD

**Issue by eminpayizov** [telegraf/telegraf#1446]
## Context

* Telegraf.js Version: 4.3.0
* Node.js Version: 14.15.3
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```ts
let msg = `<a href="tg://user?id=${link}">${name}</a> ` // <a href="tg://user?id=123456789">username</a>
const message = await ctx.reply(msg, {
    parse_mode: 'HTML',
})
```

## Expected Behavior

Mentioned user will receive notification.

## Current Behavior

There '@' when enter the chat, but without any notification to mentioned user. And the link is clicable and opens user profile. Other users also don't get notification about bot's message when he mentions somebody, like he is writing in silent mode.

If I change the link in href to sthn wrong users get notification and everything okey.

**Comment by KnorpelSenf** [comment]
Telegraf is not responsible for handling notifications. If anything, this is an issue on Telegram's side.

Make sure not to have `disable_notification` set to `true` (it does not sound like you are doing that).
