### ISSUE TITLE
add replyKeyboardForceReply

### ISSUE THREAD

**Issue by Sakujes** [telegraf/telegraf#1466]
**Right now Telegraf is missing `replyKeyboardForceReply`**

**It is a part of the bot API here: https://core.telegram.org/constructor/replyKeyboardForceReply but not added in Telegraf yet.**

**An alternative is to use `reply_markup: {force_reply: true}`, but then only ONE option can be passed (https://stackoverflow.com/a/41841237/13152247), so it is impossible to for example use both a keyboard, and a forced reply in a single message, so adding this would fix that.**

**Comment by iamgabrielsoft** [comment]
That wonderful of you.. Thanks

**Comment by MKRhere** [comment]
That function is part of MTProto, and not part of [the Bot API](https://core.telegram.org/bots/api).
Closing as issue has become stale.
