### ISSUE TITLE
Can't Send a pdf in from of buffer.

### ISSUE THREAD

**Issue by Abhishek-Srivas** [telegraf/telegraf#1467]
**Is your feature request related to a problem? Please describe.**

I initially worked on the node-telegram-bot-api and then I wanted to switch my company project to telegraf but then I got stuck to this issue that I was not able to send a pdf file which I was creating through the template and then saving it to my local server.
Then I was reading the file fs.readfilesync and storing it in a buffer form in a const. But I was not able to send it.
 await ctx.telegram.sendDocument(ctx.chat.id,buffer); but it didn't work. But as I used node-telegram-bot API it started working. 
**Describe the solution you'd like**

Not sure how this can be done.
**Describe alternatives you've considered**

Looking into the matter why buffer can't be send.
**Additional context**

**Comment by 0wx** [comment]
You don't need to read it, you can use the file path directly 
```js
ctx.sendDocument({source: '/path/to/your.pdf', filename: 'your.pdf'})
````

**Comment by MKRhere** [comment]
Closing as resolved, please reopen if additional help required.
