### ISSUE TITLE
No way to pass options to setWebhook when using launch

### ISSUE THREAD

**Issue by Loskir** [telegraf/telegraf#1469]
https://github.com/telegraf/telegraf/blob/07a09eabeca1a76f714e56d7b2553fb9aa234723/src/telegraf.ts#L194-L197

It's impossible to pass extra options like `ip_address` to `setWebhook` when using `launch`

* Telegraf.js Version: v4

**Comment by ypopovych** [comment]
The same problem with a self-signed certificate. Can't pass "certificate" property

**Comment by rootvls** [comment]
Goodwork

**Comment by MKRhere** [comment]
Fixed in 0805f41f3347982a44ed3c6186ac84191be848dd & f24874c0e32cb2cb7292fb1a0becc763f9f11520
