### ISSUE TITLE
Error: 400: Bad Request: group send failed / Error: 400: Bad Request: wrong file identifier/HTTP URL specified

### ISSUE THREAD

**Issue by LWJerri** [telegraf/telegraf#1481]
1) Error text when I send specific images with other normal: `Error 400: bad Request: group sends failed`/`Error: 400: Bad Request: failed to get HTTP URL content`, method - `replyWithMediaGroup`.

2) Error text when I send ONLY specific images: `Error: 400: Bad Request: wrong file identifier/HTTP URL specified`, method - `replyWithMediaGroup`.

URLs:
- https://i.waifu.pics/rc2YxI-.png (SFW).
- https://i.waifu.pics/OTRfON6.jpg (SFW).

I don't know why I get these errors.

Example code
```ts
      const images = [
        "https://i.waifu.pics/xMRH74e.png",
        "https://i.waifu.pics/rc2YxI-.png", // BAD LINK
        "https://i.waifu.pics/DmrSW~9.jpg",
        "https://i.waifu.pics/-j4qjGv.png",
        "https://i.waifu.pics/cKe~bpZ.jpg",
        "https://i.waifu.pics/XcpL3nR.jpg",
        "https://i.waifu.pics/Weau1RP.jpg",
        "https://i.waifu.pics/OTRfON6.jpg", // BAD LINK
        "https://i.waifu.pics/8TL6ycS.jpg",
        "https://i.waifu.pics/DjgwmRf.jpg",
      ];

      await ctx.replyWithMediaGroup(
        images.map((image) => {
          return {
            type: "photo",
            media: image,
          };
        }),
      );
```

**Comment by nitreojs** [comment]
[Sending files](https://core.telegram.org/bots/api#sending-files)
Look at the second point: 
... _Telegram will download and send the file._ **5 MB max size for photos** _and 20 MB max for other types of content._ ...
Your photos are too big for telegram, in fact, they are bigger than 5 MB max size set for photos

**Comment by LWJerri** [comment]
> [Sending files](https://core.telegram.org/bots/api#sending-files)
> Look at the second point:
> ... _Telegram will download and send the file._ **5 MB max size for photos** _and 20 MB max for other types of content._ ...
> Your photos are too big for telegram, in fact, they are bigger than 5 MB max size set for photos

Hello! Thanks for your response and yes, it's resolved my problem, thanks!
