### ISSUE TITLE
How do I get author name who used command

### ISSUE THREAD

**Issue by vansh705** [telegraf/telegraf#1485]
Hey I want to know that how can I get author name and it's username with telegraf!

**Comment by mohdradin** [comment]
I Don't Understand What You Saying
Did you Mean
If A User Run Command You Need Console Log His User Name And Name,

**Comment by edgarhurtado27** [comment]
> I Don't Understand What You Saying Did you Mean If A User Run Command You Need Console Log His User Name And Name,

Yup! I guess that was the question... 
Is it possible to fetch that information?

**Comment by Latvels** [comment]
> Hey I want to know that how can I get author name and it's username with telegraf!

Print the response to the console by: ctx.update.message.from
And there will be everything available information on who wrote the message
