### ISSUE TITLE
How to remove the need for the user to write "/start" after each code update and bot restart

### ISSUE THREAD

**Issue by Abusher** [telegraf/telegraf#1496]
### Discussed in https://github.com/telegraf/telegraf/discussions/1495

<div type='discussions-op-text'>

<sup>Originally posted by **Abusher** August  2, 2021</sup>
Hello,

In my current implementation, after each code changes and restart, User should write "/start" command again
to make bot work and handle user commands.

Can I somehow avoid this mandatory "/start" for user after each code update?</div>

**Comment by 0xAVX** [comment]
You need to store the users in persist database which used the bot before(write the "/start" command).

**Comment by 0wx** [comment]
You should implement 'backward compatibility' in your code, means user can still send old commands to your bot and you treat it like the new ones or just use it the same way as if user send `/start` command where you can update anything from there.
