### ISSUE TITLE
[Question] Update InlineKeyboard

### ISSUE THREAD

**Issue by Ali-Khazaee** [telegraf/telegraf#1498]
I am trying to edit an InlineKeyboard but it will sends new message instead of editing previous message.

My code:

    Bot.hears('HelloInline', Context =>
    {
        const InlineMenu = [ ];

        InlineMenu[0] = [ Markup.button.callback('Hello', 'Hello'), Markup.button.callback('World', 'World') ];

        Context.replyWithMarkdown('HelloWorld', Markup.inlineKeyboard(InlineMenu));
    });

    Bot.action('Hello', (Context) =>
    {
        Context.answerCbQuery();

        const InlineMenu = [ ];

        InlineMenu[0] = [ Markup.button.callback('Hello World', 'HelloWorld') ];

        Context.editMessageText('HelloWorld', Markup.inlineKeyboard(InlineMenu));
    });

**Comment by pythonjsgo** [comment]
Try to use this, you didn't set `message_id`
`
Context.editMessageText(user_id, Context.callbackQuery.message.message_id, "yourtext", { reply_markup: Markup.inlineKeyboard(InlineMenu))})`

**Comment by kr4t0z** [comment]
any update??

**Comment by Ali-Khazaee** [comment]
@pythonjsgo I did tested your code, it did not worked, I did a few edit on it and now the editing message part works correctly.

This is what I did:

`Context.editMessageText(Context.callbackQuery.message.text, Context.callbackQuery.message.message_id, { reply_markup: Markup.inlineKeyboard(InlineMenu) });`

Editing message works but InlineKeyboard is not showing up

**Comment by Ali-Khazaee** [comment]
I found it.

`
Context.editMessageReplyMarkup({ inline_keyboard: InlineMenu }, { chat_id: Context.callbackQuery.message.chat.id, message_id: Context.callbackQuery.message.message_id });
`

**Comment by lasthead** [comment]
Is it possible to editMessageText with params: text, parse_mode and inline_keyboard?
That is, I need to do this in one go:

ctx.editMessageText(description, { chat_id, message_id, parse_mode: 'HTML' })
ctx.editMessageReplyMarkup({ inline_keyboard: keyboard }, { chat_id, message_id })

If I try to do like this InlineKeyboard is not showing up: ctx.editMessageText(description, { reply_markup: keyboard, chat_id, message_id, parse_mode: 'HTML' }) 

So, i need edit message with parse_mode and inline-keyboard. But I can't figure out how to do it
