### ISSUE TITLE
createChat method

### ISSUE THREAD

**Issue by fczuardi** [telegraf/telegraf#15]
I want to use telegraf to start a private chat with someone that messages a chat group, if I try to send the message directly to the user with 

```
ctx.telegram.sendMessage(ctx.update.message.from.id, 'hello');
```

I will receive the error:

```
Error: 403: Bot can't initiate conversation with a user
```

But if the user opens a private chat with my bot then it works.

I am suspecting that initiating a chat with a user id would be possible if the createChat method was implemented, right?

https://core.telegram.org/method/messages.createChat

**Comment by dotcypress** [comment]
Hey @fczuardi 

Unfortunately this method isn't part of [Bot API](https://core.telegram.org/bots/api).

If you want to use `createChat` method, you might be interested in [cli project](https://github.com/vysheng/tg)

**Comment by fczuardi** [comment]
Thanks! And thank you for the project! I've tried in a bot this weekend and it was a joy to use! :+1:
