### ISSUE TITLE
[Solved] Delete user message in bot

### ISSUE THREAD

**Issue by sadra** [telegraf/telegraf#150]
There is a bot that get user important info.
I want when i get a message from user, make it deleted or edited to ****, how can i do this?

**Comment by bostrot** [comment]
Currently you can do this only in groups. Though, you could create a "user-bot" and open a secret chat with your user.

**Comment by sadra** [comment]
Thank you.
But how can i make a secret chat? can you give me a document please?

**Comment by sadra** [comment]
I solve this issue, by making callBackKeyboard message
When a user want to enter password, you send him a number keyboard, and after user pressed the OK button, you can change it to stars or delete it.

Type You Password:
12
| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8| 9 |
| OK | 0 | EDIT |
