### ISSUE TITLE
Command Description

### ISSUE THREAD

**Issue by Ali-Khazaee** [telegraf/telegraf#1519]
How to add description to commands like below ?

https://ibb.co/xLP1Vty

**Comment by marefati110** [comment]
you can use
```ts
ctx.telegram.setMyCommands([
{
  command: "/ali",
  description: "ali description",
},
]);
```

**Comment by Ali-Khazaee** [comment]
@marefati110 Calling this method once would be enough or I should use it as middleware ?

**Comment by Ali-Khazaee** [comment]
Calling this method once for start command is enough
