### ISSUE TITLE
InlineQuery not working!

### ISSUE THREAD

**Issue by samsumas** [telegraf/telegraf#152]
The Inline Mode doesn't work in my bot : 
```const Telegraf = require('telegraf');
const { reply } = Telegraf;
const fetch = require('node-fetch')


const bot = new Telegraf("inserttoken");

bot.command('/oldschool', (ctx) => ctx.reply('Hello'));
bot.command('/modern', ({ reply }) => reply('Yo'));
bot.command('/hipster', reply('λ'));

const myInstantSearch = async (query = '', offset = 0, limit = 50) => {
  console.log("hello");
  const apiUrl = `https://api.cleanvoice.ru/myinstants/?type=many&limit=${limit}}&offset=${offset}&search=${encodeURIComponent(query)}`;
  const response = await fetch(apiUrl);
  const { tracks } = await response.json();
  return tracks.items;
}
bot.on('inline_query', (q) => console.log("works!") );

bot.on('inline_query', async ({ inlineQuery, answerInlineQuery }) => {
  console.log('hallo here!');
  const offset = parseInt(inlineQuery.offset) || 0;
  const items = await myInstantSearch(inlineQuery.query, offset, 50);
  const results = items.map((item) => ({
    type: 'audio',
    id: item.id,
    title: item.name,
    audio_url: item.audio_url
  }));
  return answerInlineQuery(results);
})

bot.startPolling();
```
the interesting part is actually the
` bot.on('inline_query', (q) => console.log("works!") );`
which doesn't print anything when i type @nameofbot abc in a chat...
In the telegram client the loading symbol starts to rotate but nothing else happens.
I did activate the inline mode with botfather, and simple commands like /hipster works...

**Comment by dotcypress** [comment]
Just copy pasted code and it works for me.

**Comment by samsumas** [comment]
hmm thats really strange : i just created a new bot with the Botfather and it works now...

**Comment by hosein2398** [comment]
Maybe that's because it takes a little bit of time to set `inline_query` by Telegram servers.
I don't know why is that, or even this is true or not, but  when I change `inline_query` of my bot it takes new changes a few minutes to be set.



I'm just writing this so that might be helpful for anyone having same experience in future.
