### ISSUE TITLE
Token redaction is broken

### ISSUE THREAD

**Issue by KnorpelSenf** [telegraf/telegraf#1522]
## Context

Telegraf messes with the network error log messages in an attempt to strip the token from the logs. This functionality is broken.

* Telegraf.js Version: 4.4.1
* Node.js Version: all (tested on 16.2.0)
* Operating System: Debian 10

## Minimal Example Code Reproducing the Issue

Let any network request fail to a local Bot API server.

## Expected Behavior

```
FetchError: request to http://localhost:8081/bot123456:[REDACTED]/sendMessage failed
```

## Current Behavior

```
FetchError: request to http://localhost:[REDACTED]/bot123456:AbCdEfGhIjKlMnOp-q/sendMessage failed
```

**Comment by wojpawlik** [comment]
https://github.com/telegraf/client is affected as well.

**Comment by KnorpelSenf** [comment]
The fix does not work with `apiMode` set to `user`.
