### ISSUE TITLE
How to make the bot add a member to group

### ISSUE THREAD

**Issue by Matheus8174** [telegraf/telegraf#1527]
My bot receive a contact list and add this contacts to some groups. How can it add a contact to the group?

**Comment by MKRhere** [comment]
Hello Matheus, regular bots that use the bot API (the kind you can build with telegraf) cannot add members to a group. You would need user bots for that.

**Comment by Matheus8174** [comment]
> Hello Matheus, regular bots that use the bot API (the kind you can build with telegraf) cannot add members to a group. You would need user bots for that.

**Comment by Matheus8174** [comment]
Hello MKRhere, where can i find this user bots?

**Comment by francisyzy** [comment]
https://github.com/topics/telegram-userbot has quite a few projects using userbot tag. Have not used any of it before.
