### ISSUE TITLE
deleteMessage method

### ISSUE THREAD

**Issue by Pitasi** [telegraf/telegraf#153]
Hello there.
Probably I'm just doing something wrong but I'm really getting out of this, so let me ask you.

I can't find a way to use the deleteMessage method (https://core.telegram.org/bots/api#deletemessage), it is supposed to delete bot's own messages or messages in groups where bot is admin.
So far so good, but when I call `ctx.deleteMessage()` it says it is not available for messages, and when I call `ctx.tg.deleteMessage(thechatid, themessageid)` I get `message identifier is not specified`.

Any clues? Thank you!

**Comment by Pitasi** [comment]
I was just using `ctx.message.id` instead of `ctx.message.message_id` ^^'.

So, the easy way to use this is: `ctx.tg.deleteMessage(ctx.chat.id, ctx.message.message_id)`.

**Comment by StarCanada** [comment]
Hi Pitasi,

I'm pretty new in Telegram programming. However, I used PHP to run some simple programming. My goal is get DeleteMessage() Function to work. Do you have a simple example for me to test and see how this works?

Thanks.

**Comment by teto1116** [comment]
hi, how i can delete every message of chat?

**Comment by MKRhere** [comment]
@teto1116 Don't bump old threads. Create a new issue if a thread is already closed. To answer your question, there's no simple way. You'll have to iterate all message IDs from latest and call `deleteMessage` on each, while handling errors. You'll probably get rate-limited by Telegram very quickly.

Ref: https://github.com/oscartcy/telegram-del-all-msg-bot/blob/76c6b2ff18b6c0dcb17457a260fc2c008ba5db69/bot.js
