### ISSUE TITLE
Custom context Typing

### ISSUE THREAD

**Issue by fedserfey** [telegraf/telegraf#1533]
Telegraf.js: 3.39.0
Node: 14.15.4

VS Code throws a typing problem with custom context instance _Telegraf(token, { contextType: CustomContext })_

```ts
import { Context, Telegraf, Telegram } from 'telegraf'
import { Update } from 'telegraf/typings/telegram-types'

const token = process.env.BOT_TOKEN

class CustomContext extends Context {
  constructor (
    update: Update,
    telegram: Telegram,
    options?: {
      username?: string
      channelMode?: boolean
    }
  ) {
    super(update, telegram, options)
  }

  reply (...args: Parameters<Context['reply']>) {
    console.log('reply called with args: %j', args)
    return super.reply(...args)
  }
}

const bot = new Telegraf<CustomContext>(token, { contextType: CustomContext })
```
***
Problem: 
_Type 'typeof CustomContext' is missing the following properties from type 'TelegrafContext': tg, update, updateType, updateSubTypes, and 71 more.ts(2740)
index.ts(28, 63): Did you mean to use 'new' with this expression?_

Incorrect typing in contextType property

**telegraf\typings\telegraf.d.ts**

if change 
```ts
  /**
   * Custom context
   */
  contextType?: TelegrafContext
```

to 

```ts
  /**
   * Custom context
   */
  contextType?: new (
    ...args: ConstructorParameters<typeof TelegrafContext>
  ) => TelegrafContext
```

problem never shows

**Comment by MKRhere** [comment]
v3 bugs will likely no longer be attended to, and as such I'm closing this issue as not planned. v4 has had many usability [improvements over the last year](https://github.com/telegraf/telegraf/releases/), and we're now looking forward to releasing v5.

**Comment by SaadBazaz** [comment]
This is how I imported the Context Types. Maybe this'll help?
```import { Telegraf, type Context as TelegrafContext } from 'telegraf'```
