### ISSUE TITLE
Need help with cron service

### ISSUE THREAD

**Issue by ghost** [telegraf/telegraf#1534]
Hi, there. Please forgive me if it's not the right place, but I could use some help, if that's okay.

I'm trying to make a bot that stores a list of friends birthdays on a database (currently using MongoDB for that) and then send push messages on the dates to remind the user to congratulate the friend.

So far I was able to store all the data I wanted (name and DOB) and set a command that returns a list with all the data already stored.

To check if its someone's birthday on the current date, i made a schedule with node-cron to check the database every day at 9am.

But then I got stuck when it comes to return a text message to the user saying if there is a birthday to remember or not.

## Context

* Telegraf.js Version: 4.4.2
* Node.js Version: 14.18.0
* Node-Cron Version: 3.0.0
* Operating System: Windows 10

## Here's the latest piece of code for the schedule task

```ts
cron.schedule(
  '* * * * *',
  async (ctx) => {
    console.info('CronJob is running now!');
    const hasBirthdays = await checkBirthdays();
    console.log(hasBirthdays);
    if (hasBirthdays.length > 0) {
      const message = checkBirthdays
        .map((friend) => `${friend.name} - ${friend.birthday}`)
        .join('\n');
      bot.telegram.sendMessage(
        chatID,
        `Olá, ${ctx.chat.first_name}! Aqui estão os aniversários já cadastrados: \n\n${message}`,
        { parse_mode: 'Markdown' }
      );
    }
  },
  {
    scheduled: true,
  }
);
```

I can tell that this schedule works because the second console log `console.log(hasBirthdays);` returns a proper list with all birthdays of the day. I created a fake with 7 people and set  the birthday of 3 of them to today and that console.log was able to return all 3.

Odd thing is that I don't get any errors on my terminal nor Telegram. All it happens, besides getting the first two console.logs, is that nothing is sent to chat.

Can someone please help me?

**Comment by NormandoHall** [comment]
You async function has **ctx** parameter, but where it comes? Also for **chatID**.

You need to store **chatID** and **first_name** along with birthdays in mongoDB, then you can used it to send the message.

**Comment by ghost** [comment]
> You async function has **ctx** parameter, but where it comes? Also for **chatID**.
> 
> You need to store **chatID** and **first_name** along with birthdays in mongoDB, then you can used it to send the message.

Thank you for replying and sorry for the late message.

I did what you said  and saved ctx parameter at my database. Like all the other data, I was able to get them but still I'm not being able to reply with a message.

But now I got an error! The error is "chat_id is empty".

Here's the code updated. Just like the first ones, All that console.logs are returning the right data.

```
cron.schedule(
  '* * * * *',
  async () => {
    console.info('CronJob is running now!');
    const hasBirthdays = await checkBirthdays();
    console.log(hasBirthdays);
    const chatID = await User.find({});
    console.log('aqui é o console do chatID do cron', chatID.chatId);
    if (hasBirthdays != '') {
      console.log('Here');
      bot.telegram.sendMessage(
        chatID.chatID,
        `Hoje é aniversário de: \n\n${hasBirthdays}`,
        {}
      );
    }
  },
  {
    scheduled: true,
  }
);
```

That console.log right before the if statement is returning the correct parameter. For example, let's assume the ctx i've saved had a chatID = 123456. That's  exaclty the chatID I see on that console.log.

 Can you tell me what i'm doing wrong again?
I can console.log all the proper data i've stored, but i can figure out how to send a message returning that data to Telegram.

**Comment by NormandoHall** [comment]
> chatID.chatID

Maybe `chatID.chatId` ?

**Comment by Alex-146** [comment]
I think `const chatID = await User.find({});` returns collection of users, in this case you should iterate it and for each user send message to its `chat.id`

**Comment by MKRhere** [comment]
Sorry for the late reply, I'm going over old issues.
@Alex-146 was right, but it also returns all users, which you don't want. You want something like this:

```TypeScript
// filter users by birthday
const users = await User.find({ birthday: today });
// iterate over users array
for (const user of users) {
	// wish each user by their chatId, or whatever it's stored as
	bot.telegram.sendMessage(user.chatId, "...");
}
```

You don't need the `await checkBirthdays()` check, because `User.find` will already return a filtered list and if it's an empty array, no users will be wished.
