### ISSUE TITLE
description: "Webhook is already deleted"

### ISSUE THREAD

**Issue by lemondsun** [telegraf/telegraf#1540]
Trying to deploy my webhooks with AWS Lambda but I keep getting this error.

{
ok: true,
result: true,
description: "Webhook is already deleted"
}

Does anyone have experience with this error I can seem to find the solution?

**Comment by murka** [comment]
Your webhook is already deleted, use [setWebhook](https://core.telegram.org/bots/api#setwebhook) to set a new webhook.

**Comment by MKRhere** [comment]
Closing as stale
