### ISSUE TITLE
After stages.middleware does not work any middleware

### ISSUE THREAD

**Issue by gajet5** [telegraf/telegraf#1541]
* Telegraf.js Version: 4.4.2
* Node.js Version: v14.15.0
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```
const telegraf = new Telegraf<IContext>(config.TELEGRAM.KEY);

telegraf.use((_ctx, next) => {
  console.log('Before stage');
  return next();
});
telegraf.use(stages.middleware());
telegraf.use((_ctx, next) => {
  console.log('After stage');
  return next();
});

telegraf.launch();
```

after stages.middleware does not work middleware

![image](https://user-images.githubusercontent.com/3825412/138255667-c12402a7-d5c8-4007-a8af-0a47233ef3c1.png)

**Comment by huajun07** [comment]
Faced a similar issue `"telegraf": "^4.4.1"` , a possible work around:
```
telegraf.use((_ctx, next) => {
  console.log('Before stage');
  return next();
});

bot.use(async (_ctx, next) => {
  await stage.middleware()(_ctx, async () => {
    return
  })
  return next()
})

telegraf.use((_ctx, next) => {
  console.log('After stage');
  return next();
});

telegraf.launch();
```

**Comment by MKRhere** [comment]
I suspect Stage had a default scene set, and it the bot was always putting the user in the scene if they weren't in it.

If you still have this issue, please reopen or create new issue. Closing for housekeeping. Sorry for the late response; we're trying to actively close issues now.
