### ISSUE TITLE
Error: 400: Bad Request: failed to get HTTP URL content

### ISSUE THREAD

**Issue by umnichka** [telegraf/telegraf#1549]
I tried telegram.SendDocument(chatid, 'name.txt') and replyWithDocument('name.txt') and all time i get this errors:
1.Error: 400: Bad Request: failed to get HTTP URL content
2.Error: 400: Bad Request: invalid file HTTP URL specified: Host is invalid
I try to send txt file, size of it is 294 bytes

**Comment by MKRhere** [comment]
Use `sendDocument(chatId, { source: 'name.txt' })`.
