### ISSUE TITLE
Await Messages / Message Collector

### ISSUE THREAD

**Issue by gaurishhs** [telegraf/telegraf#1550]
**Is your feature request related to a problem? Please describe.**
Yes, i do have problems collecting messages

**Describe the solution you'd like**
I would like if developers add a function that when a command is run, we can Collect messages sent by user to bot and push them to a collection.

**Describe alternatives you've considered**
Tried arguments but those dont work with slash cmnds.

**Comment by jacobwaller** [comment]
I'm not sure what your request means. 
Could you give a specific example?

**Comment by MKRhere** [comment]
This is out of scope for Telegraf, but very trivial to implement yourself. Pseudocode (you might need to sanitise the Context object):

```TypeScript
bot.on("message", ctx => pushToCollectionSomehow(ctx));
```
