### ISSUE TITLE
How to download Telegram url

### ISSUE THREAD

**Issue by mayeaux** [telegraf/telegraf#1552]
If I have a link on Telegram such as https://t.me/channelName/1234

How can I download the video file?

I've been looking all over and the best I can do is a 400 error.

**Comment by 0xMDIV** [comment]
do you mean to download a video someone send or to download from a link

**Comment by mayeaux** [comment]
Download a video

**Comment by mikilian** [comment]
Generate the file url using `ctx.telegram.getFileLink()` and download the resource behind the generated url afterwards. The function requires a `fileId` as parameter, which can be found in `ctx.message.video.file_id` or `ctx.message.document.file_id`.
