### ISSUE TITLE
telegraf-mock

### ISSUE THREAD

**Issue by cleverocheck** [telegraf/telegraf#1556]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I write unit tests for bots made on Telegraf
## Describe the solution you'd like
I wanted you to make a set of testing tools within this package or a separate package, something like telegraf-mock
## Describe alternatives you've considered
The only alternative is to emulate the essence of the telegraf library with some of your own not completely correct methods and decompose the logic into unnecessary parts for testing

**Comment by jacobwaller** [comment]
You should write separate handler functions for your handlers that you may put directly in a `bot.command()`

ex:
instead of 
```
bot.command('help, (ctx, next) => ....
```
do
```
const helpHandler = (ctx, next) => {
...
}

bot.command("help", helpHandler);
```

You can then just mock the context & next objects

**Comment by cleverocheck** [comment]
@jacobwaller i am now testing my telegram bots in this way.  But sometimes, in order to test some function in the application, you need to do not quite the right rendering.  Also, sometimes it's hard enough to mock the context so that it doesn't break at all and it's easy to work with the output from the function. What you wrote is a workaround, as I indicated above.  I would like to get a ready-made set of tools for normal ctx simulation and other telegraf functions

**Comment by jacobwaller** [comment]
If you're using Jest, then mocking isn't too difficult. And verifying what the function's output also isn't difficult. I can't see this mocking being a high priority for the maintainers here. It might be helpful to create your own package which contains mocks for telegraf?

**Comment by cleverocheck** [comment]
Of course, I can create my own package for pure testing, but as you know, for commercial projects it is very expensive and no one will agree to this (and using a module written with other people's money in new projects is also not an option).  So I'd like to get a ready-made open package somewhere, I think it will be useful for many others who have this problem.  By the way, I also use jest.  In an example where a set of testing tools is needed, as in this case, I can give a database - without a ready-made mock, it will be quite difficult to test the code with it, especially if you use orm

**Comment by MKRhere** [comment]
You could, in your tests, create a bot instance and not call `bot.launch`, use `bot.handleUpdate` to send your own updates into the system. Then do: `new Telegraf(token, { telegram: { agent, attachmentAgent } })`, where agent and attachmentAgent are mocks for `http.Agent`.

This way you keep all the behaviour of Telegraf, while capturing the calls going outward and mocking the updates going in.

**Comment by cleverocheck** [comment]
@MKRhere very good solution, thanks for answer. What I really like about this solution is that I will not simulate the internal state of any specific handler, but simulate the behavior from the outside, this is exactly what I need from testing. I think we can close this issue, as a good solution was found
