### ISSUE TITLE
package-lock.json

### ISSUE THREAD

**Issue by fend25** [telegraf/telegraf#156]
Hi.
There is no `package-lock.json` file in the repo, nor such line in the .gitignore.
Is a PR with such file (or yarn.lock) welcome?

**Comment by dotcypress** [comment]
I don't think this is necessary for libraries, please [read this thread](https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514)

**Comment by fend25** [comment]
@dotcypress thank you for the link. it really makes sense.
how about PR with adding .npmrc file which content is:
```
+package-lock=false
```

**Comment by dotcypress** [comment]
@fend25 I think `.gitignore` is better place for that.
