### ISSUE TITLE
InputMedia* in typegram is different from same type in telegraf/src/core/types/typegram

### ISSUE THREAD

**Issue by AuroraDysis** [telegraf/telegraf#1568]
## Context

for example, in telegraf/src/core/types/typegram

```ts
type InputMediaDocument = {
    type: "document";
    media: string | InputFile;
    thumb?: InputFile | undefined;
    caption?: string | undefined;
    parse_mode?: ParseMode | undefined;
    caption_entities?: MessageEntity[] | undefined;
    disable_content_type_detection?: boolean | undefined;
}
```

but in typegram, it looks like
```ts
type InputMediaDocument = {
    type: "document";
    media: string;
    thumb?: undefined;
    caption?: string | undefined;
    parse_mode?: ParseMode | undefined;
    caption_entities?: MessageEntity[] | undefined;
    disable_content_type_detection?: boolean | undefined;
}
```

At least the following types have the same problem:
- InputMediaPhoto
- InputMediaVideo
- InputMediaAnimation
- InputMediaAudio
- InputMediaDocument

* Telegraf.js Version: 4.6.0
* Node.js Version: 16.x
* Operating System: macOS 12.1

## Expected Behavior

same types should have the same definitions.

## Current Behavior

same types have different definitions.

**Comment by MKRhere** [comment]
Would this be solved for you by exposing the types from Telegraf?

Edit: typegram is now available to be imported as `telegraf/types`.
