### ISSUE TITLE
dynamically obtain chat_id from express route?

### ISSUE THREAD

**Issue by Pascal3366** [telegraf/telegraf#157]
Hi, i have another question:

i still have this express route:

```js
app.post('/pinMessage', function(req, res) {
  var message = req.body.message;
  var chat_id = '-1001118865999';
  console.log(message);
  console.log(bot.telegram.Message.message_id)
  bot.telegram.sendMessage(chat_id, message).then((m) => {
    bot.telegram.pinChatMessage(chat_id, m.message_id)
  })
});
```
how do i get the chat_id in  a dynamic way?

thx in advance.

**Comment by dotcypress** [comment]
You can send `chatId` with message in `POST` request.

```js
app.post('/pinMessage', function(req, res) {
  var message = req.body.message;
  var chat_id = req.body.chat_id;
  console.log(message);
  bot.telegram.sendMessage(chat_id, message).then((m) => {
    bot.telegram.pinChatMessage(chat_id, m.message_id)
  })
});
```

**Comment by Pascal3366** [comment]
Yes i know,
but i want Telegraf to automatically obtain the chat id from the telegram servers
Is there any way to accomplish that?
Otherwise i will have to keep it static in a variable ...

**Comment by dotcypress** [comment]
It's impossible to obtain `chat_id` from `message_id`, cause `message_id` isn't global unique.
And yes, you can hardcode it or use environment variables.
