### ISSUE TITLE
Telegraf "npm install" output prompt:  2 high severity vulnerabilities

### ISSUE THREAD

**Issue by valentinpezon-izi** [telegraf/telegraf#1570]
Hi, when you run npm audit after installing telegraf you get this output :
![Screenshot 2022-01-22 at 18 45 04](https://user-images.githubusercontent.com/90831026/150649705-20db045e-dd5a-40ba-a5de-8b70f1cd3a98.png)

Maybe you can update the node-fetch version?

Thanks

**Comment by MKRhere** [comment]
Fixed in #1578
