### ISSUE TITLE
Unable to send data via XMLHttpRequest() to my nodejs

### ISSUE THREAD

**Issue by lieyongchang** [telegraf/telegraf#1575]
I am trying to send data from my js to nodejs via XMLHttpRequest. The data here is result.

Below is a snippet of my js code, saveResult is being call inside spin function

```
function saveResult (result) {
    console.log('saveResult ', result);
    var request = new window.XMLHttpRequest()
    request.open('POST', '/result', true)
    request.setRequestHeader('Content-Type', 'application/json; charset=UTF-8')
    request.send('{"result": ' + result + '}')
}


function spin(d){
  ...
  vis.transition()
      .duration(3000)
      .attrTween("transform", rotTween)
      .each("end", function(){
          //mark question as seen
          d3.select(".slice:nth-child(" + (picked + 1) + ") path")

          oldrotation = rotation;
    
          /* Get the result value */   
           var result = data[picked].value;
          saveResult(result);
          container.on("click", spin);
      });
}

```
Steps to reproduce the error message:

 1. click this [link][1] to open the game
2. Click the word 'CUISINE' to spin the wheel
3. Open web console

Actual Result: the above error message will be shown
Expected Result: able to send data to my nodejs without any issue

Any advice is appreciated.

  [1]: https://compassionate-pasteur-332166.netlify.app/

**Comment by s0ftik3** [comment]
how is that related to Telegraf?
