### ISSUE TITLE
Plugin request for Kamailio

### ISSUE THREAD

**Issue by prasathsekar** [telegraf/telegraf#1576]
The plugin for Kamailio is not available.

But this plugin is available for Prometheus.

**Comment by MKRhere** [comment]
You need to define exactly what you want from this plugin, and how it's in scope for Telegraf. Telegraf isn't a monitoring solution like Prometheus, it's a Bot API framework.

**Comment by prasathsekar** [comment]
Kamailio can be used to build large platforms for VoIP and realtime communications – presence, WebRTC, Instant messaging and other applications.  Moreover, it can be easily used for scaling up SIP-to-PSTN gateways, PBX systems or media servers like Asterisk™, FreeSWITCH™ or SEMS.

Need the Below metrics 

'Meta' metrics about exporter CPU/memory usage/uptime.
OpenSIPS load (CPU/UDP & TCP children processing messages)
OpenSIPS memory usage (per PID, % free, shared memory, private memory)
OpenSIPS replies/requests (rate of replies/requests per type)
OpenSIPS netstat (bytes waiting for consumption, network traffic)
OpenSIPS dialogs (dialog rate per status, dialogs from other OpenSIPS instances)
OpenSIPS transactions (transactions reply rate per type, current transactions in memory)
Kamailio transactions (transactions reply rate per type, current transactions in memory)
OpenSIPS error rate
OpenSIPS URI checks rate
OpenSIPS User Location module (users per domain, user registration rate, users per OpenSIPS process)

**Comment by MKRhere** [comment]
Closing as discussed outside this channel, outside the scope of this repository.
