### ISSUE TITLE
Plugin request for Stunnel 

### ISSUE THREAD

**Issue by prasathsekar** [telegraf/telegraf#1577]
The plugin for Stunnel is not available.

**Comment by MKRhere** [comment]
Are you talking about this? https://www.stunnel.org/
What would this plugin provide exactly?

**Comment by prasathsekar** [comment]
The stunnel program is an encryption wrapper between a client and a server. It listens on the port specified in its configuration file, encrypts the communitation with the client, and forwards the data to the original daemon listening on its usual port. This way, you can secure any service that itself does not support any type of encryption, or improve the security of a service that uses a type of encryption that you want to avoid for security reasons, such as SSL versions 2 and 3, affected by the POODLE SSL vulnerability.


We are using it for redis. Also we need to check the service of stunnel is up and running.

**Comment by MKRhere** [comment]
What exactly do you want to encrypt here? Bot API already uses TLS (by HTTPS); stunnel for redis would be out of scope for telegraf. I may be misunderstanding your request. Could you phrase the request better?

**Comment by MKRhere** [comment]
Closing as discussed outside this channel, outside the scope of this repository.
