### ISSUE TITLE
Return type of `context.replyWithVideo` does not support `Message.AnimationMessage`

### ISSUE THREAD

**Issue by sikrinick** [telegraf/telegraf#1579]
## Context

* Telegraf.js Version:
* Node.js Version: v17.3.0
* Operating System: macOS 11.6.2

## Minimal Example Code Reproducing the Issue

```ts
this.telegraf.on("message", async (ctx) => {

    await ctx.replyWithVideo("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4")
         .then(message => {
              // implicit typescript message type is Message.VideoMessage
              message.video.file_id // compiles and passes
         })    

    
    await ctx.replyWithVideo("put here some mp4 without sound")
         .then(message => {
              // implicit typescript message type is Message.VideoMessage
              message.animation.file_id // fails in compile-time, due to implicit message type
              message.video.file_id // fails in runtime, as it does not have video property and value is undefined 
         })    

})
```

Telegram considers MP4 videos without sound as GIFs, animations.
Even though one sends MP4 video with replyWithVideo, returning message is a Message.AnimationMessage, and this has to be specified in typescript types.

## Expected Behavior
```ts
ctx.replyWithVideo("url").then(message => {
   // implicit type of message as Message.MediaMessage & Partial<Message.VideoMessage> & Partial<Message.AnimationMessage>
}) 
```

## Current Behavior
```ts
ctx.replyWithVideo("url").then(message => {
   // implicit type of message is Message.VideoMessage
}) 
```

**Comment by MKRhere** [comment]
Wouldn't the correct type then be `Message.VideoMessage | Message.AnimationMessage`? I guess that will introduce the same issue as #1388, but I'd rather handle all of these type issues in one place (fix the Message type) than have a makeshift solution in each place.

@KnorpelSenf Requesting your opinion on supporting this Telegram behaviour

**Comment by KnorpelSenf** [comment]
In fact, the scope of this is even broader.

> The server can change type of the file in any way if the change is appropriate to improve receiver's experience. Only sendPhoto and sendDocument with the parameter disable_content_type_detection are guaranteed to send a photo/a document on success.

— [Source](https://t.me/tdlibchat/28632)

This means that the most reasonable way of type annotation would be to only return `Message`. However, this will force users to check message types in basically all scenarios, even if they know that the server won't magically change the message type.

That's why we decided against this a few months ago.

**Comment by MKRhere** [comment]
Thanks for chiming in; @sikrinick thoughts on this update? If you have a better suggestion, we'll hear it; otherwise becomes impractical for developer experience to return `Message`.

**Comment by sikrinick** [comment]
My point is that users don't need to know an actual message type, until they work with it.
I didn't make any investigation, but my hypothesis is that for media messages, like video or animation, at least, in order to decrease latency, developer would like to use `file_id`.
`file_id` is not a field of a `Message.MediaMessage`, but is accessible as a field of `video` property in `Message.VideoMessage` and as a field in `animation` property of `Message.AnimationMessage`.

Maybe it is possible, at least to delegate that `file_id` property upstream to `Message.MediaMessage` at least? Currently it holds only optional `media_group_id?: string`.

**Comment by MKRhere** [comment]
We can't do that, because `PhotoMessage` does not have `file_id`, and even if it did, we try to stick to the same type the API provides us, to avoid deviation and confusion. Regardless, I'm not sure how this helps with your original issue.

**Comment by sikrinick** [comment]
Maybe it is possible to leave it like that, but add a generic parameter T for replyWith... methods?
So we could specify an expected type, if we know about possible reply message type change?
For example, `function replyWithVideo<T = Message.VideoMessage>(...): Promise<T>`?
However, it works the same with `ctx.replyWithVideo(it: CustomMessageType => ...)`, therefore, I don't know, maybe this issue just has to be closed.

**Comment by MKRhere** [comment]
Assertion seems the best way here if you know the return type for sure. Closing as there are no alternatives from our side.
