### ISSUE TITLE
How could delete or edit both photo and inlinekeyboard ?

### ISSUE THREAD

**Issue by aminjoharinia** [telegraf/telegraf#158]
Hi
i want to delete or edit both photo and inlinekeyboard
how could i do that 
```
ctx.replyWithPhoto(`AgADBAADXKkxG5tLMFGkGa61MfnchLLVnBkABMr0vKZAzg6l8IIEAAEC`, Extra.HTML().markup((m) =>
      m.inlineKeyboard([
        [m.callbackButton(` ➕ `, '+coca')],
        [m.callbackButton(` coca`, `coca detail`)],
        [m.callbackButton(` ➖ `, `-coca`)]
      ])))
```
Thanks

**Comment by dotcypress** [comment]
Hey.

Unfortunately, with [Telegram BOT Api](https://core.telegram.org/bots/api#updating-messages) you can only update `Text`/`Caption`/`Reply markup` keyboard, but not `Photo`.
