### ISSUE TITLE
How to make a simple chat bot like livegram bot in telegraf

### ISSUE THREAD

**Issue by kashyapndps00** [telegraf/telegraf#1584]
I m new anyone could teach me basics of telegraf if i m asking others they are asking for Money Please Help Me

**Comment by MKRhere** [comment]
Here's an excellent introduction to Telegraf, Scenes, and Wizards (courtesy of https://github.com/telegraf/telegraf/discussions/1586):

https://dev.to/maklut/telegraf-vs-node-telegram-bot-api-36fk

Do raise an issue if you have a more specific question, or consider joining the Telegram chat: https://t.me/TelegrafJSChat
