### ISSUE TITLE
bot.command() work for"/command", but will not for "/command@botname"

### ISSUE THREAD

**Issue by ViacheslavLabs** [telegraf/telegraf#159]
Hi, this command will work only for "/chatid", but will not for "/chatid@botname". How can I correct it?

```
bot.command('chatid', ({ chat, from, reply }) => {
  return reply(chat.id);
})
```

**Comment by dotcypress** [comment]
For handling `/chatid@botname` you need to provide bot username.

js```
// Provide with options
const app = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})

// Or you can get username from Telegram server
const app = new Telegraf(process.env.BOT_TOKEN)

app.telegram.getMe().then((botInfo) => {
  app.options.username = botInfo.username
})

app.command('chatid', (ctx) => ctx.reply('Hello World'))
```

Related docs: http://telegraf.js.org/advanced.html
