### ISSUE TITLE
replyWithAudio, sendAudio - Error: 400: Bad Request: type of file mismatch

### ISSUE THREAD

**Issue by Shiyinq** [telegraf/telegraf#1600]
## Context

Trying send voice note but got error Bad Request

* Telegraf.js Version: ^4.3.0
* Node.js Version: v14.7.0
* Operating System: macOS Monterey 12.3

## Minimal Example Code Reproducing the Issue

```js
bot.on('voice', (ctx) => {
    let id = ctx.message.chat.id
    let voiceID = ctx.message.voice.file_id
    console.log(ctx.message)
    ctx.replyWithAudio(voiceID)
})
```

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
(node:6297) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: type of file mismatch
    at Telegram.callApi (/Users/myuser/<path-project>/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by spaskhalov** [comment]
same problem...

**Comment by MKRhere** [comment]
Files with the `.ogg` file format are treated as voice messages. To send a voice file, use `replyWithVoice` rather than `replyWithAudio`. The provided example will work when modified as follows:

```TypeScript
bot.on("voice", ctx => ctx.replyWithVoice(ctx.message.voice.file_id));
```
