### ISSUE TITLE
Command skipping on iphone

### ISSUE THREAD

**Issue by grunch** [telegraf/telegraf#1603]
Hi, I am having a weird issue and I commented here to know if sounds familiar to someone, I have a start file like this

```javascript
const initialize = (botToken, options) => {

  const bot = new Telegraf(botToken, options);
  
  bot.start(async (ctx) => { ... });

  bot.command('sell', async (ctx) => { ... });
  
  ...
  
  bot.command('release', async (ctx) => { ... });
  
  bot.action('addInvoiceBtn', async (ctx) => { ... });
  
  // finally this for non recognized commands
  bot.on('text', async (ctx) => { ... });
 
  return bot;
};
```
 
Normally this is working fine, but recently an Iphone X (ios 15.2) user reported that when he tried to execute `/release` command the bot responded with the message on `bot.on('text')`, for some reason the bot skipped the `bot.command('release')`, I asked him to do it again trying to `console.log` the context on `bot.command('release')` but it never entered there, then the user did it from an android and it worked, any ideas what would be happening here? 

* Telegraf.js Version: 4.6.0
* Node.js Version: v16.13.0
* Operating System: Linux 4.15.0-163-generic  x86_64 GNU/Linux

thanks

**Comment by NormandoHall** [comment]
It is very strange. I suspect some issue with blank spaces at the end, some upper case, etc.

I have iOS 15.4.1 and runs ok. I can't test it with 15.2. Telegraf 4.7.0

![image](https://user-images.githubusercontent.com/2943127/163088189-3ee6dd14-b08a-4483-a044-9b85592db5ae.png)


Can you get a capture of console.log?

**Comment by grunch** [comment]
Hi, I think I know what is happening, the same user had the issue again, let me try to explain it.

The bot suggest to the user the command the user have to execute, to make it easier to the user I started to use markdown and enclose it in \` (backtick) like this `/release order_id` doing this in telegraf the user just need to touch the text and the text will be copied to clipboard.

This works great with 99% of the users but for some reason for this user and another one, on iphone when they copy and paste the text it is pasted formated on monospace, we can see it here.

![photo_2022-04-13_19-16-38](https://user-images.githubusercontent.com/228364/163279482-01daa917-781f-4be6-8ed4-43bf9153fc87.jpg)

How can I avoid this? should I remove markdown only for 1% of the users?

**Comment by dr-iroh** [comment]
I think it is not Telegraf or the mobile, but some incompatibility of the Telegram app. But you could work around that by trying to use a callback button instead of a command

**Comment by NormandoHall** [comment]
> How can I avoid this? should I remove markdown only for 1% of the users?

A workaround can be:

```js
// finally this for non recognized commands
bot.on('text', async (ctx) => { 
  if(ctx.message.text.includes('/release')) {
  //do something with it... maybe split with space and get last array element to get the hex code
}
});
```

**Comment by grunch** [comment]
yes, both suggestions are good to consider, thank you very much @NormandoHall @dr-iroh 

I am closing this issue 😃

**Comment by NormandoHall** [comment]
> ![photo_2022-04-13_19-16-38](https://user-images.githubusercontent.com/228364/163279482-01daa917-781f-4be6-8ed4-43bf9153fc87.jpg)
> 
Looking at the picture I see a space between slash `/` and `release` in the first two. This can be the issue.
