### ISSUE TITLE
Does the bot react only to commands?

### ISSUE THREAD

**Issue by GRawhideMart** [telegraf/telegraf#1605]
Hello community! This is my first time asking questions about this wonderful library.
I have the following snippet of code:
```
const { Telegraf } = require('telegraf')
require('dotenv').config()

const bot = new Telegraf(process.env.BOT_TOKEN)
const ALLOWED_GROUPS = require('./constants/allowedChats')

const response = require('./commands')
const randomAnswer = require('./randomAnswers')

bot.start(ctx => {
    ctx.reply('Started service');
})

bot.help((ctx) => ctx.reply('Per ora rispondo solo a /zia e /mamma.\nStay tuned'))

// bot.on('message', (ctx, next) => {
//     if(ALLOWED_GROUPS.includes(ctx.update.message.chat.id)) {
//         console.log(ctx.update.message.text)
//         randomAnswer(ctx)
//         next()
//     }
// })

bot.on('text', ctx => {
    if(ALLOWED_GROUPS.includes(ctx.update.message.chat.id)) {
        randomAnswer(ctx)
        const receivedText = ctx.update.message.text;
        if(response.hasOwnProperty(receivedText)) {
            ctx.reply(response[receivedText]())
        } else {
            ctx.reply('Non ho capito')
        }
        
    } else {
        console.log(ALLOWED_GROUPS)
        console.log(ctx.update.message.chat.id)
        ctx.reply('Non hai i permessi di usarmi. Parlane con ' + process.env.ADMIN)
    }
})

bot.launch()
```
Now, I want the on 'text' to react to all of the messages, because randomAnswer(ctx) is a function which replies only to certain users, only one time out of 8 (I coded it this way)

```
const chanceOfAnswer = Math.floor(Math.random() * 8) == 0

module.exports = (ctx) => {
    if(ctx.update.message.from.first_name == process.env.ADMIN_NAME) {
        console.log(chanceOfAnswer)
        if(chanceOfAnswer) {
            const random = Math.floor(Math.random() * require('../commands/zia/risposte').length)
            return require('../commands/zia/risposte')[random]
        }
    }
}
```
I would expect this function to be fired each time a message is received from ADMIN_NAME, however it only works when I send a message starting with "/" (i.e. a command).
Is there any way to get past this limitation?

**Comment by NormandoHall** [comment]
If I understood correctly, you need a catch all like this:

```js
bot.use( async (ctx) {
  // do something...
});
```

Take care where you use this function, at the end or before others, you will need to continue with `next()`

```js
bot.use( async (ctx, next) {
  // do something...
  next();
});
```

**Comment by humblecoder** [comment]
@GRawhideMart I believe bots themselves must also have admin rights in order to interact with "all" messages.  While it's a "feature" of the TG API, it would be nice if it were clearly documented with `telegraf` examples listed.  Also, more practical (less basic/contrived) examples in general would be nice.  Really great project, but documentation is still . . . 😞

**Comment by MKRhere** [comment]
> bots themselves must also have admin rights in order to interact with "all" messages

No, they need to have their privacy mode turned off in botfather for them to receive all messages, and not just `/command@botname`. You're right, it could be mentioned somewhere. I'll look into it.

![image](https://user-images.githubusercontent.com/19621208/190469121-2a265c3b-3e0d-4e6d-bbce-b3a900fec54f.png)

**Comment by MKRhere** [comment]
Closing as resolved, feel free to reopen if this wasn't the problem.
