### ISSUE TITLE
look massage view

### ISSUE THREAD

**Issue by Amirhz9479** [telegraf/telegraf#161]
Hi guya!
how to look massage view in channels with telegraf
I mean that: 
![image](https://user-images.githubusercontent.com/20737945/29229177-3ba3a8c8-7ef2-11e7-8de5-c494f08ca559.png)

**Comment by dotcypress** [comment]
Hey.

Unfortunately, Telegram Bot Api doesn't support this feature.

You can try to fetch views using [MTProto](https://github.com/zerobias/telegram-mtproto)
