### ISSUE TITLE
sendDocument gives this error when sending file localy

### ISSUE THREAD

**Issue by lester51** [telegraf/telegraf#1622]
MY CODE
api.telegram.sendDocument(msg.from.id, {
   source: fs.readFileSync("/data/data/com.termux/files/home/sdcard/1Videoshow/telebot/SharedFiles"),
   filename: "torrent-links.txt"
})

ERROR MESSAGE
EISDIR: illegal operation on a directory, read

UPDATE SORRY MY MISTAKE IS "filename" need to be remove and "msg.from.id" to "msg.chat.id

WORKING CODE
api.telegram.sendDocument(msg.chat.id, {
   source: fs.readFileSync("/data/data/com.termux/files/home/sdcard/1Videoshow/telebot/SharedFiles/torrent-links.txt")
})

but file name is "document.data"😂 how can I fix this?

ANOTHER UPDATE: I FIGURE IT OUT YOU CAN CLOSE THIS😁

FULL WORKING CODE
const caption = { caption: "Test Caption" };
await api.telegram.sendDocument(msg.chat.id, {
source: fs.createReadStream("SharedFiles/torrent-links.txt"),
filename:"torrent-links.txt"
}, caption);

Output Name: torrent-links.txt w/caption

**Comment by lester51** [comment]
when I remove filename and put the absolute path on text file its sending but the filename is different and this file is send through dm though the message is from a group chat

output filename: document.dat

**Comment by MKRhere** [comment]
Great, closing as resolved
