### ISSUE TITLE
Webhooks lose their endpoint / URL after running for some time

### ISSUE THREAD

**Issue by olifur** [telegraf/telegraf#1624]
Hi,

I am using telegraf to run 4 bots in production using webhooks.

Now from time to time my bots lose their webhook urls and no requests are working any more. It just removes the url field.

I can see it using the getWebhookInfo endpoint.

If I delete the webhook and set it new it works for some time like hours or days but after some time it loses it again and all bots stop working.
Bots running all the time, nothing restarted etc.

Does one has seen this phenomena?

Here is someone else with a similar problem:
https://stackoverflow.com/questions/65574782/telegram-bot-webhook-url-gets-cleared-after-couple-requests

Best,
Oliver

**Comment by olifur** [comment]
Sorry can be closed! I was running another instances in a dev stage (i was unaware of), where I was constantly overwriting the webhook with polling getUpdates.
Sorry for stealing your time
Oliver

**Comment by sandrina-p** [comment]
Thanks @olifur , your comment made me realize I was making the same mistake! Disabling the `polling` solved it.
