### ISSUE TITLE
Typings resolution error with TS 4.7 in "Node16" mode

### ISSUE THREAD

**Issue by ulrichb** [telegraf/telegraf#1629]
## Context

* Telegraf.js Version: 4.8.2
* Node.js Version: 16
* Operating System: Win

## Minimal Example Code Reproducing the Issue

```ts
import * as telegraf from "telegraf";
```

With the (as of TS 4.7) released "native Node ESM module" support (activated via`"module": "node16"`) all "telegraf" imports fail with _"Could not find a declaration file for module 'telegraf'"_.

This is because in this mode TSC prefers the `"exports"` declaration in telegraf's package.json (and ignores the top-level `"types": "./typings/index.d.ts"`). See [this answer](https://github.com/microsoft/TypeScript/issues/49160#issuecomment-1137482639) from the TS team.

When locally changing `"exports": { ".":"./lib/index.js" }` to `"exports": {   ".": { "require": "./lib/index.js", "types": "./typings/index.d.ts" } }` the error disappears. This is also documented here: https://www.typescriptlang.org/docs/handbook/esm-node.html

Should I propose a PR with this fix?

**Comment by MKRhere** [comment]
> Should I propose a PR with this fix?

Yes! PR welcome :)

**Comment by ulrichb** [comment]
Repro sample (used in the following PR): [telegraf1629repro.zip](https://github.com/telegraf/telegraf/files/8799301/telegraf1629repro.zip)

**Comment by mees-** [comment]
Telegraf is currently the only library keeping me from fully converting to ESM. I really appreciate the effort! 😁
