### ISSUE TITLE
MiddlewareObj is not exported

### ISSUE THREAD

**Issue by dalechyn** [telegraf/telegraf#1630]
## Context

* Telegraf.js Version:
* Node.js Version:
* Operating System:

## Minimal Example Code Reproducing the Issue

Currently I have to manually exclude the `MiddlewareFn` in order to get the `MiddlewareObj` result type.
```ts
import { Context, MiddlewareObj, Middleware } from 'telegraf'
import { Update } from 'typegram'

export class TelegrafRetryMiddleware implements MiddlewareObj<Context<Update>>
{}
```

## Expected Behavior

```ts
import { Context, MiddlewareObj, Middleware } from 'telegraf'
import { Update } from 'typegram'

export class TelegrafRetryMiddleware implements MiddlewareObj<Context<Update>
{}
```

## Current Behavior
Currently I have to manually exclude the `MiddlewareFn` in order to get the `MiddlewareObj` result type.
```ts
import { Context, MiddlewareFn, Middleware } from 'telegraf'
import { Update } from 'typegram'

export class TelegrafRetryMiddleware
  implements Exclude<Middleware<Context<Update>>, MiddlewareFn<Context<Update>>>
{}
```

**Comment by MKRhere** [comment]
Fixed in 3010028c6b3285d1702769bb96dc6e04b323a76e.
