### ISSUE TITLE
repo:telegraf sendReaction

### ISSUE THREAD

**Issue by kdabwl** [telegraf/telegraf#1634]
When forwarding messages to bot, users want to see a reaction - the API says sendReaction to that.

A simple [unicode widget is possible](https://core.telegram.org/method/messages.sendReaction) and sufficient for indicating that the bot processed the forwarded message.

If there is already a way to reply with something similar, please show example. TIA

**Comment by dr-iroh** [comment]
That API is for MTProto only. If you wish you can use GramJS using the [tgsnake](https://npm.im/tgsnake) framework, but at your own risk. Since MTProto is a pretty strict API, and your account could be banned or deleted for life

**Comment by kdabwl** [comment]
Thanks.

**Comment by MKRhere** [comment]
Whenever sendReaction is added to the [Bot API](https://core.telegram.org/bots/api), we'll add support in Telegraf! :)

**Comment by cavazzatommaso** [comment]
Still waiting. Any news on telegram api side?

**Comment by MKRhere** [comment]
@cavazzatommaso No. Follow Bot API updates here: https://core.telegram.org/bots/api-changelog and channels like https://t.me/tgbeta. It's meaningless to wait on Telegraf repo before Bot API has an update.
