### ISSUE TITLE
Bad Request: can't parse menu button: MenuButton must be an Object

### ISSUE THREAD

**Issue by kdabwl** [telegraf/telegraf#1635]
Attempted to use ctx.setChatMenuButton but the MenuButton arg is not wanted.

Can you please answer an example that works, TIA.

OTOH all I want is to replace the existing button with other (text,url), any suggestion?

**Comment by dr-iroh** [comment]
Example for WebApp button:
```javascript
ctx.setChatMenuButton({
  type: 'web_app',
  text: 'Open WebApp',
  web_app: {
    url: 'https://...'
  }
})
```
Example for commands menu
```javascript
ctx.setChatMenuButton({
  type: 'default'
})
```

**Comment by kdabwl** [comment]
perfect :-)
