### ISSUE TITLE
Additional types for specific messages

### ISSUE THREAD

**Issue by atassis** [telegraf/telegraf#1643]
Add types for messages with additional data provided.
For example, we have `request_contact` option for `KeyboardButton`. If we send a contact to a bot- it will come as a [Contact](https://core.telegram.org/bots/api#contact) object in a message. No types for this are provided.
```javascript
bot.on('message', (ctx, next) => {
  if(ctx.update.message.contact) {
    console.log(ctx.update.message);
  }
});
```
Hope this code helps (might write smth erronously)
Also you might want to look through all types of messages and add else existing types

**Comment by wojpawlik** [comment]
Duplicate of #1388
