### ISSUE TITLE
Type Error between telegraf and typegram 

### ISSUE THREAD

**Issue by schrodienieur** [telegraf/telegraf#1644]
There is a difference between ErrorPayload types from telegraf/src/core/network/error.ts and ApiError types from typegram/api.d.ts. Property 'ok' is missing.

`interface ErrorPayload {
  error_code: number
  description: string
  parameters?: ResponseParameters
}`

`export interface ApiError {
  ok: false;
  error_code: number;
  description: string;
  parameters?: ResponseParameters;
}`

**Comment by MKRhere** [comment]
`ErrorPayload` is never exposed directly, only via `TelegramError`, which extends builtin `Error`. Since it is by definition an error object, seems redundant to have `ok: false`. What's your usecase?

**Comment by MKRhere** [comment]
Closing as not planned, please feel free to reopen if you have a usecase.
