### ISSUE TITLE
Add Deno support (esm)

### ISSUE THREAD

**Issue by kerosan** [telegraf/telegraf#1651]
I'd like to use this package with deno but now I cant import dependency in my project 
import {Telegraf} from "https://esm.sh/telegraf@4.8.5" throw error
/* esm.sh - error */
throw new Error("[esm.sh] " + "Package path ./lib/index is not exported from package /tmp/esm-build-ea24d6868886f752f9a14e4b8ad7716e9bf9f220-42830795/node_modules/telegraf (see exports field in /tmp/esm-build-ea24d6868886f752f9a14e4b8ad7716e9bf9f220-42830795/node_modules/telegraf/package.json)");
export default null;

**Comment by kerosan** [comment]
found solution https://doc.deno.land/https://deno.land/x/grammy@v1.9.1/mod.ts

**Comment by Evertt** [comment]
@kerosan I'm sorry, can you re-open this issue maybe?

I still can't get telegraf to work when I'm trying to deploy it on Deno. It works locally, because then I can just use `"npm:telegraf@4"`. But I can't get it to work deployed on Deno for the life of me...

**Comment by MKRhere** [comment]
@Evertt What happens when you Deno Deploy with `npm:telegraf`?

In other news: Telegraf v5 will natively support Deno (WIP in [feat-deno](https://github.com/telegraf/telegraf/tree/feat-deno))

**Comment by MKRhere** [comment]
Closing this in favour of #1812
