### ISSUE TITLE
Pass through secret_token in webhook launch options

### ISSUE THREAD

**Issue by atassis** [telegraf/telegraf#1658]
**Is your feature request related to a problem? Please describe.**
I want to set a 'secret_token' in a telegraf instance (it exists [here](https://github.com/KnorpelSenf/typegram/blob/eacfff9f4db49631313d57f1f256ba833225681d/proxied.d.ts#L125)
```typescipt 
const bot = new Telegraf('token', { launchOptions: { webhook: { ...params, secret_token } } });
```

**Describe the solution you'd like**
Pass an optional param and handle it in a callback

**Comment by atassis** [comment]
The secret token is provided via `X-Telegram-Bot-Api-Secret-Token` header as described [here](https://core.telegram.org/bots/api#setwebhook)
So to handle it we have to check if request has provided a proper token there

**Comment by MKRhere** [comment]
Will land in 4.9.0, watch #1671

**Comment by MKRhere** [comment]
Completed in #1671, v4.9.0
