### ISSUE TITLE
Integration and example file for Restify

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#166]
Hello there,

May I know how can telegraf integrate with Restify? Will there be an example file demonstrating the integration of Restify and telegraf in webhook mode?

**Comment by dotcypress** [comment]
Hey.

Try to use Telegraf server callback(`webhookCallback`) for that.  

```js
const restify = require('restify')
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)
bot.telegram.setWebhook('https://domain.tld/secret/url')
bot.command('start', ({ reply }) => reply('Welcome!')

const server = restify.createServer({
  name: 'myapp',
  version: '1.0.0'
})
server.use(bot.webhookCallback('/secret/url'))
server.use(restify.plugins.acceptParser(server.acceptable))
server.use(restify.plugins.queryParser())
server.use(restify.plugins.bodyParser())

server.get('/echo/:name', function (req, res, next) {
  res.send(req.params)
  return next()
})

server.listen(8080, function () {
  console.log('%s listening at %s', server.name, server.url)
})
```

**Comment by lifehome** [comment]
Thanks for the demonstration! However I wonder if I shall put the commands in this file, or some ways to integrate that?

**Comment by lifehome** [comment]
https://github.com/lifehome/SilentServiceBot/blob/dab3ed5d9f8426412fa525793f2c9fcc9b76e29c/handlers/endpointModules/botInitializer.js#L53

May I ask how to feed webhook response into restify? As it seem just passing `res` into `handleUpdate` is not enough (and even break the restify handler)

Also if using the the `webhookCallback` function, it seems restify cannot handle such request, yet there are no error message shown.
