### ISSUE TITLE
Disable polling and webhook

### ISSUE THREAD

**Issue by skynet-cloud** [telegraf/telegraf#1662]
I need disable polling and webhook too
 only send message not receives msg
I can't how
If not please add none mode to disable polling and send only
I want use multi instance with one token not so for bypass conflicted update I need disable polling and only send message not receives msg
Thx

**Comment by empas** [comment]
you can send messages without bot frameworks. just send GET request to `https://api.telegram.org/bot${tg.token}/sendMessage?chat_id=${tg.chatId}&text=${text}`

**Comment by hypernova7** [comment]
You can use Telegram Bot API without using bot.launch

bot.launch, bot.startPolling or bot.webhookCallback are just for handling the requests that are sent to the bot.  The bot will be able to continue sending messages without using any of the aforementioned methods


```javascript
// This will work without the need to use bot.launch or bot.startPolling
const bot = new Telegraf(token)
bot.telegram.sendVideo({
  source: 'path'
}, {
  caption: 'text'
})
bot.telegram.sendMessage(chatId, text, {
  parse_mode: 'HTML'
})
```

**Comment by MKRhere** [comment]
Closing as resolved with @hypernova7's reply
