### ISSUE TITLE
How I can remove the keyboard?

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#167]
Hi, @dotcypress 

How I can remove the keyboard after use?
It's only hidden.

```js
bot.command('onetime', ({ reply }) =>
  reply('One time keyboard', Markup
    .keyboard(['/simple', '/inline', '/pyramid'])
    .oneTime()
    .resize()
    .extra()
  )
)
```

Thanks

**Comment by TiagoDanin** [comment]
Hi, @ajsb85.
Use the `Markup.removeKeyboard(true)`

**Comment by ajsb85** [comment]
Muito obirgado @TiagoDanin 
And also works for me `{reply_markup: {remove_keyboard: true}}`

Vly

**Comment by palmerabollo** [comment]
Do you know why using `one_time_keyboard: true` (or the function `.oneTime()`) doesn't work as expected?

[Docs](https://core.telegram.org/bots/api#replykeyboardmarkup) states:

> Requests clients to **hide the keyboard as soon as it's been used**. The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat – the user can press a special button in the input field to see the custom keyboard again. Defaults to false.
