### ISSUE TITLE
why Markup buttons don't work after restart app?

### ISSUE THREAD

**Issue by pogran** [telegraf/telegraf#1675]
when i restart my app, previews buttons on history don't work. why?

**Comment by hypernova7** [comment]
> when i restart my app, previews buttons on history don't work. why?

Any minimal example you can share of what is happening?

**Comment by pogran** [comment]
> > when i restart my app, previews buttons on history don't work. why?
> 
> Any minimal example you can share of what is happening?

I have problem with session . I lost all session data after restart app.
i think problem with this **bot.use(session())**

**Comment by MKRhere** [comment]
@pogran Builtin session is in-memory, so it will be lost on bot restarts. In production, you should use a telegraf session adapter that's backed by a db.

**Comment by MKRhere** [comment]
Closing as resolved, reopen if you need further help. [This](https://www.npmjs.com/package/telegraf-session-mongodb) is one example of a db adapter for telegraf session.
