### ISSUE TITLE
Consider moving `telegraf/bin` to `@telegraf/cli`

### ISSUE THREAD

**Issue by MKRhere** [telegraf/telegraf#1676]
Supersedes #1384.

For v5, consider one of two options:

* slim down the 3 dependencies that telegraf/bin brings with it (minimist, module-alias, and es-main) to do just enough for telegraf/bin, so bin is not heavy enough to consider moving.
	- the benefit is that things like `telegraf -m set-webhook -D { url: "..." }` can stay in the main repo
* move bin to a new package, `@telegraf/cli`, which may then outdate [micro-bot](https://github.com/telegraf/micro-bot). This could be especially useful if bin were to get even more features.
	- the downside is that micro-bot has to currently re-export much of telegraf anyway, made tricky by type exports and the such with modern Telegraf. User needing both `@telegraf/cli` and `telegraf` (as a peerDep of cli?) would negate the point of having a simple plug-and-play alternative to micro-bot.

In all, I consider this a low-priority goal for v5. bin's dependencies are tiny compared to node-fetch and abort-controller, which is what we must remove first in favour of native.

**Comment by wojpawlik** [comment]
I recommend https://github.com/lukeed/mri. `es-main` is *tiny*. Is `module-alias` still necessary?

**Comment by MKRhere** [comment]
You're right, module-alias is not necessary anymore. mri looks good!
