### ISSUE TITLE
How to send a message when starting the bot server?

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#168]
Hello! (:

How does one send a message to a user (assuming the user_id is 12345) .... using ctx.telegram.send( 12345 , "Hello!") ... when the bot server is started? Is there a way to do so? or must it be manually be done using a command ...bot.command( 'send' , (ctx) =>{ ctx.telegram.send( 12345 , "Hello") } )?

Hope to hear from you soon!

**Comment by dotcypress** [comment]
Hey.

Unfortunately, You can't send message to user using `user_id`, you need to use `chat_id` for that.

**Comment by joshuaquek** [comment]
Hi dotcypress oh... ok, if I were to use a chat_id, how can this be done?  🤔 
Is there a way to send a message once the bot server starts?

**Comment by dotcypress** [comment]
You need to save all known chat ids to database, and use these ids on bot startup.

**Comment by joshuaquek** [comment]
oh... hmmm but I already have these IDs on my database (mongo)...How do I send it when the bot starts up? ...because bot.command() is only invoked when the user speaks to the bot. Is there a way to trigger the sending when the bot starts up?

**Comment by tcelestino** [comment]
I have to some problem here. I'm using the method `start` but it does not work too. Telegram show this message:

```
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}
```
