### ISSUE TITLE
Bad shorthand for context's replyWithVideo method 

### ISSUE THREAD

**Issue by Quite-Right** [telegraf/telegraf#1687]
replyWithVideo(this: Context, ...args: Shorthand<'sendAudio'>) {
    deprecate(
      'ctx.replyWithVideo',
      'reply',
      'sendVideo',
      'https://telegraf.js.org/experimental#new-reply'
    )
    return this.sendVideo(...args)
  }

**Comment by Quite-Right** [comment]
` replyWithVideo(this: Context, ...args: Shorthand<'sendVideo'>) {
    deprecate(
      'ctx.replyWithVideo',
      'reply',
      'sendVideo',
      'https://telegraf.js.org/experimental#new-reply'
    )
    return this.sendVideo(...args)
  }`

**Comment by MKRhere** [comment]
Thanks!
