### ISSUE TITLE
Receive all files

### ISSUE THREAD

**Issue by H03in** [telegraf/telegraf#169]
hi there

is there any way to receive with none media format?
like ttf

tanks.

**Comment by dotcypress** [comment]
Hey.

I'm not sure, but maybe you need something like `bot.on('document', (ctx) => ...)`?

**Comment by H03in** [comment]
yes type of other files is document
but bot.on('document'.. does not work
instead i have to use bot.on('message' and check message json
please fix it
tanks.

**Comment by dotcypress** [comment]
So strange, cause it working great `bot.on('document', (ctx) => ctx.reply('doc'))`

Could you provide more info?

**Comment by H03in** [comment]
i tested that again and worked so good!
maybe i was forget to save the code!
i`m new in java script ;-)

anyway tanks for your good support :-)
