### ISSUE TITLE
getUserProfilePhotos should probably takes number & string

### ISSUE THREAD

**Issue by raskyer** [telegraf/telegraf#1700]
For now, in the typescript definition of `getUserProfilePhotos` we have :
```typescript
getUserProfilePhotos(userId: number, offset?: number, limit?: number) {
  return this.callApi('getUserProfilePhotos', {
    user_id: userId,
    offset,
    limit,
  })
}
```

Since telegram id could be pretty big (cf. big int), it would be more wise to also add `string` in the supported type for userId, as it is the case for other method.

**Comment by MKRhere** [comment]
`getUserProfilePhotos` only accepts userId.

Refer: https://core.telegram.org/bots/api#getuserprofilephotos
