### ISSUE TITLE
Replace `Telegram::getFileLink` with `Telegram::downloadFile`

### ISSUE THREAD

**Issue by wojpawlik** [telegraf/telegraf#1703]

**Comment by KnorpelSenf** [comment]
Replace? So there will be no way to obtain the link anymore?

**Comment by MKRhere** [comment]
It's unsafe to expose outside of that context anyway. And if user wishes to for an obscure usecase, they could also construct the link themselves using file_id and token.

Is there any merit to being able to obtain the link other than being able to download the file?

**Comment by KnorpelSenf** [comment]
It's sometimes leaking a token, but not always (not even in the following cases)
- streaming it
- sending the link to other APIs which can directly download the file
- sending the link to a user to download the file
