### ISSUE TITLE
Callback data after InlineQuery

### ISSUE THREAD

**Issue by lioialessandro** [telegraf/telegraf#171]
Is it possible to send a `callback_data` after the user has clicked on one of the `InlineQueryResult`s? How?

**Comment by dotcypress** [comment]
For sure, it's totally possible, just register handler for `chosen_inline_result` update:

```js
bot.on('chosen_inline_result', ctx => ...)
```

**Comment by ouya99** [comment]
ctx.chosenInlineResult.result_id is a string of 5 chars. How do I get the input_message_content from this id? 

I need to get the acual data set that was selected
