### ISSUE TITLE
answerCbQuery() with Error: 400

### ISSUE THREAD

**Issue by TangMonk** [telegraf/telegraf#1719]
I have a telegram bot for resposing users intract with inline keyboard menu.

for example, there is some button in inline keyboard menu:

        MENU
    ---------------
    Get BTC price
    ---------------
    Get APPL price

If user click each above menu, I will call `answerCbQuery()` for stop button spin pending, And bot will response the latest price to user. It is ok for nothing happened.

But sometimes, My vps server is shutdown and restart, Or I stop the bot for maintain. after that, I will restart my bot, At this time my bot will keep going crash will error:

    Error: 400: Bad Request: query is too old and response timeout expired or query ID is invalid

this seems because users still keep click those buttons when bot down, And bot call `answerCbQuery()` after restart too late

It is going a crash circle.

I cannot try-catch `answerCbQuery()`, and `telegraf.catch` also not work

**Comment by MKRhere** [comment]
For `bot.catch` to work, all promises must be awaited. This means `await ctx.answerCbQuery()` and so on. The same is true for try-catching async function calls.

```TS
// await may only be used inside async functions
bot.action("thing", async ctx => {
	try {
		// the await is important!
		await ctx.answerCbQuery();
	} catch {
		/* ... */
	}
});
```

Read more: [Async function on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

**Comment by TangMonk** [comment]
Thanks, I got
