### ISSUE TITLE
keyboard button with custom text as label

### ISSUE THREAD

**Issue by yass-dev** [telegraf/telegraf#172]
I do not know if I am wrong but I am not able to create keyboard button(not inlineKeyboard but keyboard itself) with my custom text as the label for the button. as I figured it out Markup.keyboard() takes an array which each item in that array is a button which the text is both the name(label) of button and the name of action in case user clicked on it. My question is how can I have a keyboard button which the label is not the same as the name of action it triggered? for example I need t keyboard button with name(label) of 'Click me first' which clicking on it trigger action named 'test1'. how?
Thanks!

**Comment by dotcypress** [comment]
Hey @yass-dev 

Basically, keyboard it's just predefined text message. Telegram API have only one place, where you can pass custom parameters: [Deep Linking](https://core.telegram.org/bots#deep-linking)
