### ISSUE TITLE
chosen_inline_result does not work with messages sent by a group

### ISSUE THREAD

**Issue by Eld3rly** [telegraf/telegraf#1728]
## Context

* Telegraf.js Version: 4.10.0
* Node.js Version: 19.0.0
* Operating System: Windows 11 and Ubuntu 20.04

## Minimal Example Code Reproducing the Issue

```ts
bot.on("chosen_inline_result", async (ctx) => {
    console.log(ctx.chosenInlineResult);
});
```

## Expected Behavior

When sending a message on behalf of a group in chats displays information about the selected inline

## Current Behavior

No information is displayed, even the option to console.log all incoming updateType does not work
```ts
bot.use(async (ctx, next) => {
    console.log(ctx.updateType); // Doesn't output chosen_inline_result, when inline querying on behalf of a group
    next();
});
```
## Error Message and Logs (`export DEBUG='telegraf:*'`)
just nothing

**Comment by MKRhere** [comment]
I assume you're looking for a message sent by a group using an inline bot other than yours? This might just be that bots cannot see messages sent by other bots.

**Comment by Eld3rly** [comment]
> I assume you're looking for a message sent by a group using an inline bot other than yours? This might just be that bots cannot see messages sent by other bots.

Telegram Premium users can send messages in public chats on behalf of their groups using an inline query, but the inline query result does not come
![Image](https://user-images.githubusercontent.com/92121413/201499989-6acd1582-3fb3-4ff8-bac0-b563acac520f.png)

**Comment by MKRhere** [comment]
[Example for inline bot](https://github.com/feathers-studio/telegraf-docs/blob/4feffcd893a86ed1fcc761279d17328beb4a2f21/examples/inline-bot.ts).

It doesn't matter if you're trying to use inline bot as a group. First you have to listen to `inline_query` and send results. When the user selects one of the results, you get `chosen_inline_request`.
