### ISSUE TITLE
Custom emoji does not appear in messages from bot

### ISSUE THREAD

**Issue by DesTincT** [telegraf/telegraf#1739]
I added my own custom emojis with premium account, but my bot can't send them. If I send them directly from the text field (by user) - all is fine. Read all the new Telegram API, I think problem there, so maybe somebody knows... 🙏

## Context
* Telegraf.js Version: 4.10.0
* Node.js Version: 14.18.1
* Operating System: macOS Ventura 13.0.1

## Minimal Example Code Reproducing the Issue
```ts
await ctx.reply('❤️', {
  entities: [{
    type: 'custom_emoji', // correct type from TELEGRAM API DOCS
    offset: 0,
    length: 2,
    custom_emoji_id: '5458672011788167217' // correct ID
  }]
});
```

also tried different variants, like
```ts
ctx.telegram.sendMessage(chatID, ctx.message.message_id, '❤️', {
      entities: [{
        type: 'custom_emoji',
        offset: 0,
        length: 2,
        custom_emoji_id: '5458672011788167217'
      }]
    });
```
## To reproduce
1. Create your own custom emoji
2. Get the custom_emoji_id like `const stickersSet = await ctx.getStickerSet('YOURPACKNAME');` or you can use mine
```ts
{
     width: 100,
     height: 100,
     emoji: '❤️',
     set_name: 'GoldenResource',
     is_animated: false,
     is_video: false,
     type: 'custom_emoji',
     custom_emoji_id: '5458672011788167217',
     thumb: {
       file_id: 'AAMCAgADFQABY3fhHGslkB9FyOdAa-hUuYdwtpsAAjEoAAJGGcFLE7GHE0vnH3EBAAdtAAMrBA',
       file_unique_id: 'AQADMSgAAkYZwUty',
       file_size: 2958,
       width: 100,
       height: 100
     },
     file_id: 'CAACAgIAAxUAAWN34RxrJZAfRcjnQGvoVLmHcLabAAIxKAACRhnBSxOxhxNL5x9xKwQ',
     file_unique_id: 'AgADMSgAAkYZwUs',
     file_size: 2976
}
```

4. Try to send them via bot

## Expected Behavior
Custom emoji sent by bot is visible for the user in telegram message

## Current Behavior
Bot sends standart emoji

## Error Message and Logs (`export DEBUG='telegraf:*'`)

<img width="1140" alt="Telegram 2022-11-18 23-43-42" src="https://user-images.githubusercontent.com/1612160/202800674-13c6ca54-8642-43e9-aa7c-123ef4249470.png">

**Comment by MKRhere** [comment]
Bots cannot use custom emoji because bots cannot be premium users, yet. Your `custom_emoji` entity is being ignored.

If Telegram allows bots to be become premium in the future, then your code will likely work.

**Comment by DesTincT** [comment]
> Bots cannot use custom emoji because bots cannot be premium users, yet. Your `custom_emoji` entity is being ignored.
> 
> If Telegram allows bots to be become premium in the future, then your code will likely work.

Ok, why Telegram API has such an option, so?

**Comment by MKRhere** [comment]
It's because the same `MessageEntity` interface is used in `Message` received by the bot when a premium member sends a `custom_emoji`.
