### ISSUE TITLE
Wizard Cannot read properties of undefined (reading 'enter')

### ISSUE THREAD

**Issue by KrishEnacton** [telegraf/telegraf#1743]
* Telegraf.js Version: 4.11.2
* Node.js Version: 18.9.0
* Operating System: Mac os

## Minimal Example Code Reproducing the Issue

```ts
const superWizard = new Scenes.WizardScene(
  "wizard",
  (ctx) => {
    console.log(ctx);
    ctx.reply("What's your name?");
    ctx.wizard.state.data = {};
    return ctx.wizard.next();
  },
  (ctx) => {
    ctx.wizard.state.data.name = ctx.message.text;
    ctx.reply("Enter your phone number");
    return ctx.wizard.next();
  },
  (ctx) => {
    ctx.wizard.state.data.phone = ctx.message.text;
    ctx.reply(`Your name is ${ctx.wizard.state.data.name}`);
    ctx.reply(`Your phone is ${ctx.wizard.state.data.phone}`);
    return ctx.scene.leave();
  }
);

const stage = new Scenes.Stage([superWizard]);

bot.use(session());
bot.use(stage.middleware());
stage.register(superWizard);
bot.command("post", Scenes.Stage.enter("wizard"));
```

Above code gives an error like : 

return (ctx) => ctx.scene.enter(...args);
                                  ^

TypeError: Cannot read properties of undefined (reading 'enter');

**Comment by MKRhere** [comment]
Telegraf 4.11.2, Node 18.12.0, your code unmodified, just works:

![image](https://user-images.githubusercontent.com/19621208/203602197-ea043268-ef68-4e5a-831e-dc38ceb2673a.png)

**Comment by KrishEnacton** [comment]
@MKRhere 
I appreciate you taking the time to respond
Would you mind sharing your working code so I can figure out where I am going wrong?

**Comment by KrishEnacton** [comment]
@MKRhere 
The problem has been resolved
Another issue I encountered was not being able to open the wizard in a conditional statement.

```js
bot.hears("hello", ctx=>{
     if(true) // some condition
    {
         Scenes.Stage.enter("payout_number_wizard");
    }
});
```

**Comment by MKRhere** [comment]
Use
```TS
ctx.scene.enter("payout_number_wizard");
```
