### ISSUE TITLE
How to do this using telegraf

### ISSUE THREAD

**Issue by KrishEnacton** [telegraf/telegraf#1750]
Hey I want to show bot information like below screen shot

SS: [https://i.imgur.com/tKURytv.png](url)

**Comment by MKRhere** [comment]
This is not possible to do via the API. Use [@BotFather](https://t.me/BotFather) to edit your bot (`/mybots` -> Choose bot -> Edit bot -> Edit description):

![image](https://user-images.githubusercontent.com/19621208/203942252-f41422c0-38c5-45e7-ac6b-fc71e51bc2d7.png)
