### ISSUE TITLE
Error with types - version 4.11.0 

### ISSUE THREAD

**Issue by luisfcofv** [telegraf/telegraf#1751]
Error with types using version 4.11.0 or later.

I'm getting this error when I compile Typescript:

```bash
node_modules/typegram/index.d.ts:10:1 - error TS2308: Module "./default" has already exported a member named 'Ret'. Consider explicitly re-exporting to resolve the ambiguity.

10 export * from "./proxied";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/typegram/index.d.ts:10
```

* Telegraf.js Version: 4.11.0 
* Node.js Version: 16
* Operating System:  MacOS

### Note:
The types work when downgrading to version 4.10.0

**Comment by MKRhere** [comment]
This is a bug with the upstream types library - https://github.com/KnorpelSenf/typegram
Consider opening an issue there, although the author is aware of the issue.

You can silence the error with the officially recommended TS setting, `"skipLibCheck": true` under compilerOptions in tsconfig.json. This will also slightly improve your tsc build speed by skipping checking libs for correctness, and only checking your code.

**Comment by MKRhere** [comment]
Fixed upstream.
