### ISSUE TITLE
Check admin permissions for bot

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#176]
Hello there,

Is there a way to check which of which administrative permission a bot owns? If not possible, then would it be possible to check if a bot is an admin?

Cheers,
Ivan

**Comment by dotcypress** [comment]
Hey Ivan,

Just call [`telegram.getChatMember`]() method with chat id  and bot id 😉 

We have related example [here](https://github.com/bananiumbot/bot/blob/master/middlewares/only-admin.js).
