### ISSUE TITLE
More Function Descriptions

### ISSUE THREAD

**Issue by manasseh-fikadu** [telegraf/telegraf#1767]
**Describe the solution you'd like**
Please write proper docstrings for the methods that exist in this library.\
Like return types, input parameters and also usage scenarios.

**Comment by MKRhere** [comment]
Return types and input params are automatically documented by TypeScript. Your editor should already understand them. We could add usage examples; PRs welcome!

Meanwhile, better docs in general is a goal we're slowly working on, so closing this issue for housekeeping.
