### ISSUE TITLE
error TS2322: Type 'FmtString' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by NonameASecret** [telegraf/telegraf#1768]
## Context

* Telegraf.js Version:"^4.11.2"
* Node.js Version: 18.12.1
* Operating System: windows 11
* TS version : "^4.9.3"

## Minimal Example Code Reproducing the Issue

```
import { bold } from "telegraf/format"

await ctx.editMessageMedia(
                    {
                        type:"photo",
                        media:'fileid',
                        caption:bold('Bold text here')
                    }
)
```

## tsconfig.json file below

```
{
    "compilerOptions": {
        "target": "es2018",
        "module": "commonjs",
        "outDir": "dist",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "strict": true,
        "lib": [
            "ES2020.Promise"
          ],
        "skipLibCheck" : true
    },
    "include": ["app"],
    "exclude": ["node_modules", "dist"]
}
```
### UPDATE

`Fmtstring` doesn't support for the `InlineQueryResult[]` 🤔

**Refferences**

[https://t.me/TelegrafJSChat/94473](https://t.me/TelegrafJSChat/94473)

**Comment by sinapirani** [comment]
you forget use .text property. you should add this property to your code:
`  await ctx.editMessageMedia(
    {
        type:"photo",
        media:'fileid',
        caption:bold('Bold text here').text
    }`

**Comment by Creatoon** [comment]
@NonameASecret The line you wrote caption : bold(....) 

The bold function here returns an object of type FmtString, check below. 

```ts
FmtString {
  text: string
  entities?: MessageEntity[]
  parse_mode?: undefined
}
```
You can't assign this object to a caption, which only support string type

So simply use  .text property as @sinapirani suggested like this 

```
caption : bold('whatever').text
```

**Comment by MKRhere** [comment]
FmtString is a feature of Telegraf that provides a way to do formatting without HTML/Markdown, and doesn't need escaping. It works everywhere that text/caption is accepted, except in this case. This is indeed a bug. Will publish a fix soon.

See: [fmt helpers in the docs](https://github.com/feathers-studio/telegraf-docs/blob/4feffcd893a86ed1fcc761279d17328beb4a2f21/guide/%3F%3F%3F-formatting.md#fmt)

Using only `.text` would nullify the purpose of using fmt helpers. You'd also have to pass the `entities` array to `caption_entities` (in this case).
