### ISSUE TITLE
pass an array as options

### ISSUE THREAD

**Issue by Pranav108** [telegraf/telegraf#1769]
**Is your feature request related to a problem? Please describe.**
I am trying to pass an array of string as  `Trigger Type` (Params Type) for `bot.action` but I didn't get any response .

**Describe the solution you'd like**
What can be done to make my code in Screenshot run?

I want this 
```
bot.action( ["360p", "720p", "mp3"], (ctx) => {
  const chatId = ctx.chat.id;
  console.log("ctx in formatOptions:", ctx);
  const format = ctx.match;
  console.log("recieved Format:", format);
  videoChunkList.forEach((chunk) => {
    if (format === "mp3" && chunk.qualityLabel === null) {
      bot.telegram.sendMessage(chatId, chunk.url);
      formatOptions = [];
      videoChunkList = [];
    } else if (chunk.qualityLabel === format) {
      bot.telegram.sendMessage(chatId, chunk.url);
      formatOptions = [];
      videoChunkList = [];
    }
  });
});
``` 

To be line this : 
![image](https://user-images.githubusercontent.com/56934594/210438642-bdaefdd4-f373-41c2-b349-6470f048f348.png)
But the code in Screenshot is not working , there is no response.

What can be done to make my code in Screenshot run?

**Comment by Viiprogrammer** [comment]
Difference between code and screenshot only one - trigger moved to external var, and it should work

Please describe in more detail what is required.

Method `.action` can be unreachable if any upstream `.on('callback_query')` middleware does not call `next` function

**Comment by Pranav108** [comment]
> Difference between code and screenshot only one - trigger moved to external var, and it should work
> 
> Please describe in more detail what is required.

The code written section work perfectly but I the code in screenshot is not working, I want screenshot code to work.

**Comment by Viiprogrammer** [comment]
> > Difference between code and screenshot only one - trigger moved to external var, and it should work
> > Please describe in more detail what is required.
> 
> The code written section work perfectly but I the code in screenshot is not working, I want screenshot code to work.

`var formatOptions = ["360p", "720p", "mp3"]` - static and does not change on runtime after start?

**Comment by Pranav108** [comment]
Actually in code I need to change it on various situation, even inside the `action` method block I'm altering it. Will it work then?

**Comment by Viiprogrammer** [comment]
> Actually in code I need to change it on various situation, even inside the `action` method block I'm altering it. Will it work then?

`.action` allows use 3 types of triggers - `function`, `regexp`, `string` or any of this in array

You can match stings of `callback_query` dynamic by **[regexp](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp)**


```js
bot.action(/^format:([A-z0-9]+)$/, (ctx) => { // Changed line
  const chatId = ctx.chat.id;
  console.log("ctx in formatOptions:", ctx);
  const format = ctx.match[1]; // Changed line
  console.log("recieved Format:", format);
  videoChunkList.forEach((chunk) => {
    if (format === "mp3" && chunk.qualityLabel === null) {
      bot.telegram.sendMessage(chatId, chunk.url);
      formatOptions = [];
      videoChunkList = [];
    } else if (chunk.qualityLabel === format) {
      bot.telegram.sendMessage(chatId, chunk.url);
      formatOptions = [];
      videoChunkList = [];
    }
  });
});
```

for this example, **you should add `format:` prefix for buttons for matching**, matched value accessible from `ctx.match[1]`

| Button data      | `ctx.match[1]` |
| ----------- | ----------- |
| `format:mp3`      | `mp3`       |
| `format:720p`   | `720p`        |
| `format:360p`   | `360p`        |
| `format:acb`   | `acb`        |
| `format:a2cb2`   | `a2cb2`        |

**Comment by Pranav108** [comment]
thanks @Viiprogrammer , I tried the way you suggested , It works 👍
