### ISSUE TITLE
Missing `message_thread_id` for `forwardMessage` in Context

### ISSUE THREAD

**Issue by Viiprogrammer** [telegraf/telegraf#1772]
Missing `message_thread_id` for `forwardMessage` in Context after 1b73d335f8be09ccd7cc01783144df861aa141cd

https://github.com/telegraf/telegraf/blob/1b73d335f8be09ccd7cc01783144df861aa141cd/src/context.ts#L1377

Maybe need to add with future Bots API 6.4 
![изображение](https://user-images.githubusercontent.com/17622604/210918899-641fc789-10a0-40fc-9a97-21c3412c7e22.png)

**Comment by MKRhere** [comment]
This already works:

```TS
ctx.forwardMessage(chatId, { message_thread_id });
```
