### ISSUE TITLE
For Loop inlinekeyboard buttons

### ISSUE THREAD

**Issue by aminjoharinia** [telegraf/telegraf#178]
Hi there
i just want to read my data in an Object and print multiply buttons in a row 
how could i do that?
an similar example :
```javascript
var obj={"coca":"2$" , "7up":"3$" , "fanta":"4$"} 
for (var key in obj) {
      if (obj.hasOwnProperty(key)) {
          ctx.reply('price list', Extra.HTML().markup((m) =>
            m.inlineKeyboard([
              [m.callbackButton(`${key} : `, ` price : ${obj[key]}`)]
            ]))))

``` 
but The problem is i do not want to print "price list" every time
i just want to print it 1 time on top
and i can not use for loop inside "ctx.reply"

could any one help me?

**Comment by paOol** [comment]
```
await ctx.reply('price list\n');

----- your original code
ctx.reply( '&nsbp;' // or some invisible character, Extra.HTML()... blah blah  blah)
```

**Comment by aminjoharinia** [comment]
@paOol  unfortunately it does not work , it will print invisible characters
i tested many invisible characters but it does not work

**Comment by dotcypress** [comment]
@aminjoharinia try following:

```js
const obj={"coca":"2$" , "7up":"3$" , "fanta":"4$"} 
const buttons = Object.keys(obj).map(key => Markup.callbackButton(key, `price: ${obj[key]}`))
ctx.reply('price list', Extra.HTML().markup((m) => m.inlineKeyboard(buttons))
```

**Comment by aminjoharinia** [comment]
@dotcypress 
Thank You So much , Works Great 👍 
Exactly What I Want
