### ISSUE TITLE
Audio Speed missing

### ISSUE THREAD

**Issue by danielehrhardt** [telegraf/telegraf#1784]
**Is your feature request related to a problem? Please describe.**
When i reply a audio then i am not able to adjust the speed and see the audio wave. Is there a option to add this feature. Something like replyVoicemessage insead of replyAudio

**Describe the solution you'd like**
reply a .mp3 file and get the same like when someone is sending a voice message.

![image](https://user-images.githubusercontent.com/19570043/213930232-ee8f6d02-c076-4ec4-a038-dc90da80a59f.png)
![image](https://user-images.githubusercontent.com/19570043/213930254-33b6a633-27f4-467f-a58b-138c9037af81.png)

**Comment by MKRhere** [comment]
There's `replyWithAudio` and `replyWithVoice`. If you've tried the first one, try the other.

**Comment by danielehrhardt** [comment]
Awesome. Works!
