### ISSUE TITLE
ctx.deleteMessage() to delete previous message

### ISSUE THREAD

**Issue by suntong** [telegraf/telegraf#1789]
> Just use method: 
> `await ctx.deleteMessage();`
>  if previous message exist it will be deleted

_Originally posted by @git-antonyuk in https://github.com/telegraf/telegraf/issues/495#issuecomment-632894503_

and I saw such usage in https://github.com/telegraf/telegraf/issues/495#issuecomment-417852670 as well.

But, it is still true?

**Comment by MKRhere** [comment]
`ctx.deleteMessage()` will delete the current incoming message. Depending on the filter, this may be a user message, a chat join message, or the bot's own message if it's a callback query (the message that contained the callback button).

**Comment by suntong** [comment]
Ah, ***incoming***, not _previous_ message. 

Thanks
