### ISSUE TITLE
Get only first message

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#179]
Hi everyone, I have a problem with getting messages from a user. For example bot says: Enter your ID, and user should send a text to the bot after that bot should stop waiting a message and answer smth. But in my occasion bot gets all messages

**Comment by aminjoharinia** [comment]
Hi
Use [telegraf-flow](https://github.com/telegraf/telegraf-flow)
It Has a Very Good Examples

**Comment by JRakhimov** [comment]
Yes, it was exactly what I needed. Thank you))
