### ISSUE TITLE
scene.enter occurs twice if messages come to fast

### ISSUE THREAD

**Issue by mvarakin** [telegraf/telegraf#1799]
### Discussed in https://github.com/telegraf/telegraf/discussions/1798

<div type='discussions-op-text'>

<sup>Originally posted by **mvarakin** February 13, 2023</sup>
Hi,

I have a listener

bot.on(message('text'), async ctx => await ctx.scene.enter('my_scene')) 

in my code.

Inside the scene among other scene stuff (commands etc.) I catch all text messages and simply ignore them.

It works well if I chat with the bot.

But I noticed that if I forward two, three... messages to a bot at once from another chat, bot enters my_scene on every message!

But the bot is supposed to skip second, third... message as the bot should be already inside the scene after the first message coming.

Looks like it's a race condition. Entering the scene is still in progress but a new message comes and global listener (the above code) runs leading to call scene.enter again.</div>

**Comment by MKRhere** [comment]
Related to #1372, fixed by #1713. Will release later today!

**Comment by MKRhere** [comment]
This is fixed in https://github.com/telegraf/telegraf/releases/tag/v4.12.0
