### ISSUE TITLE
How to set polling rate?

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#180]
Hello!

I want to increase my polling rate for the bot, is there any way to do this?

Hope to hear from you soon!

Best Regards,

Josh

**Comment by dotcypress** [comment]
Hey @joshuaquek !

What do you mean by `polling rate`?

**Comment by joshuaquek** [comment]
Oh it means that the delay that the polls at. Currently it's 1000ms right?

**Comment by dotcypress** [comment]
Telegraf use [long polling](https://en.wikipedia.org/wiki/Push_technology#Long_polling) with 
 30 seconds default timeout.

**Comment by joshuaquek** [comment]
Oh I see.... so that means that there is no need for a polling interval? Like in https://github.com/mullwar/telebot ? They have an option to set the polling interval. What is the polling interval between every long poll for telegraf?

**Comment by dotcypress** [comment]
Correct, you don't need to config a polling interval.
`What is the polling interval between every long poll for telegraf` - with long polling we just connect to Telegram servers and waiting for content, thats all.

**Comment by joshuaquek** [comment]
Ah I see! So it's immediate? No delay between each long poll?

**Comment by dotcypress** [comment]
Correct

**Comment by joshuaquek** [comment]
Alright, thank you!
