### ISSUE TITLE
Feature Request: Continuously Sending Chat Action Requests

### ISSUE THREAD

**Issue by orimiles5** [telegraf/telegraf#1801]
# Description
I'm frustrated when the sendChatAction method stops after 5-6 seconds. This can be problematic when I want to run a function that takes a longer time to process, as the user may assume that the bot has stopped responding. Therefore, I'd like to request a new feature that allows for the continuous sending of chat action requests for a specified amount of time.
I'd like to request this feature, and it would be an honor to contribute and help implement it. I have experience working with Typescript and would be happy to collaborate with the development team to ensure that this feature is implemented in a way that meets their standards.

# Solution
My proposed solution is to send the sendChatAction request repeatedly, given a specified amount of time. This would allow the bot to give the user a sense of its responsiveness, and prevent the user from sending multiple requests while the bot is still processing a previous request.

# Example
For example, the "typing" chat action could be sent continuously for 20 seconds, with a delay of 1-2 seconds between requests. This would ensure that the user is aware that the bot is still processing their request, and give them a better experience overall.

# Considerations
I understand that this feature may impact the performance of the bot or the Telegram servers, and I'd be happy to discuss any potential trade-offs or drawbacks with the development team.

https://user-images.githubusercontent.com/97595296/219793214-d137b6ab-e9d8-4479-abea-4b03d23744b0.mp4

**Comment by wojpawlik** [comment]
https://github.com/telegraf/telegraf/blob/v5/src/transformers/auto_retry.ts

**Comment by MKRhere** [comment]
@wojpawlik This is a different thing; they don't want to retry on failure. They want to repeat `sendChatAction` as long as they're processing the request.

**Comment by wojpawlik** [comment]
I'd implement it as a [transformer](https://github.com/telegraf/telegraf/tree/v5/src%2Ftransformers) to avoid extending the API

**Comment by orimiles5** [comment]
Thank you for your feedback. 

If I understand the concept of transformer correctly, in order to implement it as one, the `sendChatAction` should be passed along with the main action that we want to wait for. This would require both actions to have knowledge of each other so that the `sendChatAction` can stop when the main action is fulfilled. However, implementing this feature would require significant changes to the API.

As an alternative solution, a more scalable option would be to pass a `time` argument in the `sendChatAction` extra parameters. This approach would allow the `sendChatAction` to stop after a specified amount of time, which is another way of solving this issue.

Please let me know your thoughts on these proposed solutions.

**Comment by MKRhere** [comment]
@wojpawlik

Or are you thinking of some magic with transformers that is indeed able to do this by capturing a `sendChatAction` API, then waits for any other API call in the same context? I'm not sure how to store the state in that case, but this would be possible:

```TS
bot.use(keepChatAction({ every: 6000 })); /* defaults to every 5000 milliseconds */

bot.command("video", async ctx => {
	await ctx.sendChatAction("upload_video");
	const video = somehowGetReadableStream();
	await ctx.sendVideo(Input.fromReadableStream(video));
});
```

The drawback is, of course, `sendChatAction` will stop the moment you called `ctx.sendVideo`, even though the video is still streaming to Telegram. The alternate solution I thought of would be a util that does this:

```TS
bot.command("video", async ctx => {
	await keepChatAction(ctx, "upload_video", async () => {
		const video = somehowGetReadableStream();
		await ctx.sendVideo(Input.fromReadableStream(video));
	}, { every: 6000 });
});
```

It is more explicit, but with less footguns—imo. @orimiles5 Do you have an opinion?

**Comment by orimiles5** [comment]
The alternative solution you suggested looks great. I’ll work on it and keep you updated.

**Comment by wojpawlik** [comment]
> The drawback is, of course, `sendChatAction` will stop the moment you called `ctx.sendVideo`

It could easily stop only after the request completes.

**Comment by orimiles5** [comment]
@wojpawlik 
Could you provide some guidance on how you would envision the implementation?

**Comment by wojpawlik** [comment]
No, I realized managing state in a transformer would be way too brittle...

Perhaps Telegraf support could be added to https://github.com/grammyjs/auto-chat-action ?

**Comment by wojpawlik** [comment]
On closer look, managing state in a transformer would be way too brittle...

I'd add this to Telegraf:

```ts
await ctx.persistentChatAction("typing", async () => { ... })
```

**Comment by wojpawlik** [comment]
Problem: when polling, one chat can launch multiple long processes, flooding the API with `sendChatAction` calls.

Defaulting grammY to sequential pollin was the right move all along @KnorpelSenf

**Comment by wojpawlik** [comment]
Or `ctx.telegram.use(persistentAction("typing"))`

**Comment by orimiles5** [comment]
I carefully reviewed your notes and implemented the feature. It would be an honor to have your review of my pull request. Thank you for your guidance and support.
@MKRhere @wojpawlik
