### ISSUE TITLE
Is there possibly to provide a proxy? appreciation!

### ISSUE THREAD

**Issue by ethever** [telegraf/telegraf#1807]
I saw using fetch here, but i need to proxy my local network to send data to telegram server, how can i do this? could you give me a help ? thx in advance!

https://github.com/telegraf/telegraf/blob/14d5c3fa9072bdccb796843444f75c7f8563fc51/src/core/network/client.ts#L364

**Comment by kashyapndps00** [comment]
Easy Just Pass `PROXY_URI` in `telegram.apiRoot`
```js
const bot = new Telegraf(bot_token,{
    telegram : {
       apiRoot : PROXY_URI
   }
);
```
