### ISSUE TITLE
grammY offers the possibility to have multiple sessions, can Telegraf have that too?

### ISSUE THREAD

**Issue by Evertt** [telegraf/telegraf#1824]
**Is your feature request related to a problem? Please describe.**
I want to store all the messages from all the chats that my bot is a part of. However, since currently my bot stores sessions per user, that means that in a group chat, it will be storing the messages of that group chat in a fragmented way, only grouped per user.

**Describe the solution you'd like**
I'd like to have multiple sessions, based on multiple session keys.
One session called `chat` which is based on `ctx.chat.id` as the session key, and it would contain a property called `messages`, storing all the messages in a chat.
And then I'd like to have a session called `user` which has `ctx.from.id` as the session key, and it would contain properties like `settings` related to the settings that the user has set.

**Describe alternatives you've considered**
I didn't think of any alternatives tbh.

**Comment by MKRhere** [comment]
Glad to see this issue! I've been thinking a lot about, and I believe we can have a simpler and more elegant solution to this problem. Look forward to it in the next release!

**Comment by Evertt** [comment]
I can't wait! (I almost mean that literally 😅)

### edit

Is there maybe actually already a kind of work-around to make it work in the current version already?

**Comment by MKRhere** [comment]
For anyone else reading this, as of d12da76 (pre-release `v4.12.3-canary.1`) this is available via

```TS
session({ property: "customSession" })
```

**Comment by Evertt** [comment]
Be aware that `from.id` and `chat.id` are currently the same when it's a private chat. So if you want to distinguish them as session keys, you probably want to prefix them like `chat.${chat.id}` etc.

**Comment by Magirater** [comment]
Can we somehow share session date between scenes? For example:
```
Scene 1: prev_scene = ctx.scene.id;
Scene 2: ctx.scene.enter(prev_scene)
```
