### ISSUE TITLE
I cant run my bot

### ISSUE THREAD

**Issue by kehiy** [telegraf/telegraf#1825]
I'm trying to start my telegram bot with telegraf but I get this error!

```reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://api.telegram.org/bot6014188971:[REDACTED]/getMe failed, reason: getaddrinfo ENOENT api.telegram.org
    at ClientRequest.<anonymous> (D:\projects\telegram-bots\YTDL-bot\node_modules\node-fetch\lib\index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ENOENT',
  code: 'ENOENT'
}```

**Comment by MKRhere** [comment]
This means your bot can't find Telegram's API server. Perhaps due to a network issue or your ISP is blocking Telegram.

If it's only a DNS level block, you'll be able to get around it by using another DNS provider like NextDNS, Cloudflare's 1.1.1.1, or Google's 8.8.8.8. If not, VPN is the only choice.

**Comment by kehiy** [comment]
I changed my DNS provider to Cloudflare but still get previous errors...

**Comment by MKRhere** [comment]
Try this in a command line: `ping api.telegram.org`. Post results.

**Comment by kehiy** [comment]
Ping request could not find host api.telegram.org. Please check the name and try again.

**Comment by MKRhere** [comment]
It's still blocked then. You'll probably need a VPN.

**Comment by kehiy** [comment]
I'm using a VPN now! (Dubai, Istanbul and syndrome).
that's doesn't work

**Comment by MKRhere** [comment]
No clue then, I'm not sure about the situation in any of those places.

Consider asking in the Telegram group (https://t.me/TelegrafJSChat) if anyone knows a solution.

**Comment by kehiy** [comment]
thank you...🛸

**Comment by mansoormaliyekkal** [comment]
I had faced same error.
I tried connecting another network, and it got resolved.

**Comment by NatiG100** [comment]
Is there any other way to fix this issue?

**Comment by diomedesK** [comment]
I would recommend you guys to run your bots through a local server using the [Telegram Bot API](https://github.com/tdlib/telegram-bot-api).

Just follow the guide provided in the page and then launch it, like:
``` bash
telegram-bot-api --api-id=$API_ID --api-hash=$API_HASH--local -v 4 -p 8888 
```

Then specify the local server when creating the bot:
``` typescript
bot = new Bot(process.env.BOT_TOKEN, {
	telegram: {
		apiRoot: "http://localhost:8888"
	}
})
```
