### ISSUE TITLE
Telegram group statistics

### ISSUE THREAD

**Issue by MukundDaolens** [telegraf/telegraf#1830]
Hi, in my understanding, the telegram api gives support of fetching the group stats. Is there a way in this package to fetch the group stats?

**Comment by hypernova7** [comment]
Nope, use MTProto (gramjs)

**Comment by MukundDaolens** [comment]
But it does not give detailed stats...Also no methods for stats are for bots

**Comment by MKRhere** [comment]
> Also no methods for stats are for bots

Telegraf is a Bot API framework. We only do bots. You should use gramjs/tgsnake/etc for MTProto methods with a user account.
