### ISSUE TITLE
RangeError: Maximum call stack size exceeded in Webhook file

### ISSUE THREAD

**Issue by iamnnort** [telegraf/telegraf#1832]
## Context

Unable to understand the reason of the thrown exception.

* Telegraf.js Version: 4.12.2
* Node.js Version: 16.17.1
* Operating System: ubuntu 18

## Expected Behavior

No unexpected exception or a proper call stack at least with ability to understand the real reason.

## Current Behavior

```
RangeError: Maximum call stack size exceeded
  Exception in PromiseRejectCallback:
  /app/node_modules/telegraf/lib/composer.js:485
  await handler(context, async (ctx = context) => {
  RangeError: Maximum call stack size exceeded
  at execute (/app/node_modules/telegraf/lib/composer.js:475:35)
  at /app/node_modules/telegraf/lib/composer.js:474:20
```

## Failure Information (for bugs)

The issue happens from time to time, so using the error message it's not possible to detect the real issue. (I don't have any recursions in the code)

**Comment by MKRhere** [comment]
This is not an error Telegraf can handle. Do you have nested listeners? Like:

```TypeScript
bot.on("message", ctx => {
	bot.on("message", ctx => {});
	// ^^ ❌ This is BAD! It will cause this listener to be added every time a message arrives, until you run out of memory or stack space
});
```

If this is not the case, will need to see some code.

**Comment by iamnnort** [comment]
Hi there, I finally figured out what is going wrong.

Example that throws the error.
```
const bot = new Telegraf(...)
const stage = new Scenes.Stage(...)

stage.on('message', handler); <----- throws RangeError

bot.use(stage.middleware());
```
Working example

```
const bot = new Telegraf(...)
const stage = new Scenes.Stage(...)

bot.on('message', handler); <----- works good

bot.use(stage.middleware());
```

P.S. The issue is in place only if I run multiple bots on the same ps.

**Comment by iamnnort** [comment]
> This is not an error Telegraf can handle. Do you have nested listeners? Like:
> 
> ```ts
> bot.on("message", ctx => {
> 	bot.on("message", ctx => {});
> 	// ^^ ❌ This is BAD! It will cause this listener to be added every time a message arrives, until you run out of memory or stack space
> });
> ```
> 
> If this is not the case, will need to see some code.

No, I don't

**Comment by MKRhere** [comment]
```TS
stage.on('message', handler); <----- throws RangeError
```

What's in `handler`?

**Comment by MKRhere** [comment]
Closing for housekeeping. Reopen if needed.
