### ISSUE TITLE
userRequest doesn't fit into inlineKeyboard

### ISSUE THREAD

**Issue by DasAnonas** [telegraf/telegraf#1834]
## Context

* Telegraf.js Version: 4.12.2
* Node.js Version: v16.14.0
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```ts
ctx.reply('This is a User Request button', Markup.inlineKeyboard([Markup.button.userRequest('some text', 1234)]));
```

## Expected Behavior

The user request button should be puttable inside the inline keyboard like generally any other buttons or as it's shown in the official Telegram example of this feature.

## Current Behavior

The userRequest button seems to be implemented only via HideableKBtn, not via HideableIKBtn thus making impossible to assign this button into the inlineKeyboard buttons array causing the further presented type error.

## Error Message and Logs

```
No overload matches this call.
  Overload 1 of 2, '(buttons: HideableIKBtn[][]): Markup<InlineKeyboardMarkup>', gave the following error.
    Type 'Hideable<RequestUserButton>' is missing the following properties from type 'HideableIKBtn[]': length, pop, push, concat, and 29 more.
  Overload 2 of 2, '(buttons: HideableIKBtn[], options?: Partial<KeyboardBuildingOptions<HideableIKBtn>> | undefined): Markup<InlineKeyboardMarkup>', gave the following error.
    Type 'Hideable<RequestUserButton>' is not assignable to type 'HideableIKBtn'.
      Type 'Hideable<RequestUserButton>' is not assignable to type 'WebAppButton & { hide?: boolean | undefined; }'.
        Property 'web_app' is missing in type 'Hideable<RequestUserButton>' but required in type 'WebAppButton'.ts(2769)
markup.d.ts(25, 5): 'web_app' is declared here.
```

**Comment by hypernova7** [comment]
request buttons cannot be used on inlineKeyboard
