### ISSUE TITLE
Telegram v6.6 & 6.7 ?

### ISSUE THREAD

**Issue by raskyer** [telegraf/telegraf#1835]
Hey,
Do you know if you want to support telegram 6.6 & 6.7 version ?
https://core.telegram.org/bots/api

**Comment by MKRhere** [comment]
Work in progress. Release will be soon.

**Comment by pewpewgogo** [comment]
Hi! Do you have any updates?

**Comment by ghost** [comment]
Any updates for this?

**Comment by IlyaDonskikh** [comment]
@MKRhere hey! Do you need any help to release the update?

**Comment by thearturca** [comment]
Telegram updated bot API to version 6.8
https://core.telegram.org/bots/api

**Comment by MKRhere** [comment]
6.8 support is in #1862. Adding reviews will help release sooner :) Closing this as done for now.
