### ISSUE TITLE
awaiting user input

### ISSUE THREAD

**Issue by npyramid** [telegraf/telegraf#184]
Hello. I want make a simple user form.
Its will be like this:

user type a command
then bot await text from current user, then process this text.

I hope for help. Thanks

**Comment by npyramid** [comment]
found flow module. sorry for this)

**Comment by ali-bagheri** [comment]
var gotoRegState = function(ctx)
    {
	ctx.scene.enter('registerForm');
    };
	
var registerForm_senc = new botScene('registerForm');
    registerForm_senc.enter(enterToRegState);
    registerForm_senc.leave(leaveFromRegState);
    registerForm_senc.on('message', onMessageRegState);

    var registerForm_stage = new botStage();
    registerForm_stage.register(registerForm_senc);


    venusBot.catch(errorHandle);
    venusBot.use(botSession());
    venusBot.use(registerForm_stage.middleware());
    venusBot.start(startBotHandle);
    venusBot.command('register', gotoRegState);
