### ISSUE TITLE
strange behaviour 

### ISSUE THREAD

**Issue by 3eshelon** [telegraf/telegraf#1845]
hello.
The problem is:
first time bot. hears I have right array in console. But in second time bot.hears I have first time array in console.
please help with this issue 

et price = new RegExp("/price");

bot.hears(price, (ctx) => {
  let arr = ctx.message.text.split("/");
  arr.splice(0, 2);
  ctx.reply(
    "Записать в базу?",
    Markup.inlineKeyboard([
      Markup.button.callback("Да", "btn_1"),
      Markup.button.callback("Нет", "btn_2"),
    ])
  );
  addActionBot2(arr);
});

function addActionBot2(arr) {
  bot.action("btn_1", async (ctx) => {
    console.log(arr);     
  }

**Comment by MKRhere** [comment]
You shouldn't mount listeners from inside listeners. Move them out and use other ways to communicate between handlers (session, global maps, etc. as situation demands).
