### ISSUE TITLE
Send location by callback_button

### ISSUE THREAD

**Issue by lamartire** [telegraf/telegraf#185]
Hello!
In official api docs keyboard button has `request_location` param. Is there something like this to get users location?
Thanks!

**Comment by dotcypress** [comment]
Hey.

Yep, check out examples for [`Markup.locationRequestButton`](https://github.com/telegraf/telegraf/blob/ee1b7cae46f04fb310d1535f4fa07db83d062419/examples/keyboard-bot.js#L35)

**Comment by lamartire** [comment]
@dotcypress hey, thanks! How about document markup features?

**Comment by aminjoharinia** [comment]
@dotcypress 
Hi
How is it possible with ```inlinekeyboard``` ?

**Comment by lamartire** [comment]
@aminjoharinia, I think it not possible because it provided by telegram api only in common type of keyboard.
Docs: [https://core.telegram.org/bots/api#keyboardbutton](https://core.telegram.org/bots/api#keyboardbutton)
