### ISSUE TITLE
Telegraf does a bad request when calling the API getMe

### ISSUE THREAD

**Issue by Evertt** [telegraf/telegraf#1851]
* Telegraf.js Version: telegraf@4.12.3-canary.1, because I needed the multi-session feature
* Node.js Version: I'm using Deno:
  * deno 1.34.0 (release, aarch64-apple-darwin)
  * v8 11.5.150.1
  * typescript 5.0.4
* Operating System: macOS Ventura

## Minimal Example Code Reproducing the Issue

```ts
import "https://deno.land/std@0.179.0/dotenv/load.ts"
import { Telegram } from "npm:telegraf@4.12.3-canary.1"
const { TELEGRAM_KEY } = Deno.env.toObject()
const telegram = new Telegram(TELEGRAM_KEY)
export const me = await telegram.getMe()
```

## Error Message and Logs (`export DEBUG='telegraf:*'`)

If you want the whole stack trace, here you have it:

```
error: Uncaught (in promise) FetchError: invalid json response body at https://api.telegram.org/bot[token redacted of course]/getMe reason: Unexpected token '<', "<html>
<h"... is not valid JSON
    at file:///Users/evert/Library/Caches/deno/npm/registry.npmjs.org/node-fetch/2.6.9/lib/index.js:274:32
    at Object.runMicrotasks (ext:core/01_core.js:836:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:51:14)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
    at eventLoopTick (ext:core/01_core.js:188:21)
    at async Telegram.callApi (file:///Users/evert/Library/Caches/deno/npm/registry.npmjs.org/telegraf/4.12.3-canary.1/lib/core/network/client.js:290:22)
    at async file:///Users/evert/Sites/chat-nvc-telegram-bot/src/me.ts:5:19
```

```
Please include any relevant log snippets or files here.
```

No, but I do have something curious. It does run correctly in my docker container that has Deno inside it. It just doesn't run on my local Deno. Which I still find strange, because again, it did work very recently...

**Comment by raskyer** [comment]
Seems not related to telegraf to be honest. Can you print the full response given by the api call ? (It's just a fetch so it should be easy).

Maybe a bad redirect mecanism from your local deno or something with your dns. Honestly, have no clue, but it seems your api get a full html page in response to something that should be json.
So, no implication from telegraf there (since no update on telegram side on the endpoint).

**Comment by MKRhere** [comment]
Closing as not reproduce-able and inactive. Feel free to reopen if you have more information.
