### ISSUE TITLE
Initialize only with App Id and App Hash

### ISSUE THREAD

**Issue by pedroota** [telegraf/telegraf#1853]
Hello everyone,

I hope you're doing well! I'm currently facing some challenges while trying to create a specific use case for a bot. The bot should be able to initialize with only the App Id and App Hash from a Telegram account. Once the code is initialized, it will prompt the user for their phone number and the code sent by Telegram. In some cases, it may also require the user's two-factor authentication password, if applicable.

I was wondering if there is a way to achieve this functionality. Any guidance or suggestions would be greatly appreciated.

Thank you all!

**Comment by hypernova7** [comment]
This library only use bot API not MTProto, please use gramjs o tgsnake instead
