### ISSUE TITLE
Can not listen to ``pre_checkout_query`` action from BaseScene or WizardScene

### ISSUE THREAD

**Issue by lukahukur** [telegraf/telegraf#1863]
I found out that I can not add listener to pre_checkout_query action while being inside of scene.

I do use stage.middleware() and session()

```
export const StartScene = new Scenes.BaseScene("Start");

StartScene.on("pre_checkout_query", (ctx) => {
ctx.answerPreCheckoutQuery(true);
});
```

**Comment by lukahukur** [comment]
But in case of bot everything works
```
bot.on("pre_checkout_query", (ctx) => {
  ctx.answerPreCheckoutQuery(true);
});
```

**Comment by hypernova7** [comment]
> But in case of bot everything works
> 
> ```
> bot.on("pre_checkout_query", (ctx) => {
>   ctx.answerPreCheckoutQuery(true);
> });
> ```

The `pre_checkout_query` event should always be listened for globally, as there is no point in doing it individually

**Comment by lukahukur** [comment]
Thank you @hypernova7! could you tell me how to pass payload through session context to ``successful_payment`` action listener?

**Comment by lukahukur** [comment]
Thank U!

**Comment by MKRhere** [comment]
For additional information, checkout is not related to a chat; it is always related to an individual user. By default, scenes are entered by updates that have a `update.chat.id` and `update.from.id`, and `pre_checkout_query` only has `update.from.id`.
