### ISSUE TITLE
How is the right way to set removeKeyboard to true?

### ISSUE THREAD

**Issue by lucasmdesousa** [telegraf/telegraf#187]
How is the right way to set removeKeyboard to true? 
Here is just setting this option on reply_markup but has no effect. 
Can somebody help me?

**Comment by dotcypress** [comment]
Hey @lucasmdesousa 

There are many ways to accomplish that:

```js
bot.command('remove', (ctx) => {
  return ctx.reply('No keyboard', Extra.markup(Markup.hideKeyboard()))
})
```
or

```js
bot.command('remove', (ctx) => {
  return ctx.reply('No keyboard', Extra.markup(m =>m.hideKeyboard()))
})
```
or even

```js
bot.command('remove', (ctx) => {
  return ctx.reply('No keyboard', Markup.hideKeyboard().extra())
})
```

**Comment by dalisoft** [comment]
@dotcypress Error throwns when calling `Markup.hideKeyboard()`
```bash
TypeError: Markup.hideKeyboard is not a function
```

**Comment by dotcypress** [comment]
@dalisoft use [`Markup.removeKeyboard `](https://github.com/telegraf/telegraf/blob/develop/markup.js#L7) instead.

**Comment by dalisoft** [comment]
@dotcypress Yes, thanks. I see

**Comment by yonas-g** [comment]
**2020 Update**

```javascript
ctx.reply('No keyboard', Markup.removeKeyboard())
```
