### ISSUE TITLE
ctx.payload is empty when the string length is >64 characters 

### ISSUE THREAD

**Issue by ghost** [telegraf/telegraf#1882]
## Context

* Telegraf.js Version: 4.13.1
* Node.js Version: v16.19.1
* Operating System: Ubuntu 20.04

## Minimal Example Code Reproducing the Issue

```ts
bot.start(async (ctx) => {
  console.log(ctx.payload, ctx.startPayload);
});
```

Try to add a bot with a value for the `start` parameter that's longer than 64 characters. Like this: `https://t.me/botname?start=<65 character string>`

## Expected Behavior

The field(s) contain values and are not empty string.

## Current Behavior

The field(s) are empty strings.

Quoting Bot API 6.8 changes:
> Increased to 512 characters the maximum length of the startapp parameter in direct Web App links.

**Comment by MKRhere** [comment]
`?start`: link to bot start, [limited to 64 characters](https://core.telegram.org/api/links#bot-links).
`?startapp`: direct Web App link, limited to 512 characters.

They are different deep links.
