### ISSUE TITLE
Message ordering

### ISSUE THREAD

**Issue by GloriousBreenie** [telegraf/telegraf#1888]
Hello!

I've faced problems with sending messages in correct order. Is there a way to make it work with telegraf?  We can find some thoughts about it there https://github.com/yagop/node-telegram-bot-api/issues/192. But I think we can find a better way.

Cheers

**Comment by MKRhere** [comment]
The linked issue is ancient. We have async await today.

```TS
bot.on("message", async ctx => {
  await ctx.sendMessage("1");
  await ctx.sendMessage("2");
  await ctx.sendMessage("3");
  await ctx.sendMessage("4");
  await ctx.sendMessage("5");
});
```
