### ISSUE TITLE
No live locations

### ISSUE THREAD

**Issue by Axeltherabbit** [telegraf/telegraf#189]
there isn't live locations information https://telegram.org/blog/live-locations

**Comment by dotcypress** [comment]
Live locations landed in `v3.13.0`

**Comment by vinnitu** [comment]
I can't view live-location changes sent user to bot, only first position, why?

**Comment by Axeltherabbit** [comment]
> I can't view live-location changes sent user to bot, only first position, why?

you've to check message edits
