### ISSUE TITLE
ctx.scene is undefined on successful_payment

### ISSUE THREAD

**Issue by justmavi** [telegraf/telegraf#1891]
### System info

Telegraf: ^4.13.1, Windows 11

### Steps to reproduce

1. Create a bot
2. Register session() middleware
3. Register callback for successful_payment event
4. Try to use ctx.scene in this callback
5. See error

### Expected behavior

Scene object

### Actual behavior

TypeError: Cannot read properties of undefined (reading 'enter')

### Additional info

Pay attention, ctx.session isn't undefined, it's all right with him. But ctx.scene is undefined.
I'm also using nestjs-telegraf v2.7.0

**Comment by MKRhere** [comment]
`successful_payment` does not belong to a chat, only to a user. This means it does not get captured by session and subsequently does not belong in a scene.

Default session key is `user_id:chat_id`, so session is per user per chat. You *can* make session per user globally, and not per chat, by doing:

```TS
bot.use(session({ getSessionKey: ctx => ctx.from?.id ? String(ctx.from.id) : undefined }));
```

Be warned, if you do this `successful_payment` will appear inside a scene, but each user will be in their own scene across all their chats that includes the bot.

**Comment by justmavi** [comment]
Didn't help. I'm still getting this result:

```js
{
  session: {
    __scenes: { current: 'payment', state: {} },
    lang: 'en',
    selectedCategoryId: 2,
    selectedItemId: 10,
    previousMessageId: 2325, 
  },
  scene: undefined
}
```

> successful_payment does not belong to a chat,  only to a user.

ctx.chat isn't null on successful_payment.

**Comment by justmavi** [comment]
I just need to enter user into the scene on successful payment

```js
bot.on('successful_payment', ctx => ctx.scene.enter('successful_payment'))
```

Thats all.
