### ISSUE TITLE
another way of setting ctx.state

### ISSUE THREAD

**Issue by fczuardi** [telegraf/telegraf#19]
Are there any other way to [set a state property](http://telegraf.js.org/introduction.html#state) or a way to send different/modified context to next middlewares that could play well with the [no-param-reassign](http://eslint.org/docs/rules/no-param-reassign) eslint rule?

I've tried to pass a different ctx as a parameter to the next() function, like ```next(newctx)``` but it don't seem to work as expected.

Related discussion: https://github.com/eslint/eslint/issues/6505

**Comment by dotcypress** [comment]
@fczuardi `next` function not have any parameters, if you want to change context state use following snippet:

```js
const app = new Telegraf(process.env.BOT_TOKEN)

app.use((ctx, next) => {
  ctx.state.foo = 'bar'
  return next()
})

app.on('text', (ctx) => {
  return ctx.reply(`foo=${ctx.state.bar}`)
})
```

BTW Seems this snippet is ok with `no-param-reassign`.

**Comment by fczuardi** [comment]
Yeah, by disabling part of the rule it is possible to stop the warnings… it is an acceptable tradeoff until eslint/eslint#6505 gives developers a way to punch more specific exceptions holes into the rule…

Do you think it would make sense to support a different way of passing context further to the next middlewares though?

Like the supported "value" argument of a javascript generator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/next#Sending_values_to_the_generator

I mean, middlewares are already functions that have ctx as their first argument, ```next``` could be the actual middleware function registered to be called next, if we called the function as the function that it is, with any arguments that it has, we could opt to have middlewares written as pure functions, without side-effects.

I honestly don't know if this would have any real benefits or if it is just bikeshedding / unnecessary immutable radicalism, or even if it would have negative impact on performance, I am mostly just curious about the reasoning and possibilities :)

**Comment by dotcypress** [comment]
Oh yeah, now i got it.
Good point, i'll think about it.

Immutable state and pure functions is definitely awesome, but i'm not sure they will fit current framework design, check this out.

```js
app.use((ctx, next) => {
  ctx.state.foo = 'bar'
  // I need next2 function reference in this place :(
  return next(ctx, next2)
})
```

**Comment by fczuardi** [comment]
I see your point.

As an API suggestion, what about allowing just a single argument though? Like ```return next(ctx)``` would that make sense? Just a way to override what ctx is passed to the next middleware of the pipeline.

**Comment by dotcypress** [comment]
Yeah, i see your point. 

I created a new branch for that:
https://github.com/telegraf/telegraf/compare/feature/pure-middleware

Need time to think about it and do some performance testing 🚀

**Comment by dotcypress** [comment]
Will published in `v4.x`.

See [`telegraf/next`](https://github.com/telegraf/telegraf/tree/next) banch.

Thank you 👍

**Comment by fczuardi** [comment]
Cool!
