### ISSUE TITLE
`Markup.inlineKeyboard` button callbacks working in private messages but not in group chat

### ISSUE THREAD

**Issue by VIPBotsMark** [telegraf/telegraf#1900]
## Context

I am using stage and scenes for conversation flow, I've verified they are set up properly, I've also tried playing around with botfather settings (pretty much every possible option, including inline and privacy modes), gave the bot admin in the group chat. There are no other bots in the group.  
**The same issue happens even when not using scenes, regular bot button callbacks won't work as well.**

* Telegraf.js Version: 4.15.0
* Node.js Version: Node 18
* Operating System: Ubuntu 23.04

## Minimal Example Code Reproducing the Issue

```ts
const { Telegraf, Markup, session, Scenes } = require('telegraf');
const Scene = Scenes.BaseScene;
const leave = Scenes.Stage.leave;

const bot = new Telegraf(process.env.KEY);

const setupScene = new Scene('setup');
const ethScene = new Scene('eth');

const stage = new Scenes.Stage([ethScene, setupScene]);

bot.use(session());
bot.use(stage.middleware());

// scene
setupScene.enter((ctx) => {
        ctx.reply('⚙️ Use the buttons below to customize your bot:', {
            ...Markup.inlineKeyboard([
                [Markup.button.callback(ctx.session.gif ? '✅ Gif / Media' : '❌ Gif / Media', 'gm'),
                // ...more buttons...
          ]}
    }
});

// ...

// callback
setupScene.action('gm', (ctx) => {
    console.log(1); // never logged when in group chat, never even triggered
    ctx.reply(' 🏞  Send media that will appear on your buys:');
    ctx.scene.state.step = 'gm';
});

// ...

setupScene.on('message', async (ctx) => {
    if (ctx.scene.state.step === 'gm') {
         // ...code...
    } // ...
});

```

## Expected Behavior

Button callbacks should work like they do in the private message.

## Current Behavior

Pressing the inline keyboard button in group chat, nothing will be triggered. The same code runs perfectly when interacting with the bot in private messages.
Weirdly, if I use `bot.action('gm', (ctx) => { ... })` instead of setupScene.action, the log gets triggered, however the setupScene.on won't get triggered.

**Comment by hypernova7** [comment]
Move bot.use(stage.middleware()) to the end of setupScene, like this:

```js
const { Telegraf, Markup, session, Scenes } = require('telegraf');
const Scene = Scenes.BaseScene;
const leave = Scenes.Stage.leave;

const bot = new Telegraf(process.env.KEY);

const setupScene = new Scene('setup');
const ethScene = new Scene('eth');


bot.use(session());

// scene
setupScene.enter((ctx) => {
        ctx.reply('⚙️ Use the buttons below to customize your bot:', {
            ...Markup.inlineKeyboard([
                [Markup.button.callback(ctx.session.gif ? '✅ Gif / Media' : '❌ Gif / Media', 'gm'),
                // ...more buttons...
          ]}
    }
});

// ...

// callback
setupScene.action('gm', (ctx) => {
    console.log(1); // never logged when in group chat, never even triggered
    ctx.reply(' 🏞  Send media that will appear on your buys:');
    ctx.scene.state.step = 'gm';
});

// ...

setupScene.on('message', async (ctx) => {
    if (ctx.scene.state.step === 'gm') {
         // ...code...
    } // ...
});

// Here 👇 
const stage = new Scenes.Stage([ethScene, setupScene]);
bot.use(stage.middleware());
```

**Comment by VIPBotsMark** [comment]
Now button callbacks on bot level work, however not on the stages.
Another thing I've noticed is that `scene.on(...)` won't work as well. The `scene.enter(...) ` will work and switch the step though.
This is on both of the versions, mine and yours.

**Comment by VIPBotsMark** [comment]
> Move bot.use(stage.middleware()) to the end of setupScene, like this:
> 
> ```js
> const { Telegraf, Markup, session, Scenes } = require('telegraf');
> const Scene = Scenes.BaseScene;
> const leave = Scenes.Stage.leave;
> 
> const bot = new Telegraf(process.env.KEY);
> 
> const setupScene = new Scene('setup');
> const ethScene = new Scene('eth');
> 
> 
> bot.use(session());
> 
> // scene
> setupScene.enter((ctx) => {
>         ctx.reply('⚙️ Use the buttons below to customize your bot:', {
>             ...Markup.inlineKeyboard([
>                 [Markup.button.callback(ctx.session.gif ? '✅ Gif / Media' : '❌ Gif / Media', 'gm'),
>                 // ...more buttons...
>           ]}
>     }
> });
> 
> // ...
> 
> // callback
> setupScene.action('gm', (ctx) => {
>     console.log(1); // never logged when in group chat, never even triggered
>     ctx.reply(' 🏞  Send media that will appear on your buys:');
>     ctx.scene.state.step = 'gm';
> });
> 
> // ...
> 
> setupScene.on('message', async (ctx) => {
>     if (ctx.scene.state.step === 'gm') {
>          // ...code...
>     } // ...
> });
> 
> // Here 👇 
> const stage = new Scenes.Stage([ethScene, setupScene]);
> bot.use(stage.middleware());
> ```

Now button callbacks on bot level work, however not on the stages.
Another thing I've noticed is that `scene.on(...)` won't work as well. The `scene.enter(...) ` will work and switch the step though.
This is on both of the versions, mine and yours
