### ISSUE TITLE
Webhook(s) for multiple telegram bots

### ISSUE THREAD

**Issue by royibernthal** [telegraf/telegraf#1916]
Setting up a webhook for a single bot seems to work, but once I add another one I'm starting to get an error:
`Error: listen EADDRINUSE: address already in use :::80`

I've tried setting the same webhook path (/secret-path) for both, as well as setting a separate webhook path for each, which seems to not be supported?
https://github.com/evilsprut/nestjs-telegraf/discussions/574

How am I supposed to have webhook(s) for multiple telegram bots?

## Context

* Telegraf.js Version: 4.13.1
* Node.js Version: 20.10.0
* Operating System: Windows 10

**Comment by tair-rhyme** [comment]
you have to listen different ports, then you could use nginx to handle all incoming request then forward to specific bot depending on path, here is my nginx config

```
server {
    server_name example.com;

    location /webapp {
        alias /home/almalinux/webapp/;
        try_files $uri  /index.html /$uri =404;
    }

    location /rider {
        proxy_pass http://localhost:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /driver {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin {
        proxy_pass http://localhost:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    listen 443 ssl;
...
}
``` 


here is my bot init:
```js
const bot = new Telegraf(TG_TOKEN, { telegram: { webhookReply: false } })
const app = express();
(async function() {
    if(!process.env.URL) url = await ngrok.connect(PORT);
    
    const secretPath = `${process.env.PATH_PREFIX}${bot.secretPathComponent()}`
    await bot.telegram.setWebhook(`${url}${secretPath}`);
    await app.use(bot.webhookCallback(secretPath));
})
app.listen(PORT, () => {
    console.log(`Application started on port ${PORT}!`)
})
```
change `PATH_PREFIX` depending on bot, in my case there are `/driver/telegraf/`, `/rider/telegraf/`, `/admin/telegraf/`
PS: i use ngrok for local development, in production mode url is my domain with url scheme ex: `https://example.com`

**Comment by royibernthal** [comment]
Thanks for the detailed response. Is there no way to do it when listening to the same port? I have a flexible and growing number of bots so doing it this way would be sub optimal. To the best of my understanding it would be possible with the raw telegram REST, I'm just trying to figure out how to do it with telegraf.

**Comment by MKRhere** [comment]
It's absolutely possible to use the same server and port with different routes for multiple bots if they're on the same process. Depends on how you're setting them up. Post some code.

**Comment by royibernthal** [comment]
True it's possible. I'm using [nestjs-telegraf](https://github.com/evilsprut/nestjs-telegraf), which is why I didn't share code. When I explicitly specify the port in the webhook launchOptions I get the aforementioned error, but if I don't specify a port everything works as expected. I guess this could be marked as solved. Thanks!
