### ISSUE TITLE
Failed to getMe() with nodejs 20 and ubuntu 22

### ISSUE THREAD

**Issue by jinsankim** [telegraf/telegraf#1917]
## Context

Failed at `getMe()` when `launch()` with `nodejs 20` and `ubuntu 22`. 

Please note that I've succeeded to `launch()`
- with `nodejs 20`(also `nodejs 18`) and `mac os`.
- with `nodejs 18` and `ubuntu 22`.

* Telegraf.js Version:  4.15.3
* Node.js Version: v20.10.0
* Operating System: Ubuntu 22.04.3 LTS

## Minimal Example Code Reproducing the Issue

```ts
import { Telegraf } from 'telegraf'

const BOT_TOKEN = 'MY_TELEGRAM_BOT_TOKEN'

async function main() {
  const bot = new Telegraf(BOT_TOKEN)
  bot.launch()
  console.info('done')
}

main()

process.on('unhandledRejection', (reason, promise) => {
  console.error('[Error] Unhandled rejection at ', promise, `reason: ${reason}`)
  process.exit(1)
})
```

## Expected Behavior

getMe() responses correctly.

## Current Behavior

An error is raised.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
  telegraf:main Created a `Telegraf` instance +0ms
  telegraf:main Connecting to Telegram +1ms
  telegraf:client HTTP call getMe {} +0ms
done
[Error] Unhandled rejection at  Promise {
  <rejected> FetchError: request to https://api.telegram.org/bot753256890:[REDACTED]/getMe failed, reason:
      at ClientRequest.<anonymous> (/home/my-project/node_modules/node-fetch/lib/index.js:1501:11)
      at ClientRequest.emit (node:events:514:28)
      at TLSSocket.socketErrorListener (node:_http_client:495:9)
      at TLSSocket.emit (node:events:514:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  }
} reason: FetchError: request to https://api.telegram.org/bot753256890:[REDACTED]/getMe failed
```

**Comment by ne0c0de** [comment]
same situation happening on me while I'm running docker container in host network setting, could you find any solution?

**Comment by doaortu** [comment]
apparently we need to enforce `fetch` to use IPv4 to work with node 20 (see the node-telegram-bot-api issue reference above) , but I don't know how to do it with this library.
downgrading to node 18 works tho.
