### ISSUE TITLE
Getting Error: 400: Bad Request: can't parse entities in message text: Expected end tag at byte offset 94     

### ISSUE THREAD

**Issue by Kamalnrf** [telegraf/telegraf#192]
Whenever I try to send data like this in HTML format 

1. Sent <b>Ƀ</b><b>1 </b>to <b>910000010</b><i></i>

2. Withdrew <b>Ƀ</b><b>1 </b><b></b><i><i> (pending)</i></i>

3. Withdrew <b>₹</b><b>1,000 </b><b></b><i><i> (pending)</i></i>

4. Sent <b>Ƀ</b><b>0.1 </b>to <b>910000001</b><i><i> (pending)</i></i>

5. Received <b>₹</b><b>1,000 </b>from <b>910000001</b><i><i> (pending)</i></i>

I was getting 400 bad request error but it was working fine for same format of data in other actions...

**Comment by dotcypress** [comment]
I'm afraid Telegram supports only small subset of `HTML`.
Could you share some code example?

**Comment by Kamalnrf** [comment]
I was getting this problem when a 'hear' trigger happens and when the below function is called

`ctx.replyWithHTML(reply, myMoneyKeyBoard)`

In other scenarios html data of same size works.

**Comment by dotcypress** [comment]
Could you provide more examples?

**Comment by andreyselin** [comment]
This also may occur if you you pass non-closed tags, like `<b><b>Some text</b>`
