### ISSUE TITLE
Telegraf failing catching multiple Too Many Requests error using Bun

### ISSUE THREAD

**Issue by Nishimara** [telegraf/telegraf#1921]
## Context

* Telegraf.js Version: 4.15.3
* Node.js Version: -
* Operating System: Debian 12

## Minimal Example Code Reproducing the Issue

```ts
import { Telegraf } from 'telegraf';

const bot = new Telegraf(Bun.env.TOKEN!);

bot.start((ctx) => {
    ctx.reply('Hi!');
})

bot.launch();
console.log('Started');
```

Use bun 1.0.20 and try to run this code.

## Expected Behavior

Bot launched for a long-time period and no errors encountered.

## Current Behavior

Bot launched but fails when 429 error Too Many Requests handled right after previous one.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

TypeError: setTimeout expects a function.
![image](https://github.com/telegraf/telegraf/assets/59232119/d55be32b-7bd1-4f4c-92a2-0632c182bb26)

**Comment by hypernova7** [comment]
Use async await and use bot.catch to prevent bot crash

```js
import { Telegraf } from 'telegraf';

const bot = new Telegraf(Bun.env.TOKEN!);

bot.catch(e => {
  console.error(e)
});

bot.start(async (ctx) => {
    await ctx.reply('Hi!');
})

bot.launch();
console.log('Started');
```

Additionally, error 429 is due to sending the /start command too many times, more than 30 messages per second is the limit for both users and bots.
