### ISSUE TITLE
Bot API 7.0 Support

### ISSUE THREAD

**Issue by bitcldr** [telegraf/telegraf#1923]
**Additional context**

Telegram has released [Bot API 7.0](https://core.telegram.org/bots/api#december-29-2023) which has some cool features like _Reactions_. Would be nice if the _telegraf_ would add a new API features.

**Comment by MKRhere** [comment]
Working on it: https://github.com/telegraf/telegraf/tree/feat/api-7.0
Related to https://github.com/telegraf/types/pull/1
Will be out soon.

**Comment by maZahaca** [comment]
So much waiting for `setMessageReaction`! Thank you for your dedicated work!

**Comment by DockedFerret800** [comment]
Any ETA for Bot Api 7.0 support?

**Comment by MKRhere** [comment]
@DockedFerret800 Within ~2-3 days.

**Comment by DockedFerret800** [comment]
> @DockedFerret800 Within ~2-3 days.

Brilliant, cheers!

**Comment by ittermit** [comment]
Any new ETA for Bot Api 7.0 support?

**Comment by ittermit** [comment]
@MKRhere Any news?

**Comment by MKRhere** [comment]
Not helpful people; I understand your impatience, but there's no need to ask repeatedly. You can update to the latest branch:

```shell
npm install "github:telegraf/telegraf#feat/api-7.0"
```

It is a mostly complete 7.0 branch with completely updated types, on which I'm working on a couple more things before release. Meanwhile I'd appreciate any bug reports or feedback in this thread.

**Comment by MKRhere** [comment]
Release candidate v4.16.0-rc.1 is now available on npm. Release notes available here: https://github.com/telegraf/telegraf/blob/feat/api-7.0/release-notes/4.16.0.md

I'm leaving this on for a day for potential bug reports, since it's a massive update for both the API and Telegraf. Please do try it in your bots and report any issues!
