### ISSUE TITLE
Date and time of a message

### ISSUE THREAD

**Issue by 2dvisio** [telegraf/telegraf#193]
Is there a way to get the date and time of a message being sent from user?
Locale would be the best (including the Time zone).

**Comment by dotcypress** [comment]
Hey!

Yes, all messages contains [`date`](https://core.telegram.org/bots/api#message) field:
```js
bot.command('start', (ctx) => {
  console.log(ctx.message.date) // Message date as UNIX timestamp.
})
```

**Comment by 2dvisio** [comment]
Yes, that is not a Date with a time zone embedded. The server does not necessarily knows the time zone of the user. I have checked the Telegram API  and it seems a flaw on their side. The issue can remain closed.

**Comment by muety** [comment]
Same issue here. I haven't found a way to get a user's time zone, yet.
