### ISSUE TITLE
KeyboardButtonRequestChat is not supported in Telegraf 4.15.3

### ISSUE THREAD

**Issue by chakzefir** [telegraf/telegraf#1931]
## Context

I'm trying to reply the message with `inline_keyboard`, where `request_chat` button placed.

* Telegraf.js Version: 4.15.3
* Node.js Version: 20.8.1
* Operating System: macOS 13.5.2 (22G91)

## Code Snippet

```ts
@Command('join')
  async joinGroup(ctx: Context) {
    await ctx.reply('Choose one of the public groups or channels from the list 👇', {
      reply_markup: { 
        inline_keyboard: [
          [{
            text: 'Choose group',
            request_chat: {
              request_id: 123412341233412341234123,
              chat_is_channel: true
            }
          }]
        ],
      }
    })
  }
```

## Expected Behavior

I expect that KeyboardButtonRequestChat is working same or similar as in Telegram API docs (maybe it's a feature request) https://core.telegram.org/bots/api#keyboardbuttonrequestchat

## Current Behavior

```
Object literal may only specify known properties, and 'request_chat' does not exist in type 'InlineKeyboardButton'.ts(2353)
```

The types are not okay with that, and ignoring type is just giving an error:

```
Error: 400: Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard
```

**Comment by MKRhere** [comment]
As the link you sent describes, `request_chat` can only be used in non-inline keyboards. Change "inline_keyboard" to "keyboard".

**Comment by chakzefir** [comment]
@MKRhere you might be right, but I've checked this source and it should be possible https://core.telegram.org/bots/features#chat-and-user-selection

**Comment by MKRhere** [comment]
@chakzefir The GIF on that link is wrong. I'll ask for it to be updated. The docs are right:
https://core.telegram.org/bots/api#keyboardbuttonrequestchat

Notice how the interface name starts with "KeyboardButton" instead of "InlineKeyboardButton"?

Edit:

> The GIF on that link is wrong

Refer to https://t.me/BotTalk/731814 for an acknowledgement
