### ISSUE TITLE
Configure proxy

### ISSUE THREAD

**Issue by finvernizzi** [telegraf/telegraf#194]
It could be very isefull to have config hooks to set a proxy.
An alternative solution could be to use ENVIRONMENT variables.

**Comment by dotcypress** [comment]
Hey!

You can use Telegraf with [custom proxies](http://telegraf.js.org/telegraf.html#constructor).
Use `agent` options for that:

```js
const Telegraf = require('telegraf')
const HttpsProxyAgent = require('https-proxy-agent')

const bot = new Telegraf('token', {
  telegram: {
    agent: new HttpsProxyAgent('proxy url')
  }
})
```

**Comment by finvernizzi** [comment]
Thanks!

2017-10-25 21:29 GMT+02:00 Vitaly Domnikov <notifications@github.com>:
