### ISSUE TITLE
First Scene execute two times Scenes.WizardScene

### ISSUE THREAD

**Issue by 0xHal** [telegraf/telegraf#1955]
## Context
I'm trying to use Scene to create more readable code and easily scalable but when i started to, i had a bug very strange, tried to found if someone had it too but i couldn't find anything

Here's code snap for my Scene:
![code](https://github.com/telegraf/telegraf/assets/134301949/b65d2339-275b-470f-8748-537fefc864c3)

* Telegraf.js Version: ^4.15.3
* Node.js Version: v20.10.0
* Operating System: Windows 10

hello-middleware.js
```ts
import { Composer, Context, Scenes, session, Telegraf, Format } from "telegraf";

const walletConfigurationScene = new Scenes.WizardScene(
    "hello",
    async (ctx) => {
        const { chat: { id: chatId }, message_id: messageId } = ctx.update.message;
        await ctx.sendMessage("Hello, how are you?", {
            reply_to_message_id: messageId
        });
        return ctx.wizard.next();
    },

    async (ctx) => {
        const { chat: { id: chatId }, message_id: messageId } = ctx.update.message;
        await ctx.sendMessage("Where you'r from?", {
            reply_to_message_id: messageId
        });
        return ctx.wizard.next();
    },

    async (ctx) => {
        await ctx.reply("See ya!")
        return await ctx.scene.leave();
    },
)

const walletScene = new Scenes.Stage([walletConfigurationScene])

export default walletScene;
```

bot.js
```ts
import { Composer, Context, session, Telegraf} from "telegraf";
import helloMiddleWare from './middlewares/hello-middleware.js'
import helloScene from './middlewares/hello-middleware.js'

const helloBot = new Telegraf(process.env.BOT_TOKEN)
helloBot.use(session({ store }))
helloBot.use(helloMiddleWare)
helloBot.use(helloScene.middleware())

helloBot.use(async (ctx, next) => {
    setContext(ctx);
    await next();
})

helloBot.command('hello', (ctx) => {
    ctx.scene.enter('hello')
});

await helloBot.launch();
```

## Expected Behavior

I just want one execution per "Scene", tried to google it but didn't found anything..

## Current Behavior

From my TG Bot:
![image](https://github.com/telegraf/telegraf/assets/134301949/a928a6cc-7362-4b80-bdfc-d929e04dccd4)

Thanks for reading!

**Comment by MKRhere** [comment]
Two problems:

1. The stage has been mounted twice:

	```TS
	helloBot.use(helloMiddleWare)
	helloBot.use(helloScene.middleware())
	```

	helloMiddleWare and helloScene are the same object. One of these lines is enough.

2. You must await or return `ctx.scene.enter('hello')`.

**Comment by 0xHal** [comment]
Yes it was this, thanks a lot for all the help you provide on this repo!

**Comment by MKRhere** [comment]
You're welcome!
