### ISSUE TITLE
Composer.reaction method not working on new release 4.16.0

### ISSUE THREAD

**Issue by matteolungo** [telegraf/telegraf#1956]
## Context

* Telegraf.js Version: 4.16.0
* Node.js Version: 18.15.0
* Operating System: Windows 11

## Minimal Example Code Reproducing the Issue

```ts
const bot = new Telegraf(BOT_TOKEN);

bot.reaction("👍", (ctx) => {
    ctx.reply('Thumbs up').catch(err => console.log(err));
});
```

## Expected Behavior

Debug breaks in Composer.reaction and bot replies to reaction

## Current Behavior

Nothing happens (no break on debug)

**Comment by MKRhere** [comment]
Reactions are not delivered by Telegram by default, you have to enable it by adding it to allowedUpdates:

```TS
// once you pass an array, you will only receive the updates you opt in for:
bot.launch({ allowedUpdates: [ "message", "message_reaction" ] });
```

The bot also needs to be admin in the chat to receive reactions.

**Comment by matteolungo** [comment]
> Reactions are not delivered by Telegram by default, you have to enable it by adding it to allowedUpdates:
> 
> ```ts
> // once you pass an array, you will only receive the updates you opt in for:
> bot.launch({ allowedUpdates: [ "message", "message_reaction" ] });
> ```
> 
> The bot also needs to be admin in the chat to receive reactions.

I missed this step. Thank you!
