### ISSUE TITLE
How to organize messages queue?

### ISSUE THREAD

**Issue by Kryjite** [telegraf/telegraf#196]
I have a problem. My users are too active and the bot stops responding. 
Do you have a tool to organize an outbound message queue? 
(30 messages per second for all messages, 1 message per second for a specific user)
Thank you.

**Comment by dotcypress** [comment]
Hey.

Telegraf does't have any solution from the box, but i suppose any queue will work in this case.

**Comment by JRakhimov** [comment]
There is a good [solution](https://github.com/yagop/node-telegram-bot-api/issues/192) for this problem. Hope it will be useful for all devs.
