### ISSUE TITLE
BUG] type error when sending message using Web page preview option

### ISSUE THREAD

**Issue by zC4sTr0** [telegraf/telegraf#1960]
## Context

When trying to disable preview using this example code from issue 975: https://github.com/telegraf/telegraf/issues/975
![image](https://github.com/telegraf/telegraf/assets/38432614/e56dcd06-a03a-4e90-918b-19004ba79e97)

I'm getting this typescript error due to strict type checking:

**Object literal may only specify known properties, and disable_web_page_preview does not exist in type:**

* Telegraf.js Version: 4.16.3
* Node.js Version: 20.11.1
* Operating System: Windows

## Minimal Example Code Reproducing the Issue

```ts
telegram.sendMessage(12345, "[Google](https://google.com)", { parse_mode: "Markdown", disable_web_page_preview: true })
```

How can we fix the type check?

**Comment by MKRhere** [comment]
Telegram has moved this option to `link_preview_options: { is_disabled: true }`.

**Comment by zC4sTr0** [comment]
> link_preview_options: { is_disabled: true }

Thank you. The issue is solved.
