### ISSUE TITLE
Listen to multiple bots

### ISSUE THREAD

**Issue by veob** [telegraf/telegraf#197]
Hi. My goal is to listen to multiple telegram bots.

Is it possible to create **multiple** instances of Telegraf class in **one** node.js instance (but this looks like a horrible solution, memory will leak)? Or maybe it is possible to pull out some static methods, so I could use Telegraf as not a singleton.

I've looked through source code and looks like current architecture doesn't support it.

**Comment by dotcypress** [comment]
Hi @veob 

Yes, this is possible, and we have couple of solutions:

* [`handleUpdate `](http://telegraf.js.org/telegraf.html#handleupdate) - you can create multiply instances of the bot and implement webhook server and custom routing.
* [`webhookCallback `](http://telegraf.js.org/telegraf.html#webhookcallback) - spin up 1 http server for all bots

**Comment by veob** [comment]
Thank you for the reply, @dotcypress.

> `webhookCallback` - spin up 1 http server for all bots

This method is non-static. So, in order to use it for multiple bots, I must create at least one bot instance, and then manually (without telegraf) do multiple 'setWebhook' request for all other bots. Right?

As a result I get a single bot instance and a single http server, which listens to multiple bots and uses `webhookCallback` method from that single bot instance. Am I correct?

**Comment by joshuaquek** [comment]
What if we only want to horizontally scale a single bot? 

(which means that we only use a single unique bot token, instead of using multiple tokens)

**Comment by JRakhimov** [comment]
> BTW You can use `handleUpdate` - it's more flexible.

@dotcypress Can u represent same thing with handleUpdate and with Express?
I can't understand what exactly should be in rawUpdate param. Thanks in advance!

**Comment by imdkbj** [comment]
> > This method is non-static. So, in order to use it for multiple bots, I must create at least one bot instance, and then manually (without telegraf) do multiple 'setWebhook' request for all other bots. Right?
> 
> Yes, you can spin up single http server, and attach bot listeners.
> 
> Koa example:
> 
> ```js
> const Koa = require('koa')
> const app = new Koa()
> 
> function attachBot(token) {
>   const bot = new Telegraf(token)
>   app.use(bot.webhookCallback(token))
>   bot.on('message', (ctx) => ctx.reply('Hey'))
>   bot.setWebhook('https://...../token')
> }
> 
> attachBot('token1')
> attachBot('token2')
> attachBot('token3')
> attachBot('token4')
> 
> app.listen(3000)
> ```
> 
> BTW You can use `handleUpdate` - it's more flexible.

Hey! This doesn't seems working..

**Comment by imdkbj** [comment]
> > BTW You can use `handleUpdate` - it's more flexible.
> 
> @dotcypress Can u represent same thing with handleUpdate and with Express?
> I can't understand what exactly should be in rawUpdate param. Thanks in advance!

Pls share if have working solution to listen multiple bot
