### ISSUE TITLE
Bot API 7.2 support

### ISSUE THREAD

**Issue by godemodegame** [telegraf/telegraf#1977]
31st march was released new bot API with supports business accounts.

Release Notes: https://core.telegram.org/bots/api

**Comment by MKRhere** [comment]
I couldn't get to the update yet. Will take it over the weekend.

**Comment by godemodegame** [comment]
I'm using now like that:

```
bot.on('business_message' as any, async (context: any) => {
    await context.telegram.sendMessage(
        context.update.business_message.chat.id, 
        "Hello, world!",
        {
            business_connection_id: context.update.business_message.business_connection_id
        }
      )
});
```

may be it will help to anybody, but better wait typescript support
