### ISSUE TITLE
Property data is does't exist on type CallbackQuery

### ISSUE THREAD

**Issue by miruchigawa** [telegraf/telegraf#1983]
## Context

I'm trying to get callback query data but typescript keep showing error data is doesn't exist

* Telegraf.js Version: 14.16.3
* Node.js Version: 22
* Operating System: Arch Linux

## Minimal Example Code Reproducing the Issue

```ts
... (ctx) => {
       const data = ctx.callbackQuery?.data.split(':')[1]
       console.log(data)
}
```

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
Please include any relevant log snippets or files here.
```

**Comment by undermuz** [comment]
i have the same problem

**Comment by MKRhere** [comment]
Since callbackQuery can be a data or game callback, you need to narrow it.

```TS
import { callbackQuery } from "telegraf/filters";

// later
if (ctx.has(callbackQuery("data")) {
	const [ data ] = ctx.callbackQuery.data.split(":");
	// ...
}
```

**Comment by undermuz** [comment]
@MKRhere 
Thanks a lot for your help. This solved my problem.

Could you please tell me where I can read about such nuances in the package documentation? I can't find such information

**Comment by MKRhere** [comment]
A lot of these nuances are only currently documented in https://github.com/telegraf/telegraf/releases. You can also follow releases on https://t.me/Telegraf_JS

**Comment by DiVoronov** [comment]
**This is because CallbackQuery can be either CallbackQuery.DataQuery or CallbackQuery.GameQuery**

You can declare a variable "callbackQuery" and type it exactly as **CallbackQuery.DataQuery**

Example:     
async checkCorrectAnswer(ctx: Context) {
    const callbackQuery = ctx.callbackQuery as CallbackQuery.DataQuery;
    await ctx.answerCbQuery(callbackQuery.data);
  }

This will solve the problem
