### ISSUE TITLE
`await bot.launch()` hangs forever during long polling in latest version

### ISSUE THREAD

**Issue by rikumi** [telegraf/telegraf#1989]
## Context

* Telegraf.js Version: 4.16.3
* Node.js Version: 16.18.1 / 18.20.1
* Operating System: macOS / Debian

## Minimal Example Code Reproducing the Issue

```ts
const bot = new Telegraf(config.telegramBotToken);
bot.launch().then(() => console.log('Bot started!'))
```

## Expected Behavior

`bot.launch()` should resolve when long polling begins.

This was true in Telegraf v4.4.0.

## Current Behavior

`bot.launch()` hangs forever when long polling runs.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

N/A

**Comment by MKRhere** [comment]
Duplicate: https://github.com/telegraf/telegraf/issues/1749
