### ISSUE TITLE
bot.reaction() not providing message content

### ISSUE THREAD

**Issue by steilerDev** [telegraf/telegraf#1996]
## Context

* Telegraf.js Version: 4.16.3
* Node.js Version: v18.20.2
* Operating System: macOS 14.5

## Minimal Example Code Reproducing the Issue

```js
import { Telegraf } from "telegraf";

const token = "<token>";
const bot = new Telegraf(token)

bot.reaction('👍', (ctx) => {
    console.log(JSON.stringify(ctx.msg))
})

bot.launch({ allowedUpdates: [ "message", "message_reaction" ] })

// Enable graceful stop
process.once('SIGINT', () => bot.stop('SIGINT'))
process.once('SIGTERM', () => bot.stop('SIGTERM'))
```

React to any previously sent message with thumbs up.

## Expected Behavior

Expecting to be able to access the content of the message that was reacted to.

## Current Behavior

While `ctx.msgId` is available, `ctx.message` (and `ctx.msg`) is undefined. `ctx.update` looks like this

```
{
  "update_id": 1234,
  "message_reaction": {
    "chat": {
      "id": 123,
      "first_name": "<firstName>",
      "last_name": "<lastName>",
      "username": "<username>",
      "type": "private"
    },
    "message_id": 123,
    "user": {
      "id": 123,
      "is_bot": false,
      "first_name": "<firstName>",
      "last_name": "<lastName>",
      "username": "<userName>",
      "language_code": "en"
    },
    "date": 1717427615,
    "old_reaction": [],
    "new_reaction": [
      {
        "type": "emoji",
        "emoji": "👍"
      }
    ]
  }
}
```

Additionally I cannot see an obvious way to retrieve the message content based on `message_id`.

**Comment by MKRhere** [comment]
Unfortunately, this is by Telegram's design. If you care about the message to watch for reactions, you have to store the message yourself.

There is no way with the Bot API to retrieve a message by message_id.

**Comment by steilerDev** [comment]
Ah - that's unfortunate :/ 

So the approach would be to listen on every message and store them in the app context - and then retrieve the id when the reaction comes in?

**Comment by MKRhere** [comment]
If by context you mean session, it's not advisable to store large amounts of data in session. You should just store in a database.

**Comment by steilerDev** [comment]
Yes - that makes sense - thank you and closing this as something that (at the moment) cannot be easily fixed.
