### ISSUE TITLE
getChat function do not return the good type

### ISSUE THREAD

**Issue by oom-** [telegraf/telegraf#2010]
## Context

* Telegraf.js Version: 4.16.3
* Node.js Version:  v20.14.0
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```ts
const chatInfo = await ctx.getChat();
```

You just need to try to call `getChat` method `ctx.getChat()` or `bot.telegram.getChat(chatId)`, to trigger the issue.

The return type do not have enough properties and display TS errors:

![image](https://github.com/telegraf/telegraf/assets/11071671/9ec2bcc3-5d89-4e71-9da8-2399a5c625b6)

![image](https://github.com/telegraf/telegraf/assets/11071671/8225df89-d63c-41c3-a2d1-e56152d9804a)

![image](https://github.com/telegraf/telegraf/assets/11071671/25b5725a-0253-458c-ba3c-cc97caf0b8d3)

## Expected Behavior

As per Telegram documentation for `getChat`: https://core.telegram.org/bots/api#getchat
Is returning the `ChatFullInfo` object: https://core.telegram.org/bots/api#chatfullinfo

## Current Behavior

`getChat` is returning a `ChatFromGetChat` object missing the optional properties.

**Comment by CyberPanCake3000** [comment]
Hello! I have a question about Telegraf types. Does anyone know where I can find information about `ChatFromGetChat`? I can't find any description and it seems to me that methods `ctx.getChat()` and `ctx.telegram.getChat(chatId)` both return ChatFullInfo, but something odd is happening with the documentation and typings.

I created this type assertion as a workaround (I know it looks horrible dont judge me ok 😞):
![image](https://github.com/user-attachments/assets/b5aa4dbb-2644-434d-a247-e711d3fcccb8)

Gonna dive in but not sure if I can fix it 😶‍🌫️

**Comment by MKRhere** [comment]
The reason for this is that different types of `ChatFullInfo` objects have different properties. Telegraf types this as a union between them, and you have to test the type to narrow it down.

```TS
// this `chat` object seems to only have properties common to all types of chats
const chat = await ctx.getChat();

const name = chat.first_name; // type error because groups don't have `first_name`!

if (chat.type === "private") {
	// `chat` now also has properties exclusive to private!
	// `chat.first_name` is now safe to access
}

if (chat.type === "supergroup") {
	// `chat.is_forum` is now safe to access, because it's only available on supergroup chats!
}
```

So, all you need to do is inspect the `chat.type`.
