### ISSUE TITLE
'Unbind' earlier set triggers (telegraf.hears)

### ISSUE THREAD

**Issue by NoahKr** [telegraf/telegraf#202]
As far as I can see it is not possible to override or unbind earlier set telegraf.hears triggers.

For instance if the following code is executed:
```
        app.hears('test', ({reply}) => {
            return reply("FIRST!");
        });

        app.hears('test', ({reply}) => {
            return reply("SECOND!");
        });

        app.hears('test', ({reply}) => {
            return reply("THIRD!");
        });
```

If the bot hears test it will always reply with "FIRST!".

Is there any way to unbind old triggers or to override them?

**Comment by weijinnx** [comment]
What do you need to do?

**Comment by NoahKr** [comment]
I'm letting users set triggers and responses based on certain words.

In example a user can set a trigger for the word "420" and a response "Blaze it". 
When the word "420" is used the bot would reply with "Blaze it".

I though this would be funny in groups.

The problem is however. Users need to be able to delete triggers, and since I can't 'unbind' an "telegraf.hears" method I'm not sure how to do that

**Comment by weijinnx** [comment]
So, as for as I understood, trigger it is telegraf.hears, is it correct? If it is, so I don't think that users could delete them, because this trigger is a code, and users haven't access to sources. But, you can write some class to register 'custom' triggers and save them somewhere (cache, memory, database) and use it like... User says '420 time' and you can create telegraf.hears(/(420) (.*)/) - like command with params, and do what you want.

But I'm not sure, that I completely understand what you mean) If not (if i didn't understand task correctly), can you describe it more?

**Comment by NoahKr** [comment]
I understand i can create a command users can use to register something like 'telegraf.hears(/(420) (.*)/)'. My problem is that there is no way to unset the 'hears trigger' for that specific regex.

**Comment by weijinnx** [comment]
Of course. Users can't do that :(

**Comment by NoahKr** [comment]
Yes but wouldn't the trigger still activate in the code? I understand nothing would happen since the status in the database is deactivated. I fear this would impact performance in the long term. Since there are all kinds of triggers going off that don't actually do anything

**Comment by weijinnx** [comment]
Honestly, it will be a problem in future. But for now, I don't see another way, sorry :(
It's like... You have a bot, which just execute commands... It has some stack of commands and thats all. User can just run the command, but it can't affect on source code.

**Comment by NoahKr** [comment]
But if there was a function to unbind previous set triggers (to unset registered telegraf.hears) than I could avoid the problem.

**Comment by dotcypress** [comment]
@NoahKr as I understood, you want some sort of `dynamic text routing`.
Actually, you can use `.hears` like that:

```js

function checkAnswer(text) {
   // Naive implementation, replace with any predicate
   return text === '420'
}

bot.hears(checkAnswer, ctx => ctx.reply('Blaze it'))

```

**Comment by NoahKr** [comment]
Thanks. I think this will work for my use case.
Would something like this also work?

```
let wordArray = ['420', '1337'];

function giveWordArray() {
    return wordArray;
}

bot.hears(wordArray, ctx => ctx.reply('Blaze it'))
```

At this point in time the words "420" and "1337" will trigger the response "Blaze it".

But if the wordArray is changed later on
```
wordArray = ["something else"];
```

Will the response be triggered by the word "something else"? And will the response not trigger for "420" and "1337" anymore?

**Comment by weijinnx** [comment]
@NoahKr yes.
