### ISSUE TITLE
handling error with  bot.telegram.sendMessage

### ISSUE THREAD

**Issue by lenny76** [telegraf/telegraf#203]
hi
please help
how to manage error when I do not have a reply context like this?

bot.telegram.sendMessage(123123,'hi');

(node:12852) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 400: Bad Request: chat not found
(node:12852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

thanks

**Comment by dotcypress** [comment]
Hey!

Telegraf massively uses [`Promises`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), so you need to handle errors in promise chain like that:

```js
bot.telegram.sendMessage(123123,'hi').catch(err => console.log(err))
```

or with `async/await`

```js
try {
  await bot.telegram.sendMessage(123123,'hi')
} catch (err) {
  console.log(err)
}
```

**Comment by lenny76** [comment]
thanks a lot
I need to study more promises :smile:

**Comment by oxfn** [comment]
@dotcypress And why does this error occur (`400: Bad Request: chat not found`)? We have it from time to time on notification service, managed by pm2. Messages are lost often while chat surely exists

**Comment by TesfaM** [comment]
![image](https://user-images.githubusercontent.com/47814231/54539309-f0829800-49a6-11e9-8331-3f65f5c950d0.png)

its not working
![image](https://user-images.githubusercontent.com/47814231/54539362-098b4900-49a7-11e9-8db8-75cce3c5c2e5.png)
