### ISSUE TITLE
Security Vulnerabilities in Dependencies (request/tough-cookie)

### ISSUE THREAD

**Issue by Duman360** [telegraf/telegraf#2048]
Hello, I encountered moderate security vulnerabilities when installing Telegraf. These issues seem to originate from outdated dependencies (request, tough-cookie) in the dependency tree. Below are the details:

Vulnerable Dependency: request

Type: Server-Side Request Forgery (SSRF)
Advisory: https://github.com/advisories/GHSA-p8p7-x288-28g6
Vulnerable Dependency: tough-cookie

Type: Prototype Pollution
Advisory: https://github.com/advisories/GHSA-72xf-g2v4-qvf3
Steps to Reproduce:

Install Telegraf with npm install telegraf.
Run npm audit.
Observe the reported vulnerabilities.
Environment:

Telegraf Version: 10.9.1
Node.js Version: [22.11.0]
OS: [Windows 11]
Expected Behavior: Telegraf's dependency tree should be free of known vulnerabilities.

Suggested Fix: Update request and tough-cookie dependencies or replace request with a modern HTTP library like axios.

**Comment by KnorpelSenf** [comment]
Please stop bullshitting people with your AI spam thanks bye
