### ISSUE TITLE
TypeError: Cannot read property 'hi' of undefined

### ISSUE THREAD

**Issue by Amirhz9479** [telegraf/telegraf#205]
By executing this code, I get this error
But I do not know why, please help me

`TypeError: Cannot read property 'hi' of undefined`
`      at app.on (C:\Users\Mohammad\Desktop\TeleGo\index.js:19:18)`
`      at Promise.resolve.then (C:\Users\Mohammad\Desktop\TeleGo\node_modules\telegraf\lib\core\composer.js:81:56)`
`      at <anonymous>`
`      at process._tickCallback (internal/process/next_tick.js:169:7)`

`Failed to process updates. TypeError: Cannot read property 'hi' of undefined`
`   at app.on (C:\Users\Mohammad\Desktop\TeleGo\index.js:19:18)`
`    at Promise.resolve.then(C:\Users\Mohammad\Desktop\TeleGo\node_modules\telegraf\lib\core\composer.js:81:56)`
`    at <anonymous>`
`    at process._tickCallback (internal/process/next_tick.js:169:7)`

my code

`app.on('text', (ctx) => {`
`		if (typeof msgs[ctx.message.text] === 'undefined') {`
`		return ctx.telegram.sendCopy(ctx.from.id, msgs[ctx.message.text])}`
`		else { return ctx.telegram.sendCopy(ctx.from.id, 'test') }`
`})`

**Comment by weijinnx** [comment]
Are you sure, that this part of code initiate an error? This part of code doesn't contains any 'hi' property...

**Comment by Amirhz9479** [comment]
sorry 
this is all of code:
`const Telegraf = require('telegraf')`
`const fs = require('fs')`
`var msgs;`
`const app = new Telegraf(process.env.BOT_TOKEN)`
`fs.exists("./msg.json", function(fileok){`
`  if(fileok)fs.readFile("./msg.json", function(error, data) {`
`    msgs = fs.readFile('./msg.json', 'utf8');`
`  });`
`  else console.log("file [msg.json] not found");`
`});`

`app.command('start', (ctx) => {`
`//	ctx.telegram.sendCopy(ctx.from.id, ctx.message)`
`//	console.log(JSON.stringify(msgs[ctx.message.text]))`
`})`

`app.on('text', (ctx) => {`
`//	console.log(ctx.message.text)`
`		if (typeof msgs[ctx.message.text] === 'undefined') {`
`		return ctx.telegram.sendCopy(ctx.from.id, msgs[ctx.message.text])}`
`		else { return ctx.telegram.sendCopy(ctx.from.id, 'test') }`
`})`

`app.startPolling()`

msg.json file:`
`{`
`	"hi": "hello"`
`	"/start": "hello"`
`}`

**Comment by Amirhz9479** [comment]
Thanks, my problem has been resolved
