### ISSUE TITLE
How does one scale a bot horizontally? 

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#207]
Is it possible to allow multiple instances of the bot to be hosted to scale it horizontally? Like using PM2 to make a cluster of instances to distribute the load? 

Or would it cause a conflict in the long polling?

**Comment by dotcypress** [comment]
To scale a bot horizontally you can use any dedicated http server for receiving webhook, and then just call `handleUpdate` or `webhookCallback` on bot instance.

See #197

**Comment by hammadzz** [comment]
@joshuaquek I am deploying it on AWS lambda and it autoscales horizontally infinitely. Contact me on telegram for help, you can PM me to get you my telegram username.
