### ISSUE TITLE
/command@bot_name not work

### ISSUE THREAD

**Issue by ptkdev** [telegraf/telegraf#208]
I have problem with function of telegraf:

> command()

Example: `bot.command('test', (ctx) => ctx.reply('ok'));`

If i write `/test` in group my bot response "ok"
But if i click on suggestion `/test@bot_name` my bot not response

What is wrong? `command` and `hears` are alias? 
P.s. I setcommand with botfather.

**Comment by dotcypress** [comment]
Hey @ptkdev!

For handling group/supergroup commands(/start@your_bot) you need to provide bot username.

```js
// Provide with options
const app = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})

// Or you can get username from Telegram server
const app = new Telegraf(process.env.BOT_TOKEN)

app.telegram.getMe().then((botInfo) => {
  app.options.username = botInfo.username
})

app.command('test', (ctx) => ctx.reply('ok'))
```

[Command handling in group](http://telegraf.js.org/advanced.html)

**Comment by ptkdev** [comment]
Great! Thanks work :)
