### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by dotcypress** [telegraf/telegraf#211]
Nice to have:

- [ ] More examples
- [ ] Stages/Scenes(ex telegraf-flow) advanced usage
- [ ] Extending Telegraf aka implementing middleware
- [ ] Composer magic explained
- [ ] Webhooks. Make requests in response to update stuff
- [ ] API docs for
  - [ ] Markup
  - [ ] Extra
  - [ ] Composer
  - [ ] Router
  - [ ] Stage
  - [ ] Session

**Comment by Piterden** [comment]
#247

**Comment by Piterden** [comment]
Want to add ES6 import style to all short examples.
Like here https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L13

**Comment by Piterden** [comment]
I don't want to create another one issue. It's about docs.

```js
bot.use((ctx, next) => {
  console.log(Object.keys(ctx).map(p => typeof ctx[p] !== 'function' ? p : false).filter(p => p))
  const start = new Date()
  return next(ctx).then(() => {
    console.log(`Response time ${(new Date()) - start}ms`)
  })
})
```

That log shows me 6 options:

- 'tg'
- 'update'
- 'options'
- 'updateType'
- 'updateSubTypes'
- 'contextState'

Docs don't have them

**Comment by ilyaigpetrov** [comment]
It's not clear from the docs that `ctx.getChatMember` shortcut must be called not with `(chatId, userId)` args, but only with `(userId)`.
I've stumbled on error and only figured this by reading the sources.

**Comment by Piterden** [comment]
`ctx.tg.getChatMember(chatId, userId)`
Reading sources is good.
