### ISSUE TITLE
switchToChatButton is callback being called before it's pressed

### ISSUE THREAD

**Issue by mateuswetah** [telegraf/telegraf#214]
Hi there!

I have the following routine:

1. Chat with other user, invokes bot's inline query with a `switch_pm` button, when pressed goes to PM with bot.
2. Bot offers option with `inlineKeyboard`, all options should be buttons with a `switch_inline_query` option, which would then move user back to previous chat, having the query inserted.

I couldn't find much details about using `switch_inline_query` , so I took a look at `Markup` code and implemented something like this:

```
// Start command
bot.command('start', (ctx) => {

  if(ctx.state.command.args[0] == 'from_inline') {

    const menu = Extra.markdown().markup((m) => m.inlineKeyboard(
      [		[ m.switchToChatButton('📄 Item1', 'item1 '),
		  m.switchToChatButton('👤 Item2', 'item2 ')  ],
	        [ m.switchToChatButton('💵 Item3', 'item3 '),
		  m.switchToChatButton('📦 Item4', 'item4  ')  ]
	]))

      ctx.reply('Hi there!. It looks that you want to change some options. Peek one:', menu)

  } else {
    ctx.reply('Welcome!.')
  }
})

// Inline query
bot.on('inline_query', async ({ inlineQuery, answerInlineQuery }) => {
       ... // inline query stuff
return answerInlineQuery(results, {next_offset: offset + 10, switch_pm_text: 'Choose search options.', switch_pm_parameter: 'from_inline'})
})
```
I was hoping that this would work, but oddly it's redirecting back to my previous conversation even before I click on any button, and passing the first argument (item1). If I enter the chat with bot and try to press one of the buttons tough, it does offers me the list of chats.

**Comment by shmuft** [comment]
I have that problem too. Do you have finded a solution of this problem?

**Comment by mateuswetah** [comment]
Actually no @shmuft, tried here and still have the same problem on the latest version :/

**Comment by Piterden** [comment]
I have inline keyboard like this:
```js
    ctx.replyWithPhoto(
      { url: getFileURL(filePath) },
      Markup
        .inlineKeyboard([
          Markup.callbackButton('Apply theme', `/apply/${theme}`),
        ])
        .removeKeyboard()
        .extra()
    )
```
all work fine for me...

**Comment by shmuft** [comment]
I try to run this code:
```
buttons.push(Markup.switchToChatButton("Back ", "ok"));
ctx.reply("back text", Markup
    .inlineKeyboard(buttons)
    .removeKeyboard()
    .extra());
```
But it's redirecting back to my previous conversation even before I click on any button. May be I do something wrong?

**Comment by Piterden** [comment]
Try not to push that button ))))))) :joy:

**Comment by shmuft** [comment]
Well, you do callback button and reply with photo. And it is working. But if you try to do a code from first comment you will find a problem. And it's not funny.

**Comment by dotcypress** [comment]
@shmuft you need to make 2 separated calls: one for `removeKeyboard`, and second for `inlineKeyboard`

**Comment by shmuft** [comment]
@dotcypress Thank you

**Comment by Piterden** [comment]
Sorry for the joke, dude

**Comment by swampfast** [comment]
Lot of time passed but the same problems.. =((
After press on button :'Text on button'  in inline mode with set switch_pm_... parameters I successfully switch to a private chat.
Code for inline mode button :
```
ctx.answerInlineQuery(
  [{ 
    type: 'article', 
    id: 'id',
    title: 'title',
    input_message_content: {'message_text':'input message content'},
  }],
  {switch_pm_text:'Text on button',switch_pm_parameter:'pm_parameter'}
);
```
But after send message with keyboard to private chat (by bot)
Code for this: 
```
ctx.reply("back text", Markup
    .inlineKeyboard([Markup.switchToChatButton("Back ", "ok")])
    .extra()
    );  
```
user immediately return into group conversation. But i want to give to user possibility press on button and switch to group conversation only after that.
If I manually return into the private chat with bot after that and try to press button, it does offers me the list of chats. 

Why addition switchToChatButton into keyboard button set switch conversation itself?
Can anybody help me to resolve this problem?
