### ISSUE TITLE
Can not catch error 409

### ISSUE THREAD

**Issue by nshtg** [telegraf/telegraf#215]
For the past hour I tried to handle the error 409 that is thrown if the token is already in use somewhere else. I tried try/catch and your recommend snippet:

```coffee
bot = new Telegraf token

bot.catch (err) ->
  console.error '\n---- ERROR telegram bot:\n'
  console.error err
  bot.stop()
```

The idea is to just stop the bot when the token is already in use.

However the function is never called and the error keeps being rethrown.

```
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description: 'Conflict: terminated by other long poll or webhook' },
  description: 'Conflict: terminated by other long poll or webhook',
  parameters: {} }
```

**Comment by dotcypress** [comment]
Hey @nshtg 

Actually, that recommend snippet used to handle only bot pipeline errors, not polling ones.
Long polling stopped only after explicit call to `stop` function, cause sometimes Telegram server are down for moments, and Telegraf need to handle that.

Anyway, I'll think about this use case with 409 error.

**Comment by nshtg** [comment]
As an idea, you could make the startPolling function return a promise that gets rejected if the token is already in use?

**Comment by dotcypress** [comment]
From next version, long-polling will automatically stop on conflict(`401`, `409`)
