### ISSUE TITLE
Group commands should be enabled in all chats

### ISSUE THREAD

**Issue by Vlad-Zhukov** [telegraf/telegraf#22]
For example I chat with a bot called TestBot. If I type ```/start@randomstring``` the bot defines it as ```/start``` and works fine, but when I type ```/start@TestBot``` it doesn't work.

**Comment by dotcypress** [comment]
Hey.

For handling group commands (/start@TestBot) you need to provide bot username.

```js
// Provide with options
const app = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})

// Or you can get username from Telegram server
const app = new Telegraf(process.env.BOT_TOKEN)

app.telegram.getMe().then((botInfo) => {
  app.options.username = botInfo.username
})

app.command('start', (ctx) => ctx.reply('Hello World'))
```

http://telegraf.js.org/advanced.html#command-handling-in-group

**Comment by Vlad-Zhukov** [comment]
I know, it does work it groups butdoes not in private chats.

See [composer.js](https://github.com/telegraf/telegraf/blob/develop/lib/core/composer.js), line 134.
```js
const groupCommands = ctx.me && (ctx.chat.type === 'group' || ctx.chat.type === 'supergroup')
        ? commands.map((command) => `${command}@${ctx.me}`)
        : []
```

**Comment by dotcypress** [comment]
But you already in private chat with bot, you don't need to specify bot name.

**Comment by Vlad-Zhukov** [comment]
Yes but if Telegram supports it I don't see a reason why Telegraf shouldn't.

**Comment by dotcypress** [comment]
Cause this doesn't make any sense. 😃 

But i'm fine with changes, if you need this feature - feel free to make PR.
