### ISSUE TITLE
List of dynamic ids as commands

### ISSUE THREAD

**Issue by hammadzz** [telegraf/telegraf#220]
I want to give the user a list of commands in a reply message for them to select. This will be dynamic depending on an in-line keyboard used for paginating the edit of a message. I can't possibly ad each and every option as bot.command()

/341 option 1
/132 option 2
/912 option 3

**Comment by dotcypress** [comment]
Actually you can handle all command in 1 handler:

```js
bot.command((ctx) => {
  console.log('command',ctx.message.text)
 // Dynamic command handling
})
```

**Comment by hammadzz** [comment]
I ended up doing a bot.hears with regex. I saw that in an example. Wouldn't that one command handler conflict with other commands by intercepting all of them?

Or does it have to be added after all other command handlers?

**Comment by bostrot** [comment]
It's been a while since I used it but if you don't break your code you can simply add a if-statement to handle it.
