### ISSUE TITLE
How to leave() from WizardScene?

### ISSUE THREAD

**Issue by dobeerman** [telegraf/telegraf#221]
I tried `bot.command("cancel", leave());`, `wizardName.command` and `.action`. No action, just errors in console.

**Comment by dotcypress** [comment]
The main idea around wizard is calling handler sequentially.
You can achieve the same functionality with a bunch of `BaseScene`, but with `WizardScene` it's easier.

So, if user currently in wizard, we have only one way to leave: call `ctx.stage.leave()` inside handler:
```js
const superWizard = new WizardScene('super-wizard',
  (ctx) => {
    ctx.reply('Step 1')
    ctx.wizard.next()
  },
  (ctx) => {
    if (ctx.message.text === 'yay') {
      ctx.stage.leave()
    }
  },
  (ctx) => {
    ctx.reply('Done')
    ctx.scene.leave()
  }
)
```

**Comment by dobeerman** [comment]
By your solution I should to add this logic to each step. In the telegraf-flow it was just one middleware.

**Comment by dotcypress** [comment]
[`leave` factory](https://github.com/telegraf/telegraf/blob/develop/stage.js#L45-L47) is tiny wrapper around `ctx.scene.leave()`

**Comment by dobeerman** [comment]
I've a more than 20 steps in my wizard. I think it's a not good idea to add this logic to each one.

**Comment by dotcypress** [comment]
@dobeerman from next version, `WizardScene` will be compatible with `Composer`

Thank you for your time 👍
