### ISSUE TITLE
How to upload big document?

### ISSUE THREAD

**Issue by npyramid** [telegraf/telegraf#222]
Hello. If i use instance.telegram.sendDocument,
telegram response like this

    <html>\\r\\n<head><title>413 Request Entity Too Large</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>413 Request Entity Too Large</h1></center>\\r\\n<hr><center>nginx/1.10.0</center>\\r\\n</body>\\r\\n</html>

How i can resolve this?

**Comment by dotcypress** [comment]
Hey @npyramid 

Unfortunately, bots can send files of [up to 50 MB in size](https://core.telegram.org/bots/api#senddocument), this limit may be changed in the future.

**Comment by npyramid** [comment]
upload file of 25mb. same error
