### ISSUE TITLE
photo albums

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#225]
https://telegram.org/blog/albums-saved-messages

is it possible to have bots create albums?
I couldn't find it in the bot api page

https://core.telegram.org/bots/api#sendphoto

**Comment by dotcypress** [comment]
Next update will introduce brand new method `sendMediaGroup`, and I believe Telegram will be roll out bot api update soon.

**Comment by paOol** [comment]
https://core.telegram.org/bots/api-changelog#november-17-2017

**Comment by dotcypress** [comment]
`sendMediaGroup` published as part of `telegraf@3.16.0`

**Comment by Xaz16** [comment]
Hi guys

@dotcypress 
Can you check this example?
https://stackblitz.com/edit/typescript-y2m1hw?file=index.ts

It looks like there are not any `sendMediaGroup`.

`"telegraf": "^3.24.1"`
