### ISSUE TITLE
Koa compatible middleware

### ISSUE THREAD

**Issue by mahnunchik** [telegraf/telegraf#226]
Hi,

Are you planning to implement [koa](https://www.npmjs.com/package/koa) v2 compatible middleware?

**Comment by dotcypress** [comment]
Hey,

You can do it right now:
```js
const Koa = require('koa')
const app = new Koa()

const bot = new Telegraf(token)
app.use(bot.webhookCallback(token))
bot.on('message', (ctx) => ctx.reply('Hey'))
bot.setWebhook('https://...../token')

app.listen(3000)
```

**Comment by mahnunchik** [comment]
First, I've faced with the following error:
```js
TypeError: bot.setWebhook is not a function
```

There is mistake in documentation too: 
```js
bot.setWebhook('https://server.tld:8443/secret-path')
```

Second, I think that signatures is not compatable between `express` and `koa`:

```
TypeError: res.end is not a function
      at /test-telegram/node_modules/telegraf/core/network/webhook.js:10:18
      at dispatch (/test-telegram/node_modules/koa-compose/index.js:42:32)
      at /test-telegram/node_modules/koa-compose/index.js:34:12
      at Application.handleRequest (/test-telegram/node_modules/koa/lib/application.js:150:12)
      at Server.handleRequest (/test-telegram/node_modules/koa/lib/application.js:132:19)
      at emitTwo (events.js:126:13)
      at Server.emit (events.js:214:7)
      at parserOnIncoming (_http_server.js:602:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
```
Source: https://github.com/telegraf/telegraf/blob/develop/core/network/webhook.js#L4

As I know `koa` uses `ctx` and `next` arguments.

**Comment by dotcypress** [comment]
@mahnunchik got it, will write Koa example soon.

**Comment by dotcypress** [comment]
koa integration example has been added to `docs/examples`

**Comment by polRk** [comment]
TypeScript error 
app.use(ctx => bot.handleUpdate(ctx.request.body, ctx.response))

ctx.response 

Response is not assignable to ServerResponse

**Comment by azat-io** [comment]
> Response is not assignable to ServerResponse

Use `ctx.res` instead of `ctx.response`
