### ISSUE TITLE
How to send both caption and inline keyboard with photo?

### ISSUE THREAD

**Issue by mahnunchik** [telegraf/telegraf#228]
How to send both caption and inline keyboard with photo?

**Comment by dotcypress** [comment]
@mahnunchik  Just add `caption` value to extra parameters:

```js
bot.command('foo', (ctx) => {
  const extra = Extra.markup(Markup.inlineKeyboard([
    Markup.urlButton('❤️', 'http://telegraf.js.org')
  ]))
  extra.caption = 'Caption text here'
  return ctx.replyWithPhoto('http://lorempixel.com/400/200/cats/', extra)
})
```

**Comment by lamuertepeluda** [comment]
This is so outdated! 😞  I wonder how much difficult is to have a proper documentation for Markup and Extra...

**Comment by yauhenipakala** [comment]
https://github.com/telegraf/telegraf/blob/4cef44e16babe590dd62d8da9913bae7abfbbced/docs/examples/keyboard-bot.js#L83-L92
