### ISSUE TITLE
Problem with session save on scene enter handler

### ISSUE THREAD

**Issue by seniv** [telegraf/telegraf#235]
I have this code:
```
scene.command('test', ctx => {
  return ctx.reply('text').then(res => ctx.session.messageId = res.message_id)
})
```
and he perfectly send message and then save to session id of sended message
But if i use the same code in scene enter handler
```
scene.enter((ctx) => {
  return ctx.reply('text').then(res => ctx.session.messageId = res.message_id)
})
```
message has ben sended, but session not be saved

What is wrong?
Telegraf version 3.16.3
Used my own mongodb sessions, based on last version of telegraf-session-redis

**Comment by dotcypress** [comment]
@seniv could you try to reproduce this with memory session? `require('telegraf/session')`

**Comment by seniv** [comment]
@dotcypress yes, i'm tried memory session.
I added debug after session is getted from Map and before saved to Map, and get the same result as in my mongo session.
Session saved before i set messageId
![image](https://user-images.githubusercontent.com/18112951/33125742-64a04824-cf8a-11e7-8323-68bb66d88e0f.png)
```
scene.enter(ctx => {
  console.log('enter to scene')
  ctx.session.beSaved = '123'
  return ctx.reply('text').then(res => {
    console.log('save message id', res.message_id)
    return ctx.session.messageId = res.message_id
  })
})
```
My session files https://gist.github.com/seniv/0dec97b89530dd52bd452692295b83ba

**Comment by seniv** [comment]
Problem was that I didn't return enter to scene call in another scene. Woops..
