### ISSUE TITLE
BUG: v3.16.x is not working on Cloudno.de

### ISSUE THREAD

**Issue by dalisoft** [telegraf/telegraf#239]
Hi @dotcypress 
Thanks for framework and it's really make things easier and faster. But it not works latest ver on Cloudno.de, so old version is working great (my working ver `3.6.7`).
Thanks

**Comment by dotcypress** [comment]
Hey @dalisoft 

Could you provide more information(code example/log output)?

**Comment by dalisoft** [comment]
Log doesn't provide any erros.
Local nodejs execution works fine (long-poll).
Server web-hooks says working, but it doesn't do anything, just like `return false` in JS

**Comment by dalisoft** [comment]
I now relaized, if on the server nodejs package.json `private:true`, free account can't execute. Sorry for falsely log
