### ISSUE TITLE
Detecting of stop polling when error in handleUpdates

### ISSUE THREAD

**Issue by PsiXdev** [telegraf/telegraf#241]
Hi, I came across a situation where polling was stopped due to an error in the this.handleUpdates:
```
fetchUpdates () {
      ...
      .then((updates) => {
        throw new Error('Example error'); // For test
        return this.handleUpdates(updates).then(() => updates)
      })
      .catch((err) => {
        console.error('Failed to process updates.', err)
        this.polling.started = false
        this.polling.offset = 0
        return []
      })
      ...
}
```
If an error occurs, it is logged, the polling stops and the bot stops working. And I do not know how to detect this error in order to try to resume the polling or restart the server.
The real error that I had was: `error 409: Conflict: terminated by other long poll or webhook` and I could not process it. Are there any ways to handle such errors?

**Comment by bostrot** [comment]
Try to remove 

> return []

Or use an external "program" to detect wether your service stopped and then restarts it. I made a repo a while ago. You can look in it if you want.

**Comment by PsiXdev** [comment]
@bostrot If I remove `return []`,  then there will be an error "Cannot read property 'length' of undefined" in next `then`.

The use of additional state tracking is an extreme measure, I would just like to track the occurrence of an error in current app.

**Comment by dotcypress** [comment]
Actually you can change [error handling flow](http://telegraf.js.org/#/?id=error-handling)

**Comment by PsiXdev** [comment]
@dotcypress How? The error is not passed to `bot.catch`, it's just put out  inside the library

**Comment by dotcypress** [comment]
Yes, `bot.catch` wraps processing pipeline, not network errors.
I think we can implement something like a `bot stopped callback` for handle this.

PR highly welcome.

**Comment by PsiXdev** [comment]
I also like the idea with `bot stopped callback`. Unfortunately, I'm not sure I can find enough time in the near future. Maybe someone else can help, or I'll try to tackle the problem a little later.

**Comment by PsiXdev** [comment]
Cool, it seems that your fix works as it should. I was able to catch the stop of the polling and start it:
```
Failed to process updates. { Error: 409: Conflict: terminated by other long poll or webhook ..... }
[info] bot polling stopped
[info] start bot polling
```
Thank you. When can I expect the release of a new version with this fix? The task can be closed?

**Comment by dotcypress** [comment]
@PsiXdev new release will be available in ~10-15 hours
