### ISSUE TITLE
TypeError: Cannot read property 'audio' of undefined

### ISSUE THREAD

**Issue by yianni-ververis** [telegraf/telegraf#242]
at Object.keys.find (D:\development\server4\node_modules\telegraf\telegram.js:364:77)

here  is my scene
/*************
 * SALESFORCE
 *************/
// BUTTONS
const keyboardSalesforce = Markup.inlineKeyboard([
	Markup.urlButton('❤️', 'https://webapps.qlik.com/salesforce/index.html'),
	Markup.callbackButton('Dashboard', 'salesforceDashboard'),
	Markup.callbackButton('Opportunities', 'salesforceOpportunities')
])
// SCENE
const salesforceScene = new Scene('salesforce')
salesforceScene.enter((ctx) => {
	console.log(2)
	site.logger.info(`salesforce-main`, {route: `api/sense-bot/telegram`});
	ctx.reply('Welcome to Salesforce')
	ctx.telegram.sendCopy(ctx.from.id, ctx.message, Extra.markup(keyboardSalesforce))
})
salesforceScene.leave((ctx) => ctx.reply('Bye'))

**Comment by dotcypress** [comment]
@yianni-ververis thank you for report.

Fix will be shipped in next release.

As quick fix you can add additional check for `message`:
```js
ctx.reply('Welcome to Salesforce')
if (ctx.message) {
  ctx.telegram.sendCopy(ctx.from.id, ctx.message, Extra.markup(keyboardSalesforce))
}
```
