### ISSUE TITLE
how can we update commands realtime

### ISSUE THREAD

**Issue by MAmin233** [telegraf/telegraf#246]
i need to read commands from database and the data can be change while the bot is running 
for example 
app.hear(  readString.FromDataBase() , function( ctx ) {
     // do something
});
the function `readString.FromDataBase()` can return different value on different time but  the `hear` call it for one time on start... 
how can i do this work? 

readString.FromDataBase() ==> it is asynchronous function

**Comment by MAmin233** [comment]
by the way
i don't want to use ` bot.on( 'message', callback )  `

**Comment by dotcypress** [comment]
[Example of dynamic routing](https://github.com/telegraf/telegraf/issues/202#issuecomment-340920583)

**Comment by MAmin233** [comment]
my function is asynchronous function 
it doesn't work for async functions 
@dotcypress

**Comment by dotcypress** [comment]
In your scenario `bot.on('text')` will works better, but if you want some fancy way:

```js
const { lazy, hears } = require('telegraf/composer')

bot.on('text', lazy(() => readString.FromDataBase().then((someValue) => hears(someValue, (ctx) => {
  // Actual handler
})))

// Async example
bot.on('text', lazy(async () => {
  const someValue = await readString.FromDataBase()
  return hears(someValue, (ctx) => {
    // Actual handler
  })
))
```

**Comment by zealotrahl** [comment]
I am meeting the same problem, pls help me to find what I am doing wrong.
In scene, on enter I am getting data from database, then I'm puting hears on every item in loop(scene.on doen't work at all). If i change data in database, and enter scene again, i can see changed data in console, but bot still send old data, only restart helps.

`productsList.forEach((el) => {
	products.hears(el.title, updateUserTimestamp, (ctx) => {
		ctx.replyWithHTML("<b>"+el.title+"&#13;&#10;</b>"+el.desc");
	});
})`
