### ISSUE TITLE
Multiple check on same message

### ISSUE THREAD

**Issue by 96Octavian** [telegraf/telegraf#25]
Hi, sorry if it is a dumb question. How would I check if a single message is both a message and (for example) a command?
I want to do something like this
`app.on('message', ctx => console.log("It's a message"));
app.command('start', ctx => console.log("And a command too"));`
but it only execute wichever I wrote first. 
The reason is because I want it to execute a function on every input the bot receives, and then another specific to the type of the input

**Comment by dotcypress** [comment]
Hey.

You might need to [execute the downstream middleware](http://telegraf.js.org/introduction.html#middleware), see example below:

```js
app.on('message', (ctx, next) => {
  console.log("It's a message")
  return next(ctx)
}) 
app.command('start', ctx => console.log("And a command too"))
```

**Comment by 96Octavian** [comment]
Great thanks I get it now
