### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by Piterden** [telegraf/telegraf#250]
https://github.com/telegraf/telegraf/blob/2ed775a5cb8b7c8b85ba304829e02d88bf2bed64/markup.js#L149-L151

As I see, if at least one element of buttons array is array, we do nothing excepting filtering?

```js
let buttons = [[], 1, 's']
```
And this should throws an exception ^

**Comment by dalisoft** [comment]
@Piterden, what should throw an exception? The @telegraf uses ES6 syntax and code you quoted is valid.
Please let us know more by writing more clear, where (closer or that line in code, reference to code) it should throw?

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/33713308-cb27a09c-db5b-11e7-8afa-c8e85f230723.png)

**Comment by dalisoft** [comment]
There bug should in Chrome, as condition happens, when `buttons` child is `Array`.
Please try to not use Arrays close `string` and `number` if possible. (Sorry for this)

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/33714751-1f4a098a-db61-11e7-8f36-cdd0a2809f76.png)

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/33714841-8306c63e-db61-11e7-9f94-d7f7dabbf8bf.png)

**Comment by dalisoft** [comment]
I'm not understand what you want achieve and what you except?
I'm using this library almost year, there some only few issues i'm faced, but fixed by alternative solution.

**Comment by Piterden** [comment]
I don't understand what happens there. If at least one element is array it is doing map. But what if there would be `[[{},{}],[{},{}],{}]`?

**Comment by Piterden** [comment]
> Note: [].filter only for Arrays

```js
Object.keys(obj).find()
Object.keys(obj).filter()
```

**Comment by dalisoft** [comment]
> Object.keys(obj).find()
Object.keys(obj).filter()

When you called `Object.keys`, object converted to object keys, mean `Array`

**Comment by dalisoft** [comment]
> I don't understand what happens there. If at least one element is array it is doing map. But what if there would be [[{},{}],[{},{}],{}]?

I'm too
