### ISSUE TITLE
editMessageText edits inline keyboard, but editMessageReplyMarkup doesn't

### ISSUE THREAD

**Issue by sovtara** [telegraf/telegraf#252]
Hello.
My question is about `editMessageReplyMarkup` function. 
After running `editMessageReplyMarkup` for a message with inline-keyboard, the inline-keyboard disappears. 
```
ctx.editMessageReplyMarkup(
    {
        reply_markup:{
            inline_keyboard:[[{text:'new button', callback_data:'callback_data'}]]
        }
    }
)
```
At the same time `editMessageText` with the same reply_markup edits inline keyboard as I expected.
```
ctx.editMessageText(
    'Some text', 
    {
        reply_markup:{
            inline_keyboard:[[{text:'new button', callback_data:'callback_data'}]]
        }
    }
)
```
What am I doing wrong while editing message reply markup with editMessageReplyMarkup, so the inline-keyboard goes away?

**Comment by Piterden** [comment]
Maybe you would try to set "not to remove keyboard" directly?

**Comment by dotcypress** [comment]
It's happens because you call it with wrong argument, try following:
```js
ctx.editMessageReplyMarkup(
    { inline_keyboard:[[{text:'new button', callback_data:'callback_data'}]]  }
)
```

**Comment by sovtara** [comment]
Thank you, **dotcypress**. @Now it's clear.
