### ISSUE TITLE
Bad Request: can't parse entities in message text: Expected end tag

### ISSUE THREAD

**Issue by bodyajoy** [telegraf/telegraf#253]
```
<b>Вы</b><i> <i> Прочитано</i>
<i>Пустое сообщение</i>
<i>1</i> ?
 /message_1699888
-----------
```

(node:4796) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: 400: Bad Request: can't parse entities in message text: Expe
cted end tag at byte offset 15
(node:4796) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by Piterden** [comment]
I think, you call it wrong

**Comment by bodyajoy** [comment]
That works good, but when there are emoji from another social network - sometimes crashes

Some times - emoji works well, somtimes not

**Comment by Piterden** [comment]
I tried on my machine, all good, I have:
```html
<b>Покажите же, наконец, как вы делаете вызов.</b>
```

**Comment by bodyajoy** [comment]
`ctx.editMessageText(text, Extra.HTML().webPreview(false).markup((m) =>
				m.inlineKeyboard([keys_next_prev, answer_read, key_return])
			));`

**Comment by Piterden** [comment]
А вызывается ли он, когда нечего редактировать?

**Comment by bodyajoy** [comment]
Он выдает ошибку даже в первый свой раз срабатывания. Например, есть массив кнопок, и по нажатию на одну из них выдаются сообщения (изменяется сообщение с кнопками). И когда встречаются некоторые эмодзи (хотя в телеграме они и есть, и по одному я могу их отправить, и все норм) выкидывает ошибку эту

**Comment by bodyajoy** [comment]
Все, я увидел ошибку. Нет одного закрывающего тега.
Извини за потраченное время на этот пустяк.
Можно закрывать

Если есть возможность , ответь на следующий мой вопрос в теме, он интереснее
