### ISSUE TITLE
Pooling drops

### ISSUE THREAD

**Issue by bodyajoy** [telegraf/telegraf#254]
example:

```
authScene.on('message', async (ctx) => {
   main.bot.telegram.sendChatAction(ctx.from.id, 'typing');
   await user.passingAuth();
}
```
passingAuth() - wait for entering new data(entering captcha from user)

but pooling drops and no new messages come...

**Comment by Piterden** [comment]
`user.passingAuth()` is the action, and not a listener. `await` is the same like `sync`

**Comment by bodyajoy** [comment]
Там библиотека построена так, что этот passingAuth() проходит авторизацию в ВК, и если будет капча, оно не закончит своё выполнение (а будет висеть в памяти) и ждёт, когда вызовется функция retry(captcha)
И, получается, что происходит ожидание вызова функции retry(), и дальнейшая обработка сообщений в телеграме не происходит..

**Comment by Piterden** [comment]
So, don't write `await user.passingAuth();`

**Comment by bodyajoy** [comment]
Если я не напишу, выдает ошибку
Я могу скинуть эту библиотеку. Это vk-io 4.0.4 alfa, я общался с разрабом, он сказал, что без await это не делается

**Comment by Piterden** [comment]
Take the release version of something, and don't fix brains everybody around.

**Comment by bodyajoy** [comment]
https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/auth.md

Implicit flow потребует капчу, и вызовется обработчик капчи. И все это будет висеть, пока я не вызову метод retry(captcha) от обработчика типа с введением кода

**Comment by dotcypress** [comment]
Привет

Поллинг останавливается, потому что все сообщения обрабатываются последовательно.
Самое простое что можно сделать, это не ждать выполнение `user.passingAuth()`, например:

```js
authScene.on('message', async (ctx) => {
   main.bot.telegram.sendChatAction(ctx.from.id, 'typing');
   user.passingAuth().then(x => ...);
}

```
 или так
```js
const { fork } = require('telegraf/composer')
authScene.on('message', fork(async (ctx) => {
   main.bot.telegram.sendChatAction(ctx.from.id, 'typing');
   await user.passingAuth();
})
```

**Comment by bodyajoy** [comment]
Спасибо тебе большое, помогло!

А какая разница между await и then()?

**Comment by Piterden** [comment]
Then принимает параметром функцию, которая должна быть выполнена асинхронно. То же самое делает и async, а await указывает, какие выражения, внутри асинхронной функции, выполнять синхронно.

**Comment by bodyajoy** [comment]
Спасибо большое
