### ISSUE TITLE
Intellect feature (maybe Cortana, AI)

### ISSUE THREAD

**Issue by dalisoft** [telegraf/telegraf#257]
Hi @dotcypress 
I amazed your work and already build more than 5 bots, very easy.
I now think about intellectual chatting with peoples, rather than static bots.

Maybe you can port Cortana.

Examples how it should look:
```
# user: /start
# bot: Hello ${name}, how are you?
# user: ok, order me pizza
# bot: i'm happy for you, i can search closest pizza center for you, if i find send them order for you?
# user: yes
# bot: ${name}, i ordered pizza for you, shipped to your home in 5minutes or at 5:15pm
# bot: Thanks for contacted to me, if any help requires tell me, i'm would be happy to help you
# user: ok, i can fly to Malaysia?
# bot: Yes, you can at Tomorrow, at 6:00pm
.... so-on
```

This can be done via static bot coding but intellect would be much better

**Comment by dotcypress** [comment]
@dalisoft you can use following extensions to add some `intellectual` abilities to bot:

* [telegraf-wit](https://github.com/telegraf/telegraf-wit)
* [telegraf-recast](https://github.com/telegraf/telegraf-recast)

**Comment by dalisoft** [comment]
Thanks, amazing. You best developer @dotcypress

**Comment by Piterden** [comment]
Try madelineproto also...

**Comment by dalisoft** [comment]
Madelineproto isn't intellect, an PHP implementation of MTProto as i'm seen. Thanks anyway
