### ISSUE TITLE
How to make wizard after some action/command/hears?

### ISSUE THREAD

**Issue by dalisoft** [telegraf/telegraf#264]
Hi @dotcypress 
Thanks again for library, it's super-easy and fast.

Demo Wizard demo works nice, but i want trigger wizard after some action/command/hears.

Here i describe.

1. User clicks to `Order subscribers`
EDIT: Wizard should start at 2 step
2. Reply to user how much subscribe requires? (keyboard removes)
3. Users send/reply anything
4. Receive  value only from that sub-menu, without affecting to other hears,commands,etc. (because others should have other thing)
5. Then users pay for subscribe (inline button with URL) (not requires, i do this)
6. Opens window Internet (not requires, i do this)
7. User closes window (not requires, i do this)
8. Checking payment, if success send to user `DONE/FAIL` (not requires, i do this)
9. Wizard done...

It's possible?

**Comment by dalisoft** [comment]
Scene, Stage there and i did, but there anyway issue with keyboard within scene/stage

**Comment by R-iskey** [comment]
Hi @dalisoft , can you give me some example please?

**Comment by dalisoft** [comment]
https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js

**Comment by Y1a2s3h4** [comment]
> https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js

404 not found

**Comment by MKRhere** [comment]
It's in the new docs repo now:
https://github.com/feathers-studio/telegraf-docs/blob/master/examples/scenes/scenes.ts
