### ISSUE TITLE
send by order

### ISSUE THREAD

**Issue by ali-bagheri** [telegraf/telegraf#267]
Hi.
what i send my msg ordered but i get inordered.

my code:

    ```
var msgReplays = [10];

    for(var i=0; i<10; i++)
	    {
		msgReplays[i] = i;
	    }

    for(var i=0; i<count; i++)
	    {
		ctx.reply(msgReplays[i]);
	    }
```

but in device i get inordered msg:
5
7
1
2
4
.
.

please get me a solution.
.

**Comment by Piterden** [comment]
```js
new Array(10).fill().forEach((el, idx) => ctx.reply(idx))
```

**Comment by dotcypress** [comment]
Hey @ali-bagheri 

To send messages sequentially see [related issue](https://github.com/telegraf/telegraf/issues/80)

**Comment by ali-bagheri** [comment]
Tanks Piterden,
your code not true answer, but very much help to me,

listarray.forEach((el, idx) => setTimeout(function() { ctx.reply(listarray[idx], arg[idx]); }, 140 + (idx*190)));
