### ISSUE TITLE
how get some section of hears text?

### ISSUE THREAD

**Issue by ali-bagheri** [telegraf/telegraf#268]
Hi guys.
how I can get a section of hears text?

venusBot.hears(/year\s(\d\d\d\d)/, sendMyDateUsersInfo);

i want send (\d\d\d\d) to function.

**Comment by Piterden** [comment]
Read docs more detailed, man
https://github.com/telegraf/telegraf/blob/develop/docs/examples/example-bot.js#L55

**Comment by ali-bagheri** [comment]
Tanks .

I use this.

function fn(ctx)
{
var mat = ctx.match;
.
.
.
}

bot.hears(/\my rex/, fn);
