### ISSUE TITLE
Telegram rejects

### ISSUE THREAD

**Issue by H03in** [telegraf/telegraf#278]
when is use sendAudio, sendDocument , sendVideo..
telegram repond is :

**UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1)**

why??

**Comment by Piterden** [comment]
Try to send related chat action, before you send file.

**Comment by H03in** [comment]
Sorry!
that was stupid mistake from my self
please close this.

**Comment by Piterden** [comment]
It's really not obvious

**Comment by H03in** [comment]
no mistake wasn't that u said :)

**Comment by Piterden** [comment]
What do you mean?

**Comment by Piterden** [comment]
https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L238-L247

**Comment by Piterden** [comment]
Btw, it can be closed only by you or by the owner...
