### ISSUE TITLE
weird issue with emoji :heart:

### ISSUE THREAD

**Issue by ken-talkingsource** [telegraf/telegraf#279]
I saw other bots can display heart emoji normally.
<img width="133" alt="2017-12-20 4 49 00" src="https://user-images.githubusercontent.com/15817957/34198560-d5f61a40-e5a5-11e7-87ae-187c36b4a503.png">

But I sent string as uni-code (nodejs)
`return '\u{2665}';// heart`
or direct paste
`return '♥️';// heart`

It's always a black heart (or diamond)
<img width="82" alt="2017-12-20 4 49 50" src="https://user-images.githubusercontent.com/15817957/34198570-daff4d2c-e5a5-11e7-9029-670bcd890154.png">

(Telegram Client on Android is fine, but on iOS is always black.)

Did I encode something wrong ?
How should I fix this?

thank you

**Comment by Piterden** [comment]
What a pity that Steve died. No one to ask.

**Comment by ken-talkingsource** [comment]
Finally, I know how to fix this up.
Don't send in unicode and don't copy symbols from Windows.
I copy symbols on a MacBookPro(use VS code) then both iOS and Android display color correctly.

**Comment by Piterden** [comment]
It turns out that this is not done without the Mac. I recognize the asshole Steve)))

**Comment by Piterden** [comment]
Btw, didn't you try to use backticks instead of normal quotes for this purpose?
