### ISSUE TITLE
WizardScene

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#280]
Hi guys, I have a question there... How can I send some variables between functions in SuperWizardScene? In first 3-4 function Bot collects some infromation from user inputs and at the end sends them back to user. Is there ways to send value to other functions like ctx.wizard.next(value) or smth like this.
Thanks in advance

**Comment by dotcypress** [comment]
Hey @JRakhimov 

You can store collected info in any session:
* `ctx.session` - user session
* `ctx.scene.session` - current scene session(automatically cleared on `leave`)

**Comment by JRakhimov** [comment]
Got it. It works. Thank you

**Comment by Piterden** [comment]
@JRakhimov rename it to *Share variables between scene functions*, please.

**Comment by KR1470R** [comment]
Tell me pls, how i can into ctx.message save array and push there data without reset him?
