### ISSUE TITLE
Handle user's live location

### ISSUE THREAD

**Issue by botguy123** [telegraf/telegraf#281]
I'm developing a bot that sends content based on user's location, but can't figure it out how to manage live locations sent by users.
I'm currently polling (no webhook) and using the .on("location") event, but I'm receiving only the initial location and not the updates.
Any advice? Thanks

**Comment by botguy123** [comment]
@Piterden Well thanks for the thumbs down, if it's such a dumb question could you take 5 seconds to answer it so I won't make another dumb question tomorrow? thanks

**Comment by Piterden** [comment]
It seems you wrote a wrong code. We are not magicians here.

**Comment by Piterden** [comment]
`.on("location")` shouldn't work, cause it hasn't a callback function passed to.

**Comment by botguy123** [comment]
@Piterden Thanks for answering.

```
bot.on('location', ({from, message}) => {
	var user = from.id;
	var location = message.location;
	console.log(user, location);
})

bot.startPolling();
```

This is what I'm using. The code is working fine and I'm receiving user's location correctly, the fact is that i'm not receiving any location update when the user sends a "live location" instead of a normal location.

**Comment by Piterden** [comment]
Unfortunately can't test it now
Try to check
```js
bot.on('location', (ctx) => {
  console.log(ctx.update)
})
```

**Comment by dotcypress** [comment]
@botguy123 to receive live location updates you need to handle `edited_message`:

```
bot.on('edited_message', (ctx) => {
  console.log(ctx.editedMessage.location)
})

**Comment by botguy123** [comment]
@dotcypress Thanks, works perfectly!

**Comment by ouya99** [comment]
Hi @botguy123 . How did you get it to work? Could you paste some code please. thanks!

**Comment by Piterden** [comment]
What about [this piece of code](https://github.com/telegraf/telegraf/issues/281#issuecomment-353732569) @ouya99 ? Doesn't it work for you?

**Comment by ouya99** [comment]
@Piterden There is no call to edited_message. Though I receive calls to bot.on(location .. ), but only for the 2nd time user presses keyboard ("Location").

`bot.on('location', (ctx) => {
  console.log(ctx.message)
})

bot.on('edited_message', (ctx) => {
  console.log(ctx.editedMessage.location)
})`
