### ISSUE TITLE
Plz anyone Clearify How to Reply With Photo with picture recived from sender?

### ISSUE THREAD

**Issue by ParsaGachkar** [telegraf/telegraf#283]
😖 Plz anyone Clarify How to Reply With Photo with picture recived from sender?
sry if this is a silly question i'm a newbie. 

here is the thing I'm trying to achieve:

1. get a Photo from user
2. add a caption to the photo and reply

OK, Correct me if I'm wrong! I need to store the photo and the caption first right? then i should forge a new PhotoMessage to reply with the caption i want. 

iv'e already gone through the Doc but i didn't Noticed a Clear way of doing this. if the ctx object and it's members where clear it would be a lot easier but it took me about 1 hour to figure out that if the message is a Photo the ctx will contain a Photo member, ahem with 2 photo childs i don't have any idea why?! ❓ 

I think i figured out how to set the caption for Photo add it as a member to Extras Object in JSON format just like telegram bot api Doc?

- OK, first Question How to save This Photo (The Original One)?
- Is There a way to help me save my time without Downloading media?

i'd really appreciate the help of community 🙇

**Comment by Piterden** [comment]
Check how these bots work
[Colorizer](https://github.com/telegraf/colorizer-bot)
[Syntax Highlighter](https://github.com/Piterden/syntax-highlighter-bot) [Bot](https://t.me/cris_highlight_bot)

**Comment by dalisoft** [comment]
```javascript
const app = new Telegraf(BOT_TOKEN)

app.on('photo', ({message, replyWithPhoto}) => replyWithPhoto(message.photo.pop().file_id, {caption:'Your caption here'})
```

It should work as you excepted, but not sure

**Comment by Piterden** [comment]
@dalisoft https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L101

**Comment by dalisoft** [comment]
@Piterden thanks for reply at all, but for my bot this way works as excepted, so i just share the working code snippet

**Comment by Piterden** [comment]
For my bot, it was not working without that line. I load a photo from a FS.

**Comment by dalisoft** [comment]
Yea, maybe. I try to not use hosting storage as possible and use Telegram hosting as possible, if you here i need your help

**Comment by dalisoft** [comment]
@Piterden 
1. How i can use Markdown in `Caption`?
2. How i can add `Share` button for forward message from bot with Inline Keyboard

Thanks for answer

**Comment by Piterden** [comment]
What you mean here? Write to t.me

**Comment by dalisoft** [comment]
> Yea, maybe. I try to not use hosting storage as possible and use Telegram hosting as possible, if you here i need your help

I mean when images uploaded to server, not call to self (hosting) from JS, so would be more free CPU, i using free hosting for Node.js, for me matters CPU free percent so i used this way
