### ISSUE TITLE
Say Hi / Hello

### ISSUE THREAD

**Issue by drow-ranger** [telegraf/telegraf#284]
How to make when i chat Hi and bot replied Hi $username / Hi $firstname ?
i use this command _**bot.hears('hi', (ctx) => ctx.reply('Hey there!'))**_.

And then how to make when i chat Hello and bot replied Hello.. Good Evening / Afternoon / etc  adjust the time of the bot server?

Pls  advice.. Thankyou.
Good work .. I am very helpful for your services!!

**Comment by dalisoft** [comment]
try this
```javascript
bot.hears('hi', ({ from: { username, first_name }, reply }) => reply(`Hi @${username} (${first_name})`)
```

**Comment by Piterden** [comment]
@drow-ranger , the physical location of a user not depends on your server's timezone, so it doesn't make any sense to do a calculation of a daytime on the server.

**Comment by drow-ranger** [comment]
@Piterden thank you for your answer. I laughed to read it. 
Well if that's not possible. I think we can refer to the timing of the message to be used as a benchmark of time as a greeting.


@dalisoft Thanks dude.. I am very helpful for your answer. I've implemented it:

> bot.hears('hi!', ({ from: { username, first_name, last_name }, reply }) => reply(`Hi ${first_name} ${last_name}. Your ID: @${username}`))

**Comment by Piterden** [comment]
Sorry for `man`, @drow-ranger )

**Comment by drow-ranger** [comment]
no problem @Piterden :)

Sorry one more, may I make Telegraph to send a random image?
i use this syntax: 

> bot.hears('pict', (ctx) => ctx.replyWithPhoto({ url: 'hhttp://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg' }))

I want to create some list of images and call them randomly when user sends a "pict" message.
 I am very helpful for your services!!

**Comment by Piterden** [comment]
Yes, you can do it with JS.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

You can get a random integer between zero and array length minus one.

**Comment by Piterden** [comment]
@drow-ranger you can join our chat, there are English speakers, almost everyone. https://t.me/telegraf_ru
