### ISSUE TITLE
audio file

### ISSUE THREAD

**Issue by archimedix** [telegraf/telegraf#29]
How to send an audio file?

**Comment by dotcypress** [comment]
Hey @archimedix.

You have couple of options to [send audio file](http://telegraf.js.org/telegram.html#sendaudio):
```js

bot.on('message', (ctx) => {
  ctx.telegram.sendAudio(chatId, 'https://server.tld/file.mp3')
  ctx.telegram.sendAudio(chatId, 'fileId')
  
  // Or you can use context shortcuts
  ctx.replyWithAudio('https://server.tld/file.mp3')
  ctx.replyWithAudio({url: 'https://server.tld/file.mp3'})
  ctx.replyWithAudio({content: new Buffer(...)})
})

```

**Comment by pladaria** [comment]
Is this documented? I can't find those details in doc

**Comment by theMasix** [comment]
I have same problem. where are those usages in Doc? Poor Documentation .... From where I can find that object  to pass in the sendAudio method?

**Comment by theMasix** [comment]
> Hey @archimedix.
> 
> You have couple of options to [send audio file](http://telegraf.js.org/telegram.html#sendaudio):
> 
> ```js
> bot.on('message', (ctx) => {
>   ctx.telegram.sendAudio(chatId, 'https://server.tld/file.mp3')
>   ctx.telegram.sendAudio(chatId, 'fileId')
>   
>   // Or you can use context shortcuts
>   ctx.replyWithAudio('https://server.tld/file.mp3')
>   ctx.replyWithAudio({url: 'https://server.tld/file.mp3'})
>   ctx.replyWithAudio({content: new Buffer(...)})
> })
> ```
> 
> [Working with files in Telegraf](http://telegraf.js.org/telegraf.html#working-with-files)

Also your links won't open ...

**Comment by jassler** [comment]
@theMasix @pladaria 

Updated Link: https://telegraf.js.org/#/?id=working-with-files

You can send (audio) files by specifying a `source` key:

```js
ctx.replyWithAudio({source: `path/to/file.mp3`})
```

**Comment by theMasix** [comment]
@jassler Could you please check #986 too?
