### ISSUE TITLE
Node.js Telegraf Wizard by importing data between steps

### ISSUE THREAD

**Issue by HadiAbbasi** [telegraf/telegraf#292]
Hi
my bot has 2 parts!
1. which can handle by normal scene! I have used normal scene (default scene)!
2.which must be wizard (step by step) place by having input data steps to getting x , y numbers from user and do a task on x,y at the end of wizard! (interaction between the bot and user). I have used wizard scene for that!
using 2 scenes are required because I have 2 states on my bot that must be  separated without interference inputs together!
suppose that I want to reply to enter value and then the user must input his/her value and then I must reply second msg and he/she must enter second value and so on so forth...
e.g: 
bot: Hi ..please enter your name.
jack: jack
bot: Hi jack . please enter your age:
jack: 22
.
.
.
but I can't do that. because I must save my values per user. the only way to saving all these values is on telegram context (ctx) but I know that wizard ctx is different by input data ctx.
so I can access to wizard ctx from input ctx but I think it must has better way to support interaction between users and bots on wizard step by step mode!
at the below code:
1- I don't know if I could do both functions in a single function inside wizard (because of common ctx to save x,y on same ctx)!
2- I want to access both x , y values on the end of wizard? (region ACCESS TO X,Y)
3- in the stepHandler.use function I have to know the step of wizard to know which variable (x or y) is my next goal. but I don't know how?
thanks to help....

```
const stepHandler = new Composer();
const wizardscene = new WizardScene('info_scene',
  (ctx) => {
	ctx.reply("please...", Markup.inlineKeyboard([
	  Markup.callbackButton('cancel' , 'cancel')
	]).extra());
	return ctx.wizard.next();
  },
  stepHandler,
  (ctx) => {
	ctx.reply('please...', Markup.inlineKeyboard([
	  Markup.callbackButton('cancel', 'cancel')
	]).extra());
	var x = ctx.message.text;//or maybe -> ctx.x = ctx.message.text
	return ctx.wizard.next();
  },
  (ctx) => {
	ctx.reply('please...', Markup.inlineKeyboard([
	  Markup.callbackButton('cancel', 'cancel')
	]).extra());
	var y = ctx.message.text;//or maybe -> ctx.y = ctx.message.text
	return ctx.wizard.next();
  },
  (ctx) => {
	//ACCESS TO X,Y
	return returnToDefaultScene(ctx);
  });
  
  stepHandler.use((ctx) =>
  {
	//how can I know the step number of ctx.wizard ??? I think ctx.wizard.cursor is not correct way
	if(ctx.wizard.cursor == 1)
	{
		if(utils.isNumber(ctx.message.text))
		{
			var x = Math.abs(parseInt(ctx.message.text,10));
			return ctx.wizard.steps[2](ctx);
		}
		else
		{
			//..
		}
	}
	else
	{
		if(ctx.message.text == "")
		{
			//..
		}
		else
		{
			var y = ctx.message.text;
			//..
		}
	}
});
```

**Comment by Piterden** [comment]
Do you mean something like this?
It's for old telegraf-flow, but should be the same.
```js
const conf = {
  fio: {
    rules: /([а-я]+)(\s+)([а-я]+)(\s+)([а-я]+)/i,
    errorMessage: 'Пожалуйста, введите правильные фамилию, имя и отчество.',
  },
}

const label = (field, idx) => `
Шаг ${idx + 1}
Введите значение поля
<b>${field.label}</b>
`

const buildStep = (field, idx) => ({ message, reply, replyWithHTML, flow }) => {
  const { rules, errorMessage } = conf[field.slug]

  if (message && message.text && rules) {
    if (!message.text.match(rules)) {
      return replyWithHTML(errorMessage)
    }
  }

  reply(label(field, idx))

  flow.wizard.next()
}

export default (doc, fields) =>
  new WizardScene(`doc-wizard-${doc.id}`, ...fields.map(buildStep))
```

**Comment by HadiAbbasi** [comment]
Hi Piterden...
thanks a lot...
I'm not familiar with you code language...
but now I have found my way...
for getting data between wizard I must try this link:
https://github.com/telegraf/telegraf/issues/221
and for sharing variables with each step I can use session:
https://github.com/telegraf/telegraf/issues/280
thanks a lot and good luck...
