### ISSUE TITLE
Export Telegraf Logs

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#293]
Hi, dear developers.
I have a question here: How can I export all logs from `bot.use(Telegraf.log())` to the some variable or .json file?
Thanks in advance.

**Comment by Piterden** [comment]
I use own mw for it 
https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L174-L187

**Comment by JRakhimov** [comment]
@Piterden there are more than I need, Thank you for your great work)

**Comment by Piterden** [comment]
NP )
Actually, it was rewriting of an old bot with similar functionality.
@CristianOspina is the real author of it.
