### ISSUE TITLE
The outdated method name in the documentation

### ISSUE THREAD

**Issue by batlab** [telegraf/telegraf#295]
[Working with files](http://telegraf.js.org/#/?id=working-with-files)
There is list of methods (answerWithVideo, answerWithPhoto, etc.)
But 'answerWith...' was changed to 'replyWith...'. 
[For example](http://telegraf.js.org/#/?id=shortcuts)
So rewrite [this part](http://telegraf.js.org/#/?id=working-with-files) in the documentation.

**Comment by Piterden** [comment]
Reply:
https://github.com/telegraf/telegraf/blob/develop/core/context.js#L261-L264
https://github.com/telegraf/telegraf/blob/develop/core/context.js#L341-L409

Answer:
https://github.com/telegraf/telegraf/blob/develop/core/context.js#L142-L170

**Comment by batlab** [comment]
But there are no methods like answerWithVideo, answerWithPhoto. They were replaced by replyWithVideo, replyWithPhoto, etc.
So [this part](http://telegraf.js.org/#/?id=working-with-files) is outdated.

**Comment by dotcypress** [comment]
@batlab this part of documentation is obsolete.
Thank you for report

**Comment by dotcypress** [comment]
Fixed
