### ISSUE TITLE
Dynamic Keyboard

### ISSUE THREAD

**Issue by kmahsi** [telegraf/telegraf#296]
I have a json obj like RSP. it is something like this:

    [{"captoin", "A"},
     {"caption", "B"},
     {"caption", "C"}]
the number of objects in RSP and the values of them("A", "B",...) are not constant and I get them with calling an API.
Now I want to make an inline keyboard for my bot which it's buttons are the values of this json ("A", "B", "C",...).

**Comment by Piterden** [comment]
https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L90-L98

**Comment by kmahsi** [comment]
@Piterden 
Can you explain more?
I'm writing it with telegraf.

**Comment by Piterden** [comment]
What you want me to explain? It's dynamic inline keyboard which you asked for.
