### ISSUE TITLE
Inline search in bot

### ISSUE THREAD

**Issue by kmahsi** [telegraf/telegraf#297]
I want an inline search in my bot and I want to show the result of the searching in real-time.
Something like what @gif or @bing do.
They show the result of the search in real-time and you can click on each item you want to select.

Thanks for any help.

**Comment by dotcypress** [comment]
@kmahsi you can achieve that with `inline mode`, see related [example](https://github.com/telegraf/telegraf/blob/develop/docs/examples/inline-bot.js).

**Comment by Piterden** [comment]
And one more example too
https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L296-L320
