### ISSUE TITLE
How to handle button of a dynamic keyboard

### ISSUE THREAD

**Issue by kmahsi** [telegraf/telegraf#298]
I have an inline keyboard which it's buttons come from a JSON obj like RSP. It is something like this:

[{"caption", "A"},
 {"caption", "B"},
 {"caption", "C"}]
the number of objects in RSP and the values of them("A", "B",...) are not constant and I get them by calling an API.
Now I don't know how to handle the response of each key.
Should I use [Scenes](http://telegraf.js.org/#/?id=stage) or something else?

Thanks for any help.

**Comment by dotcypress** [comment]
Hi @kmahsi 

We have few solutions here:

Dispatch callback query data manually:
```js
bot.on('callback_query', (ctx) => {
  console.log(ctx.callbackQuery.data)
})
```

Or using predicate function:

```js
function predicateFn (callbackData) {
   return callbackData === 'A' || callbackData === 'B' 
}

bot.action(predicateFn, ({ reply }) => reply('foo'))
```

**Comment by kmahsi** [comment]
Hi @dotcypress 
Thanks for your answer.
What is the application of this "action" method?
Is it just for inline keyboard and callbackQuerys?

**Comment by dotcypress** [comment]
@kmahsi Yes, the second solution will fit well
