### ISSUE TITLE
Some problems with scenes

### ISSUE THREAD

**Issue by kmahsi** [telegraf/telegraf#299]
I am using [scenes](http://telegraf.js.org/#/?id=stage) like what is in the tutorial.
My problem is that for example in function command I want to do this:

```
greeterBlue.command('red', async (ctx) => {
    ctx.reply("Hi")
    ctx.scene.leave()
    ctx.scene.enter('greeter-red')
})

```
But it seems that just the first line of the function executes.
How can I write this to execute all three lines?

Thanks for any help.

**Comment by eonicum** [comment]
Just add await for each line inside the function:
`greeterBlue.command('red', async (ctx) => {
    await ctx.reply("Hi")
    await ctx.scene.leave()
    awiat ctx.scene.enter('greeter-red')
})
`

**Comment by Piterden** [comment]
`ctx.scene.leave()` makes current `ctx.scene` inactive, isn't it?

```js
greeterBlue.command('red', async (ctx) => {
    ctx.reply("Hi")
    ctx.scene.leave()
    ctx.scene.enter('greeter-red')
})
```

You should use static method of the Stage class, IMHO

**Comment by kmahsi** [comment]
Thanks for you answer @Piterden.
But in the third line you have entered "Stage", so what is the difference between scene and stage?
Shouldn't you enter the scene?

**Comment by Piterden** [comment]
Btw, mixing of `'` and `"` is da bad practice...

**Comment by Piterden** [comment]
A stage keeps a collection of scenes, isn't it, @dotcypress ?

**Comment by dotcypress** [comment]
@Piterden yep

**Comment by Piterden** [comment]
Oh thanx. Could you tell me what are the advantages of using `async/await` there?
```js
greeterBlue.command('red', async ({ reply, scene, stage }) => {
    await reply('Hi')
    await scene.leave()
    await stage.enter('greeter-red')
})
```
As I understand the `await` statement forces some parts of an async function to work synchronously.
So, it means for this case it wouldn't be any difference if I wrote like:
```js
greeterBlue.command('red', ({ reply, scene, stage }) => {
    reply('Hi')
    scene.leave()
    stage.enter('greeter-red')
})
``` 
Or not?

**Comment by dotcypress** [comment]
@Piterden I believe following thread will help: #80

**Comment by kmahsi** [comment]
Hi @Piterden 
Your answer didn't work.
I get this error on the third line of greeterBlue.command()
`Cannot read property 'enter' of undefined`

**Comment by danilaplee** [comment]
do scenes work with redis or firebase adapter session adapter?

**Comment by dotcypress** [comment]
@danilaplee  certainly!

**Comment by dotcypress** [comment]
@kmahsi https://github.com/telegraf/telegraf/issues/309#issuecomment-362870720

**Comment by TesfaM** [comment]
please some one give me an answer

**Comment by Piterden** [comment]
An answer
