### ISSUE TITLE
Feature: allow passing own http[s] server on initialisation

### ISSUE THREAD

**Issue by Firfi** [telegraf/telegraf#3]
Hey, 

it would be useful to have this. I.e. I have only one network interface to listen on but I want to handle other http[s] request in application besides telegram webhooks. Currently I have a conflict if I do http.createServer on same interface two times.

**Comment by dotcypress** [comment]
Hey,

Just release `0.6.0`, check out [webhook docs](https://github.com/telegraf/telegraf#telegram-webhook)
