### ISSUE TITLE
picture with caption

### ISSUE THREAD

**Issue by archimedix** [telegraf/telegraf#30]
if i want to send picture with caption?
i try:
`        return ctx.replyWithPhoto({ 
          url: 'http://som-picture-image.jpg',
          caption : 'some caption'
        })
`
but didn't work

**Comment by dotcypress** [comment]
Try `return ctx.replyWithPhoto({ url: 'http://som-picture-image.jpg'}, {caption : 'some caption' })`

**Comment by userbq201** [comment]
@dotcypress how replyWithPhoto + mardown ?

**Comment by zougataga** [comment]
how to send the image in small size?
