### ISSUE TITLE
Add option to ignore Unsupported messages from telegram

### ISSUE THREAD

**Issue by sergeysova** [telegraf/telegraf#300]
Bot crash if get unsupported message from telegram.

That behaviour makes bot very unstable, because cannot be controlled by developer.

![image](https://user-images.githubusercontent.com/5620073/34725506-32c781d4-f562-11e7-9307-ce71ef5f0beb.png)

**Comment by dotcypress** [comment]
What do you mean by `bot crash`? 
Polling process [will wait](https://github.com/telegraf/telegraf/blob/develop/telegraf.js#L135-L137) 1 sec and retry call.
