### ISSUE TITLE
Reply to specific chat/message

### ISSUE THREAD

**Issue by ahmadarif** [telegraf/telegraf#301]
I'm using telegraf `^3.17.2`, how to reply to spesific message?

**Comment by ahmadarif** [comment]
Please add function like this
`sendMessageReply (chatId, messageId, text, extra) {
    return this.callApi('sendMessage', Object.assign({ chat_id: chatId, reply_to_message_id: messageId, text: text }, extra))
  }`

I need reply to original message

**Comment by ahmadarif** [comment]
Or add something like this in `context.js`

```js
replyToMessage (message, extra) {
    return this.reply(message, Object.assign({ 'reply_to_message_id': this.message.message_id }, extra))
}
```

**Comment by dotcypress** [comment]
I believe you talk about `Extra.inReplyTo` helper:

```js
replyToMessage (message, extra) {
    return this.reply(message, extra.inReplyTo(message.message_id))
}
```

And I realized that `inReplyTo` isn't documented yet 🙁

**Comment by dotcypress** [comment]
Closing in favor of #262

**Comment by sarangsmk** [comment]
I had the same question but I was unable to catch up the above mention code snippet, and I found something like this

`ctx.telegram.sendMessage(<ctx.message.chat.id>, "Your message", { reply_to_message_id: <the message id that you want to reply> });`

**Comment by Porkechebure** [comment]
> I believe you talk about `Extra.inReplyTo` helper:
> 
> ```js
> replyToMessage (message, extra) {
>     return this.reply(message, extra.inReplyTo(message.message_id))
> }
> ```
> 
> And I realized that `inReplyTo` isn't documented yet 🙁

How to use "Extra"? Where to import/use? I can't find it

**Comment by VenRoot** [comment]
> > I believe you talk about `Extra.inReplyTo` helper:
> > ```js
> > replyToMessage (message, extra) {
> >     return this.reply(message, extra.inReplyTo(message.message_id))
> > }
> > ```
> > 
> > 
> > And I realized that `inReplyTo` isn't documented yet 🙁
> 
> How to use "Extra"? Where to import/use? I can't find it

Extra has been removed since Telegraf@4.0.0

**Comment by Porkechebure** [comment]
> > > I believe you talk about `Extra.inReplyTo` helper:
> > > ```js
> > > replyToMessage (message, extra) {
> > >     return this.reply(message, extra.inReplyTo(message.message_id))
> > > }
> > > ```
> > > 
> > > 
> > > And I realized that `inReplyTo` isn't documented yet 🙁
> > 
> > 
> > How to use "Extra"? Where to import/use? I can't find it
> 
> Extra has been removed since Telegraf@4.0.0

SO what we have tio use?

**Comment by Dimi-Dun-Morogh** [comment]
for anyone still wondering, you can reply to specific message like that now: 
```
ctx.reply('I got balls of steel', { reply_to_message_id: message_id });
  }
```

**Comment by eminyalcin** [comment]
this is work for me
ctx.reply("__\*This message*__ is reply \r\nand \r\n`markdown` message", Extra.inReplyTo(ctx.message.message_id).markdown())
