### ISSUE TITLE
Send periodical messages

### ISSUE THREAD

**Issue by propercoil** [telegraf/telegraf#304]
There's no way to send periodic messages or send a message to a specific group if someone
wants to for example output the same message to a group every 60 minutes, etc.

**Comment by Piterden** [comment]
`setInterval()`

**Comment by propercoil** [comment]
@Piterden I tried doing something like:

```
const app = new Telegraf('')
function sendPic() {
 app.on('', (ctx) => ctx.replyWithPhoto({ url: 'http://lorempixel.com/400/200/cats/' }))
}

setInterval(sendPic, 10*1000)
```

But it's not working. I don't know what command to use to simply send a message without waiting for anything..

**Comment by Piterden** [comment]
`app.on` is the listener. Think about what would you reach if you bind the new one listener by each iteration of the interval.
Try next:
```js
app.on(/.*/, (ctx) => {
  setInterval(() => {
    ctx.replyWithPhoto({ url: 'http://lorempixel.com/400/200/cats/' })
  }, 3600000)
})
```
