### ISSUE TITLE
Get the "stage" in callback_query

### ISSUE THREAD

**Issue by kmahsi** [telegraf/telegraf#309]
Hello.
I'm writing a bot with telegraf and I'm using [stages](http://telegraf.js.org/#/?id=stage) in it.
I have a scene like this:
 ```
 chooseServiceScene.on('callback_query', async ({reply, scene, stage, session, update, 
    editMessageText}) => { 
    await reply("Hi")
    await scene.leave()
    await stage.enter('serviceDetailsScene')
}
```
I have two scenes called "chooseServiceScene" and "serviceDetailsScene".
In serviceDetailsScene I want to leave it and enter the serviceDetailsScene, but I get this error:
 TypeError: Cannot read property 'enter' of undefined.
I have declared these two scenes just like this tutorial: [stages](http://telegraf.js.org/#/?id=stage)
Thanks for any help.

**Comment by dotcypress** [comment]
@kmahsi it happens cause Stages use session storage, and `ctx.stage` stays undefined in case session [isn't exists](http://telegraf.js.org/#/?id=session). 

If you want to use session with `callback_query`, you  must implement custom [session key resolver](https://github.com/telegraf/telegraf/blob/develop/session.js#L4), cause `ctx.chat` will be empty for some callback queries(see `inline_message_id ` in Telegram Bot api docs).

**Comment by jkjok** [comment]
have you found a solution?

**Comment by TesfaM** [comment]
somebody please answer the question please
