### ISSUE TITLE
sendMessage freeze if I try send more than 20 message / per minute for different users

### ISSUE THREAD

**Issue by sautchenkov** [telegraf/telegraf#310]
Hello! I try to send a message to all bot users. In the documentation, I see the only 30/sec limit. But when I try to send, if I send more than 20/min sendMessage freeze for 30 sec. And I can send more than 20/per minute to separate users. Does anyone get this limit?

**Comment by Piterden** [comment]
Is it @sautchenkov_dev_bot? Why is it so freezy after any request?

**Comment by sautchenkov** [comment]
@Piterden no, I get this behavior in another bot.

**Comment by CristianOspina** [comment]
What do you mean exactly with "freeze"?  The bot API should answer with some error if it's a limit, or other problem.

You should try to see what error or answer gives Telegram in the call 21+, maybe @piterden can show you how to handle those errors/exceptions with Telegraf.

With that error we could know what happens.

If there's no error, then it would seem like a problem with Telegraf, try to describe exactly the sendMessage you are sending.

**Comment by Piterden** [comment]
[Freeze](https://www.youtube.com/watch?v=l7sikNiPM9I)
