### ISSUE TITLE
Missing doucumentation for Markup Layout

### ISSUE THREAD

**Issue by CiccioJS** [telegraf/telegraf#311]
i have a problem with the inlineKeyboard, how size the button? i see the example [here](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js)
How can i change the layout of buttons?
![send-message-with-inlinekeyboard](https://user-images.githubusercontent.com/33873839/35415906-86bbb928-0227-11e8-9b29-6f092fa0f849.png)
something like this

**Comment by dotcypress** [comment]
#211

**Comment by Piterden** [comment]
https://github.com/telegraf/telegraf/blob/develop/markup.js#L144-L167

**Comment by xamgore** [comment]
```
Markup.resize().keyboard([
  Markup.button('title'),
  Markup.button('title2')
], { columns: 2 })
```

**Comment by dotcypress** [comment]
@CiccioJS to change layout you can pass [array of arrays of buttons](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js#L20-L24) 😉 

Closing in favor of #211

**Comment by roccomuso** [comment]
The markup layout is not documented, his methods neither

**Comment by Piterden** [comment]
Generally they do this:
```
button (text, hide = false) returns { text: text, hide: hide }
contactRequestButton (text, hide = false) returns { text: text, request_contact: true, hide: hide }
locationRequestButton (text, hide = false) returns { text: text, request_location: true, hide: hide }
urlButton (text, url, hide = false) returns { text: text, url: url, hide: hide }
callbackButton (text, data, hide = false) returns { text: text, callback_data: data, hide: hide }
switchToChatButton (text, value, hide = false) returns { text: text, switch_inline_query: value, hide: hide }
switchToCurrentChatButton (text, value, hide = false) returns { text: text, switch_inline_query_current_chat: value, hide: hide }
gameButton (text, hide = false) returns { text: text, callback_game: {}, hide: hide }
payButton (text, hide = false) returns { text: text, pay: true, hide: hide }
```
