### ISSUE TITLE
how I can always access last send message id ?

### ISSUE THREAD

**Issue by Shoyad** [telegraf/telegraf#315]
Hi 

I want to save last messageId which send my bot always

telegramId | msgId | date

**Comment by Piterden** [comment]
Do you need to store all these ids, or either only last one?

**Comment by Shoyad** [comment]
Last one only

**Comment by Piterden** [comment]
Store it in file

**Comment by Shoyad** [comment]
How?

**Comment by Shoyad** [comment]
I use this but lost editMessage, deleteMessage any function. Only ctx.reply works

`bot.use((ctx, next) => {
  const reply = ctx.reply;
  ctx.reply = (...args) => {
    ctx.session.lastMessage = args;
    reply(...args);
  };
  return next();
});`

**Comment by Piterden** [comment]
Check `fs`
