### ISSUE TITLE
How I can access always to sendMessage id 

### ISSUE THREAD

**Issue by Shoyad** [telegraf/telegraf#316]
Hi 

I want to access lastMessage id from bot always. I try it code: 

`bot.use((ctx, next) => {`
 `   const reply = ctx.reply;`
`    ctx.reply = (...args) => {`
  `  ctx.session.lastMessage = args;`
  `     reply(...args);`
`   };`
`    return next();`
`});`
But I lost editMessage deleteMessage of ctx

**Comment by dotcypress** [comment]
@Shoyad You can save `message_id` to database or file(`ctx.reply('hello').then((message) => message)`)
