### ISSUE TITLE
Commands addressing a bot don't work

### ISSUE THREAD

**Issue by glor** [telegraf/telegraf#317]
Commands like `/command@bot_name_bot` don't work with the `bot.command()` handler.

**Comment by Piterden** [comment]
Maybe you are wrong?

**Comment by dotcypress** [comment]
@glor could you provide more details?

**Comment by glor** [comment]
This scenario applies mainly to groups.  
In a group there can be multiple bots. If you want just one bot to execute a command, you can mention the bot in there by postpending the command with @botname.  
Also: If your bots offer commands within a message written by that bot (e.g. `/help`) they become clickable. If you click on such a link, it is automatically suffixed with @botname. So a command /something becomes `/something@botname`

**Comment by dotcypress** [comment]
For handling group/supergroup commands(/start@your_bot) you need to [provide bot username.](http://telegraf.js.org/#/?id=command-handling-in-group)

**Comment by glor** [comment]
:o Sorry to waste your time

**Comment by michaelkolber** [comment]
This could probably be automated using the `/getMe` API endpoint. Is there any interest in this? If so I could look into it.

**Comment by michaelkolber** [comment]
Also, even when you put it in manually, it doesn't work in direct messages.
