### ISSUE TITLE
Unix socket for webhook

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#319]
Hello there,

May I know is it possible to let webhook listen on a unix socket instead of tcp? If so, how to do?

Regards,
Ivan

**Comment by Piterden** [comment]
Where from do you wait a request to the listened webhook?

**Comment by lifehome** [comment]
That would be nginx, it's directives will be hot reloaded when a scale action has been done.

**Comment by dotcypress** [comment]
Unfortunately, we don't support unix socket yet. Anyway, in your case `proxy_pass` fits well.

```
server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

  ssl_certificate     /tls/server.crt;
  ssl_certificate_key /tls/server.key;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

  location    / {
    proxy_pass  http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

```js
bot.startWebhook('/secret-path', null, 3000)
```
