### ISSUE TITLE
Reply with promises

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#320]
Hi everyone, within 2 months I used all replies and other interactivity commands with promises and everything was fine. But today I created new project with the last update and encountered with a problem:
```js
bot.start((ctx) => {
  authReq(ctx)
    .then(response => {
      mockup.reply(ctx, 'Success!');
      mockup.reply(ctx, 'Success!');
      console.log(response)
    })
    .catch(err => {
      mockup.reply(ctx, answers.error);
      mockup.toAllAdmins(ctx, 'Start', err);
      console.log(err)
    })
});
```
where authReq returns Promise, and mockup.reply does a bit the sam as ctx.reply and what is a problem... If I delete one of  mockup.reply(ctx, 'Success!'); user recieve nothing and when I double reply function user recieve Success one time (console.log(response) works). In addition, if there will be an err mockup.reply works with and without toAllAdmins function o_O
Is there anything changed in the new update or my code is wrong, pls help...

**Comment by tva10** [comment]
Hello @JRakhimov 
Do you use polling mode to test this code?
Do you try to return `.reply promise`?
```
.then(response => {
      console.log(response)
      return mockup.reply(ctx, 'Success!');
     })
```

I had soooome similar problem with `webhookReply=true` in telegraf@3.17.4 or .5

**Comment by JRakhimov** [comment]
@tva10 Thank you) webhookReply=false and the problem solved, but can you explain to me what WebhookReply exactly do?

**Comment by tva10** [comment]
So, then you use Webhook, you getting updates via http socket
When something happens in your bot, Telegram server makes a call to your webhook path and our server handles update. 
But by default in telegraf `webhookReply` was enabled and it keeps socket opened specially to make answer with your `reply` for this update.

When `webhookReply` is disabled, it should close socket imidately after receiving update
And all your replies will go througth `http://api.telegram/bot.../replyMethod` 

So in first case, you can use one and more http query to deal with telegram server
In the second one, you can use two and more. one to receive update, one and more to answer...

Something similar to your problem happened an week ago in my bot. It appeared after updating telegraf up to 3.17.5
And I explained that with WebHook in 3.17.3 all works fine, but in 3.17.4 or .5 - not.
And so in [3.17.4](https://github.com/telegraf/telegraf/commit/ac90d6835f73b1bb5458f882f67090cd7e7aa128) had changed logic in webhook calls....

But Im not sure in this write-up

**Comment by tva10** [comment]
And how I think
Our problem happened because `response` was finished (by timeout or another promise) before we call `.reply`. And in `client.js/ApiClient` `callApi` does not handle that moment now.

in 3.17.3 there was `!this.response.finished` check
now there is `!this.responseEnd` special flag check

So and then you tried to call `.reply` twice, I think, that 
In first try, `responseEnd` flag was false and your `'Succes!'` go in already closed `response.end(...)`
And after, in second try, `responseEnd` flag was true - because first attempt happened. And your response go througth new http query via `http://apitelegram/bot/reply....`

**Comment by dotcypress** [comment]
I think, telegram client object caching is the reason.
Hopefully fixed  [this commit](https://github.com/telegraf/telegraf/commit/5dc34b9e5dd2b2bb0065362feeea6e85d8edc437)

Release will be landed soon, stay tuned.

**Comment by dotcypress** [comment]
@JRakhimov @tva10 could you try with latest version?

https://github.com/telegraf/telegraf/releases/tag/3.17.6

**Comment by tva10** [comment]
@dotcypress 
Yep
tried to update telegraf up to 3.17.6 but nothing happens for me :(
But also tried to return `!response.finished` check in `client.js` `callApi` method and all works!

**Comment by tva10** [comment]
```
const Telegraf = require('telegraf');

const token = ' some bot token';
const lturl = 'local tunnel path';
const path = '/somepath';
const ltport = 8082;


const config = {
	telegram: { webhookReply: true }
};
const app = new Telegraf( token || process.env.BOT_TOKEN, config);

app.use(Telegraf.log());

/// works fine when webhookReply true
app.command('return', function(context){
	return new Promise(function(res){
		setTimeout(res, 1000);
	}).then(function(){
		console.log('wanna reply');
		context.reply('you write smth');	
	}).catch(console.log);
});

///	did not work when webhookReply true
app.on('text', function(context){
	new Promise(function(res){
		setTimeout(res, 1000);
	}).then(function(){
		console.log('wanna reply');
		context.reply('you write smth');	
		//context.reply('success!2');	
	}).catch(console.log);
});

/// works fine too
/// maybe because response not finished yet
app.on('sticker', function(context){
	context.reply('HI!');
});


//app.telegram.setWebhook().then(()=>{ app.startPolling() });

app.telegram.setWebhook(lturl + path).then(()=>{app.startWebhook(path, null, ltport)});
```

**Comment by JRakhimov** [comment]
@dotcypress The results are the same as those of @tva10 
`//Didn't work when webhookReply= true`
`bot.start((ctx) => {`
`  authReq(ctx)`
`    .then(response => {`
`      if (response.result) {`
`        mockup.reply(ctx, 'Already logged in!')`
`      } else {`
`        mockup.reply(ctx, 'Pls, log in!')`
`      }`
`    })`
`    .catch(err => {`
`      mockup.reply(ctx, answers.error);`
`      mockup.toAllAdmins(ctx, 'Start', err);`
`      console.log(err)`
`    })`
`});`

`//Works fine with webhookReply = true`
`bot.start((ctx) => {`
`  return authReq(ctx)`
`    .then(response => {`
`      if (response.result) {`
`        mockup.reply(ctx, 'Already logged in!')`
`      } else {`
`        mockup.reply(ctx, 'Pls, log in!')`
`      }`
`    })`
`    .catch(err => {`
`      mockup.reply(ctx, answers.error);`
`      mockup.toAllAdmins(ctx, 'Start', err);`
`      console.log(err)`
`    })`
`});`

`//And also works when webhookReply = false`
`bot.start((ctx) => {`
`  authReq(ctx)`
`    .then(response => {`
`      if (response.result) {`
`        mockup.reply(ctx, 'Already logged in!')`
`      } else {`
`        mockup.reply(ctx, 'Pls, log in!')`
`      }`
`    })`
`    .catch(err => {`
`      mockup.reply(ctx, answers.error);`
`      mockup.toAllAdmins(ctx, 'Start', err);`
`      console.log(err)`
`    })`
`});`

**Comment by dotcypress** [comment]
@tva10 @JRakhimov Guys, in provided example I found that you break promise chain.
To fix that, just add `return` keywords:


```js
/// works fine when webhookReply true
app.command('return', function(context){
	return new Promise(function(res){
		setTimeout(res, 1000);
	}).then(function(){
		console.log('wanna reply');
		RETURN context.reply('you write smth');	
	}).catch(console.log);
});

///	did not work when webhookReply true
app.on('text', function(context){
	RETURN new Promise(function(res){
		setTimeout(res, 1000);
	}).then(function(){
		console.log('wanna reply');
		RETURN context.reply('you write smth');	
	}).catch(console.log);
});
```

[Related issue](https://github.com/telegraf/telegraf/issues/80)

**Comment by tva10** [comment]
@dotcypress Yes, I know what promise was broken. But I would't have noticed by this error if that was happened earlier in previous version of telegraf on default webhook settings
