### ISSUE TITLE
Does this library support sendBroadcast?

### ISSUE THREAD

**Issue by ablankenship10** [telegraf/telegraf#321]
I dont see it in the docs or code. Is this still available in the latest telegram API?

I need to be able to send 1 message to a list of several thousands of people at the same time. Whats the best way to go about this if broadcast isn't available?

**Comment by ablankenship10** [comment]
Hmm, any other methods to message tons of people at once via Bot API? I can do it over time but it needs to be within like 5 seconds for 50-100k people, so the rate limit of 30 per second isnt enough. And it needs to be select users not everyone talking to bot.

**Comment by dotcypress** [comment]
50-100k people? Do you consider to create Telegram Channel instead?
