### ISSUE TITLE
bot.telegram.sendMessage timeout needed?

### ISSUE THREAD

**Issue by ptkdev** [telegraf/telegraf#331]
> https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once

>  When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.
If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. Consider spreading out notifications over large intervals of 8—12 hours for best results.
Also note that your bot will not be able to send more than 20 messages per minute to the same group.

Telegraf have 30message/seconds delay if i use `bot.telegram.sendMessage(chat.id, '...');` ?

**Comment by dotcypress** [comment]
@ptkdev no, rate limiting is't part of Telegraf.

**Comment by ptkdev** [comment]
What is correct flow to not reach the rate limit?

I count sendMessage() calls and add [sleep](https://www.npmjs.com/package/system-sleep) of 1sec if i send 30 request?

**Comment by ptkdev** [comment]
[1sec sleep after 30 request](https://github.com/ptkdev/wordpress-telegram-bot.js/blob/master/modules/feed.js) work fine :)

**Comment by AndreoliBR** [comment]
Could you reupload the gist pls? the repo was not found :(

**Comment by ptkdev** [comment]
@AndreoliBR 
```javascript
    function check_database(json){
        let sleep = require('system-sleep');
        db.serialize(function() {
            let limit = 0;
            db.each("SELECT rowid AS id, chat_id, last_url FROM users", function(err, row) {
                let last_url = null;
                let chat_id = null;
                let i = 0;
                for (i = 0; i < config.wp_total_feed && i < json.rss.channel[0].item.length; i++) {
                    let url = json.rss.channel[0].item[i].link[0].replace("'", "");
                    if(i == 0){
                        last_url = url;
                        chat_id = row.chat_id;
                    }
                    if(url == row.last_url)
                        break;

                    bot.telegram.sendMessage(row.chat_id, url);
                    limit++;

                    if(limit >= 29){ // bug: https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once
                        sleep(1000);
                        limit = 0;
                    }
                }

                if(i > 0){
                    db.run("UPDATE users SET last_url = ? WHERE chat_id = ?", last_url, chat_id);
                }
            });
        });
    }
```

**Comment by AndreoliBR** [comment]
@ptkdev Thanks for the gist but I've written a more elegant solution using `setInterval` without aditional modules:

```javascript
const msgInterval = setInterval(() => {
  users.splice(0, 29).forEach((user) => {
    ctx.telegram.sendMessage(user.user_id, message, {
      ...messageSettings
    });
  });
}, 1000);

if (users.length === 0) {
  clearInterval(msgInterval);
}
```

**Comment by ptkdev** [comment]
@AndreoliBR great! Nice bro!
