### ISSUE TITLE
There is any Forum or Discussion group of Telegraf?

### ISSUE THREAD

**Issue by NuMarAki** [telegraf/telegraf#333]
Is there any group that you guys discuss or share experiences using Telegraf and TelegramBots?

I am new to this world and trying to do a bot that is able to send msg, depending on some conditions in API result searchs in infinite loop, to every Chat/GroupChat which he is added and I am looking for more documentations of what Telegraf can do and how it is done internally.

**Comment by sergeysova** [comment]
We have russian community in Telegram: https://t.me/telegraf_ru

But we can create english speaking group/chat

**Comment by NuMarAki** [comment]
I joined the group, lets see if I can learn something.

I will close this "Issue", thank you very much.
