### ISSUE TITLE
How do I forward a user to a group or channel ?

### ISSUE THREAD

**Issue by mojo2405** [telegraf/telegraf#336]
Hi,

I want to forward user to a group or channel.
I want to put a button that after the user clicks on it - the user is asked to go to a group or a channel.
please help.

**Comment by NuMarAki** [comment]
Need to be a button? You could send to the user the link for the group, then the user click on link and join the group/channel.

**Comment by adefirmanf** [comment]
Yeah, you can forward a user to a group or channel using `Markup.urlButton`.
```
ctx.reply('This is our channel', Markup.inlineKeyboard([
        Markup.urlButton('@JavascriptIndonesia', 'https://t.me/Indonesia_Javascript', false)
]).extra())
```

Documentation not ready yet for `Markup`, you must seeing directly about parameter used for.
https://github.com/telegraf/telegraf/blob/develop/markup.js#L59-L61
