### ISSUE TITLE
Multiple Answer

### ISSUE THREAD

**Issue by drow-ranger** [telegraf/telegraf#337]
Good Morning,

I want to make a bot answer my 3 messages and at the end of the answer will combine the message I'm delivering.

Example
> me> / unlock
> bot> what is your account?
> me> drow-ranger
> bot> what is your computer name?
> me> PC-99
> bot> what's your ticket number?
> me> TICKET-001
> bot> admin pls unlock drow-ranger on PC-99 with TICKET-001
> 

is this possible? so far I have not understood making a session in Telegraf, Please help.

**Comment by sergeysova** [comment]
Scenes?

**Comment by sergeysova** [comment]
https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js
https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js
