### ISSUE TITLE
Get if message with url entity has preview enabled

### ISSUE THREAD

**Issue by jmolero** [telegraf/telegraf#338]
Is it possible to know if a message with a url has the preview enabled or disabled?

I saw a group that warns the users if they share a URL with the preview open and I'd like to do the same. 

Thanks!

**Comment by adefirmanf** [comment]
If users send a link, there's nothing you can do with URL preview. Telegram API is support `entity` to detect type of message send by user such as `url` but you can't detect URL preview via telegram API. 
In otherway, you can do method such as scrapping his meta inside `entity` and then returned message if true. 

```
Bot.entity('url',(ctx)=>{
    //Do something here like scrapping 
})
```
This question might be helped you 
[https://stackoverflow.com/questions/38599625/access-link-previews-from-the-bot-api](url)

Sorry for grammar

**Comment by jmolero** [comment]
I thought about doing scrapping but wasn't sure if that's what that group did and how to do it myself. 

Thanks for the help and link!
