### ISSUE TITLE
Plz Help Me! How send shade message type? 

### ISSUE THREAD

**Issue by vladmysiur** [telegraf/telegraf#341]
<img width="866" alt="screen shot 2018-02-11 at 10 41 50 pm" src="https://user-images.githubusercontent.com/10451554/36078262-d110f5bc-0f7c-11e8-8d84-d1796eb95c97.png">
"test" in screen
I thin that i can send this message via answerInlineQuery but i have error:
Ooops Error: Telegraf: "answerInlineQuery" isn't available for "message::text"

**Comment by dotcypress** [comment]
@vladmysiur `answerInlineQuery` - designed for sending inline query result, and not available for messages.

**Comment by vladmysiur** [comment]
How i can send this message type which is on the screen?
