### ISSUE TITLE
How to force user leave scene after 30 min user inactivity?

### ISSUE THREAD

**Issue by alishermuhamed** [telegraf/telegraf#342]
Hello. 

I have one idea: to save time of last message in session (I'm using redis) and to make infinite cycle that looks through redis storage and searches for users with 'last message time' being more than 30 minutes ago. If there are such users, then force them to leave scene.

Also I found that there is ttl option in redis-sessions. Maybe such option exists for scenes?

Thank you.

**Comment by dotcypress** [comment]
@alishermuhamed Hello 👋

Yes, this option available for scenes and you can find example usage [here](https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js#L23).

**Comment by alishermuhamed** [comment]
@dotcypress thank you for the answer!

If I use one scene as a default, will inactive users enter it after ttl is expired? Or they will just leave stage?

Example:
`const stage = new Stage([firstScene, secondScene], { default: 'firstScene', tll: 1800 })`

**Comment by roccomuso** [comment]
is ttl in seconds?

**Comment by dotcypress** [comment]
@roccomuso yes, seconds

**Comment by felinto-dev** [comment]
> @alishermuhamed Hello 👋
> 
> Yes, this option available for scenes and you can find example usage [here](https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js#L23).

The link does not exist.
