### ISSUE TITLE
How to implement menu Back

### ISSUE THREAD

**Issue by zbarinov** [telegraf/telegraf#343]
I have a tree-like menu. And on each sub-tree I'd like to remember the menu above. Can anybody give an advice how can I implement this way of work? Thank you!

**Comment by adefirmanf** [comment]
Did you ever try `ctx.scene.reenter()` ?

**Comment by zbarinov** [comment]
Thank you, I guess this is what I need.

**Comment by adefirmanf** [comment]
@zbarinov Gald to hear it. Please close this issue then @dotcypress

**Comment by zbarinov** [comment]
sure
