### ISSUE TITLE
Choose who will see keyboard on replykeyboardmarkup with selective broken on Telegram clients

### ISSUE THREAD

**Issue by yangwao** [telegraf/telegraf#344]
Hey, great work! Really, I could assemble fine bot w/o any knowledge, very straightforward library.

I just found this is what I want to use from https://core.telegram.org/bots/api#replykeyboardmarkup
```
selective | Boolean | Optional. Use this parameter if you want to show the keyboard to 
specific users only. Targets: 
1) users that are @mentioned in the text of the Message object;
2) if the bot's message is a reply (has reply_to_message_id), sender of the original message.Example: 
A user requests to change the bot‘s language, bot replies to the request with a keyboard
to select the new language. Other users in the group don’t see the keyboard.
```
I should go and use this http://telegraf.js.org/#/?id=editmessagereplymarkup ?

Any help appreciated. Thanks 🙌

**Comment by yangwao** [comment]
This should be what I looking for https://github.com/telegraf/telegraf/blob/ed279cbfbbf9ca5e161821390ee6d9a7f10598af/markup.js#L12 but apparently does not work for me when I used it after keyboard()

**Comment by yangwao** [comment]
Oh looks like there is no static for selective

**Comment by yangwao** [comment]
I put myself 
```  static selective (value = true) {
    return new Markup().selective(value)
  }```
into markup.js 

It works, when is command triggered from Desktop OSX and keyboard does not show up on iOS/Android. That's fine. Without selective it shows keyboard every user. 
But when is triggered from iOS/Android, it looks like it will show on desktop either (not same user), but not on iOS/Android.

**Comment by dotcypress** [comment]
@yangwao thank you for jumping in 👍 

Static `selective` method will be published with next release.

**Comment by yangwao** [comment]
Thanks for adding. But I think there is problem in Telegram clients with this. I can test during next days.
Thanks for add anyway!
