### ISSUE TITLE
How to set a Telegram Bot with webhook? 

### ISSUE THREAD

**Issue by france193** [telegraf/telegraf#347]
Hi! I'm not able to understand through the documentation how to start a telegram bot with a webhoock...

Can someone explain me?

I'd like to do it with a self-signed certificate.

**Comment by j-c-levin** [comment]
I'm currently making a bot using telegraf and webhooks, perhaps this will give you an example of how it works?

https://github.com/j-c-levin/notcatbot/blob/master/source/index.ts
