### ISSUE TITLE
How to wrap callbackButton

### ISSUE THREAD

**Issue by adefirmanf** [telegraf/telegraf#349]
For example, I have an array like this
`arr = [10000, 1000000, 10000000, 20000, 50000, 500000, 5000000, 500000000]
`

And this is what happened
![image](https://user-images.githubusercontent.com/23324722/36362704-ad7c2890-1569-11e8-8db2-e898dd40a1aa.png)

How to wrapped that button when I calling them via dynamic parsing
```
let DenomCallBack = arr.map(n=>Markup.callbackButton(n, `{"DenomChoosen" : "${n}"}`))
ctx.replyWithHTML('Test Button', Markup.inlineKeyboard([
  DenomCallBack
])
```

The goal is I want to divide them into 2 rows
[....],[....],[....],[....],
[....],[....],[....],[....],

Thanks

**Comment by CryptoSmileee** [comment]
Should work this way:

arr = [
[10000, 1000000, 10000000, 20000], 
[50000, 500000, 5000000, 500000000]
]

**Comment by jecacs** [comment]
Try this `Markup.inlineKeyboard(DenomCallBack, { columns: 4 })`

**Comment by adefirmanf** [comment]
@CryptoSmileee Sorry, I forget about explaining the detail about that array. That array coming from High order function(?), so I can't modify array like that. For example, 
`let arr = Response.map(n => n.BigNum)`

@jecacs  No, it doesn't work. I got an error
`TypeError: row.filter is not a function`

**Comment by CryptoSmileee** [comment]
@adefirmanf 
You could use something like this:

```
var arr = [10000, 1000000, 10000000, 20000, 50000, 500000, 5000000, 500000000];

let newArr = [];
while(arr.length > 0) {
	newArr.push(arr.splice(0, 4));
}
```

**Comment by adefirmanf** [comment]
@CryptoSmileee Nice, it's works on [Jsfiddle](https://jsfiddle.net/gew5g3a1/) but I haven't implemented to real code yet . But, I'm sure it's works too.
