### ISSUE TITLE
self argument regex?

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#35]
lets say i have something like 
`bot.hears(/test (.+)/i, (ctx) => { //not important});`

is there a way/method to get the regex into ctx? 
so that ctx.exampleMethod would return  `(.+)/i` ?

**Comment by dotcypress** [comment]
Hey!

You can use constants:

```js
const regex = new RegExp(/test (.+)/i)
bot.hears(regex, (ctx) => { 
  //regex
});
```

or pass RegEx via context

```js
const regex = new RegExp(/test (.+)/i)
bot.context.regex = regex
bot.hears(regex, (ctx) => { 
  //ctx.regex
});
```

**Comment by paOol** [comment]
hello, that works great for one function.
However, I would like it for all of my functions, so defining variables for each is not ideal.

would it be possible have a middleware that "wraps" before `bot.something` functions?

**Comment by dotcypress** [comment]
I'm not sure that i clearly understand your question 😁
Could you provide more information/examples?

**Comment by paOol** [comment]
hello,
so basically I am trying to check against the regex for each of my functions that uses regex.

so bringing the first example again, `bot.hears(/test (.+)/i, (ctx) => { //not important});`
within the function, I would like a way to check that the match (ctx.match[1]), passes the regex (`(.+)`).

is it possible for this as some kind of higher-level middleware so that i don't have to declare each regex for each function?

**Comment by dotcypress** [comment]
Basically you can't do that, and i can't find any good approaches to patch `telegraf` without breaking changes.

By the way, you can implement band new `hears` handler, it's really easy, [check this file for examples](https://github.com/telegraf/telegraf/blob/develop/lib/core/composer.js).
