### ISSUE TITLE
Wrong error stack trace

### ISSUE THREAD

**Issue by smaznet** [telegraf/telegraf#352]
![image](https://user-images.githubusercontent.com/10239885/36500201-e38a47a0-1758-11e8-84ae-f8cdfa016aba.png)

what is this code problem i putted inside `process.on ("unhandledRejection"...` ?
``` js 
console.log(err.stack);
```
Why i don't get full stack trace?

**Comment by watchdots** [comment]
when bot blocked by user in telegram, any message that send to user throw 403 error.
why you should get full stack trace of exception?

**Comment by dotcypress** [comment]
@smaznet you get full stack trace, but it's a little bit ugly because we massively uses Promises :(

FYI: http://telegraf.js.org/#/?id=error-handling
