### ISSUE TITLE
How to get user by username?

### ISSUE THREAD

**Issue by SilencerWeb** [telegraf/telegraf#353]
I have to get a user by username. I know Telegram API doesn't give a method for that but maybe using your framework I can do that like using [Tgfancy](https://github.com/GochoMugo/tgfancy).

**Comment by dotcypress** [comment]
@SilencerWeb as you haver mention, Telegram API does't support username resolving.

BTW, Tgfancy uses webpage to parse user info and this approach might stop working any time.
