### ISSUE TITLE
How to disable/enable a command?

### ISSUE THREAD

**Issue by 1valdis** [telegraf/telegraf#354]
Hello there, thanks for outstanding library.
For each set of commands I have a class. My idea is to make them switchable. First what comes to mind is some counterpart of `.command` or `.action` which unsubscribes the function which was previously subscribed, like `add.../removeEventListener` . Is there any?
Second idea is just to check it inside a handler, like `if (!this._enabled) return`, though it gets messy to write it for every single one.
Any other ideas on how to achieve this are appreciated too.

_BTW, while being cool, this library really does lack documentation and JSDoc for functions. I have to go to source many times to check what's happening :(_

**Comment by dotcypress** [comment]
@1valdis Second idea is more real to implement and we have [`optional`](http://telegraf.js.org/#/?id=telegraf-optional) factory for such cases:

```js
const { optional } = require('telegraf')

bot.command('start', optional(_enabled, (ctx) => { }))
bot.action('foo', optional(_enabled, (ctx) => { }))
``` 

Alternatively, you can group all `dynamic` handlers in one sub-bot:

```js
const { Composer, optional } = require('telegraf')

const subBot = new Composer()
subBot.command('start', (ctx) => { })
subBot.action('foo', (ctx) => { })

bot.use(optional(_enabled, subBot))
```

**Comment by 1valdis** [comment]
@dotcypress that is something, beautiful. Thank you very much.
