### ISSUE TITLE
Middlewares are not triggered If I don't return the ctx.reply

### ISSUE THREAD

**Issue by se** [telegraf/telegraf#356]
Hi guys, First, I'm sorry if I'm missing something.

When I want to send a message with the first example, my middleware is triggered successfully;

```javascript
bot.on('text', (ctx) => ctx.reply("Hi there!"))
```
But when I use that. No chance...

```javascript
bot.on('text', (ctx) => {
  // Explicit usage
  ctx.telegram.sendMessage(ctx.message.chat.id, `Hello ${ctx.state.role}`)

  // Using shortcut
  ctx.reply(`Hello ${ctx.state.role}`)
})
```

Is this bug or? 

telegraf version: 3.17.8

**Comment by dotcypress** [comment]
@se could you provide more input, cause given code looks totally fine?

**Comment by dotcypress** [comment]
@se actually `next()` resolves with a processing result, and for fix it you need to return context from handler

```js
bot.on('text', (ctx) => {
  ctx.reply('This will not be handled by middleware.')
  ctx.reply('Why ?')
  ctx.reply('I want to send many mess.')
  return ctx.reply('Help 🆘')
})
```
or 
```js
bot.on('text', (ctx) => {
  return Promise.all([
    ctx.reply('This will not be handled by middleware.'),
    ctx.reply('Why ?'),
    ctx.reply('I want to send many mess.'),
    ctx.reply('Help 🆘')
  ])
})
```

**Comment by se** [comment]
@dotcypress Your second one is correct. But first one is also wrong because If you do that, Middleware only will catch the last one which is `ctx.reply('Help 🆘')`.

Thank you. I have updated my code. But maybe mentioning this can help people about middlewares and sending multiple messages with Promise.
