### ISSUE TITLE
Commands are not registered if declared after .on('message') invokation

### ISSUE THREAD

**Issue by claudiodangelis** [telegraf/telegraf#357]
I don't know if this is an issue or an undocumented expected behavior, but in the following snippet, the command `hi` is not registered (the bot does not react to it):

```js
const bot = new Telegraf(process.env.BOT_TOKEN)
bot.on('message', ctx => {
    /* some code */
})
bot.command('hi', ctx => {
    ctx.reply('hi!')
}
```

However, if `bot.command` is declared **before** `bot.on` everything works fine:

```js
const bot = new Telegraf(process.env.BOT_TOKEN)
bot.command('hi', ctx => {
    ctx.reply('hi!')
}
bot.on('message', ctx => {
    /* some code */
})
```

 Is this an expected behavior? Thanks.

**Comment by dotcypress** [comment]
@claudiodangelis yes, this is expected behavior, cause `command` is subtype of `message`.
