### ISSUE TITLE
Jump to another command

### ISSUE THREAD

**Issue by watchdots** [telegraf/telegraf#359]
Hi.
I want jump to another command in my code.
`bot.on('cmd1',(ctx)=>jumpToCommand('cmd2'))
bot.on('cmd2',(ctx)=>ctx.reply('hi'))`
So if user in telegram sends /cmd1, bot send to user 'hi'
How can I do It?!

**Comment by 1valdis** [comment]
As a quick and dirty workaround you can make your handlers named functions/variables and call them like:
```javascript
const cmd2 = ctx => ctx.reply('hi')
const cmd1 = ctx => cmd2()

bot.on('cmd1', cmd1)
bot.on('cmd2', cmd2)
```
Don't know about if there any built-in Telegraf options for this one.
