### ISSUE TITLE
Wrong order of messages

### ISSUE THREAD

**Issue by Galdias** [telegraf/telegraf#360]
The issue is simple - i am sending multiple messages in one response, but is seems like Promise dont giva a thing about order... here is the code

```
http.createServer(function (req, res, next) {
  const token = req.url.substr(1);
  const bot = new Telegraf(token);
  const webhookCb = bot.webhookCallback(req.url);
  webhookCb(req, res, next);
  bot.on('message', (ctx) => {
    ctx.reply('Hey there!').then(
      ctx.replyWithPhoto('https://picsum.photos/200/500/').then(
        ctx.reply('Hey there!').then(
        )
      )
    );
  });
}).listen(3000);
```

So every 4-5 messages the image appears at 1st place or at the end. Any ideas on how to fix this?

**Comment by Otto-AA** [comment]
One error I noticed: You are giving `.then` not the function, but the output of the function.
Instead of `.then(ctx.reply('Hey there!'))`
write         `.then(() => ctx.reply('Hey there!'))` or `.then(function () { ctx.reply('Hey there!'); })`

**Comment by glococo** [comment]
Async/Await works flawless:
await ctx.reply("Hi1")
await ctx.reply("Hi2")
and so on...
