### ISSUE TITLE
How can deploy telegram bot with telegraf on heroku

### ISSUE THREAD

**Issue by watchdots** [telegraf/telegraf#363]
Hi.
I deploy a bot on heroku and get this error:
`Stopping process with SIGKILL
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
 heroku[web.1]: Process exited with status 137
 heroku[web.1]: State changed from starting to crashed`
I think that should use webhook and set it on heroku but I can't. Telegraf says that it can't set port of webhook on limited number of ports.
What should I do?!

**Comment by watchdots** [comment]
https://github.com/telegraf/telegraf/issues/44
This link helped me! 
Please add this subject in document and telegraf.js.org.
Thanks and Sorry a lot.

**Comment by sachaysl** [comment]
Same problem!

**Comment by sachaysl** [comment]
I really don't think it's helpful to redirect people to other semi-relevant issues. Something as basic as this should really be explained more formally

**Comment by nnqq** [comment]
@watchdots  @hackingclimate 
Heroku kills process because it can't start listen port. You can use Long-Polling bot with Heroku, but you should also connect Express (not for Bot, just to open port for Heroku). This will work, e.g. below:
**Note: You shouldn't set environment variable PORT. Heroku will set PORT itself**
```javascript
const Telegraf = require('telegraf')
const express = require('express')
const expressApp = express()

const port = process.env.PORT || 3000
expressApp.get('/', (req, res) => {
  res.send('Hello World!')
})
expressApp.listen(port, () => {
  console.log(`Listening on port ${port}`)
})

const bot = new Telegraf(process.env.BOT_TOKEN)
bot.hears(/./, (ctx) => ctx.reply('Hello'))
bot.startPolling()
```

**Comment by Aaron-Vasilev** [comment]
In version telegraf: "^4.12.2" it looks like this:
_Plus you don't need to use express_. 
And as an @nnqq mentioned:
**You shouldn't set environment variable PORT. Heroku will set PORT itself**

```
import http from 'http'

http.createServer((req, res) => {
  res.writeHead(200, {'Content-Type': 'text/plain'})
  res.write('Hello World!')
  res.end()
}).listen(+process.env.PORT)

bot.launch()
```
