### ISSUE TITLE
Limit scene sequential change in wizard with a particular user action only

### ISSUE THREAD

**Issue by choonfahh** [telegraf/telegraf#366]
I'm utilizing the wizard to do a bot sequence, which is initiated by the user clicking on an inline button. 

```
const recommendProcess = new WizardScene(`recommend-process`,
  (ctx) => {
    select(ctx)       // Step 1: Select Song
  },
  (ctx) => {
    explain(ctx)      // Step 2: Explain Why
  },
  (ctx) => {
    dedicate(ctx)     // Step 3: Dedicate Message
  },
  (ctx) => {
    deliver(ctx)      // Step 4: Deliver Recommendation
  }
)
```
Below is a sample of one of the sequence in the scene:
```
function dedicate(ctx) {
  return console.log("User dedicating song"),
         ctx.reply("Any message for the user? If you don't have any, type 'no'."),
         ctx.wizard.next()
}
```
However, I would like to only limit the user interactions to 'message' only, excluding 'callback_query' in order for them to move onto the next step.

I understand `ctx.wizard.next()` doesn't have any parameters, so is there a way to limit it? I've been looking through the wizard bot example and the documentation but I can't find anything.

Thanks!

**Comment by dotcypress** [comment]
@choonfahh great question!

You can easily filter messages with `mount` helper:

```js
const { mount } = require('telegraf')

const recommendProcess = new WizardScene(`recommend-process`,
  mount('message', (ctx) => {
    select(ctx)       // Step 1: Select Song
  }),
  mount('message', (ctx) => {
    explain(ctx)      // Step 2: Explain Why
  }),
  mount('message', (ctx) => {
    dedicate(ctx)     // Step 3: Dedicate Message
  }),
  mount('message', (ctx) => {
    deliver(ctx)      // Step 4: Deliver Recommendation
  })
)
```

**Comment by choonfahh** [comment]
Thanks! @dotcypress

I think the documentation for the wizard can be further worked for clarity and I'll be willing to help in that too.

I have another question - I've been playing around with the update_types but I realize there's no way to distinguish a normal text from a command. Yet on the other hand, a command can be distinguished from a normal text. Is there any way to do that?

**Comment by dotcypress** [comment]
@choonfahh sure, you can do that like in following snippet:
```js
const { mount, command,  hears } = require('telegraf')

const recommendProcess = new WizardScene(`recommend-process`,
  mount('message', (ctx) => {
    select(ctx)       // Step 1: Select Song
  }),
  mount('message', (ctx) => {
    explain(ctx)      // Step 2: Explain Why
  }),
  command('test', (ctx) => {
    dedicate(ctx)     // Step 3: Dedicate Message
  }),
  hears('done', (ctx) => {
    deliver(ctx)      // Step 4: Deliver Recommendation
  })
)
```
