### ISSUE TITLE
loader middleware

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#37]
I would like to have a middleware that does the following

-inserts animated gif into current chat
-waits for an event or callback
-upon completion, the initial gif message is edited with the actual reply you wanted in the first place.

```
bot.on('something', loaderMiddleware(), (ctx) =>
// a function that takes a longgg time (5+ seconds)
// when complete, event is triggered, or a callback occurs.
// ctx.reply( here is the payload ) ;
); 
```

is it possible to create a middleware like this?
Ideally I would like some kind of progress bar indicator, but I understand that's a lot of added complexity.

**Comment by dotcypress** [comment]
Closed in favor of #49
