### ISSUE TITLE
Failed to fetch updates. Waiting: 1s 500: Unsupported message from Telegram

### ISSUE THREAD

**Issue by jsu93** [telegraf/telegraf#370]

**Comment by jsu93** [comment]
pm2 logs above error message, and my bot didn't work anymore. I think it's telegraf's bug.

**Comment by jsu93** [comment]
update to latest version solve the problem

**Comment by jsu93** [comment]
Today I have seen this error too, this will help:
https://github.com/fuerbringer/tldr-telegram/issues/5

**Comment by ksaitor** [comment]
suddenly experiencing this issue now

**Comment by vpotseluyko** [comment]
Looks like it's related to telegram servers down.

**Comment by iinsta** [comment]
I have this issue too... and many times

**Comment by user0107** [comment]
It happens even with Webhook.
Something is going wrong.

**Comment by Khuzha** [comment]
I have this error too
