### ISSUE TITLE
How to wrap text in buton to multipel line?

### ISSUE THREAD

**Issue by parsarian** [telegraf/telegraf#373]
In bot, I want to  wrap text in to multiple line. Now it show only part of that.

![image](https://user-images.githubusercontent.com/25129775/37338908-179ecf6e-26ce-11e8-896d-992be0d3c0f5.png)

**Comment by Piterden** [comment]
`{ columns: 2 }`

**Comment by parsarian** [comment]
@Piterden , So thankful for your reply.  no any other way to show full text like reducing font size or removing bold attribute of caption?
