### ISSUE TITLE
.replyWithMarkdown bold issue

### ISSUE THREAD

**Issue by roccomuso** [telegraf/telegraf#374]
```javascript
ctx.replyWithMarkdown(`Hello **world**`)
```

the "hello" word in response is not in bold as expected.

**Comment by dotcypress** [comment]
Telegram supports only small subset of Markdown, and for your case:

```js
ctx.replyWithMarkdown(`Hello *world*`)
```

**Comment by Alynva** [comment]
This is so strange, in [one page](https://core.telegram.org/api/entities) (for end users) they say double asterix, and [this other page](https://core.telegram.org/bots/api#markdown-style) (for bots) say just one asterix
