### ISSUE TITLE
deleteMessage method is not working

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#375]
I'm using the latest 3.19.0 version of Telegraf and when I wanna delete message, the second parameter is not transmitted. I tried to send message_id in context and also explicitly indicating in string but all the same - message to delete not found! In 3.17v anything was fine. Can anybody check this?

**Comment by robverhoef** [comment]
This was confusing for me too.
Looking at https://github.com/telegraf/telegraf/blob/develop/docs/examples/self-cleaning-scenes.js there is only one parameter; the messageId. That appears to be working just fine. 
Don't use the chat_id when using ctx.deleteMessage.

I'm new to Telegraf and the documentation is often somewhat difficult to grasp…
But in https://github.com/telegraf/telegraf/blob/develop/core/context.js line 461 it accepts only one parameter.
In https://github.com/telegraf/telegraf/blob/develop/telegram.js there is a deleteMessage too (line 308) that accepts 2 parameters; chatId and messageId. I haven't tried this one yet.

**Comment by dotcypress** [comment]
@robverhoef most of `Context` methods is shortcuts to `Telegram` with prebinded `chat_id`.

Context already knows chat_id/message_id:
```js
ctx.telegram.deleteMessage(chatId, messageID) //Delete any message in any chat
ctx.deleteMessage(messageID) //Delete message in current chat with messageID
ctx.deleteMessage() //Delete current message in current chat
```
