### ISSUE TITLE
"middleware" on bot.sendmessage

### ISSUE THREAD

**Issue by lenny76** [telegraf/telegraf#377]
hi,
is it possible to create a middleware every time a .sendmessage call is done?
I have a lot of .sendmessage in many function, ad I'd like to run a function without modifying every line of code.

thanks

**Comment by tva10** [comment]
Hello
How about creating your own .sendMessage which you will add in context?

```javascript

bot.use((ctx, next) => {
  ctx.mySendMessage = function(id, msg){
   return telegram.sendMessage( id, msg )
     .then(function(){ /*do smth*/ })
     .catch(function(){ /*do smth*/ });
  };
  return next();
})

bot.on('text', (ctx, next) => {
   return ctx.mySendMessage( .... )
})

```

**Comment by lenny76** [comment]
hi
trying this code but I get an error
TypeError: Cannot read property 'callApi' of undefined

    const sendMessage = bot.telegram.sendMessage;
    bot.telegram.sendMessage = (...args) => {
        sendMessage(...args).then((m) => {
            console.log("ok");
        });
    }


any suggestion?

**Comment by 1valdis** [comment]
@lenny76 by doing `const sendMessage = bot.telegram.sendMessage;` and then `sendMessage(...)`, you're losing `this` in `sendMessage` method. That's how Javascript works. You must bind `sendMessage` to context, like so: `const sendMessage = bot.telegram.sendMessage.bind(bot.telegram);` (notice bind call on `ctx.reply` function in my previous post).
