### ISSUE TITLE
News feed example

### ISSUE THREAD

**Issue by ButuzGOL** [telegraf/telegraf#380]
Do you have some news feed example 
so mostly i want to build bot which will give me info every 3 hours
?

**Comment by ButuzGOL** [comment]
As i understand the only solution is cron job or setInterval ?

**Comment by TiagoDanin** [comment]
Use the [cron](https://www.npmjs.com/package/cron) in my bot.
Example: [TiagoDanin/TTgram/index.js - Line 193](https://github.com/TiagoDanin/TTgram/blob/e0da820ab6dc0323e8a83da46bee20fabaf3e446/index.js#L193)

**Comment by ButuzGOL** [comment]
thanks
