### ISSUE TITLE
InlineKeyboardButtons keep the loading circle turning on Android...

### ISSUE THREAD

**Issue by MohGanji** [telegraf/telegraf#383]
### Steps to reproduce
1.Generate an InlineKeyboardButton and send it as an InlineKeyboardMarkup in `editMessageText()`
2.The user clicks on this key on his Android phone, causing a callback handler to be called on the bot's side.
3.Eventually the bot generates a new page including new inlineKeyboardButtons (with exactly the same text and same callback query data) and send it to the user in the next `editMessageText()`. However, the new inlineKeyboardMarkup button still keeps that loading turning circles!

### Expected behaviour
The loading circle should disappear after a new inlineKeyboardButton is sent to the user via `editMessageText()`

### Actual behaviour
The new inlineKeyboardButtons (with text similar to previous ones) keep their turning loading circle. This happens only on Android Telegram clients and not on iOS/Windows clients.
and in my case it only happens if the buttons have the same `data` attribute

**Comment by dotcypress** [comment]
@MohGanji I believe this is Android client bug.
Anyway, when you call `editMessageText` with same data, Telegram will throw error, and here we have only one way to hide loading circle: `ctx.answerCbQuery()`

**Comment by MohGanji** [comment]
@dotcypress thanks.
I googled and found out that I can use telegrams `answerCallbackQuery` or in your wrapper `ctx.answerCbQuery` to hide the loading circle, but I thought this is just a dirty way to get things done and I wanted to know if there was a better way.
thank you anyway, I look forward to hearing about this issue getting fixed.

**Comment by kevrat** [comment]
Same. 
ctx.answerCbQuery does not work in the official Android client, but it works in the web version.
I reported this in support.
My code:
```js
function menuStart() {
    return Markup.inlineKeyboard([
        Markup.callbackButton('Играть', 'game'),
        Markup.callbackButton('Правила', 'rules')
    ]).extra()
}
bot.action('main', (ctx) => {
    ctx.editMessageText('Главное меню', menuStart())
    ctx.answerCbQuery()
})
bot.action('rules', (ctx) => {
    ctx.editMessageText('Правила', Extra.HTML().markup(m => m.inlineKeyboard([
        m.callbackButton('Назад', 'main')
    ])))
    ctx.answerCbQuery()
})
```
