### ISSUE TITLE
Why bot suddenly crashed?

### ISSUE THREAD

**Issue by parsarian** [telegraf/telegraf#385]
This code was working properly one month ago but since last night it was crashing.

`
(node:3848) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: message is not modified at buildConfig.then.then.then.then (D:\apps\bot\node_modules\telegraf\core\network\client.js:235:17) at at process._tickCallback (internal/process/next_tick.js:118:7) (node:3848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:3848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
code :
```

app.action('start', (ctx) => {
    http.get('http://localhost:3000/api/questions', (res) => {
        //res.setEncoding('utf8');
        let rawData = '';
        res.on('data', (chunk) => {
            rawData += chunk;
        });
        res.on('end', () => {
            try {
                data = JSON.parse(rawData);
                i = Object.keys(data).length;
                ctx.editMessageText('Choose one of the options:', 
                Extra.HTML().markup(m => m.inlineKeyboard([
                    m.callbackButton(data[x].Q1, 'plus1'),
                    m.callbackButton(data[x].Q2, 'plus2')
                ], {
                    columns: 1
                })));
            } catch (e) {
                console.error(e.message);
            }
        });
    }).on('error', (e) => {
        console.error(`Got error: ${e.message}`);
    });
});

app.action('plus1', (ctx) => {
    if (x < i) {
        answer[x] = 1;
        ctx.editMessageText('Choose one of the options:', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton(data[x].Q1, 'plus1'),
            m.callbackButton(data[x].Q2, 'plus2')
        ], {
            columns: 1
        })));
        x++;
    } else {
        ctx.editMessageText('Finished :', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton('Result', 'result')
        ])));
    }
});

app.action('plus2', (ctx) => {
    if (x < i) {
        answer[x] = 2;
        ctx.editMessageText('Choose one of the options', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton(data[x].Q1, 'plus1'),
            m.callbackButton(data[x].Q2, 'plus2')
        ], {
            columns: 1
        })));
        x++;
    } else {
        ctx.editMessageText('Finished :', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton('Result', 'result')
        ])));
    }});

app.action('result', (ctx) => {
    ctx.reply(answer);
});
app.startPolling();
```

**Comment by tva10** [comment]
Hello @parsarian 
Then you use `editMessageText` and send to user same content which is not diffs to previous edition of that message - Telegram Bot Api returns this error - `Error: 400: Bad Request: message is not modified`

So and in your app you don't handle any error `In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`
You can try to handle this error
``` javascript
ctx.editMessageText( .... ).catch( function(error){ console.error(error); } );
```
or any other errors in your bot
``` javascript
app.catch(function(err){ console.log(err); });
```

**Comment by rsa408** [comment]
Hi @tva10 , thanks for your help.

After adding those lines to code this error shows up when clicking on first option of first question. and after second click on answer it continue to ask a question for the end and nothing wrong happens. only on first question.
```

{ Error: 400: Bad Request: message is not modified at buildConfig.then.then.then.then (D:\apps\bot\node_modules\telegraf\core\network\client.js:235:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: message is not modified' },
  description: 'Bad Request: message is not modified',
  parameters: {},
  on:
   { method: 'editMessageText',
     payload:
      { chat_id: 52886869,
        message_id: 329,
        text: 'Choose one of the options:',
        parse_mode: 'HTML',
        reply_markup: [Object] } } }
```

**Comment by parsarian** [comment]
Hi @tva10 , thanks for your help.

After adding those lines to code this error shows up when clicking on first option of first question. and after second click on answer it continue to ask a question for the end and nothing wrong happens. only on first question.
```

{ Error: 400: Bad Request: message is not modified at buildConfig.then.then.then.then (D:\apps\bot\node_modules\telegraf\core\network\client.js:235:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: message is not modified' },
  description: 'Bad Request: message is not modified',
  parameters: {},
  on:
   { method: 'editMessageText',
     payload:
      { chat_id: 52886869,
        message_id: 329,
        text: 'Choose one of the options:',
        parse_mode: 'HTML',
        reply_markup: [Object] } } }
```

**Comment by tva10** [comment]
@parsarian 
First of all, I think `plus2` works fine (without error) on first query, because you have not colon `:` in `plus2` editMessage. 

But I think that your Questions seems the same on first two clicks ( `start` and `plus1` or `plus2` )
Ie, you press `start` and you have EditMessage with `data[0]` Questions. After that you press `plus1` and you have got set answered[0] and EditMessage with `data[0]` Questions. 
Are they the same in that case, arn't they?
If the same, move `x++`

Hope that will work/

**Comment by rsa408** [comment]
Dear @tva10 Thank you so much for your pay attention,
The bot logic is: fetching over 60 pairs of questions like: 

by choosing preferred sentence next question appears.  In the first question, this happens(I start from the beginning for both choices).
![image](https://user-images.githubusercontent.com/4402631/38175962-cf2be528-35fa-11e8-9917-484b7777ca84.png)
after the second click, it goes to end without any problem.

For  Sessions recommendation, I am so thankful. I will use it absolutely.

**Comment by tva10** [comment]
@rsa408, don't know how to explain right, but Im trying to hint that error happens from wrong logic at start and first answers. After press start, and first answer (plus1 or plus2) you try to send same Questions (where `data[0]`) to user and that repeat cause our error

Tried out to rewrite your example as I see. Did not check it but should work
```javascript
const session = require('telegraf/session');

app.use( session() );

// ......

app.action('start', (ctx) => {
    http.get('http://localhost:3000/api/questions', (res) => {
        //res.setEncoding('utf8');
        let rawData = '';
        res.on('data', (chunk) => { rawData += chunk; });
        res.on('end', () => {
            try {
                data = JSON.parse(rawData);     //  if questions are unique for each user, u can save them in session too
                                                //  or cache them in global variable once and don't query each time...
                sendNextQuestion( ctx );
            } catch (e) {
                console.error(e.message);
            }
        });
    }).on('error', (e) => {
        console.error(`Got error: ${e.message}`);
    });
});

function sendNextQuestion( context ) {
        if( !context.session.x && context.session.x !== 0 ){ /// Init, if it is first start
            context.session.x = 0;
            context.session.answer = [];
        } else {
            context.session.x++;
        }

        if( context.session.x < Object.keys(data).length ){ // or data.length
            return ctx.editMessageText('Choose one of the options:', Extra.HTML().markup(m => m.inlineKeyboard([
                m.callbackButton(data[x].Q1, 'plus1'),
                m.callbackButton(data[x].Q2, 'plus2')
            ], {
                columns: 1
            })));
        } else {
            return ctx.editMessageText('Finished :', Extra.HTML().markup(m => m.inlineKeyboard([
                m.callbackButton('Result', 'result')
            ])));
        }
};

function setAnswer( context, value ){
        // mb need check if 'answer' exists in session ...
        context.session.answer[context.session.x] = value;
};


app.action('plus1', (ctx) => {
    setAnswer( ctx, 1 );
    return sendNextQuestion( ctx );
});

app.action('plus2', (ctx) => {
    setAnswer( ctx, 2 );
    return sendNextQuestion( ctx );   
});

app.action('result', (ctx) => {
    ctx.reply(/* do stuff with ctx.session.answer */);
});

app.catch( function( err ){
    sails.log.error( err );
});

app.startPolling();
```

**Comment by rsa408** [comment]
Dear @tva10 , I am so so thankful for your help and making time for me. Since yesterday I am trying to solve an error of "`sendNextQuestion( context )`" function, after getting /start command this message send to console:

`Cannot read property 'x' of undefined`
![image](https://user-images.githubusercontent.com/4402631/38230619-0619097e-3724-11e8-8d70-2c123ebecf3e.png)

what is your Idea?

Thanks

**Comment by parsarian** [comment]
Dear @tva10 , I am so so thankful for your help and making time for me. Since yesterday I am trying to solve an error of "`sendNextQuestion( context )`" function, after getting /start command this message send to console:

Cannot read property 'x' of undefined
![image](https://user-images.githubusercontent.com/25129775/38233804-1d5abcf6-3731-11e8-8aaf-e794f34d74b9.png)


what is your Idea?

Thanks

**Comment by tva10** [comment]
@parsarian yep, because Im forgot to move `m.callbackButton(data[x].Q1, ....)`  to `context.session.x`

**Comment by parsarian** [comment]
@tva10 I checked but still the same 😔. I manipulated but nothing changed.

**Comment by tva10** [comment]
@parsarian 
Checked out my solution, works fine (after fixing access to ctx and context.session.x)
Mb you tried to access to `x` somewhere else?
Im updated my solution again. You can copy it to an empty project, install telegraf, set bot token and run it

**Comment by parsarian** [comment]
@tva10 Believe me, as you said, I made a new project and the fallowing code is what I copy,pasted on :
But the line  : 
`app.action('start', (ctx) => {` should be like `app.command('start', (ctx) => {`  to start and line 
`sendNextQuestion(ctx);` seems incorrect because of _`ctx is not defined`_ message, and I changed to `sendNextQuestion(data);` but steel _`Cannot read property 'x' of undefined`_ message appear.

```
const session = require('telegraf/session');
const Telegraf = require('telegraf');
const app = new Telegraf(Mytoken);
app.use(session());
const http = require('http');
const {    Extra,    Markup } = require('telegraf');

app.command('start', (ctx) => {
    http.get('http://localhost:3000/api/questions', (res) => {
        //res.setEncoding('utf8');
        let rawData = '';
        res.on('data', (chunk) => {
            rawData += chunk;
        });
        res.on('end', () => {
            try {
                data = JSON.parse(rawData); //  if questions are unique for each user, u can save them in session too
                //  or cache them in global variable once and don't query each time...
                sendNextQuestion(data);
            } catch (e) {
                console.error(e.message);
            }
        });
    }).on('error', (e) => {
        console.error(`Got error: ${e.message}`);
    });
});

function sendNextQuestion(context) {
    if (!context.session.x && context.session.x !== 0) { /// Init, if it is first start
        context.session.x = 0;
        context.session.answer = [];
    } else {
        context.session.x++;
    }

    if (context.session.x < Object.keys(data).length) { // or data.length
        return ctx.editMessageText('Choose one of the options:', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton(data[context.session.x].Q1, 'plus1'), // no x
            m.callbackButton(data[context.session.x].Q2, 'plus2')
        ], {
            columns: 1
        })));
    } else {
        return ctx.editMessageText('Finished :', Extra.HTML().markup(m => m.inlineKeyboard([
            m.callbackButton('Result', 'result')
        ])));
    }
};

function setAnswer(context, value) {
    // mb need check if 'answer' exists in session ...
    context.session.answer[context.session.x] = value;
};


app.action('plus1', (ctx) => {
    setAnswer(ctx, 1);
    return sendNextQuestion(ctx);
});

app.action('plus2', (ctx) => {
    setAnswer(ctx, 2);
    return sendNextQuestion(ctx);
});

app.action('result', (ctx) => {
    ctx.reply( /* do stuff with ctx.session.answer */ );
});

app.catch(function (err) {
    console.error(err);
});

app.startPolling();
```

**Comment by tva10** [comment]
@parsarian , Nope, sendNextQuestion, receive context as param. `data` object with questions will be stored as global variable
`and line sendNextQuestion(ctx); seems incorrect because of ctx is not defined message, and I changed to sendNextQuestion(data); but steel Cannot read property 'x' of undefined message appear.`

ctx is not defined message appears because forgot to rename `ctx` to `context` at `return ctx.editMessageText('Choose one of the options:',...` and `return ctx.editMessageText('Finished :',` lines

**Comment by parsarian** [comment]
Great thanks @tva10, So many thanks I've learned so many things.

**Comment by na-zi-ya** [comment]
Hey....!! can anyone help me in fixing my bot issue...3 months ago it was working fine...now suddenly its showing error what might be the issue ....? 
im new to nodejs.....i'm not using same token for different bot...any kind of help will be greatly appreciated.
![image](https://github.com/telegraf/telegraf/assets/76842801/9505d6e1-21ff-4a65-ab90-88e0bf180945)
![image](https://github.com/telegraf/telegraf/assets/76842801/cf433df9-1930-4268-b9ab-17953e9fa230)

**Comment by MKRhere** [comment]
@naz-i-ya Don't bump an old issue with an unrelated message. [Open a new issue here instead](https://github.com/telegraf/telegraf/issues/new/choose).
