### ISSUE TITLE
Comparison against yagop/node-telegram-bot-api and other libraries

### ISSUE THREAD

**Issue by Aparus** [telegraf/telegraf#386]
Hi! 
I have completed one project with [yagop/node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api). Unfortunately, your project appears in google far away, and in youtube there is many screencasts with yagop library. And I noticed your project too far, but I liked it because of laconic code.  

Please, can you explain main differences of your project from yagop's ? 
Sorry for issue, but I didn't find any other place for feedback to send this question.

**Comment by dotcypress** [comment]
Hi @Aparus 

Key differences:
- Full BotAPI support
- Lightweight deps http://npm.anvaka.com/#/view/2d/node-telegram-bot-api vs http://npm.anvaka.com/#/view/2d/telegraf
- [Send request in response to update](https://core.telegram.org/bots/faq#how-can-i-make-requests-in-response-to-updates)
- First class middleware support(killer feature)
- Tons of examples, [scaffolding tools](https://github.com/telegraf/create-bot), [zero config bot runner](https://github.com/telegraf/micro-bot)

**Comment by Aparus** [comment]
@dotcypress , I think you should add this info into the main page , it's really useful for newbies who are seeking tg-framework at first time in their life.

**Comment by anatoly314** [comment]
Is there any significant difference now, two years later? It looks like [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api) more popular. Don't want to start the holywar, just want to know which one to choose for my needs.

**Comment by KnorpelSenf** [comment]
First, I should say that I have used a number of different frameworks in production, but not node-telegram-bot-api yet (only for playing around).

That said, I believe that the points outlined above are still valid today. We're not far away from releasing 4.0 which ships with Telegram Bot API 5.0 support that was released less than a month ago. node-telegram-bot-api's latest commit was six weeks before that ([ref](https://github.com/yagop/node-telegram-bot-api/commit/fc24d0dc4d45fb3eabe97f43325d662f18bf64c0)).

`telegraf` is still using much fewer dependencies. This might not be the issue for you, but especially in serverless environments it is important to keep startup times low for cold starts, and [dependencies are the top three important things to keep in mind](https://medium.com/@duhroach/improving-cloud-function-cold-start-time-2eb6f5700f6) there.

It is a dealbreaker for me not to have TypeScript support, which node-telegram-bot-api does not provide. While having had mediocre TypeScript support in the past, `telegraf` is now close to being fully typed with advanced inference systems that have access to the full Telegram API, hence giving you every single property in autocomplete right at your fingertips. This is also coming in 4.0, the code is mostly written for that.

While a bot is a complete middleware system in `telegraf`, in node-telegram-bot-api it is a plain event emitter. For small projects you probably won't notice the difference in convenience, but if you are planning ahead, I have my doubts about node-telegram-bot-api being flexible enough to fit your needs. The existence of https://github.com/idchlife/node-telegram-bot-api-middleware proves this IMO.

`telegraf` is used less, when comparing npm downloads per week. I cannot say much about the ecosystem around the libraries. While I didn't really miss anything yet for `telegraf`, it might well be that node-telegram-bot-api has an impressive ecosystem that they do not refer to on the GitHub page.

`telegraf` has worse docs. It is pretty simple to get up and running, there's examples, type annotations, and an active community, but honestly: I learned more about `telegraf` from looking into the implementation than having a nice guide that helps me fix bugs in corner cases. We're working on that, but of course you shouldn't base that decision on promises.

**Comment by wojpawlik** [comment]
> [‎08‎.‎02‎.‎2018 ‎14‎:‎46]
> I need to get ntba out of my life eventually

> [‎28‎.‎04‎.‎2020 ‎16‎:‎48]
Last time I checked, ntba provided no middleware, matching only on type and via regex, and required you to import bot everywhere and pass chat id to everything

> [‎14‎.‎07‎.‎2019 ‎09‎:‎30]
How to disable handling forwards in ntba (please don't): https://bitbucket.org/GingerPlusPlus/rextester-bot/src/cddd0eae01d12d04c1dc4601e7a525287c7fbe87/main.ls#lines-103
> 
> Telegraf doesnt process forwards by default iirc, but still, if I wanted to filter out some updates, I can do that by just adding a handler / middleware
