### ISSUE TITLE
Can Telegram Bots talk to each other

### ISSUE THREAD

**Issue by hallmayer** [telegraf/telegraf#389]
Hello, 
Im try to let telegram bots talk to each other but i can't do it. 
I have added both bots to a group but the bots just read messages of users. Is there any solution? 

Here is my Code:
```
const Telegraf = require('telegraf')

const bot = new Telegraf('***')
bot.command('/oldschool', (ctx) => ctx.reply('Hello'))
bot.command('/modern', ({ reply }) => reply('Yo'))
bot.command('/shutdown_PC', ({ reply }) => reply('Shutdown'))
bot.command('/hipster', Telegraf.reply('?'))
bot.startPolling()
```

**Comment by 1valdis** [comment]
If you check the official Telegram Bot API documentation, you can find out that bots don't see messages of each other. It is done so exactly to avoid what you're trying to do.
