### ISSUE TITLE
New chat member

### ISSUE THREAD

**Issue by voroncv** [telegraf/telegraf#393]
How can I send a message to the new member in the group only to the newest member? That this message was in the group, but others did not see it.

**Comment by CQBinh** [comment]
I think you have to create a new private chat with him/her.

**Comment by robverhoef** [comment]
I don't think this is possible.
Yes, you should use a private chat. However, there is this Telegram API limit; 

> Bots can't initiate conversations with users. A user must either add them to a group or send them a message first.

(https://core.telegram.org/bots#4-how-are-bots-different-from-humans)

**Comment by athimannil** [comment]
@robverhoef I am afraid chance to get spam report.
