### ISSUE TITLE
AWS lambda fetch error issue.

### ISSUE THREAD

**Issue by margor666** [telegraf/telegraf#394]
Hello, help please.
I have deployed bot with apex/up to aws lambda. from this [tutorial](https://www.youtube.com/watch?v=JR0RC6OFZ5M) 
bot is working with webhooks, but i have issue sending more then one answer.
i got  this error: 

> (node:16)

 UnhandledPromiseRejectionWarning: FetchError: request to https://api.telegram.org/bot<mytoken>/sendMessage failed, reason: socket hang up

> 

**example:** 
var moderator = myuserID;
var sticker = 'CAADBAADjgEAAmFNcgMrOokiECRTJAI'
bot.command('test', (ctx) => {
ctx.reply('one message')
.then(() => ctx.reply('second one')
.then(() => bot.telegram.sendSticker(moderator, sticker))
}

He sends only one message. only first.

but if im starting to flood bot with this command he sometimes sends . but from first attempt he stuck

**Comment by margor666** [comment]
finded solution, its telegrafjs promises issue. Folded replies with "return Promise.all([]) "
and have to use full commands, not shortcuts. 
ctx.reply('message') is still sending one message, i think its something with stage,scene middleware.

but bot.telegram.sendMessage(userId, 'text') work fine with many executable.

**Comment by yangwao** [comment]
I'm trying run telegraf on stdlib and I think I've ran into same issues 🤔

Definitely would be good serverless example, if you want to troubleshoot, I'm willing to write article to help others, hit me up https://t.me/yangwao
Cheers
