### ISSUE TITLE
Send a photo from local computer

### ISSUE THREAD

**Issue by arefaslani** [telegraf/telegraf#395]
[This](http://telegraf.js.org/#/?id=sendphoto) is the documentation of the sendPhoto method. In the docs type of the photo is `File`. How could I send a photo from local computer? I've tested this:
```javascript
const response = await telegram.sendPhoto(
    process.env.TELEGRAM_CHAT_ID,
    fs.readFileSync("./images/test.png"),
  );
```
but it responds with 400 bad request.

**Comment by dotcypress** [comment]
@arefaslani you can see exampled in [library docs](http://telegraf.js.org/#/?id=working-with-files)

Couple of solutions:

```js
const response = await telegram.sendPhoto(
    process.env.TELEGRAM_CHAT_ID, {
      source: "./images/test.png"
   }
);

const response = await telegram.sendPhoto(
    process.env.TELEGRAM_CHAT_ID, {
      source: fs.readFileSync("./images/test.png")
   }
);
```

**Comment by stefanocudini** [comment]
how can I send a Buffer contains a photo? using ctx.replyWithPhoto(... ???
