### ISSUE TITLE
Bot doesn't answer using webhooks on Heroku

### ISSUE THREAD

**Issue by nemyxa** [telegraf/telegraf#396]
Hi there, i think i am going insane. :laughing: 

I wrote bot with telegraf using polling. But on Heroku this thing not working, because needs port, so i decided to use webhooks.
My code looks like:
```javascript
const Telegraf = require("telegraf");
const bot = new Telegraf("12312321123:aNKasdasjKKJQyYsH"); //token for example
const PORT = process.env.PORT || 8443;
const URL = process.env.URL || 'https://my-app-name.herokuapp.com';
// Set telegram webhook
bot.telegram.setWebhook('https://my-app-name.herokuapp.com:8443/bot12312321123:aNKasdasjKKJQyYsH');
// Start https webhook
bot.startWebhook('/bot12312321123:aNKasdasjKKJQyYsH', null, PORT);
```

i push all this stuff to heroku, in logs appears "build succeeded" etc, and my bot starts with npm start script. To remind, all this works flawlessly with polling method, but with webhooks, bot doesn't answer at all. 

 Any response would be appreciated

_sorry for my English_

**Comment by TiagoDanin** [comment]
Remove the port in `setWebhook()`
Example:
`https://my-app-name.herokuapp.com:8443/bot12312321123:aNKasdasjKKJQyYsH` ~> `https://my-app-name.herokuapp.com/bot12312321123:aNKasdasjKKJQyYsH`

PS: I recommend not using your token as "Secret Path"

**Comment by nemyxa** [comment]
@TiagoDanin Thanks, but there's another problem. Looks like everything works fine, but bot still silent.
And now i got this messages on Heroku logs:
```
at=info method=POST path="/bot************" host=my-app-name.herokuapp.com request_id=3e284e2d-cf0c-468c-9a37-b30e26e449c5 fwd="149.154.167.203" dyno=web.1 connect=1ms service=3ms status=200 bytes=94 protocol=https
```

**Comment by nemyxa** [comment]
Okay... I just switched to node-telegram-bot-api and everything works fine.
Maybe i did something wrong, but now it doesn't make sense.
Good luck :heart:
