### ISSUE TITLE
Allow to specify custom context class

### ISSUE THREAD

**Issue by GingerPlusPlus** [telegraf/telegraf#398]
I ask for some way to customize class of the context created right here: https://github.com/telegraf/telegraf/blob/64d43bbbc74df899b86f15328a5cb0bb61e35185/telegraf.js#L119

Because I'm not sure how should it look like (ie. should the class be property on instances of Telegram, or should it be passed in options), I'm opening an issue instead of pull request.

Use case: I'd like to add one method to the context, and override `reply` method.

1. `bot.context` should work fine for adding a method, but with overriding, how do I access the original one? I'd have to do `TelegrafContext.prototype.reply.call` shenanigans...
2. Creating a handler, assigning the methods, and calling `next()` (like in https://github.com/telegraf/telegraf/issues/377#issuecomment-378888250) works, but I don't like it.
3. Inheriting from `TelegrafContext` results in simple, object-oriented code. Original method is accessible via `super`. Sadly, when I create a new context and pass it to `next` as argument, I won't get all of the `bot.context` customizations, and I have to manually `Object.assign` them, which makes the code look not that pretty.

<hr />

Thinking again, it'd also be interesting to be able to use custom `Telegram` as well, for example to rate-limit some functions (https://github.com/thedevs-network/the-guard-bot/issues/26#issuecomment-363555896).

**Comment by GingerPlusPlus** [comment]
Why closing, @dotcypress?

**Comment by dotcypress** [comment]
@GingerPlusPlus Cleaning up old issues, feel free to reopen if issue still a thing

**Comment by GingerPlusPlus** [comment]
As just a contributor, I cannot reopen my issue closed by collaborator; please reopen.

**Comment by dotcypress** [comment]
@GingerPlusPlus what about make `Telegraf` parametrized over `Context`?

Something like:
```js
const Telegraf = require('telegraf')
const { Context } = Telegraf

class MyContext extends Context {
  constructor (update, telegram, options) {
    // Extract custom options if needed
    super (update, telegram, options)
  }

  reply (...args) {
    // Rate-limit logic
    return super.reply(...args)
  }
}

const bot = new Telegraf(process.env.BOT_TOKEN, { contextType: MyContext })
```
