### ISSUE TITLE
How i can remove/clear keyboard

### ISSUE THREAD

**Issue by chek** [telegraf/telegraf#399]
If i do 
`    ctx.reply('Some text here', Extra.markup(
        Markup.keyboard(['First button', 'Second button'])
    ))
`
it stays until i do the same with another buttons.
I want clear keyboard from buttons how i do it?

**Comment by chek** [comment]
Ok found it https://github.com/telegraf/telegraf/issues/51

**Comment by creativeboy1999** [comment]
await ctx.editMessageReplyMarkup({
                reply_markup: { remove_keyboard: true },
            })

**Comment by M1Ergash** [comment]
I is working code but not deleting the keyboard

**Comment by x1q2q** [comment]
> await ctx.editMessageReplyMarkup({ reply_markup: { remove_keyboard: true }, })

this is so helpfull. thanks

**Comment by GatsbyFuture** [comment]
await ctx.editMessageReplyMarkup({
reply_markup: { remove_keyboard: true },
})
this is right and will work
