### ISSUE TITLE
.on( reply?);

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#40]
is there a method in this framework (or in telegram) to determine if a message is a type of message that is reply?

for example

person1: hello

person2: ^replies to this message with "howdy"

is there a way to do like

`bot.something('howdy', (ctx) => {  // stuff });`

**Comment by dotcypress** [comment]
[See reply_to_message](https://core.telegram.org/bots/api#message)


`bot.on('message', (ctx) => console.log(ctx.message.reply_to_message))`
