### ISSUE TITLE
Moving between stages

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#400]
Hi there! Here I have a problem: I am on the some scene and lets say there is 4 stages so situatiots go back or skip stage, moving beetween stages in a nutshell, ctx.scene.enter(sceneId, [defaultState, silent]) I couldn't understand how to use this, state is stages?

**Comment by ouya99** [comment]
+1

**Comment by Enflow-io** [comment]
+1

**Comment by robverhoef** [comment]
If I understand your question correctly, you want to jump between steps in a scene(?).
I do this by keeping a map of all steps in a scene. This requires a little bookkeeping when steps are added or removed. But after that it is easy.
My map:
```
const wizsteps = {
  // to get the correct step number; count the 'async (ctx)' lines
  mainmenu: 0,
  add_stop: 2,
  edit_stop: 6,
  delete_stop: 12
}
```

Example of a jump:

```
ctx.wizard.selectStep(wizsteps.edit_stop)

return ctx.wizard.steps[wizsteps.edit_stop](ctx)

```

**Comment by xsanderblack** [comment]
You can use defaultState to pass data to the scene you want to enter. In that scene data will be available through ctx.scene.state. For example:

```
ctx.scene.enter('someScene', { foo: 'bar' })

someScene.enter((ctx) => {
  ctx.reply(`Data: ${ctx.scene.state.foo}`) // Replies 'Data: bar' to user
})
```

It is also possible to pass data between stages with [ctx.state](https://telegraf.js.org/#/?id=state).

**Comment by vitaliysavich** [comment]
How to achieve the same result in case if step is Composer?) ctx.wizard.steps[3].handler(ctx) ?

**Comment by MKRhere** [comment]
Use Wizard steps to accept new input. Avoid using Wizard to move between steps within the same user input. Often when you do this, you might just want to combine the content of the two steps. You might want `Composer.compose(middleware1, middleware2)` instead of two steps.

But in the case you do need to switch steps, that's a way to do it.
