### ISSUE TITLE
How to send url button?

### ISSUE THREAD

**Issue by Lisennk** [telegraf/telegraf#407]
https://core.telegram.org/bots/2-0-intro#url-buttons

**Comment by dotcypress** [comment]
@Lisennk See examples for details: https://github.com/telegraf/telegraf/blob/develop/docs/examples/echo-bot.js#L6

**Comment by gfiore88** [comment]
Is this works only with inlineKeyboard? Is there any chance to make it work with a custom keyboard button? (see example https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js).

I need a custom button that, when clicked, goes to an URL

**Comment by Piterden** [comment]
If you mean a keyboard which displayed under the message type area, then no, it supports only text buttons writing messages to a chat. Inline keyboard supports also callback and url buttons. You can check this in the telegram bots API docs.

**Comment by gfiore88** [comment]
> If you mean a keyboard which displayed under the message type area, then no, it supports only text buttons writing messages to a chat. Inline keyboard supports also callback and url buttons. You can check this in the telegram bots API docs.

ok thank you!

**Comment by SantiagoAcevedo** [comment]
` Markup.urlButton("NAME", "https://url.com/"),`

**Comment by dr-iroh** [comment]
@SantiagoAcevedo 

For v4
```js
Markup.inlineKeyboard([
  Markup.button.url('Name', 'url')
])
```
