### ISSUE TITLE
how to send image directly

### ISSUE THREAD

**Issue by bwired-nl** [telegraf/telegraf#410]
Hi 
i want to to send an image **directly** to a chat, so not on a reply, but when I want
i know in can send text directly with this
bot.telegram.sendMessage(521695556, "Hello Pikn Im at your command 👍")

this does not work for images
bot.telegram.sendPhoto(521695556,'../../assets/img/db_20180503_095807_867.jpg')

hope you can help

thanks!

**Comment by dotcypress** [comment]
@bwired-nl try following snippet
```js
bot.telegram.sendPhoto(521695556, {source: '../../assets/img/db_20180503_095807_867.jpg'})
```
