### ISSUE TITLE
ctx.reply not always working

### ISSUE THREAD

**Issue by Otto-AA** [telegraf/telegraf#412]
I recently found out, that `ctx.reply(msg)`, `ctx.telegram.sendMessage(chat_id, msg)` and `bot.telegram.sendMessage(chat_id, msg)` don't behave equally in asynchrounous functions. While latter seems to always work, `ctx.reply` and `ctx.telegram.sendMessage` sometimes doen't send messages.

Here is the code I used:
```javascript
bot.command('test', ctx => {
  const chat_id = ctx.message.chat.id;
  setTimeout(() => ctx.reply('context.reply'), 0);
  setTimeout(() => ctx.telegram.sendMessage(chat_id, 'context.telegram'), 0);
  setTimeout(() => bot.telegram.sendMessage(chat_id, 'bot.telegram'), 0);
});
```
with following sent messages:
```
context.telegram
bot.telegram
```
The output also depends on the order of execution. For instance, setting the delay for `ctx.reply` to 1000ms leads to the following output:
```
bot.telegram
context
```

Is this in some way intended behaviour?

(P.S. By using bot.telegram.sendMessage one is on the safe side. So if you also have this problem just go with this version :)

**Comment by tva10** [comment]
Hello @Otto-AA 
Did you use webHook in your bot? webHookReply is enabled?
Mb this issue looks like #320 and your promise chain was broken

**Comment by Otto-AA** [comment]
Thanks, this helped me :)
