### ISSUE TITLE
How to scale the bot?

### ISSUE THREAD

**Issue by anilatalay** [telegraf/telegraf#423]
How can I run the same bot in multiple locations?

**Comment by Otto-AA** [comment]
Some ideas (I currently don't have time for testing):
- Set up all bots to use polling/[getUpdates](https://core.telegram.org/bots/api#getupdates) method and let the interval start at different times (so the first one receives updates at 0.00s, the second one at 0.10s, the third at 0.20s, ...)
- You could assign each server a time interval which it should handle, for instance the first server only handles messages where the date property is between x.00s and x.10s and the second one where the time is between x.11s and x.20s. But with this method each server would still retrieve all request and then decides whether it should process it or not, so it may not be much of an advantage.

If telegraf doesn't provide a function for that (dunno if it does) you may want to take a look at how it works and create your own version of it: 
- [fetchUpdates](https://github.com/telegraf/telegraf/blob/41d2b5f9a19b3e39455d744fcf806211e2448e9a/telegraf.js#L124)
- [handleUpdates](https://github.com/telegraf/telegraf/blob/41d2b5f9a19b3e39455d744fcf806211e2448e9a/telegraf.js#L102)


Hope this input can help you :)

**Comment by Otto-AA** [comment]
This could also be of interest: https://github.com/yagop/node-telegram-bot-api/issues/219

**Comment by Christian-X** [comment]
you'll need a session backend that supports being shared between multiple nodes... 
I'm not aware whether any of the existent  db-based backends are suitable for that.

Apart from that, when using a load balancer of some sorts, you could set it up so that the requests are split up by chat.id - that way chat-relevant context is alway held locally
