### ISSUE TITLE
Add a reference to the telegraf bot instance to the telegrafContext

### ISSUE THREAD

**Issue by lucaelin** [telegraf/telegraf#425]
**Is your feature request related to a problem? Please describe.**
Trying to write a middleware that wants to access the bots api currently requires you to pass the instance of the bot to the middlewares constructor. It would be easier if the bot would be available in every context that is passed to the middleware handler.

**Describe the solution you'd like**
Add a reference to the telegraf bot instance to TelegrafContext
```javascript
bot.use((ctx, next)=>{
  console.log(ctx.bot);
  next();
});
```

**Describe alternatives you've considered**
The alternative would be something like (in case the middleware is not living inside the scope of the bots creation)
```javascript
bot.use(((bot)=>(ctx, next)=>{
  console.log(bot);
  next();
})(bot));
```

**Comment by Otto-AA** [comment]
What about `ctx.telegram[api_endpoint_name]`? It seems to be exactly what you ask for

**Comment by lucaelin** [comment]
I don't know what `api_endpoint_name` is supposed to be and i don't see any reference to an instance of `Telegraf` withing the `ctx.telegram` object...
And this would only help if every middleware knew this `api_endpoint_name`...

**Comment by Otto-AA** [comment]
Sorry, I think I got your question wrong.

`ctx.telegram` is an [Telegram](https://github.com/telegraf/telegraf/blob/edfedcefdc06d50e743bccd2ca1c35a111f32310/docs/examples/scenes-bot.js) object which gives you access to the Telegram API. With it you can call functions like `ctx.telegram.getMe` and `ctx.telegram.sendMessage`.

Did you mean functions like these two above or functions like `ctx.bot.start` and `ctx.bot.command`?

**Comment by lucaelin** [comment]
I mean functions that are part of the bot itself like `on` or `command` and not those from telegram api.. I am looking for those that are member of the `Telegraf` instance.

**Comment by Otto-AA** [comment]
Something like this?

```javascript
// Attach Bot to Context
bot.use((ctx, next) => {
  ctx.bot = bot;
  return next();
});

// Middleware can now use ctx.bot
bot.use((ctx, next) => {
  ctx.bot.command('test', ctx => ctx.reply('Successful'));
  return next();
});
```

**Comment by lucaelin** [comment]
Yes something like that. Not entirely useful with this example because the middleware already gets everything ever send to the bot, but in my case I want to modify the inner workings of the bot upon request... It's not like that it is impossible right now, I just think that this addition would make some code a little nicer.

**Comment by GingerPlusPlus** [comment]
```js
bot.context.bot = bot
```

**Comment by lucaelin** [comment]
The question is, how is the middleware supposed to add the bot to the bots context without having an instance of the bot in the first place :D
All current solutions require you 'add some code' after instantiating the bot and then add the middleware. But it would be horrible to tell people 'Hey uhm.. in order to use the middleware you need to add these lines after creating your bot'... same with 'You need to pass the bot to a function that returns the middleware'. 
Yes it's possible, but I think it would just be nice to `bot.use(require('mymiddleware'))`, with the middleware taking care of the things it needs (instead of the user).

**Comment by lucaelin** [comment]
There is no real problem that is impossible so solve right now, thats why I put problem in quotes before. 
I just noticed that for some middlewares I created i needed to pass an instance to the bot. 
So a common pattern I saw in my code was 
```javascript
const mymiddleware = require('mymiddleware');
bot.use(mymiddleware(bot));
```
so i thought that it would be nice to be able access the bot from the middleware directly.
The reason why the bot needs to be passed to the middleware most of the times is because the middleware lazy-loads another middleware after certain preconditions are met. It's certainly possible to have the middle compose all the things it needs inside its very own handler, but that would be even more complicated than passing the bot itself.

**Comment by dotcypress** [comment]
@lucaelin if middleware (factory) needs a bot as argument - this middleware designed not very well. Ideal middleware factory implementation don't need to know anything about bot instance.

Closing for now, feel free to open new issue when needed.
