### ISSUE TITLE
missing typings for 'help' method

### ISSUE THREAD

**Issue by Matthew-Risedale** [telegraf/telegraf#426]
it seems that you didn't write types for 'help' method

`[ts] Property 'help' does not exist on type 'Telegraf<ContextMessageUpdate>'.`

**Comment by emersonlaurentino** [comment]
This issue has already been fixed:

![here](https://user-images.githubusercontent.com/10627086/46559337-73ff6f80-c8c6-11e8-8624-9b0fe8e8d8ef.png)

**Comment by EdJoPaTo** [comment]
I checked, this is working

@dotcypress please close this
