### ISSUE TITLE
Match commands case-insensitively

### ISSUE THREAD

**Issue by wojpawlik** [telegraf/telegraf#430]
I cannot imagine any scenario in which anyone would want a bot to respond to `/foo`, `/Foo` and `/FOO` differently, so I suggest to match commands case-insensitively in [`Composer.command`](https://github.com/telegraf/telegraf/blob/b84b36f3c508ca392b1b181a6952f48e72b89914/composer.js#L166-L181).

Usernames should be matched case-insensitively as well (#287).

**Describe alternatives you've considered**
1. `hears(/^\/foo\b/i, handler)` is less readable, and doesn't check if usernames match (ie. `/foo@notMyBot` still runs) and if "command" isn't just a code block starting with slash,
2. To achieve case-insensitivity and inspectability ([`router.handler`](https://github.com/telegraf/telegraf/blob/b84b36f3c508ca392b1b181a6952f48e72b89914/router.js#L9)) I wrote [own command routing function](https://github.com/thedevs-network/the-guard-bot/blob/develop/handlers/commands/routingFn.js), to be passed to `Router` constructor. BTW., check it out, I think you may be interested in bringing it into this repo.

**Comment by dotcypress** [comment]
Frankly, I don't wanna add implicit magic(case-insensitivity) to Telegraf, cause it will slow down library a bit. And I can't imagine any scenario as well.

**Comment by GingerPlusPlus** [comment]
> I can't imagine any scenario as well

If you can't imagine scenario for case-insensitivity:

1. Autocorrect or start by capital letter done by some phone keybaords,
2. caps lock,
3. longer commands, which are more readable when written in camelCase. but it still would be nice to be able to type them more quickly without having to use shift key to insert capital letters.

If you can't imagine scenario for case-sensitivity, why should it be the default and easy way to attach commands?

> I don't wanna add implicit magic (case-insensitivity)

Do you have any quick, 100%  correct, and explicit way to achieve it? Regex is not correct, and routing function is not that quick (it is 4 lines of code, yes, but it uses 2 utils defined elsewhere).

> it will slow down library a bit

Only a bit. And, if someone really needs to optimize message matching, they should switch from `O(n)` `Composer` to `O(1)` `Router` with `O(1)` routing function.

**Comment by Colduction** [comment]
Hey mate, you can use this permutation snippet (I'm using it already!):

```
function letterCasePermutation(S) {
	S = S.toLowerCase();
	let len = S.length,
		ans = [];
	const dfs = (i, res = "") => {
		if (i < len) {
			dfs(i + 1, res + S[i]);
			if (S[i] >= "a") dfs(i + 1, res + S[i].toUpperCase());
		} else ans.push(res);
	};
	dfs(0);
	return ans;
}
```

**Comment by julianmojico** [comment]
I came here for escenario 3: 

> longer commands, which are more readable when written in camelCase. but it still would be nice to be able to type them more quickly without having to use shift key to insert capital letters.

So sad @[dotcypress](https://github.com/dotcypress) doesn't consider a useful feature, I was really expecting Telegraf can achieve this.
This issue should be closed already.

**Comment by MKRhere** [comment]
How about supporting RegExp in `bot.command`?

* It's not implicit magic
* It only costs a `typeof` check in the existing case

At least two users have also asked me for RegExp command handling for the unrelated `/command_*` usecase as well.

**Comment by wojpawlik** [comment]
https://github.com/telegraf/telegraf/issues/898#issuecomment-734269096

**Comment by MKRhere** [comment]
> should `Composer.command` check the username before trying the regex

Yes, that would be reasonable.
