### ISSUE TITLE
[question] how to join a group?

### ISSUE THREAD

**Issue by dcsan** [telegraf/telegraf#434]
is there a bot API / method to join a telegram group?
if someone posts a link to a group in one of my chats, i'd like to send my bot to visit them.

heres one mtProto layer client lib, eg channels API. 
https://lonamiwebs.github.io/Telethon/methods/channels/join_channel.html
but Bots can't use this method.

wondering if there's a workaround using the bot API?

**Comment by TiagoDanin** [comment]
Telegram does not provide API to use this in bot.
