### ISSUE TITLE
Group chats reply 

### ISSUE THREAD

**Issue by borovik96** [telegraf/telegraf#437]
## Context

* Telegraf.js Version: 3.21.2
* Node.js Version: 10.1.0
* Operating System: Ubuntu 16.04.3 

## Expected Behavior

`bot.hears` triggers comand handler if message from group

## Current Behavior

`bot.hears` doesn't trigger comand handler if message from group

### Steps to Reproduce

I have next code 

```javascript
const helpResp = 'test';
bot.telegram.getMe().then((botInfo) => {
  bot.options.username = botInfo.username;

  bot.hears(/\/help(@botname)?/, (ctx) => ctx.replyWithMarkdown(helpResponse));
});
```

Bot replies in private chat on `/help` and `/help@botname` commands, but doesn't reply in group

Messages from group are in logs, but bot do not response to chat

I will appreciate any help

I think it related with #134

**Comment by dotcypress** [comment]
@borovik96 we have [special case for commands](https://telegraf.js.org/#/?id=command-handling-in-group):

```js
bot.command('help', (ctx) => ctx.replyWithMarkdown(helpResponse));
```

**Comment by borovik96** [comment]
Can I send arguments with commands? Like this `/\/verify (.+)'/`, then i whant to get  the first param as `ctx.match[1]`

**Comment by xRealMaks** [comment]
Maybe solved already.. anyway:
This should work with the command-parts middleware.
https://github.com/telegraf/telegraf-command-parts

**Comment by borovik96** [comment]
I tried to use `.command`, but bot do not response to commands with botname, i have setup bot username as docs say

**Comment by dotcypress** [comment]
@borovik96 For handling group/supergroup commands(/start@your_bot) you need to provide bot username.

https://telegraf.js.org/#/?id=command-handling-in-group

**Comment by borovik96** [comment]
@dotcypress Yes, I do

```javascript
bot.telegram.getMe().then((botInfo) => {
  bot.options.username = botInfo.username;

  bot.command('help', (ctx) => ctx.replyWithMarkdown(helpResponse));
});
```

**Comment by dotcypress** [comment]
@borovik96 
```js
bot.telegram.getMe().then((botInfo) => {
  bot.options.username = botInfo.username; 
});

bot.command('help', (ctx) => ctx.replyWithMarkdown(helpResponse));
```

**Comment by borovik96** [comment]
Same, bot do not response to command with `@botname` :disappointed:

**Comment by aalyokhin** [comment]
This is truly amazing guys. I have spent around 6 hours in total during a few days, trying to figure out why a bot doesn't reply to a group chat. Previously wasn't able to find this issue to read about setting `options.username`, which has *helped*.
The main thing is that it's absolutely absent in the documentation...
