### ISSUE TITLE
How does heroku support work?

### ISSUE THREAD

**Issue by Juliano-rb** [telegraf/telegraf#44]
Hi, In your page I read that telegraf is ready for heroku, do you have any page explaining what features it makes available for bot deployment in heroku? And if possible some tutorial teaching this? Sorry if it is obvious, I'm starting at these web stuff.

**Comment by newvertex** [comment]
Hi, for deploy your bot on heroku you have to run a web server that's listen on process.env.PORT to prevent terminate your dyno[more about this](https://devcenter.heroku.com/articles/dynos#web-dynos)  
  
The page shows some example about telegraf webhooks is [here](http://telegraf.js.org/introduction.html#webhooks)  
  
  1. to easy deploy bot on heroku just add express to your node.js app
  2. setWebhooks to your app url
    something like this: `bot.telegram.setWebhook(`${URL}/secret-path`);`
  3. use telegraf webhookCallback as express middleware
    like this: `expressApp.use(bot.webhookCallback(`/secret-path`));`
  4. and start a server on PORT environment variable and 
  
a complete code can be somthing like this: 
```js
const Telegraf = require('telegraf');
const express = require('express');
const expressApp = express();

const API_TOKEN = process.env.API_TOKEN || '';
const PORT = process.env.PORT || 3000;
const URL = process.env.URL || 'https://your-heroku-app.herokuapp.com';

const bot = new Telegraf(API_TOKEN);
bot.telegram.setWebhook(`${URL}/bot${API_TOKEN}`);
expressApp.use(bot.webhookCallback(`/bot${API_TOKEN}`));
/*
 your bot commands and all the other stuff on here ....
*/
// and at the end just start server on PORT
expressApp.get('/', (req, res) => {
  res.send('Hello World!');
});
expressApp.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
```

**Comment by dotcypress** [comment]
@newvertex thank you for explanation!

BTW, you might create bot without `express`

```js
const Telegraf = require('telegraf');

const API_TOKEN = process.env.API_TOKEN || '';
const PORT = process.env.PORT || 3000;
const URL = process.env.URL || 'https://your-heroku-app.herokuapp.com';

const bot = new Telegraf(API_TOKEN);
bot.telegram.setWebhook(`${URL}/bot${API_TOKEN}`);
bot.startWebhook(`/bot${API_TOKEN}`, null, PORT)
```

**Comment by tunix** [comment]
Should I use

```
bot.on("text", ...)
```

when using webhook? When I try both `on("text")` and `on("sticker")` and other API calls, nothing happens.

**Comment by tunix** [comment]
I can see that I'm able to get stickers. But I can't use anything besides text. For instance I don't receive the event if I add the following:

```
bot.on("/hello", console.log)
```

**Comment by adarrra** [comment]
For me only example with express works... Without (like in this  [comment](https://github.com/telegraf/telegraf/issues/44#issuecomment-269666490) ) Heroku get me 403 forbiden.

**Comment by TorlanDelta** [comment]
How do I use it with long polling though? Or do I have to use webhooks if I want to deploy to heroku?
