### ISSUE TITLE
How to send HTML or makrdown editMessageText

### ISSUE THREAD

**Issue by sekarpdkt** [telegraf/telegraf#443]
Hi,

how to send HTML or mardown editMessageText? I tried following, but not working..

`
ctx.editMessageText( Extra.HTML(helpMessage), Extra.markup(serviceNowBotActions.config.startkeyboard));
`

**Comment by sekarpdkt** [comment]
Oops.. Solved it.. Following works. 

```
ctx.editMessageText( helpMessage,Extra.markdown().markup(serviceNowBotActions.config.startkeyboard));

ctx.editMessageText( helpMessage,Extra.HTML().markup(serviceNowBotActions.config.startkeyboard));
```

**Comment by VinayakGurav64** [comment]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './markup' is not defined by "exports" in D:\NODEJSTUTORIAL\chatbotTelegram\node_modules\telegraf\package.json
Getting this error ...How to solve it this?

**Comment by MKRhere** [comment]
Don't necropost, and your question has nothing to do with the original issue. Please open a new issue if you think there's an issue.
