### ISSUE TITLE
Hide/remove service message

### ISSUE THREAD

**Issue by CQBinh** [telegraf/telegraf#447]
When a user join/leave the group chat, there is one service message like:
```
Username join to a chat
Username is join to a chat by invite link
Username is left the chat
```

I want to hide/remove them.

A [PHP library do it as expected](https://stackoverflow.com/questions/47959521/how-to-remove-service-messages-from-telegram-with-bot-api). How about us?

**Comment by dotcypress** [comment]
Unfortunately this feature is't allowed in BOT API.

**Comment by CQBinh** [comment]
So, why [that PHP lib](https://stackoverflow.com/questions/47959521/how-to-remove-service-messages-from-telegram-with-bot-api) can?

**Comment by dotcypress** [comment]
Please provide link to example with this feature in PHP
