### ISSUE TITLE
Are types actually supported? 

### ISSUE THREAD

**Issue by mxs42** [telegraf/telegraf#449]
I wanted to use Telegram with TypeScript but it seems that typings are just wrong. 
For example, `Context` doesn't have `updateType`, `updateSubTypes`, it doesn't have `update` as well, how am I supposed to get update object from API? No `match`, `state`, etc.
Maybe I miss something but it seems like types are incompatible with Telegraf docs and actually are pretty much useless because you have to use `any` to access all properties from Context and other objects. 
I mean, it's easy to fix by extending Context interface but still, I guess that such big library could have better TypeScript support.

**Comment by mxs42** [comment]
I will try to fix them in a few days if nobody is going to do this.

**Comment by ak5** [comment]
I am also running into this when converting my little bot to TS.

Property 'restrictChatMember' does not exist on type 'Telegram'. (2339)
Property 'catch' does not exist on type 'Telegraf<ContextMessageUpdate>'. (2339)

Both of these work in JS

**Comment by mxs42** [comment]
Yea, it's awful. Like, look, Composer has static `filter` but not instance method `filter`, so you can't generate middleware.
I wonder how they even merged these types lol

**Comment by tplk** [comment]
@mxs42 do you mind sharing?

**Comment by mxs42** [comment]
@tplk actually I just stopped using Telegraf and wrote my own library in TypeScript using heavily interfaces, decorators and reflection.
Example:
```
export class TgApp {
    private startDate: number;
    private telegram: Telegram;

    public constructor(username: string, token: string) {
        this.startDate = Date.now() / 1000 | 0;

        this.telegram = new Telegram({
            username,
            token
        });

        // middleware to discard "old" updates (for example when bot was offline)
        this.telegram.Use(this.MiddlewareDiscardOldUpdates);

        // do not process forward messages as commands
        this.telegram.Use(this.MiddlewareDiscardForwardCommands);

        // "magical" method, makes library automatically load methods decorated by @Command or @Action decorators
        this.telegram.AttachTo(this);
    }

    // simply replies to user with current chat ID
    // @Command decorator specifies that trigger is /chatid command
    // no need to "add" this callback to somewhere, as long as you use telegram.AttachTo, library will load it automatically
    // if you don't need to use this method, just comment out decorator
    // it's damn good lol
    @Command(/chatid/)
    private async CommandChatID(ctx: Context) {
        ctx.sendMessage({
            text: `<b>Chat ID:</b> <code>${ctx.chat!.id}</code>`,
            parse_mode: "HTML"
        });
    }
    
    // Updates decorator says that this middleware will only listen for "message" update type
    @Updates("message")
    // autobind is from andreypopp/autobind-decorator to bind callback to object instance
    @autobind
    private async MiddlewareDiscardOldUpdates(ctx: Context) {
        if (ctx.update.message!.date < this.startDate) {
            return false;
        }
    }

    @Updates("message")
    @autobind
    private async MiddlewareDiscardForwardCommands(ctx: Context) {
        if (ctx.update.message!.forward_from) {
            if (ctx.commandString) {
                return false;
            }
        }
    }
}
```

I also wrote Markup helpers for generating keyboard, passing data to callback buttons, etc.
Sadly I can't release it because it's still in development, I created it because I just need it to develop another project. Some time later I will release it I guess but for now it's too early.

**Comment by max7z** [comment]
Just want to confirm, that current TypeScript typings are totally wrong :(
I couldn't add this library to an TypeScript project.

**Comment by robincher** [comment]
There are no  action middleware for handling callbackQuery data with regular expressions also :( 

```
bot.action(ctx => )
```

**Comment by EdJoPaTo** [comment]
Most of the issues of the first message are related to #459.

`bot.catch` has typings
`bot.restrictChatMember` is added in #706

`bot.action()` is addressed in #733

I think the only open points directly addressed within this issue are duplicates of #459. This issue should be closed when #733 is accepted.

**Comment by dotcypress** [comment]
Fixed typings will be published soon. Closing for now

**Comment by mfissehaye** [comment]
Are the typings fixed yet?

**Comment by skmohammadi** [comment]
It is 2020 and type State is not exist in **TelegrafContext**.

**Comment by SoundAsleep192** [comment]
Its hilarious how a framework written >70% in typescript has had one hell of a mess with types for so many years
![image](https://user-images.githubusercontent.com/52359798/100603933-de7d9000-3316-11eb-85bf-730a8cd87e3a.png)

**Comment by EdJoPaTo** [comment]
@SoundAsleep192 The repo started as JavaScript. TypeScript Types were added manually later on.

Now there is great progress of refactoring everything into TypeScript (#1074 which is even pinned. How could you overlook that?). So you see the current status of refactoring and assume it has been "for many years" that way?

Big thanks to the guys doing all the refactoring works! (I don't want to mention anyone so i don't wrongly attach someone to this issue)

**Comment by KnorpelSenf** [comment]
Seriously? Please stop whining and start contributing.

> written >70% in typescript

@SoundAsleep192 that is wrong.

This project is traditionally not a TypeScript project. I submitted #1108 three months ago that actually brings us up the the 75+ % TS, and [typegram](https://github.com/KnorpelSenf/typegram) had to be published before we could do any meaningful stuff. The current version on npm is [completely written in JS](https://github.com/telegraf/telegraf/tree/master) with a few manually created types to the side. This has nothing to do with “being written in TS”.

The code that fixes our problems is already pushed, but given that none of you guys bothers to review the respective pull requests (#1194, #1195, #1200, just to name the currently open ones) and confirming that they actually work, how do you think anyone of us will be able to benefit from the work behind it?

> It is 2020 and type State is not exist in **TelegrafContext**.

@skmohammadi it does exist. I submitted it. Can you please confirm that it works (so we can arrive in 2020)? #1194

> Are the typings fixed yet?

@mfissehaye they are. @wojpawlik and I submitted them. If you are interested in them, can you then please review the above PRs and confirm that we can merge them?

My point is: People are investing their spare free time here, and taking that for granted while dropping snappy comments does in no way accelerate it. Joining in does.\</outrage>

I'm looking forward to the contributions of you all! Please try out what is written, and provide feedback. This is essential. (Also, IMO it would be good to have more docs. What do you think?)

**Comment by KnorpelSenf** [comment]
Thank you @EdJoPaTo. Also for pointing them to #1074.

**Comment by aadtyn** [comment]
so many errors with types

i'll get to fixing these types after i finish this project im working on

**Comment by MKRhere** [comment]
A lot has changed since 2018, and Telegraf is Typescript-first now (thanks in large part due to the efforts of @KnorpelSenf and @wojpawlik). If you have issues today, please open a new issue with more specific details so we can help.

Locking this issue to stop necro-posting.
