### ISSUE TITLE
Persisting context

### ISSUE THREAD

**Issue by RamonBeast** [telegraf/telegraf#45]
I have a bot that sends automated updates to users (say every hour), how can make the session with the user persistent over bot restarts? Should I persist the whole ctx object or there's e better way to do it? Or to make it simpler: what is the correct way to send a reply to a user without asking the user to recreate the session every time the bot is restarted?

Thanks.

**Comment by dotcypress** [comment]
Hey.

You can use [Redis session](https://github.com/telegraf/telegraf-session-redis) for that.

**Comment by RamonBeast** [comment]
Thank you very much @dotcypress, I checked it while studying the documentation but it wasn't clear if I could use it for this purpose, thank you very much for you help.
