### ISSUE TITLE
Reply to message help

### ISSUE THREAD

**Issue by Aka-San** [telegraf/telegraf#450]
For example, I use a command in reply to a message, how to make the bot reply to a message to which I replied?

**Comment by mxs42** [comment]
https://core.telegram.org/bots/api#message
Message has `reply_to_message`

**Comment by Daspharion** [comment]
I imagine you can create a `WizardScene`, send a message to the user, put its `message_id` into session, go to the next step and from there check if incoming messages `reply_to_message` equals your `message_id` from the session. Then just `elegram.sendMessage` with `reply_to_message_id`

**Comment by Aka-San** [comment]
Thx all
