### ISSUE TITLE
Composer, general question.

### ISSUE THREAD

**Issue by ImTheDeveloper** [telegraf/telegraf#452]
Hi,

This is a general question based on some of the code examples I have seen.

What is Composer and when should it be used as opposed to instantiating a new Telegraf instance and then requiring this into modules where bot is needed?

Example of code where I have seen Composer used:
```
const bot = new Composer()
bot.use(session())
bot.use(stage.middleware())
bot.command('greeter', (ctx) => ctx.scene.enter('greeter'))
bot.command('cancel', (ctx) => ctx.scene.leave())
module.exports = bot
```

Why is Composer() chosen in the above instead of utilising:

```
const Telegraf = require('telegraf')
const bot = new Telegraf(process.env.BOT_TOKEN)
bot.command('greeter', (ctx) => ctx.scene.enter('greeter'))
bot.command('cancel', (ctx) => ctx.scene.leave())
```

I also see there is a telegraf.compose method also:
https://telegraf.js.org/#/?id=telegraf-compose

**Comment by dotcypress** [comment]
Hey @ImTheDeveloper 

Generally speaking, `Composer` is middleware composition tool.

All handlers and plugins for Telegraf are middleware, and we need some abstraction layer to simplify development. Thats why we have `Composer` as first class citizen, and `compose` method is core library functionality.

For example, you can make available some part of bot functionality only for selected users:

```js
const Telegraf = require('telegraf')
const bot = new Telegraf(process.env.BOT_TOKEN)

var exampleBot = new Composer();
exampleBot.command("/start", (ctx) => {});
exampleBot.command("/get", (ctx) => {});

var adminBot = new Composer();
adminBot.command("/delete", (ctx) => {});
adminBot.command("/add", (ctx) => {});

// for admins only
bot.use(Composer.acl(['adminId1', 'adminId2'], adminBot));

// for all users
bot.use(exampleBot);
```
