### ISSUE TITLE
example inline-bot.js not working

### ISSUE THREAD

**Issue by manmountain** [telegraf/telegraf#460]
I tried the inline bot example and get a error.

I modified the example to use my Spotify API token:
`  const response = await fetch(apiUrl, {headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer '+process.env.API_TOKEN }})
`

but when I run the example I get an error: Error: 400: Bad Request: wrong remote file id specified: can't unserialize it. Wrong last symbol. I cant figure out whats is wrong. My results array looks fine i think
pastebin link to error output https://pastebin.com/gkv0ZDkr

`
Failed to process updates. { Error: 400: Bad Request: wrong remote file id specified: can't unserialize it. Wrong last symbol
    at buildConfig.then.then.then.then (C:\Users\xxxxxxxxxxxx\development\inline-bot\node_modules\telegraf\core\network\client.js:235:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: wrong remote file id specified: can\'t unserialize it. Wrong last symbol' },
  description: 'Bad Request: wrong remote file id specified: can\'t unserialize it. Wrong last symbol',
  parameters: {},
  on:
   { method: 'answerInlineQuery',
     payload:
      { inline_query_id: '2413710350366191214',
        results: '[{"type":"audio","id":"667RpixwEumqApRJRDzHWj","title":"Löv","audio_url":"https://p.scdn.co/mp3-preview/9daf76c5be3068d585c9520d45026e1306e84cc9?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"6sYhG8LVYCfrZoJMyrREzr","title":"Jennifer","audio_url":"https://p.scdn.co/mp3-preview/51197bf8c648c30ebfe2c7e90dfce4caa1709434?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"2ThjxgTq4NHJs8dKifJc1K","title":"Får jag lov","audio_url":"https://p.scdn.co/mp3-preview/27136b5669f692a4b875a890e067ccb6408cdbd8?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"1SmP64QdHl8HHlqRVDYcZ4","title":"Får jag lov","audio_url":"https://p.scdn.co/mp3-preview/211e2164d857477cf9222571afcf4c5a18fa817f?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"28ZA17StpxMWT1jindaMhq","title":"Kan jag få lov","audio_url":"https://p.scdn.co/mp3-preview/daad1dfc68bc4cbacfa5eb29805c8b360cb34f67?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"5mMGR1UewDaCLJFbPFiCk2","title":"Kärlekens lov","audio_url":"null"},{"type":"audio","id":"5rS2mOnKXvDJdA2ymtsKk8","title":"Alt er lov","audio_url":"https://p.scdn.co/mp3-preview/e8035dd72239dce8f0cdf88ff2582502482c633b?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"3Z4CRaBKD2GrcO48LOhQbg","title":"Till strömmingens lov","audio_url":"null"},{"type":"audio","id":"1KI82onNI1x4477zQZS66a","title":"LOV (feat. Sondr, Andrew Jackson)","audio_url":"null"},{"type":"audio","id":"4SJbz7aBc8aC58sYOIGwhx","title":"LOV (feat. Sondr, Andrew Jackson)","audio_url":"null"},{"type":"audio","id":"3KWMtrwlMGIVIwGvjtZUnl","title":"Ingen tid","audio_url":"https://p.scdn.co/mp3-preview/66fd6ba2f29c6a0ddc9027391c5232eda3060ec5?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"6YheF7Pb5NUK7HjF2u8J82","title":"55 Ford","audio_url":"https://p.scdn.co/mp3-preview/6440b15a9b641e82cc596af169ef88ea3d42a139?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"7djjT9MSKJQjtMT7Mkvife","title":"Tack och lov är jag Gnagare","audio_url":"https://p.scdn.co/mp3-preview/313becb52a19cd3583fbbe0f4a53bfbaba3957bc?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"4UL0aB15t82uRX7aNBvmO7","title":"Kan jag få lov","audio_url":"https://p.scdn.co/mp3-preview/900b2e23cdabad30d8d0499ff6850fc5f9850b4f?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"7qvYAb7QfcVkt1WcTbC20O","title":"Får jag lov","audio_url":"https://p.scdn.co/mp3-preview/fc9af6ccdf415dc6dffa13a2a3b8ebf66b0ed88e?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"0MshuOJAT5bbfCxoWOfQo7","title":"Vem får följa dig hem","audio_url":"https://p.scdn.co/mp3-preview/49a5768acadcdc766969097375eda1b13b053f16?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"7oEiIStdxuxvhLhKyEe23Z","title":"Du ska få lov","audio_url":"null"},{"type":"audio","id":"159yahywdoiIufe7yc30xL","title":"Natten har tusen ögon","audio_url":"https://p.scdn.co/mp3-preview/fbafbe0c1e1934e97954387faa16a20d81af8fb7?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"6C5chXTH7JgOrOBUaY30bH","title":"People Grinnin\' (feat. The Child Of Lov) - MOWE Remix","audio_url":"https://p.scdn.co/mp3-preview/606f214d71b01f1e0687776748abbfa5d85aae50?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"1TeochmzYRseQk04IsJj2Y","title":"Kärlekens lov","audio_url":"null"},{"type":"audio","id":"46ZQ1cJuBliKlV02yiqbNj","title":"Fallna löv (skrattspegel)","audio_url":"null"},{"type":"audio","id":"1V0ElgA3UYYopSlmcqtDBJ","title":"Hvis Din Far Gir Dig Lov - Remastret","audio_url":"https://p.scdn.co/mp3-preview/6d116a2b9efbea875697090b9853c479e0eed208?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"1yLppSStQ40GXAhQFKV1x2","title":"Får jag lov (feat. Chords)","audio_url":"null"},{"type":"audio","id":"16zDUP5XE9Cl13txnWDday","title":"Kainn Æ Få Lov","audio_url":"https://p.scdn.co/mp3-preview/950ac4cf37de0affbfde264992b7b972687efd5f?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"2dIheNFzLLKi6XWAqECu6g","title":"Sju ensamma kvällar (Seven Lonely Days)","audio_url":"https://p.scdn.co/mp3-preview/0c03c9b8af7e1fcd4d913fe7e3c7bf5dfadc9b4e?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"3SbBWMOUei4zhQMAjKVYSJ","title":"Tänk Om En Ros Kunde Tala (Schön War\'n Die Tage Der Rosen)","audio_url":"https://p.scdn.co/mp3-preview/a39fb1d8e12403cb24c0c66560a8091560bc7585?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"5wkeRU6CjFOx6yuX7KJYLp","title":"Hon Är Så Fin (Reet Petit)","audio_url":"https://p.scdn.co/mp3-preview/1f9c5b5ac3530a044c9f30a448dd53e7d846bc8e?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"4NaV6Rm9v8TZIValzFOAb0","title":"Gröna løv","audio_url":"https://p.scdn.co/mp3-preview/88696193af89f3a4702c95584f8617dbcf6532b5?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"1gu3jSUEeEf0BXmdsk23HF","title":"Lov, Ära Och Pris (Psalm 10)","audio_url":"https://p.scdn.co/mp3-preview/32f3136b0924fca3eaab2c998ac4770e253efc39?cid=774b29d4f13844c495f206cafdad9c86"},{"type":"audio","id":"4cWDaH6u4fqF6iUNTLQDIG","title":"Jorden runt på 80 da\'r","audio_url":"https://p.scdn.co/mp3-preview/3b4bbed1dd7608a0df00c5c3a94d07394fbc7ba0?cid=774b29d4f13844c495f206cafdad9c86"}]',
        next_offset: 30 } } }

`

**Comment by Daspharion** [comment]
You can filter out the results without an url:
```
  const results = tracks.filter(({ preview_url }) => preview_url).map((track) => ({
    type: 'audio',
    id: track.id,
    title: track.name,
    audio_url: track.preview_url
  }))
```
But don't really understand why does spotify respond with an empty preview url.

**Comment by manmountain** [comment]
Yes, the above would work, But I think that error message `description: 'Bad Request: wrong remote file id specified: can't unserialize it. Wrong last symbol' ` is useless.
