### ISSUE TITLE
bot does not correctly stopping (.stop())

### ISSUE THREAD

**Issue by sxwebdev** [telegraf/telegraf#462]
Hey. In my application, I manage the bot settings from the admin panel. So I have to initialize the bot on a new one. Before that, I'm doing the `bot.stop()` command. and immediately initialize a new bot with the same token and call the function `bot.startPolling()`.

After I get the error:
```js
{ code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' },
  description:
   'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on:
   { method: 'getUpdates?offset=306369692&limit=100&timeout=30',
     payload: {} } }
```

How to resolve this? Thx...

**Comment by TheDevXen** [comment]
any fix?

**Comment by sxwebdev** [comment]
> any fix?
> i am still getting this error

The error was in my code.
