### ISSUE TITLE
Question - How can I see my own bots message id? 

### ISSUE THREAD

**Issue by HaydarOzturk** [telegraf/telegraf#463]
I am having a trouble of understanding this. I use logs with bot.use(Telegraf.log());

But it doesn't show me bots messages. I think I read it somewhere in the official document that bots can't read other bots messages but I don't know if they can't read their own messages. Even if they can't read their own messages, let me raise this question regarding making a welcoming bot for a supergroup: "How can we delete the old bots welcome message if there are two incoming new chat members or three or even four consecutively" I want to avoid spamming in the future.

**Comment by Daspharion** [comment]
```
bot.command('msg', ctx => {
  ctx.reply('Hello there').then(({ message_id }) => {
    console.log(message_id)
  })
})
```

**Comment by HaydarOzturk** [comment]
Thank you very much.
