### ISSUE TITLE
bot.on('chosen_inline_result', Promise) dont get triggered

### ISSUE THREAD

**Issue by manmountain** [telegraf/telegraf#465]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.21.2
* Node.js Version: v8.11.3
* Operating System: Windows 10

## Expected Behavior

When selecting a inline query result to get the print out 'You chosed an inline query result'

## Current Behavior

Nothing happens when selecting an inline query result. `bot.on('chosen_inline_result', Promise)` doesnt get triggered.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run bot code posted below
2. write an inline query to the bot
3. select one of the inline query results
4. Nothing is printed in the node console

```
require('dotenv').load();
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)

bot.on('inline_query', async ({ inlineQuery, answerInlineQuery }) => {
  const offset = parseInt(inlineQuery.offset) || 0
  items = []
  for(var i = 0; i < 100; i++) {
    items.push({ title: 'Item '+i, desc: 'item '+i+' desc', id: '0000'+i, moreinfo: 'More info about item'+i+', mucho importante information'})
  }
  results = items.slice(offset, offset+10).map((item) => ({
    type: "article",
    id: item.id,
    title: item.title,
    description: item.desc,
    input_message_content: {
      message_text: '*'+item.title+'*\n'+item.desc,
      parse_mode: 'Markdown'
    },
    reply_markup: {
        inline_keyboard: [
          [{ text: 'More info', callback_data: 'moreinfo' }]
    ]},
    hide_url: true,
    url: 'http://www.domain.se/'+item.id,
  }))
  return answerInlineQuery(results, {is_personal: true, next_offset: offset+results.length, cache_time: 10})
})

/* what was selected from the inline query? */
bot.on('chosen_inline_result', ctx => {
  console.log('You chosed an inline query result')
})

/* start bot */
bot.startPolling()


```

### Failure Logs

Nothing gets printed

**Comment by Daspharion** [comment]
From [Telegram Bot API:](https://core.telegram.org/bots/api#choseninlineresult)

> Note: It is necessary to enable inline feedback via @Botfather in order to receive these objects in updates.

**Comment by mahercoder** [comment]
hey there. can i send thumbnail as a inline query result?
