### ISSUE TITLE
Example with http proxy on https-proxy-agent

### ISSUE THREAD

**Issue by an-ivannikov** [telegraf/telegraf#466]
**In some countries, authorities restrict access to Telegram servers. The logical solution is a proxy connection.**
Below I presented an example of setting up a bot to connect via proxy.
Perhaps your team will make the connection more proxy friendly?

```js
const HttpsProxyAgent = require('https-proxy-agent')
const Telegraf = require('telegraf')
const Extra = require('telegraf/extra')
const Markup = require('telegraf/markup')

const proxyConfig = {
  telegram: {
    agent: new HttpsProxyAgent({host: process.env.PROXY_HOST, port: process.env.PROXY_PORT})
  }
}

const keyboard = Markup.inlineKeyboard([
  Markup.urlButton('❤️', 'http://telegraf.js.org'),
  Markup.callbackButton('Delete', 'delete')
])

const bot = new Telegraf(process.env.BOT_TOKEN, proxyConfig)
bot.start((ctx) => ctx.reply('Hello'))
bot.help((ctx) => ctx.reply('Help message'))
bot.on('message', (ctx) => ctx.telegram.sendCopy(ctx.from.id, ctx.message, Extra.markup(keyboard)))
bot.action('delete', ({ deleteMessage }) => deleteMessage())
bot.startPolling()
```

**Comment by yofi2tofi** [comment]
it's would be great feature! Now i need do smth like that
`const DefaultOptions = {
  apiRoot: 'https://api.telegram.org',
  webhookReply: true,
  agent: new HttpsProxyAgent({
    host: *.*.*.*,
    port: ****,
    keepAlive: true,
    keepAliveMsecs: 10000
  })
}`
