### ISSUE TITLE
How can I reply a message with keyboard and inline keyboard [help wanted]

### ISSUE THREAD

**Issue by Iniro** [telegraf/telegraf#467]
I'm trying to reply with both keyboards at same time, with this code, but it isn't working. (I also tried to pass both "m" in an array)

```
	ctx.reply(' Test Reply 2 menus', Extra.HTML().markup((m) =>{
		m.keyboard(['Menu'])
			.oneTime()
			.resize()
			.extra();				
		m.inlineKeyboard([
			m.callbackButton('Inline Menu1', 'cbMenu1'),
			m.callbackButton('Inline Menu2', 'cbMenu2')
		])
		return m.extra();
	}));
```

Am I doing something wrong, or that is not possible?

**Comment by Daspharion** [comment]
You can only pass one object as `reply_markup` per message [(source)](https://core.telegram.org/bots/api#sendmessage).
