### ISSUE TITLE
Having difficulty sending audio files with a thumbnail [need help]

### ISSUE THREAD

**Issue by Daspharion** [telegraf/telegraf#470]
Greetings, with the new Bot API version i was pleasantly surprised that they've added support for audio thumbnails. Though after countless failed tries of including a thumb in an audio, my only option is to ask for help with the realization.

#### Sandbox that i am using:
```
Bot.on('audio', ctx => console.log(ctx.message.audio))

Bot.command('test', ({ replyWithAudio }) => {
  replyWithAudio({ source: './media/audio.mp3' }, { 
    title: 'Walk with me in Hell',
    performer: 'Lamb of God',
    duration: 311,
    thumb: { url: 'https://i.imgur.com/p0FcTDy.jpg' }
  }).then(({ audio }) => console.log(audio))
})
```
#### My results:
- After executing command 'test', song gets uploaded, in console i get expected message:
```
{ duration: 311,
  mime_type: 'audio/mpeg',
  title: 'Walk with Me In Hell',
  performer: 'Lamb of God',
  thumb:
  { file_id: 'AAQCABMUbbYOAASe9xeMiD-NxnOiAAIC',
    file_size: 3373,
    width: 90,
    height: 90 },
  file_id: 'CQADAgADxQEAAmNoAAFLENxLF-xvS1sC',
  file_size: 12462497 }
```
- After downloading this audio file the thumbnail and other metadata (title, performer...) is nowhere to be found
- If i forward that audio back to my bot, gonna get the same result in the console
- If i send my bot an audio file that **has a builtin thumbnail - all works fine**. Console log:
```
{ duration: 274,
  mime_type: 'audio/mpeg',
  title: 'Deliver Us (Live)',
  performer: 'In Flames',
  thumb:
  { file_id: 'AAQCABM8NzMOAASDkEskDc_6zdVkAAIC',
    file_size: 5311,
    width: 90,
    height: 90 },
  file_id: 'CQADAgADxgEAAmNoAAFLl_jUBnxWauMC',
  file_size: 11178596 }
```
_send help_

**Comment by magic-akari** [comment]
Same issue.
