### ISSUE TITLE
webhooks expressjs it does not work

### ISSUE THREAD

**Issue by pookdeveloper** [telegraf/telegraf#474]
I use the code for  Express.js  who is in the docu and dosen't work

````javascript
const Telegraf = require('telegraf')
const express = require('express')
const expressApp = express()

const bot = new Telegraf(process.env.BOT_TOKEN)
expressApp.use(bot.webhookCallback('/secret-path'))
bot.telegram.setWebhook('https://xxx:xxx/secret-path')

expressApp.get('/', (req, res) => {
  res.send('Hello World!')
})

expressApp.listen(3000, () => {
  console.log('Example app listening on port 3000!')
})
````

I deploy on heroku and I get this error.

![8068df0b-5bdc-4a70-b3c1-55e692bac79f](https://user-images.githubusercontent.com/3384734/43704371-b87a3d66-995f-11e8-8b1a-fd4568e220c9.jpg)

**Comment by the-AjK** [comment]
On heroku you shall use "process.env.PORT" rather than port 3000.

JK

**Comment by pookdeveloper** [comment]
Thanks @the-AjK  it's works fine :)
