### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by robverhoef** [telegraf/telegraf#477]
I really like this project! 
But it is very hard to find the right documentation. 

For instance; 
- What does Markup.forceReply do?
- How can I jump to a specific step in a wizard (…is this even possible)?
- When I look at https://telegraf.js.org/#/?id=extra it points me to the examples. There I see code like this:
`reply('One time keyboard', Markup
    .keyboard(['/simple', '/inline', '/pyramid'])
    .oneTime()
    .resize()
    .extra()
  )`
What does .extra() do? oneTime()? I don't get any clue, anywhere.

Providing more guide-like documentation would help me out a lot. Or maybe links to the Telegram API when appropriate.
As an alternative, I don't mind looking at the source code or examples. But it offers too little information (inline comments) on what methods do and when to use them.

I would be happy to help here, since this looks like a massive job. But I simply don't understand what is going on in many parts of the code.

**Comment by dotcypress** [comment]
Duplicate #211

**Comment by IDIDIR** [comment]
1. docs https://core.telegram.org/bots/api#forcereply
2. return ctx.wizard.selectStep(2) 
source: https://github.com/telegraf/telegraf/blob/develop/scenes/wizard/context.js 
3. you can clearly understand such things if you create two menus with a parameter and without it.

**Comment by dotcypress** [comment]
@robverhoef jumping is possible, but actual handler will be called on next user message.

**Comment by vitaliysavich** [comment]
How to achieve the same result in case if step is Composer?) ctx.wizard.steps[3].handler(ctx) ?
