### ISSUE TITLE
Failed to fetch updates. Waiting: 1s 404: Not Found

### ISSUE THREAD

**Issue by mfgabriel92** [telegraf/telegraf#478]
I wrote a small block of code in an attempt to make it work, but when I start the server, the message

> Failed to fetch updates. Waiting: 1s 404: Not Found

keeps popping up.

**`index.js`**:
```javascript
const Telegraf = require("telegraf");
const bot = new Telegraf("<token>");

bot.start((ctx => ctx.reply("When you say CHEESY I say MELT!")));
bot.hears("CHEESY", ctx => ctx.reply("MELT!"));
bot.startPolling();
```
**`package.json`**:
```
{
  "name": "bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "telegraf": "^3.22.1"
  },
  "engines": {
    "node": "8.11.3"
  }
}
```

This is my folder structure.

```
Bot/
    node_modules/
    index.js
    package.json
    package-lock.json
```

I noticed that it has something to do with the module because when I erased everything and just pasted a code to listen to a port, it doesn't show the error message.

**Comment by mfgabriel92** [comment]
Is there any update?

**Comment by dotcypress** [comment]
@mfgabriel92 could you provide more info about your internet connection? Probably Telegram is blocked in your country :(
If so, you can use HTTP proxy with Telegraf

**Comment by mfgabriel92** [comment]
Telegram isn't blocked. I have the app installed and I can create bots using `espress` and `axios` normally.

**Comment by dotcypress** [comment]
@mfgabriel92 token in code is invalid `Telegraf("<token>");`
