### ISSUE TITLE
Sending Gifs

### ISSUE THREAD

**Issue by Kaesebrot84** [telegraf/telegraf#48]
I am trying to send animated Gifs using:

`app.hears('cat',(ctx) => {
  return ctx.replyWithPhoto({
    url: 'http://thecatapi.com/api/images/get?format=src&type=gif'
  })
})`

But when using 'replyWithPhoto', the gif is actually posted as an image. How are animated gifs sent?

Greets

**Comment by dotcypress** [comment]
Hey.
You need to provide filename:
```js
bot.hears('cat', (ctx) => ctx.replyWithDocument({
  url: 'http://thecatapi.com/api/images/get?format=src&type=gif',
  filename: 'cat.jpg'
}))
```

**Comment by Kaesebrot84** [comment]
Thank you Vitaly this did work. This issue can be closed, right?
