### ISSUE TITLE
[Question] How to use ctx.onReplyToMessage?

### ISSUE THREAD

**Issue by wisdomabioye** [telegraf/telegraf#480]
I uses this from another nodejs library. How do I make this work with Telegraf?

                    ctx.replyWithHTML("Please send your email address",
				{reply_to_message_id:ctx.message.message_id,
				reply_markup:{force_reply:true, selective:true}
				}).then(function(res){
				const replyListener = ctx.onReplyToMessage(res.chat.id,res.message_id,function(response){
			          //remove listener
			          ctx.removeReplyListener(replyListener);
			          //grab the response
			          console.log(response)
			          fun(response);
			        });
				});`

I can't see any method to get reply to a message in Telegraf
Help me out please.

**Comment by dotcypress** [comment]
@wisdomabioye for such cases you can use `Scenes`(simple FSM implementation).

Examples: 
* https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js
* https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js

**Comment by wisdomabioye** [comment]
@dotcypress Thanks for response. Where can I find document for Scenes and stages?

**Comment by dotcypress** [comment]
@wisdomabioye For now we have only few examples and [short help](https://telegraf.js.org/#/?id=stage).
Feel free to ask questions, if any.

**Comment by wisdomabioye** [comment]
@dotcypress thanks for the help. 
Can I quickly ask from here the difference between `bot.on('text')` and `bot.on('message')`?

**Comment by athimannil** [comment]
@wisdomabioye 
`bot.on('text')`: Text messages only including **emoji**
`bot.on('message')`:  New incoming message of any kind — text, photo, sticker, etc.

**Comment by wisdomabioye** [comment]
Thank you @athimannil . That was very helpful.
