### ISSUE TITLE
Router Middleware

### ISSUE THREAD

**Issue by JRakhimov** [telegraf/telegraf#481]
## Context

* Telegraf.js Version: 3.21.2
* Node.js Version: 10.5.0
* Operating System: Windows 10

## Expected Behavior

Control context in current router

## Current Behavior

Middleware does not work and does not react to anything

## Code

```js
const Router = require('telegraf/router');

const admin = new Router(({ message }) => {
  return { route: message.text }
})

admin.middleware(async (ctx, next) => {
  console.log("Test")
  await next(ctx)
})

admin.on("/start", ctx => {
  ctx.reply("Welcome!")
})
```

So here should be Test in console every time when user enters to router...

**Comment by dotcypress** [comment]
@JRakhimov looks like you use `middleware` method wrong. 

As I understood, you need something like:
```js
const Composer = require('telegraf/composer')
const Router = require('telegraf/router')

const admin = new Router(({ message }) => {
  return { route: message.text }
})

admin.on("/start", ctx => {
  ctx.reply("Welcome!")
})

const bot = new Composer();

bot.use(async (ctx, next) => {
  console.log("Test")
  await next(ctx)
})

bot.use(admin)
```

**Comment by JRakhimov** [comment]
@dotcypress In issues I found your example [here](https://github.com/telegraf/telegraf/issues/452) and this was what I actually need) so why we need routers when we have composers? And one more question, you said that I used ```middleware``` wrongly, in this case what ```middleware``` metdon in routers is actually do and when use it?

**Comment by dotcypress** [comment]
@JRakhimov Router is more internal helper, please don't use it separately.
