### ISSUE TITLE
For loop inlineKeyboard with 2 buttons per row

### ISSUE THREAD

**Issue by wdamaral** [telegraf/telegraf#483]
Hello everybody.

Following the question from #178 , is there any way of creating a limited number of buttons by row?

This approach suggested by @dotcypress creates all buttons in the same row.

> const obj={"coca":"2$" , "7up":"3$" , "fanta":"4$"} 
> const buttons = Object.keys(obj).map(key => Markup.callbackButton(key, `price: ${obj[key]}`))
> ctx.reply('price list', Extra.HTML().markup((m) => m.inlineKeyboard(buttons))

In my case, I fetch the data from the database and then show them using inline buttons.  What happens is that sometimes I have only 1 button though I can have 10. If I put all buttons in the same line, it's impossible to read them.

Any suggestion?
Thanks

**Comment by dotcypress** [comment]
@wdamaral you can use following snippet to setup maximum amount of buttons in a row:

```js
const obj={"coca":"2$" , "7up":"3$" , "fanta":"4$",  "water":"1$"}
const buttons = Object.keys(obj).map(key => Markup.callbackButton(key, price: ${obj[key]}))
ctx.reply('price list', Extra.HTML().markup((m) => m.inlineKeyboard(buttons, {columns: 2}))
```

or you can provide [custom wrapping function](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js#L47).
