### ISSUE TITLE
Unable to modify redis session in callback

### ISSUE THREAD

**Issue by Relecto** [telegraf/telegraf#485]
Helllo!
I am using stage, redis session and mongoose.

The following code behaves weird.
```javascript
const channelMenuScene = new Scene("channelMenu");

channelMenuScene.hears(/.+/, (ctx) => {
    models.Channel.findOne({ name: ctx.message.text }) //mongoose query
        .exec((err, channel) => { //callback
            if (channel) {
                ctx.session.channel = channel;
                ctx.scene.enter('channel')
            }
    })
});
```
`ctx.scene.enter('channel')` invokes enter() of channel scene, and `ctx.session.channel` is accessible there.
```javascript
const channelScene = new Scene("channel");

channelScene.enter(ctx => {
    if (ctx.session.channel) {
        ctx.reply(`*${ctx.session.channel.name}*`)  
    }
});
```
However, session doesn't get modified. It's current scene remains channelMenu, and there's no channel property, which I added in mongoose callback. So when the next update arrives, it goes to channelMenu scene again.
redis key value remains like this: `"{\"__scenes\":{\"current\":\"channelMenu\",\"state\":{}}}"`

I tried reproducing this in a blank project without mongoose, but it worked fine. So now i think that's because I modify session inside a mongoose callback. If so, what should I do to get it working? 
Or if callback doesn't really matter, what am I doing wrong?

Thanks in advance for any help!

**Comment by dotcypress** [comment]
@Relecto you have a data race here, cause Telegraf session invalidated only after all handlers.

You need to wait for db query, eg:

```js
const channelMenuScene = new Scene("channelMenu");

channelMenuScene.hears(/.+/, (ctx) => {
    return new Promise((resolve, reject) => {
       models.Channel.findOne({ name: ctx.message.text }) //mongoose query
        .exec((err, channel) => { //callback
           if (err) {
             return reject(err)
           }
           if (channel) {
                ctx.session.channel = channel;
                ctx.scene.enter('channel').then(resolve)
            } else {
                resolve()
            }
      })
    })
});
```

Also you can use async/await:
```js
const channelMenuScene = new Scene("channelMenu");

channelMenuScene.hears(/.+/, (ctx) => {
     const channel = await models.Channel.findOne({ name: ctx.message.text }) //mongoose query
     if (channel) {
        ctx.session.channel = channel;
        await ctx.scene.enter('channel')
     }
});
```

**Comment by Relecto** [comment]
Ah, I got it, this is working.
Async/await solution is really beautiful
Thank you for your attention!
