### ISSUE TITLE
How to handle errors

### ISSUE THREAD

**Issue by WolfyLPDC** [telegraf/telegraf#486]
Hello,

I'm currently doing a little project using Telegraf and I have a problems handling errors. I have read a lot about it and I have seen some solutions but they are not working.

The code I am having problems with is basically this one:

    const bot = new Telegraf(config.telegram.token);
    bot.on('message', (ctx) =>
        process_message(ctx.message, callback)
    );

    bot.startPolling();

And, for example, when I open another bot I have this problem, very reported:
`Failed to process updates. { Error: 409: Conflict: terminated by other getUpdates request`

I have seen that you can use `bot.catch(err => console.log(err));` but it's not working for me. As I know, Telegraf works with promises, so I also tried `bot.startPolling().catch(err => console.log(err));`

I'm sorry it this have been answered already, as you can see I did some research but nothing is working because I'm missing something. 

Thanks a lot.

**Comment by WolfyLPDC** [comment]
I have another bot running in Python and I know that with Telepot (The python framework for Telegram) it has a loop trying to reconnect, but here the process stops suddenly.

**Comment by Piterden** [comment]
```js
const bot = new Telegraf(config.telegram.token)

const process_message = (message, cb) => new Promise((resolve, reject) => {
  const response = cb(message)

  if (response) {
    return resolve(response.result)
  }

  return reject()
})

bot.on('message', async (ctx) => {
  try {
    await ctx.reply(`Your message was: ${ctx.message}`)
  }
  catch (error) {
    console.log(error)
  }

  let result

  try {
    result = await process_message(ctx.message, callback)
  }
  catch (error) {
    console.log(error)
  }
})

bot.startPolling()
```

**Comment by WolfyLPDC** [comment]
I'm going to try it as soon as I can. Thank you.

**Comment by Piterden** [comment]
And what do you want?

**Comment by WolfyLPDC** [comment]
To auto reconnect after this kind of conflict, leaving it as a warning or something like that

**Comment by Piterden** [comment]
Use `try/catch` or `.catch()` for it.
```js
const bot = new Telegraf(config.telegram.token);

bot.on('message', (ctx) =>
  try {
    process_message(ctx.message, callback);
  }
  catch (error) {
    debug(error);
  }
);

bot.startPolling();
```

**Comment by WolfyLPDC** [comment]
That is the same answer than the first one. The problem does not appear processing the message, the problem is caused by the getUpdates process. That it's what I want to catch.

I also tried 

```
        try {
            await bot.startPolling();
        }
        catch (error) {
            console.log(error);
        }
```

**Comment by Piterden** [comment]
But you sad the problem caused by getUpdates. Why are you catching it in startPolling? Btw, it is not async function.

So if you remove the process_message, does error gone away?

**Comment by WolfyLPDC** [comment]
const bot = new Telegraf(config.telegram.token);
bot.startPolling();

This code raises the same error. I think that getUpdates is the function that launch the event 'on message', so I can not catch it by catching bot.on

**Comment by Piterden** [comment]
Why don't I have it? Maybe it's your environment issue? Check out things like a firewall and so on...

**Comment by WolfyLPDC** [comment]
It happens when two bots are running at the same time. You can force it consulting the API while the bot is on work.  Try it:

https://api.telegram.org/[bot]/getUpdates?offset=0&limit=100&timeout=30

**Comment by Piterden** [comment]
Probably only one bot can do it?

**Comment by WolfyLPDC** [comment]
Yeah, it can. But it is a security check. What if someone else starts another bot with the same token or you use the same token on development and production?

You have to be sure that your server ia not going to stop working because of a little mistake.

**Comment by WolfyLPDC** [comment]
I finally decided to edit the bot to add the option to reconnect after the 409 error. You can take a look to it here: https://github.com/telegraf/telegraf/pull/494

**Comment by joshuaquek** [comment]
You could also look at this:
https://telegraf.js.org/#/?id=error-handling

**Comment by WolfyLPDC** [comment]
As I said, that does not work because I am dealing with a very specific error that does not throw anything.

**Comment by rndlaine** [comment]
@msolefonte is it possible to run multiple telegraf clients on the same bot? For instance, in a cluster scenario, each node would require a telegraf client that have access to the same bot.

**Comment by akloketa** [comment]
can anyone tell me how fix this error???
[*] Service: facebook 
[*] Checking if username exists...
Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-x86_64/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by Piterden** [comment]
What did you do to get it? And how is it relating to the telegraf?

Try to put the geckodriver executable to your PATH variable. Just like it written in the error.

**Comment by Piterden** [comment]
@rndlaine try to connect your cluster to one telegraf instance, just like you wanted to connect a few telegraf clients to a bot.

**Comment by andrew-medvedev** [comment]
Lol I don't know how scaling of Node.js works in your world, but in mine I use pm2 that runs multiple node instances plus several physical hosts thats comes out with 12 parallel node instances minimum. All of them running the same code and sharing the same telegram bot token. And ultimately expected that after running u momentally get this error: 

> Failed to process updates. TelegramError: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

Dear telegram and telegraph, I don't need to make sure, I completely sure that I run multiple instances and I will not left only one!

@msolefonte I completely agree with your problem. It turns out that Telegraph needs to be finalized to become production-ready

**Comment by andrew-medvedev** [comment]
@msolefonte Yes, I re-checked the case. If you want to pass 409's, you will face update duplicates: 

node_modules/telegraf/core/network/client.js:280 :
```
.then((data) => {
        if (!data.ok) {
          if(data.error_code === 409 && data.description.startsWith('Conflict: terminated by other')){
            if(method.startsWith('getUpdates')){
              return [];
            } else {
              return null;
            }
          }
          debug('API call failed', data)
          throw new TelegramError(data, { method, payload })
        }
        return data.result
      })
```
So the only solution for me rn is to remove telegraf from my project and rewrite functionality by my hands.
