### ISSUE TITLE
How can I get Inline Message ID

### ISSUE THREAD

**Issue by thedevxen** [telegraf/telegraf#489]
How can I get the Inline Message ID after it being sent.

**Comment by Piterden** [comment]
Try `console.log(ctx)`.

There aren't any inline messages in telegram's bots API.

There are **inline_query**, **inline mode**, **inline result** and **inline keyboard**.

What exactly do you mean?

**Comment by austinhuang0131** [comment]
https://core.telegram.org/bots/api#callbackquery

inline_message_id | String | Optional. Identifier of the message sent via the bot in inline mode, that originated the query.
-- | -- | --
