### ISSUE TITLE
some commands being skipped

### ISSUE THREAD

**Issue by paOol** [telegraf/telegraf#49]
I have 2 separate commands that both sometimes get completely ignored.

```
 bot.hears(/gif (.+)/ig, google.getGifs, (ctx) => {
  return console.log('something happened');
 });
```
I have tried making one a middleware and that didn't solve anything.

i can test with `gif cats` and if i do it 2 or 3 times in a row. at least one time will not register and console.log only appears 1 or 2 times.

i also have a seperate command, but same syntax.

using bot.hears and the same regex capture.
same issue.

other commands do not seem to have the problem and return reliably.

what is some debugging I can do to find why this is happening?

**Comment by dotcypress** [comment]
Could you send a minimal code to reproduce this error?

**Comment by paOol** [comment]
```
  console.log('inside get gifs');


    return next().then(() => {

      let query = ctx.match[1];
      let replyTo = ctx.update.message.message_id;

      request('https://www.googleapis.com/customsearch/v1?q=' + query +....., function(error, response, body) {
        if (error) {
          console.log('debug', error)
          return ctx.reply(`error: ${error}`, { reply_to_message_id: replyTo });
        }


        let data = JSON.parse(body);

        if (data.searchInformation.totalResults == 0) {
          return ctx.reply(`no results found for ${query}`, { reply_to_message_id: replyTo });
        } else {


          if (filtered.length) {
            let random = _.sample(filtered);
            ctx.replyWithChatAction('upload_video');
            return ctx.replyWithVideo({ url: random['url'] });
          } else {
            return ctx.reply(`no valid results found for ${query}`, { reply_to_message_id: replyTo });
          }

        }

      });

    });
```

I have tried `request-promise` instead. but the same issue occurs.
I also have tried a non middleware version (without next().then()). same issue

**Comment by dotcypress** [comment]
@paOol i got it, it's because you have breaking promise chain in your example.

Just use `node-fetch` instead `request-promise` (Teleraf already uses it)

[Good article about `Promises`](https://developers.google.com/web/fundamentals/getting-started/primers/promises)

```js
function getGifs(ctx, next) {
  const query = ctx.match[1];
  const replyTo = ctx.update.message.message_id;

  fetch('https://www.googleapis.com/customsearch/v1?q=' + query )
    .then(res => res.json())
    .then(data => {
      if (data.searchInformation.totalResults == 0) {
        return ctx.reply(`no results found for ${query}`, { reply_to_message_id: replyTo });
      }
      if (!filtered.length) {
        return ctx.reply(`no valid results found for ${query}`, { reply_to_message_id: replyTo });   
      }
      const random = _.sample(filtered);
      ctx.replyWithChatAction('upload_video');
      return ctx.replyWithVideo({ url: random['url'] });           
    })
    .then(next)
}
```

**Comment by paOol** [comment]
my other functions are written in a very similar flow and seem to reliably output what they're supposed to.

i have switched to node-fetch and still having the same issues.

**Comment by paOol** [comment]
i have my bot replying to the message id when the command is used.
i am reliably seeing that every other command is ignored.

**Comment by paOol** [comment]
found the issue.

```
bot.hears(/test/i, (ctx) => {
  console.log('debug', 'in the test function');
});
```
that would work but 


```
bot.hears(/test/ig, (ctx) => {
  console.log('debug', 'in the test function');
});
```

that would reliably skip every other command. It was the `g` regex tag breaking things.
