### ISSUE TITLE
bot.catch seems not to catch everything

### ISSUE THREAD

**Issue by EdJoPaTo** [telegraf/telegraf#491]
## Context

bot.catch does not seem to catch all errors. For example Telegram API Errors like "message is not modified" is not catched.
This is especially bad when Node drops support for UnhandledPromiseRejectionWarning and just dies in the future.

Possibly #486 has the same issue.

* Telegraf.js Version: 3.22.1
* Node.js Version: v10.9.0
* Operating System: Arch Linux

## Expected Behavior

bot.catch catches error

## Current Behavior

bot.catch never sees error. But Error gets posted to console by node.

### Steps to Reproduce

Send a message with inline Callback button
On callback Button click edit the message to the same text

### Failure Logs

```
(node:19896) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: message is not modified
    at buildConfig.then.then.then.then (…/node_modules/telegraf/core/network/client.js:235:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Piterden** [comment]
Could you please show the code which sends that message for you?

**Comment by EdJoPaTo** [comment]
I agree with you @Piterden, you always should catch errors on the spot where they happen but a global error fallback is great to log while not crashing the hole program (which will be the case after node removes UnhandledPromiseRejectionWarning). 

I tested it further (see this [gist](https://gist.github.com/EdJoPaTo/e4eb060ec303c690015f03d995049c73))

Interestingly try catch is useless when returning a promise. also finally is kinda useless then.

`bot.catch` only seems to catch things that are returned or awaited.
I often use things without await when they are in the middle of a section and there is no need to wait for them. The most obvious example maybe is `sendChatAction` because you can just start to do what you want to do without waiting for telegram to know you are doing something.
Looks like I have to attach a .catch no-op to this or Promise.all it with the return.

Also checking for changes in the message by myself is kinda hard because `ctx.callbackQuery.message.text` is always without Markdown. The new text (in my case) mostly is.
