### ISSUE TITLE
Is it possible to delete the entire previous message by bot ? 

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#495]
Currently bot has option to show welcome messages for the new `new_chat_members` which shows for each member. There are plenty of welcome messages staying in group due to the high volume of new members. iIt is bit irritating for the current users showing multiple number of welcome messages.

```
const welcomeMessage = (ctx) => {
  const { new_chat_members } = ctx.message;
  const newMembers = new_chat_members.filter( member => member.is_bot === false)
  var membersName = newMembers.map( usr =>{ 
    let fullname = [usr.first_name,usr.last_name].join(" ");
    return fullname;
  });
  ctx.replyWithMarkdown(`Welcom ${membersName.join(', ')}`);
}
bot.on('new_chat_members', welcomeMessage);
```

Is there any option to delete all the previous welcome messages ?

**Comment by the-AjK** [comment]
You should keep track of the welcome message's IDs, and then use the telegram.deleteMessage method to delete the messages after a fixed period of time for example.

**Comment by athimannil** [comment]
@Piterden Unfortunately your solution doesn't delete previous welcome messages. However it is helpful for me to clean my code with best practice ☺️

**Comment by athimannil** [comment]
@the-AjK  Currently the welcome message delete in one minute 
```
ctx.replyWithMarkdown(`Welcom ${membersName.join(', ')}`)).then(
  ({ message_id }) => {
    setTimeout(
      () => ctx.deleteMessage(message_id),
    60 * 1000)
    // console.log(message_id)
})
```

The solution I am looking for to delete all the previous message in case some one joined with the `setTimeout( () => ctx.deleteMessage(message_id), 60 * 1000)`

**Comment by Piterden** [comment]
```js
const { message_id } = await ctx.replyWithMarkdown(`Welcom ${membersName.join(', ')}`))
setTimeout(() => ctx.deleteMessage(message_id), 60 * 1000)
console.log(message_id)
```
I affraid we talk about the service welcome message.

**Comment by athimannil** [comment]
@Piterden Hope you understand the point. I just wanna delete the existing welcome message if somebody join with in the 1 minute

**Comment by Piterden** [comment]
Could you please send a screenshot, to make it fully clear for everyone?

**Comment by git-antonyuk** [comment]
Just use method, if previous message exist it will be deleted
`await ctx.deleteMessage();`

**Comment by Texnocom** [comment]
**After selecting the button, I am looking for a solution to redirect the written message to the channel**


![2021-03-27_15-02-00](https://user-images.githubusercontent.com/76031213/112718577-6a8e7580-8f0d-11eb-8f8f-2a9737f46b43.png)
