### ISSUE TITLE
Problem with Webhook (no response)

### ISSUE THREAD

**Issue by TiagoDanin** [telegraf/telegraf#497]
## Context

Problem with Webhook (no response)

* Telegraf.js Version: 3.23.0
* Node.js Version: 9.9.0
* Operating System: Manjaro (Kenel 4.14.52)

## Expected Behavior

Bot send the message via WebHook

## Current Behavior

Bot not send the message

### Steps to Reproduce

My code: https://gist.github.com/TiagoDanin/c6551845298d889eacb0dc4a7ab5e446

1. Run command "2"
2. Puff.. No response 

### Details

![image](https://user-images.githubusercontent.com/5731176/44961693-9d099a80-aeeb-11e8-9236-513a657d849e.png)
Command "1" - Work

![image](https://user-images.githubusercontent.com/5731176/44961703-c296a400-aeeb-11e8-8e34-febdb53764c9.png)
Command "2" - No work

![image](https://user-images.githubusercontent.com/5731176/44961713-ec4fcb00-aeeb-11e8-8f1f-3dff7819634e.png)
Debug log

![image](https://user-images.githubusercontent.com/5731176/44961742-8283f100-aeec-11e8-91ab-89e724c280ff.png)
Telegram

**Comment by tva10** [comment]
Hello @TiagoDanin

Is your example works fine in polling mode?
You need to check what your promise chain was not broken 
or try to disable `webhookReply` option

I think this #320 issue is the same

**Comment by TiagoDanin** [comment]
Hi @tva10, based on [your comment](https://github.com/telegraf/telegraf/issues/320#issuecomment-362674832) can solve the problem, thank.

```javascript
bot.hears('2', async (ctx) => { //Use async
	var a = async (ctx) => {
		//....//
		ctx.replyWithHTML(`<b>10 == ${data}</b>`)
	}
	await a(ctx) //Use await
})
```

**Comment by Piterden** [comment]
Why not just
```js
bot.hears('2', async (ctx) => {
  /* .... */
  await ctx.replyWithHTML(`<b>10 == ${data}</b>`)
})
```
????

**Comment by TiagoDanin** [comment]
@Piterden This is an example of how to work on my bot (https://github.com/SynkoDevelopers/EDPlugins). 
https://github.com/SynkoDevelopers/EDPlugins/blob/f47b8de7998fc8fef84ec77f8d9300b80f3eaf17/index.js#L68 plugins are like modules.
