### ISSUE TITLE
Strange Error 500 with no response text.

### ISSUE THREAD

**Issue by AFunnyMeme** [telegraf/telegraf#500]
## Context

Originally I was trying to have a video file saved locally be sent as a reply through a callback, and I received the 500 error below (with no response text). After testing this happens for any API call involving mulitpart upload

* Telegraf.js Version: 3.23.0
* Node.js Version: 10.9.0
* Operating System: Windows 10 Enterprise 64-Bit

## Failure Information (for bugs)

```
{ Error: 500: Unsupported http response from Telegram
   at buildConfig.then.then.then.then (C:\node\bot\node_modules\.registry.npmjs.org\telegraf\3.23.0\node_modules\telegraf\core\network\client.js:254:17)
   at process._tickCallback (internal/process/next_tick.js:68:7)
 code: 500,
 response:
  { error_code: 500,
    description: 'Unsupported http response from Telegram',
    response: '' },
 description: 'Unsupported http response from Telegram',
 parameters: {},
 on:
  { method: 'sendVideo',
    payload: { chat_id: 303893144, video: [Object] } } }
```

### Steps to Reproduce

Currently unsure of how this is happening.

**Comment by CoolShitWebsite** [comment]
After some troubleshooting I believe this is due to one of the dependencies telegraf uses, as this only occurs on a fresh `npm install`.

**Comment by saxjonas** [comment]
What parameters are you using for the function call?
I was dealing with similar issues for sendPhoto. The `client.js` file gave me some clues:
```
  if (media.url) {
    return fetch(media.url).then((res) =>
      form.addPart({
        headers: { 'content-disposition': `form-data; name="${id}"; filename="${fileName}"` },
        body: res.body
      })
    )
  }
  if (media.source) {
    if (fs.existsSync(media.source)) {
      fileName = media.filename || path.basename(media.source)
      media.source = fs.createReadStream(media.source)
    }
    if (isStream(media.source) || Buffer.isBuffer(media.source)) {
      form.addPart({
        headers: { 'content-disposition': `form-data; name="${id}"; filename="${fileName}"` },
        body: media.source
      })
    }
  }
```
That is: 
`sendPhoto(chat_id,{url: [url] })` will use fetch()
`sendPhoto(chat_id,{source: [local_path]})` will create a local stream
`sendPhoto(chat_id,{source: [stream/buffer]})` will use the existing buffer/stream

This ended up working even with a fresh npm install.

**Comment by saxjonas** [comment]
Have you tried just passing the path to the source-parameter instead of a buffer? As you can see in the code above from client.js, telegraf takes care of creating the buffer automatically.

**Comment by CoolShitWebsite** [comment]
Apologies for the delayed response.

> Have you tried just passing the path to the source-parameter instead of a buffer?

I have, and the error still persists, regardless of media type.

**Comment by dotcypress** [comment]
Closing. 
Feel free to open new issue if needed
