### ISSUE TITLE
How to send location in telegraf ? 

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#501]
Is something wrong in the `sendLocation` with the given code !

```
bot.command('location', (ctx) => ctx.sendLocation(ctx.message.message_id, '11.120310', '76.119350'));
bot.command('location', (ctx) => ctx.sendLocation(ctx.message.message_id, ['11.120310', '76.119350']));
bot.command('location', (ctx) => ctx.sendLocation(['11.120310', '76.119350']));
bot.command('location', (ctx) => ctx.sendLocation('11.120310', '76.119350'));
```
I am getting error like this when running any of the code 

> TypeError: ctx.sendLocation is not a function

**Comment by TiagoDanin** [comment]
Use the `ctx.replyWithLocation('11.120310', '76.119350')` or `bot.telegram.sendLocation(ctx.chat.id, '11.120310', '76.119350')`

**Comment by Piterden** [comment]
Also
```js
ctx.tg.sendLocation(ctx.chat.id, '11.120310', '76.119350')
```
should work too...

**Comment by oalmatov** [comment]
How do I send multiple location points through telegraf?

**Comment by Piterden** [comment]
@oalmatov try to use `Promise.all()` or either `for await of` on an array of your location sends.
