### ISSUE TITLE
Stage support to callback_query.

### ISSUE THREAD

**Issue by Fazendaaa** [telegraf/telegraf#502]
I'm trying to use [Stage](https://telegraf.js.org/#/?id=stage) in Callback Query, by entering a scene due to the button pressed.  This is to handle differentiate some users buttons request in bot conversations to any other chat. But, right now, is not available. Is there any way to make this work?

**Comment by Piterden** [comment]
What you mean not available? Show your code, please...

**Comment by Fazendaaa** [comment]
@Piterden my code

```js
bot.use(session());

bot.on('callback_query', async ({ i18n, callbackQuery, scene }) => {
    console.log(scene);
});

bot.on('text', async ({ i18n, message, replyWithMarkdown, scene }) => {
    console.log(scene);
});
```

The first console.log prints *undefined* and the second works just fine.

**Comment by Piterden** [comment]
```js
const stage = new Stage(scenesArray)

bot.use(stage.middleware())
```
Do you have this?

**Comment by Fazendaaa** [comment]
@Piterden , yes!!! Sorry, forgot to add this in the example.

**Comment by Piterden** [comment]
https://github.com/Piterden/chessbot/blob/master/src/handlers/join/index.js#L30-L32

**Comment by Fazendaaa** [comment]
I have the following stages:

```js
bot.use(anilistStage.middleware());
bot.use(locationStage.middleware());
```

**Comment by Piterden** [comment]
I didn't hear about multistage bots. Usually, there is one stage and a few scenes.

**Comment by Fazendaaa** [comment]
Thanks, @Piterden . My bad.
