### ISSUE TITLE
Heroku and long polling? 

### ISSUE THREAD

**Issue by TorlanDelta** [telegraf/telegraf#503]
I saw #44, but I didnt get any input on my question there so I'll repost: How do I use it with long polling though? Or do I have to use webhooks if I want to deploy to heroku? 

The example posted in the thread did not do it for me too. 

In yagop node-telegram-bot-api I just blindly have tried this - `bot.startPolling({port:process.env.PORT})`

Did not work for telegraf. Shame, I like it a lot :O

**Comment by TorlanDelta** [comment]
Pinpointed the issue. 

Composer bots cannot process enter or leave calls. They just ignore them, even though composerbot.use(stage.middleware()) works as expected. Kinda counterintuitive and not documented at all afaik.

**Comment by dotcypress** [comment]
@TorlanDelta  [startPolling method parameters](https://telegraf.js.org/#/?id=startwebhook)
