### ISSUE TITLE
How to handle deep linking? (command parameters, like /start test) 

### ISSUE THREAD

**Issue by TorlanDelta** [telegraf/telegraf#504]
I couldn't find anything about how can I handle command parameters. bot.command does not support regexes, which means I cannot make it handle deep linking params
I have a code such as this: 
```
bot.command('start', ctx => startstuff()) 

bot.hears(/^\/start (.*)$/, ctx => registerReferral()) 
```

`registerReferral()` doesnt get fired when using https://telegram.me/mybot?start=test link to access and start it. Instead `startstuff()` responds.

**Comment by TorlanDelta** [comment]
Turns out the order in which I place handlers matters. If `hears` comes before `command` it works. 

I'm not sure whether this is a bug or a feature xD

**Comment by Piterden** [comment]
```js
bot.hears(/^\/start[ =](.+)$/, (ctx) => registerReferral())
```

**Comment by Christian-X** [comment]
you can use the bot.command handler for arguments as well - message.text will contain the whole line sent to the bot.

do e.g. 

let args=message.text.split(' ')
where args[0] will be your bot-command, and args[1..] will be all space delimited parts afterwards

**Comment by 777genius** [comment]
If you want to use URL params with bot like this: `action=delete&userId=123`

1. Convert payload to base64: `btoa('a=123&b=gdfgd-gdfgdfgdf')`
2. Pass it to the bot: https://telegram.me/MY_COOL_BOT?start=YT0xMjMmYj1nZGZnZC1nZGZnZGZnZGY=
3. Handle

``` js
  bot.onText(/\/start/, (msg) => {
    // Removes /start prefix
    const payload = msg.text!.substring(6);

    if (payload.length) {
      const url = Buffer.from(payload, 'base64').toString();
      const params = Object.fromEntries(new URLSearchParams(url).entries());

      // Result: { a: '123', b: 'gdfgd-gdfgdfgdf' }
      console.log(params);
    } else {
      // Start bot without payload
    }
  });
```
