### ISSUE TITLE
How to connect the bot to mtproto proxy?

### ISSUE THREAD

**Issue by aminjoharinia** [telegraf/telegraf#507]
Hi
How the bot could connect to mtproto proxy ?

**Comment by Piterden** [comment]
The MTProto proxy should be run on a non-blocked server. So if you would run your bot there, it will work fine. The same is for the opposite situation: if you would run proxy on server which was blocked, your proxy will lose a sense and wouldn't work at all.

**Comment by aminjoharinia** [comment]
The bot is running on a raspberry pi in a blocked server country
It is using for home automation systems and it should be local
I need to connect mtproto proxy like a client
Something similar to  connect to socks5
'''
var socks = require('socksv5');
var http = require('http');

var socksConfig = {
  proxyHost: 'localhost',
  proxyPort: 1080,
  auths: [ socks.auth.None() ]
};
'''

**Comment by Piterden** [comment]
Where are you going to run your proxy, or are you going to use external?

**Comment by Piterden** [comment]
Bot is not the client-side, either it is the server, you can simple launch your bot near your mtproto server.

**Comment by Piterden** [comment]
3. 6 euro VDS

**Comment by aminjoharinia** [comment]
@Piterden i have a vps in france
it works perfectly in telegram desktop , android ,...
How to connect the bot (.js file)?

**Comment by Piterden** [comment]
Run your bot on that VPS in the France. RPi is not a good solution for the bot's server, anyway...

**Comment by aminjoharinia** [comment]
@Piterden 
I run openvpn , but i have some problems
Don't make me cry , every thing is blocked here , freedom has no meaning

**Comment by Piterden** [comment]
Why don't yuou run your bot in france. No there is no way to connect bot to mtproto. At least for now. Look in client.js of telegraf.

**Comment by cybercoder** [comment]
The same problem, how telegraf can connect to telegram servers through external MtProto proxy servers? @aminjoharinia Did you find any solution?

**Comment by VadimMalykhin** [comment]
You can use [tor](https://www.torproject.org/) as a VPN.
```js
import https from 'https'
import Telegraf from 'telegraf'
import { SocksProxyAgent } from 'socks-proxy-agent'

process.env.SOCKS_PROXY_HOST = 'socks://localhost:9050'
process.env.BOT_TOKEN = '0000000000:8JWgxaInU7MHu2wE2lRc5ziOVBePKkVgcYF'

const agent = new SocksProxyAgent(process.env.SOCKS_PROXY_HOST)

https.get('https://api.ipify.org?format=json', { agent }, res => {
  res.on('data', d => {
    console.log(d.toString())
  })
})

const bot = new Telegraf(process.env.BOT_TOKEN, {
  telegram: {
    agent
  }
})

bot.telegram.getMe().then(botInfo => {
  bot.options.username = botInfo.username
})

bot.use(async (ctx, next) => {
  const start = new Date()
  await next()
  const ms = new Date() - start
  console.log(`${bot.options.username} response time: ${ms}ms`)
})

bot.on('text', ctx => {
  ctx.reply(`Hello World (${new Date().getTime()})`)
})

bot.launch()
```

**Comment by cybercoder** [comment]
> You can use [tor](https://www.torproject.org/) as a VPN.
> 
> ```js
> import https from 'https'
> import Telegraf from 'telegraf'
> import { SocksProxyAgent } from 'socks-proxy-agent'
> 
> process.env.SOCKS_PROXY_HOST = 'socks://localhost:9050'
> process.env.BOT_TOKEN = '0000000000:8JWgxaInU7MHu2wE2lRc5ziOVBePKkVgcYF'
> 
> const agent = new SocksProxyAgent(process.env.SOCKS_PROXY_HOST)
> 
> https.get('https://api.ipify.org?format=json', { agent }, res => {
>   res.on('data', d => {
>     console.log(d.toString())
>   })
> })
> 
> const bot = new Telegraf(process.env.BOT_TOKEN, {
>   telegram: {
>     agent
>   }
> })
> 
> bot.telegram.getMe().then(botInfo => {
>   bot.options.username = botInfo.username
> })
> 
> bot.use(async (ctx, next) => {
>   const start = new Date()
>   await next()
>   const ms = new Date() - start
>   console.log(`${bot.options.username} response time: ${ms}ms`)
> })
> 
> bot.on('text', ctx => {
>   ctx.reply(`Hello World (${new Date().getTime()})`)
> })
> 
> bot.launch()
> ```

this is sucks

**Comment by VadimMalykhin** [comment]
> > You can use [tor](https://www.torproject.org/) as a VPN.
> > ```js
> > import https from 'https'
> > import Telegraf from 'telegraf'
> > import { SocksProxyAgent } from 'socks-proxy-agent'
> > 
> > process.env.SOCKS_PROXY_HOST = 'socks://localhost:9050'
> > process.env.BOT_TOKEN = '0000000000:8JWgxaInU7MHu2wE2lRc5ziOVBePKkVgcYF'
> > 
> > const agent = new SocksProxyAgent(process.env.SOCKS_PROXY_HOST)
> > 
> > https.get('https://api.ipify.org?format=json', { agent }, res => {
> >   res.on('data', d => {
> >     console.log(d.toString())
> >   })
> > })
> > 
> > const bot = new Telegraf(process.env.BOT_TOKEN, {
> >   telegram: {
> >     agent
> >   }
> > })
> > 
> > bot.telegram.getMe().then(botInfo => {
> >   bot.options.username = botInfo.username
> > })
> > 
> > bot.use(async (ctx, next) => {
> >   const start = new Date()
> >   await next()
> >   const ms = new Date() - start
> >   console.log(`${bot.options.username} response time: ${ms}ms`)
> > })
> > 
> > bot.on('text', ctx => {
> >   ctx.reply(`Hello World (${new Date().getTime()})`)
> > })
> > 
> > bot.launch()
> > ```
> 
> this is socks

@cybercoder, of course, this is the sOcks ~~not sUcks~~ protocol. 😀

One of the solutions that allows Telegraf bots establish persistent connection to Telegram servers, where Telegram was banned in the countries such as Iran, Russia, China etc... Except the last one.
Tor is also banned and blocked by the Great Firewall of China.
Read the [``socks-proxy-agent``](https://www.npmjs.com/package/socks-proxy-agent) docs to change Tor to our own VPN.

**Comment by cybercoder** [comment]
> > > You can use [tor](https://www.torproject.org/) as a VPN.
> > > ```js
> > > import https from 'https'
> > > import Telegraf from 'telegraf'
> > > import { SocksProxyAgent } from 'socks-proxy-agent'
> > > 
> > > process.env.SOCKS_PROXY_HOST = 'socks://localhost:9050'
> > > process.env.BOT_TOKEN = '0000000000:8JWgxaInU7MHu2wE2lRc5ziOVBePKkVgcYF'
> > > 
> > > const agent = new SocksProxyAgent(process.env.SOCKS_PROXY_HOST)
> > > 
> > > https.get('https://api.ipify.org?format=json', { agent }, res => {
> > >   res.on('data', d => {
> > >     console.log(d.toString())
> > >   })
> > > })
> > > 
> > > const bot = new Telegraf(process.env.BOT_TOKEN, {
> > >   telegram: {
> > >     agent
> > >   }
> > > })
> > > 
> > > bot.telegram.getMe().then(botInfo => {
> > >   bot.options.username = botInfo.username
> > > })
> > > 
> > > bot.use(async (ctx, next) => {
> > >   const start = new Date()
> > >   await next()
> > >   const ms = new Date() - start
> > >   console.log(`${bot.options.username} response time: ${ms}ms`)
> > > })
> > > 
> > > bot.on('text', ctx => {
> > >   ctx.reply(`Hello World (${new Date().getTime()})`)
> > > })
> > > 
> > > bot.launch()
> > > ```
> > 
> > 
> > this is socks
> 
> @cybercoder, of course, this is the sOcks ~not sUcks~ protocol. 😀
> 
> One of the solutions that allows Telegraf bots establish persistent connection to Telegram servers, where Telegram was banned in the countries such as Iran, Russia, China etc... Except the last one.
> Tor is also banned and blocked by the Great Firewall of China.
> Read the [`socks-proxy-agent`](https://www.npmjs.com/package/socks-proxy-agent) docs to change Tor to your own VPN.

The problem is ```socks``` connection will block from inside in that countries, as fast as you can think. :)

**Comment by VadimMalykhin** [comment]
> The problem is socks connection will block from inside in that countries, as fast as you can think. :)

@cybercoder, I understand 🙁, but for me that solution works great, at least in my country 🤫🤐.
As a second solution, i think you need to use something like this [``TDLib bindings for Node.js``](https://github.com/nodegin/tglib) which uses [``TDLib (Telegram Database library)``](https://github.com/tdlib/td) which uses your [``Telegram Account``](https://my.telegram.org/auth) ``api_id`` ``api_hash`` and a phone number for authorization. As i can see a Telegraf still not implemented MTProto feature.

**Comment by hosseinse1919** [comment]
> Why don't yuou run your bot in france. No there is no way to connect bot to mtproto. At least for now. Look in client.js of telegraf.

cuz he is spammer .. want free one ... and 7 euro per month is high price here ... lol
