### ISSUE TITLE
editMessageReplyMarkup fails at random times

### ISSUE THREAD

**Issue by austinhuang0131** [telegraf/telegraf#516]
## Context

* Telegraf.js Version: 3.22.2
* Node.js Version: 8.12.0
* Operating System: I think https://glitch.com uses some sort of Linux

## Expected Behavior

Everytime I run editMessageReplyMarkup, it should edit the message markup.

## Current Behavior

I checked the markup JSON and it's right...

```js
[ [ { text: '✅',
      callback_data: 'send:-1001351539721:2:1' } ],
  [ { text: 'Back', callback_data: 'back' } ] ]
```

Yet sometimes when I trigger editMessageReplyMarkup through a inline keyboard button, it clears the keyboard.
### Steps to Reproduce

1. Make a message with an inline keyboard.
2. `editMessageReplyMarkup` it upon responding a callback query.
3. At random times it will clear all the buttons without replacing them with new buttons.

### Failure Logs

I tried to `.catch` but it gives me nothing.

**Comment by Piterden** [comment]
I don't have it. Probably it caused by your near placed code?

**Comment by austinhuang0131** [comment]
Yeah, I run `editMessageText` immediately before `editMessageMarkup`.

**Comment by Christian-X** [comment]
do you wait for the editMessageText ?

random times could be due to a race condition, depending on the order the updates are executed in telegrams server.

you can alter the reply Markup with editMessageText as well; both in one call. That might make more sense.

**Comment by austinhuang0131** [comment]
just realized that i can do markups in editMessageText
