### ISSUE TITLE
How to enter second scene after leaving first scene ? 

### ISSUE THREAD

**Issue by vlad82010** [telegraf/telegraf#518]
How to enter second scene after leaving first scene ? 
`await ctx.reply("Start");`
`await ctx.scene.enter('firstScene');`
`await ctx.scene.enter('secondScene');`
`await ctx.reply("End ");`

When I do `enter('secondScene')` it automatically leave first scene and enter second.
I need to start secondScene after I myself leave the firstScene.
Sorry for my English)

**Comment by Piterden** [comment]
Try to write in Russian, I am not follow...

**Comment by vlad82010** [comment]
> Try to write in Russian, I am not follow...

Когда я выполняю код, что описал выше, то получаю следующее:

1. Сообщение "Start"
2. Enter firstScene
3. Leave firstScene
4. Enter secondScene
5. Leave secondScene
6. Сообщение "End"

А я хочу, чтобы было так:

1. Сообщение "Start"
2. Enter firstScene
3. !!! Выполняю действия в firstScene, где в итоге делаю в определённый момент leave()
4. Leave firstScene
5. !!! Только после того, как я сам сделал leave() с первой сцены, автоматически запускается вторая сцена
6. Enter secondScene
7. !!! Выполняю действия в secondScene, где в итоге делаю в определённый момент leave()
8. Leave secondScene
9. !!! Только после того, как я сам сделал leave() со второй сцены, выводится сообщение "End"
10. Сообщение "End"

**Comment by Piterden** [comment]
5. Don't make `leave()`, just call `enter('secondScene')`.
9. You can override a `leave()` handler for scene directly.
