### ISSUE TITLE
Could the bot process it's own message and delete the previous message sent by the same bot?

### ISSUE THREAD

**Issue by nicholasteoyk** [telegraf/telegraf#520]
From what I've found in the telegram libraries, it seems that bot-to-bot interaction is not possible. But I am not too sure if it applies to the bot itself interacting with itself. I tried tracking message ids but it seemed almost impossible once edits are involved.

Eg: 
Bot sends: message1
User sends: "Hello world!"
Intended bot action: Bot deletes message1 and sends: message2

**Comment by Piterden** [comment]
I suppose, it could, but if it would have admin rights.

**Comment by Piterden** [comment]
Easier than what? You could easily track messages by user id.

**Comment by nicholasteoyk** [comment]
What if the user id I need is my bot's user id - is that possible..?

**Comment by Piterden** [comment]
Why not?

**Comment by nicholasteoyk** [comment]
Could you please show me an example how..? :)

**Comment by Piterden** [comment]
Of course. Show me how do you do it and I will try to fix.

**Comment by Piterden** [comment]
You have wrong RegExp. Try `new RegExp('.*')` or `/.*/` without new.

**Comment by nicholasteoyk** [comment]
AH! Thank you Piterden! :)
