### ISSUE TITLE
how can i ask question and wait for replay

### ISSUE THREAD

**Issue by natget21** [telegraf/telegraf#522]
hello, is it possible to wait for a replay for a single question if so can you give example on how to do this 

example
```
ctx.reply('Send me your name')
ctx.waitForAnswer().then(ctx.replay("i will call you " + ctx.message+" from now on");
```

so the bot will send a message and the bot will accept the users response what ever he types like the 
`bot.on('message'.....)` but only for one time until he replays then it will not

Thanks,

**Comment by Piterden** [comment]
https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js

**Comment by natget21** [comment]
@Piterden  thanks for your replay, i have seen this but is there a way simpler/shorter just for one task step only?

**Comment by Piterden** [comment]
There can be many ways to resolve it. For example you can add some variables and conditions. It is JavaScript.

**Comment by natget21** [comment]
@Piterden but how could i set a variable for that specific user i think i need to use a session but i dont know how to control the session for specific user at that particular command? can you please provide me example if it was this scenario 

 
user : /edit_name
bot : "ok send me your name"
user : "jon doe"
bot  :  "your mane has been edited to jon doe"

thanks

**Comment by Piterden** [comment]
Sure, here is an example of different actions, depending on `ctx.session` properties values:
https://github.com/Piterden/chessbot/blob/master/src/handlers/moves/index.js

**Comment by natget21** [comment]
@Piterden Thanks a lot i got how the session works now you were really helpful
