### ISSUE TITLE
Hi! Cant run simple webhook bot from your example ((((((

### ISSUE THREAD

**Issue by eugen35** [telegraf/telegraf#524]
## Context

On webserver:
* Telegraf.js Version: "telegraf": "^3.24.0"
* Node.js Version:  v9/2/0
* Operating System: Ubuntu 18

And winows local machine fails too:
* Telegraf.js Version: "telegraf": "^3.24.0"
* Node.js Version:  v9/2/0
* Operating System: Win 10 Pro x64

## Expected Behavior

Bot listens and answers. I have Centos

## Current Behavior

Bot not answers. Not listen (

### Steps to Reproduce
This is my code:
```
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN || 'xxxxxxx')
bot.command('image', (ctx) => ctx.replyWithPhoto({ url: 'https://picsum.photos/200/300/?random' }))
bot.on('text', ({ replyWithHTML }) => {console.log('Incoming');return replyWithHTML('<b>Hello</b>')})

// Set telegram webhook
// npm install -g localtunnel && lt --port 6000
bot.telegram.setWebhook('https://-----.localtunnel.me/secret-path')

// Start https webhook
bot.startWebhook('/secret-path', null, 6000)



```

## On windows i see next text:
(node:11672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to https://api.telegram.org/botxxxxxxxx/setWebhook failed, reason: certificate has expired

**Comment by Piterden** [comment]
Do you have a correct certificate?

**Comment by eugen35** [comment]
Hi! Maybe i do (self signed key.pem and cert.pem generated yesterday with openssl. I have tested them online with https://www.sslshopper.com/certificate-decoder.html):

> Locality: Perm
> Country: RU
> Valid From: October 1, 2018
> Valid To: October 1, 2019
> Serial Number: xxxx

**But where must i place it in my code?** 
There is in the example above no place for that setting.

**Comment by tva10** [comment]
@eugen35, Hello
You can send your certificate to the Telegram via setWebhook, if you self signed them
But you also need to configure TLS with this cert on your https server
Check examples in https://telegraf.js.org/#/?id=webhooks

```javascript 
config = { source: fs.readFileSync( pathToYourCert.pem ) }
////	path, crtFile, maxConnections(40, 1-100), allowedUpdates
app.telegram.setWebhook( path, config )
```

**Comment by Piterden** [comment]
I use letsencrypt generated certificates for webhook bot https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/.env.example#L6-L7

**Comment by tva10** [comment]
@eugen35, Nope
If you are using Localtunnel, you don't need to install tls and send cert to the telegram. Because it should provide own valid certificate

But if you run your own web server on white IP address, you can run https server (express, nginx, .... or inside `startWebhook`) with your TLS options without using Localtunnel proxy
If you don't have white IP, try to use Polling mode or forward port

Second thing/ When you send selfsinged certificate, you should send content of file, not that file name
Mb that thing raise cert expired error, but it is invalid certificate also

It should be looks like
```javascript
bot.telegram.setWebhook('https://190.1.50.51:8443/secret-path',{ source: fs.readFileSync(  './pathTo/cert.pem') })
  .catch(err=>console.log(err))

bot.startWebhook('/secret-path', tlsOptions, 8443, '190.1.50.51')
```
If you are using port forwarding
```javascript
// also need to add rule 190.1.50.51:8443 -> 192.168.0.10: 3000
bot.telegram.setWebhook('https://190.1.50.51:8443/secret-path',{ source: fs.readFileSync(  './pathTo/cert.pem') })
  .catch(err=>console.log(err))

bot.startWebhook('/secret-path', tlsOptions, 3000, '192.168.0.10')
```


---
Notes 
1. You will not be able to receive updates using getUpdates for as long as an outgoing webhook is set up. 
2. To use a self-signed certificate, you need to upload your public key certificate using certificate parameter. Please upload as InputFile, sending a String will not work. 
3. Ports currently supported for Webhooks : 443, 80, 88, 8443 .

NEW! If you're having any trouble setting up webhooks, please check out this [amazing guide to Webhooks ](https://core.telegram.org/bots/webhooks).

**Comment by eugen35** [comment]
Ok. if i use the code:
```
const bot = new Telegraf('xxxxx')
bot.on('text', ({ replyWithHTML }) => replyWithHTML('<b>Hello</b>'))
// If you are using Localtunnel, you don't need to install tls and send cert to the telegram. Because it should provide own valid certificate
// npm install -g localtunnel && lt --port 3000
bot.telegram.setWebhook('https://-----.localtunnel.me/secret-path')
bot.startWebhook('/secret-path', null, 3000)
```
I have next error in api.telegram.org: 

> {"ok":false,"error_code":502,"description":"Bad Gateway"}

and error in console of ubuntu:  

> { Error: 400: Bad Request: bad webhook: Failed to resolve host: Name or service not known
>     at buildConfig.then.then.then.then (/opt/webserver/chat/node_modules/telegraf/core/network/client.js:262:17)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 400,
>   response:
>    { ok: false,
>      error_code: 400,
>      description:
>       'Bad Request: bad webhook: Failed to resolve host: Name or service not known' },
>   description:
>    'Bad Request: bad webhook: Failed to resolve host: Name or service not known',
>   parameters: {},
>   on:
>    { method: 'setWebhook',
>      payload: { url: 'https://-----.localtunnel.me/secret-path' } } }

**Comment by Piterden** [comment]
Ну телега то заблокирована! Че ж ты хочешь?

**Comment by eugen35** [comment]
Дак получается этот ваш код из примера не запустить?

**Comment by Piterden** [comment]
> Дак получается этот ваш код из примера не запустить?

Unfortunately not from local. Or either you can setup a global proxy for your local computer.

**Comment by eugen35** [comment]
I run it from ubuntu vps, which hosted in Moskau

**Comment by Piterden** [comment]
This IP is blocked by our government.

**Comment by Piterden** [comment]
Now try to
```
wget api.telegram.org
```

**Comment by eugen35** [comment]
index.html

**Comment by Piterden** [comment]
Are you trolling me?

**Comment by eugen35** [comment]
Not.

**Comment by eugen35** [comment]
Not. I three days try to use telegram with webhook(

**Comment by eugen35** [comment]
With polling all is good

**Comment by Piterden** [comment]
Wget would anyway gave you index.html if there is not defined document name (index.html.1 if you already have index.html) I mean what is the content of that index.html?

Because if you have working polling, then your server's provider didn't block telegram gateway.

**Comment by eugen35** [comment]
<meta charset="utf-8">                                                
    <title>Bots: An introduction for developers</title>                   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="description" content="Bots are third-party application
s that run inside Telegram. Users can interact with bots by sending them m
essages, commands~@">                                                     
    <meta property="og:title" content="Bots: An introduction for developer
s">                                                                       
    <meta property="og:image" content="https://core.telegram.org/file/8111
40663/1/uHVzwsRJz3Y/a499733c59840694ca">                                  
    <meta property="og:description" content="Bots are third-party applicat
ions that run inside Telegram. Users can interact with bots by sending the
m messages, commands~@">                                                  
    <link rel="shortcut icon" href="/favicon.ico?3" type="image/x-icon" />
                                                                          
    <link href="/css/bootstrap.min.css?2" rel="stylesheet">               
                                                                          
    <link href="/css/telegram.css?152" rel="stylesheet" media="screen">   
    <style>

**Comment by Piterden** [comment]
NOT blocked. The problem is in your configuration.

Try to clone [my webhook bot](https://github.com/Piterden/syntax-highlighter-bot) and launch it.

**Comment by eugen35** [comment]
In file: "bots are thid party....

**Comment by Piterden** [comment]
Write me in telegram. To not spamming here

**Comment by tva10** [comment]
https://github.com/telegraf/telegraf/issues/524#issuecomment-427011881

> { method: 'setWebhook',
> payload: { url: 'https://-----.localtunnel.me/secret-path' } } }

When you are trying to use localtunnel, you need to run `lt --port 3000` first
Then it generate you your private link, which you should use instead of `"https://-----.localtunnel.me"`
This will proxy all queries and apply them at 127.0.0.1:3000

**Comment by eugen35** [comment]
Thank you. But i can try it only tomorrow.

**Comment by eugen35** [comment]
To: Write me in telegram. To not spamming here. What is your telegram nick?

**Comment by eugen35** [comment]
> > { method: 'setWebhook',
> > payload: { url: 'https://-----.localtunnel.me/secret-path' } } }
> 
> When you are trying to use localtunnel, you need to run `lt --port 3000` first
> Then it generate you your private link, which you should use instead of `"https://-----.localtunnel.me"`
> This will proxy all queries and apply them at 127.0.0.1:3000

Its working ))))
