### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by natget21** [telegraf/telegraf#525]
hey again, i have been looking and i couldn't find examples or written documentation

so here is my question is there a way to implement localization if there is how could i implement it? if there is none how can i achieve it?

thanks

**Comment by Piterden** [comment]
What you mean "localization"?

**Comment by dotcypress** [comment]
Check this out: https://github.com/telegraf/telegraf-i18n

**Comment by Piterden** [comment]
Oh! Didn't know it, sorry.

**Comment by natget21** [comment]
thanks alot
