### ISSUE TITLE
Other Bot message does not showing in log 

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#527]
I am using @combot in the same group where use telgraf made bot. Unfortunately it doesn't show any log when @combot put messages in the group. 

Here is my current code 
```
console.log(ctx.message);

bot.on('text', (ctx) => {
  console.log(ctx.message)
  console.log("=========")
});
```
Bot are not giving any result if the messages are coming from another bot for example @combot

Any idea why not getting bot's log ?  🤔

**Comment by athimannil** [comment]
> I am using @combot in the same group where use telgraf made bot. Unfortunately it doesn't show any log when @combot put messages in the group.
> 
> Here is my current code
> 
> ```
> console.log(ctx.message);
> 
> bot.on('text', (ctx) => {
>   console.log(ctx.message)
>   console.log("=========")
> });
> ```
> Bot are not giving any result if the messages are coming from another bot for example @combot
> 
> Any idea why not getting bot's log ? 🤔

**Comment by athimannil** [comment]
@Piterden I think bot can't see messages sent by other bots

**Comment by Piterden** [comment]
https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

First link from Google
