### ISSUE TITLE
UnhandledPromiseRejection for async middlewares

### ISSUE THREAD

**Issue by dexterleng** [telegraf/telegraf#528]
I have this middleware:
```
module.exports = (db, limit) => async (ctx, next) => {
    throw new Error("blah");
}
```
And this middleware at the end to catch errors:
```
bot.catch((err) => {
    console.log("ERROR");
    console.log(err);
});
```
I get UnhandledPromiseRejection and the bot.catch does not catch the error; Any ideas why? In Express you do next(err) for it to be propagated down but I'm not sure how its done in telegraf.

**Comment by dexterleng** [comment]
`bot.command('add', validateCommands.validateAdd, limitSubscriptions(db, 3), async (ctx) => {`

heres where the middleware is used.

**Comment by dotcypress** [comment]
@dexterleng you calling `limitSubscriptions` outside of the middleware chain and you need to
