### ISSUE TITLE
Add to docs: Body-Parser Warning

### ISSUE THREAD

**Issue by agstover** [telegraf/telegraf#529]
Just a suggestion that in the Webhooks section of the docs, there should be a warning posted that the webhook handler uses 

`    req.on('data', (chunk) => {
      body += chunk.toString()
    })`

which means server.use(body-parser()) or server.use(express.json()) will cause the webhook to silently fail. Req comes in but bot.on() registers nothing. Extremely frustrating and easy to forget. This trips me up all the time.

**Comment by EmileSpecs** [comment]
Yes, please add to docs!

Spent half the day pulling my hair out over this, thank goodness I found this post!
