### ISSUE TITLE
Inline bot example: when calling answerInlineQuery, how is the id generated

### ISSUE THREAD

**Issue by bitinn** [telegraf/telegraf#532]
From the doc, `inline_query_id` is required:

https://core.telegram.org/bots/api#answerinlinequery

From the example and code, somehow this is handled by telegraf:

https://github.com/telegraf/telegraf/blob/develop/docs/examples/inline-bot.js#L24

https://github.com/telegraf/telegraf/blob/25c575a52aa57e85a9325be10ee1b58f4454d2ad/core/context.js#L149-L152

How is this id generated? Does it affect caching of query?

(I ran into a situation where my inline bot's search results are different from my API's actual result, and the result is likely cached in some way, but I need to figure out if it's a telegram issue or telegraf issue.)

**Comment by bitinn** [comment]
I am obviously looking at `cache_time` and `is_personal` to see if I should remove such caching, but I unsure how caching is actually done: I assume telegram cache by `query` string value, but then how is `inline_query_id` used?

**Comment by EdJoPaTo** [comment]
you dont need to provide the `inline_query_id` when using the 
[Context Shortcut](https://telegraf.js.org/#/?id=shortcuts): `ctx.answerInlineQuery(results, [extra])`

also see the [Extras](https://core.telegram.org/bots/api#answerinlinequery) as @bitinn pointed out correctly.

**Comment by EdJoPaTo** [comment]
Caching of the inline query can be done via `is_personal`, `query`, `offset`. I assume its just simpler for the Telegram API to handle the answer to a request via id.
