### ISSUE TITLE
Attach data to callbackButton

### ISSUE THREAD

**Issue by jakegladdengc** [telegraf/telegraf#536]
Hello,

I am making a bot to assign incoming clients to our agents at the office,

So far i can get the data in and send a message that creates a callbackButton for each possible agent,

So what i need now is to find a way to attach the ID of the incoming client to assign to the button so when the user clicks the callbackButton it knows what client ID to update in our CRM,

How would i go about doing this?,

Regards,

**Comment by Leekao** [comment]
+1

**Comment by kaiansaari** [comment]
Had a similar need & solved this using regex on the bot.action described here: https://github.com/telegraf/telegraf/blob/311f201729225efb2865fa942904813cd25c09cd/docs/README.md#action

**Example:**
With an inlineKeyboard with buttons of clientId's calling `client-clientId` as callback_data.

```
bot.action(/^[client]+(-[a-z]+)?$/, ctx => {
  console.log(ctx.match[1].split('-')[1] )
})
```

You can also something like this for dynamic buttons:
`ctx.editMessageText(text, Extra.markup(makeMenu(clientId)))`

```
function makeMenu(clientId){
  let clientButton = [Markup.callbackButton('📗 '+clientId+' Information', 'info-'+proj)]
  return Markup.inlineKeyboard([clientButton])
}
```

**Comment by mackbdev** [comment]
Clutch with a capital K, thanks!

This is my solution based on yours @kaiansaari

<pre>
<code>
let sendKeyboard = Markup.inlineKeyboard([Markup.button.callback('📢', `send ${msgID}`)])

bot.action(/send (.+)/, (ctx,next) => {
  let msgID = ctx.match[1]
  ctx.telegram.copyMessage(chatTo,notifyChannel,msgID)
  return ctx.answerCbQuery(`Announcement made!`).then(() => next())
})
</code>
</pre>
