### ISSUE TITLE
Please remove 'typings' directory

### ISSUE THREAD

**Issue by kraftwerk28** [telegraf/telegraf#537]
`index.d.ts` is probably broken, and I am not getting suggestions in Visual Studio Code

**Comment by Infl1ght** [comment]
> index.d.ts is probably broken, and I am not getting suggestions in Visual Studio Code
It works perfectly for me. Why do you think problem is in `index.d.ts`?

**Comment by kraftwerk28** [comment]
> > index.d.ts is probably broken, and I am not getting suggestions in Visual Studio Code
> 
> It works perfectly for me. Why do you think problem is in `index.d.ts`?

Yes. I forgot to `require('telegraf/telegraf')` instead of `require('telegraf')`.
