### ISSUE TITLE
Multiple wizards

### ISSUE THREAD

**Issue by yogakeen** [telegraf/telegraf#540]
Hi,
I would like to have several wizards in my bot.
I have the following (rough sketch) but cannot start wizard2 or wizard3?
Any help would be appreciated.
```
.....
const Stage = require("telegraf/stage");
const WizardScene = require("telegraf/scenes/wizard");
.....
const wiz1 = new WizardScene(
ctx => {...},
ctx => {...}
....
);
const wiz2 = new WizardScene(
ctx => {...},
ctx => {...}
....
);
const wiz3 = new WizardScene(
ctx => {...},
ctx => {...}
....
);

const stage = Stage([wiz1,wiz2,wiz3])
bot.command('wiz1', Stage.enter('wiz1')); // this works
bot.action('anAction', (ctx) => {Stage.enter('wiz2')}); // this does not work

```

**Comment by sadriddin** [comment]
@yogakeen 
Stage.enter returns function: 
https://github.com/telegraf/telegraf/blob/develop/stage.js#L38
Try 
`bot.action('anAction', (ctx) => {Stage.enter('wiz2')(ctx)})`;
Or
`bot.action('anAction', Stage.enter('wiz2'))`;

**Comment by yogakeen** [comment]
Sadriddin,
Thank you for the help.
