### ISSUE TITLE
[QUESTION] How to enter a scene without context but with chatId

### ISSUE THREAD

**Issue by SwiTool** [telegraf/telegraf#544]
I'm trying to enter a scene because a server side event happened.
I have the `chatId` but no context, since the user didn't talk in the chat.

How should I enter the scene ?

Here's a little bit of code:
```javascript
const PrivateMessage = new Scene('PRIVATE_MESSAGE')
PrivateMessage.enter((ctx) => ctx.reply('echo scene'))
PrivateMessage.leave((ctx) => ctx.reply('exiting echo scene'))
PrivateMessage.command('back', leave())
PrivateMessage.on('text', (ctx) => ctx.reply(ctx.message.text))

this.bot = new Telegraf(this.options.token, {username: this.options.username});
const stage = new Stage([PrivateMessage]);
this.bot.use(session());
this.bot.use(stage.middleware());

ipcMain.on('TelegramNotificationRequest', (ev, obj) => {
  Stage.enter(obj.type); // 'PRIVATE_MESSAGE'
})
```

When the `TelegramNotificationRequest` happens, I would like to enter the scene to ask the user what does he want to do.

Is it possible ?

**Comment by SwiTool** [comment]
Or maybe, how could I create my own context ? Don't know if that is possible.

**Comment by prodislav** [comment]
@SwiTool hello, did you resolve this problem ?

**Comment by SwiTool** [comment]
No, still searching, but I think i'm gonna add a keyboard to the automatic chat so the user can start a command and then have a context.

**Comment by dotcypress** [comment]
Guys, `enter` can't be called without context. If you want to achieve external control for user, you need to store this event and use it only when you have any update from user.

```js

this.bot = new Telegraf(this.options.token)
const stage = new Stage([PrivateMessage])
stage.on('message', (ctx) => {
  if (database.eventPending(ctx.chat.id)) {
    return ctx.scene.enter('blabla')
  } else {
    return next()
})
this.bot.use(session())
this.bot.use(stage.middleware())

```

**Comment by slyder** [comment]
Hello, isn't still possible to enter into the scene during some server event? I think it is a very useful case and is there any way to realize it?
So I need to enter into the scene, then send a message to the user and wait for a response.
