### ISSUE TITLE
How to handle bot mentions

### ISSUE THREAD

**Issue by ghost** [telegraf/telegraf#545]
I created a bot (amazing framework btw), I made it join a group, but how do I handle mentions?
`@BotFather` on `/setprivacy` says:
> 'Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.

How do I get the messages where the bot is mentioned when privacy is enabled? So far I tried with `bot.on('message')`, `bot.on('text')`, and `bot.mention(username)` (should it even be used like that?), but none works.
I have already provided the bot username, in fact `/help@botName` works. What am I missing?

**Comment by macarie** [comment]
I tried disabling the privacy mode and now `bot.mention(...)` works.
Is there a problem with `@BotFather`'s wording or the way the framework handles this case? 🤔

**Comment by ejnshtein** [comment]
I think this article can help:
https://core.telegram.org/bots#privacy-mode
