### ISSUE TITLE
Can't get hold of photo

### ISSUE THREAD

**Issue by Kaesebrot84** [telegraf/telegraf#55]
Hi,

I am trying to use your example in order to 'repost' an photo. Meaning chat member sends a photo, bot grabs photo and sends it too.

Got this code from your media-bot example:

```
const downloadPhotoMiddleware = (ctx, next) => {
  return app.telegram.getFileLink(ctx.message.photo[0].file_id)
    .then((link) => {
      ctx.state.fileLink = link
      console.log("LOG!!!:" + ctx.message.photo[0].file_id)
      return next()
    })
}
```

Now I am waiting for a 'photo' and try to reply:
```
app.on('photo', downloadPhotoMiddleware, (ctx, next) => {
  return ctx.replyWithPhoto({ source: '/directory/file.jpeg' })
})
```
What I get is:

> Error: Invalid file descriptor
>      at Array.map (native)
>      at Telegram.buildFormDataPayload (/app/node_modules/telegraf/lib/network/client.js:119:70)
>      at Telegram.callApi (/app/node_modules/telegraf/lib/network/client.js:79:45)
>      at Telegram.sendPhoto (/app/node_modules/telegraf/lib/telegram.js:103:17)
>      at TelegrafContext.replyWithPhoto (/app/node_modules/telegraf/lib/core/context.js:184:26)
>      at app.on (/app/index_bu.js:53:14) // Here: return ctx.replyWithPhoto({ source: '/directory/file.jpeg' })
>      at execute (/app/node_modules/telegraf/lib/core/composer.js:162:34)
>      at Promise.resolve.handler (/app/node_modules/telegraf/lib/core/composer.js:162:53)
>      at app.telegram.getFileLink.then (/app/index_bu.js:25:14)

So maybe I got it wrong, I thought that '/directory/file.jpeg' is some default path? Is there anything else I am missing? 

If I try the following:

```
app.on('photo', (ctx, next) => {
  return ctx.replyWithPhoto({ url: 'https://api.telegram.org/file/bo<BOT-TOTKEN>/photo/file_1.jpg' })
})
```

the bot does reply with the desired image/photo but it is in very low quality, why is that?

**Comment by dotcypress** [comment]
Hey.

Actually you don't need to use `getFileLink`, just send file id as follow:

```js
app.on('photo', (ctx, next) => {
  const photoId = ctx.photo[0].file_id
  return ctx.replyWithPhoto(photoId)
})
```

**Comment by Kaesebrot84** [comment]
@dotcypress Thank you this works except you forgot to add message.

```
app.on('photo', (ctx, next) => {
  const photoId = ctx.**message**.photo[0].file_id
  return ctx.replyWithPhoto(photoId)
})
```
