### ISSUE TITLE
Wrong function parameter sequence

### ISSUE THREAD

**Issue by destec** [telegraf/telegraf#552]
## Context

I'm trying to use `kickChatMember` function like: `ctx.kickChatMember(ctx.chat.id, ctx.from.id)`.
It showed that "Error: 400: Bad Request: wrong user_id specified". But after I changed the parameters' sequence like `ctx.kickChatMember(ctx.from.id, ctx.chat.id)` and it worked. So I think there's something wrong with the document.

* Telegraf.js Version: 3.24.1
* Node.js Version: 10.x
* Operating System: OSX 

## Expected Behavior

kick the member from the chat

## Current Behavior

Not worked, throw an error.

## Failure Information (for bugs)

Error: 400: Bad Request: wrong user_id specified

### Steps to Reproduce

calling by "ctx.kickChatMember(ctx.chat.id, ctx.from.id)"

### Failure Logs

Error: 400: Bad Request: wrong user_id specified

**Comment by tva10** [comment]
Hello @destec 
In your example you used wrapped method with specified `chat.id` for current update context
In the document showed original method - `telegram.kickChatMember(chatId, userId, [extra])`

E.g. there is `reply` method in context. It wraps `telegram.sendMessage(this.chat.id, ...args)`

https://github.com/telegraf/telegraf/blob/25c575a52aa57e85a9325be10ee1b58f4454d2ad/core/context.js#L302-L305

**Comment by destec** [comment]
@tva10 ahhhh, I see. Thanks!
I will close this issue.
