### ISSUE TITLE
How to optimize Telegraf WebHook installation with Express in Nodejs running on Google Firebase SDK?

### ISSUE THREAD

**Issue by alemens** [telegraf/telegraf#555]
## Context

Telegraf WebHook with Express in Nodejs running on Google Firebase SDK

### Steps to reproduce environment 

```javascript
const Telegraf = require('telegraf');
const { Extra, Markup } = Telegraf;
const bot = new Telegraf(`${functions.config().tgraf.botid}`);

const thook = express();
const tpath = `${functions.config().tgraf.patid}`;
thook.use(`/${tpath}`, async (req, res) => {
  try {
    let updates = req.body;
    console.log(updates);

    if (!Array.isArray(updates)) {
      updates = [updates];
    }

    await bot.handleUpdates(updates, res);

    if (!res.finished) {
      return res.end();
    }
    return Promise.resolve(res);
  } catch (err) {
    console.error('Webhook error', err);
    res.writeHead(500);
    return res.end();
  }
});
exports.thook = functions.https.onRequest(thook);
bot.telegram.setWebhook(`https://us-central1-${process.env.GCLOUD_PROJECT}.cloudfunctions.net/thook/${tpath}`);
```

### Logs

The response of `getWebhookInfo` Telegram Bot Api endpoint is this below:

```JSON
{
    "ok": true,
    "result": {
        "url": "https://us-central1-projectid.cloudfunctions.net/thook/AA123456789KK",
        "has_custom_certificate": false,
        "pending_update_count": 0,
        "last_error_date": 1542150829,
        "last_error_message": "Wrong response from the webhook: 500 Internal Server Error",
        "max_connections": 40
    }
}
```

I would like to improve performances: any suggestion on how to optimize Telegraf WebHook installation with Express in Nodejs running on Google Firebase SDK?

@dotcypress 

Thank you,

**Comment by alemens** [comment]
Please @dotcypress do you have any news about this?

**Comment by qm3ster** [comment]
Why don't you just use
```js
thook.use(bot.webhookCallback(`/${tpath}`))
```
?

**Comment by igormatos** [comment]
@alemens did you find how to improve the performance?

**Comment by OleksiiBrylin** [comment]
@alemens , @dotcypress do you have any news about this question?

**Comment by molavec** [comment]
Hi.

I tried with node and directly, but nothing works for me.  

[@Zizheng](https://stackoverflow.com/users/8630453/zizheng) give me a solution without express. Thanks to him.

Maybe, "double path" (firebase function name and express path) should be the problem cause, but it's an idea that I didin't verify yet.

```
delete
bot.launch()

try add this
exports.YOURFUNCTIONNAME = functions.https.onRequest(
  (req, res) => bot.handleUpdate(req.body, res)
)
then set ur webhook manually

https://api.telegram.org/bot{BOTTOKEN}/setWebhook?url={FIREBASE FUCNTION URL}' 
```

You can see it in [stackoverflow](https://stackoverflow.com/questions/58731075/how-to-use-telegraf-telegram-in-firebase/58764487#58764487).

**Comment by a-syafiq** [comment]
Any update on fixing this?

**Comment by Gloix** [comment]
I was trying to follow the expressjs way of binding Telegraf:

```typescript
app.use(bot.webhookCallback(`/${localconf.webhookToken}`))
```
but the request body was not being read properly, as it was trying to stream it, when the json object was already available under `req.body`.

Then used the approach of setting one's handler function for the request and handled the case when no answer is available, ending up with this working code:

``` typescript
const bot = new Telegraf(localconf.telegramToken);
bot.hears('hi', (ctx: ContextMessageUpdate) => ctx.reply('Hey there'))

export const helloBot = functions.https.onRequest((req, res) => {

  const callToken = req.path.substr(1);

  if ( callToken === localconf.webhookToken ) {
    return bot.handleUpdate(req.body, res).then(() => {
        if (!res.finished) {
            res.end();
        }
    })
  } else {
    res.sendStatus(403);
    return Promise.resolve();
  }
});
```

**Comment by shauntrennery** [comment]
@Gloix I'm seeing similar issues keeping my bot hosted on Firebase Functions awake. Did your solution above do the trick for you?

**Comment by ginfante-entel** [comment]
Do your functions trigger but give an empty response? That should only happen if none of the rules given to the bot match the incoming update message.

By "awake" do you mean "constantly running"? Using the `launch` method does that, but you absolutely should avoid it, as Firebase functions are not meant to be long-running.

Try doing some console logging to see if the function gets triggered. What is the returned http code?

**Comment by Gloix** [comment]
@shauntrennery Do your functions trigger but give an empty response? That should only happen if none of the rules given to the bot match the incoming update message.

By "awake" do you mean "constantly running"? Using the launch method does that, but you absolutely should avoid it, as Firebase functions are not meant to be long-running.

Try doing some console logging to see if the function gets triggered. What is the returned http code?

**Comment by shauntrennery** [comment]
@Gloix thank you for the quick response. My issue must be related to the use of launch. I’ll follow your advice and remove it as well as add additional console logs. Thank you again.

**Comment by shauntrennery** [comment]
@Gloix Just a quick update on my findings. I've migrated my app over to GAE. All my previous issues resolved and performance is way better.

**Comment by KnorpelSenf** [comment]
This looks like it is not an issue of `telegraf`.

(Btw, I have never had a performance issue with GAE either.)
