### ISSUE TITLE
Inline menu build 

### ISSUE THREAD

**Issue by AyoPrez** [telegraf/telegraf#557]
I have been looking for how to build an inline menu with different options in the documentation, but I couldn't find nothing. Would be great to include some example of how to do it.

**Comment by ejnshtein** [comment]
Maybe this can help: [https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js)

**Comment by Khuzha** [comment]
```ctx.reply('text', {reply_markup: {inline_keyboard: [[{text: 'first button in first line', url: 'url'}, {text: 'second button in first line', url: 'url'}, ...], [{text: 'first button in second line', callback_action: 'action'}, [...]] }})
```
etc.
