### ISSUE TITLE
Emitting events

### ISSUE THREAD

**Issue by Immortalizd** [telegraf/telegraf#558]
**Is your feature request related to a problem? Please describe.**
I am trying to make a bot that relays messages to Discord and vice versa. In discord.js, they use the native node module `events`, which makes emitting events very easy, and upon inspection, the closest thing I could find was `mount()` in the composer.js file, but I don't know how to access it.

**Describe the solution you'd like**
I want an easy way to emit events, so that I can do `client.emit("foo", foo);` and look for the event with `client.on("foo", bar => bar.baz);`

**Describe alternatives you've considered**
I have tried looking in the source code for alternatives to the event emitter I'm used to, and found something that looked promising (the `mount()` function in composer.js), but can't find a way to call it.

**Comment by Immortalizd** [comment]
Can someone let me know if this is possible to do and if not, if it will be implemented? I can't really wait forever with this. Thanks.

**Comment by ejnshtein** [comment]
Maybe you need `Composer.on()` method? It will mount your update types from telegram server with your middleware functions. [Composer.on()](https://github.com/telegraf/telegraf/blob/6a160842a8120d22b915364a30987a0fed399166/composer.js#L13)
OR you need just a local event emitter?

**Comment by Immortalizd** [comment]
I only need a local event emitter

**Comment by ejnshtein** [comment]
Here's event emitter module documentation, i think it can help you: https://nodejs.org/dist/latest-v10.x/docs/api/events.html
