### ISSUE TITLE
Bad Request: QUERY_ID_INVALID for inline-bot.js 

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#56]
Steps to reproduce:

1. Create inline bot
1. Try to use the bot without init the script, example: `@usernamebot request`
1. Run `node inline-bot.js `

```
Failed to process updates. { Error: 400: Bad Request: QUERY_ID_INVALID
    at buildPayload.then.then.then.then (\node_modules\telegraf\lib\network\client.js:99:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 400,
  description: 'Bad Request: QUERY_ID_INVALID',
  retryAfter: undefined,
  migrateToChaId: undefined }
```

**Comment by dotcypress** [comment]
@ajsb85 could you provide minimal implementation to reproduce this issue?

**Comment by ajsb85** [comment]
Use this example:
https://github.com/telegraf/telegraf/blob/develop/examples/inline-bot.js

Make a inline request with the process down. 
Keep the data in the field example: @inlinebot data (Maybe the user put this information as draft)
Run the bot.

**Comment by dotcypress** [comment]
It happen cause QUERY_ID is temporary. 

You might add [custom error handling](http://telegraf.js.org/introduction.html#error-handling) for this case:

```js
app.catch((err) => {
  console.log('Error', err)
})
```
