### ISSUE TITLE
Possible to let bot send text message after callback query?

### ISSUE THREAD

**Issue by Samleo8** [telegraf/telegraf#562]
I've created a trivia bot which sends text messages and hints. I want to have an inline "Hint" button that posts the next hint after it is pressed.

However, it seems that I cannot send a text message from the callback context as such:

```
bot.action('hint_callback', (ctx) => {
    ctx.reply("HINT!"); //doesn't work
    nextHint(ctx); //sends hint messages. doesn't work
}
```

I recognise that it might be something to do with the context type being different for callbacks, so is there an alternative like:

```
bot.action('hint_callback', (ctx) => {
    ctx2 = bot.context;
    ctx2.reply("HINT!"); //doesn't work
    nextHint(ctx2); //sends hint messages. doesn't work
}
```

I've tried this but it doesn't work.

**Comment by Khuzha** [comment]
Have you tried .sendMessage()?
For example:

`bot.telegram.sendMessage(ctx.update.callback_query.from.id, 'hi')`

**Comment by Khuzha** [comment]
Also don't forget to check where you're answering. It could be callback from any chat or channel (if bot supports that). 

Method I've described works only in private.
