### ISSUE TITLE
.hears just pull the command once

### ISSUE THREAD

**Issue by devofthings** [telegraf/telegraf#565]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.25.0
* Node.js Version: 10.13.0
* Operating System: Manjaro / Android 

## Expected Behavior
To add multilanguage support. I expect that the hear functions access the correct Strings out of an json file.

This is the code:
```
Session.lang = 'en';

const setLanguage = (language) => {
  Session.lang = language;
  return Session.lang;
}

Bot.hears(Strings[Session.lang].MAIN, ctx => ctx.reply(roll(ctx)))

```

## Current Behavior
Actual only the 'en' Strings will load. Although the Session variable is set to another language..

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Activate @NicerDicerDev
2. Select english 
3. Go in the settings and change the language to german
4. Now the bot does not accept the german input but the english commands still work.

**Comment by tva10** [comment]
@saiij 

In that small case, first, you use one global session variable to keep lang name, but you need to have this varible for each user...

Second, you make one `hears` subscription only for english locale. And I think you need run `hears` subscription for each locale, or pass array of strings
```javascript
Bot.hears( [Strings['en'].MAIN, Strings['de'].MAIN], ctx => ctx.reply(roll(ctx)))
```

check this helpful links:
[hears method](https://telegraf.js.org/#/?id=hears)
[simple per user session](https://telegraf.js.org/#/?id=session)
[internationalization lib](https://github.com/telegraf/telegraf-i18n)
