### ISSUE TITLE
Is it possible to know when a user has viewed the bot?

### ISSUE THREAD

**Issue by jlei523** [telegraf/telegraf#569]
I would like to know when a user of my bot opens my bot in Telegram. This is valuable to me because I want to track how engaging my bot is over time so I know if I'm improving it.

## Context

* Telegraf.js Version: Latest
* Node.js Version: Latest
* Operating System: MacOS

**Comment by Khuzha** [comment]
You can only track when users use your bot, but when open bot`s profile - can`t.
