### ISSUE TITLE
post inline keyboards and remove old keyboards ( not inline ) in same time

### ISSUE THREAD

**Issue by Zoha** [telegraf/telegraf#572]
hi.
thanks for this amazing package.
I have a question . how can I send inline keyboards and in same time remove keyboards ( not inline )
I tried the fallowing, but they do not work : 
```
ctx.reply(message, Extra.markup(m => {
    return m.removeKeyboard();
}).markup(m => {
    return m.inlineKeyboard([
        m.callbackButton(messages.buttons.contact, "contact")
    ]);
})
```
```
ctx.reply(message, Extra.markup(m => {
    m.removeKeyboard();
    return m.inlineKeyboard([
        m.callbackButton(messages.buttons.contact, "contact")
    ])
})
```

```
ctx.reply(message, Extra.markup(m => {
    return m..removeKeyboard().inlineKeyboard([
        m.callbackButton(messages.buttons.contact, "contact")
    ])
})
```
and some other ... 
can you help me ?

**Comment by Shoyadbek** [comment]
You can send two message first for remove keyboard:

`ctx.reply(message, reply_markup: { remove_keyboard: true})`

And send new message with new buttons. 

For quaque use async/await function

**Comment by Zoha** [comment]
honestly, I had already found out what the problem was. but I forgot to share here.
Telegram website has been blocked in my country and that's why my code does not work properly. perhaps this problem can be solved with a proxy, but I can not try it right now. I will try it later
thanks @Shoyadbek

**Comment by dmred** [comment]
> honestly, I had already found out what the problem was. but I forgot to share here.
> Telegram website has been blocked in my country and that's why my code does not work properly. perhaps this problem can be solved with a proxy, but I can not try it right now. I will try it later
> thanks @Shoyadbek

do you find the sollution? your examples up dont remove the keyboard

**Comment by sheykh** [comment]
@Zoha Ok i hope it works with proxy

**Comment by weihan1394** [comment]
I tried the above methods, it doesn't remove the keyboard too.

**Comment by M1Ergash** [comment]
Same didnt help(
