### ISSUE TITLE
Server down when use getUserProfilePhotos()

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#573]
## Context
I am using telegraf.js for more than 3 bots which run very well in plenty of groups. 
Currently one of the bot needs to request for Display Picture the user who does not have display picture.

It works very well as expected but very unfortunately the bot getting error and  server become down 😔

## Current Code

```
// Request for display picture
const requestDP = async  (ctx, next) => {
  const { from, chat } = ctx.message;
  const { can_delete_messages:canDelete } = await deletePermision(ctx);

  let totalDPs = 1;
  totalDPs = await ctx.telegram.getUserProfilePhotos(ctx.message.from.id)
  .then((result) => result.total_count)
  .catch((err) => {
    console.log(err);
  });
  
  if (totalDPs != 0) return next();
  
  if ((chat.id === -1001341734527 || chat.id === -1001083711103 ) && canDelete) {
    await ctx.deleteMessage().then((response) => response, ({ response }) => response.ok);
    
    await ctx.replyWithMarkdown(`[${from.first_name||''} ${from.last_name||''}](tg://user?id=${from.id}), പ്രൊഫൈൽ ഫോട്ടോ ഇല്ലാത്തവർക്ക് ഗ്രൂപിൽ മെസേജ് അയക്കാൻ സാധ്യമല്ല`)
    .then(({ message_id }) => setTimeout(() => ctx.deleteMessage(message_id), 5 * 60 * 1000))
    .catch((err) => console.log("Error in prevencontacts: " + err));
  }
}

module.exports = requestDP;
```

## Failure Information (for bugs)
```
let totalDPs = 1;
totalDPs = await ctx.telegram.getUserProfilePhotos(ctx.message.from.id)
.then((result) => result.total_count)
.catch((err) => {
  console.log(err);
});
```
The functions seems to be working unfortunately  sometimes getting error and server become down
Error message 👇

`Error: 400: Bad Request: request for new profile photos has already been sent`
It is really hard to refresh the server occasionally :-(  
Is there any solution to manage this error ?

**Comment by 2naive** [comment]
@dotcypress I've got the same error message sometimes even with caching profile photos results.
If you have any ideas -> would be great
