### ISSUE TITLE
Failed to process updates

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#574]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: v3.25.5
* Node.js Version: v11.4.0
* Operating System: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

```console
Failed to process updates. { Error: 409: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
    at buildConfig.then.then.then.then (/.../node_modules/telegraf/core/network/client.js:263:17)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      "Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first" },
  description:
   "Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first",
  parameters: {},
  on:
   { method: 'getUpdates?offset=0&limit=100&timeout=30',
     payload: {} } }
```

**Comment by tva10** [comment]
Hello @ajsb85 

If you are used webhook on your bot before and want to run bot in polling mode you need to delete webhook first

Try to use [deleteWebhook()](https://telegraf.js.org/#/?id=deletewebhook) or [setWebhook()](https://telegraf.js.org/#/?id=setwebhook) with empty params before your `startPolling()` call

```javascript
bot.telegram.deleteWebhook()
    .then( () => bot.startPolling( /*...*/ ) );
```

**Comment by wisepotato** [comment]
This does not work. When implemented i get thte same error.

```json
Failed to process updates. { Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at buildConfig.then.then.then.then (x\client.js:263:17)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' },
  description:
   'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on:
   { method: 'getUpdates?offset=0&limit=100&timeout=30',
     payload: {} } }
```

**Comment by tva10** [comment]
Hello @wisepotato
Do you have only one instance of bot running? Is there only one call of `startPolling()` in code?

Now you can use `bot.launch()` [method](https://telegraf.js.org/#/?id=launch) instead of `deleteWebhook` & `startPolling`. Please, check examples in docs folder

**Comment by wisepotato** [comment]
My bot was registered via inversify and was instanced twice...
