### ISSUE TITLE
Error when send a message using reply method

### ISSUE THREAD

**Issue by tcelestino** [telegraf/telegraf#577]
When I'm using `reply` method to interact with Telegram, I've seen this message:

> Method: messages.sendMessage
> Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}

I looking for about it and it seems be a problem with `chat.id` value. Is there a solution about that?

**Comment by ejnshtein** [comment]
Do you understand what is written in the `error_message` field?

**Comment by tcelestino** [comment]
> Do you understand what is written in the `error_message` field?

Yes, I do. But I thankfully to you for alert me about that messages.

**Comment by ejnshtein** [comment]
I am glad to help
