### ISSUE TITLE
Misleading function name

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#580]
## Context
* Telegraf.js Version: ^3.25.5
* Node.js Version: v11.6.0
* Operating System: Linux 4.0 or up, macOS 10.14.2

## Expected Behavior
using this code:
```
ctx.reply(`Hello world message: ${ctx.message.text}`)
``` 
would be equalivant to:
```
ctx.telegram.sendMessage(ctx.message.chat.id, `Hello world message: ${ctx.message.text}`, {'reply_to_message_id': ctx.message.message_id})
```

## Current Behavior

It simply sends a message to the originating chat id, neither it is replying to the inbound message, nor it is literally doing any reply. It just SEND a message.

### Steps to Reproduce

```
const Telegraf = require('telegraf')
const bot = new Telegraf(process.env.BOT_TOKEN)

// On receiving text messages
bot.on(['message', 'edited_message'], ctx => {
  ctx.reply(`Hello world message: ${ctx.message.text}`)
})
```

**Comment by lifehome** [comment]
I have not checked on other method calls prefixed with `reply`, but I guess they just sends the message away instead of "replying".

**Comment by dotcypress** [comment]
@lifehome we using `reply*` patter because we `replying` to Telegram updates, not messages itself.

**Comment by lifehome** [comment]
@dotcypress Can you recommend a method to reply to a message?
