### ISSUE TITLE
sendVideo failed, reason: socket hang up

### ISSUE THREAD

**Issue by bongiozzo** [telegraf/telegraf#581]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.26.0
* Node.js Version: v10.15.0
* Operating System: Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

## Expected Behavior

I'd like to send short video from bot to user.
It worked some time ago using bot with connection through HTTP proxy (due to Russiam limitations), but now, with SOCKS5 proxy it doesn't.

const Telegraf = require('telegraf');
const SocksAgent = require('socks5-https-client/lib/Agent');
const socksAgent = new SocksAgent({
  socksHost: 'host',
  socksPort: port,
  socksUsername: 'user',
  socksPassword: 'password',
});
const bot = new Telegraf('token', {
  telegram: { agent: socksAgent }
});

bot.use((ctx, nxt) => {
  const start = new Date();
  if (ctx.message && ctx.message.text)
    logger.log('info', 'Access ', ctx.from.username, ' with a command ', ctx.message.text);
  if (people.includes(ctx.from.username))
    return nxt(ctx).then(() => {
      const ms = new Date() - start
      logger.log('info', 'Response time %sms', ms)
    })
})

bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.command('video', (ctx) => {
      ctx.replyWithVideo({ source: file });
      logger.log('info', 'video - %s', file );
}

### Failure Logs

Please include any relevant log snippets or files here.

Bot works Ok for text messages, but keeps silent for for stickers.

In Telegram:

hi
   Hey there
😐
   Silent
/video
   Silent

In console:

info: Access  {"meta":["USER"," with a command ","hi"]}
info: Response time 640ms
info: Access  {"meta":["USER"," with a command ","😐"]}
info: Response time 2ms
info: Access  {"meta":["USER"," with a command ","/video"]}
info: video - 11-01-2019__13-33-10.mp4
info: Response time 166ms

(node:8453) UnhandledPromiseRejectionWarning: FetchError: request to https://api.telegram.org/botTOKEN/sendVideo failed, reason: socket hang up
    at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:187:15)
    at Socks5ClientSocket.socketOnEnd (_http_client.js:426:9)
    at Socks5ClientSocket.emit (events.js:187:15)
    at TLSSocket.<anonymous> (/home/pi/node_modules/socks5-client/lib/Socket.js:146:8)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tva10** [comment]
@bongiozzo Hello!
Revoke your bot token pls if you did not it yet

About socket hang up error. Does it happens with other `send"File"` actions? What is the size of the file?
Mb this is problem due to proxy using - ref #63

**Comment by bongiozzo** [comment]
> Revoke your bot token pls if you did not it yet
Revoked - thank you so much! :) Din't mention it in logs.

> Does it happens with other `send"File"` actions?
It happens for stickers and video at least. So Yes.

> What is the size of the file?
-rwxrwxrwx 1 pi pi 712034 Jan 11 13:44 11-01-2019__13-44-39.mp4
Less than 1Mb

**Comment by bongiozzo** [comment]
> Mb this is problem due to proxy using - ref #63

Actually I used code sample from this thread:

I done it!
Let's document the snippet for e.g. all russian users under the government's internet blocking:

const Telegraf = require('telegraf');
const SocksAgent = require('socks5-https-client/lib/Agent');
const socksAgent = new SocksAgent({
  socksHost: config.proxy.host,
  socksPort: config.proxy.port,
  socksUsername: config.proxy.login,
  socksPassword: config.proxy.psswd,
});

const app = new Telegraf(token, {
  telegram: { agent: socksAgent }
});

And it works for simple message.

**Comment by bongiozzo** [comment]
Proxy logs are absolutely Ok. No error. For multipart/form-data requests there are several info entries with no errors.

I don't have other working proxies :/

**Comment by bongiozzo** [comment]
> And I would also try to send already readed file as Buffer
> [working-with-files](https://telegraf.js.org/#/?id=working-with-files)

The same result

**Comment by tva10** [comment]
> I don't have other working proxies :/

proxyme? tgvpnbot? there are public in telegram and also has socks5. But after test I would change the token.
Another way is [ssh tunnel](https://www.opennet.ru/tips/1691_ssh_tunnel_socks.shtml)
After `ssh -D 5555 user@remotehost -f -N` proxy will be avilable on localhost:5555

If it does not work, then I will try to reproduce it in the evening.

**Comment by bongiozzo** [comment]
> Another way is [ssh tunnel](https://www.opennet.ru/tips/1691_ssh_tunnel_socks.shtml)
> After `ssh -D 5555 user@remotehost -f -N` proxy will be avilable on localhost:5555

Thank you! It's much better than SOCKS5 service. SSH tunnel is tested. The same problem. Works fine with simple message and doesn't work for sending files.

It seems that problem in socks5-https-client module.
Because SOCKS5 proxy works Ok with Windows client and bot worked Ok with https-proxy-agent module.

**Comment by tva10** [comment]
Hello! @bongiozzo 
Sorry for the delay, think that issue is ended

Yep checked on my provider - using ssh tunnel
`socks5-https-client` does not work

Upd
But after search another npm package - `socks-proxy-agent` - and using it, then example works fine
```javascript
const SocksProxyAgent = require('socks-proxy-agent');
const socksAgent = new SocksProxyAgent('socks://127.0.0.1:5555');
```

**Comment by bongiozzo** [comment]
Thank you!
But with this module there are other troubles - with authentication :)

So I'm tired of this proxy/socks problems - going to build vpn tunnel from server or router and keep code clean.

Thank you once again :)

**Comment by tva10** [comment]
Hmm, with authentication works fine to for me. Public socks5 server was used
eg: `'socks://user:pass@ip:port'`
