### ISSUE TITLE
[Seeking Advice]  Manage Routing with callBackButton with Telegraf and Typescript 

### ISSUE THREAD

**Issue by robincher** [telegraf/telegraf#585]
Hi folks,

OS : macOS Moave
Node version : Node 10.14.x LTS
TypeScript : 3.2.2
Telegraf : 3.26.0

First of all, thanks for managing this awesome library :).

I am a new user starting my first both with Telegraf + Typescript, and would like to check how i can do proper routing to different scene (something like route.js in nodejs)? 

 For example, i am present with these options : 

<img width="853" alt="screenshot 2019-01-15 at 4 11 30 pm" src="https://user-images.githubusercontent.com/328109/51167009-4cb23880-18e0-11e9-8914-a4a7418f8f08.png">

**_Code snippets_**

```
  Tools.replyInlineKeyboard(ctx, `Hi! What you planning to do with your survey?`, [
            Markup.callbackButton(' Add a survey', 'ADD_SURVEY'),
            Markup.callbackButton('Update a survey', 'UPDATE_SURVEY'),
            Markup.callbackButton(' Delete a survey', 'DELETE_SURVEY'),
        ]);
```

Upon clicking the button, how can i be 'redirected' to a new scene based on the action i selected?'

**_My existing code :_** 

```
bot.on('callback_query', (ctx) => {
       const surveyAction = ctx.update.callback_query.data;
       switch (surveyAction) {
                   case 'ADD_SURVEY':
                            console.log('Inside Add_Survey Switch');
                            return surveyTalent.addSurvey(ctx);
                            break;
                  case 'UPDATE_SURVEY':
                            console.log('Inside Update_Survey Switch');
                            break;
                  case 'DELETE_SURVEY':
                           console.log('Inside Delete_Survey Switch');
                           break;
                   default:
                           break;
          }
}
```

An example is the Youtube bot, where after clicking **All my subscriptions**, i be redirected to another scene where i am prompted to **Connect my account**.

<img width="963" alt="screenshot 2019-01-15 at 4 24 42 pm" src="https://user-images.githubusercontent.com/328109/51167735-3f964900-18e2-11e9-9d7b-707c78b9562a.png">

Are there any features that i can look deeper into? Composer? Router?

Thanks!

**Comment by EdJoPaTo** [comment]
Maybe take a look at my [inline-menu](https://github.com/EdJoPaTo/telegraf-inline-menu) library. 
It has no typescript support (I am thinking about a typescript rewrite) and has some issues but its a good start I think.

**Comment by robincher** [comment]
@EdJoPaTo thanks, i take a look. As of now ,i just traverse using context commands instead for my MVP.
