### ISSUE TITLE
Replace node-fetch with slim-fetch

### ISSUE THREAD

**Issue by cktang88** [telegraf/telegraf#586]
**Is your feature request related to a problem? Please describe.**

node-fetch is larger size than it should be, slim-fetch is much lighter with identical implementation and API.

**Describe the solution you'd like**
Replace node-fetch with slim-fetch.
https://www.npmjs.com/package/slim-fetch is a new library that has basically identical code to node-fetch, but stripped away unnecessary parts of the distribution (eg. node-fetch actually has three copies of the same code for backwards compatibility purposes).

**Describe alternatives you've considered**

**Additional context**

**Comment by dotcypress** [comment]
@cktang88 Thank you for proposition, but I'm afraid we can't do that. Seems like `slim-fetch` don't have any developers community around it and switching now is unnecessary risk.
