### ISSUE TITLE
[Typescripts] Property 'options' does not exist on type 'Telegraf<ContextMessageUpdate>'.

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [telegraf/telegraf#587]
## Context

* Telegraf.js Version: 3.25.5
* telegram-typings Version: 3.6.1
* Node.js Version: v8.11.2
* Operating System: win10

## Expected Behavior

in the offical document https://telegraf.js.org/#/?id=recipes
it say, i  can get the username from Telegram server.

```ts
const bot = new Telegraf(process.env.BOT_TOKEN)

bot.telegram.getMe().then((botInfo) => {
  bot.options.username = botInfo.username
})

bot.command('foo', (ctx) => ctx.reply('Hello World'))
```

## Current Behavior

if i import and use the Telegraf bot like follow, it work well:
```ts
const Telegraf = require("telegraf");
const bot = new Telegraf(process.env.BOT_TOKEN);
bot.telegram.getMe().then((botInfo) => {
    bot.options.username = botInfo.username;
});
```

but if i import it use typescript style, like follow:
```ts
import {Telegraf, ContextMessageUpdate} from "telegraf";
const bot: Telegraf<ContextMessageUpdate> = new Telegraf(process.env.BOT_TOKEN);
bot.telegram.getMe().then((botInfo) => {
    bot.options.username = botInfo.username;  // <--- this line: Error
});
```

the typescript tell me 
```Error:(30, 9) TS2339: Property 'options' does not exist on type 'Telegraf<ContextMessageUpdate>'.```

<hr/>

And i look-over all the types, it only defind it on ```TelegrafOptions``` , and the ```TelegrafOptions``` only be used in ```TelegrafConstructor```.

```ts
export interface TelegrafOptions {

  telegram?: TelegramOptions

  username?: string
}
```

```ts
export interface TelegrafConstructor {
  new <TContext extends ContextMessageUpdate>(token: string, options?: TelegrafOptions): Telegraf<TContext>;
}
```

but cannot find the TelegrafOptions on the Telegraf :

```ts

export interface Telegraf<TContext extends ContextMessageUpdate> extends Composer<TContext> {

  token: string
  webhookReply: boolean
  telegram: Telegram
  context: TContext

  startPolling(timeout?: number, limit?: number, allowedUpdates?: tt.UpdateType[]): Telegraf<TContext>
  startWebhook(webhookPath: string, tlsOptions: TlsOptions | null, port: number, host?: string): Telegraf<TContext>
  stop(): Telegraf<TContext>
  webhookCallback(webhookPath: string): (req: IncomingMessage, res: ServerResponse) => void
  handleUpdate(rawUpdate: tt.Update, webhookResponse?: ServerResponse): Promise<any>
  catch(logFn?: Function): void;
}
```
And i look the file ```\node_modules\telegraf\telegraf.js``` , it be set as the ```Telegraf``` class menber, like follow:
```javascript

class Telegraf extends Composer {
  constructor (token, options) {
    super()
    this.options = Object.assign({}, DefaultOptions, options)        //  <--------- this
    this.token = token
    this.handleError = (err) => {
      console.error()
      console.error((err.stack || err.toString()).replace(/^/gm, '  '))
      console.error()
      throw err
    }
    this.context = {}
    this.polling = {
      offset: 0,
      started: false
    }
  }
 // ............. many other
```

<hr/>

so, i think the types of Telegraf lost something.

**Comment by Lyoko-Jeremie** [comment]
and, i find that

this can work
```ts
import {Telegraf, ContextMessageUpdate} from "telegraf";
const bot = new (require("telegraf"))(process.env.BOT_TOKEN);
```

but this cannot work
```ts
import {Telegraf, ContextMessageUpdate} from "telegraf";
const bot: Telegraf<ContextMessageUpdate> = new Telegraf(process.env.BOT_TOKEN);
```

Emmmm....... something wrong ???

**Comment by ozeemandias** [comment]
@Lyoko-Jeremie 

try this
```ts
import Telegraf, { ContextMessageUpdate } from "telegraf";
const bot: Telegraf<ContextMessageUpdate> = new Telegraf(process.env.BOT_TOKEN);
```

**Comment by Lyoko-Jeremie** [comment]
@ozeemandias thanks for your help.
but the ```bot.options``` still not work . same error .

i think it need add something to the types to resolve it.

**Comment by EdJoPaTo** [comment]
While investigating this I found out when using `bot.launch()` `options.username` is set. `bot.startWebhook()` and `bot.startPolling()` are not doing this.

@dotcypress Maybe deprecate the other two methods? Everyone should always use `bot.launch()`?

When this is getting the same on every kind of start I can check on typings again. so they actually are the same as the code does.
