### ISSUE TITLE
How to catch unhandledRejection?

### ISSUE THREAD

**Issue by londonxxx** [telegraf/telegraf#589]
## Context

I have a simple event where the bot is listening for a command and retrieves a list of Twitter usernames from a file:

```
bot.hears('!twitter', (ctx) => {
	console.log("!twitter called.");
	ctx.deleteMessage();

	ctx.replyWithHTML("some strings from a file..", {
		disable_web_page_preview: true
	}).then(({
		message_id
	}) => {
		setTimeout(() => {
			ctx.deleteMessage(message_id);
			console.log("Twitter message " + message_id + " was deleted.");
		}, 21600000);
	});

});

```

* Telegraf.js Version: 3.22.2
* Node.js Version: v8.11.3
* Operating System: Linux localhost 4.15.0-29-generic #31-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior

Twitter usernames retrieved without any errors.

## Current Behavior

The list with Twitter accounts is being retrieved but there's an error in the console:

```
4|twitterrobot  | !twitter called.
4|twitterrobot  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
4|twitterrobot  | Error: 400: Bad Request: message can't be deleted
4|twitterrobot  |     at buildConfig.then.then.then.then (/home/matt/node_modules/telegraf/core/network/client.js:254:17)
4|twitterrobot  |     at <anonymous>
4|twitterrobot  |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
or

```
4|twitterrobot  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```
I know Telegraf massively uses Promises, but I don't know how to catch one given the snippet above.

Lastly, is that error purely informative, just to tell me I won't catch eventual errors or are there actual errors?

**Comment by Shoyadbek** [comment]
You can write on general file

`process.on ('unhandledRejection', e => {
  console.log (e);
});
process.on ('uncaughtException', e => {
  console.log (e);
});
process.on ('rejectionHandled', event => {
  console.log (event);
});`
