### ISSUE TITLE
Can API read and write memberID permissions?

### ISSUE THREAD

**Issue by 1blockologist** [telegraf/telegraf#594]
It wasn't clear from the documentation if the API can set a user's ability to send a message or send gifs and things like that.

I would like to pull a whole list of users in a supergroup where my bot is admin and set particular permissions conditionally

**Comment by EdJoPaTo** [comment]
As of now that is not currently possible with the current Bot API: [Recent Changes](https://core.telegram.org/bots/api#recent-changes)

Group Permissions are added on [22 Jan 2019](https://telegram.org/blog/permissions-groups-undo) while Bot API version 4.1 is from Aug 2018.

Currently there are only [`restrictChatMember`](
https://core.telegram.org/bots/api#restrictchatmember) and [`promoteChatMember`](
https://core.telegram.org/bots/api#promotechatmember) for setting and [`getChatMember`](https://core.telegram.org/bots/api#getchatmember) for reading that information currently available.

I assume there will be a Bot API update soon.

**Comment by prototypeV8** [comment]
> It wasn't clear from the documentation if the API can set a user's ability to send a message or send gifs and things like that.
> 
> I would like to pull a whole list of users in a supergroup where my bot is admin and set particular permissions conditionally

You can set user permissions using `restrictChatMember()` and [options](https://core.telegram.org/bots/api#restrictchatmember). You could loop through all members and set the permissions according to your conditions. Telegram might add more granular options soon though if you need more control.

```javascript
const options = {
  can_send_messages: true, // text messages, contacts, locations and venues
  can_send_media_messages: true, // audios, documents, photos, videos, video notes and voice notes, implies can_send_messages
  can_send_other_messages: true, // animations, games, stickers and use inline bots, implies can_send_media_messages
  can_add_web_page_previews = true // web page previews to messages, implies can_send_media_messages
}

telegram.restrictChatMember(chatId, userId, options);
```
