### ISSUE TITLE
send photo using binary from request

### ISSUE THREAD

**Issue by RaminMT** [telegraf/telegraf#595]
Hi
I was wondering is there any way to send photo (replyWithPhoto) using binary came from request?
I send a request and as response I have the binary of photo I tried to send the photo using that but seems It's not working/possible? Is it true?

**Comment by prototypeV8** [comment]
You can send a (binary) file like this: 
`ctx.replyWithPhoto({ source: fs.createReadStream('filePath')})`

Just make sure that your binary is converted into a file that is accepted by telegram (.jpg and .png works for sure).

**Comment by RaminMT** [comment]
That's not what I was seeking for, also it seems that's not possible, so I made my trick
But thanks anyway

**Comment by dotcypress** [comment]
@RaminMT yes you can send stream as @prototypeV8 shows, also you can pipe any http(s) content:
```js
bot.command('pipe', (ctx) => ctx.replyWithPhoto({ url: 'photo url' }))
```

**Comment by RaminMT** [comment]
@dotcypress 
Thank you, none of these two solutions worked for me.
I upload an image & the api responses with a binary data of same image. currently I'm using tmp, creating an image in temp with the binary data, then send temp image, then remove! done!
I was looking for a way to not use tmp, and pass the binary data received as argument.

**Comment by dotcypress** [comment]
@RaminMT bot.command('upload', (ctx) => ctx.replyWithPhoto({ source: BUFFER_WITH BINARY_DATA }))
