### ISSUE TITLE
Pressing callbackButton in stage multiple time triggering next stage; Working with Wizard

### ISSUE THREAD

**Issue by yourmummy** [telegraf/telegraf#597]
If you take a look in example with Wizard: 
```javascript
const superWizard = new WizardScene('super-wizard',
  (ctx) => {
    ctx.reply('Step 1', Markup.inlineKeyboard([
      Markup.urlButton('❤️', 'http://telegraf.js.org'),
      Markup.callbackButton('➡️ Next', 'next')
    ]).extra())
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Step 2')
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Done')
    return ctx.wizard.leave()
  }
)

const stage = new Stage([superWizard])
bot.use(session())
bot.use(stage.middleware())
bot.hears('foo', Stage.enter('super-wizard'));
```

you'll see that if we tap Next button from step 1 multiple times, this will take you to the step 2, step 3, etc.
In other words, if you have callbackButton in each of wizard steps, pressing one of this buttons multiple times will broke your bot logic with data manipulation in following steps. 

How to avoid this? This is real User Experience which I saw with my own eyes.

P.s. Also, if user goes through steps and in some moment run /foo command that must start Wizard again - nothing happens. User must type again /foo to run Wizard.

![Image](http://funkyimg.com/i/2R2QT.png)

**Comment by robverhoef** [comment]
Exactly this issue is what stopped me from using callbackButtons. 
Not an ideal solution; but switching to keyboards (with oneTime()) made things  a lot more reliable. One big disadvantage of this method is that you will have to scan for the label text of your keys to determine what the user wants. Which is not great when using multi-language bots.

**Comment by dotcypress** [comment]
@yourmummy it will be much easier to use simple Scenes for every step.
