### ISSUE TITLE
EditMediaMessage TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by prototypeV8** [telegraf/telegraf#599]
I am sending a _file.mp3_ via `ctx.replyWithAudio()`. This works.
I am trying to edit the media content of that message via `telegram.editMessageMedia()`, but I only get `TypeError: Cannot convert undefined or null to object`. 

```javascript
const msg = await ctx.replyWithAudio({source: "file.mp3"});
telegram.editMessageMedia(chatId, msg.message_id, {type: "audio", media: "anotherFile.mp3"});
```

The [media bot example](https://github.com/telegraf/telegraf/blob/master/docs/examples/media-bot.js) only shows how to swap media with a new url. Isn't it possible to replace the content with newly uploaded files? According to the telegram bot api it is [not possible for inline messages](https://core.telegram.org/bots/api#editmessagemedia), but it should work with normal messages then?  

I also tried it with a _file_id_ with the same error: 
```javascript
telegram.editMessageMedia(chatId, msg.message_id, {type: "audio", media: "file_id"});
```

**Comment by dotcypress** [comment]
@prototypeV8  you must provide inline message id anyway for `editMessageMedia`, even if you don't have one :)

```js
const msg = await ctx.replyWithAudio({source: "file.mp3"});
telegram.editMessageMedia(chatId, msg.message_id, undefined, {type: "audio", media: "anotherFile.mp3"});
```
