### ISSUE TITLE
keyboard does not work

### ISSUE THREAD

**Issue by orin220444** [telegraf/telegraf#604]
/node_modules/telegraf/markup.js:156
    return buttons.map(row => row.filter((button) => !button.hide))
                                  ^

TypeError: row.filter is not a function
    at buttons.map.row (/node_modules/telegraf/markup.js:156:35)

**Comment by code-by** [comment]
same problem (

**Comment by MKRhere** [comment]
@code-by Please create a new issue, and include your code and the error message you're getting.

**Comment by code-by** [comment]
Turned out there no separating comma between ['2'] and ['3'] 
```
Markup.keyboard([
['1'], ['2'],  // this comma was accidentally erased
['3']
]);
```
