### ISSUE TITLE
How to reply to a specific message?

### ISSUE THREAD

**Issue by francescomesianodev** [telegraf/telegraf#607]
How can I reply to a specific message?

**Comment by akeinhell** [comment]
`ctx.reply(response, Extra.inReplyTo(message_id));`

**Comment by mohammadreza** [comment]
And is there any way to reply to a specific message with also showing inline keyboard?

**Comment by ajoao88** [comment]
> 
> 
> And is there any way to reply to a specific message with also showing inline keyboard?

```js
Extra.inReplyTo(message_id).markup(Markup.inlineKeyboard([Markup.callbackButton('Sim', 'dados')]))
```

**Comment by Porkechebure** [comment]
> > And is there any way to reply to a specific message with also showing inline keyboard?
> 
> ```js
> Extra.inReplyTo(message_id).markup(Markup.inlineKeyboard([Markup.callbackButton('Sim', 'dados')]))
> ```

How to use that "Extra" thing?

**Comment by Rockbass** [comment]
> > > And is there any way to reply to a specific message with also showing inline keyboard?
> > 
> > 
> > ```js
> > Extra.inReplyTo(message_id).markup(Markup.inlineKeyboard([Markup.callbackButton('Sim', 'dados')]))
> > ```
> 
> How to use that "Extra" thing?

Have you figured that out?

**Comment by Porkechebure** [comment]
> > > > And is there any way to reply to a specific message with also showing inline keyboard?
> > > 
> > > 
> > > ```js
> > > Extra.inReplyTo(message_id).markup(Markup.inlineKeyboard([Markup.callbackButton('Sim', 'dados')]))
> > > ```
> > 
> > 
> > How to use that "Extra" thing?
> 
> Have you figured that out?

Yep. Apparently those things belong to the old v3 of the project and the current version is 4. The made it more intuitive but I don't think I've ever used it, but the authour should have transported all the "Extra" thing here:
[https://telegraf.js.org/modules/types.html#extrareplymessage](https://telegraf.js.org/modules/types.html#extrareplymessage)

So, in short it should be:
```
bot.command('links', async (ctx) => {
    ctx.reply("x", {reply_to_message_id : ctx.message.reply_to_message.message_id})
}
```

or something like that


Useless to mention that the author have no idea whatsoever on how to document things and I opened already 2 issues asking him to document the whole thing better.
What I've received in response is basically that the project is free and he is not obligated to document things.

Whatever
