### ISSUE TITLE
Bot added to channel

### ISSUE THREAD

**Issue by electic** [telegraf/telegraf#608]
I am using the latest version of Telegraf, and I can't seem to find any documentation pages on how to work with Chanenls.

1. I have a channel. 
2. I add the bot to the channel.

Question: How do I get a notice the bot has been added to the channel?

**Comment by EdJoPaTo** [comment]
Unlike in groups you don't get notified on being added to a channel. You only get channel_post for example when someone posts something.

**Comment by electic** [comment]
Got it, thanks :)
