### ISSUE TITLE
Support/Request: editMessageText documentation needed

### ISSUE THREAD

**Issue by grahamPegNetwork** [telegraf/telegraf#609]
Hello, I've been playing with Telegraf for a while and can't find enough details or examples of how to use editMessageText. I read through the Telegraf and Telegram docs but have not been able to get my issue sorted out.

I am working on a standard messaging bot (bot <==> user) and am sending messages via ctx.reply. I would like to edit those messages later on, but am unable to find the proper context/format. I am already passing the chat and message IDs back from the reply I'm sending.

Can I make a request for a simple example of a bot editing its own message sent via reply? 

I am looking for something along these lines:

`bot.on('message', (ctx) => {
  ctx.reply("hello world").then((msgInfo) => {
    bot.editMessageText(msgInfo.chat.id, msgInfo.message_id, "goodbye");
  });
`
(Format for that is probably wrong, I have tried several variations/contexts, consider it pseudocode)
In reality I would be passing the message ID and chat ID to a function which processes info, then use it to update the staus of a job for the user

Application/context:
I allow users to send links to my bot (ytdl-core stuff) which then downloads the media and does some processing. Currently my bot notifies when it starts downloading, then sends a second message upon completion. This is both noisy, and as the processes are async, a bit confusing matching multiple starts/completions up. My goal is to have a message that reads something like:
`Video: Title here\n
Status: Downloading`
Upon completion/processing, edit the message to read:
`Video: Title here\n
Status: Complete`

Thanks in advance for input!

**Comment by volodalexey** [comment]
If your bot received at least one message from user - you can send message to this user at any time later (exept case - when user deleted chat with your bot):
```
const tlgfBot = new Telegraf(...bot_token...);

tlgfBot.telegram.sendMessage(...chatId..., ...text...);
```

**Comment by yanislav-igonin** [comment]
@grahamPegNetwork same question, bro

```
bot.on('message', async (ctx) => {
  console.log('TCL: ctx', ctx.update.message.message_id);
  console.log('TCL: ctx', ctx.update.message.chat.username);
  // await redis.set(c)

  const msgInfo = await ctx.reply('WORK');
	console.log('TCL: msgInfo', msgInfo);

  setTimeout(() => {
    ctx.editMessageText(msgInfo.chat.id, msgInfo.message_id, 'PLEASE');
  }, 1000);
});
```

with piece doesn't work, still getting error `Error: Telegraf: "editMessageText" isn't available for "message::text"`, docs doesn't say anything about this

**Comment by yanislav-igonin** [comment]
I've figured it out

```
ctx.telegram.editMessageText(
  msgInfo.chat.id,
  msgInfo.message_id,
  msgInfo.message_id,
  `PLEASE`,
);
```

**Comment by ejnshtein** [comment]
Instead of second `msgInfo.message_id` you can just use `undefined`.
The third argument is for inline messages

**Comment by yanislav-igonin** [comment]
@ejnshtein tnx for info, will update my code :)

**Comment by divyenduz** [comment]
Yes, I am also interested in 

> this piece doesn't work, still getting error Error: Telegraf: "editMessageText" isn't available for "message::text", docs doesn't say anything about this

What is this error about?

**Comment by Piterden** [comment]
Check [this](https://core.telegram.org/bots/api#editmessagetext) example

**Comment by divyenduz** [comment]
I know the one from `ctx.telegram.editMessageText`, I could make it work. My question is more around the helper wrapper `ctx.editMessageText` which produces the error: 

`this piece doesn't work, still getting error Error: Telegraf: "editMessageText" isn't available for "message::text", docs doesn't say anything about this`

**Comment by Piterden** [comment]
> I know the one from `ctx.telegram.editMessageText`, I could make it work. My question is more around the helper wrapper `ctx.editMessageText` which produces the error:
> 
> `this piece doesn't work, still getting error Error: Telegraf: "editMessageText" isn't available for "message::text", docs doesn't say anything about this`

https://github.com/telegraf/telegraf/blob/develop/context.js#L195-L212

**Comment by divyenduz** [comment]
Does it make sense to add support for “message”? Happy to contribute that

**Comment by Piterden** [comment]
> Does it make sense to add support for “message”? Happy to contribute that

What do you mean?

**Comment by divyenduz** [comment]
Ah, sorry my bad. I overlooked the API. Please ignore my last message 👍

**Comment by jvlianodorneles** [comment]
Guys, how can I edit the message (and keyboard) sent by the start command?
I'm lost trying to get the message ID. :cry: 

```
bot.command('start', ctx => {
  let startMessage = `start message`;
  bot.telegram.sendMessage(ctx.chat.id, startMessage,
    {
      reply_markup: {
        inline_keyboard: [
          [
            { text: "botão", callback_data: 'clique' }
          ]
        ]
      },
      parse_mode: "markdown"
    }
    )
  })

bot.action('clique', ctx => {
    let editedMessage = `edited message`;
    ctx.telegram.editMessageText(ctx.chat.id, ctx.message.message_id, undefined, editedMessage,
      {
        reply_markup: {
          inline_keyboard: [
            [
              { text: "⬅️ Voltar", callback_data: 'start' }
            ]
          ]
        },
        parse_mode: "markdown"
      })
  })
```

**Comment by yanislav-igonin** [comment]
@jvlianodorneles hello bro

try 
```javascript
const message = await bot.telegram.sendMessage(ctx.chat.id, startMessage, .....
```

**Comment by ejnshtein** [comment]
> Guys, how can I edit the message (and keyboard) sent by the start command?
> I'm lost trying to get the message ID. 😢
> 
> ```
> bot.command('start', ctx => {
>   let startMessage = `start message`;
>   bot.telegram.sendMessage(ctx.chat.id, startMessage,
>     {
>       reply_markup: {
>         inline_keyboard: [
>           [
>             { text: "botão", callback_data: 'clique' }
>           ]
>         ]
>       },
>       parse_mode: "markdown"
>     }
>     )
>   })
> 
> bot.action('clique', ctx => {
>     let editedMessage = `edited message`;
>     ctx.telegram.editMessageText(ctx.chat.id, ctx.message.message_id, undefined, editedMessage,
>       {
>         reply_markup: {
>           inline_keyboard: [
>             [
>               { text: "⬅️ Voltar", callback_data: 'start' }
>             ]
>           ]
>         },
>         parse_mode: "markdown"
>       })
>   })
> ```

`ctx.editMessageText(txt, extra...)`
