### ISSUE TITLE
Heroku falls asleep

### ISSUE THREAD

**Issue by radyslavkrechet** [telegraf/telegraf#611]
Hi! Firstly, thank you for the great framework! I believe that someone can help me with my problem. Heroku falls asleep after 30 minutes of inaction, but after that, if I try to use bot's command, Heroku will not awake. Any ideas?

**Comment by pvnetto** [comment]
Did you solve this problem? I made a bot, deployed it to Heroku and everything works fine, except that the server goes idle, there's no way to wake it up.
