### ISSUE TITLE
how to find  admin

### ISSUE THREAD

**Issue by rozi98** [telegraf/telegraf#614]
hi sry for dump question i hav problem i want make an admin panel for my bot , when admin send messge to bot can chnge  something 
i want something like this 

`if(ctx.mesg.chat.id==adminlist)
{
do something
}`

**Comment by dotcypress** [comment]
@rozi98 in Telegraf we have some [useful middleware factories](https://github.com/telegraf/telegraf/blob/develop/composer.js#L294) for such cases.

```js
const { admin } = require('telegraf')

// Enable session for admins only
bot.use(admin(session()))

// Admin command example
bot.command('ban', admin(
  (ctx) => ctx.reply('Done')
))
```

#211

**Comment by rozi98** [comment]
@delvedor tnx  can i use it just in pv chat ? for manage other user access to bot?

**Comment by dotcypress** [comment]
@rozi98 for private chats we have `acl` factory:

```js
const { acl } = require('telegraf')

const adminIds = [444, 222, 666]

// Admin command example
bot.command('admin', acl(
  adminIds
  (ctx) => ctx.reply('Done')
))
```
