### ISSUE TITLE
Resive message  and update varable

### ISSUE THREAD

**Issue by rozi98** [telegraf/telegraf#615]
hello its dummy ask i know but i need help
look
i want update some varable  when some buton press 
for example when admin in pv pressed input btn  i want next message from him save in my varble 
soething like this 
`if(admin press btn)
send messg(insert input)
waint for admin messge
var input=ctx.messge.text;

`

**Comment by tva10** [comment]
Hello @rozi98 
I think you can use [session](https://telegraf.js.org/#/?id=session) or [stage](https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js) middleware here
