### ISSUE TITLE
stucked in bot.on 

### ISSUE THREAD

**Issue by rozi98** [telegraf/telegraf#618]
hi
this code stucked in bot.on and  save every mesg form user  after  sign up button  in database 
how can improve it ?

`   bot.hears('sign up',(ctx)=>{`
`     ctx.reply('enter ur data'); `
   `   bot.on('text',(ctx)=>{ `
   `  sendtoDB(ctx.mes.txt) `
   `    ctx.replay('saved') `

`       })   `

   `  })  `

**Comment by chakaponi** [comment]
Middleware should not be nested.

**Comment by rozi98** [comment]
@chakaponi 
Can u help me how to save input data from user.? Any idea?

**Comment by chakaponi** [comment]
> @chakaponi
> Can u help me how to save input data from user.? Any idea?

To transfer data between listeners, I use the assignment to the external property " bot.content"

Each message contains its own chat number (message_id). It can be used to correctly process user responses

**Comment by marcusique** [comment]
> > @chakaponi
> > Can u help me how to save input data from user.? Any idea?
> 
> To transfer data between listeners, I use the assignment to the external property " bot.content"
> 
> Each message contains its own chat number (message_id). It can be used to correctly process user responses

Could you please give a quick example of this? I'm also trying to handle user responses correctly, but I haven't found a way around it yet.
