### ISSUE TITLE
Array to forwardMessage

### ISSUE THREAD

**Issue by chakaponi** [telegraf/telegraf#619]
Please add the "**number[]/string[]**" type of the "**chatid**" parameter to the `forwardMessage` function.

**Comment by EdJoPaTo** [comment]
In general I think forwarding to multiple targets could easily be seen as spamming. Consider using a channel for example.

also using native JS [Array Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) is helpful here:
```js
await Promise.all(
  chatIds.map(id => ctx.forwardMessage(id))
)
```
