### ISSUE TITLE
Low Quality  of photos getFileLink 

### ISSUE THREAD

**Issue by rozi98** [telegraf/telegraf#623]
Hi i Want keep Photo received from Users in my Db.i try  `getFileLink ()`   BUT its unusable for have
 **low quality**
can you help me how to handle my problem [new link or something like that for good quality]

**Comment by Khuzha** [comment]
If you're going to send that photos in future in the Telegram, you can just save files ids. 

The id of file with maximal quality is:   `ctx.message.photo[ctx.message.photo.length - 1].file_id`
