### ISSUE TITLE
send message to channel every min

### ISSUE THREAD

**Issue by rozi98** [telegraf/telegraf#624]
its not work 
TypeError: Cannot read property 'telegram' of undefined
can y help me 
```
cron.schedule('* * * * *', (ctx) => {
   console.log('in time schudle');
   
   ctx.telegram.sendMessage('@mychannel','send this every min' ).then((result) => {
      
   }).catch((err) => {
      
   });
 

    })

```

**Comment by TiagoDanin** [comment]
Use `bot.telegram.sendMessage(...)`

**Comment by Khuzha** [comment]
1. ctx doesn't contain sendMessage() method
2. ctx is not declared there. You can use ctx only in handlers like 

bot.hear('hi', (ctx) => {
  // here ctx is defined
)}

But:

setInterval(function () {
  // here is no ctx
)}

**Comment by dotcypress** [comment]
@rozi98 context only available on update, you can use `bot.telegram.sendMessage` instead.
