### ISSUE TITLE
How to get the user's phone number?

### ISSUE THREAD

**Issue by eliasdeoliveira** [telegraf/telegraf#626]
How to get the user's phone number?

**Comment by ejnshtein** [comment]
Bot API does not have access to such information.

**Comment by Khuzha** [comment]
You can only ask user to send his number. Ask him to send it as text or add the keyboard-button for this:

`ctx.reply('Send me your number please', { reply_markup: { keyboard: [[{text: '📲 Отправить телефон', request_contact: true}]] } }`

**Comment by nick4fake** [comment]
That is not true anymore, not api v2 allows it

**Comment by nick4fake** [comment]
https://core.telegram.org/bots/2-0-intro

**Comment by francisyzy** [comment]
[Official 5.3 API](https://core.telegram.org/bots/api#keyboardbutton) still shows that this is available.
![image](https://user-images.githubusercontent.com/24467184/134393398-2f323dfc-d037-4499-b87f-3c5b66d90f36.png)

I am using this in the [V4.3](https://github.com/telegraf/telegraf/releases/tag/v4.3.0) telegraf package.
```typescript
ctx.reply("Please send your contact by pressing your contact", {
      reply_markup: {
        keyboard: [
          [
            {
              text: "📲 Send phone number",
              request_contact: true,
            },
          ],
        ],
        one_time_keyboard: true,
      },
    })
```
