### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by perqin** [telegraf/telegraf#63]
My develop environment is behind a http proxy which makes it hard for me to test the bot locally. Will Telegraf support HTTP proxy?

**Comment by dotcypress** [comment]
Yes, Telegraf supports [custom proxies](http://telegraf.js.org/telegraf.html#constructor) via `agent` options:

```js
const Telegraf = require('telegraf')
const HttpsProxyAgent = require('https-proxy-agent')

const bot = new Telegraf('token', {
  telegram: {
    agent: new HttpsProxyAgent('proxy url')
  }
})
```

**Comment by ri4ter** [comment]
Hello, I'm use poll updates with [SocksProxyAgent](https://github.com/TooTallNate/node-socks-proxy-agent)
Every 2-3 minutes i see an error 

`
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
`

This creates a lot of connections and a load of socks server.
How i can solve this problem? Thanks

**Comment by a-x-** [comment]
I done it!

Let's document the snippet for e.g. all russian users under the government's internet blocking:

```js
const Telegraf = require('telegraf');
const SocksAgent = require('socks5-https-client/lib/Agent');
const socksAgent = new SocksAgent({
  socksHost: config.proxy.host,
  socksPort: config.proxy.port,
  socksUsername: config.proxy.login,
  socksPassword: config.proxy.psswd,
});

const app = new Telegraf(token, {
  telegram: { agent: socksAgent }
});
```

We can use your usual socks5 proxy settings you use on your desktop/mobile clients!

**Comment by a-x-** [comment]
also, you should setup a custom `apiRoot` if you can use file apis.
so you should use something like https://github.com/kotfenix/tgdante2 as a socks5 server with no domain restrictions

**Comment by bongiozzo** [comment]
> I done it!
> 
> Let's document the snippet for e.g. all russian users under the government's internet blocking:
> 
> ```js
> const Telegraf = require('telegraf');
> const SocksAgent = require('socks5-https-client/lib/Agent');
> const socksAgent = new SocksAgent({
>   socksHost: config.proxy.host,
>   socksPort: config.proxy.port,
>   socksUsername: config.proxy.login,
>   socksPassword: config.proxy.psswd,
> });
> 
> const app = new Telegraf(token, {
>   telegram: { agent: socksAgent }
> });
> ```
> 
> We can use your usual socks5 proxy settings you use on your desktop/mobile clients!

Hello!
Does it work for sending files (Videos)?

**Comment by timmson** [comment]
@a-x- , @bongiozzo , i've found workaround.

I use this [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent) instead of socks5-https-client.

File upload works ;)
