### ISSUE TITLE
I am constantly getting an unhandled warning

### ISSUE THREAD

**Issue by thedevxen** [telegraf/telegraf#636]
I am using latest version of Telegraf. I don't know how but I am constantly getting this warning getting logged in my terminal : 

```UnhandledPromiseRejectionWarning: Error: 400: Bad Request: wrong parameter action in request```

**Comment by EdJoPaTo** [comment]
You should use async await or return methods like `ctx.reply`. That way JavaScript knows where to put these errors and displays a proper call stack when errors are not catched.

```js
ctx => {
  return ctx.reply('Hi there!')
}
```
or
```js
async ctx => {
  await ctx.reply('Hi there!')
  await ctx.reply('Still here?')
}
```
