### ISSUE TITLE
sending files via source or url ignores extra options

### ISSUE THREAD

**Issue by maddin77** [telegraf/telegraf#64]
Using the [media-bot.js](https://github.com/telegraf/telegraf/blob/develop/examples/media-bot.js) example script with `reply_to_message_id` added:
```js
const Telegraf = require("telegraf");
const fs = require("fs");

const bot = new Telegraf(process.env.BOT_TOKEN);

bot.on("text", (ctx) => {
    return Promise.all([
        // file
        ctx.replyWithPhoto({
            source: '/example/cat.jpeg'
            reply_to_message_id: ctx.message.message_id
        }),

        // Stream
        ctx.replyWithPhoto({
            source: fs.createReadStream('/example/cat2.jpeg')
            reply_to_message_id: ctx.message.message_id
        }),

        // Buffer
        ctx.replyWithPhoto({
            source: fs.readFileSync('/example/cat3.jpeg')
            reply_to_message_id: ctx.message.message_id
        }),

        // url
        ctx.replyWithPhoto({
            url: "http://lorempixel.com/400/200/cats/",
            reply_to_message_id: ctx.message.message_id
        })
    ]);
});

bot.startPolling();

```

Files are being sent just fine, but the extra params are ignored. I tested this with `reply_to_message_id` and `caption` but i assume it's the same for the others. The problem occurs with all `send*` methods as far as i can tell (i tested with photo, video & voice). 

The problem only occurs when the files are being sent via `url` or `source` option. Using the last example
```js
ctx.replyWithPhoto("http://lorempixel.com/400/200/cats/", {
     reply_to_message_id: ctx.message.message_id
})
```
works as expected.

**Comment by dotcypress** [comment]
Hey,

try this:
```js
ctx.replyWithPhoto({source: '/example/cat.jpeg'}, {
     reply_to_message_id: ctx.message.message_id
})
```

or more clean solution:

```js
const { Extra } = require('telegraf')

ctx.replyWithPhoto({source: '/example/cat.jpeg'}, Extra.inReplyTo(ctx.message.message_id))
```

**Comment by maddin77** [comment]
Ah i see, i thought using `source` meant to omit the first param and place `source` as an extra. Now it works, thanks.

As a side note, maybe i would be good idea to specify what the `File` type in the [docs](http://telegraf.js.org/telegram.html#sendphoto) means. As far as i can tell it's not really clear what exactly can be passed to the function. Or did i miss that somewhere?
