### ISSUE TITLE
How can I distinguish location message from live location message?

### ISSUE THREAD

**Issue by inikonorov** [telegraf/telegraf#641]
Hello! When I try to send location (just a place/building/etc) I get the same message object as when I try to send live location (first time; other times I get an edited message and this helps me to understand that this message is live location). How can I distinguish location message from live location message?

**Comment by namnguyen9x** [comment]
I also want to distinguish these two location types. Do you have any workaround?

**Comment by KnorpelSenf** [comment]
This is possible now since Bot API 5.0 by looking at the new `live_period` property.
