### ISSUE TITLE
'Send as separate photos' skip steps in Wizard

### ISSUE THREAD

**Issue by itaibaruch** [telegraf/telegraf#643]
Hi Telegraf Team,

I face a problem, and I like to have your advice.

I have a simple wizard just like in the wizard-bot.js example, only that mine accept photos:
```  
...
async (ctx) => {
    await ctx.reply('Step 3')
    return ctx.wizard.next()
  },
  async (ctx) => {
    await ctx.reply('Step 4')
    return ctx.wizard.next()
  },
  async (ctx) => {
    await ctx.reply('Done')
    return ctx.scene.leave()
  }
... 
```

The thing is when user upload 2 or more photos as separate photos, the wizard will move to the next step for each photo uploaded. Because the images not sent as a group, but each is loaded one after the other, and the wizard get each as a response. 

Do you have any idea how I can make the wizard stay in the same step, until all photos loaded (and I will pick one of them)?
or a way to define Telegram "send photo" popup to only accept 1 file? 

Thanks!

**Comment by dotcypress** [comment]
@itaibaruch best and easiest way here is to create separate scene for each step and get rid of `Wizard`.
