### ISSUE TITLE
Admin Bot

### ISSUE THREAD

**Issue by koliberr136a1** [telegraf/telegraf#644]
Hi dear friends,

Thanks for your great library, 
I have written an `AdminBot` for telegram groups and super groups recently using `Telegraf` and `Sequelize ORM` 

If you  would like, you can add it to `Telegraf` examples list

This is my bot source link:
[AdminBot](https://github.com/Azhant/AdminBot)

**Comment by dotcypress** [comment]
@koliberr136a1 feel free to make PR with link to your bot.
Closing for now.
