### ISSUE TITLE
Enter wizard from telgraf-inline-menu question button

### ISSUE THREAD

**Issue by RobSteward** [telegraf/telegraf#647]
Hi, 
I am struggling to enter a wizard scene from the question menu button

```
mainMenu.submenu("📜 Rules", "showRulesMenu", rulesMenu)
  .question('📜 add', 'addRule', {
    questionText: 'Name of the rule?',
    setFunc: async (_ctx, key) => {
      await _ctx.answerCbQuery(`you selected ${key}`)
      stage.enter("add_wizard");
      console.log("Entered stage addWizard");
    },
    joinLastRow : true})
```

Which should call 

```
const addWizard = new wizard('add_wizard',
  (ctx) => {
    ctx.reply('Step 1', Markup.inlineKeyboard([
      Markup.urlButton('❤️', 'http://telegraf.js.org'),
      Markup.callbackButton('➡️ Next', 'next')
    ]).extra())
    return ctx.wizard.next()
  },
  stepHandler,
  (ctx) => {
    ctx.reply('Step 3')
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Step 4')
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Done')
    return ctx.scene.leave()
  }
)
```

My launch section looks like this:
```
const addWizardStage = new stage([addWizard], {
  default: 'add_wizard'
})
bot.use(addWizardStage.middleware())
bot.use(mainMenu.init({
  backButtonText: 'Back',
  mainMenuButtonText: 'Back'
}))
bot.use(session());
bot.launch();
```
This above is the sample wizard script from [https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js](url).

However, the menu just returns without entering. The function is executed, as the console log is showing.

###

**Comment by sfarzoso** [comment]
@RobSteward  did you fixed that?

**Comment by RobSteward** [comment]
Hi mate, sorry. No I moved on for now. But I will have to address this issue at some point. Guess wizards are a much more elegant way of solving this than writing manual scenes.

**Comment by sfarzoso** [comment]
@RobSteward I fix that issue, you can check the fix [here](https://stackoverflow.com/questions/55749437/stage-enter-doesnt-start-the-wizard) hope it helps.
