### ISSUE TITLE
Get an array of chat members statuses? eg getChatMembers

### ISSUE THREAD

**Issue by nicholasteoyk** [telegraf/telegraf#651]
Hi Telegraf Team!

I was just wondering since we have a `getChatAdministrators` function which would return an array of administrators, would there be an inverted feature eg `getChatMembers`? Or any snippet of code that could help me do the same function too?

I took a look at one of the closed issue by @dotcypress and he did say he has a middleware regarding this issue and he would implement this but I didn't see it when I was looking through though. :/

Thank you! :)

**Comment by pedrocarlos-ti** [comment]
same problem.

**Comment by TiagoDanin** [comment]
I have this ([Telegraf GetChatMembers](https://github.com/TiagoDanin/Telegraf-GetChatMembers)) solution using memory cache.

**Comment by nicholasteoyk** [comment]
Hi @TiagoDanin! I took a look at your code and it's very insightful. I'll only get to try it out after my final exams next Wednesday so pardon the slow and late reply :/
