### ISSUE TITLE
How to initiate a wizard?

### ISSUE THREAD

**Issue by risonsimon** [telegraf/telegraf#652]
Is there a way to initiate a wizard? I want to ask the user a survey periodically. Currently, I can only see a way to send messages as seen in [this issue](https://github.com/telegraf/telegraf/issues/101). However, it doesn't mention how to continue the conversation. 

Is there a way to enter a wizard by using user id?

Can someone help with this?

**Comment by tawsbob** [comment]
`bot.command('sign', ctx => {
   ctx.scene.enter('your-wizard-id')
})
`
