### ISSUE TITLE
Commands in groups stop working after while 

### ISSUE THREAD

**Issue by N3TC4T** [telegraf/telegraf#653]
## Context

Unfortunately the bot commands will stop working after while in groups and have to use /start command or run the commands with bot username to make it work again .

I try to check the logs and debug but couldn't find anything , also removed other bots from group and tried again but couldn't fix the problem .

[here](https://github.com/N3TC4T/xrp-telegram-bot) is the bot repo, i would appreciate if you could take a look.

* Telegraf.js Version: `^3.27.1`
* Node.js Version: `v8.12.0`
* Operating System: `Centos 7`

## Expected Behavior

run the commands(without including bot username) in the groups all the time.

## Current Behavior

running commands without bot username will stop working ***after a while***

**Comment by KnorpelSenf** [comment]
Possibly related to #735

**Comment by wojpawlik** [comment]
This is expected if [privacy mode](https://core.telegram.org/bots#privacy-mode) is enabled and you have more than one bot.

**Comment by N3TC4T** [comment]
FYI, the privacy mode were off.

**Comment by KnorpelSenf** [comment]
@N3TC4T you have to remove the bot from the group and add it again after disabling privacy mode. [[Source](https://core.telegram.org/bots#privacy-mode)]

Could that be the problem?

**Comment by N3TC4T** [comment]
the bot privacy mode was off from the first place, and all the commands were working without bot username, but for example after two days suddenly the bot commands would stop working and I had to run the commands with bot username to make them work again.

BTW I'm not maintaining the bot anymore so maybe the problem is already solved.

**Comment by KnorpelSenf** [comment]
It seems to me that Telegram behaves strange when it comes to which messages the bot receives and which not.

Either way, it does not look like an issue of `telegraf` to me.
