### ISSUE TITLE
How would you structure folders in a bot project?

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#654]
Just wondering, to everyone who has used this library before to build a bot, how would you structure your code into smaller files and folders?

**Comment by mfissehaye** [comment]
![image](https://user-images.githubusercontent.com/2877236/64532395-0ea7d000-d31a-11e9-9782-64de235f4dad.png)

I find this structure interesting.

**Comment by wojpawlik** [comment]
Look at community bots in https://github.com/telegraf/telegraf/blob/develop/docs/README.md
