### ISSUE TITLE
[input.httpjson] problem

### ISSUE THREAD

**Issue by badgerman11** [telegraf/telegraf#657]
Hi, 
I've stuck on this problem for about a week. Sorry for this stupid question. I'm not a programmer, just trying to make MagicMirror with smog measurements. Read everything about it and still no clue why I can't make it work.

I need to put data form this link to ifnluxdb
[http://api.gios.gov.pl/pjp-api/rest/data/getData/18038](url)

This is my telegraf.config:

> [[outputs.influxdb]]
>
 >urls = [
   > "http://localhost:8086",
 > ]
 > database = "domoticz"
>
>[agent]
>  interval = "30m"
 > round_interval = true
>
>[[inputs.httpjson]]
  
 > name = "PM25"

 > servers = [
>    "http://api.gios.gov.pl/pjp-api/rest/data/getData/18038", 
 > ]
 >response_timeout = "15s"

>  method = "GET"

>  tag_keys = [
 >  "key"
> ]

Thanks for help!

**Comment by ejnshtein** [comment]
whaaaaaaaaaaaaa

**Comment by badgerman11** [comment]
Yep, I know. Sorry. I can't find any good tutorial about it. I really tried it and don't understand it at all. Please help.

**Comment by ejnshtein** [comment]
Read readme of this repo first, please

**Comment by badgerman11** [comment]
Ok, got it, my bad :) i dunno wtf i wrote it here.
