### ISSUE TITLE
Is it possible to remove a middleware after it is no longer needed?

### ISSUE THREAD

**Issue by tigermarques** [telegraf/telegraf#658]
Hi, this is more a question than a bug report.

I'm using a middleware to restrict the possible actions a user can take after they send a specific command to the bot. However, when the sequence of messages regarding that command are finished, I would like to remove the middleware from the stack.

Is this possible?

Thank you!

**Comment by dotcypress** [comment]
@tigermarques you can't change middleware stack, but you can add optional handlers to it:

```js

bot.command('hide_secret', (ctx) => {
  ctx.session.hide_secret = true
  return ctx.reply('Ok')
})

bot.command('secret', Telegraf.optional(
  (ctx) => !ctx.session.hide_secret,  
  (ctx) => ctx.reply('Secret')
))
```
