### ISSUE TITLE
Webhook example is not clear

### ISSUE THREAD

**Issue by alkhimey** [telegraf/telegraf#660]
What does the three dashes mean?

https://github.com/telegraf/telegraf/blob/b8fe94ebaac3352d833a16c530779ea2691462fb/docs/examples/webhook-bot.js#L15

In general, the docs and the examples are not clear on how to use webhooks. 

1. Should I call myself telegrams API to register the webhook, or does telegraf handles this for me?

2. Why does "start webhook directly" requires two steps and a secret path but the bot.launch method does not?

3. What will be the endpoint that I need to register telegram with when using the launch method? My guess is that telegraf generates it automatically but I need to know this for debugging.

**Comment by alkhimey** [comment]
Ok, after some tinkering I figured myself most of the stuff. Still I think it is good to have these things documented.

**My findings:**
Three dashes are just an example. the domain parameter is where bot's back-end is deployed. When using the `launch` function, telegraf will register an endpoint with telegram and will set up the routing inside your application. It will look like `https://yourdomain.net/telegraf/<secret hash>`. To find out what is the registered endpoint I used `getWebhookInfo` API call (GET of `https://api.telegram.org/bot<bot token>/getWebhookInfo`).

**Comment by b3z** [comment]
`// npm install -g localtunnel && lt --port 3000`

This comment in line 1 gives you information how to acquire the domain

**Comment by thewayur** [comment]
what if i want to use serveo? please help me

**Comment by hypernova7** [comment]
it may be a bit later, but here are some examples

### Setup webhook

ngrok example with `top-level-await`:

```javascript
const ngrok = require('ngrok')
const app = require('express')()
const [ Telegraf } = require('telegraf')

const url = await ngrok({
  authToken: ngrokAuthToken,
  addr: 8080
})
const bot = new Telegraf(token)
app.use(await bot.createWebhook({ domain: url }))

bot.on('message', async ctx => {
  await ctx.reply('Hello there')
})

app.listen(8080)
```

ngrok example without `top-level-await`:

```javascript
const ngrok = require('ngrok')
const app = require('express')()
const [ Telegraf } = require('telegraf')

const bot = new Telegraf(token)

bot.on('message', async ctx => {
  await ctx.reply('Hello there')
})
(async () => {
  const url = await ngrok({
    authToken: ngrokAuthToken,
    addr: 8080
  })

  await bot.launch({
    webhook: {
      domain: url,
      port: 8080,
      cb: app
    }
  })
})()
```
