### ISSUE TITLE
Official example wizard Scene don't work. help me please!

### ISSUE THREAD

**Issue by 45Code** [telegraf/telegraf#662]
Hello everybody!
Help me please!
Sorry, english no native language...:(

I copy paste example from https://github.com/telegraf/telegraf/blob/develop/docs/examples/self-cleaning-scenes.js

I change token for activation, but code don't work. Help me!

**Comment by dogusev** [comment]
same for me

**Comment by dotcypress** [comment]
Guys, this example is invalid and will be deleted, sorry for that.

Feel free to open new Issue if you have any `Scene` related questions.
