### ISSUE TITLE
ctx.match is missing

### ISSUE THREAD

**Issue by EugeneDraitsev** [telegraf/telegraf#666]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version:  3.29.0
* Node.js Version: 11.6.0
* Operating System: Win10

## Expected Behavior

Please describe the behavior you are expecting

ctx.match is available in `command` handler (based on your [documentation](https://telegraf.js.org/#/?id=context))

## Current Behavior

What is the current behavior?

ctx.match is undefined in `command` hanlder

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create simple command handler and log ctx.match
```jsx
bot.command('test', (ctx) => {
  console.log(ctx.match)
  return ctx.reply('λ')
})
``` 
2. check your console!
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by ejnshtein** [comment]
ctx.match is using only for Regexp, so
```js
 /text/, ctx => {console.log(ctx.match)}
```

**Comment by psixdev** [comment]
@ejnshtein Could you provide a more detailed example of using `bot.command` with regular expressions? I try, but it just doesn't work

```
bot.command(/test/, () => console.log('success 1'));
bot.command(/^test$/, () => console.log('success 2'));
bot.command(/\/test/, () => console.log('success 3'));
bot.command(/^\/test$/, () => console.log('success 4'));
```

This only works with `bot.hears`
