### ISSUE TITLE
Spinner remains on inline button after click

### ISSUE THREAD

**Issue by YuriGor** [telegraf/telegraf#670]
## Context

* Telegraf.js Version: v3.29.0
* Node.js Version, Operating System: [@now/node builder](https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node/)

## Expected Behavior

Spinner animation on the inline callback button should disappear after click was processed at the backend

## Current Behavior

Spinner animation remains even after button click was handled at the backend
![image](https://user-images.githubusercontent.com/6861317/58085856-2c63f480-7bc6-11e9-91d0-ee6cede1f267.png)

Maybe I do something wrong, here is a piece of code:

```js
  // on 'checkbox' option button click..
  bot.action(/o_\d+/, async (ctx) => {
      /*
        - extract index of the button
        - toggle checked state in the session
        - regenerate array of buttons to render check marks accordingly
        - update previous message 
      */
      return ctx.editMessageText('some title here',
      Extra.markup((m) =>
        m.inlineKeyboard( [/* array of updated buttons */], { columns:2 } )
      )
    );
});
```
Looks like Telegram doesn't get correct response when I edit existing message instead of sending new reply and still waits for something after click.
Maybe I should not return `ctx.editMessageText` but return something like `200 OK` code?

**Comment by YuriGor** [comment]
I also tried to call `next` as in some examples, but issue still remains
```js
  // on 'checkbox' option button click..
  bot.action(/o_\d+/, async (ctx, next) => {
      /*
        - extract index of the button
        - toggle checked state in the session
        - regenerate array of buttons to render check marks accordingly
        - update previous message 
      */
      return ctx.editMessageText('some title here',
      Extra.markup((m) =>
        m.inlineKeyboard( [/* array of updated buttons */], { columns:2 } )
      )
    ).then(() => next());
});
```

**Comment by YuriGor** [comment]
Here is how my lambda made to run in the zeit now:

```js
const cb = bot.webhookCallback('/' + secret);
module.exports = async (req, res) => {  return cb(req, res); };
```

**Comment by YuriGor** [comment]
According to telegram docs, [answerCallbackQuery should be used](https://core.telegram.org/bots/api#answercallbackquery)
I tried this:
```js
bot.action(/o_\d+/, async (ctx) => {
      await ctx.editMessageText('some title here',
      Extra.markup((m) =>
        m.inlineKeyboard( [/* array of updated buttons */], { columns:2 } )
      ));
      ctx.answerCbQuery();
});
``
And now it works perfectly.

**Comment by PQMISSCMP** [comment]
@YuriGor 
Hello friend, do you have any specific example of a checkbox that can be implemented in telegraph? I would be very helpful. regards

**Comment by YuriGor** [comment]
Hi, as you see in "discussion" above, I use online keyboard and prepend button text with Unicode emoji of check box depending on state which I keep in session. In action handler i toggle state which manage by my self and then update buttons using this new state.
So that array of buttons configs i generate on each action using updated state. Giving full working example will cost a lot of time and it also depends on how you host your bot, so just try to display online keyboard and update it on action.

**Comment by PQMISSCMP** [comment]
thanks Yuri ... although I suppose the refresh rate is not that good ... I thought that telegram had some native object that was useful

**Comment by YuriGor** [comment]
you can test rate here:
https://t.me/BuyOrNotBot
but it's in Russian.
To see checkbox button choose or say  "/start"
and then when he will say his Russian greeting abracadabra - send him some text
then the questionnaire will start with checkbox buttons.

**Comment by PQMISSCMP** [comment]
thk
