### ISSUE TITLE
[Typescript] Property 'sendMediaGroup' does not exist on type 'Telegram'

### ISSUE THREAD

**Issue by arkada38** [telegraf/telegraf#686]
## Context

* Telegraf.js Version: 3.30.1
* Node.js Version: v8.11.1
* Operating System: Windows 10

## Expected Behavior

_index.d.ts_ have _sendMediaGroup_ property.

## Current Behavior

_index.d.ts_ does not have _sendMediaGroup_ property.

## Failure Information

`bot.telegram.sendMediaGroup(ctx.from.id, res)`

```
lib/bot/user/cars.ts:425:30 - error TS2339: Property 'sendMediaGroup' does not exist on type 'Telegram'.

589                 bot.telegram.sendMediaGroup(ctx.from.id, res)
```

**Comment by fan-tom** [comment]
Moreover, library has many problems with typings, some of classes/methods are not typed at all, others are wrong. Seems that typings are totally not in sync with js part

**Comment by dotcypress** [comment]
Duplicate #732
