### ISSUE TITLE
Receive an update when message is deleted in chat??

### ISSUE THREAD

**Issue by thusfar7** [telegraf/telegraf#687]
Is it possible to receive an update/notification/type in NodeJS when a user deletes a message? I would like to know which message was deleted. I'm talking about long-press on a message and pressing "Trash icon".

I think this might be done with callback_query but that's not preferable to me and my situation.

Thx

**Comment by dotcypress** [comment]
@thusfar7 I'm afraid this is impossible due BotAPI restrictions.
