### ISSUE TITLE
How can we restrict an user?

### ISSUE THREAD

**Issue by wilcorrea** [telegraf/telegraf#689]
Hey guys, sorry if it is not the right channel to questions, but I am working on a bot to show a captcha and I wanna restrict the new user of post messages before handle the captcha. Can you help me to know how to it?

**Comment by Raingerlina** [comment]
What I have in my mind is to have the if statement at the very start of a function which compares user's id with the allowed list (or vice versa, disallowed)

```js
bot.command('help', (ctx) => {
  if (ctx.message.from.id === <something_to_compare>) {
    // do stuff
  }
  else {
    // don't do stuff
  }
})
```

**Comment by wilcorrea** [comment]
Actually I wanna call `restrictChatMember` (https://core.telegram.org/bots/api#restrictchatmember).

I found it in the base code [here](https://github.com/telegraf/telegraf/blob/320094ae1bd9f1c3682e7e29231768d9f4a8b2c2/telegram.js#L189).
I dont know why this method is not working (I will understand soon), so I call the API
```js
ctx.telegram.callApi('restrictChatMember', payload)
```

After I understand the reason why to call the method directly is not working I will comment here, make a pr (if necessary) and close the issue.

**Comment by KnorpelSenf** [comment]
Any updates on this?
