### ISSUE TITLE
reply_to_message is inconsistent

### ISSUE THREAD

**Issue by selabie68** [telegraf/telegraf#692]
## Context

* Telegraf.js Version: 3.30.1
* Node.js Version: 11.15.0
* Operating System: Ubuntu 19.04

## Expected Behavior

User is to reply to another users message, the bot picks up based on a command and the acts accordingly. Bot is looking for `ctx.update.message.reply_to_message`

## Current Behavior

`ctx.update.message.reply_to_message` returns undefined

**Comment by dotcypress** [comment]
@selabie68 please use `ctx.message.reply_to_message`

**Comment by Porkechebure** [comment]
how this does work in groups @dotcypress
