### ISSUE TITLE
getFileLink on voice message never returns

### ISSUE THREAD

**Issue by bkahlerventer** [telegraf/telegraf#697]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.30.1
* Node.js Version: 8.10
* Operating System: Linux

## Expected Behavior
```javascript
bot.on('voice', (ctx) => {
    console.log('--- voice message ---');
    console.log('file_id: ' + ctx.message.voice.file_id);
    ctx.telegram.getFileLink(ctx.message.voice.file_id).then((url) => {
        console.log('--- url: ' + url);
    }).catch((err) => {
        console.log('*** error ***');
        console.log(err);
    });
}
```
This prints the file_id but the call to the getFileLink method does not complete, nor does it fail.

I do not know if this constitutes a bug or a feature request.

**Comment by dotcypress** [comment]
@bkahlerventer because you calling `ctx.telegram.getFileLink` synchronously.  

Fixed example
```js
bot.on('voice', (ctx) => {
  console.log('--- voice message ---')
  console.log('file_id: ' + ctx.message.voice.file_id)
  return ctx.telegram.getFileLink(ctx.message.voice.file_id).then((url) => {
    console.log('--- url: ' + url)
  }).catch((err) => {
    console.log('*** error ***')
    console.log(err)
  })
})
```
