### ISSUE TITLE
Channel subscriber events

### ISSUE THREAD

**Issue by Eligioo** [telegraf/telegraf#698]
**Is your feature request related to a problem? Please describe.**
Right now in Telegraf, for chats you have the `new_chat_members` and `left_chat_member` events. Comparable events when a user subscribes or unsubscribes to a channel don't exist.

**Describe the solution you'd like**
Having the two events added: `new_channel_subscriber` and `left_channel_subscriber` so a bot can keep track who subscribed and who unsubscribed.

**Comment by ejnshtein** [comment]
Impossible due Bot API limitation
