### ISSUE TITLE
Sending keyboard with message with buttons

### ISSUE THREAD

**Issue by Mrglut** [telegraf/telegraf#70]
Hello, sorry for the foolish question, but how can I do it in one message?

I have this code, but here 2 messages:

```
const testMenu = Telegraf.Extra
  .markdown()
  .markup((m) => m.inlineKeyboard([
    m.callbackButton('Test button', 'test')
  ]));

const aboutMenu = Telegraf.Extra
  .markdown()
  .markup((m) => m.keyboard([
    m.callbackButton('⬅️ Back')
  ]).resize());

bot.hears('test', (ctx) => {    
  ctx.reply('test message', testMenu).then(() => {
    ctx.reply('about', aboutMenu)
  })
});
```

Or maybe you have a solution to send normal keyboard without message. Then I would send 'about' keyboard and after that sent test message with inline keyboard. But I read Bot API documentation and did not find this.

Also I don't understan why the 'about' reply sometimes comes first.

Regards!

**Comment by Mrglut** [comment]
@dotcypress so, can you help me?

**Comment by dotcypress** [comment]
Hey @Mrglut 
Actually you can't send `keyboard` without message.

Example callback keyboard handler:
```js
const testMenu = Telegraf.Extra
  .markdown()
  .markup((m) => m.inlineKeyboard([
    m.callbackButton('Test button', 'test')
  ]))

const aboutMenu = Telegraf.Extra
  .markdown()
  .markup((m) => m.keyboard([
    m.callbackButton('⬅️ Back')
  ]).resize())

app.hears('test', (ctx) => {
  ctx.reply('test message', testMenu).then(() => {
    ctx.reply('about', aboutMenu)
  })
})

app.action('test', (ctx) => ctx.answerCallbackQuery('Yay!'))
```

**Comment by Mrglut** [comment]
@dotcypress Thank you. And as I understand it is normal that sometimes reply comes not in right order?

**Comment by dotcypress** [comment]
Not normal, but also is't a bug. Anyway i can't reproduce that issue, maybe it's network related.

**Comment by Mrglut** [comment]
Yeah, I think it's network. Anyway thank you!
