### ISSUE TITLE
Telegram in-app Audio Player doesn't work with sendAudio method

### ISSUE THREAD

**Issue by BJ4K3** [telegraf/telegraf#700]
Hi, I'm working on a bot that sends on-server downloaded audio.

This is the code:
```javascript
const Telegraf = require('telegraf')
const bot = new Telegraf("API-here")
var filepath = "path/to/the/file.mp3"
var duration = 128
var name = "The Simpson"
var performer = "Homer Simpson"
var mime = "audio/mpeg"
bot.command("dl", ctx=>{
   ctx.replyWithAudio({source: filepath}, {title: name, duration: duration, performer: performer, mime_type: mime})
})
```

The file will be sent but, when I click play (for only listening, the in-app audio player), the file starts to downloading. What's wrong with my code? Thank you.

**Comment by dotcypress** [comment]
@BJ4K3 I can't reproduce issue. Could you provide `mp3` file from your example.
