### ISSUE TITLE
How can I adjust this inline_keyboard?

### ISSUE THREAD

**Issue by francescomesianodev** [telegraf/telegraf#701]
So, i know how to adjust the keyboard in colums or resize it using only **context** but how can i resize it using **context.telegram**?

For example, this is using ctx.telegram

```
const keyboard = [ [ Markup.callbackButton('1', 'op1'), Markup.callbackButton('2', 'op2') ] ]
...
ctx.telegram.sendMessage(ctx.from.id, "some text with a inline keyboard",  { reply_markup: { inline_keyboard: keyboard } })
```

this one is using only ctx

```
const keyboard = Telegraf.Extra
  .markdown()
  .markup((m) => m.keyboard([
    m.callbackButton('1', 'op1'),
    m.callbackButton('2', 'op2')
  ]).resize())

ctx.reply("some text with inline keyboard", keyboard)

```

How can I do resize a keyboard using arrays of arrays?

**Comment by pedrocarlos-ti** [comment]
Hello @francescomesianodev, in the telegram context you should configure your buttons inside each array child for example:

``` 
const keyboard = 
    [
        [
           Markup.callbackButton("Label1", "action1"),
           Markup.callbackButton("Label2", "action2"),
        ],
        [
           Markup.callbackButton("Label3", "action3"),
           Markup.callbackButton("Label4", "action4")
        ]
    ]
```

Each child array will render a line, in this example we'll have two rows with two buttons.

I hope that its help you.

**Comment by mfissehaye** [comment]
> Hello @francescomesianodev, in the telegram context you should configure your buttons inside each array child for example:
> 
> ```
> const keyboard = 
>     [
>         [
>            Markup.callbackButton("Label1", "action1"),
>            Markup.callbackButton("Label2", "action2"),
>         ],
>         [
>            Markup.callbackButton("Label3", "action3"),
>            Markup.callbackButton("Label4", "action4")
>         ]
>     ]
> ```
> 
> Each child array will render a line, in this example we'll have two rows with two buttons.
> 
> I hope that its help you.

This does not work for me in the case of inline keyboards.
