### ISSUE TITLE
No log when using the keyboard

### ISSUE THREAD

**Issue by gajet5** [telegraf/telegraf#702]
## Context

* Telegraf.js Version: 3.30.1
* Node.js Version: 12.6.0
* Operating System: Win10

## Expected Behavior

When using the keyboard, the message is logged.

## Current Behavior

There is no reaction when sending a message/action using the keyboard.

## Additional Information

I want to solve the problem: Clear the chat when changing scenes.
I found this example: https://github.com/telegraf/telegraf/blob/develop/docs/examples/self-cleaning-scenes.js
I manage to delete all messages except those messages that are sent to the chat using the keyboard. (https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js#L20)
They are not logged and I cannot catch them using an middlewares function.

**Comment by gajet5** [comment]
I recorded a video in which I reproduce the problem: https://www.youtube.com/watch?v=DZpjse-O6Oc

**Comment by dotcypress** [comment]
Closing in favor of #662
