### ISSUE TITLE
ERROR 409 / Failed to process updates...

### ISSUE THREAD

**Issue by montblanc13** [telegraf/telegraf#704]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.30.1
* Node.js Version: 10.16.6
* Operating System: xubuntu

## Expected Behavior

Just making simple sample bot answering "message received" on each update

## Current Behavior

Crash with 409 Error

## Failure Information (for bugs)

Here id the error stack
`{ env: 'dev',
  bot: { key: '???' } }
Failed to process updates. { Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at buildConfig.then.then.then.then (/home/slandeau/Dev/workspace-js/telegram-bot/node_modules/telegraf/core/network/client.js:263:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' },
  description:
   'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on:
   { method: 'getUpdates?offset=0&limit=100&timeout=30',
     payload: {} } }
`

### Steps to Reproduce

Here the tested code... Simple stupid isn't it ? 

'
const util = require("util");
const Telegraf = require("telegraf");

const cfg = require("./config");
const bot = new Telegraf(cfg.bot.key);

bot.on('text', (ctx) => {
    ctx.reply("Message received !");
});

bot.launch();
'
### Failure Logs

Please include any relevant log snippets or files here.

@See failure information above

**Comment by montblanc13** [comment]
Sorry, opening was a mistake...

**Comment by leonardolima99** [comment]
I have this error. What do I do?

```
Failed to process updates. TelegramError: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at /home/leonardo/Projetos/diario2_bot/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 409,
  response: {
    ok: false,
    error_code: 409,
    description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'
  },
  description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on: {
    method: 'getUpdates?offset=952996623&limit=100&timeout=30',
    payload: {}
  }
}
```

**Comment by cupcakearmy** [comment]
@leonardolima99 for me it was having 2 `bot.launch()` from the example
