### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by SoilChang** [telegraf/telegraf#71]
Is it possible to add in typescript definition for this library? It would make development much easier.

**Comment by dotcypress** [comment]
Hey.

It absolutely possible 👍 

PR is highly welcome.

**Comment by LestaD** [comment]
And flow?

**Comment by mRs-** [comment]
Hey, what's the current status? Would like to use TypeScript with this lib :)

**Comment by flaticols** [comment]
Hey! I'm started to write **.d.ts**. After few days plan PR.

**Comment by mRs-** [comment]
Awesome. Looking forward to it.

**Comment by LestaD** [comment]
I'm started working on typescript typings.
Please, contribute: https://github.com/LestaD/telegraf/tree/typings

**Comment by elementh** [comment]
Any update on the current status of this issue?

**Comment by sagax85** [comment]
could we merge the work of @LestaD to the main repo?

**Comment by sergeysova** [comment]
@SoilChang @mRs- @flaticols @elementh @sagax85 

Welcome to [feature/typings](https://github.com/telegraf/telegraf/tree/feature/typings) branch

PR: #245

**Comment by sajjad-ser** [comment]
how can i use this at the moment?

**Comment by Y0hy0h** [comment]
Is there an example that uses TypeScript with Telegraf? I have trouble setting it up and would love to see a working setup.

**Comment by Y0hy0h** [comment]
@sajjad-ser I managed to get it to work by telling npm to fetch the branch directly from GitHub instead of the npm package in the package.json:
```
"dependencies": {
   ...
   "telegraf": "telegraf/telegraf#feature/typings"
}
```
If you would like to see an example, you can check out my bot at https://github.com/Y0hy0h/secret-santa-bot/tree/typescript.

**Comment by Y0hy0h** [comment]
Is it a good idea to port all of Telegraf to TypeScript? That way, the would be no way that the typings could mismatch the library.

**Comment by sergeysova** [comment]
Full telegram bot types parsed and stored in [telegram-typings](https://npmjs.com/telegram-typings)


https://github.com/sergeysova/telegram-typings/blob/master/javascript/index.d.ts

**Comment by Y0hy0h** [comment]
Are there any examples of Telegraf bots using TypeScript? I'm having trouble setting it up.

**Comment by j-c-levin** [comment]
@Y0hy0h If it helps, I'm working on one now

https://github.com/j-c-levin/notcatbot

**Comment by divyenduz** [comment]
Is there any way I can help in moving this forward?

**Comment by Piterden** [comment]
Guys, there is one bot which need to be rewritten. https://github.com/Piterden/syntax-highlighter-bot
The structure smells fishy there for now, however in the past it smelled stronger https://github.com/Piterden/syntax-highlighter-bot/tree/old-double-bot?files=1

**Comment by shurygindv** [comment]
Hi, guys, help! Probably, is there an incorrect type definition in index.d.ts file:
`870: export interface Telegraf<TContext extends ContextMessageUpdate> extends Composer<TContext>`
Interface doesn't have an '.action(...)' method, yep, it has in here
`788: export interface ComposerConstructor`, but not in `740: export interface Composer<TContext extends ContextMessageUpdate> {` (in the same time Telegraf extends exactly Composer instead ComposerConstructor interface)

p.s in js: class Telegraf extends Composer (it has such interface), I don't feel right till post about that, thank you!

**Comment by backmeupplz** [comment]
Yep, it doesn't, I had to introduce it myself in my code.

**Comment by thedevxen** [comment]
> I'm started working on typescript typings.
> Please, contribute: https://github.com/sergeysova/telegraf/tree/typings
> 
> https://github.com/sergeysova/telegraf/blob/typings/typings/telegraf.d.ts
> 
> 2K lines of typings is ready now

all repositories has been removed, why? :cry:

**Comment by Piterden** [comment]
@thedevxen [take a look](https://github.com/sergeysova/telegram-typings)

**Comment by divyenduz** [comment]
@Piterden Ooops! I just saw today (because of the latest changes) for some reason that I got mentioned in that last comment. Is this work still to be done? Happy to pick that up if it is still there.

**Comment by Piterden** [comment]
@divyenduz sorry I don't understand what you are talking about

**Comment by divyenduz** [comment]
This [message](https://github.com/telegraf/telegraf/issues/71#issuecomment-415233801) has 

> I would be happy if you will try to write this code, @divyenduz

I am sorry that missed it earlier, happy to help if this is still a task :)
