### ISSUE TITLE
Empty keyboard if the Extra.HTML().markup() is async

### ISSUE THREAD

**Issue by IDIDIR** [telegraf/telegraf#719]
Sync function:
```
Extra.HTML().markup((m) => {
	return m.inlineKeyboard([
		Markup.callbackButton('oke', 'lang1'),
	])
})
```
result:
```
Extra {
    parse_mode: 'HTML',
    reply_markup: { inline_keyboard: [ [Array] ] } }
```
Async function:
```
Extra.HTML().markup(async (m) => {
	return m.inlineKeyboard([
		Markup.callbackButton(`${(await Translate('oke'))}`, 'lang1'),
	])
})
```
result:
```
Extra {
    parse_mode: 'HTML',
    reply_markup: { } }
```

**Comment by IDIDIR** [comment]
work solution.
I change framework function `extra.markup()` to
```
  async markup (markup) {
    if (typeof markup === 'function') {
      markup = await markup(new Markup())
		}
		this.reply_markup = Object.assign({}, markup)
    return this
  }
```
and async function:
```
await Extra.HTML().markup(async (m) => {
	return m.inlineKeyboard([
		Markup.callbackButton(`${(await Translate('oke'))}`, 'lang1'),
	])
})
```
are there any better solutions?

**Comment by ejnshtein** [comment]
I guess you can wrap markup into function and call it in async function.
Should be ok

**Comment by IDIDIR** [comment]
@ejnshtein yes, I had to add another line with the markup declaration. but then when working with the functionality of the framework, laconicism is lost

**Comment by ejnshtein** [comment]
Well, you want to use asynchronous function in place which designed only for synchronous function.
🤔🤔🤔🤔🤔🤔
And even better, you can’t  handle error in this situation.

**Comment by dotcypress** [comment]
@IDIDIR you can run all async code before markup creation:
```js
async (ctx) => {
  const text = await Translate('oke')
  const extra =  Extra.HTML().markup((m) => {
    return m.inlineKeyboard([
       Markup.callbackButton(`${text}`, 'lang1'),
    ])
  })
}
```

**Comment by TorlanDelta** [comment]
Also have run into the same problem. 

```js
async function defaultBtns(m) {
  return [
   m.callbackButton("Give me money", "an_offer_we_cant_refuse") 
]
}

var _extra = Extra.markup( m=> m.inlineKeyboard(defaultBtns(m)))
console.log(_extra) // returns "Extra { reply_markup: {} } " 

```


Note that somehow the `reply_markup` was empty **even though the function didn't have any async calls in it**. I spent like an hour trying to find an issue. 

It is super logical that the function could be awaitable, I have no idea why it can't do that. This is not intuitive and can potentially cause tons of misunderstanding.

**Comment by ejnshtein** [comment]
async always return Promise
