### ISSUE TITLE
how to use composer with in time range?

### ISSUE THREAD

**Issue by mo7deve** [telegraf/telegraf#722]
Hey 
I just want to use composer in specific time range, so when time ends this composer functions won't be active 

```
const schedule = require('node-schedule')
let startTime = new Date()
startTime.setHours(3, 0, 0)
let endTime = new Date()
endTime.setHours(5, 0, 0)

const bot = new Telegraf(botData.botToken)
schedule.scheduleJob({ start: startTime, end: endTime, rule: '50 54 3 * * *' }, function() {
          console.log('start here')
          bot.use(Composer.chatType('channel', ChannelComposer))
})
bot.use(Composer.chatType('private', Composer.aclAdminClient(Number(botData.adminChatId), AdminComposer, ClientComposer)))
bot.launch()
```

**Comment by ejnshtein** [comment]
Check time in `Composer.optional(checkTimeFunction, doThisIfTrue)` or in function like this.
It's not recommended to mount handlers while bot is running and you can't control it.

**Comment by dotcypress** [comment]
Agreed with @ejnshtein, dynamic middleware mounting is anti-pattern and may cause undefined behavior.
