### ISSUE TITLE
InlineQuery : how to retrieve results by id?

### ISSUE THREAD

**Issue by ouya99** [telegraf/telegraf#723]
Hello,

I made an inline_query and I am trying to  access the results . 
`bot.on('chosen_inline_result', async (ctx) => {`

But ctx does not hold them and though I have correct **ctx.chosenInlineResult.result_id** to search for my result (to display it), I cannot get access to the original result list given to
  **ctx.answerInlineQuery(results)**
I tried to store the results in a ctx.session variable, but also the ctx.session.results, I cannot access from 
`bot.on('chosen_inline_result', async (ctx) => {`

How to overcome this problem?

Thanks!

**Comment by ejnshtein** [comment]
https://core.telegram.org/bots/inline#collecting-feedback

**Comment by ouya99** [comment]
Problem solved:
You cannot use 'chosen_inline_result' for this. You  must specify reply_markup (if you want a keyboard and input_message_content: { message_text } for your message instead

`        reply_markup: {
          inline_keyboard: [
            [{
              text: 'Like this item 👍',
              callback_data: 'likeitem'
            }]
          ]
        },
        input_message_content: {
          message_text: markdown,
          parse_mode: 'Markdown'
        }`
