### ISSUE TITLE
Unresolved variable ctx.state

### ISSUE THREAD

**Issue by littlegamer757** [telegraf/telegraf#724]
Hello,

everytime I try to write something like `ctx.state.role`, I get an "unresolved variable state" error. Anything else works fine, my IDE is IntelliJ Ultimate 2019.2.

I'm sorry if this is not the right place for things like this, but I didn't know what to do anymore after all my research didn't end so well.

Can anybody help me?

**Comment by ejnshtein** [comment]
Send code snippet please

**Comment by littlegamer757** [comment]
Has no need anymore. Thank you anyways.
