### ISSUE TITLE
List of Telegraf-based bots

### ISSUE THREAD

**Issue by bukhalo** [telegraf/telegraf#727]
I suggest adding a list of repos with Telegraf-based Telegram bots to the readme, so that new Telegraph users can better understand how to use Telegraph on large projects, organize their project structure well, etc.

**Comment by ejnshtein** [comment]
Isn't that what you was looking for - https://telegraf.js.org ?

![image](https://user-images.githubusercontent.com/18352350/63064908-60705c80-bf0c-11e9-97e9-e355498832c6.png)

**Comment by bukhalo** [comment]
@ejnshtein oops, yes. I do not know how I did not see this section in the documentation)
