### ISSUE TITLE
Telegraf: "reply" isn't available for "chosen_inline_result::"

### ISSUE THREAD

**Issue by andrey-furman** [telegraf/telegraf#728]
Node.js v: v12.6.0
OS: MaxOS 10.14.6
Can't make any reply for "chosen_inline_result" action.
Logged ctx, all the necessary functions are present:
http://joxi.ru/YmEGM1aHwo5WlA

bot.on('chosen_inline_result', async ctx => {
  await ctx.reply('hello, world')
})

**Comment by dotcypress** [comment]
Not a bug because [chosen_inline_result](https://core.telegram.org/bots/api#choseninlineresult) doesn't contains any information about chat.

**Comment by andrey-furman** [comment]
Ok, thanks for response!
