### ISSUE TITLE
Accessing context from the node-cron function

### ISSUE THREAD

**Issue by Raingerlina** [telegraf/telegraf#730]
Hello!

I have difficulties with accessing telegram context from the node-cron function.
What I want to achieve:
```
var cron = require('node-cron');
 
cron.schedule('* * * * *', () => {
  ctx.session.variable = 'something';
  ctx.telegram.sendMessage(chatID, message);
  <..>
});
```

You got a general idea. Is it possible or I should look in another direction? The main goal is to periodically execute something. Right now it looks like this:
```
bot.on('text', (ctx) => {
    if ((ctx.message.date - ctx.session.variableWithTimestamp) > 3600) {
    ctx.session.variableWithTimestamp += 3600;
    //do something
  }
})
```
and I understand that there should be much better way to perform it

**Comment by igormatos** [comment]
Some doubt here

**Comment by dotcypress** [comment]
@Raingerlina context is a short-lived and valid only during update processing. 

For sending messages from any kind of a queues/schedulers use `Telegram` instance. 
And you can access to session directly, without context.

**Comment by kiwikern** [comment]
> And you can access to session directly, without context.

How can you access the session directly without a context? I know how to create the session key but I can't access the session storage.

**Comment by Raingerlina** [comment]
```
const redisSession = new RedisSession() // create an instance
var localSession; // in this case I declare a variable so I could work with session intself and then save it lately


await redisSession.getSession(SESSION_KEY).then(session => {
  localSession = session;
});
/* replace SESSION_KEY with your key. For example, if you have

| const session = new RedisSession({
|   getSessionKey: (ctx) => {
|     if (!ctx.chat) {
|       return
|     }
|     return '3847384:1203123'
|   }
| })
|  bot.use(session)

then your SESSION_KEY is equal to '3847384:1203123'. 
If you have something like ctx.message.chat.id in declaring session, then you need to manually retrieve needed key and insert it here.*/

// do stuff with local Session here

redisSession.saveSession(SESSION_KEY, localSession);
```

**Comment by Piterden** [comment]
I have a custom session key the [next way](https://github.com/Piterden/chessbot/blob/master/src/index.js#L35-L39):
```js
bot.use(session({
  property: 'game',
  getSessionKey: (ctx) =>
    (ctx.callbackQuery && ctx.callbackQuery.inline_message_id) ||
    (ctx.from && ctx.chat && `${ctx.from.id}:${ctx.chat.id}`),
}))
```

**Comment by Raingerlina** [comment]
As far as I understand you still need to clarify the session key manually in order to access it outside the context.
Because otherwise how would the redis itself  know where to retrieve and put the information
