### ISSUE TITLE
Order in which messages are sent

### ISSUE THREAD

**Issue by federico-github** [telegraf/telegraf#74]
How can I ensure that a message is sent only after another?

**Comment by dotcypress** [comment]
Hey.

All bot method returns Promise. Just wait before sending second message.

```js
bot.command('start', (ctx) => {
  ctx.reply('First message').then(() => ctx.reply('Second message').)
})
```

Async example(Babel or node 7.x required)
```js
bot.command('start', async (ctx) => {
  await ctx.reply('First message')
  await ctx.reply('Second message')
})
```

PS: Sometimes Telegram sends messages in wrong order, be careful.

**Comment by der-dirk** [comment]
Hi,
i followed your suggestion using the await but still get messages in the wrong order. I had a previous PHP version of my bot using self written (ok self copied :) ) communication code and the order was always correct. Moreover I used a webhook.

So do you know if a webhook is less prone to messages getting mixed up by telegram?

Thanks,
Dirk
