### ISSUE TITLE
Extra.caption() is not a function!

### ISSUE THREAD

**Issue by vasilisach** [telegraf/telegraf#741]
I want to send a photo and use next code:

import Telegraf from 'telegraf'
import Extra from 'telegraf/extra'

let Bot = new Telegraf(token);
Bot.catch((err) => {
  console.log('Bot connection error:', err)
})

Bot.telegram.setWebhook('some url')

Bot.telegram.sendPhoto(chatId, fileLink, Extra.caption('some text'))

And I get error: TypeError: Extra.caption is not a function

**Comment by sjinks** [comment]
This was fixed in b976466c
