### ISSUE TITLE
Sending animated webp from local file

### ISSUE THREAD

**Issue by shobhitg** [telegraf/telegraf#742]
I am trying to send an animated webp from a local file.
Here is the relevant code:
```
  ctx.replyWithDocument({
    source: fs.readFileSync('./out.webp')
  });
```

But the file doesn't show up as an actual animated webp. Instead it shows up as a document like this:

![Screen Shot 2019-08-29 at 12 48 59 PM](https://user-images.githubusercontent.com/440151/63971480-66615400-ca5b-11e9-8c30-9c61105e7f1f.png)

Is there any guidance on how to send animated webp files? Its important to note that the webp file is only available on local file system, and I can't use a `url`, else I get this error: `UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported`

**Comment by shobhitg** [comment]
NOTE: I am facing exact same issue with local GIF files.

**Comment by dotcypress** [comment]
@shobhitg try to add `filename' config:
```js
ctx.replyWithDocument({
    source: fs.readFileSync('./out.webp'),
    filename: 'out.webp'
});

**Comment by shobhitg** [comment]
Yes, that worked for iamges.

Unfortunately it seems `webp` animations aren't supported in Telegram itself.
