### ISSUE TITLE
Could not create WizardScene with step handlers only

### ISSUE THREAD

**Issue by mfissehaye** [telegraf/telegraf#748]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.32.0
* Node.js Version: 10.16.3
* Operating System: Windows

## Expected Behavior

I am using WizardScene to step from stage to stage but be able write step handlers in separate files as follows.

Here is my wizard
```
const handlers = require('./handlers')

wizard = new WizardScene('post',
    ctx => ctx.wizard.next(),
    handlers.company_name_handler,
    handlers.category_step_handler,
    handlers.location_handler,
    handlers.employment_type_handler,
    handlers.seniority_level_handler,
    handlers.description_handler,
    handlers.application_method_step_handler,
    handlers.accept_terms_handler,
    handlers.confirmation_handler,
)
```

`handlers` is a folder containing all the handlers in separate files and with an index.js file that exports all the different handlers.
Here is one handler for example:

```
const Composer = require('telegraf/composer')

const handler = new Composer()

handler.on('message', ctx => {
    ctx.reply('Enter the name of the company')
    ctx.wizard.state.company = ctx.message.text
    ctx.wizard.next()
    return ctx.wizard.steps[ctx.wizard.cursor].handler(ctx)
})

handler.on('text', ctx => {
    ctx.reply('Got the company text')
})

// handler.on('text', ctx => {
//     ctx.reply('Got the company text')
// })

handler.use(ctx => {
    ctx.reply('Enter the name of the company')
    ctx.wizard.next()
})

module.exports = handler
```
## Current Behavior

What is the current behavior?

The `.use` middleware block in the handler does not get executed. However the `on('text')` section gets executed. This results in skipping a few stages. For example "Skips to asking category without asking the name of the company which had to be the first step"

**Comment by dotcypress** [comment]
@mfissehaye make sure that you calling next:
```js
handler.use((ctx, next) => {
    ctx.reply('Enter the name of the company')
    return next()
})
```
