### ISSUE TITLE
telegraf location

### ISSUE THREAD

**Issue by fefroyo** [telegraf/telegraf#749]
How to reply location with coords in telegraf bot?

bot.hears(/coords (.+)/, (ctx) => ctx.replyWithLocation(ctx.message.location.latitude+','+ctx.message.location.longitude))

example : /coords 40.123456, 1.123456
 and view map

**Comment by TiagoDanin** [comment]
`ctx.replyWithLocation(111, 222)`

**Comment by fefroyo** [comment]
my code , match[2] don't work

```
bot.hears(/local (.+)/, ({ match, replyWithLocation }, next) => {
    let lat = match[1],
        lon = match[2]
    console.log(match[2])
    console.log(match[1])

    return Promise.all([
         replyWithLocation(lat,lon),
         next()
    ])
})
```

user : /local 40.123, 40.123

lon not defined

**Comment by fefroyo** [comment]
my solution

```
bot.hears(/local (.+)/, ({ match, replyWithLocation }, next) => {
    let coords = match[1].split(',');
    let lat = coords[0]
    let lon = coords[1]

    console.log(lat+','+lon);

    return Promise.all([
         replyWithLocation(lat,lon),
         next()
    ])
})
```

**Comment by TiagoDanin** [comment]
> my code , match[2] don't work
> 
> ```
> bot.hears(/local (.+)/, ({ match, replyWithLocation }, next) => {
>     let lat = match[1],
>         lon = match[2]
>     console.log(match[2])
>     console.log(match[1])
> 
>     return Promise.all([
>          replyWithLocation(lat,lon),
>          next()
>     ])
> })
> ```
> 
> user : /local 40.123, 40.123
> 
> lon not defined

Work, but your regex only has one capture (`(.+)` == match[1]). https://regex101.com/r/hAQJgB/1

[This](https://regex101.com/r/qSQlSY/1/) captures two groups.
