### ISSUE TITLE
Requesting for a file and storing a file

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#75]
Dear Telegraf Developer,

Thank you for your extensive API. I've been using it for a while already and its been really awesome! One of the BEST Telegram Bot APIs for Node out there!

However, I am trying to figure out how I can do this:

When the user does /upload , It will reply with "Upload a file please", after which it will wait for the user can upload a file which would be stored in the Telegram servers.

Would you have any idea how to do this?

At the moment, I can think of one solution, which is to use the 'telegraf-flow' library, which is a middleware package. 

However, is there a way to do this with just the Telegraf API, without needing to use 'telegraf-flow'?

**Comment by dotcypress** [comment]
Hey, thank you!

Yes, [`telegraf-flow`](https://github.com/telegraf/telegraf-flow) is definitely what you need. 👍 

```js
const Telegraf = require('telegraf')
const TelegrafFlow = require('telegraf-flow')
const { Scene } = TelegrafFlow

const flow = new TelegrafFlow()

// Global commands
flow.command('upload', (ctx) => ctx.flow.enter('upload'))

// Upload scene
const uploadScene = new Scene('upload')
uploadScene.enter((ctx) => ctx.reply('Upload a file please'))
uploadScene.on('document', (ctx) => {
  // save document
  ctx.flow.leave()
  return ctx.reply('Thank you')
})
// fallback
uploadScene.on('message', (ctx) => ctx.flow.reenter())

// Scene registration
flow.register(uploadScene)

const app = new Telegraf(process.env.BOT_TOKEN)
app.use(Telegraf.memorySession())
app.use(flow.middleware())
app.use(other middlewares/handlers)
app.startPolling()
```

But if you want more simple solution, you can store in session some flag, like a `uploadPending` and handle it with simple `if...else` logic.

```js
const Telegraf = require('telegraf')

const app = new Telegraf(process.env.BOT_TOKEN)
app.use(Telegraf.memorySession())
app.command('upload', (ctx) =>{
  ctx.session.uploadPending = true
  return ctx.reply('Upload a file please')
})
app.on('message', (ctx, next) =>{
  if(ctx.session.uploadPending){
     return ctx.reply('Upload a file please')
  } 
  return next()
})
app.on('document', (ctx, next) =>{
  if(ctx.session.uploadPending){
     //save document
   ctx.session.uploadPending = false
    return ctx.reply('Thank you')
  } 
  return next()
})
app.on('message', (ctx) => { 
  // Other bot logic
})
app.startPolling()
```

Yay, second example looks weird.

**Comment by joshuaquek** [comment]
Dear dotcypress ,

Thank you, this has been very helpful. 

I'll probably use the second solution that you provided, as it allows more control by using the session to keep track of states.

Once again, thank you so much for the speedy reply!

Regards,
joshua
