### ISSUE TITLE
How can I respond to callbackButton within a wizard?

### ISSUE THREAD

**Issue by zhanhaopeh** [telegraf/telegraf#750]
I'm trying to react to 2 callbackButtons within my wizard, but can't seem to do it. Below is my code:

```
const wizard1 = new WizardScene("wizard1", 
   ctx => {
       ctx.reply(
            Markup.keyboard([
                 Markup.callbackButton("Proceed", "PROCEED"),
                 Markup.callbackButton("Go Back", "BACK")
            ]).extra()
       )
    },
    ... wizard either proceeds or go back ...
);
```

Tried to react to the actions via the following but it doesn't seem to work:

```
bot.action("BACK", ctx => { 
   return ctx.wizard.back();
});

bot.action("PROCEED", ctx => { 
   return ctx.wizard.next();
});
```

My entire script works fine if I pass in return `ctx.wizard.next();` within each ctx, but I just can't seem to go back 1 step.

Can someone kindly advise me on this? Am I getting it right, or should I be passing in an if-else within each ctx in the wizard?

**Comment by zhanhaopeh** [comment]
Hi there, appreciate if you could advise me on this soon...thanks!

**Comment by dotcypress** [comment]
@zhanhaopeh You need to handle actions before wizard itself:


```js
stage.action("BACK", ctx => { 
   return ctx.wizard.back();
});

stage.action("PROCEED", ctx => { 
   return ctx.wizard.next();
});

bot.use(stage);
```
