### ISSUE TITLE
How can I edit message in chosen_inline_result

### ISSUE THREAD

**Issue by hosein2398** [telegraf/telegraf#751]
Hey can I edit message which is sent via InlineQuery after user has chosen one item?
I want to edit the message in `chosen_inline_result` but it seems that `editMessageText` is not a function there.
As is this said here https://core.telegram.org/bots/api#choseninlineresult it should receive a `inline_message_id` which can be used to update the message there, right?

**Comment by hosein2398** [comment]
code:
```
bot.on("chosen_inline_result", ctx => {
  ctx.editMessageText('hey')
});
```
error:
```
 "editMessageText" isn't available for "chosen_inline_result::"
```

**Comment by hosein2398** [comment]
oops I closed by mistake sorry

**Comment by twoperkg** [comment]
As I understood correctly you will get inline_message_id field only if inline keyboard is attached to the message. From telegram bot api: 

>inline_message_id --- Optional. Identifier of the sent inline message. **### Available only if there is an inline keyboard attached to the message**. Will be also received in callback queries and can be used to edit the message.

**Comment by hosein2398** [comment]
Yeah I know about this and I've inline keyboard attached to my messages.
But the problem is that inside of "chosen_inline_result" event I can not edit the message, I get this error:
```
Error: Telegraf: "editMessageText" isn't available for "chosen_inline_result::"
```

**Comment by hosein2398** [comment]
:hushed: Why this is closed?

**Comment by hosein2398** [comment]
As duplicate of https://github.com/telegraf/telegraf/issues/728 ?!

**Comment by dotcypress** [comment]
@hosein2398 yes

**Comment by hosein2398** [comment]
But there should be a way to do this, I know bots which does the same thing, @ilyricsbot does the exact same thing, don't you know any workaround for this?!
If this is not possible how the bot does that? :thinking:

**Comment by hosein2398** [comment]
To edit message you don't need chat_id:
https://core.telegram.org/bots/api#editmessagetext
`chosen_inline_result` will return a `inline_message_id` which is enough to update the message, as said in link.

**Comment by dotcypress** [comment]
@hosein2398 hmm, interesting. I will deep dive this issue later today.

**Comment by dotcypress** [comment]
@hosein2398 fixed version of library will be available today. Thank you for cooperation.

**Comment by hosein2398** [comment]
@dotcypress This would be great. Thanks your support.
