### ISSUE TITLE
How to add inline options to sendPhoto?

### ISSUE THREAD

**Issue by DeusNexus** [telegraf/telegraf#758]
I want to send a photo with caption and then have the user click two buttons saying "Like"/"Dislike".
Is it possible to make these two buttons send with the photo as a whole or will they be send on a seperate message?

This is what I'm using now. Where should I add inline option?
ctx.replyWithPhoto({url: `${photo_url}`}, Extra.caption(my_photo_caption).HTML());

**Comment by twoperkg** [comment]
This should do what you need.

const keyboard = Markup.inlineKeyboard([
    Markup.callbackButton("Like", "opinion: like"),
    Markup.callbackButton("No", "opinion: no")
])

bot.command("photo", ctx => {
    ctx.replyWithPhoto("http://www.quoteambition.com/famous-success-quotes-sayings/", Extra.load({caption: "Success"}).markup(keyboard))})
