### ISSUE TITLE
VSCode intelliSense isn't working with telegraf

### ISSUE THREAD

**Issue by foodornt** [telegraf/telegraf#763]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.32.0
* Node.js Version: 8.11.3
* Operating System: Windows 10

## Expected Behavior

Showing hints and autocompleting code

## Current Behavior

Not showing hints for telegraf.js, it works for any other node.js module

**Comment by foodornt** [comment]
## Temporary solution
Go to \node_modules\telegraf\typings\index.d.ts
Change the last line to be `export = Telegraf` instead of `export default Telegraf`

I'm not too sure about it, please let me know if this causes any further issues.

**Comment by FSou1** [comment]
@foodornt Thx, it works

**Comment by SwapnilSoni1999** [comment]
not working :(

**Comment by wojpawlik** [comment]
@foodornt on what code you expected autocompletion but didn't get it?

**Comment by IscoV** [comment]
> 
> ## Temporary solution
> 
> Go to \node_modules\telegraf\typings\index.d.ts
> Change the last line to be `export = Telegraf` instead of `export default Telegraf`
> 
> I'm not too sure about it, please let me know if this causes any further issues.

Doesn't work

**Comment by SwapnilSoni1999** [comment]
> > ## Temporary solution
> > Go to \node_modules\telegraf\typings\index.d.ts
> > Change the last line to be `export = Telegraf` instead of `export default Telegraf`
> > I'm not too sure about it, please let me know if this causes any further issues.
> 
> Doesn't work

from latest update you can try 
```
const Telegraf = require('telegraf').default;
```
then intellisense will work and module too

**Comment by IscoV** [comment]
> > > ## Temporary solution
> > > Go to \node_modules\telegraf\typings\index.d.ts
> > > Change the last line to be `export = Telegraf` instead of `export default Telegraf`
> > > I'm not too sure about it, please let me know if this causes any further issues.
> > 
> > Doesn't work
> 
> from latest update you can try 
> ```js
> const Telegraf = require('telegraf').default;
> ```
> then intellisense will work and module too

i will try, thanks

**Comment by IscoV** [comment]
> > > ## Temporary solution
> > > Go to \node_modules\telegraf\typings\index.d.ts
> > > Change the last line to be `export = Telegraf` instead of `export default Telegraf`
> > > I'm not too sure about it, please let me know if this causes any further issues.
> > 
> > Doesn't work
> 
> from latest update you can try 
> ```js
> const Telegraf = require('telegraf').default;
> ```
> then intellisense will work and module too

Work perfectly
