### ISSUE TITLE
ctx won't work as intended after coupling or different algorithm

### ISSUE THREAD

**Issue by hanamiyuna** [telegraf/telegraf#766]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.32.0
* Node.js Version: v12.10.0
* Operating System: macOS Mojave 10.14.6

## Expected Behavior

`ctx.reply` and `ctx.answerInlineQuery` should work like the way that this function can be executed among you call it directly.

## Current Behavior

ctx.reply() and ctx.answerInlineQuery() won't send the data out to Telegram, so my bot gets nothing. I was thinking about one error I have got long time ago that the node is telling me   
```
console.log is not a function
```   
or something like   
```
console is not defined
```   
which those problems were caused by the mass coupling of many callbacks inside the codes.
So I tried to move the callback directly into the function where Bot.on() is, for some specific situations that the ctx.answerInlineQuery() will work, but ctx.reply() won't.
Even inside the app.js where I directly use the ctx, the ctx.reply() and the ctx.answerInlineQuery won't work as they should be. I tried many times for different data input. It's even related to the data you put inside.
Such as the strings that contains `"` quotes, it might not be able to process it.
Such as the array that contains too many things, it might not be able to process it.
Even for the examples I have mentioned above, there is still exception that they will work based on the different algorithm.

## Failure Information (for bugs)

There is no such failure or information about the wired exception that I am experiencing right now. However I tried to catch the error by using catch from Promise, I still go nothing.

### Steps to Reproduce

For the inlineQuery
```
async functioon inlineDistributor(ctx) {
    let args = []
        args.push(ctx)

        // compoData.inline returns the __array__ of plugin reflact and function instance names
        var method = compoData.inline
        for (let i of method) {
            let detail = []
            const idx = method.indexOf(i)
            try {

                // The Reflact calls the inline processing function
                // From here I couldn't do anything by just pass the ctx in and 
                // ctx.anwerInlineQuery inside of it. So I changed it 
                // to return a value for the __array__ of InlineQueryResultArticle
                const res = await Reflect.apply(method[idx].instance, undefined, args)
                detail.push(res)
             } catch (err) {
                Log.fatal(err)
             }
        return detail
    }
}
Bot.Telegram.Bot.on("inline_query", async ctx => {
    let result = await inlineDistributor(ctx)
    ctx.answerInlineQuery(result, {cache_time: 10})
})
```

The second one for reply is kind of wired somehow
```
// This won't reply anything where it is located under app.js
Bot.Telegram.Bot.on("text", async (ctx) => {
    ctx.replyWithChatAction("typing")
    Bot.Message.Nlp.tag(ctx, ctx.message.text).then(res => {

        // The res is a __string __
        let text = res
        if(text != undefined) {
            ctx.reply(text).then(res => {
                Log.debug("Message replied")
            }).catch(err => {
                Log.fatal(err)
            })
        }
    })
})
```

I figured out a way to fix this by using another way of doing things which is like:
```
Bot.Telegram.Bot.on("text", async (ctx) => {

    // Insert this line and it can be triggered now
    ctx.replyWithChatAction("typing")

    Bot.Message.Nlp.tag(ctx, ctx.message.text).then(res => {
        let text = res
        if(text != undefined) {
            ctx.reply(text).then(res => {
                Log.debug("Message replied")
            }).catch(err => {
                Log.fatal(err)
            })
        }
    })
    Bot.Message.messagectl.logMsg(ctx)
    Bot.Message.Message.hears(ctx)
})
```

__Note: Log is from log4js__

### Failure Logs

Nothing

**Comment by dotcypress** [comment]
@hanamiyuna make sure, that you call all async methods with `await`.

**Comment by hanamiyuna** [comment]
I do know the way `await` does, however sometimes `ctx` requires `.then(callback)` to have the value to reply on
