### ISSUE TITLE
How to remove emoji from ctx.message.text?

### ISSUE THREAD

**Issue by Fazendaaa** [telegraf/telegraf#77]
I'm having some difficulties with ctx.message.text. When the user sends 'Gantz:o' as the argument, my bot receives :o as a emoji. How can I correct this?

**Comment by dotcypress** [comment]
Hey.

Could you provide more info?

**Comment by Fazendaaa** [comment]
@dotcypress Sure. Here's my code:
```javascript
bot.command( 'search', ctx => {
	const movie =  ctx.message.text.split(' ').slice( 1 ).join(' ')
	
	console.log( movie )

	imdb.get( movie ).then( response => ctx.reply( response.imdburl ) )
	.catch( console.log( 'Reject promise in search function' ) )
} )
```
When the user type '/search gantz:o', const movie turns out to be 'gantz😨'. And I want to be gantz:o. In others words, I don't want my string in unicode.

**Comment by dotcypress** [comment]
I suppose reason is Telegram app autoreplace feature.

See Telegram Desktop settings screen for examlpe:
<img width="424" alt="screen shot 2017-03-03 at 11 25 07 am" src="https://cloud.githubusercontent.com/assets/1333916/23565853/237ce664-0004-11e7-8111-44ecff5af81d.png">

**Comment by Fazendaaa** [comment]
@dotcypress thanks.

So far I'm using this function:

```javascript
function messageToString( message ) {
	return Buffer
		  .from( message, 'ascii' )
		  .toString( 'ascii' )
		  .replace( /(?:=\(|:0|:o|: o|: 0)/, ': o' )
}
```

**Comment by 0xMDIV** [comment]
> @dotcypress thanks.
> 
> So far I'm using this function:
> 
> ```js
> function messageToString( message ) {
> 	return Buffer
> 		  .from( message, 'ascii' )
> 		  .toString( 'ascii' )
> 		  .replace( /(?:=\(|:0|:o|: o|: 0)/, ': o' )
> }
> ```

Thank you so much for that Solution fixed my bot 👍
