### ISSUE TITLE
How can I clear the session (invalidate cache) of all users?

### ISSUE THREAD

**Issue by Ramin-Bateni** [telegraf/telegraf#771]
I want invalidate the following caches

- **All session items** of **all users**:
- **Some session items** of **all users**

So, How can I **access the session store of all users** and doing this job?

I use this code:
```
const session = require('telegraf/session');
bot.use(session());

bot.command('clear', (ctx: any) => {
     // const currentUserSession = ctx.session;
});
```

**Comment by dotcypress** [comment]
@Ramin-Bateni you can use your own store with session middleware:

```js
const session = require('telegraf/session');
const store = new Map();
bot.use(session({ store }));

bot.command('clear', (ctx: any) => {
    store.clear();
});
```

**Comment by Ramin-Bateni** [comment]
> @Ramin-Bateni you can use your own store with session middleware:
> 
> ```js
> const session = require('telegraf/session');
> const store = new Map();
> bot.use(session({ store }));
> 
> bot.command('clear', (ctx: any) => {
>     store.clear();
> });
> ```

@dotcypress , Thank you for your reply.

After `store.clear();` the store variable become empty but it dose not any effect on the content of `ctx.session`. Actually `store.clear()` dose not clear `ctx.session`.😕

**Comment by dotcypress** [comment]
@Ramin-Bateni actually all session data gonna be lost except for current session. To make a full cleanup just clear current session state:
```js
const session = require('telegraf/session');
const store = new Map();
bot.use(session({ store }));

bot.command('clear', (ctx: any) => {
  ctx.session = null    
  store.clear();
});
```
