### ISSUE TITLE
It is not clear how to setup webhook + express

### ISSUE THREAD

**Issue by nastakhov** [telegraf/telegraf#773]
As I see in example express-webhook-bot.js there is no invocation of 'bot.launch()' method.
Is it correct? 

Struggling to run telegram+nest.js (there is expressjs under belt).

If i run bot.launch() with webhook options it tries to create its own http server, not use my express.js

**Comment by ailinykh** [comment]
Yes, that is correct.
`bot.launch()` makes a long poll connection or listening server on localhost.
in _express.js_ case you just passing an _update_ you received to bot, _express_ do all the job
