### ISSUE TITLE
sendPhoto/sendDocument fails with Request Entity Too Large error

### ISSUE THREAD

**Issue by pshanoop** [telegraf/telegraf#774]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.32.0
* Node.js Version: v10.16.3
* Operating System: Debian sid

## Expected Behavior
photo is sent and a message id created if the file size is under 50Mb. 

## Current Behavior
Return error saying file is too large even though the file size is 203KB.

Note: that this file with same `chat_id` and bot token worked fine using `curl` telegram API call. 
```bash
curl -F chat_id="${CHAT_ID}" -F photo=@"./cat.png" -F caption="test"  https://api.telegram.org/bot${TG_TOKEN}/sendPhoto
```

What is the current behavior?
Return error saying file is too large even though the file size is 203KB.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
bot.js
```javascript
const Telegraf = require("telegraf");

const botToken = 'TG_TOKEN';
const bot = new Telegraf(botToken);

module.exports = bot;
```

tele.js
```javascript

const { telegram } = require('./bot.js'); 
const fs = require('fs');

const san_id = 'personal chat_id given';

(async () => {
  try {
      console.log("Running....");
      let photo = fs.readFileSync('cat.png');
      let test = await telegram.sendDocument(san_id, photo, {captions:'blah'});
      console(test);
  } catch(e) {
    console.log(e);
  }
})();

```

### Failure Logs

```
{ Error: 413: Request Entity Too Large
    at buildConfig.then.then.then.then (/appoint/node_modules/telegraf/core/network/client.js:263:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 413,
  response:
   { ok: false,
     error_code: 413,
     description: 'Request Entity Too Large' },
  description: 'Request Entity Too Large',
  parameters: {},
  on:
   { method: 'sendPhoto',
     payload:
      { chat_id: 'chat_id',
        document:
         <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 05 3b 00 00 01 dc 08 06 00 00 00 19 44 7e 7f 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 20 00 ... >,
        captions: ' fdss' } } }
```

**Comment by pshanoop** [comment]
It worked as expected, When call the function this way, 
```
let test = await telegram.sendPhoto(san_id, {source: photo}, {caption:'test'});
```

Documentation gives another idea. https://telegraf.js.org/#/?id=sendphoto  
What is the expected way to call this function  ?

**Comment by athimannil** [comment]
@pshanoop I had the similar issue for sending video message

**Comment by zero-t4** [comment]
the same

**Comment by dotcypress** [comment]
With `Buffer` you must use `telegram.sendPhoto(san_id, {source: photo})`, not `telegram.sendPhoto(san_id, photo)`.

[Sending files with Telegraf](https://telegraf.js.org/#/?id=working-with-files)

**Comment by viartemev** [comment]
@dotcypress Hello, I have the same issue, but only on big files (~ 66Mb).
```
telegram
    .sendVideo("id", {source: fs.createReadStream("./asset_1800k.mp4")});
```
Is there differenct betweend sending big and small files?
