### ISSUE TITLE
Bot does not working in group chat

### ISSUE THREAD

**Issue by RodionCoach** [telegraf/telegraf#775]
## Context

I have some problem with bot after integrating telegraf with koa, he cant working in group chat, when I run it locally its work ok in long poll mode.
Ive deploy my app on heroku, here below in attachments you can find screenshot of heroku log, When Im sending some command to bot in privat chat Ive normally behavior (answer with code 200) but when Im sending some command to bot in group chat Im became trouble (answer with code 404) .
I guess this problem is due '/secret-path' - I do not understand how to work with him.
I`ve used this example:
https://github.com/telegraf/telegraf/blob/develop/docs/examples/koa-webhook-bot.js
Please, give me some solution. Thanks!

* Telegraf.js Version: 3.32.0;
* Node.js Version: 10.16.3;
* Operating System: Window 10;

## Expected Behavior

The bot should be working not only in private chat (like just I and bot), and in group chat too.

### Failure Logs

![66715262-c58be580-edc9-11e9-95fe-4b8ccf8bb102](https://user-images.githubusercontent.com/25160654/66783405-813f3900-eee0-11e9-871d-b554f5c78ba9.jpg)
![66715325-c1ac9300-edca-11e9-911a-bb9f9e8e40ff](https://user-images.githubusercontent.com/25160654/66783407-813f3900-eee0-11e9-9031-bf3ec20a498a.png)

**Comment by andbul** [comment]
Have you disabled the privacy mode for your bot with botfather?

**Comment by RodionCoach** [comment]
> Have you disabled the privacy mode for your bot with botfather?

Yep, you can see it on the second screenshot. "Current status is: DISABLED"

**Comment by dotcypress** [comment]
Hey @RodionCoach

For handling group/supergroup commands(/start@your_bot) witout calling `launch` you need to provide bot username with any of following methods.

```js
// Provide with options
const app = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})

// Or you can get username from Telegram server
const app = new Telegraf(process.env.BOT_TOKEN)
app.telegram.getMe().then((botInfo) => {
  app.options.username = botInfo.username
})
```

**Comment by RodionCoach** [comment]
> Hey @RodionCoach
> 
> For handling group/supergroup commands(/start@your_bot) witout calling `launch` you need to provide bot username with any of following methods.
> 
> ```js
> // Provide with options
> const app = new Telegraf(process.env.BOT_TOKEN, {username: 'your_bot'})
> 
> // Or you can get username from Telegram server
> const app = new Telegraf(process.env.BOT_TOKEN)
> app.telegram.getMe().then((botInfo) => {
>   app.options.username = botInfo.username
> })
> ```

Much thanks to you! It's working)
