### ISSUE TITLE
Conflict: terminated by other getUpdates request

### ISSUE THREAD

**Issue by vrenda16** [telegraf/telegraf#779]
Hi guys i have this issue when i deploy my bot in Now Zeit v2."Conflict: terminated by other getUpdates request; make sure that only one bot instance is running". My structure is:

const telegraf =require...
const bot = new telegraf
bot.start(..){...}
bot.actiont(...){...}
....
bot.launch();
module.exports= bot;

Someone can help me with some tips.

**Comment by dotcypress** [comment]
@vrenda16 try to switch to webhook handler.
