### ISSUE TITLE
Error: 400: Bad Request: there is no administrators in the private chat

### ISSUE THREAD

**Issue by agnoam** [telegraf/telegraf#782]
## Context
* Telegraf.js Version:
"telegraf": "^3.32.0"

* Node.js Version:
v12.13.0

* Operating System:
Heroku node.js server

## Expected Behavior
My bot needs to check if the sender is an admin
By this code:
`const isAdmin: boolean = admins.some(admin => admin.user.id === ctx.from.id);`

## Current Behavior
Telegraf library throws an exception that no received when I run it on my workstation.
but when I deploy it to Heroku its throws the exception.

The exception is:
````
Error: 400: Bad Request: there is no administrators in the private chat
at /app/node_modules/telegraf/core/network/client.js:263:17
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
````

**Comment by dotcypress** [comment]
@agnoam before checking for admin, make sure that update comes from group chat.
