### ISSUE TITLE
ctx.replyWithMarkdown() returning undefined

### ISSUE THREAD

**Issue by agnoam** [telegraf/telegraf#788]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: "^3.32.0"
* Node.js Version: v12.13.0
* Operating System: Heroku

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?
````
const newWelcomeMessage: Message = await ctx.replyWithMarkdown(messageContent, {
    disable_web_page_preview: true,
    reply_markup: inlineKeyboard
});
````

`newWelcomeMessage.message_id` is `undefined`.

Failure Message:
````{
2019-10-31T17:05:07.200769+00:00 app[web.1]:   webhook: true,
2019-10-31T17:05:07.200771+00:00 app[web.1]:   details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
2019-10-31T17:05:07.200772+00:00 app[web.1]: }
````

## Expected Behavior
`newWelcomeMessage.message_id` is not `undefined`.

**Comment by dotcypress** [comment]
You need to disable webhook reply feature:
```js
const bot = new Telegraf(process.env.BOT_TOKEN, { telegram: { webhookReply: false } })
``` 

https://core.telegram.org/bots/api#making-requests-when-getting-updates
