### ISSUE TITLE
the website is not loading

### ISSUE THREAD

**Issue by waotzi** [telegraf/telegraf#789]
im sorry if this is not the right place to report this

when trying to load telegraf.js.org nothing is loaded
in the console it says

Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/docute@3/dist/docute.js”.
ReferenceError: docute is not defined

when i follow the jsdelivr cdn we page is Unable to connect

**Comment by dotcypress** [comment]
@waotzi I can't reproduce right now, could you recheck?

**Comment by waotzi** [comment]
@dotcypress the website works again, i guess jsdelivery was down for some time

**Comment by waotzi** [comment]
hmmm i dno, for me it the jsdelvire document wont load :/

**Comment by waotzi** [comment]
is there a way to clone the website repository locally so i can manually add the doctue file?

**Comment by waotzi** [comment]
im trying to inject the docute script manually, but still haven't figured it out...
its a bit frustrating that jsdelvr has to be used which does not seem to work for my mobile network - im sure im not the only one who can't us the site

**Comment by waotzi** [comment]
well thanks for the help... without a working documentation this is useless...
