### ISSUE TITLE
How to reply_markup?

### ISSUE THREAD

**Issue by Fazendaaa** [telegraf/telegraf#79]
My inline bot works fine until I tried to add reply_markup to it.
``` javascrtipt
bot.on( 'callback_query', ctx => {
	const response = ctx.update.callback_query
	return ctx.answerCallbackQuery( response.id, response.data )
} )

function replyButton( plot ) {
	return Markup.inlineKeyboard([
		Markup.callbackButton( 'Plot', plot )
	] )
}

function replyInline( data ) {
	const poster = ( null != data.poster ) ? data.poster : 'http://bit.ly/2moqQnT'
	const plot = verifyData( data.plot, '' )

	return {
		id: data.imdb.id,
		title: data.title,
		type: 'article',
		input_message_content: {
			message_text: replyMessage( data ),
			parse_mode: 'Markdown',
		},
		reply_markup: replyButton( plot ),
		description: plot,
		thumb_url: poster,
	}
}
```

I wanna know why isn't working. I tried the way in keyboard examples but didn't work, that's why I came up with this 'solution' but isn't working either. What is the problem?

p.s.: btw, the 'plot' variable is a String.

**Comment by dotcypress** [comment]
Hey.

Try to convert your markup to string:
```js
reply_markup: JSON.stringify(replyButton( plot ))
```

**Comment by notmedia** [comment]
@Fazendaaa Hi. I have had the similar issue. I suppose that the replyButton function returns not the reply_markup object.

console.log your function result: 
```js
 Markup { inline_keyboard: [ [ [Object] ] ] }
```

So maybe you should try to do this:
```js
reply_markup: replyButton( plot ).inline_keyboard
```

**Comment by Fazendaaa** [comment]
@notmedia Same issue again:
```
Error: 400: Bad Request: field "reply_markup" must be of type Object
    at buildPayload.then.then.then.then (/home/farm/Documents/imdb_bot_telegram/node_modules/telegraf/lib/network/client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 400,
  description: 'Bad Request: field "reply_markup" must be of type Object',
  retryAfter: undefined,
  migrateToChatId: undefined }
```

**Comment by notmedia** [comment]
@Fazendaaa Okay. And what if you create keyboard this way:

```js
  return Telegraf.Extra
    .markup((m) =>
      m.inlineKeyboard([
          m.callbackButton('Plot', plot)
      ])
    );
````

Then you will get an Extra object, and you should do this:

```js
reply_markup: replyButton( plot ).reply_markup
```

**Comment by Fazendaaa** [comment]
@notmedia same problem as before :(

**Comment by notmedia** [comment]
@Fazendaaa Found it. You have an unexpected comma:

```js
input_message_content: {
			message_text: replyMessage( data ),
			parse_mode: 'Markdown', // <- Here
},
````

After fix this try my previous answer.

**Comment by Fazendaaa** [comment]
@notmedia you're totally right! I didn't even notice... hahahaha -- but now other problem appeared:
```
Error: 400: Bad Request: URL_INVALID
      at buildPayload.then.then.then.then (/home/farm/Documents/imdb_bot_telegram/node_modules/telegraf/lib/network/client.js:98:17)
      at process._tickCallback (internal/process/next_tick.js:109:7)

Failed to process updates. { Error: 400: Bad Request: URL_INVALID
    at buildPayload.then.then.then.then (/home/farm/Documents/imdb_bot_telegram/node_modules/telegraf/lib/network/client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 400,
  description: 'Bad Request: URL_INVALID',
  retryAfter: undefined,
  migrateToChatId: undefined }
```
I thought that the URL was optional. And I still using my original code because you're previous answer game this error:

```
Error: 400: Bad Request: BUTTON_DATA_INVALID
    at buildPayload.then.then.then.then (/home/farm/Documents/imdb_bot_telegram/node_modules/telegraf/lib/network/client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 400,
  description: 'Bad Request: BUTTON_DATA_INVALID',
  retryAfter: undefined,
  migrateToChatId: undefined }

```

**Comment by notmedia** [comment]
Can you console.log the plot variable? I think the problem is there

Here is working sample: 

```js
bot.on('inline_query', (ctx) => {  
  return ctx.answerInlineQuery([replyInline('a')])
})

function replyButton( plot ) {  
 return Telegraf.Extra
    .markup((m) =>
      m.inlineKeyboard([
          m.callbackButton('Plot', plot)
      ])
  );
}

function replyInline( data ) {
  return {
    id: data,
    title: data,
    type: 'article',
    input_message_content: {
      message_text: '*REPLY INLINE*',
      parse_mode: 'Markdown'
    },
    reply_markup: replyButton('test').reply_markup
  }
}
```

**Comment by Fazendaaa** [comment]
@notmedia I can, my plot variable is always a String because:
```javascript
function verifyData( data, unit ) {
	return ( null != data && undefined != data ) ?
		   `${data}${unit}` : 'Not avaliable'
}
```

**Comment by notmedia** [comment]
@Fazendaaa  I think the error in your code, not in telegraf. Use my working example, and try to find an error.

For example, pass to replyButton function any string like:

```js
reply_markup: replyButton('testString').reply_markup
```

If the error not occurs then the problem 100% is in your implementation.

**Comment by Fazendaaa** [comment]
@notmedia you're totally right. I will see what's going on here. Thanks for everything :+1:

**Comment by Fazendaaa** [comment]
I discovered the problem. The plot string is too big.

**Comment by dotcypress** [comment]
@notmedia thank you for your help 😉

**Comment by Fazendaaa** [comment]
@notmedia me again. I was reading the Telegram API when i see this:
```
text	String	Optional	Text of the notification. If not specified, nothing will be shown to the user, 0-200 characters
```
in answerCallbackQuery. So I tried to sent a 200 characters string in your working example in this discussion. Didn't work. Do you know why?

**Comment by notmedia** [comment]
@Fazendaaa  Hello. Are you shure tha you use `answerCallbackQuery` method instead of `answerInlineQuery`?

Explain please what means `Didn't work`. What error did you get? Or nothing happens?

**Comment by Fazendaaa** [comment]
@notmedia Yes, I used the code found in /examples:
```javascript
bot.action( /.+/, (ctx) => {
 	return ctx.answerCallbackQuery( `${ctx.match[0]}` )
})
```
And I used this test string:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
```
And gave me this error:
```
Error: 400: Bad Request: BUTTON_DATA_INVALID
    at buildPayload.then.then.then.then (/home/farm/Documents/imdb_bot_telegram/node_modules/telegraf/lib/network/client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 400,
  description: 'Bad Request: BUTTON_DATA_INVALID',
  retryAfter: undefined,
  migrateToChatId: undefined
```

**Comment by Fazendaaa** [comment]
@notmedia Me again, any news?

**Comment by notmedia** [comment]
@Fazendaaa Sorry, forgot about you :(

Hm. I tried to send and it worked fine
```js
const mainMenu = Telegraf.Extra
  .markdown()
  .markup((m) => m.inlineKeyboard([
    [m.callbackButton('A', 'a')],
    [
      m.callbackButton('B', 'b'),
      m.callbackButton('C', 'c')
    ]
  ]));

bot.command('test', (ctx) => {
  return ctx.reply('HI', mainMenu);
});

bot.action(/.+/, (ctx) => {
  return ctx.answerCallbackQuery('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut');
});
```

**Comment by Fazendaaa** [comment]
Hmmm, How can I make my bot show a message like this when the user pressed a button?

![149097883277737](https://cloud.githubusercontent.com/assets/12137236/24560196/1048e302-1618-11e7-8410-b0e9b3bd2dc8.png)

**Comment by notmedia** [comment]
@Fazendaaa 

The third parameter in answerCallbackQuery should be true
Read the docs [here](http://telegraf.js.org/telegram.html#answercallbackquery)

```js
return ctx.answerCallbackQuery('Your text', undefined, true);
```

**Comment by dotcypress** [comment]
@Fazendaaa @notmedia be careful, `answerCallbackQuery` signature will be changed in next major release.

`ctx.answerCallbackQuery('Your text', undefined, true)` will be `ctx.answerCallbackQuery('Your text', true)`. 

We will split this method to `answerCallbackQuery` and `answerGameQuery`
Check out new documentation on [next](https://github.com/telegraf/telegraf/blob/next/docs/telegram.md#answercallbackquery) branch.

This is only one breaking change in next release, sorry for that, bad API design decision 😞

**Comment by Fazendaaa** [comment]
@dotcypress thanks for this adivice and @notmedia for all the help.

**Comment by Fazendaaa** [comment]
This message occours when I tried to pass any string that has more than 60 characters:
```
Error: 400: Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard

```

**Comment by notmedia** [comment]
@dotcypress Thanks for the notice. Don't worry you do the great job 😉 

@Fazendaaa Where do you pass the string? But firstly I recomend to read the docs and watch code [samples](https://github.com/telegraf/telegraf/tree/next/examples) (the samples are great and there you can find all answers).

**Comment by Fazendaaa** [comment]
@notmedia the samples helped me out a lot, but they don't have the case that I'm looking for. The code idea is that when the user uses inline mode the response has a 200 characters button.

```javascript
bot.action( /.+/, ( ctx ) => {
 	return ctx.answerCallbackQuery( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut', undefined, true )
})

function replyButton( plot ) {
	return Telegraf.Extra
				   .markdown( )
				   .markup((m) =>
				      m.inlineKeyboard([
					      m.callbackButton( 'Plot', plot.substring( 0, 199 ) )
				   ])
	).reply_markup
}

function replyInline( data ) {
	const poster = ( null != data.poster ) ? data.poster : 'http://bit.ly/2moqQnT'
	const plot = ( null != data.plot ) ? data.plot : 'Not avaliable'

	return {
		id: data.imdb.id,
		title: data.title,
		type: 'article',
		input_message_content: {
			message_text: replyMessage( data ),
			parse_mode: 'Markdown'
		},
		reply_markup: replyButton( plot ),
		description: plot,
		thumb_url: poster
	}
}
```

**Comment by dotcypress** [comment]
@Fazendaaa [Telegram docs](https://core.telegram.org/bots/api#inlinekeyboardbutton) says that inline button requires  `1-64 bytes` in `callback_data`

**Comment by Fazendaaa** [comment]
@dotcypress Thanks... But there's a bot, @NoSpoilersBot, that do what I'm trying to do. But I think that who made it use another way.

**Comment by Fazendaaa** [comment]
@dotcypress and @notmedia I finally made it all that I was looking for. The bot is called @Farmoviebot, thanks for advice :)

**Comment by ilhmpy** [comment]
Why i get error 'cannot read properties of undefined (reading 'markdown') when i call Telegraf.Extra.markdown()?
