### ISSUE TITLE
cannot get message after reply to a message

### ISSUE THREAD

**Issue by exoticknight** [telegraf/telegraf#792]
## Context

I used
```javascript
ctx.reply('w', {reply_to_message_id: message_id}).then(console.log)
```
to reply a message, but only got
```javascript
{
 webhook: true,
details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
```
in console.log, not the Message structure, so I can't edit what I sent.
but in another [bot project](https://github.com/soruly/trace.moe-telegram-bot/blob/master/server.js#L243) which use node-telegram-bot-api, it seems that telegram did return the Message back

* Telegraf.js Version: ^3.33.3
* Node.js Version: v12.13.0
* Operating System: macOS 10.15.1

## Expected Behavior

after ctx.reply, get back the Message response as return from telegram

## Current Behavior

get
```javascript
{
 webhook: true,
details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
```

## Failure Information (for bugs)

maybe a bug during processing JSON response?

**Comment by dotcypress** [comment]
Duplicate #788

@exoticknight more info here: https://github.com/telegraf/telegraf/issues/788#issuecomment-548493510

**Comment by exoticknight** [comment]
@dotcypress 
thx! I looked into the source code and found out this hidden(?) rule just now...
this is not a bug, but I think it should be illustrated in the documentation.
