### ISSUE TITLE
Login-bot - ERROR: BOT_DOMAIN_INVALID - Login to the site via bot (telegraf)

### ISSUE THREAD

**Issue by baur** [telegraf/telegraf#793]
Hi,
I'd like to use a bot to login for my site

1) Request phone number 
2) Register via API
3) Get user Token
4) **Login via login button**

[this code](https://github.com/telegraf/telegraf/blob/develop/docs/examples/login-bot.js)
```
Markup.loginButton('Login', 'http://localhost:3000', {
    bot_username: 'my_bot',
    request_write_access: 'true'
```
returns error:
```
Error: 400: Bad Request: can't parse inline keyboard button: Field "request_wr
ite_access" must be of type Boolean
```

this code
```
Markup.loginButton('Login', 'http://localhost:3000', {
    bot_username: 'my_bot',
    request_write_access: true
```
returns error:
```
Error: 400: Bad Request: wrong HTTP URL
```
though http://localhost:3000 is available in my localhost

what means options:
{
    bot_username: 'my_bot',
    request_write_access: true
}
query params or headers?

**Comment by baur** [comment]
Now I'm set real domain

```
Markup.loginButton('Login', 'http://global_available_ip:3000', {
    bot_username: 'my_bot',
    request_write_access: true
  }),

```
>node -v
v12.8.1
>npm -v
6.10.2

, but get next error:

```
C:\baur\node\node-bot>node bot.js

  Error: 400: Bad Request: BOT_DOMAIN_INVALID
      at C:\baur\node\node-bot\node_modules\telegraf\core\network\client.js:281:
17
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
      at async Promise.all (index 0)

Failed to process updates. TelegramError: 400: Bad Request: BOT_DOMAIN_INVALID
    at C:\baur\node\node-bot\node_modules\telegraf\core\network\client.js:281:17

    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 0) {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: BOT_DOMAIN_INVALID'
  },
  description: 'Bad Request: BOT_DOMAIN_INVALID',
  parameters: {},
  on: {
    method: 'sendMessage',
    payload: { chat_id: 525933426, text: 'Hello', reply_markup: [Object] }
  }
}
```

**Comment by tva10** [comment]
Hello @baur. I'm not sure but there is Domain setting in botfather. 
And looks like that it is specifies web login for special domain

**Comment by baur** [comment]
@tva10  yes, you're right, thanks for the tip

**Comment by Fortur** [comment]
> @tva10 yes, you're right, thanks for the tip

I faced the same problem. As I understand it, you need to use setdomain in botfather. But it doesn't work for me. Could you describe in detail how you solved the problem?

**Comment by Fortur** [comment]
I solve this. My bot_username was wrong

**Comment by baur** [comment]
Hi @Fortur, 
Just applied setdomain in botfather
