### ISSUE TITLE
Detect message type i.e. audio, photo, voice etc

### ISSUE THREAD

**Issue by thewayur** [telegraf/telegraf#794]
**How to detect media/document?**

can you please give a very simple code to detect it?
like i want to fetch voice recorded message and save it locally.

**Comment by twoperkg** [comment]
const bot = new Telegraf(config.BOT_TOKEN)

bot.on('voice', ctx => {
  // get voiceObject
const voiceObject =  ctx.message.voice
})

For voice object properties refer to [Telegraf Bot Api](https://core.telegram.org/bots/api#voice)

**Comment by thewayur** [comment]
> const bot = new Telegraf(config.BOT_TOKEN)
> 
> bot.on('voice', ctx => {
> // get voiceObject
> const voiceObject = ctx.message.voice
> })
> 
> For voice object properties refer to [Telegraf Bot Api](https://core.telegram.org/bots/api#voice)

:) thank u,  
i will experiment and close  this question in 2 3 days.

**Comment by thewayur** [comment]
> const bot = new Telegraf(config.BOT_TOKEN)
> 
> bot.on('voice', ctx => {
> // get voiceObject
> const voiceObject = ctx.message.voice
> })
> 
> For voice object properties refer to [Telegraf Bot Api](https://core.telegram.org/bots/api#voice)

ok, finally i am able to get the full link via this code:

```
ctx.telegram.getFileLink(voiceObject.file_id).then( (link) => {
            console.log(link);
        }
        );
```

now, let suppose, user has deleted this voice msg
 can u tell me what will happen after that =>

1. will voice be accessible by bot? for how long?
2. For how long, real file will stay on TELEGRAM SERVER?
3. can i use this file_id to send it to other chats like channel/group(after deleted by user)?

any other FAQs of files (after deletion)?

**Comment by twoperkg** [comment]
1. Yes. It will be accessible. Just save somewhere file_id to use it later.
2. Do not know.
3. I have not tried to send to channel or group but definitely can confirm that u can send to other bot's users who instantiated private chat with the bot.

**Comment by marcopiii** [comment]
It seems that in version `4.x` the `message` object doesn't have a `voice` property anymore. I'm not able to find any reference in the documentation about how to retrieve the voice messages the bot receives.

**Comment by dvornikov-dev** [comment]
@marcopiii solution:
```
import { message } from 'telegraf/filters';
this.bot.on(message('voice'), (ctx) => ctx.reply('Voice message received'));
```
