### ISSUE TITLE
TypeError: Markup.callbackButton is not a function

### ISSUE THREAD

**Issue by jwandekoken** [telegraf/telegraf#795]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.33.0
* Node.js Version: 10.16.3
* Operating System: Ubuntu

## Expected Behavior

Create a inline keyboard

## Current Behavior

Error: TypeError: Markup.callbackButton is not a function

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
My code:

```
const env = require('../.env');
const Telegraf = require('telegraf');
const Extra = require('telegraf/extra');
const Markup = require('telegraf');

const bot = new Telegraf(env.token);

let contagem = 0;

const botoes = Extra.markup(Markup.inlineKeyboard([

  Markup.callbackButton('+1', 'add 1'),
  Markup.callbackButton('+10', 'add 10'),
  Markup.callbackButton('+100', 'add 100'),
  Markup.callbackButton('-1', 'sub 1'),
  Markup.callbackButton('-10', 'sub 10'),
  Markup.callbackButton('-100', 'sub 100'),
  Markup.callbackButton('Zerar', 'reset'),
  Markup.callbackButton('Resultado', 'result')

], { columns: 3 }));

bot.start(async ctx => {
  const nome = ctx.message.from.first_name;
  await ctx.reply(`Seja bem vindo, ${nome}`);
  await ctx.reply(`A contagem atual está em ${contagem}`, botoes);
});


bot.action(/add (\d+)/gi, ctx => {
  contagem += parseInt(ctx.match[1]);
  ctx.reply(`A contagem atual está em ${contagem}`, botoes);
});

bot.action(/sub (\d+)/gi, ctx => {
  contagem -= parseInt(ctx.match[1]);
  ctx.reply(`A vontagem atual está em ${contagem}`, botoes);
});

bot.action('reset', ctx => {
  contagem = 0;
  ctx.reply(`A vontagem atual está em ${contagem}`, botoes);
});

bot.action('result', ctx => {
  ctx.answerCbQuery(`A contagem atual está em ${contagem}`);
});

bot.launch();
```
This feature "Markup.callbackButton" is not supported anymore?

**Comment by jwandekoken** [comment]
My bad. Just found what was missing. Sry about that.

**Comment by ne0c0de** [comment]
Having the same isue. What was the solution @jwandekoken ?

**Comment by nfdevua** [comment]
> Having the same isue. What was the solution @jwandekoken ?

//create inline keyboard
Markup.inlineKeyboard([
    Markup.button.callback("👍", "like"),
    Markup.button.callback("👎", "dislike"),
  ])
  
  //catch callback
 bot.action(/.+/, ctx => {
  return ctx.answerCbQuery(`Oh, ${ctx.match[0]}! Great choice`);
});

**Comment by Juamedrod** [comment]
I hate this kind of things, if you solve it, just solve it and make it public.

**Comment by code-by** [comment]
same issue...

**Comment by MKRhere** [comment]
@code-by See https://github.com/telegraf/telegraf/issues/795#issuecomment-820373720.

**Comment by code-by** [comment]
seems one need change 
`Markup.callbackButton`
to
`Markup.button.callback`
to work in v.4

**Comment by code-by** [comment]
not understand how to use `button.callback` with `keyboard` instead of `inlineKeyboard` or this is not possible?

**Comment by MKRhere** [comment]
@code-by Please don't necro-post. Open a new issue or discussion for new questions.
Yes, this is not possible; Telegram doesn't support callback buttons in Keyboard.

**Comment by hiddenpool** [comment]
> seems one need change `Markup.callbackButton` to `Markup.button.callback` to work in v.4

This worked. Thanks!

**Comment by Gobindapaull** [comment]
const { Telegraf, Markup } = require('telegraf');

you can do it to solve your problem. Mine is working
