### ISSUE TITLE
How to use telegraf on aws lambda? 

### ISSUE THREAD

**Issue by mattiapv** [telegraf/telegraf#797]
From lambda [documentation](https://docs.aws.amazon.com/en_us/lambda/latest/dg/nodejs-prog-model-handler.html)

> If your code performs an asynchronous task, return a promise to make sure that it finishes running. When you resolve or reject the promise, Lambda sends the response or error to the invoker.

But lambda function terminate before bot reply because bot.handleUpdate resolve immediately.

```javascript
const Telegraf = require('telegraf');
const bot = new Telegraf('TOKEN', {
  telegram: { webhookReply: false }
});

bot.on('text', ctx => {
  ctx.reply('Hello from Lambda');
});

exports.handler = async event => {
  return bot.handleUpdate(event);
};
```

If I force lambda function to run for 2 seconds using a Timeout I get a response from the bot.

```javascript
const Telegraf = require('telegraf');
const bot = new Telegraf('TOKEN', {
  telegram: { webhookReply: false }
});

bot.on('text', ctx => {
  ctx.reply('Hello from Lambda');
});

exports.handler = async event => {
  await bot.handleUpdate(event);
  const promise = new Promise(function(resolve, reject) {
    setTimeout(() => {
      resolve;
    }, 2000);
  });
  return promise;
};
```
So my question is how I use telegraf serverless?
In documentation telegraf is now/Firebase/AWS λ/Whatever ready but there are no examples.
Thanks

**Comment by tva10** [comment]
Hello @mattiapv 
In this case, looks like u have broken promise chain. And most likely that event promise ends before `reply()` happens.

You should `return reply(...)` (or another promise) in this case:
```javascript
bot.on('text', ctx => {
  return ctx.reply('Hello from Lambda');
});
```

**Comment by mattiapv** [comment]
Thanks, this fixed the problem. I have another question.
 I don't understand the second optional parameter _webhookResponse_ in [handleUpdate](https://telegraf.js.org/#/?id=handleupdate)
For example on firebase cloud functions to [terminate](https://firebase.google.com/docs/functions/http-events#terminate_http_functions) a function you use send(), redirect(), or end().
Google Cloud functions use [Express request and response object](https://firebase.google.com/docs/functions/http-events#using_express_request_and_response_objects)
Why passing res object in handleUpdate doesn't terminate function?
I can terminate a function using send() after waiting handleUpdate to resolve. So for what do I use res object in handleUpdate?

```javascript
const functions = require('firebase-functions');
const Telegraf = require('telegraf');
const bot = new Telegraf('TOKEN', {
  telegram: { webhookReply: false }
});

bot.on('text', ctx => {
  return ctx.reply('Hello from Cloud Functions');
});

const runtimeOpts = {
  timeoutSeconds: 3,
  memory: '128MB'
};

exports.bot = functions
  .runWith(runtimeOpts)
  .region('europe-west1')
  .https.onRequest(async (req, res) => {
    await bot.handleUpdate(req.body, res); // Never terminate
    //res.status(200).send('OK'); //If I uncomment this line function terminate after bot reply
  });
