### ISSUE TITLE
No botInfo in context if bot not started via launch()

### ISSUE THREAD

**Issue by Niklv** [telegraf/telegraf#798]
## Context

In express.js example:

```js
const Telegraf = require('telegraf')
const express = require('express')
const expressApp = express()

const bot = new Telegraf(process.env.BOT_TOKEN)
expressApp.use(bot.webhookCallback('/secret-path'))
bot.telegram.setWebhook('https://server.tld:8443/secret-path')

expressApp.get('/', (req, res) => {
  res.send('Hello World!')
})

expressApp.listen(3000, () => {
  console.log('Example app listening on port 3000!')
})
```

There are not explicitly called `bot.launch(...)` in this example.
So `botInfo` in context will be `undefined`.

https://github.com/telegraf/telegraf/blob/develop/telegraf.js#L103-L105

* Telegraf.js Version: 3.33.3
* Node.js Version: 12.12.0
* Operating System: macos

## Expected Behavior

Similar behaviour in all launch configs. 

## Current Behavior

`botInfo` exists or not exists in `context` depending launch config.

**Comment by dotcypress** [comment]
@Niklv this is not a bug, because `Telegraf` doesn't get bot by default. In some use cases we can't call Telegram at bot start(multi node configuration with webhook only)
