### ISSUE TITLE
Permament memory reservation(?)/leak when sending file to a user.

### ISSUE THREAD

**Issue by asc11cat** [telegraf/telegraf#799]
## Context

* Telegraf.js Version: 3.32.0
* Node.js Version: v10.16.3
* Operating System: Ubuntu 18.04.3 LTS x86_64

## Expected Behavior

Normal sending of files to a user.

## Current Behavior
Big memory reservation/leak(up to 800mb) on file upload.

## Failure Information (for bugs)
File size is 5MB, example code is:
https://gist.github.com/asc11cat/c381b38e3902353452a81cfb01f96ca5

Same issue with --expose-gc node argument.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. use code from https://gist.github.com/asc11cat/c381b38e3902353452a81cfb01f96ca5
2. change path to file which size is more than 5mb
3. change token of bot
4. rapidly spam /test to bot
5. get memory leak/reservation up to 800mb

**Comment by dotcypress** [comment]
@asc11cat it happens because you using `readFileSync`
