### ISSUE TITLE
Chaining Message Sending Properly

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#80]
Hello! 

Thank you for taking the time to read this. The previous questions that you have answered were super super helpful!

Anyway, I just wanted to ask a question on how to correct chain message replies so that they will send sequentially.

Is this the correct way to do it? (Below)

```
bot.command('start', (ctx) => {
    ctx.replyWithHTML("Hello").then(()=>{
        ctx.replyWithHTML("This").then(()=>{
            ctx.replyWithHTML("Should").then(()=>{
                ctx.replyWithHTML("Send").then(()=>{
                    ctx.replyWithHTML("Sequentially")
                })
            })
        })
    })
});
```

...or is this the correct way? (below)

```
bot.command('start', (ctx) => {
    return ctx.replyWithHTML("Hello").then(()=>{
        return ctx.replyWithHTML("This").then(()=>{
            return ctx.replyWithHTML("Should").then(()=>{
                return ctx.replyWithHTML("Send").then(()=>{
                    return ctx.replyWithHTML("Sequentially")
                })
            })
        })
    })
});
```

I understand that we can use ES7's Async/Await feature, but if we don't use it, what is the proper way to chain replies?

Hope to hear from you soon!

**Comment by dotcypress** [comment]
Hey.

Yes, ES7's `async/await` will help you with charm ;)

Otherwise, you might use [any approaches to call Promise chain sequentially](http://stackoverflow.com/questions/24586110/resolve-promises-one-after-another-i-e-in-sequence).

Your second example is absolutely correct, you might just minimize code, like following:

```js
bot.command('start', (ctx) => ctx.replyWithHTML("Hello")
  .then(() => ctx.replyWithHTML("This"))
  .then(() => ctx.replyWithHTML("Should"))
  .then(() => ctx.replyWithHTML("Send"))
  .then(() => ctx.replyWithHTML("Sequentially"))
  .then(() => ctx.replyWithHTML("This"))
)
```

PS: But this is not guarantee that messages arrive to user sequentially, it's really depends on Telegram servers logic.

**Comment by joshuaquek** [comment]
Dear dotcypress, 

Thank you for extremely speedy reply!

Just to check, the syntax of

```
bot.command('start', (ctx) => ctx.replyWithHTML("Hello")
  .then(() => ctx.replyWithHTML("One"))
  .then(() => ctx.replyWithHTML("Two"))
)
```

be the same as 

```
bot.command('start', (ctx) => ctx.replyWithHTML("Hello")
  .then(() => {
      return ctx.replyWithHTML("One")
  }).then(()=>{
      return ctx.replyWithHTML("Two")
  })
)

```

or would it be the same as 


```
bot.command('start', (ctx) => ctx.replyWithHTML("Hello")
  .then(() => {
      ctx.replyWithHTML("One")
  }).then(()=>{
      ctx.replyWithHTML("Two")
  })
)

```

?

Hope to hear from you soon!

**Comment by dotcypress** [comment]
Hey 😃 

We massively use [Promises](https://developers.google.com/web/fundamentals/getting-started/primers/promises) in Telegraf, and when you omit `return` keywork in last example - you just break Promise chain, and you will have similar result as in following example:
  
```js
bot.command('start', (ctx) => {
  ctx.replyWithHTML("Hello")
  ctx.replyWithHTML("One")
  ctx.replyWithHTML("Two")
})
```

As you see, you lose all `Promise` benefits here. 😉

**Comment by dotcypress** [comment]
@joshuaquek btw, good article about [asynchronous js](https://www.sitepoint.com/simplifying-asynchronous-coding-es7-async-functions/).

**Comment by joshuaquek** [comment]
Dear dotcypress,

ok, thank you!!! (:

Your answers have been super helpful!
