### ISSUE TITLE
Missing state type in context interface

### ISSUE THREAD

**Issue by chrisands** [telegraf/telegraf#804]
## Context

Context interface doesn't have state type but in docs there in [suggestion](https://telegraf.js.org/#/?id=state) to use state of the context.

* Telegraf.js Version: 3.33.3
* Node.js Version: 12
* Operating System: mac os

## Expected Behavior

Context interface have state type

## Current Behavior

Context interface doesn't have state type

**Comment by chrisands** [comment]
Also there missing botInfo type in context interface

**Comment by nasuke0302** [comment]
Sorry for asking, maybe Im missing something but why is this closed? I have the latest npm version of `telegraf` at the moment (3.38.0) and still `ctx.state` throws `Property 'state' does not exist on type 'TelegrafContext'.`

**Comment by wojpawlik** [comment]
It's fixed, just not yet published

**Comment by dimankiev** [comment]
> It's fixed, just not yet published

Still waiting :(
![image](https://user-images.githubusercontent.com/30737847/100152255-17e37500-2eab-11eb-8577-6bdc2d6415da.png)
