### ISSUE TITLE
Processing the same update multiple times

### ISSUE THREAD

**Issue by KnorpelSenf** [telegraf/telegraf#806]
## Context

The bot is running on Google App Engine with autoscaling limited to 2 F1 instances.

* Telegraf.js Version: 3.33.3
* Node.js Version: nodejs12 environment
* Operating System: ?

## Expected Behavior

When an update is received, it should be confirmed (200) so that Telegram will not resend it.

If the error is not on the Telegraf side (that is, if Telegram tries to redeliver a message that was indeed confirmed by a 200 status code), the Telegraf framework should filter out the duplicates.
For example, the list of update ids from a configurable time interval should be stored and omitted if received again. As Telegram is retrying only within a given time frame, it should even be possible to set a default value of 24 hours for this setting.
I know that this list can grow quite large. Therefore this should perhaps be an optional functionality for bots that do not need to scale to millions of updates per day.
Also, this list can be compressed quite easily by storing it as a list of intervals. This way, it's possible to avoid duplicates with constant memory (just the last update id), given the update ids are auto-incremented.
EDIT: I do not see any log entries saying that Telegraf responded with a status code 500, hence I suggest to implement the above duplicate filtering.

## Current Behavior

I do not know whether the response status of Telegraf is 200 or 500, but what I do see is how the same update gets processed over and over again.

## Failure Information (for bugs)

There's no stack trace or something, just logs (see below).

### Steps to Reproduce

1. Set up the bot using webhooks
2. Pass `{ telegram: { webhookReply: false } }` as the second argument to the `Telegraf` constructor
3. Even when sending a message to the very same chat the update is coming from, Telegram will consider the delivery of the message as unsuccessful and thus try again.

### Failure Logs

I see the following logs:
![image](https://user-images.githubusercontent.com/12952387/69244256-edc6eb00-0ba4-11ea-9768-fde561bda5d4.png)

Notice how the update xxx31 gets processed again and again. In the meantime, the bot's handler has been executed, some background task has been performed, a message has been sent to the chat, replying to the message from update xxx31.

## Note

Am I maybe missing something? Do I manually need to confirm a received message?

**Comment by KnorpelSenf** [comment]
Possibly related to #836 and #851

**Comment by absemetov** [comment]
@KnorpelSenf please help. My main file https://github.com/absemetov/rzk-com-ua/blob/master/functions/bot.js
Upload scene https://github.com/absemetov/rzk-com-ua/blob/master/functions/bot_upload_scene.js
When I upload goods Telegram resend me message many times, how res 200 Ok to bot when processing upload?

**Comment by KnorpelSenf** [comment]
@absemetov I don't have much time to study your code right now, but generally you should employ a lower timeout (say, 10 seconds) and then handle timeout errors and suppress the error so you respond with 200 anyway.

The upload takes too long, so Telegram is sending the update again, assuming it got lost.

Alternatively, you can deduplicate incoming updates via `update_id` but that's hard to get right. Storing the identifiers in memory is unreliable. I recommend the first approach for simplicity.
