### ISSUE TITLE
Deploy to Heroku goes Idle after 30min and doesn't start again with commands

### ISSUE THREAD

**Issue by pvnetto** [telegraf/telegraf#807]
I've deployed my bot to Heroku and everything works fine, except that when the bot goes idle after 30 minutes inactive, sending commands through Telegram doesn't wake it up. Accessing the bot's URL (the one provided by Heroku) through my browser triggers a get request on Heroku server, which is handled by Express and makes the server start again, but commands don't seem to do the same. Is there any way I could handle Telegram commands through Express just to send empty responses and wake my bot up, but still keep the Telegraf part of my application the same way?

Here's the source code for my bot https://github.com/pvnetto/OhHellBot/blob/master/src/index.js

I have little knowledge in Express and webhooks, so any help would be appreciated. Thank you!

**Comment by mattiapv** [comment]
I think your bot is using polling, you use bot.launch();
Go to https://api.telegram.org/bot<token>/getWebhookInfo, if url is empty your bot is using polling.
Also port on heroku for webhook is 443 not 8443

**Comment by pvnetto** [comment]
I removed launch and changed webhook port from 8443 to 443 and now it's working properly. Thank you very much!

**Comment by Porkechebure** [comment]
> I removed launch and changed webhook port from 8443 to 443 and now it's working properly. Thank you very much!

How you did that? I used bot.launch()
```
bot.launch()
console.log('bot launched')
```

but it still falls asleep. Using the @mattiapv  url check gives empty url, but I never set polling anywhere. I remember seeing somewhere bot.StartPolling but I never used it. How you set the whole thing up?
