### ISSUE TITLE
Multiple line inline keyboard

### ISSUE THREAD

**Issue by Stephirio** [telegraf/telegraf#811]
Is there a way to make an inline keyboard on multiple lines? I want to make something like this. Thanks in advance!

Button1   |   Button2
Button3   |   Button4

**Comment by blackforest-t** [comment]
on native markup keyboard ?
it's interesting for me too

**Comment by blackforest-t** [comment]
maybe i found answer for this question.
if you wan to show buttons in 2 columns you could markup inline keyboard
like:
markup.inlinekeyboard([
//1-st collum
[<button>,<button>],
//second collum
[<button>,<button>]
])

**Comment by blackforest-t** [comment]
maybe i found answer for this question.
if you wan to show buttons in 2 columns you could markup inline keyboard
like:
markup.inlinekeyboard([
//1-st collum
[button,button],
//second collum
[button,button]
])

**Comment by Stephirio** [comment]
> 
> 
> maybe i found answer for this question.
> if you wan to show buttons in 2 columns you could markup inline keyboard
> like:
> markup.inlinekeyboard([
> //1-st collum
> [button,button],
> //second collum
> [button,button]
> ])

thank you
