### ISSUE TITLE
Bot cannot send message to private chat

### ISSUE THREAD

**Issue by chrisvel** [telegraf/telegraf#812]
I have read past closed issues like https://github.com/telegraf/telegraf/issues/624 but the resolution is not clear when I want the bot to send a message to our direct private chat. 

I have tried to use `bot.telegram.sendMessage("@someone", "Hello man")` but it fails with error `(node:53799) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found`. But it always works fine with a group chat Id. 

The purpose is to make the bot send me notifications directly every X minutes or seconds. 

Any ideas?

**Comment by TiagoDanin** [comment]
Do not work with `user`, you should inform the id.

>https://core.telegram.org/bots/api#sendmessage
> 
> chat_id | Integer or String | Yes | Unique identifier for the target chat or username of the target channel (in the format @channelusername)
> -- | -- | -- | --

**Comment by alialparslan** [comment]
First you need to receive a message from user. Then you can use chat->id from that message. You can't directly send messages to users.
