### ISSUE TITLE
ENOENT error during npm i

### ISSUE THREAD

**Issue by y1n** [telegraf/telegraf#813]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.34
* Node.js Version: 13.0.1
* Operating System: Windows 10 Pro

## Current Behavior

Cannot install the package :/

### Failure Logs

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path d:\union\hunion\node_modules\telegraf\bin\telegraf
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod 'd:\union\hunion\node_modules\telegraf\bin\telegraf'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\namez\AppData\Roaming\npm-cache\_logs\2019-11-29T01_32_14_033Z-debug.log

**Comment by keyyuki** [comment]
got save errror, I check https://www.npmjs.com/package/telegraf, look like new version have problem, rollback to 3.33.3
```
npm i telegraf@3.33.3
```

**Comment by dotcypress** [comment]
@y1n fixed! 
Thank you for report

Latest version now is: `3.34.1`
