### ISSUE TITLE
Any way to send image from HTTP (not HTTPS)?

### ISSUE THREAD

**Issue by y1n** [telegraf/telegraf#814]
Hello! Sorry for a newbie question, but I have been stuck with it for at least a few hours now. 

Is there any shortcut provided by Telegraf to be able to send pictures from HTTP remote host? In particular, I would like to embed them into **sendMediaGroup** : )

**Comment by y1n** [comment]
```
                for await (image_page_url of gallery_image_array) {
                    let image_page_body = await axios.get(image_page_url).then(res1 => res1.data);
                    let image_url = image_page_body.match(/<img id="img" src="(.*?)" style="(.*?)" onerror="(.*?)">/s)[0].replace(/<img id="img" src="/, '').replace(/" style="(.*?)" onerror="(.*?)">/, '').trim()
                    image_array.push({'type': 'photo', 'media': {url: image_url, filename: '1.jpg'}});
                }
await api.sendMediaGroup(-1001366696396, image_array)
                .then(data => {
                    console.log(data)
                })
                .catch(error => {
                    console.error(error)
                })
```
`TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"`
![image](https://user-images.githubusercontent.com/13171326/69841510-24b59480-1268-11ea-8c0f-3e0fc835aa41.png)
I think its caused by the fact that the array is a mix of http and https URLs. However, maybe I just did something else wrong.

**Comment by twoperkg** [comment]
Hi! I had the same issue.  Telefgraf.js is using node-fetch module to fetch data and by default node-fetch  not allowing requests by http protocol. 
Just for testing purposes swap telegraf module with my  fork git@github.com:twoperkg/telegraf.git  and see if it will work for you. 

Or reference this file:
https://github.com/twoperkg/telegraf/blob/develop/core/network/client.js
rows 12-27 and 179 where I pass options to  agent property.

**Comment by septs** [comment]
workaround
```ts
const bot = new Telegraf(process.env.BOT_TOKEN!, {
  telegram: {
    // ...
    // @ts-ignore
    agent(parsedURL: URL) {
      if (parsedURL.protocol !== 'https:') {
        return http.globalAgent;
      }
      return new https.Agent({
        keepAlive: true,
        keepAliveMsecs: 10000,
      });
    },
    // ...
  },
});
```
