### ISSUE TITLE
ForceReply?

### ISSUE THREAD

**Issue by gugiserman** [telegraf/telegraf#82]
Hello, I read all the docs and searched through the source code until I found the ForceReply under the Markup module, but I just can't understand how to use it :P

I read everything I could on the official Telegram API documentation as well.

```
Upon receiving a message with this object, Telegram clients will display a reply interface to the user
```

But I still don't understand how to achieve this. I'm currently getting a `/command` from inside a group chat and I need to send back a message (a question) so the user might answer directly from inside the reply/quote thing.

I tried several approaches using `.reply` shortcut and telegram's `sendMessage` with the settings/extra object (with reply_markup and force_reply) and got nowhere.

Thanks :(

**Comment by dotcypress** [comment]
Hey @gugiserman 

```js
bot.command('test', ctx.reply('Hey', Extra.markup(Markup.forceReply())))
```
or
```js
bot.command('test', ctx.reply('Hey', Markup.forceReply().extra()))
```

You can find example usage [here](https://github.com/telegraf/telegraf/blob/develop/examples/keyboard-bot.js)

**Comment by gugiserman** [comment]
@dotcypress Awesome! It worked. Thanks, man.

**Comment by dalisoft** [comment]
@dotcypress This `ForceReply` method as you mentioned here isn't works with keyboard `Markup` how i can do it? Thanks

**Comment by dotcypress** [comment]
@dalisoft telegram allows only one keyboard type per request
https://core.telegram.org/bots/api#sendmessage

**Comment by dalisoft** [comment]
@dotcypress I have fixed issue when find `inReplyTo` param

**Comment by diosamuel** [comment]
How to trigger a force reply after i clicked the inline button?

i try this code but didnt worked

```
bot.command('btn', (ctx) =>{
	ctx.replyWithMarkdown('*Force* Reply',{
		reply_markup: { 
			inline_keyboard: [[{
				text:'Click to trigger force reply',
				callback_data:'force'
			}]],
		},
	})
})

bot.action('force', (ctx) => {
	Markup.forceReply()
})
```

any suggestions?

**Comment by NormandoHall** [comment]
> How to trigger a force reply after i clicked the inline button?
> 

```
bot.action('force', (ctx) => {
	ctx.reply('something', Markup.forceReply());
})
```
