### ISSUE TITLE
Custom command prefix

### ISSUE THREAD

**Issue by watzon** [telegraf/telegraf#821]
**Is your feature request related to a problem? Please describe.**
Many bots use a custom prefix rather than the standard `/`. In some cases this allows bots with identical commands to avoid collisions, or allows different kinds of commands (admin vs user?) to have a different prefix.

**Describe the solution you'd like**
I know this is currently possible by using `.hears`, but that requires a little extra work. The ideal solution would be to have an optional argument to `.command` called prefix. The prefix should be settable to a single string or an array of strings. It would also be nice to be able to set the prefix globally and have all commands use it by default.

**Describe alternatives you've considered**
Like I said it's possible with `.hears`, but it's not the ideal solution in my humble opinion. Many existing bot frameworks allow a custom prefix.

**Additional context**
It's possible that I've missed something that already makes this possible, but I've looked at the source for the `.command` method and I don't think so. If I have please let me know!

**Comment by dotcypress** [comment]
@watzon `.command` handler doesn't parse message text and use information from `MessageEntities` instead. So, for custom command prefix you must use '.hears' or even create new handler.

**Comment by watzon** [comment]
That makes sense. Unfortunate, but it makes sense. I'll close.
