### ISSUE TITLE
resize and wrap inline buttons when use editMessageReplyMarkup

### ISSUE THREAD

**Issue by mohammadreza** [telegraf/telegraf#822]
**Is your feature request related to a problem? Please describe.**
I don't see any solution for resize and wrap inline buttons when using `editMessageReplyMarkup`. It's can be annoying on mobile phone displays and small screens.

**Additional context**
![image](https://user-images.githubusercontent.com/5070181/69955559-28207880-1513-11ea-8f86-3373abb03d4a.png)

**Comment by Fi1osof** [comment]
@mohammadreza try to use arrays. https://github.com/telegraf/telegraf/issues/811#issuecomment-560116408

**Comment by Piterden** [comment]
There is two-column split:
https://github.com/Piterden/admin_von_bot/blob/master/src/buttons/settings.js#L12-L19

And there is three column:
https://github.com/Piterden/admin_von_bot/blob/master/src/handlers/new-chat-member.js#L74-L86

You can use one column if you wish

**Comment by Fi1osof** [comment]
My solution:
```
const keyboard = .... array;

const columnsCount = 2;

keyboard..reduce((curr, next, index) => {

        if (index % columnsCount === 0) {

          // Add new row
          curr.push([]);
        }

        // Get current row
        const [row] = curr.slice(-1);

        // Insert button
        row.push(next);

        return curr;
      }, []);
```
