### ISSUE TITLE
Wrong margins in web.telegram.org

### ISSUE THREAD

**Issue by Fi1osof** [telegraf/telegraf#824]
## Context

OK
![Screenshot from 2019-12-04 17-12-52](https://user-images.githubusercontent.com/2550668/70149540-5f308e80-16b9-11ea-897a-995c9139f8e5.png)

Not OK
![Screenshot from 2019-12-04 17-13-08](https://user-images.githubusercontent.com/2550668/70149552-65bf0600-16b9-11ea-919e-e0cfdf6186df.png)

```
    const keyboard = Markup.inlineKeyboard([
      [
        Markup.callbackButton('Delete', 'delete'),
        Markup.urlButton('❤️', 'http://telegraf.js.org'),
      ],
      [
        Markup.urlButton('❤️', 'http://telegraf.js.org'),
        Markup.callbackButton('Delete', 'delete'),
      ],
      [
        Markup.callbackButton('Delete wefwefewf', 'delete'),
        Markup.urlButton('❤️', 'http://telegraf.js.org'),

      ],
    ]);
```

* Telegraf.js Version:3.34.1
* Operating System: Ubuntu
Browser: Firefox 70.0.1 (64-bit)

**Comment by Piterden** [comment]
What if you try without smiles? I mean it would be nice you to detect the reason of those shifts.

**Comment by Fi1osof** [comment]
Of course I tried without smiles, and everything is OK.
But I need it with smiles. 
And this smile from [official examples](https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js#L22).
And official examples looks not good too. 
![Screenshot from 2019-12-05 05-43-08](https://user-images.githubusercontent.com/2550668/70199203-2678cf80-1722-11ea-86de-b34602ce8092.png)

**Comment by Piterden** [comment]
Does it heart smile only have such behavior? Have you tested other smiles? And also have you tried to fix that using inspector styles (what inspector shows you about those margins)?

**Comment by Fi1osof** [comment]
Yes, I tried, but not very carefully.
And maybe it's bug in https://github.com/zhukov/webogram

**Comment by del333ted** [comment]
I think this a Telegram Web bug.

**Comment by Fi1osof** [comment]
@del333ted looks so. I close this issue.
