### ISSUE TITLE
Login button not works on the browser version of the telegram

### ISSUE THREAD

**Issue by baur** [telegraf/telegraf#825]
Hi, all!
[login-bot](https://github.com/telegraf/telegraf/blob/develop/docs/examples/login-bot.js) works just fine on the mobile version, but not works on the browser version of the telegram

**Comment by Piterden** [comment]
Hm.. Okay. Keep us posted!

**Comment by baur** [comment]
any suggestions?!

**Comment by KnorpelSenf** [comment]
Telegram bots are independent of the Telegram client that is used. This is not an issue of `telegraf`.
