### ISSUE TITLE
self cleaning scene example please ?

### ISSUE THREAD

**Issue by Matan-M** [telegraf/telegraf#827]
im trying to delete all my scene messages after the user done the scene questions,
i cant find example , its deleted from git its redirect me to 404 page ,
can someone help please ?

thats where i looked for the self cleaning scene 
https://github.com/telegraf/telegraf/blob/develop/docs/examples/self-cleaning-scenes.js
its 404 page ...

**Comment by Piterden** [comment]
https://github.com/telegraf/telegraf/commit/1dab73bd4c26ef18f5527cea6bdfe3495feebe29#diff-3bae13f6fc8b1a50c8d1c90fcdc37e04

**Comment by Matan-M** [comment]
@Piterden tryied the example but the bot not sending the messages he needs to send , runned same script as there

**Comment by Matan-M** [comment]
its sending after adding stage.register , but the messages not get deleted .. :O

**Comment by Matan-M** [comment]
oh my bad sorry for spamming , but im using WizardScene , and the method you showed there is not working for the WizardScene 
i tried to save the message within session , but its deleteing only bot messages and not the user messages

**Comment by Piterden** [comment]
#828

**Comment by Piterden** [comment]
> oh my bad sorry for spamming , but im using WizardScene , and the method you showed there is not working for the WizardScene
> i tried to save the message within session , but its deleteing only bot messages and not the user messages

So try to do it with a similar way
