### ISSUE TITLE
How can I do forceReply inline button? 

### ISSUE THREAD

**Issue by GreinOne** [telegraf/telegraf#831]
Please, help :)
I send message with inline keyboard and I want when user tap on button shows reply interface to the user, as if they manually selected the bot's message and tapped ’Reply'.
I found examples only with `ctx.reply('some_text', Markup.forceReply().extra())`, but I need to use the previously sent message without new reply.
[image](https://monosnap.com/direct/fUwY57sxfU5YCaBZ6JPyYmJfqYcpuI)

**Comment by Piterden** [comment]
You can't do that. Bots API doesn't allow you.

**Comment by GreinOne** [comment]
Ok, thx for answer.
