### ISSUE TITLE
Stopping and relaunching a bot is broken

### ISSUE THREAD

**Issue by kschingiz** [telegraf/telegraf#832]
## Context

I am writing an app where user can stop and relaunch tg bot by clicking: Enable, Disable buttons.
When user clicks Enable:
```
this.bot.launch()
```
On Disable:
```
this.bot.stop()
```
Quite simple.

* Telegraf.js Version: 3.34.1
* Node.js Version: v10.16.3
* Operating System: Ubuntu 16.04

## Expected Behavior

But should relaunch and start polling for new updates without any issues.

## Current Behavior

When user relaunches the bot, I am getting this error log:
```
Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```
And the message handlers (on("text"), on("document")) are executed several times like I have launched several bots: If user relaunched 2 times, message handlers executed twice, if relaunched 5 times then =  executed 5 times

### Steps to Reproduce

1. Create a bot
2. Launch
3. Stop
4. Launch

### Reproduction code

I have simulated user behaviour by simple script, it launches and stops tg bot:
```
const Telegraf = require("telegraf");

const bot1 = new Telegraf(token);

bot1.on("text", (ctx) => {
  console.log(ctx.message)
})

bot1.launch();

setInterval(() => {
  bot1.stop(() => {

    bot1.launch();
  });
}, 1000);
```

### Failure Logs
```
Failed to process updates. { Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at buildConfig.then.then.then.then (/home/user/projects/tg_issue/node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 409,
  response:
   { ok: false,
     error_code: 409,
     description:
      'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' },
  description:
   'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',
  parameters: {},
  on:
   { method: 'getUpdates?offset=0&limit=100&timeout=30',
     payload: {} } }
```

**Comment by dotcypress** [comment]
@kschingiz you trying to stop bot with `setInterval`, but you need to wait for `stop` callback or make long-polling timeout less than interval.

```js
bot.launch({ polling: { timeout: 1 } })

setInterval(() => {
  bot.stop(() => {
    bot.launch({ polling: { timeout: 1 } })
  })
}, 3000)
```
