### ISSUE TITLE
Is it possible to upload photos in editMessageMedia?

### ISSUE THREAD

**Issue by feed4rz** [telegraf/telegraf#834]
I am trying to use `editMessageMedia` in a same way as `replyWithPhoto`:

```js
// source is a buffer
ctx.replyWithPhoto({ source })

ctx.editMessageMedia({ source })
```

But it seems impossible because I get this error:
```
Bad Request: can't parse InputMedia: Media is not specified
```

Here is a payload that gets generated by telegraf (taken from error object):

```js
{
  chat_id: 167702358,
  message_id: 458,
  media: {
    source: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ... 146896 more bytes>,
    parse_mode: undefined
  },
  reply_markup: { inline_keyboard: [ [Array] ] }
}
```

What can I do to use `editMessageMedia` in a same way as `replyWithPhoto`? Or otherwise how do I upload a photo to telegram servers and then just change `media` to some attachment name as stated in telegram docs and in this issue #599 ?

**Comment by dotcypress** [comment]
@fabnicolas with `editMessageMedia` you must provide media type explicitly:
```js
ctx.editMessageMedia({
   type: 'photo',
   media: source
})
```

**Comment by feed4rz** [comment]
@dotcypress 
So here is what I get when I try doing what you are telling me:

<img width="638" alt="Screenshot 2019-12-26 at 13 51 38" src="https://user-images.githubusercontent.com/13008534/71473143-ebc8fb00-27e6-11ea-89d6-a1cd351dbe14.png">

The code itself is a very basic thing with image generation:
```js
// returns a buffer
const media = await image.getBufferAsync(jimp.MIME_JPEG)

await ctx.editMessageMedia(
	{ type: 'photo', media },
	Extra
	.caption(text)
	.markup(
		Markup.inlineKeyboard([[...]])
	)
	.markdown()
)
```

I dont get why it says `entity too large`, when I can do the same thing but using `replyWithPhoto` method.

**Comment by feed4rz** [comment]
I ve figured it out, you should pass buffer as shown below:

```js
// returns a buffer
const source = await image.getBufferAsync(jimp.MIME_JPEG)

await ctx.editMessageMedia(
	{ type: 'photo', media: { source } },
	Extra
	.caption(text)
	.markup(
		Markup.inlineKeyboard([[...]])
	)
	.markdown()
)
```

But it wont allow you to edit media if you didnt attach any while sending original message, so trying it was kinda worthless.

**Comment by albertoxamin** [comment]
I'm trying to do the same with `telegram.editMessageMedia` but I'm getting 
```
UnhandledPromiseRejectionWarning: Error: 400: Bad Request: can't parse InputMedia: Field "media" must be of type String
```
