### ISSUE TITLE
Telegraf keeps processing promise error after cleaning chat with bot?

### ISSUE THREAD

**Issue by DeusNexus** [telegraf/telegraf#836]
## Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: telegraf@3.34.1
* Node.js Version: v8.10.0
* Operating System: Ubuntu 18.04.3 LTS

## Expected Behavior
After cleaning the chat for both the bot and user I expect the bot not to throw an error of old promise sent from the old chat history. 

## Current Behavior
The bot throws errors of chat that has already been deleted for both bot and user. These promises seem to be pending even after deletion. 

### Steps to Reproduce
1. Create an async function that checks for a value that is unavailable
2. Send a message on telegram with the corresponding command to trigger the function.
3. Telegraf logs the error and stops.
4. Clean the chat for both the user and bot, this should make the bot not to trigger the function anymore.
5. With cleaned chat, the error still occurs and is loaded, how to clean this pending queue?

### Failure Logs
Regex does not have value for a group:
Failed to process updates. TypeError: Cannot read property '1' of null
    at MyFunction (/home/user/telegram-bot/index.js:45:18)
    at Main.bot.hears (/home/user/telegram-bot/index.js:260:83)
    at Promise.resolve.then (/home/user/telegram-bot/node_modules/telegraf/composer.js:143:56)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by dotcypress** [comment]
@DeusNexus could you please provide minimal bot code to reproduce?

**Comment by KnorpelSenf** [comment]
I have a feeling that this is related to #851 but I might be mistaken.

**Comment by wojpawlik** [comment]
I just checked, bot API delivers updates about already deleted messages, and they might have been reprocessed before #1224.
