### ISSUE TITLE
ctx.setChatTitle not exposed to typescript

### ISSUE THREAD

**Issue by sharedRoutine** [telegraf/telegraf#837]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: v3.34.1
* Node.js Version: v8.9.0
* Operating System: MacOS Catalina

## Expected Behavior

Documentation says that `ctx.setChatTitle("");` or `ctx.telegram.setChatTitle(chat.id, title);` works

## Current Behavior

I am using typescript and it says that `ctx (of type ContextMessageUpdate)` does not respond to `setChatTitle `. Nor does `ctx.telegram.setChatTitle`

### Steps to Reproduce

1. Create a nodejs project
2. Setup Typescript
3. Install telegraf
4. Import it
5. try `bot.on("text", (ctx: ContextMessageUpdate) => { ctx.setChatTitle("Test Title"); });`

### Additional Information

Manually adding `setChatTitle` to the index.d.ts file fixes typescript and therefore allows me to compile. So it is just missing in the typescript definition.

**Comment by yanislav-igonin** [comment]
I'll help in 1-2 days and make PR.
Assign on me.
