### ISSUE TITLE
webhookCallback() doesn't work properly with express

### ISSUE THREAD

**Issue by alexmww** [telegraf/telegraf#845]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: telegraf@3.34.1
* Node.js Version: v8.10.0
* Operating System: Ubuntu 18.04.3 LTS

## Expected Behavior

express-webhook-bot.js example works as expected

## Current Behavior

WebHook is set but controller wich set through webhookCallback() returns 503 error after 30 seconds
JSON returned /getWebhookInfo 
![image](https://user-images.githubusercontent.com/32086218/71512500-125f6280-28c9-11ea-9589-cc94506b0de1.png)

Maybe somehow it is connected to Heroku (#610) 

I was managed to fix that issue writing router for express by myself.

**Comment by TiagoDanin** [comment]
@alexmww Could you post your code?

**Comment by evasyuk** [comment]
I had the same issue: "webhookCallback()" did not call next() and execution hanged

I decided to bypass this problen by
1. manually parsing incoming webhook updates 
2. passing updates to bot.handleUpdate(...)

works like a charm!

**Comment by KnorpelSenf** [comment]
I should add that I cannot reproduce the issue. Please reopen if you can provide a SSCCE.
