### ISSUE TITLE
ctx.wizard.next() with differents users

### ISSUE THREAD

**Issue by hugorplobo** [telegraf/telegraf#850]
I have a code like that:

``` javascript
const turnScene = new wizardScene(
   "sceneId",
   ctx => {
      manageTurn();
      return ctx.wizard.next();
},
   ctx => {
   // rest of the code...
}

const stage = new Stage([turnScene]);
bot.use(session());
bot.use(stage.middleware());
bot.command("start", Stage.enter("sceneId"));
```

I'm using this in a group, and I need to change the step after the manageTurn(), but the bot only pass the step if the user that used /start sends a message. All others are ignored. How can I solve this?

**Comment by Piterden** [comment]
Why do you need to change a step there? The sense of wizard is to change step only after somebody answered. 
`manageTurn` and `next` are not defined variables in your code.

**Comment by hugorplobo** [comment]
> Why do you need to change a step there? The sense of wizard is to change step only after somebody answered.
> `manageTurn` and `next` are not defined variables in your code.

Those are just examples. After the manageTurn(), the user have to send a message like you said, but the bot only change the step if the message sender is the user that sent the /start. My problem is that. The bot in a group have to change the step with different people messages.

**Comment by Piterden** [comment]
`bot.use(session())` force it to work with the only one user. You should init the session, overriding its session key. It haven't to include a user ID.

**Comment by hugorplobo** [comment]
> `bot.use(session())` force it to work with the only one user. You should init the session, overriding its session key. It haven't to include a user ID.

Thank you so much for the explanation. So, how can I do that? The session ID is in the ctx?

**Comment by Piterden** [comment]
Wizard can't do that.

**Comment by hugorplobo** [comment]
> Wizard can't do that.

Is it possible with a base scene? If yes, can you help me in how to do that? There's no explanation in docs about the scenes. I have read the issue #705 but it doesn't tell about the session ID.

**Comment by Piterden** [comment]
You don't need session. Just use the Telegraf's context to store your data related to steps.

**Comment by hugorplobo** [comment]
> You don't need session. Just use the Telegraf's context to store your data related to steps.

Sorry for that but I didn't understand the session and scenes very well. I'm using the session just like the code example above because I saw this in the issue mentioned before. I'm only using the line of require, and the `bot.use(session())`

Then, I'm not using the session for anything else like store data, but, when I run the application without the line `bot.use(session())`, I get a:

```
TypeError: Cannot read property 'enter' of undefined
      at /home/hugo/Desktop/telegraf-bot/node_modules/telegraf/stage.js:39:31
      at /home/hugo/Desktop/telegraf-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)

Failed to process updates. TypeError: Cannot read property 'enter' of undefined
    at /home/hugo/Desktop/telegraf-bot/node_modules/telegraf/stage.js:39:31
    at /home/hugo/Desktop/telegraf-bot/node_modules/telegraf/composer.js:143:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

Can you help me with that?
