### ISSUE TITLE
Processing an update twice when graceful shutdowned

### ISSUE THREAD

**Issue by mbelsky** [telegraf/telegraf#851]
## Context

Hey,

I've implemented graceful shutdown for my bot and face an issue. I've created a small demo project: https://github.com/mbelsky/tf-update-issue/blob/master/index.js

* Telegraf.js Version: 3.35.0
* Node.js Version: 12.13.0
* Operating System: MacOS 10.15.1

## Expected Behavior

An updated handled once

## Current Behavior

An updated handled twice

### Steps to Reproduce

1. `npm start`
2. Send '/long' message to a bot
3. Send SIGINT to the node process while it processing update
4. Let the process die
5. `npm start` again 

<img width="954" alt="Screenshot 2020-01-03 at 01 29 35" src="https://user-images.githubusercontent.com/3923527/71698151-7606f580-2dcb-11ea-89b0-23a4fd1f98f7.png">

As you may see it processes `933862816` twice.

I think it could be fixed with adding `offset` arg in `Telegraf. startPolling` method, but before making a PR I'm interested to know your opinion about the preferred way to fix this issue.

**Comment by mbelsky** [comment]
@dotcypress Could I do something to help with investigation about this issue?

**Comment by wojpawlik** [comment]
I believe Telegraf should confirm the last batch of updates before exiting, by calling `this.telegram.getUpdates(0, 1, offset, allowedUpdates)` before exiting, PR welcome.

**Comment by wojpawlik** [comment]
Does Telegram consider update acknowledged if `getUpdates` request is aborted?

**Comment by wojpawlik** [comment]
Sounds like yes:

> An update is considered confirmed __as soon as__ `getUpdates` is called with an `offset` higher than its `update_id`.

So, aborting `getUpdates` on `bot.stop()` would not only speed up bot shutdown, but also prevent bot from handling updates twice if `bot.stop()` happens during `getUpdates`, with no extra requests! Extra request will be needed if it happens during processing a batch tho.

**Comment by wojpawlik** [comment]
This would require adding optional `signal` param to `callApi`.
