### ISSUE TITLE
WizardScene without Session

### ISSUE THREAD

**Issue by hugorplobo** [telegraf/telegraf#854]
I have this in my code to use the Wizard Scene:

```
const stage = new Stage([turnScene]);
bot.use(session());
bot.use(stage.middleware());
stage.register(turnScene);
bot.command("start", Stage.enter("sceneId"));
```

I need the Wizard Scene go to the next step with a message of different users, but with the session I can't do that. When I try to use the Wizard Scene without the `bot.use(session))`, I get this:

```
TypeError: Cannot read property 'enter' of undefined
      at /home/hugo/Área de Trabalho/telegraf-bot/node_modules/telegraf/stage.js:39:31
      at /home/hugo/Área de Trabalho/telegraf-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)

Failed to process updates. TypeError: Cannot read property 'enter' of undefined
    at /home/hugo/Área de Trabalho/telegraf-bot/node_modules/telegraf/stage.js:39:31
    at /home/hugo/Área de Trabalho/telegraf-bot/node_modules/telegraf/composer.js:143:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

I know that I need to use the Telegraf's context to store my data related to steps, but I don't store data in the session and yet I get the error above. How can I solve this?

**Comment by IMalyugin** [comment]
Session is required for Scenes to work at all.
Reason: bot needs to know whom he is talking to and in which chat. Without session no replying would be possible.

So it all actually depends on your goals. By default session is created for chatId+userId. If you want your chat bot to “enter” state based on message from any user in given chat, you could create your own custom session that binds session only to chatId.

To do so:
1. Initialize session like this: 
‘’’
session({
  property: 'chatSession',
  getSessionKey: (ctx) => ctx.chat && ctx.chat.id,
})
‘’’

2. pass { sessionName: 'chatSession' } in Stage constructor

**Comment by hugorplobo** [comment]
Thank you so much!
