### ISSUE TITLE
bot.command('command', callback); not working after bot.on('message', callback);

### ISSUE THREAD

**Issue by B4TT3RY** [telegraf/telegraf#855]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.35.0
* Node.js Version: 12.13.1
* Operating System: Windows 10

## Expected Behavior

```javascript
bot.on('message', callback);
bot.command('command', callback);
```
both working

## Current Behavior

```javascript
bot.on('message', callback);
bot.command('command', callback);
```
only working `bot.on('message', callback);`
ignore `bot.command('command', callback);`

**Comment by dotcypress** [comment]
Yes, this is intended behavior because all commands are messages.
