### ISSUE TITLE
[Question][Help]

### ISSUE THREAD

**Issue by mcaldas** [telegraf/telegraf#858]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.35.0
* Node.js Version: 13.5
* Operating System: Mac

Hi,

I am trying to customize the behavior of several bots together by using handle update and different routes on an express server.

For the handleUpdate i need to pass the req.body so telegraf can handle the update, but is there a place i can pass custom params? like the route accesed, or similar?
Couldnt find anything on the issues or documentation.

Thanks!

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#answerinlinequery

**Comment by KnorpelSenf** [comment]
You can use the `webhookCallback` described here: https://telegraf.js.org/#/?id=webhooks
Alternatively, you could directly invoke `bot.handleUpdate` with the `req.body` to let the update be handled by `telegraf`.
