### ISSUE TITLE
how can i set timeout for scene ?

### ISSUE THREAD

**Issue by Skull-Collector** [telegraf/telegraf#860]
i want to make a timeout to some of my scenes , how can i implement that with TelegrafJs
lets say if passed 10 minutes , then the scene will leave automaticly ?
that is possible ? 
if yes can i get some example please ?
thanks advice !

**Comment by kirosc** [comment]
Perhaps using the [session](https://telegraf.js.org/#/?id=session) to store a timestamp.

**Comment by IMalyugin** [comment]
Or just initialize session as
‘’’
session({ ttl: 600 })
‘’’
So it expires in 10 minutes, leaving scenes automatically (scenes are using session under the hood)

**Comment by Siedlerchr** [comment]
As I need a custom timeout only for some scenes I have created an example with Promise and setTimeout to manage this
https://gist.github.com/Siedlerchr/a9446c64d08033e3d68e7b9515d3255f

The only challenge was to trigger the saveSession method manually to remove the session data.
setting session = null was not sufficient in the timeout case, it did not trigger the saveSession method

**Comment by KnorpelSenf** [comment]
Looks closed to me.
