### ISSUE TITLE
bot.on('sticker') from example not responding

### ISSUE THREAD

**Issue by idkjs** [telegraf/telegraf#861]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version:
* Node.js Version:
* Operating System:

## Expected Behavior

Please describe the behavior you are expecting
Expecting typing `sticker` or `/sticker` into input on Telegram App returns a sticker.

## Current Behavior

What is the current behavior?
Nothing happens.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

https://github.com/idkjs/telegraf-telegram-bot-starter

## Example code from repo

```js
const Telegraf = require('telegraf');
require('dotenv').config();

const bot = new Telegraf(process.env.BOT_TOKEN);
bot.start((ctx) => ctx.reply('Welcome'))
bot.help((ctx) => ctx.reply('Send me a sticker'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.launch()
```

## Issue

Typing `/sticker` or `sticker` into `Telegram` input field does nothing when a reply is expected.

<img width="694" alt="Screenshot" src="https://user-images.githubusercontent.com/2370391/72180523-5b2d1600-33b5-11ea-92d3-dc14fc24d85e.png">

If you add this line:

```js
bot.hears('stickerhear', (ctx) => ctx.reply('👍'))
```

You get the sticker bot as seen below.

<img width="694" alt="Screenshot2" src="https://user-images.githubusercontent.com/2370391/72180607-831c7980-33b5-11ea-8adb-08e472692434.png">
How do I get the example to run as described?

Thank you.

**Comment by dotcypress** [comment]
You need to send literally a sticker.

<img width="281" alt="Screen Shot 2020-01-10 at 9 52 29 PM" src="https://user-images.githubusercontent.com/1333916/72199637-8fbfc280-33f3-11ea-9e17-5b5b0d1a9ed6.png">

**Comment by idkjs** [comment]
So the code in the example is not sending a sticker? How do we send a sticker using `ctx.reply`?
