### ISSUE TITLE
Chaining reply doesn't work properly

### ISSUE THREAD

**Issue by kirosc** [telegraf/telegraf#863]
* Telegraf.js Version: 3.35.0
* Node.js Version: 13.1.0

I tried to make my bot to reply multiple times with the code provided in #80 
```js
bot.command('start', (ctx) => ctx.replyWithHTML("Hello")
  .then(() => ctx.replyWithHTML("This"))
  .then(() => ctx.replyWithHTML("Should"))
  .then(() => ctx.replyWithHTML("Send"))
  .then(() => ctx.replyWithHTML("Sequentially"))
  .then(() => ctx.replyWithHTML("This"))
)
```

Strangely that the bot reply with the first line successfully. But, my another bot replies the last five lines. Both bots aren't related. They are hosted on different servers.

Anyone runs into this problem before?

**Comment by Piterden** [comment]
```js
bot.command('start', async (ctx) => {
  await ctx.replyWithHTML("Hello")
  await ctx.replyWithHTML("This")
  await ctx.replyWithHTML("Should")
  await ctx.replyWithHTML("Send")
  await ctx.replyWithHTML("Sequentially")
  await ctx.replyWithHTML("This")
})
```

**Comment by kirosc** [comment]
I don't think it's a problem with syntax. Maybe a GIF explains this issue better.

![](https://media.giphy.com/media/Q65qYkOk1ABVxebjxw/giphy.gif)

**Comment by oualidcena** [comment]
same problem!
i'm using firebase functions

**Comment by smaznet** [comment]
That's because you using webhookReply 
disable it and try again

**Comment by smaznet** [comment]
> That's because you using webhookReply
> disable it and try again



Or you can use it like this:
```js
bot.command('start', async (ctx) => {
  ctx.webhookReply = false;
  await ctx.replyWithHTML("Hello")
  await ctx.replyWithHTML("This")
  await ctx.replyWithHTML("Should")
  await ctx.replyWithHTML("Send")
  await ctx.replyWithHTML("Sequentially")
  ctx.webhookReply = true;
  await ctx.replyWithHTML("This")
})

```

**Comment by kirosc** [comment]
> > That's because you using webhookReply
> > disable it and try again
> 
> Or you can use it like this:
> 
> ```js
> bot.command('start', async (ctx) => {
>   ctx.webhookReply = false;
>   await ctx.replyWithHTML("Hello")
>   await ctx.replyWithHTML("This")
>   await ctx.replyWithHTML("Should")
>   await ctx.replyWithHTML("Send")
>   await ctx.replyWithHTML("Sequentially")
>   ctx.webhookReply = true;
>   await ctx.replyWithHTML("This")
> })
> ```

But I got an error.

```
  Error: 401: Unauthorized
      at C:\Projects\node_modules\telegraf\core\network\client.js:281:17
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async C:\Projects\api\index.js:39:3
```

**Comment by smaznet** [comment]
> > > That's because you using webhookReply
> > > disable it and try again
> > 
> > 
> > Or you can use it like this:
> > ```js
> > bot.command('start', async (ctx) => {
> >   ctx.webhookReply = false;
> >   await ctx.replyWithHTML("Hello")
> >   await ctx.replyWithHTML("This")
> >   await ctx.replyWithHTML("Should")
> >   await ctx.replyWithHTML("Send")
> >   await ctx.replyWithHTML("Sequentially")
> >   ctx.webhookReply = true;
> >   await ctx.replyWithHTML("This")
> > })
> > ```
> 
> But I got an error.
> 
> ```
>   Error: 401: Unauthorized
>       at C:\Projects\node_modules\telegraf\core\network\client.js:281:17
>       at processTicksAndRejections (internal/process/task_queues.js:93:5)
>       at async C:\Projects\api\index.js:39:3
> ```

Is your token ok?
This errors happens when you enter invalid token

**Comment by kirosc** [comment]
> > > > That's because you using webhookReply
> > > > disable it and try again
> > > 
> > > 
> > > Or you can use it like this:
> > > ```js
> > > bot.command('start', async (ctx) => {
> > >   ctx.webhookReply = false;
> > >   await ctx.replyWithHTML("Hello")
> > >   await ctx.replyWithHTML("This")
> > >   await ctx.replyWithHTML("Should")
> > >   await ctx.replyWithHTML("Send")
> > >   await ctx.replyWithHTML("Sequentially")
> > >   ctx.webhookReply = true;
> > >   await ctx.replyWithHTML("This")
> > > })
> > > ```
> > 
> > 
> > But I got an error.
> > ```
> >   Error: 401: Unauthorized
> >       at C:\Projects\node_modules\telegraf\core\network\client.js:281:17
> >       at processTicksAndRejections (internal/process/task_queues.js:93:5)
> >       at async C:\Projects\api\index.js:39:3
> > ```
> 
> Is your token ok?
> This errors happens when you enter invalid token

Yeah. Never mind, it's fixed after I reset the environment.
