### ISSUE TITLE
How to display data in Table format in BOT

### ISSUE THREAD

**Issue by damvinod** [telegraf/telegraf#865]
Hi,

Is it possible to display the response in table as below ?

<table><tr><th>Txn Date</th><th>Txn Desc</th><th>Txn Amount</th><th>Txn Remarks</th></tr><tr><td>2019-01-01</td><td>MonthendRepayment</td><td>-800</td><td>Dopayment</td></tr><tr><td>2019-01-01</td><td>MonthendRepayment</td><td>-800</td><td>Dopayment</td></tr></table>

**Comment by llgdd** [comment]
You can try to use monowidth font to draw a table using text or generate an image with your table.
