### ISSUE TITLE
'Bad Request: RESULT_ID_INVALID' 

### ISSUE THREAD

**Issue by el-lsan** [telegraf/telegraf#869]
## Context
So i've been running my bot for around two years now. The main functionality of my bot is to search GIF using keywords (inline query) and then user would get a list of GIFs related to that keyword via answerInlineQuery.
But since the recent update for telegram bot API seems like something is change and telegraf doesn't take care of it.
Not sure if it related to new file_id or file_unique_id !
( FYI everything was fully functional and fine before bot api 4.6 update )

For some reason if you use the new format of file_id ( which is much longer comparing to old file_id ):
example of new file_id:

CgACAgIAAxkBAAEX5bNeKforSXvcNs_XCw2Ex861kXtSTwACzgYAAoyjSUmS8XL7EvBDWhgE

would throw an error : 

```
 { 
     ok: false,
     error_code: 400,
     description: 'Bad Request: RESULT_ID_INVALID' 
 },
```

* Telegraf.js Version: 3.36.0
* Node.js Version: v13.6.0
* Operating System: MacOS 10.15.2

## Expected Behavior

Should show a list of selectable GIFs like this:

![image](https://user-images.githubusercontent.com/1249548/73021413-d23bc300-3e27-11ea-944b-5da2f2f0c0d2.png)

## Current Behavior

Throws and error and answerInlineQuery would fail!

## Failure Information (for bugs)

```
{ method: 'answerInlineQuery',
     payload:
      { inline_query_id: '177471044005248298',
        results:
         '[
{"type":"gif","id":"Q2dBREFnQURGZ1FBQWd3VEFBRkxBQUdGMHNUeUVUVWxGZ1E=","gif_file_id":"CgADAgADFgQAAgwTAAFLAAGF0sTyETUlFgQ","title":"test","caption":""},{"type":"gif","id":"Q2dBQ0FnSUFBeGtCQUFFWDViTmVLZm9yU1h2Y05zX1hDdzJFeDg2MWtYdFNUd0FDemdZQUFveWpTVW1TOFhMN0V2QkRXaGdF","gif_file_id":"CgACAgIAAxkBAAEX5bNeKforSXvcNs_XCw2Ex861kXtSTwACzgYAAoyjSUmS8XL7EvBDWhgE","title":"test","caption":""}
]',
        cache_time: 0,
        next_offset: 'END' } } }

```

response:
```
{ ok: false,
     error_code: 400,
     description: 'Bad Request: RESULT_ID_INVALID' },
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. send a gif to you bot
2. use the file_id of that gif inside your answerInlineQuery

### Failure Logs

```
{ ok: false,
     error_code: 400,
     description: 'Bad Request: RESULT_ID_INVALID' },
```

**Comment by Piterden** [comment]
`next_offset: 0 + (PAGE_SIZE * PAGE_INDEX)`

https://core.telegram.org/bots/api#answerinlinequery

**Comment by TiagoDanin** [comment]
@el-lsan Your id result (`Q2dBQ0FnSUFBeGtCQUFFWDViTmVLZm9yU1h2Y05zX1hDdzJFeDg2MWtYdFNUd0FDemdZQUFveWpTVW1TOFhMN0V2QkRXaGdF`) has more than 50 characters. Fix with `.slice(0, 64)` :)

> id | String | Unique identifier for this result, 1-64 Bytes
> -- | -- | --

**Comment by el-lsan** [comment]
@TiagoDanin Yeah, that was exactly the problem.
Thanks for your reply.
