### ISSUE TITLE
inviteToChannel method

### ISSUE THREAD

**Issue by stepanmas** [telegraf/telegraf#873]
Implement the [_inviteToChannel_](https://core.telegram.org/method/channels.inviteToChannel), please.

**Comment by vlakam** [comment]
This doesn't look like bot api. Thus cannot be implemented in Telegraf at this moment.

**Comment by Piterden** [comment]
@stepanmas Look at these methods https://core.telegram.org/bots/api

**Comment by stepanmas** [comment]
> @stepanmas Look at these methods https://core.telegram.org/bots/api

How to use inviteToChannel using Telegraf?

**Comment by Piterden** [comment]
There's no way to do it!

**Comment by Piterden** [comment]
@stepanmas did you ever think about people may don't want you to add them somewhere?

**Comment by stepanmas** [comment]
> @stepanmas did you ever think about people may don't want you to add them somewhere?

I understand this, but I need this for my chat, not for spam.

**Comment by vlakam** [comment]
Consider using tdlib
