### ISSUE TITLE
⚡️ Unique File ID

### ISSUE THREAD

**Issue by NeroxFB** [telegraf/telegraf#876]
When to wait for an update to use file_unique_id?

**Comment by Piterden** [comment]
Why do you need to use it?

**Comment by NeroxFB** [comment]
For example, ctx.replyWithPhoto(unique_id....

вт, 4 февр. 2020 г. в 05:54, Denis Efremov <notifications@github.com>:

**Comment by Piterden** [comment]
What if you use `file_id`?

**Comment by NeroxFB** [comment]
I’ve used it, but it’s easy to use between different bots. Because they’ll have the same unique_id

**Comment by smaznet** [comment]
According telegram documents: 
Unique identifier for this file, which is supposed to be the same over time and for different bots. **Can't be used to download or reuse the file.**

**Comment by twoperkg** [comment]
Yes, it's indeed not possible to reuse the unique file id.  

Could someone point out what could be the use of a unique file id?

**Comment by KnorpelSenf** [comment]
Unique IDs can be used to find out whether two files are the same. That said, they are not useful in most cases for bots.
