### ISSUE TITLE
How to get new channel members?

### ISSUE THREAD

**Issue by sfanculatodinotte** [telegraf/telegraf#882]
So I write a bot that need to execute a method when a new user join to a channel. I added my bot as channel administrator, the problem is that this code:

    bot.on('new_chat_members', (ctx) => console.log(ctx.message.new_chat_members))

Only works for groups but not for channels. How can I execute a method when a new user join to channel where my bot Is linked to?

**Comment by Piterden** [comment]
Does API allow you to do it?

**Comment by sfanculatodinotte** [comment]
Hi @Piterden I wasn't able to find nothing in the documentation of Telegram, so I Guess there is no official way yet. I don't know why Telegram API lack on this

**Comment by sfanculatodinotte** [comment]
Hi @Piterden I was wondering if Is possibile get the updates of a specific Channel setting a webhook https://github.com/telegraf/telegraf/blob/develop/docs/examples/express-webhook-bot.js Is this actually possible?

**Comment by jacobwaller98** [comment]
@sfanculatodinotte I don't think Telegram would allow this given that regular users cannot see who is in a channel.

I think the best way to replicate this would be to have a group where no users except admins can post messages, from there it would be exactly the same as a normal group bot. but the behavior should emulate a channel closely enough?

That's the easiest way I can think to do it.

**Comment by sfanculatodinotte** [comment]
@jacobwaller98 I asked this because I created a paid TG channel, I also asked here: https://stackoverflow.com/questions/60027707/how-to-manage-invite-link-in-private-channel?noredirect=1#comment106284816_60027707

So essentially the feature I need avoid to use the invite link reset

**Comment by Piterden** [comment]
> I think the best way to replicate this would be to have a group where no users except admins can post messages, from there it would be exactly the same as a normal group bot. but the behavior should emulate a channel closely enough?

Moreover, you are able to emulate channel right inside your bot.

**Comment by sfanculatodinotte** [comment]
@Piterden there Is thing which is not clear for me. Essentially, the bot runs on a group here and emulate a channel. But, if someone start the bot it can send the message to the group. Should I check each time if the user is an admin of the group or there is another way?
