### ISSUE TITLE
AUDIO_TITLE_EMPTY error

### ISSUE THREAD

**Issue by natget21** [telegraf/telegraf#884]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version:3.24.0
* Node.js Version: 10.16.3
* Operating System: mac 10.13.6

## Expected Behavior

send audio file to the inline query

## Current Behavior

returns error 400 Bad Request : AUDIO_TITLE_EMPTY

## Failure Information (for bugs)

to send audio response for inline query i have the following code. which sends the audio if the audio that has been uploaded to telegram have an artist info if not it is sending error 
```

bot.on('inline_query', ({ inlineQuery, answerInlineQuery }) => { 
var  options = data.map((m,i) => { 
                    return { 
                        type: 'audio', 
                        id: i, 
                        audio_file_id: {telegram_audio_file_id}, 
                        title: "test", 
                        audio_duration:10, 
                        performer:"test", 
                        caption:"test"    
                    } 
                }) 
                return answerInlineQuery(options) 
})

```

### Failure Logs

Error: 400: Bad Request: AUDIO_TITLE_EMPTY
    at buildConfig.then.then.then.then (/..../node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: AUDIO_TITLE_EMPTY' },
  description: 'Bad Request: AUDIO_TITLE_EMPTY',
  parameters: {},
  on:
   { method: 'answerInlineQuery',
     payload: { inline_query_id: '938564299438758461', results: [Array] } } }

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#answerinlinequery

**Comment by natget21** [comment]
> https://core.telegram.org/bots/api#answerinlinequery

The replay is working well the problem is when the audio that is replayed doesn't have an artist name in the metadata it will response AUDIO_TITLE_EMPTY when trying to replay with that file_id even if the audio is already uploaded and is working

**Comment by Piterden** [comment]
> > https://core.telegram.org/bots/api#answerinlinequery
> 
> The replay is working well the problem is when the audio that is replayed doesn't have an artist name in the metadata it will response AUDIO_TITLE_EMPTY when trying to replay with that file_id even if the audio is already uploaded and is working

Did you read docs? You are passing wrong objects there
https://core.telegram.org/bots/api#inlinequeryresultaudio

**Comment by posti85** [comment]
I had the same problem and I've found out that it's related to the mp3 file, that hasn't the title ID3 tag defined in it. You could edit the mp3 file to define a title ([(here is how is done in Windows 10)](https://www.windowscentral.com/how-edit-music-metadata-information-windows-10), for example). But it also works without doing that, just sending the audio as a document:
```
{ 
  type: 'document', 
  document_file_id: '...',
  title: 'audio'
  ...
}
```

**Comment by KnorpelSenf** [comment]
@natget21 please consider closing this issue unless you still need to solve this problem.

**Comment by KnorpelSenf** [comment]
Please reopen if this is still an issue.
