### ISSUE TITLE
start scene and pass parameter into scene by callbackquery

### ISSUE THREAD

**Issue by Skull-Collector** [telegraf/telegraf#885]
hey im trying to start scene with SceneWizard and pass it an parameter when its started,
the parameter is always changing so i need to pass it into the current scene
i tried to do it with ctx.scene.session but in the scene its return undefined...

this is the code:

```
this is the wizard scene

profiledReview: new WizardScene('profiled-review',async (ctx)=>{
        var k = ctx.scene.session.user_id 
        await ctx.reply(`seller id :${k}`)
        await ctx.scene.leave();
    })

this is the method where im trying to pass the profiled-review scene the parameter "data[1]"

const startNewReview = async (ctx)=>{
    var data = ctx.callbackQuery.data.split('-');
    await ctx.scene.enter('profiled-review')
    ctx.scene.session.user_id = data[1];

}

this is the callback handling
bot.on('callback_query', async (ctx) => {
        if (ctx.callbackQuery.data.startsWith('new-')) return await startNewReview(ctx);
})
```
there result of ``` await ctx.reply(`seller id :${k}`) ``` is 'seller id: undefined'

how can i pass the data[1] value into the started session ?
thank you for you help guys..

**Comment by Piterden** [comment]
Why do you think `ctx.scene.session.user_id` should have a value?

**Comment by Matan-M** [comment]
@Piterden  i want to pass it a value to use it in the session it self thats why i tried to used that ctx.scene.session.user_id

there is another why to pass a parameter into wizardScene ?

**Comment by Matan-M** [comment]
@Piterden  can  you help me please to give me derection to handle this problem ?

**Comment by Piterden** [comment]
I can't until I will look at all your bot's code

**Comment by IMalyugin** [comment]
Just pass your session data as second param to ctx.scene.enter, it’ll automatically initialize ctx.scene.state

**Comment by KnorpelSenf** [comment]
Looks solved to me.
