### ISSUE TITLE
wrong remote file id specified: try to send file via telegram

### ISSUE THREAD

**Issue by harimambura** [telegraf/telegraf#886]
## Context

I'm trying to send local file via `ctx.telegram.sendDocument`.
Have next code:
`
await ctx.telegram.sendDocument(ctx.chat.id, {
			type: 'text/plain',
			media: {source: './test.txt', filename: 'test.txt'}
		});
`
As I debugged, everything should be ok, but response comes with the next error:
`
{
    ok: false,
    error_code: 400,
    description: 'Bad Request: wrong remote file id specified: Wrong character in the string'
  }
`

* Telegraf.js Version: 3.35.0
* Node.js Version: v12.14.0
* Operating System: Win 10

## Expected Behavior

File should be uploaded to chat

## Current Behavior

Error about wrong file id comes from telegram server

### Steps to Reproduce

1. siply run code provided

**Comment by Piterden** [comment]
https://core.telegram.org/bots/api#sending-files

**Comment by harimambura** [comment]
@Piterden so?)
I try to send local file and describe 'media' and 'type' properties (as I understand, 'type' is MIME type of file). And file id generates from random crypto bytes in method `attachFormValue()` of core/network/clinet.js, also here I saw only one way to send local file with `attachFormMedia()`, that takes generated id, and I couldn't provide any other id to send with file. And this logic already 

> Post the file using multipart/form-data in the usual way that files are uploaded via the browser.

 Am I doing something wrong?

**Comment by Piterden** [comment]
Yes, you are doing wrong things.

_There are three ways to send files (photos, stickers, audio, media, etc.):_

1. _If the file is already stored somewhere on the Telegram servers, you don't need to reupload it: each file object has a file_id field, simply pass this file_id as a parameter instead of uploading. There are no limits for files sent this way._
2. _Provide Telegram with an HTTP URL for the file to be sent. Telegram will download and send the file. 5 MB max size for photos and 20 MB max for other types of content._
3. _Post the file using multipart/form-data in the usual way that files are uploaded via the browser. 10 MB max size for photos, 50 MB for other files._

Where do you see something about local files here?

**Comment by harimambura** [comment]
Of course I am about point 3: Post the file using multipart/form-data - this is exactly about uploading files. And by telegraf clinet logic, that create multipart/form-data and readable file stream in request body, too

**Comment by harimambura** [comment]
so, that is part from telegraf client implementation a told about:
```
  if (media.source) {
    if (fs.existsSync(media.source)) {
      fileName = media.filename || path.basename(media.source)
      media.source = fs.createReadStream(media.source)
    }
    if (isStream(media.source) || Buffer.isBuffer(media.source)) {
      form.addPart({
        headers: { 'content-disposition': `form-data; name="${id}"; filename="${fileName}"` },
        body: media.source
      })
    }
  }
```

looks like it can upload files

**Comment by Piterden** [comment]
`fs.createReadStream` is the sync fabric, and above there is `res.body` passed to the same place. Maybe there is a little mistake?

**Comment by harimambura** [comment]
this is the captured request from telegraf:

```
POST /bot830191101:{BOT_ID}/sendDocument HTTP/1.1
content-type: multipart/form-data; boundary=e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463
connection: keep-alive
Accept: */*
User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
Accept-Encoding: gzip,deflate
Host: api.telegram.org
Transfer-Encoding: chunked

--e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463
content-disposition:form-data; name="method"

sendDocument
--e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463
content-disposition:form-data; name="chat_id"

{CHAT_ID}
--e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463
content-disposition:form-data; name="55815aae8b723fa3bc9290b60af37648"; filename="test.txt"

CONTENT
OF
TEST
FILE
--e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463
content-disposition:form-data; name="document"

{"type":"text/plain","media":"attach://55815aae8b723fa3bc9290b60af37648"}
--e59da4b0db8ff0aa332f8f85f0091964a42b465b69545ea893ade49aefdb5463--
```

Looks like file sent correctly, and now tg api returns new error:
```
{
	"ok": false,
	"error_code": 400,
	"description": "Bad Request: wrong remote file id specified: Wrong string length"
}
```

now I have no idea what's the problem

**Comment by harimambura** [comment]
And package 'node-telegram-bot-api' send files without problems, but uses 'request' lib instead of fetch.
I think there is no need of file_id when file path provided

**Comment by dotcypress** [comment]
@harimambura could you provide code example?

**Comment by harimambura** [comment]
@dotcypress 
Code is so simple, I use telegraf-inline-menu:
```
const app = new Telegraf(token);
const mainMenu = new TelegrafInlineMenu('menu');
...
mainMenu.simpleButton('Send file', 'snd', {
	doFunc: async ctx => {
		await ctx.replyWithDocument({ type: 'text/plain', media: 
			{
				source: './test.txt',
				filename: 'test.txt'
			} 
		});
		ctx.answerCbQuery();
	}
});
...
app.use(mainMenu.init());
app.startPolling();
```
I tried ```await ctx.replyWithDocument({ source: './test.txt', filename: 'test.txt' });```, result is below:
```
Failed to process updates. TelegramError: 400: Bad Request: there is no document in the request
    at async Promise.all (index 0) {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: there is no document in the request'
  }
```

**Comment by harimambura** [comment]
And this one works fine:
```
const Tg = require('node-telegram-bot-api');
const bot = new Tg(token, {polling: false});

const doc = require('fs').createReadStream('./test.txt');
bot.sendDocument(chatId, doc, {filename: 'test.txt'});
```

**Comment by latentstops** [comment]
Any news?

**Comment by KnorpelSenf** [comment]
Closing because outdated.
