### ISSUE TITLE
Question: How could i post message in channel via bot?

### ISSUE THREAD

**Issue by iKethavel** [telegraf/telegraf#889]
I've create bot and private channel. How could bot post messages to specific channel?

**Comment by jacobwaller98** [comment]
```
const Telegraf = require("telegraf");

let options = {
  channelMode: true    // Handle `channel_post` updates as messages (optional)
}

const bot = new Telegraf(BOT_TOKEN);

bot.on("message", ctx => console.log(ctx.chat.id));
```


Then send an update to the channel. In your console you should see an ID. That's the channel ID.

From there, if the bot is able to post messages to a channel, then:

`bot.telegram.sendMessage(CHANNEL_ID,"Hello, World!");`
should post that message to your channel.

**Comment by sfanculatodinotte** [comment]
@jacobwaller98 could you please take a look <a href="https://github.com/telegraf/telegraf/issues/882">here</a>?

**Comment by totalamd** [comment]
> channelMode: true    // Handle `channel_post` updates as messages (optional)

Where did you get this documentation?? I don't see it anywhere at https://telegraf.js.org/
