### ISSUE TITLE
fetchUpdates() blocks with long running update Handlers

### ISSUE THREAD

**Issue by Sheco** [telegraf/telegraf#892]
## Context

I am writing a bot that sleeps for some seconds before sending a reply, when using the polling mechanism, I noticed that the bot would stop fetching updates while there was an update handler that hadn't finished.

* Telegraf.js Version: 3.36.0
* Node.js Version: v10.15.2
* Operating System: Debian 10

## Expected Behavior

When executing an update handler that takes some time to finish, the bot should continue being able to get new updates using the polling mechanism.

## Current Behavior

The bot blocks and doesn't process anything up until the update handlers finish.

## Failure Information (for bugs)

The fetchUpdates() method in telegraf.js blocks on line 190 and doesn't pass the execution to the next block which calls fetchUpdates again.

### Steps to Reproduce

use this test.js file:
```
function sleep (ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
}   
      
const Telegraf = require('telegraf')
const bot = new Telegraf(process.env.BOT_TOKEN)
bot.start(async (ctx) => {
  ctx.reply('Sleeping')
  await sleep(5000)
  ctx.reply('Woke up')
})        
bot.launch()
```

1. launch the bot
```
BOT_TOKEN=1234:aaaaaaaaaaaaaaaaaa DEBUG=* node test.js
```
2. send two /start messages to the bot
3. see how the bot responds

### Failure Logs

```
--- current state, not working, two parallel messages
  telegraf:core Connecting to Telegram +0ms
  telegraf:client HTTP call getMe {} +0ms
  telegraf:core Launching @FabiCarbot +868ms
  telegraf:client HTTP call deleteWebhook {} +867ms
  telegraf:client HTTP call getUpdates?offset=0&limit=100&timeout=30 {} +321ms
  telegraf:core Bot started with long-polling +322ms
  telegraf:core Processing update 573133527 +10s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Sleeping' } +10s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Woke up' } +5s
  telegraf:client HTTP call getUpdates?offset=573133528&limit=100&timeout=30 {} +0ms
  telegraf:core Processing update 573133528 +6s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Sleeping' } +841ms
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Woke up' } +5s
  telegraf:client HTTP call getUpdates?offset=573133529&limit=100&timeout=30 {} +0ms

--- with my dont-wait-for-updates patch, two parallel messages
  telegraf:core Connecting to Telegram +0ms
  telegraf:client HTTP call getMe {} +0ms
  telegraf:core Launching @FabiCarbot +915ms
  telegraf:client HTTP call deleteWebhook {} +913ms
  telegraf:client HTTP call getUpdates?offset=0&limit=100&timeout=30 {} +189ms
  telegraf:core Bot started with long-polling +190ms
  telegraf:core Processing update 573133525 +12s
  telegraf:client HTTP call getUpdates?offset=573133526&limit=100&timeout=30 {} +12s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Sleeping' } +1ms
  telegraf:core Processing update 573133526 +2s
  telegraf:client HTTP call getUpdates?offset=573133527&limit=100&timeout=30 {} +2s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Sleeping' } +1ms
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Woke up' } +3s
  telegraf:client HTTP call sendMessage { chat_id: 14103853, text: 'Woke up' } +2s
```

**Comment by dotcypress** [comment]
@Sheco as I mentioned before this is Intended behavior. You must wait until all batch is processed.

**Comment by Sheco** [comment]
I am sorry, I wasn't aware and I can't find where you mentioned this before.

Where can I find more info about this?

**Comment by Sheco** [comment]
@dotcypress the same code (with a long running response with sleep()) works  fine with webHooks but fails with the polling mechanism.

Rejecting this patch would mean I would have to use webHooks, which is fine, but the polling mechanism feels easier when testing.

I am just curious as to what the undesired side effect of doing what I am proposing would be.

**Comment by dotcypress** [comment]
@Sheco side effects of that PR are simple:
- Breaking back-pressure support (bloating event-loop)
- Breaking FSM (Scenes, Stages, etc.) because updates may be handled in wrong order.

**Comment by nezort11** [comment]
@dotcypress  
> updates may be handled in wrong order.

1. So do webhook polling mechanism break bots?
2. And also when bot gets multiple new updates (after processing previous batch  or  on bot start)  it right now may process it in wrong order (by which is completed faster).

I agree wrong order of process in the same user chat is not good (in group it may be) , but it may be fixed so it will work at least for multiple users (right now it user 1 update is taking a lot of time, user 2 update is not getting processed at all because updates are not fetched).

(wrong order should be solved by things like https://github.com/KnightNiwrem/telegraf-throttler maxConcurrent property)
