### ISSUE TITLE
Sending messages "synchronously"

### ISSUE THREAD

**Issue by MarvinSkilla** [telegraf/telegraf#895]
I'd like to send some messages in a certain order (first sendMessage() should be the first Message to arrive in Telegram) but I haven't found a way to do so.

Here an example of what I want:
`bot.telegram.sendMessage(<chat_id>, 'Foo');`
`bot.telegram.sendMessage(<chat_id>, 'Bar');`
Expected message order of above in Telegram:
`Foo`
`Bar`
Actual Message order in Telegram (sometimes as expected):
`Bar`
`Foo`

I already tried it with setTimeout(), but that didn't change anyting:
`setTimeout(() => bot.telegram.sendMessage(<chat_id>, 'Foo'));`
`setTimeout(() => bot.telegram.sendMessage(<chat_id>, 'Bar'));`

**Comment by erkutorenk** [comment]
`const Telegraf = require('telegraf')

const bot = new Telegraf('process.env.BOT_TOKEN')

bot.on('message', async function(ctx) {
    await ctx.telegram.sendMessage(ctx.chat.id, 'Foo');
    await ctx.telegram.sendMessage(ctx.chat.id, 'Bar');
    }
);
bot.launch();
`

**Comment by erkutorenk** [comment]
```ruby
const Telegraf = require('telegraf')

const bot = new Telegraf('process.env.BOT_TOKEN')

bot.on('message', async (ctx) => {
    await ctx.telegram.sendMessage(ctx.chat.id, 'Foo');
    await ctx.telegram.sendMessage(ctx.chat.id, 'Bar');
    }
);

bot.launch();
```

**Comment by Sheco** [comment]
That's the correct answer.

**Comment by smaznet** [comment]
Answered in #863
