### ISSUE TITLE
Context.command does not support regex matching

### ISSUE THREAD

**Issue by Sheco** [telegraf/telegraf#898]
The documentation at https://telegraf.js.org/#/?id=context mentions that the ctx.match propery is available only for hears, command, action and inline queries, but it does not seem to be available in command queries.

**Comment by Piterden** [comment]
Why do you sure so?

**Comment by Sheco** [comment]
This test doesn't work:

```
const Telegraf = require('telegraf')
require('dotenv').config()
const bot = new Telegraf(process.env.BOT_TOKEN)

bot.command(/test (.*)/, (ctx) => {
  console.log(ctx.match)
})

bot.hears(/hello (.*)/, (ctx) => {
  console.log(ctx.match)
})

bot.launch()
```

In [telegraf.js](/telegraf.js) some of them use match() while .command doesn't

- [hears()](https://github.com/telegraf/telegraf/blob/f9df25ddd05bb3867c6b5713c7989ef00e5f1fae/composer.js#L266])
- [action()](https://github.com/telegraf/telegraf/blob/f9df25ddd05bb3867c6b5713c7989ef00e5f1fae/composer.js#L287)
- [inlineQuery()](https://github.com/telegraf/telegraf/blob/f9df25ddd05bb3867c6b5713c7989ef00e5f1fae/composer.js#L291)
- [command()](https://github.com/telegraf/telegraf/blob/f9df25ddd05bb3867c6b5713c7989ef00e5f1fae/composer.js#L269)

**Comment by SpineEyE** [comment]
Did you find a solution? Is it the same to use `hears()` or is hears somehow triggered differently? Not in group chats for example?

**Comment by Sheco** [comment]
> Did you find a solution? Is it the same to use `hears()` or is hears somehow triggered differently? Not in group chats for example?

I didn't find a built-in solution, so I just use parsed the command() message manually, I just hoped it worked automatically as suggested in the docs.

As far as I remember, hears() doesn't react when a user sends a command.

**Comment by wojpawlik** [comment]
It'd be trivial to just fix the docs and call it a day, but if someone (not me, unless #430) were to implement this, should `Composer.command` check the username before trying the regex, or should it leave username checking to library user?

**Comment by didkivskyy** [comment]
I just do it using **hears**:
`bot.hears(/\/command/, (ctx) => {
  console.log('User sent /command')
})`

**Comment by MKRhere** [comment]
Since Telegraf 4.12.0, `bot.command` supports RegExp
