### ISSUE TITLE
Problem with Bot Commands in Group 

### ISSUE THREAD

**Issue by sascha1337** [telegraf/telegraf#9]
Ive got a small problem. When my telegraf bot is inside a group, telegram shows this strange syntax of commands which is like following: /start is described as /start@MyBot.
This is a Telegram feature that multiple bots in one group can be accessed correctly ( e.g if two bots have /test as a command ) ...

But my bot.command('test') code doesnt reply to this syntax, so i would have to duplicate my command like this what seems not to be the right solution
 
     bot.command('link@FBExchangeBot', (ctx) => {

Could you implement routing this problem because this is a major bug that stops me pushing to production 

greets from germany !

<img width="647" alt="screen shot 2016-08-27 at 10 33 25" src="https://cloud.githubusercontent.com/assets/12372821/18026285/c7356ddc-6c41-11e6-85c9-5b077c995e4c.png">

**Comment by dotcypress** [comment]
Thank you for feedback 🍺 

Group/supergroup command handling landed in `2.8.0`
[Check out documentation](https://github.com/telegraf/telegraf/blob/master/docs/api.md#command-handling-in-groupssupergroups)
