### ISSUE TITLE
Multiple photos in one message

### ISSUE THREAD

**Issue by J0hnPreston** [telegraf/telegraf#906]
I have a simple code:

```
(async () => {
  ...
  bot.start(start);
  bot.on(['photo', 'document'], (ctx) =>
    console.log(
      `\nGetting ctx in PHOTO => `,
      JSON.stringify(ctx.message.photo),
    ),
  );

  bot.catch((err, ctx) => {
    console.log(`Ooops, encountered an error for ${ctx.updateType}`, err);
  });
  bot.launch();
})();
```
Why does the handler (_['photo', 'document']_) fire twice? Photos are sent in one message. How to fix it?

**Comment by Piterden** [comment]
How many photos?

**Comment by J0hnPreston** [comment]
> How many photos?

2

**Comment by smaznet** [comment]
this isn't telegraf bug

That's because media group messages sent separately to bots

**Comment by AguChaves92** [comment]
wait but how do you do it, how do you send multiple pictures as a single message with a caption?

**Comment by MKRhere** [comment]
@AguChaves92 Please don't bump unrelated old issues. Open new issue/discussion in the future.

If you use `ctx.sendMediaGroup` and one of the photos has a caption, it appears as the media group caption.
