### ISSUE TITLE
Make users communicate in the chatbot

### ISSUE THREAD

**Issue by mynameismental** [telegraf/telegraf#908]
I'm new using this framework, I wonder if it is possible to make two users communicate with each other IN the bot. EXAMPLE: User 1 starts a ticket request, the ticket request arrive to Admin, which is user 2, the admin accept the ticket and then, when the admin types something in the chatbot, that text arrives to the user 1, and when the user1 types something in the chatbot, that will arrive to Admin.

**Comment by sfanculatodinotte** [comment]
I'm looking for a symilar solution too. I tried Livegram but I want make my own solution

**Comment by Piterden** [comment]
I did it already. It is achievable with standard methods. Here is [the example](https://github.com/Piterden/chessbot/blob/backup/src/handlers/message/index.js)

**Comment by mynameismental** [comment]
> I did it already. It is achievable with standard methods. Here is [the example](https://github.com/Piterden/chessbot/blob/backup/src/handlers/message/index.js)

Thanks a lot !!
