### ISSUE TITLE
Retry sendMessage on failure

### ISSUE THREAD

**Issue by DamiToma** [telegraf/telegraf#909]
**Is your feature request related to a problem? Please describe.**
`Telegram.sendMessage` might reject for various reasons, it happened to me that some requests timed out. This kind of failures tend to be isolated, meaning that sending a new request right after will almost certainly work.

**Describe the solution you'd like**
I modified `Telegram.sendMessage` so that, in case of a failure, it tries to send the message again `n` times before rejecting. The maximum number of calls allowed before rejecting the Promise could be set as an option passed to the constructor.

**Describe alternatives you've considered**
We could use a context middleware so that `ctx.telegram.sendMessage` implements the retry, but this would not override `Telegraf.telegram.sendMessage`.

**Additional context**
The retry is implemented by recursively calling `sendMessage` on rejection, [here is the code](https://github.com/telegraf/telegraf/files/4205244/sendMessage.txt).

Please let me know whether this is an interesting feature to add, in that case I will create a pull request.

**Comment by dotcypress** [comment]
Not sure that we need this in Telegraf core. Anyway, you can create a library for that
