### ISSUE TITLE
cannot use http urls as source for thumbnail and media

### ISSUE THREAD

**Issue by smaznet** [telegraf/telegraf#912]
I got this error when i use http:// urls for media source
**Protocol "http:" not supported. Expected "https:"**

And that's come from [This line](https://github.com/telegraf/telegraf/blob/f9df25ddd05bb3867c6b5713c7989ef00e5f1fae/core/network/client.js#L161)  **because you used https.Agent** as parameter for fetch

**Comment by dotcypress** [comment]
Not a bug, we enforced SSL by default. You can use any HTTP client to download files via HTTP and then send
