### ISSUE TITLE
Send big files

### ISSUE THREAD

**Issue by n3nikita** [telegraf/telegraf#913]
## Context

I get an error when trying to sendDocument over 200mb size.

## Expected Behavior

I need to send files over 200mb size.

## Current Behavior

I get an error. 
```javascript
Unhandled rejection Error: 413: Request Entity Too Large
    at ...\telegraf\core\network\client.js:281:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Steps to Reproduce

```javascript
await ctx.replyWithDocument({
          url: 'https://bigfile.com/',
          filename: 'file.zip'
        });
```

**Comment by LetItCode** [comment]
Bots can currently send files of any type of up to 50 MB in size, this limit may be changed in the future.

https://core.telegram.org/bots/api#senddocument

**Comment by Hi7cl4w** [comment]
Unfortunately, the official API has some limitations you can send only up to 50 MB. but there is a `workaround ` for this this way you can send a large file up to 2GB.

https://github.com/tdlib/telegram-bot-api

You can `build and install` this to your server by following the instructions on this link https://tdlib.github.io/telegram-bot-api/build.html 

basic setup :

 1. Generate Telegram Applications id from https://my.telegram.org/apps
 2. Start the server `./telegram-bot-api --api-id=<your-app-id> --api-hash=<your-app-hash> --verbosity=20` 
 3. Default address is http://127.0.0.1:8081/ and the port is 8081.
 4. All the official APIs will work with this setup. Just change the address to http://127.0.0.1:8081/bot<token>/METHOD_NAME reference: https://core.telegram.org/bots/api

Example Typescript Code using axios: 


```typescript
import axios from 'axios';
import FormData from 'form-data';
import { createReadStream } from 'fs';

  async function sendLargeVideoFile(
    chatId: string 
    path: string,
  ): Promise<any> {
    const formData = new FormData();
    formData.append('chat_id', chatId);
    formData.append('video', createReadStream(path));
    formData.append('supports_streaming', 'true');
    return await axios
      .post(
        `http://127.0.0.1:8081/bot${process.env.BOT_TOKEN}/sendVideo`,
        formData,
        {
          headers: { 'Content-Type': 'multipart/form-data' },
        },
      )
```

Hope this helps.
