### ISSUE TITLE
replyWithContact is missing in docs and not works properly.

### ISSUE THREAD

**Issue by rufat** [telegraf/telegraf#916]
## Context

* Telegraf.js Version: 3.36.0
* Node.js Version: 12.7.0
* Operating System: Windows 10

## Expected Behavior

"replyWithContact" is not listed in the documentation and doesn't work properly.

## Current Behavior

It returns sometimes "Error: 429: Too Many Requests: retry after 84754".

**Comment by KnorpelSenf** [comment]
May be related to #1046

**Comment by KnorpelSenf** [comment]
May be fixed by #1205
