### ISSUE TITLE
bot.hears

### ISSUE THREAD

**Issue by ssow** [telegraf/telegraf#919]
Greetings,

I'd like to understand the following construct from the exemple-bot.js :

const { reply, fork } = Telegraf
const sayYoMiddleware = fork((ctx) => ctx.reply('yo'))

// Text messages handling
bot.hears('Hey', sayYoMiddleware, (ctx) => {
  ctx.session.heyCounter = ctx.session.heyCounter || 0
  ctx.session.heyCounter++
  return ctx.replyWithMarkdown(`_Hey counter:_ ${ctx.session.heyCounter}`)
})

-------------------------
Here the hears method as 3 arguments (how is that allowed) and I can't figure out how these parameters are handled by the method.
If I put the sayYoMiddleware after the named function the 'yo' message is not displayed/sent.

Thank you in advance.

**Comment by Ryabikovalex** [comment]
Check offical [docs](https://telegraf.js.org/#/?id=telegraf-hears)
>  Generates middleware for handling text messages with regular expressions.
`Telegraf.hears(triggers, ...middleware) => function`

`...middleware` allows you to handle message with several functions.
Three dots is feature introduced in ES6.
