### ISSUE TITLE
starting bot

### ISSUE THREAD

**Issue by mortazakiyani** [telegraf/telegraf#926]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version:3.32
* Node.js Version:13.9
* Operating System:windows 10

## Expected Behavior

running bot

## Current Behavior

faild to  running bot

## Failure Information (for bugs)

when i write npm bot.js  on my console to start the bot nothing happened for a moment and after a few  seconds i get the log (i put in log sections) on my console and still my bot does not work

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install node.js 
2. copy and paste example from your page and replace tokken 
3. i got nothing..

### Failure Logs

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\morta\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

**Comment by jacobwaller** [comment]
start the bot using one of these commands:
`node bot.js`
or
`npm start`
