### ISSUE TITLE
/command match in middle of texts

### ISSUE THREAD

**Issue by gugiserman** [telegraf/telegraf#93]
I noticed the handler function of my `/list` command is being called even if the message doesn't start with `/list`.

e.g.: `foo /list bar`

Is this intended behaviour?
I'm currently writing code to prevent this.

Thanks

**Comment by dotcypress** [comment]
Hey.

Command handling based on [Telegram server response](https://github.com/telegraf/telegraf/blob/develop/lib/core/composer.js#L138)

Additional info: https://core.telegram.org/bots/api#messageentity

But you can use `hear` method:
```js
bot.hear('/list', (ctx) => ...)
bot.hear(/^\/list/g, (ctx) => ...)
```

**Comment by gugiserman** [comment]
Thanks mate :)
