### ISSUE TITLE
Incorrect upload of file filename with ;

### ISSUE THREAD

**Issue by GeovaneSchmitz** [telegraf/telegraf#934]
## Context
In some cases, file names are truncated, sending files with names containing ; are cut in ;
E.g send file with name 'abc;.txt' is sent as 'abc'

* Telegraf.js Version: 3.36.0
* Node.js Version: v12.14.0
* Operating System: Arch (Linux) and Ubuntu Docker image

## Expected Behavior

Correct file name with ';', send file with name k without cutting
E.g send file with name 'abc;.txt' is sent as 'abc;.txt'

## Current Behavior

Sending files with names containing ; are cut in ;
E.g send file with name 'abc;.txt' is sent as 'abc'

### Steps to Reproduce

- Create a file with ; in the name
- Send a file with ; in the name

E.g
```javascript

const path = require('path')
const Telegram = require('telegraf/telegram')

const telegram = new Telegram(process.env.BOT_TOKEN)

telegram.sendDocument(process.env.CHAT_ID, {
  source: path.resolve('./file;.txt') // A file with ';' in the name
})

// OR

telegram.sendDocument(process.env.CHAT_ID, {
  source: path.resolve('./file.txt'),
  filename: 'file;.txt' // filename name with ';'
})
```
![result](https://user-images.githubusercontent.com/29206637/76132934-430ff680-5ff4-11ea-910f-fc14d0065d39.png)
This snippet sends 2 files with the name 'file' and not 'file;.txt'

**Comment by GeovaneSchmitz** [comment]
Maybe this bug is with the Telegram and not the Telegraf

**Comment by BRA1L0R** [comment]
Not an issue with telegram apparently, I tested uploading a file with an ; and i succesfully uploaded it without problem.

**Comment by BRA1L0R** [comment]
I'll try to do some research and see if I can find something in the code

**Comment by BRA1L0R** [comment]
well, I investigared on the issue and found out that telegraf doesn't encode the header. I'm trying to implement the RFC 5987 standard with the encoded filename right now and I'm currently working on it

**Comment by KnorpelSenf** [comment]
Any updates on this?

**Comment by wojpawlik** [comment]
Before I can label this as a bug, I need to upload a file with semicolon in name to Bot API, how can I do that?

```
~/JS/telegraf
$ curl --form 'document=@"test%3B.js"' --form 'chat_id=197767148' https://api.telegram.org/bot$BOT_TOKEN/sendDocument
curl: (26) Failed to open/read local data from file/application

[26] ~/JS/telegraf
$ curl --form 'document=@"test;.js"' --form 'chat_id=197767148' https://api.telegram.org/bot$BOT_TOKEN/sendDocument
{"ok":true,"result":"[REDACTED FOR BREVITY]"}
```

![obraz](https://user-images.githubusercontent.com/23058303/102696926-3cc0d300-4232-11eb-9629-c79528f83593.png)

**Comment by wojpawlik** [comment]
I wouldn't mind delegating multipart stream logic to another package (especially if current implementation has a bug), is there one that has tests and [not many dependencies](http://npm.anvaka.com/#/view/2d/telegraf)? Nice to have: TypeScript typings, high performance, Deno support.

**Comment by KnorpelSenf** [comment]
I read somewhere that it has something to do with how HTTP headers are encoded and that ; needs to be escaped in them, but I cannot find the source anymore, so perhaps that does not help. Definitely needs more investigation.

**Comment by joeyave** [comment]
Is there any workaround before you've pushed a fix?

**Comment by GeovaneSchmitz** [comment]
Hi,

> Maybe this bug is with the Telegram and not the Telegraf

I put this hypothesis, because when a file has a semicolon the browser sends exactly the semicolon, I made an [gist](https://gist.github.com/GeovaneSchmitz/b668e6668aa206bccb9ebcb229fc7220) that shows this.
If you run and choose an empty file, what firefox and chrome will send is this:
```
-----------------------------346825488627071920482065471512
Content-Disposition: form-data; name="multipleFiles"; filename="test;.jpg"
Content-Type: image/jpeg


-----------------------------346825488627071920482065471512--
```
And if you debug the project, you'll realize that what it sends is the same thing.
https://github.com/telegraf/telegraf/blob/57f16c70901e3c73b9ab67933a926fedf7a2b11d/src/core/network/client.ts#L219
I think we just need to escape the quotes and the problem with semicolons doesn't belong to us.

**Comment by wojpawlik** [comment]
https://github.com/tdlib/td/issues/1459
