### ISSUE TITLE
is there contact handling?

### ISSUE THREAD

**Issue by noob9590** [telegraf/telegraf#935]
i searched for phone number handling but the only thing i saw that bot.on('contact', function).
is there another handling for the last contact number that the bot received?
not just for any contact number that sent in the bot...
please advise!
thanks

**Comment by KnorpelSenf** [comment]
You can either use `.on('contact')` to handle receiving contacts from users, or access the `message_entities` on the message object to handle phone numbers inside regular text messages and captions.
