### ISSUE TITLE
typings: incorrect bindings

### ISSUE THREAD

**Issue by SwapnilSoni1999** [telegraf/telegraf#943]
The typings are not working correctly as expected
the IntelliSense is working when `const Telegraf = require('telegraf').Telegraf` is done which is not correct and its throwing error
but it does shows suggestions in vscode
![image](https://user-images.githubusercontent.com/25403317/77200225-243f5300-6b10-11ea-972f-a709e487abb8.png)
 
working behavior should be without `require('telegraf').Telegraf` this extra `.Telegraf` thing

* Telegraf.js Version: 3.36.0
* Node.js Version: 13.11.0
* Operating System: ArchLinux

## Expected Behavior
it should work without `.Telegraf import`. but in this case its not showing with normal method provided in documentation 
![image](https://user-images.githubusercontent.com/25403317/77200446-90ba5200-6b10-11ea-9515-4cb230670338.png)

## Current Behavior
Current behaviour throws error with `const Telegraf = require('telegraf').Telegraf`
```js
const bot = new Telegraf(process.env.BOT_TOKEN);
            ^

TypeError: Telegraf is not a constructor
    at Object.<anonymous> (/home/sonisins/prujekts/node/gamerary-tg-bot/bot.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by wojpawlik** [comment]
This problem arises because `telegram.js` uses `module.exports =`, while `typings/index.d.ts` uses named `export` instead of `export =`.

However, `export =` disallows all other exports, so `typings/index.d.ts` would have to be revamped.

I'm willing to fix this, but only after my much more straightforward #939 gets merged.

**Comment by SwapnilSoni1999** [comment]
> This problem arises because `telegram.js` uses `module.exports =`, while `typings/index.d.ts` uses named `export` instead of `export =`.
> 
> However, `export =` disallows all other exports, so `typings/index.d.ts` would have to be revamped.
> 
> I'm willing to fix this, but only after my much more straightforward #939 gets merged.

So what hack I'm using currently is to set a `RUN` env so that it requires telegraf without the `.Telegraf` object.
I hope they will fix this soon.

**Comment by wojpawlik** [comment]
While (worryingly) waiting for #939, we started overhauling the typings at https://github.com/thedevs-network/telegraf.ts. @dotcypress, when we're done, would you rather we:

1. Bring the improved typings back to this repo?
2. Take over typings and make `telegraf.ts` a dependency?

Either way, `index.d.ts` will be replaced, so it makes no sense to merge further improvements to typings; I'll backport them instead.

**Comment by SwapnilSoni1999** [comment]
damn I hope they will merge the changes and fix typings that hack I've mentioned is not working I have to change require statement everytime which is super annoying

**Comment by Edgar-P-yan** [comment]
Hi @SwapnilSoni1999  !
You can always add some JSDocs to make IntelliSense work:
```js
/** @type {typeof import('telegraf').Telegraf} */
const Telegraf = require('telegraf');
``` 
Hope it helps :)

**Comment by SwapnilSoni1999** [comment]
> ```js
> /** @type {typeof import('telegraf').Telegraf} */
> const Telegraf = require('telegraf');
> ```

omg! thanks alot <3

**Comment by ghost** [comment]
**This works for me.**

`const { Telegraf } = require("telegraf");

**Comment by SwapnilSoni1999** [comment]
> **This works for me.**
> 
> `const { Telegraf } = require("telegraf");

this is fixed since one and half year though 
Thanks for responding :3
