### ISSUE TITLE
Add basic keyboard interaction examples

### ISSUE THREAD

**Issue by antony** [telegraf/telegraf#946]
**Is your feature request related to a problem? Please describe.**
The documentation for this project lacks examples of basic interaction - waiting for a command, throwing up a keyboard, and doing something else on receipt of an answer. Basic interaction, which is what bots are all about, is extremely difficult to find. After an hour of trawling the docs and examples, I'm still none the wiser.

**Describe the solution you'd like**
Just some basic examples would be great. Everything past simply calling a single command in the docs involves going to a github repository of hugely complex examples/existing projects, and trying to understand the architecture of them, and find what you need, and I can never find it.

**Describe alternatives you've considered**
I've used telegraf before in the early days, and it seemed to have simpler, more basic examples

**Comment by ailinykh** [comment]
Hi! You can find a lot of examples in [keyboard-bot](https://github.com/telegraf/telegraf/blob/master/docs/examples/keyboard-bot.js)

**Comment by antony** [comment]
Hi @ailinykh @dotcypress 

Sorry I didn't spot the reply earlier. The examples in keyboard bot aren't suitable. There isn't a clear example of:

How to accept input and then reply based on that input. I can see that it requires use of scenes, but it's very unclear, so unclear in fact that I haven't figured out how to do it yet (all my users end up with keyboards stuck on their screen).

The example in keyboard-bot is too trivial - it works for a single bot and single human, but this is rarely the case.
