### ISSUE TITLE
How to display message using acl? 

### ISSUE THREAD

**Issue by sfanculatodinotte** [telegraf/telegraf#948]
I using the `acl` middleware for enable my bot commands only to admin, I would like to show an error message if the user is not an admin, what I did is:

    const { acl } = require('telegraf')

    const adminIds = [444, 222, 666]

    // Admin command example
    bot.command('admin', acl(
      adminIds
      (ctx) => ctx.reply('Done')
    ))

if an user is not admin, then nothing is displayed, is possible do this?

**Comment by ailinykh** [comment]
You could use you own middleware to handle this
```js
bot.command('admin', acl((ctx) => {
    if (!adminIds.includes(ctx.message.from.id)) {
        return ctx.reply('Access denied!')
    }

    return ctx.reply('Done!')
}))
```

**Comment by ailinykh** [comment]
You could write your own acl middleware
```js
const acl = async (ctx, next) => {
    if (!adminIds.includes(ctx.message.from.id)) {
        return ctx.reply('Access denied!')
    }
    
    return next(ctx)
}

bot.command('admin', acl, (({ reply }) => reply('done!')))
```

**Comment by mortezae** [comment]
@sfanculatodinotte acording to [composer.js#L295](https://github.com/telegraf/telegraf/blob/0cb042a1035a0175e35e60187af117c300fa0c2d/composer.js#L295), it seems we can do more advanced works with acl.

**Comment by mortezae** [comment]
For this purpose best practice is to use `Composer` and `Composer.acl`.
In the following code, we defined `/admin` command for `admin` and `public` separately.

```javascript
const Composer = require('telegraf/composer')

const adminIds = [444, 222, 666]

var admin = new Composer();
admin.command("admin", (ctx) => ctx.reply('Done'));

var public = new Composer();
public.command("admin", (ctx) => ctx.reply('Access denied'));
public.command("public_command", ctx.reply('Anybody can use this command'));


// for admins only.
bot.use(Composer.acl(adminsIds, admin)); // Note: It must come before bot.use(public) for admins to get 'Done' intead of 'Access denied'

// for all users
bot.use(public);
```
