### ISSUE TITLE
How to edit a sended message?

### ISSUE THREAD

**Issue by sfanculatodinotte** [telegraf/telegraf#950]
I wrote a bot which sent a message to a group, essentially the interesting line is the following:

     ctx.telegram.sendMessage(
                process.env.GROUP_ID,
                ctx.message.text
            );

this is actually working, but I have a question: suppose that I did a mistake on the message sent, is there a way to update the message to the group? Thanks

**Comment by Yashko** [comment]
Yes, you can update a message.

`sendMessage` function returns a promise. If the message was sent successfully, you can retrieve `message_id` and save it. Afterwards you can use `editMessageText` function. You need to know `chat_id` and `message_id` to update sent messages.

Ref: https://telegraf.js.org/#/?id=editmessagetext
