### ISSUE TITLE
Telegraf with firebase realtime database not working in AWS

### ISSUE THREAD

**Issue by J053Fabi0** [telegraf/telegraf#953]
## Context

* Telegraf.js Version: 3.36
* Node.js Version: 12.16.1

## Expected Behavior

Bot in AWS with firebase should send the value of the realtime database only once when asked.

## Current Behavior

The bot is sending the value from the firebase realtime database indefinitely without stopping.

### Steps to Reproduce

1. Create Lambda function (ZIP node_modules and all neccessary files like index.js) and set BOT_TOKEN environment variable to secret token given by BotFather.
1.2 `index.js` must be: 
```
const Telegraf = require('telegraf');
require('dotenv').config();
const bot = new Telegraf(process.env.TOKEN);

require('dotenv').config();
const firebase = require('firebase');
 
const app = firebase.initializeApp({
  apiKey: process.env.APIKEY,
  authDomain: process.env.AUTHDOMAIN,
  databaseURL: process.env.DATABASEURL,
  projectId: process.env.PROJECTID,
  storageBucket: process.env.STORAGEBUCKET,
  messagingSenderId: process.env.MESSAGINGSENDERID,
  appId: process.env.APPID
});

bot.use((ctx, next) => {
  // console.log(ctx.update.message.sticker) // Stickers
  // console.log(ctx.update);
  const rootRef = firebase.database().ref();
  let ordersRef = rootRef.child("last");

  ordersRef.once('value', function (dataSnapshot) {
    let data = dataSnapshot.val();
    ctx.reply(data);
  })
  next(ctx)
})

exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body); // get data passed to us
  bot.handleUpdate(tmp); // make Telegraf process that data
  return callback(null, { // return something for webhook, so it doesn't try to send same stuff again
    statusCode: 200,
    body: '',
  });
};
```
2. Create API Gateway -> Add method POST -> Lambda Function -> Deploy -> Copy invoke url
3. Set invoke URL as webhook

Maybe the return value of the handler is not being sended to Telegram Servers so they keep sending the same message?

**Comment by ailinykh** [comment]
> The bot is sending the value from the firebase realtime database indefinitely without stopping.
Try to log all the `handler` invocations, cause that is suspicious. As soon as you using webhook it might be helpful

```js
bot.use((ctx, next) => {
  // console.log(ctx.update.message.sticker) // Stickers
  // console.log(ctx.update);
  const rootRef = firebase.database().ref();
  let ordersRef = rootRef.child("last");

  ordersRef.once('value', function (dataSnapshot) {
    let data = dataSnapshot.val();
    ctx.reply(data);
  })
  next(ctx)
})
```
You have put `reply` in a middleware, so it will be called on **every** update. Please consider to use more plain methods such as `bot.command` or `bot.hears`


And one more tip. May be you want to reply to webhook request using existing callback function?
```js
exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  return bot.handleUpdate(tmp, callback);
};
```

You can find more information about webhooks and firebase/aws here: #917 #797 #98

**Comment by J053Fabi0** [comment]
I tried some simple example to test your code and tip about the `return`. I guess I'm not doing it right. This is my code and the error it gives me:
```
const Telegraf = require('telegraf');
require('dotenv').config();
const bot = new Telegraf(process.env.TOKEN);

bot.hears('Hi', ctx => {
  return ctx.reply("Hi");
});

exports.handler = (event, context, callback) => {
  return bot.handleUpdate(event.body, callback);
};
```
`Cannot use 'in' operator to search for 'callback_query' in {\"update_id\":862840803,\n\"message\":{\"message_id\":4781,\"from\":{\"id\":861617600,\"is_bot\":false,\"first_name\":\"Jose Fabio\",\"username\":\"Jose_Fabio\",\"language_code\":\"es\"},\"chat\":{\"id\":861617600,\"first_name\":\"Jose Fabio\",\"username\":\"Jose_Fabio\",\"type\":\"private\"},\"date\":1585603163,\"text\":\"valor\"}}",
`

**Comment by ailinykh** [comment]
My fault! You still need to parse json
```js
const tmp = JSON.parse(event.body); // get data passed to us
return bot.handleUpdate(tmp, callback);
```

**Comment by J053Fabi0** [comment]
Now the error is:
```
{
    "errorType": "TypeError",
    "errorMessage": "response.setHeader is not a function",
    "stack": [
        "TypeError: response.setHeader is not a function",
        "    at answerToWebhook (/opt/nodejs/node_modules/telegraf/core/network/client.js:194:16)",
        "    at Telegram.callApi (/opt/nodejs/node_modules/telegraf/core/network/client.js:253:14)",
        "    at Telegram.sendMessage (/opt/nodejs/node_modules/telegraf/telegram.js:71:17)",
        "    at TelegrafContext.reply (/opt/nodejs/node_modules/telegraf/context.js:314:26)",
        "    at /var/task/index.js:6:14",
        "    at /opt/nodejs/node_modules/telegraf/composer.js:143:56"
    ]
}
```
The code is the same, except for this line:
```
exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  return bot.handleUpdate(tmp, callback);
};
```

**Comment by J053Fabi0** [comment]
I changed that block of code to:
```
exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  return bot.handleUpdate(tmp, callback.response);
};
```
But now the problem is that is doing the same thing as with firebase, is constantly sending the response:
[![Captura-de-pantalla-2020-03-31-06-44-11.png](https://i.postimg.cc/gjxDfYXZ/Captura-de-pantalla-2020-03-31-06-44-11.png)](https://postimg.cc/rRLx429V)

**Comment by J053Fabi0** [comment]
I notice something:
While this code works just fine:
```
const Telegraf = require('telegraf');
require('dotenv').config();
const bot = new Telegraf(process.env.TOKEN);

const firebase = require('firebase');
const app = firebase.initializeApp({
  apiKey: process.env.APIKEY,
  authDomain: process.env.AUTHDOMAIN,
  databaseURL: process.env.DATABASEURL,
  projectId: process.env.PROJECTID,
  storageBucket: process.env.STORAGEBUCKET,
  messagingSenderId: process.env.MESSAGINGSENDERID,
  appId: process.env.APPID
});

bot.command('value', (ctx) => {
//  const rootRef = firebase.database().ref();
  ctx.reply("Hello")
})

exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  bot.handleUpdate(tmp);
  return callback(null, {
    statusCode: 200,
    body: '',
  });
};
```

By uncommenting the reference, it starts failing, replying "Hello" a lot if times.

**Comment by theghostbel** [comment]
> By uncommenting the reference, it starts failing, replying "Hello" a lot of times.

When you see a lot of repeating answers, it means that Telegram resends failed hooks and your bot responded to them. 
1. Check [WebhookInfo](https://core.telegram.org/bots/api#webhookinfo) for `pending_update_count` prop
2. Add some `nonce/hash/timestamp` to all your responses to see if you're getting the same message

When your code starts working ok you'll stop to see this problem, and it's quite often when you are in a process of bot development.

**Comment by J053Fabi0** [comment]
The WebhookInfo is saying `"last_error_message": "Wrong response from the webhook: 502 Bad Gateway"`.

**Comment by peteraiken** [comment]
I am terrifically late to this @J053Fabi0, but I had this exact issue and could not for the life of me solve it. I eventually did by changing:
```
exports.handler = (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  bot.handleUpdate(tmp);
  return callback(null, {
    statusCode: 200,
    body: '',
  });
};
```
to
```
exports.handler = async (event, context, callback) => {
  const tmp = JSON.parse(event.body);
  bot.handleUpdate(tmp);
  return await callback(null, {
    statusCode: 200,
    body: '',
  });
};
```

My app was returning a Promise to Telegram instead of the `{ statusCode: 200 }` it wants, so by awaiting it I was able to correctly send that correct code to Telegram, which lets it acknowledge the request has been processed. Not sure if this helps you, but that was my issue at least.
