### ISSUE TITLE
Trigger command again when message is edited

### ISSUE THREAD

**Issue by Tiim** [telegraf/telegraf#954]
**Is your feature request related to a problem? Please describe.**
I have a bot that fetches information when people type commands. When
used on desktop often instead of typing the whole command again from new I want 
to edit the last command (arrow up on desktop), and trigger the command on the bot again.

**Describe the solution you'd like**

Allowing the `bot.command` method to have a third option
with a config object, something like that:

```js
bot.command('events', onEventsCmd, { triggerOnEdit: true });

...
function onEventsCmd(ctx) {
  const msg = ctx.message || ctx.editedMessage;
  ...
}
```

**Comment by ailinykh** [comment]
Why not to use a middleware?
```js
bot.use((ctx, next) => {
  ctx.message = ctx.message || ctx.editedMessage;
  return next(ctx)
})
```

**Comment by dotcypress** [comment]
@Tiim I don't think this isn't a good design because it implies some magic inside. If you want to process message editing - just implement handler for `edited_message`

**Comment by Tiim** [comment]
How would I build such a middleware that triggers the correct command handler?
Can i modify the context so telegraf treats it like a usual message?
