### ISSUE TITLE
TypeScript problem with agent option.

### ISSUE THREAD

**Issue by HouCoder** [telegraf/telegraf#955]
Hi, I want to use this package through my local socks proxy, so I passed the `agent` option in the constructor:

```ts
import Telegraf from 'telegraf';
import { SocksProxyAgent } from 'socks-proxy-agent';

const key = '';
const proxy = 'socks://127.0.0.1:7891';
const allowedUsers = [''];
const bot = new Telegraf(key, {
    telegram: {
        agent: new SocksProxyAgent(proxy),
    }
});
```
but TypeScript checker keeps telling me this error at line 9:

```
No overload matches this call.
  Overload 1 of 3, '(token: string, options?: TelegrafOptions | undefined): Telegraf<ContextMessageUpdate>', gave the following error.
    Property 'options' is missing in type 'SocksProxyAgent' but required in type 'Agent'.
  Overload 2 of 3, '(...middlewares: Middleware<ContextMessageUpdate>[]): Composer<ContextMessageUpdate>', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'Middleware<ContextMessageUpdate>'.ts(2769)
https.d.ts(21, 9): 'options' is declared here.
```

I checked the typing file, possible to change https://github.com/telegraf/telegraf/blob/develop/typings/index.d.ts#L14 to `  agent?: Agent | SocksProxyAgent`?

Related topic - https://github.com/telegraf/telegraf/issues/63#issuecomment-465130505

**Comment by HouCoder** [comment]
Change the `agent` option to `agent: new https.Agent({keepAlive: true})` works, but I want to use `socks-proxy-agent` package to send/receive messages though my local socks5 proxy.

**Comment by Edgar-P-yan** [comment]
Hi!
I submitted a PR which fixes this issue, but for now you can avoid the error by manually casting the type

```ts
const bot = new Telegraf(key, {
  telegram: {
    agent: new SocksProxyAgent(proxy) as any,
  }
});
```

**Comment by HouCoder** [comment]
Many thanks, @Edgar-P-yan, I'm currently using `@ts-ignore-start` to disable this error.
