### ISSUE TITLE
Why should I press a button twice to make it work?

### ISSUE THREAD

**Issue by DenRamus** [telegraf/telegraf#958]
Why should I press a button twice to make it work?

`
const Telegraf = require('telegraf');
const Telegram = require('telegraf/telegram')
const WizardScene = require('telegraf/scenes/wizard');
const { Markup } = Telegraf;
const Composer = require('telegraf/composer')
const config = require('../config.json');
const telegram = new Telegram(config.token);

const stepHandler = new Composer();

stepHandler.action('checkAdmin', (ctx) => {  
    
});

const channelAddWizard = new WizardScene(
    'channel-add',
    ctx => {
      ctx.wizard.state.data = {};
      ctx.reply("Введите username вашего канала, подробности смотрите в инструкции выше");
      return ctx.wizard.next();
    },

    ctx => {
      ctx.wizard.state.data.usernameChannel = ctx.message.text;
      ctx.reply('Добавьте этого бота в администраторы вашего канала и нажмите "Готово". Подробности смотрите в инструкции выше',
      Markup.inlineKeyboard([
        Markup.callbackButton('Готово', 'next'),
    ]).extra());
      return ctx.wizard.next();
    },
    ctx => {
      telegram.getChatAdministrators(ctx.wizard.state.data.usernameChannel).then((chatAdministrators) => {
        telegram.getMe().then(value => {   
          for (let item of chatAdministrators) {
            if(item.user.username == value.username){
              if(item.status == 'administrator') {
                return ctx.wizard.next();
              }
            }
          }
        });
  
      }, (error) => {
        ctx.reply('Вы не добавили бота в администраторы, попробуйте снова или смотрите инструкцию выше', Markup.inlineKeyboard([
          Markup.callbackButton('Готово', 'next'),
      ]).extra());
      });
    },
    ctx => {
      ctx.reply('Отлично, вы на верном пути. Теперь укажите тематику вашего сообщетсва.\n\nПримечание: Рекламодатели будут искать вас по вашей тематике, поэтому внимательно отнеситесь к этому шагу.\n\nЕсли не нашли свою тематику в списке, нажмите "другое" и введите название вашей тематики\n\nЕсли появились вопросы, посмотрите инструкцию выше');
    }
);

module.exports = channelAddWizard;
`

![2020-03-31_06-30-05](https://user-images.githubusercontent.com/59447183/77959209-8e7aa380-7319-11ea-9c05-11376c271060.png)

**Comment by DenRamus** [comment]
What is the problem and how to solve it?

**Comment by dotcypress** [comment]
@DenRamus yes, because you move `getChatAdministrators ` to the next step 😃 

I don't recommend using `WizardScene` without a deep understanding of how middlewares and [scenes](https://en.wikipedia.org/wiki/FSM) work.  But you can easily recreate logic with a bunch of `BaseSene's`.
