### ISSUE TITLE
Custom middleware not working as expected

### ISSUE THREAD

**Issue by expelliamus** [telegraf/telegraf#962]
I have created the following middleware:

     module.exports = function () {
        return (ctx, next) => {
            ctx.deleteMessage();
            console.log(ctx.updateSubTypes[0])

            return next()
                .then()
                .catch((err) => {
                    console.log(err);
                    throw err
                })
        }
    }

I added the middleware as follow:

     const memberMiddleware = require('../middlewares/member');
     bot.use(memberMiddleware());

now the middleware remove the message "user x has joined the group" when a new user join the group, this works only for the event new_chat_members, when the user leave nothing happens.

If instead I do:  `bot.on('message', (ctx) => { console.log(ctx.updateSubTypes[0])) })`

I also get the event left_chat_member, what I did wrong?

**Comment by Piterden** [comment]
Probably you should bind middleware handler to the events you want to handle?

**Comment by sfanculatodinotte** [comment]
Hi @Piterden thanks for the answer, I'm not really sure if I understood what do you mean, could you please write a little example?

**Comment by sfanculatodinotte** [comment]
@Piterden  Another weird thing is that if I do:

    this.bot.on(['new_chat_members', 'left_chat_member'], (ctx) =>{
            console.log(ctx.updateType)
            console.log(ctx.updateSubTypes)
        })

I can see:

    message
    [ 'new_chat_members' ] 
    message
   [ 'left_chat_member' ]

so why my middleware is not working?

**Comment by sfanculatodinotte** [comment]
@Piterden I also tried with this:

    module.exports = function () {

        return (ctx, next) => {

            // Rimuove i messaggi di servizio inclusi nell'array
            let unwantedMessages = ['new_chat_members', 'left_chat_member', 'new_chat_title'];
            let isUnwanted = unwantedMessages.some(x => ctx.updateSubTypes.includes(x));

            if (isUnwanted) {
                ctx.deleteMessage();
                console.log(isUnwanted);
            }

            return next(ctx);
        }
    }

then binding:

    const messageMiddleware = require('../middlewares/message');
    this.bot.use(messageMiddleware());

and the left event isn't working

**Comment by sfanculatodinotte** [comment]
I opened a ticket here: https://stackoverflow.com/questions/61043940/left-chat-member-not-invoked

**Comment by KnorpelSenf** [comment]
Has an answer here: https://stackoverflow.com/a/61178216/4453823
