### ISSUE TITLE
How to create menus like this?

### ISSUE THREAD

**Issue by HouCoder** [telegraf/telegraf#963]
What's the name of this menu and how to create it with telegraf? any code example? thanks.

![image](https://user-images.githubusercontent.com/5292143/78454764-a9a83300-76cc-11ea-9351-43123df9d5fc.png)

**Comment by sfanculatodinotte** [comment]
Hi @HouCoder 

this menu is called `inlineKeyboard` and can be created as follows:

    const { Markup } = require('telegraf');

    ctx.replyWithMarkdown(
        'Select an option: ',
        Markup.inlineKeyboard([
            Markup.callbackButton('Send a message', 'message-add'),
            Markup.callbackButton('Message list', 'message-list')
        ], { columns: 1 }).extra()

you can also define how many columns should have, if you take as example the image you posted, then: `{ columns: 3 }`, more on [Telegram documentation](https://core.telegram.org/bots/api#inlinekeyboardmarkup)

**Comment by HouCoder** [comment]
Many thanks @sfanculatodinotte
