### ISSUE TITLE
TypeError: ctx.unbanChatMember is not a function

### ISSUE THREAD

**Issue by thedevxen** [telegraf/telegraf#966]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: ^3.37.0
* Node.js Version: 13.6.0
* Operating System: macOS High Seirra 

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

It returns an error `TypeError: ctx.unbanChatMember is not a function` whenever I run that function. VS Code shows it's a function but in the console, it shows it's undefined.
 
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Just run, `ctx.unbanChatMember();`

**Comment by expelliamus** [comment]
try to use `ctx.telegram.unbanChatMember(chatId)`
