### ISSUE TITLE
Forward message from private users to Admin

### ISSUE THREAD

**Issue by bishowb** [telegraf/telegraf#968]
Hello i want to forward  message from private user who are talking with bot to admin. How can i do that?
I found this on telegraf.js but dont know how to implent 
`telegram.forwardMessage(chatId, fromChatId, messageId, [extra]) => Promise`

**Comment by YouTwitFace** [comment]
It might be easier to get answers in [the Telegraf community group on telegram](https://t.me/TelegrafJSChat).

**Comment by EdJoPaTo** [comment]
You can use the ctx object on the specific message you want to forward. Then just  supply the message id that should receive the message. It basically does the second and third parameter for you when using the ctx.

```js
bot.on('message', async ctx => {
  await ctx.forwardMessage(adminUserId)
})
```
