### ISSUE TITLE
`replyWithPoll` options not available in TypeScript

### ISSUE THREAD

**Issue by rhlsthrm** [telegraf/telegraf#970]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version:
* Node.js Version:
* Operating System:

## Expected Behavior

`replyWithPoll` option available on ctx object.

## Current Behavior

Copying [example](https://github.com/telegraf/telegraf/blob/master/docs/examples/poll-bot.js) errors when trying to run with Typescript.

### Steps to Reproduce

1. Create bot
```ts
import Telegraf, { Extra } from "telegraf";

bot.start((ctx) => ctx.reply("Welcome"));
bot.command('poll', (ctx) =>
  ctx.replyWithPoll(
    'Your favorite math constant',
    ['x', 'e', 'π', 'φ', 'γ'],
    { is_anonymous: false }
  )
)
bot
  .launch()
  .then(() => console.log("Bot Started!"))
  .catch((e) => console.error("Uh oh, bot didn't start: ", e.toString()));
```

2. Run bot
`$ ts-node src/bot.ts`

### Failure Logs
```
TSError: ⨯ Unable to compile TypeScript:
src/bot.ts:44:7 - error TS2551: Property 'replyWithPoll' does not exist on type 'ContextMessageUpdate'. Did you mean 'replyWithPhoto'?

44   ctx.replyWithPoll(
         ~~~~~~~~~~~~~

  node_modules/telegraf/typings/index.d.ts:260:3
    260   replyWithPhoto(photo: tt.InputFile, extra?: tt.ExtraPhoto): Promise<tt.MessagePhoto>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'replyWithPhoto' is declared here.
```

**Comment by rhlsthrm** [comment]
Looks like I can `require` and it works, so the typings are probably just wrong.

**Comment by wojpawlik** [comment]
Related missing typings:
- `Telegraf::replyWithQuiz`,
- `Telegraf::stopPoll`,
- `Telegram::sendPoll`,
- `Telegram::sendQuiz`,
- `Telegram::stopPoll`
