### ISSUE TITLE
Sending multiple messages in a row

### ISSUE THREAD

**Issue by paulbraam** [telegraf/telegraf#971]
Hi,

I'm quite new to JS and telegram bot development.

I would like to get my bot to work this way:
Once a user sends a command, the bot sends back a set of messages including audio and images. The user gets one set of messages daily.

My question is what is the best approach to send multiple messages?

I tried this way so far:

```
bot.command("test", (ctx) => {
  bot.telegram.sendMessage(ctx.chat.id, "Hey there!")
  .then(function () {
    bot.telegram.sendMessage(ctx.chat.id, "I'm John")
  }).then(function () {
    bot.telegram.sendMessage(ctx.chat.id, "Nice to meet you")
  }).then(function () {
    bot.telegram.sendAudio(ctx.chat.id, {source: 'src/audio.mp3'})
  })
})

```

Please let me know if it's gonna work this way or whether or not there are other more secure approaches to implement this.

Thanks!

**Comment by YouTwitFace** [comment]
You can either do it the way you shared, or you can use `async`/`await` which might make it a bit more readable.

P.S. we have an [unofficial Telegraf community on Telegram](https://t.me/TelegrafJSChat).

**Comment by BRA1L0R** [comment]
i mean, yeah, but the issues section is not the right place to ask this kind of question. It should work btw

**Comment by LetItCode** [comment]
`({ reply }) => Promise.all([reply('parallel oneline'), reply('without'), reply('order')])`
