### ISSUE TITLE
Is there a way to prevent bot being added to any group or channel?

### ISSUE THREAD

**Issue by expelliamus** [telegraf/telegraf#974]
I would like to keep my bot private, I don't want that my bot is being added to other groups or channels, is there a way to do this?

**Comment by YouTwitFace** [comment]
You can do using [@BotFather](https://t.me/BotFather):

/setjoingroups — toggle whether your bot can be added to groups or not. Any bot must be able to process private messages, but if your bot was not designed to work in groups, you can disable this.

**Comment by expelliamus** [comment]
@YouTwitFace my bot is designed to work in groups, but I would like to keep the bot private just for my group not for groups which are not mine

**Comment by YouTwitFace** [comment]
You can either add it to your group and then change the settings in BotFather, or you can have a handler for `new_chat_member` and leave if the bot was added.

P.S. we have an [unofficial Telegraf community on Telegram](https://t.me/TelegrafJSChat).

**Comment by LetItCode** [comment]
You can check and leave from other chats
