### ISSUE TITLE
Disable website preview + Markdown

### ISSUE THREAD

**Issue by dducted** [telegraf/telegraf#975]
I was wondering how I can set disable website preview as well as markdown. So far I tried:

`ctx.editMessageText(config.testCommandText, Extra.markdown(), Extra.webPreview(false))`

**Comment by YouTwitFace** [comment]
It would be nice if you shared your solution in case anyone else in the future has the same problem.

**Comment by ne0c0de** [comment]
This is makes the magic @AndrewLaneX 
```telegram.sendMessage(12345, '[Google](https://google.com)', { parse_mode: 'Markdown', disable_web_page_preview: true })```

**Comment by mertoenjosh** [comment]
> This is makes the magic @AndrewLaneX
> `telegram.sendMessage(12345, '[Google](https://google.com)', { parse_mode: 'Markdown', disable_web_page_preview: true })`

this worked for me 👍🏽
