### ISSUE TITLE
no Telegraf.phone and telegraf.phone

### ISSUE THREAD

**Issue by zvshka** [telegraf/telegraf#976]
* Telegraf.js 3.37.0:
* Node.js 12.14.1:
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/39166475/79070621-c30a3a00-7cdf-11ea-8921-388cabb6ef10.png)

**Comment by zvshka** [comment]
![image](https://user-images.githubusercontent.com/39166475/79070645-e59c5300-7cdf-11ea-8edc-55e612b15770.png)

**Comment by LetItCode** [comment]
And phone.telegraf() too. Wanna call to bot?

**Comment by zvshka** [comment]
![image](https://user-images.githubusercontent.com/39166475/79078659-79871280-7d12-11ea-84cd-59ed37af1678.png)

**Comment by YouTwitFace** [comment]
[`Telegraf::phone`](https://github.com/telegraf/telegraf/blob/646476197d2c6b7e02bea0ba6a9f03da67ac2809/composer.js#L221-L223) exists but probably doesn't have any types.

Related PR: #960

**Comment by zvshka** [comment]
Thank you
