### ISSUE TITLE
How to handle simple keyboard callback

### ISSUE THREAD

**Issue by Dimabytes** [telegraf/telegraf#978]
When I use this:

```
const mainMenuKeyboard = Markup.keyboard([
  Markup.callbackButton('Add', 'addAddress'),
  Markup.callbackButton('Go', 'start_order')
  ]).resize().extra();
```

I need to use this code to handle it:

`bot.hears('Add',(ctx) => ctx.scene.enter("addAddress"));`

and cant catch nothing with 'action'

But when I use this:

```
export const mainMenuKeyboard = Markup.inlineKeyboard([
  Markup.callbackButton('Add', 'addAddress'),
  Markup.callbackButton('Go', 'start_order')
  ]).resize().extra();
```

I can handle it like this:

`bot.action('addAddress',(ctx) => ctx.scene.enter("addAddress"));`

What the difference?
And second one what the difference between use Markup and Extra.markup ?

**Comment by EdJoPaTo** [comment]
`bot.hears()` looks on messages (`ctx.message.text`).
A keyboard returns no messages. When the user hits a button it returns a callbackQuery with data.
`bot.action` checks this data (`ctx.callbackQuery.data`)

`Extra` are addition arguments for methods.
Sometimes you have `Markup` as part of your Extra.
Markup can be created with `Markup` like `Markup.inlineKeyboard()` and is added to the Extra object with `Extra.markup(myMarkup)`
