### ISSUE TITLE
Integration with firebase?

### ISSUE THREAD

**Issue by nicolassrod** [telegraf/telegraf#98]
Is it possible to use it with firebase functions ?, would be great.

**Comment by dotcypress** [comment]
Hey.

Hopefully yes with some modification, but anyway i will do some research.

**Comment by bostrot** [comment]
@nicolassrod it is. See the Firebase documentation about it here: https://firebase.google.com/docs/admin/setup

**Comment by dotcypress** [comment]
@nicolassrod @bostrot i did it 😎 

```js
const Telegraf = require('telegraf')
const functions = require('firebase-functions')

// Yeah, you don't need Bot token for following example, 
// cause Telegraf will use webhook request as transport.
const bot = new Telegraf()

// Or you can store token in firebase config 
const bot = new Telegraf(functions.config().bot.token)

bot.command('/start', (ctx) => ctx.reply('Hello'))
bot.hears('yo', ({ reply }) => reply('Yo'))

exports.bot = functions.https.onRequest(
  (req, res) => bot.handleUpdate(req.body, res)
)
// After deploy, just call `setWebhook` manually with function url.
```

**Comment by ButuzGOL** [comment]
// After deploy, just call `setWebhook` manually with function url.
cant find method ?

**Comment by ailinykh** [comment]
@ButuzGOL you can set a webhook via simple GET request
```shell
curl https://api.telegram.org/bot{BOT_TOKEN}/setWebhook\?url\={FIREBASE_FUNCTION_URL}
// {"ok":true,"result":true,"description":"Webhook was set"}
```

or via API
```javascript
bot.telegram.setWebhook(FIREBASE_FUNCTION_URL);
```

**Comment by ailinykh** [comment]
> @nicolassrod @bostrot i did it 😎
> 
> ```js
> const Telegraf = require('telegraf')
> const functions = require('firebase-functions')
> 
> // Yeah, you don't need Bot token for following example, 
> // cause Telegraf will reply while sending an answer to the webhook.
> const bot = new Telegraf()
> 
> // Or you can store token in firebase config 
> const bot = new Telegraf(functions.config().bot.token)
> 
> bot.command('/start', (ctx) => ctx.reply('Hello'))
> bot.hears('yo', ({ reply }) => reply('Yo'))
> 
> exports.bot = functions.https.onRequest(
>   (req, res) => bot.handleUpdate(req.body, res)
> )
> // After deploy, just call `setWebhook` manually with function url.
> ```

That is a really great example, thanks you so much, but there is a little problem with unhandled requests. For example firebase could send an [audit log](https://cloud.google.com/logging/docs/audit/understanding-audit-logs) to your function and bot wont be able to reply to that request, or some users can experiment with undocumented command invocations which your bot can't handle with

In that case you having log like that
```
Function execution took 60009 ms, finished with status: 'timeout'
```
to avoid this you have to response is all cases:
```js
exports.bot = functions.https.onRequest(
  (req, res) => bot.handleUpdate(req.body, res).then( rv => !rv && res.sendStatus(200))
)
```

**Comment by Acex187x** [comment]
I began to make a complex bot with firebase, which uses scenes and session state but firebase makes it very slow and unpredictable 🙁. I am planning to make session storage in firestore but I guess it will be quite difficult to do.

**Comment by weijinnx** [comment]
> > @nicolassrod @bostrot i did it 😎
> > ```js
> > const Telegraf = require('telegraf')
> > const functions = require('firebase-functions')
> > 
> > // Yeah, you don't need Bot token for following example, 
> > // cause Telegraf will reply while sending an answer to the webhook.
> > const bot = new Telegraf()
> > 
> > // Or you can store token in firebase config 
> > const bot = new Telegraf(functions.config().bot.token)
> > 
> > bot.command('/start', (ctx) => ctx.reply('Hello'))
> > bot.hears('yo', ({ reply }) => reply('Yo'))
> > 
> > exports.bot = functions.https.onRequest(
> >   (req, res) => bot.handleUpdate(req.body, res)
> > )
> > // After deploy, just call `setWebhook` manually with function url.
> > ```
> 
> That is a really great example, thanks you so much, but there is a little problem with unhandled requests. For example firebase could send an [audit log](https://cloud.google.com/logging/docs/audit/understanding-audit-logs) to your function and bot wont be able to reply to that request, or some users can experiment with undocumented command invocations which your bot can't handle with
> 
> In that case you having log like that
> 
> ```
> Function execution took 60009 ms, finished with status: 'timeout'
> ```
> 
> to avoid this you have to response is all cases:
> 
> ```js
> exports.bot = functions.https.onRequest(
>   (req, res) => bot.handleUpdate(req.body, res).then( rv => !rv && res.sendStatus(200))
> )
> ```

I used, but every request have timeout problem...

```js
exports.bot = functions.https.onRequest(
  (req, res) => bot.handleUpdate(req.body, res).then( rv => !rv && res.sendStatus(200))
)
```

What do you think?

**Comment by weijinnx** [comment]
@ailinykh I'm using Telegraf + Firebase + Firestore (as DB). Seems like this timeout problem is as you said but your code didn't help me :(

**Comment by weijinnx** [comment]
Hey there! @ailinykh helped me with the problem, thanks!
And I want to tell you what could be wrong and how you can fix that.

So, in my case, it was a conflict of how I try to get updates. Firstly, you need to make sure, that you **DON'T** use `bot.launch()` with the firebase functions handler. In my case it was like:

```js
bot.launch();

exports.bot = functions
  .region('europe-west1')
  .https.onRequest((req, res) =>
    bot.handleUpdate(req.body, res).then((rv) => !rv && res.sendStatus(200)),
);
```

When I commented `bot.launch()` timeouts are gone away. Because `launch` starts long polling and when it starts your webhook will be cleared. Also, I wanted to add to use firebase tools instead of just `node index.js` or `nodemon index.js`.

Now, I'm using:

`firebase emulators:start --only functions,firestore`

to serve just functions and emulate Firestore on your local environment. Good luck!

**Comment by Alynva** [comment]
@weijinnx then how do you set the webhook?

**Comment by ailinykh** [comment]
@Alynva the first message would be sent as a response to telegram. The rest messages you have to send via [bot API](https://core.telegram.org/bots/api#making-requests)
