### ISSUE TITLE
How to send WAV file?

### ISSUE THREAD

**Issue by luluhoc** [telegraf/telegraf#982]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: Latest
* Node.js Version: v13.11.0
* Operating System: Win10

I'm trying to send a 55mb WAV file, but I keep getting Error: 413: Request Entity Too Large.

Trace
```
(node:4552) UnhandledPromiseRejectionWarning: Error: 413: Request Entity Too Large
    at C:\Users\lulu\Desktop\botHHL\node_modules\telegraf\core\network\client.js:281:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I tried 
```
ctx.replyWithAudio({
                source: element,
              });
```
and 
```
ctx.replyWithDocument({
                source: element,
              });
```

**Comment by LetItCode** [comment]
Bots can currently send files of any type of up to 50 MB in size

https://core.telegram.org/bots/faq#handling-media
