### ISSUE TITLE
Bad Request: REPLY_MARKUP_GAME_EMPTY

### ISSUE THREAD

**Issue by ArturAralin** [telegraf/telegraf#985]
## Context

I was trying to send inline buttons with a game, instead I got bad request, but I can't understand reasons

* Telegraf.js Version: ^3.37.0
* Node.js Version: v12.16.1
* Operating System: Mac OS X 10.15.2

## Expected Behavior

I expect to get custom button instead of default "Play <game_name>"

## Code

```javascript
await bot.telegram.sendGame(ctx.update.message.chat.id, GAME_NAME, {
    reply_markup: JSON.stringify({
      inline_keyboard: [
        [
          { text: 'my button', url: APP_HOST }
        ]
      ]
    })
  });
```

**Comment by dotcypress** [comment]
@ArturAralin this is a [BOT API restriction](https://core.telegram.org/bots/api#sendgame)

> A JSON-serialized object for an inline keyboard. If empty, one ‘Play game_title’ button will be shown. If not empty, the first button must launch the game.

**Comment by HaykMarkosyan** [comment]
![image](https://user-images.githubusercontent.com/77397812/141056870-1004855e-6dc1-4ec0-8bf6-ca414e490aa1.png)

![image](https://user-images.githubusercontent.com/77397812/141057140-0fbfffcb-5cda-450d-87cf-d00aa18d6568.png)
you should add you options object in [option]

![image](https://user-images.githubusercontent.com/77397812/141057679-e51dd272-a2a2-40a0-835a-0aad463b4cc0.png)
