### ISSUE TITLE
Bot acts different from Telegram Doc

### ISSUE THREAD

**Issue by theMasix** [telegraf/telegraf#986]
## Context

* Telegraf.js Version: 3.37
* Node.js Version: 13.13
* Operating System: Ubuntu 19.10

## Expected Behavior

In the Telegraf documentation in [Doc](https://telegraf.js.org/#/?id=sendaudio) says that the extra parameter can be whatever that official telegram doc has said! So I can be able to send something to bot:
```
ctx.replyWithAudio(downloadLink, {
        title: mytitle,
        caption: `this is a caption`,
});
```
because the telegram accept title and caption property.

## Current Behavior

But the bot doesn't send title and if I wanna have title I can write something like:
```
ctx.replyWithAudio({
        url: downloadLink,
        filename: myFileName,
 });
```
Which there is not in the Telegraf Doc even! (url and filename property...)
In this case the caption property won't work too!

## Failure Information (for bugs)

There isn't any log or something that I can show you!

**Comment by jassler** [comment]
Tried sending a request directly in the browser through

```
https://api.telegram.org/bot<your_token>/sendAudio?chat_id=<your_id>&audio=https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3&title=othertitle
```

It didn't change the title for me either, nor did it alter any of the file's meta tags. This might be a problem on Telegram's side.

**Comment by theMasix** [comment]
@jassler So how we could send title, as well as description(caption) for an audio?

**Comment by jassler** [comment]
I contacted BotSupport, hopefully they come back to me.

Otherwise, your best bet for now is to

- Download the audio (if necessary)
- Change the title locally
- Upload the new file
