### ISSUE TITLE
How to delete .on("message", ...)

### ISSUE THREAD

**Issue by zvshka** [telegraf/telegraf#995]
Is it possible to delete .on("message", ...)?

**Comment by zvshka** [comment]
So when you declare Telegraf.on("message", (ctx) => ...) or like that, its work everytime, when event emits, but i want to stop it or delete after some actions. So im trying to create message collector like(no) in discord.js

**Comment by eeWynell** [comment]
Hi
I can't think of exactly how to remove the event handler, but I've come up with a slightly different solution that might help you:
Add the _if_ condition to your handler (which means that depending on some variable value, your code will be executed or not). It can be a global variable or a _ctx.session_ (don't forget to require _Telegraf/session_ first) property. This solution can be more useful sometimes, for example, when you want to re-add this handler, you don't need to use it _.on("message" ,...)_ again and just set the variable value to _true_

**Comment by zvshka** [comment]
So yeah, thank you, i though about it

**Comment by zvshka** [comment]
Right now i have system like this: on message event => Handler.message(ctx) => if (database.get(ctx.chat.id)) {some code} and also on command ... event => Handler.set(ctx.chat.id) => database.set(ctx.chat.id, true)

**Comment by eeWynell** [comment]
If this variable is individual for each user then you can use the _telegraf/session_ module, by the way

**Comment by KnorpelSenf** [comment]
Looks solved to me. Also confer the branching middleware in `composer.ts`, even though I think it is currently not documented yet.
