### ISSUE TITLE
Session is undefined inside callback query handler of callback data coming from an inline keyboard inside inline query result 

### ISSUE THREAD

**Issue by awesomelike** [telegraf/telegraf#996]
* Telegraf.js Version: 3.37.0
* Node.js Version: 12.16.2
* Operating System: Windows 10

I have an inline query, where it has reply_markup inline_keyboards after choosing one of the results. 
```
const results = data.map(({ id, title, price }) => ({
    id,
    type: 'article',
    title,

    // other parameters

    reply_markup: {
      inline_keyboard: [
        [{
          text: 'Buy',
          callback_data: JSON.stringify({
            action: 'buy',
            drugId: id,
          }),
        }],
      ],
    },
  }));
ctx.answerInlineQuery(results, { cache_time: 0 });
```
And I have a callbackQuery handler:
```
bot.on('callback_query', (ctx) => {
    const data = JSON.parse(ctx.callbackQuery.data);
    switch(data.action) {
        case 'buy': {
           console.log(ctx.session); //Here this statement prints undefined, (session is lost)
        }
}
});
```
`ctx.session` is working normally for other values of callback_data. But as you can see it is not working for a callback_data which is coming from inline_query.

I am using Redis for session, and using the recommended `getSessionKey()` method as shown in the docs:
```
{
  getSessionKey: (ctx) => {
    if (ctx.from && ctx.chat) {
      return `${ctx.from.id}:${ctx.chat.id}`
    } else if (ctx.from && ctx.inlineQuery) {
      return `${ctx.from.id}:${ctx.from.id}`
    }
    return null
  }
}
```
Are there any mistakes in my code or is it normal for the session to be lost when used with inline query's callback_data?

**Comment by Piterden** [comment]
I use like this:
```js
bot.use(session({
  property: 'game',
  getSessionKey: (ctx) => (ctx.callbackQuery && ctx.callbackQuery.inline_message_id) ||
    (ctx.from && ctx.chat && `${ctx.from.id}:${ctx.chat.id}`),
}))
```
https://github.com/Piterden/chessbot/blob/master/src/index.js#L35-L39

**Comment by awesomelike** [comment]
> I use like this:
> 
> ```js
> bot.use(session({
>   property: 'game',
>   getSessionKey: (ctx) => (ctx.callbackQuery && ctx.callbackQuery.inline_message_id) ||
>     (ctx.from && ctx.chat && `${ctx.from.id}:${ctx.chat.id}`),
> }))
> ```
> 
> https://github.com/Piterden/chessbot/blob/master/src/index.js#L35-L39

Thanks, for your answer, now it is not undefined. But, now `ctx.session` is an empty object (still losing data).
