### ISSUE TITLE
Error "TypeError: Telegraf is not a constructor"

### ISSUE THREAD

**Issue by tushar-compro** [telegraf/telegraf#998]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.37.0
* Node.js Version: 8.11.2
* Operating System: Win 10

## Expected Behavior

Please describe the behavior you are expecting
It should connect the server with Telegram Bot

## Current Behavior

What is the current behavior?
Used example code from telegraf github page
import { Telegraf } from 'telegraf';

const bot = new Telegraf(<Token>);
bot.start((ctx) => ctx.reply('Welcome!'));
bot.help((ctx) => ctx.reply('Send me a sticker'));
bot.on('sticker', (ctx) => ctx.reply('👍'));
bot.hears('hi', (ctx) => ctx.reply('Hey there'));
bot.launch(); 

It says "TypeError: Telegraf is not a constructor"

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Make a node application using "npm init";
2. In the index js paste the example code as mentioned above.
3. Use node command "node index.js"

### Failure Logs

Please include any relevant log snippets or files here.
TypeError: Telegraf is not a constructor
    at Object.<anonymous> (F:\ex-app\index.js:3:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by ColCh** [comment]
Telegraf is default export, just try to use this snippet

```
const bot = new Telegraf();
bot.start((ctx) => ctx.reply('Welcome!'));
bot.help((ctx) => ctx.reply('Send me a sticker'));
bot.on('sticker', (ctx) => ctx.reply('👍'));
bot.hears('hi', (ctx) => ctx.reply('Hey there'));
bot.launch();

```

but may be documentation should be updated

**Comment by dotcypress** [comment]
@tushar-compro `import { Telegraf } from 'telegraf';` introduced in Telegraf version `3.38.0`, you can either update version or use `import Telegraf from 'telegraf';`

**Comment by Eyu27** [comment]
replacing      const Telegraf = require('telegraf') to     const { Telegraf } = require('telegraf') might help
